### PR TITLE
fix(applicationset): support webhook with matrix interpolation (#9931)

### LINKED ISSUE #9931: Applicationset not refreshed after webhook event using matrix generator when using matrix generator references
@KojoRising @crenshaw-dev @sboschman

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It appears that the changes from #8998 are not compatible with the work done in #9080. This has been confirmed by the author of #8998

> @ejhayes , can you please open a new issue for this? This PR was merged before the implementation of the new feat of #9080. I had a quick glance at the code, and you are correct in your assumption that the webhook logic has not been updated to include the new #9080 feature.

**To Reproduce**

For example if I create an application set like this   and setup a webhook for pull requests they will not be refreshed when pull request events happen.
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appbundle-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: https
            github: 
              organization: SOME_ORG
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^argocd-test
        - pullRequest:
            github:
              owner: '{{ organization }}'
              repo: '{{ repository }}'
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
  template:
...
```

**Expected behavior**

However if I do not attempt to use `{{organization}}` and `{{repository}}` in the pull request generator then everything works as expected:

```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appbundle-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: https
            github: 
              organization: SOME_ORG
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^argocd-test
        - pullRequest:
            github:
              owner: 'SOME_ORG'
              repo: 'SOME_REPO'
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
  template:
...
```

I suspect there may be an issue with using the interpolated values that is causing the webhook event to be discarded.

### PR DESCRIPTION
**Pull request by sboschman**
Moved the webhook code to its own 'webhook' package, otherwise go ends up in a cyclic dependency error.

fixes #9931 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@sboschman can you resolve the conflicts?

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@sboschman can you describe (or add as comments) what the changes in `shouldRefreshMatrixGenerator` do? I need to read this more in-depth, but I think a quick description will help a lot.  :-) 

I'm a little worried that the temporary generators don't include matrix and merge generators. Is this solution expected to work with nested matrix generators, or matrix generators that contain nested merge generators?

**Comment by sboschman** [comment]
> I'm a little worried that the temporary generators don't include matrix and merge generators. Is this solution expected to work with nested matrix generators, or matrix generators that contain nested merge generators?

No not expected in its current form, as for some reason I was under the impression nesting those two generators was not allowed. After checking the docs again, I see you are allowed to nest them just once. So, will have to do some changes to support that.

**Comment by sboschman** [comment]
Even before interpolation the webhook code didn't support nested matrix/merge generators. Do we silently fix this as part of the interpolation fix, or do you want me to open a new issue for changelog purposes @crenshaw-dev ?

Talking about changelog, should this fix be added to the changelog or not? As it fixes something that is not yet released, the interpolation feat is part of the upcoming 2.5 release... Might be a bit strange to have fixes in the changelog for 2.5 release for features introduced in that same 2.5 release?

**Comment by crenshaw-dev** [comment]
> Even before interpolation the webhook code didn't support nested matrix/merge generators. Do we silently fix this as part of the interpolation fix, or do you want me to open a new issue for changelog purposes @crenshaw-dev ?

I'm okay with just adding the support here, rather than with a new issue.

> Talking about changelog, should this fix be added to the changelog or not? As it fixes something that is not yet released, the interpolation feat is part of the upcoming 2.5 release... Might be a bit strange to have fixes in the changelog for 2.5 release for features introduced in that same 2.5 release?

I think it's fine to include in the changelog. Folks will probably mostly look at the "features" section. Might be a little surprised to see this in the "bug fixes" section, but I don't think that will be a huge problem.

**Review by crenshaw-dev — APPROVED** [review]
Fantastic. Thanks @sboschman!

**Pull request merged**
