### PR TITLE
fix: button consistency in logs panel #9945

### LINKED ISSUE #9945: Button behavior is very inconsistent
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?view=tree&resource=name%3Aargocd-redis-ha-server%2Cname%3Aargocd-redis-ha-server-0&node=%2FPod%2Fargocd%2Fargocd-redis-ha-server-0%2F0&tab=logs&page=0&untilTimes=
2. See the button bar above the logs
3. There's a 📋 button for "Copy logs"
    image
4. Hovering over it shifts all the buttons to the right
    image
5. Clicking it replaces the icon with ✔️ and makes the button even bigger (shifting things more)
    image
6. Hover over the ⬇️  download button
    image
7. Clicking actually makes it smaller:
    image
8. Hover over the 🥞 containers icon
    image
9. Click it, the button grows and things shift right
    image
10. Hover over the ➡️ follow button (note that hover doesn't impact width/height):
    image
 11. Click and note that this changes the button to ➡️✔️ (making it much wider):
    image
12. Look at the ¶ wrap lines button:
    image
13. Hover over it
    image
14. Click it (note that it shrinks)
image
15. Hover over ⏪ previous logs

   image

16. Click it
    image
17. Note that it becomes ⏪ ✔️ 
    image
18. Hover over 🌙 
    image
19. Click it and note it highlights
    image
20. It becomes a 🌞 (highlighted -- this is ok)
    image
21. Hover over 🕔 show timestamps
    image
22. Click it and note that it grows
    image
23. And inverts
    image
24. Click the ↗️ Fullscreen view
    image
25. Close the popped out view
26. Click the ❗ negation (note that it's really hard to understand the state of these things)
    image
27. The button grows... 
28. And shrinks
    image

**Expected behavior**

1. Buttons shouldn't change dimensions -- neither when hovered nor clicked
2. Buttons shouldn't gain a ✔️ item -- they can either use a color-depressed state or a different icon
3. The 📋, ⬇️, and ↗️ items should be grouped together and not part of the same bar/button behavior as the others as they aren't acting on the content below
4. The `Filter string` text should change to `Filter out string` when appropriate

**Screenshots**

image

https://user-images.githubusercontent.com/2119212/178348902-5ff05ae6-ed85-43d6-b7b3-365b804e2658.mov

**Version**

```shell
{
    "Version": "v2.4.0+af7d970",
    "BuildDate": "2022-07-11T16:14:05Z",
    "GitCommit": "af7d97076c3bcce322288dac353eed361468c589",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.5 2022-05-20T20:25:40Z",
    "HelmVersion": "v3.9.0+g7ceeda6",
    "KubectlVersion": "v0.23.1",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by Marvin9**
Fixes #9945 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks, @Marvin9!

What if, instead of darkening the "active" buttons and adding a small green checkmark, we just added a proper square checkbox to the left of each icon (inside the button) which will become checked when activated.

That would allow these boxes to remain "bright" (not confusing them with the darker "action" buttons) and very clearly mark them as either active or inactive.

**Comment by Marvin9** [comment]
Thanks for the suggestion @crenshaw-dev. I will change the design

**Comment by Marvin9** [comment]
With new changes

https://user-images.githubusercontent.com/17699717/180642781-1f7a7334-f36c-49f3-8977-0b394ffcdb10.mov

**Comment by crenshaw-dev** [comment]
I like it! Will wait for UI folks to weigh in.  :-)

**Comment by Marvin9** [comment]
Thanks @crenshaw-dev. Can you please mention here who should review and approve?

**Comment by crenshaw-dev** [comment]
Added @rbreeze as a review. Remington, feel free to punt to another UI-capable person.  :-)

**Review by rbreeze — CHANGES_REQUESTED** [review]
I think the consistency improvements are great, and agree that each button should have consistent behavior and a fixed width. This feels like a big improvement already, but I see 2 different options that could make it look even better:

1. All buttons, even the ones with checkboxes, should be the same dark color

OR 

2. We remove the checkbox paradigm from all buttons. Buttons that can be enabled / disabled would be hollow when disabled and filled in when enabled. 

Option 1 is more explicit and a smaller change to the current state of this PR. Personally I think Option 2 would look cleaner, but may be more confusing. @alexec or @alexmt do you have an opinion here?

**Comment by Marvin9** [comment]
Thanks for the suggestion @rbreeze. The reason to avoid dark colour for toggles is that it confuses with static dark buttons (eg. copy, download). As soon as both groups have same color (darker one), they seem to loose the context, unless they have checkbox. Let me know what you think on it.

**Review by rbreeze — APPROVED** [review]

**Comment by jsoref** [comment]
Fwiw, I agree that option 2 is slightly better, but I'm happy with the current improvement over the previous state.

**Pull request merged**
