### PR TITLE
fix(ui): adjust transform origin in application-resource-tree component

### LINKED ISSUE #19519: Floating view toolbar covers cloud and first two resource boxes in Network View
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When entering network mode, sometimes resource boxes are covered by the view toolbar.

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications/argo-cd?view=network&resource=
2. Zoom out until the view toolbar covers a resource box

**Expected behavior**

A way for the view toolbar to not obscure resource boxes

**Screenshots**

image

**Version**

```shell
{
    "Version": "v2.11.0+1cffa15",
    "BuildDate": "2024-04-18T08:51:13Z",
    "GitCommit": "1cffa15f0ddecbc241d572e316ea20920fdfdb65",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.9",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

### PR DESCRIPTION
**Pull request by srikanth597**
Closes #19519

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by srikanth597** [comment]
Tested On a Regular device of 15-16 inches
image

**Review by nitishfy — CHANGES_REQUESTED** [review]
Please sign the commits.

**Comment by srikanth597** [comment]
Hi @nitishfy I am not sure if I have understood it correctly, but I have already signed the commits in the new PR, is that not correct?
image

**Comment by crenshaw-dev** [comment]
@srikanth597 the naming is unfortunate. "Signed commits" are cryptographically signed. "Signed-off commits" just have an extra bit of text on the commit message. You can check the details of the failed "DCO" check for instructions on how to sign off commits.

**Comment by nitishfy** [comment]
> Hi @nitishfy I am not sure if I have understood it correctly, but I have already signed the commits in the new PR, is that not correct? image

Simply ammend it using `git commit --amend --signoff` command

**Comment by srikanth597** [comment]
@nitishfy i have cleared the DCO check

**Review by nitishfy — APPROVED** [review]
LGTM!

**Comment by srikanth597** [comment]
@nitishfy PR is still OPEN, any action item on me ?
do i need to update branch

**Review by gdsoumya — APPROVED** [review]

**Review by christianh814 — COMMENTED** [review]
Thank you for this!

**Pull request merged**
