### PR TITLE
chore: Removed appset from core-installation

### LINKED ISSUE #9398: Remove applicationset controller from core-install.yaml
During merge of application set , it was included as a part of core installtion and i think it is not needed as core installtion is meant to install limited components of argo-cd

### PR DESCRIPTION
**Pull request by rishabh625**
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes  https://github.com/argoproj/argo-cd/issues/9398

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Hm. ApplicationSet is pretty light-weight. What's the reason for removing it from core?

**Comment by rishabh625** [comment]
> Hm. ApplicationSet is pretty light-weight. What's the reason for removing it from core?

core-install is meant for things that require minimal functionality to run argocd

and applicationset is not core to argocd , it's an addon that's why i thought to remove it.

**Comment by crenshaw-dev** [comment]
My personal feeling is that if no one is complaining about having the applicationset controller in core, we should just leave it.

**Comment by pdrastil** [comment]
Imho the applicationset is core functionality when you are using argocd to manage fleet of clusters.

**Comment by jannfis** [comment]
The reason for core is that it's being run headless, without API server and UI, and managed using Kubernetes API.

So, I think ApplicationSet should stay in core install.

**Pull request closed without merging**
