### PR TITLE
docs: update 2021 roadmap

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

PR updates roadmap with the next few month

### CODE REVIEW

**Comment by jannfis** [comment]
Why do we remove so many things from the roadmap?

**Comment by alexmt** [comment]
I've removed items that are done. But maybe I incorrectly understand what should be in roadmap document. Do you think it is better to keep completed items and mark them as done?

**Comment by jannfis** [comment]
> Do you think it is better to keep completed items and mark them as done?

I think that would visualize our progress, yes :)

**Comment by alexmt** [comment]
Thanks for the review @jannfis . Added completed items. Can you take a look one more time?

**Review by jannfis — APPROVED** [review]
LGTM, thank you

Sorry for the late reply, somehow this slipped through.

**Pull request merged**
