### PR TITLE
feat: metrics, argocd_app_info adding syncpolicy info, argocd_cluster_info adding clustername

### PR DESCRIPTION
**Pull request by wecger**
Checklist:

* [x] (c) Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Hi, 
this PR adds some new labels to the following metrics:
argocd_app_info: adding sync_automated, sync_prune, sync_selfheal label
argocd_cluster_info: adding clustername label

This allows the users more flexibility while creating dashboards etc. Now you can panels e.g. current sync states of applications with sync automated enabled.
Furthermore the clustername label should allow the users to use the given name for the clusters instead of the destination server URL.

### CODE REVIEW

**Comment by wecger** [comment]
remarks: 
- make lint wants to fix multiple files (outside of the edits I made). I did not add those edits to this PR to avoid confusion
- I did not find any test for the argocd_cluster_info yet?!

**Review by jannfis — APPROVED** [review]
LGTM. @jessesuen you might want to take another look since you recently reworked stuff in metrics.

**Comment by ermakov-oleg** [comment]
@jannfis  After merging this, the `argocd-application-controller` crashes with panic:

```
panic: inconsistent label cardinality

goroutine 2926 [running]:
github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
	/go/src/github.com/prometheus/client_golang/prometheus/value.go:98
github.com/argoproj/argo-cd/controller/metrics.(*clusterCollector).Collect(0xc00055ed80, 0xc001535f20)
	/go/src/github.com/argoproj/argo-cd/controller/metrics/clustercollector.go:91 +0x638
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/go/src/github.com/prometheus/client_golang/prometheus/registry.go:428 +0x19d
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/go/src/github.com/prometheus/client_golang/prometheus/registry.go:520 +0xe36
```

**Comment by jannfis** [comment]
@ermakov-oleg Thanks for the notice. But this is weird, because the E2E tests are running succesfully.  When does the crash happen? At startup?

**Comment by ermakov-oleg** [comment]
Crash occurs when collecting metrics from pod.
[Clustername](https://github.com/argoproj/argo-cd/blob/master/controller/metrics/clustercollector.go#L91) not present in descClusterInfo metric [definition](https://github.com/argoproj/argo-cd/blob/master/controller/metrics/clustercollector.go#L18).

**Comment by jannfis** [comment]
I have created a revert PR just for if we need it.

But I have trouble reprocuding the crash. I start `argocd-application-controller` locally, and then run `curl 127.0.0.1:8082/metrics` to collect metrics. There is no crash happening for me, and the metrics are successfully retrieved.

**Comment by jannfis** [comment]
OK, could reprocuce it now @ermakov-oleg - guess the merge should be reverted. Thanks for your prompt notice!

**Comment by ermakov-oleg** [comment]
Thanks for the quick response!  👍

**Pull request merged**
