### PR TITLE
chore(deps): Upgrade aws-sdk-go to support eks pod identity (cherry-pick  #17063)

### PR DESCRIPTION
**Pull request by csantanapr**
Cherry-picked chore(deps): Upgrade aws-sdk-go to support eks pod identity (https://github.com/argoproj/argo-cd/pull/17063)
* chore: Upgrade aws-sdk-go to support eks pod identity

---------

Signed-off-by: Carlos Santana <carrlos@amazon.com>
Co-authored-by: Mathieu Bruneau <brunemat@amazon.com>

* add cogen for notifications

Signed-off-by: Carlos Santana <carrlos@amazon.com>

---------

Signed-off-by: Carlos Santana <carrlos@amazon.com>
Co-authored-by: Mathieu Bruneau <brunemat@amazon.com>

### CODE REVIEW

**Comment by csantanapr** [comment]
@crenshaw-dev check if I did the cherry-pick correctly when you have a chance

**Review by ishitasequeira — APPROVED** [review]
@csantanapr The cherry-pick looks good.

**Comment by csantanapr** [comment]
thank you @ishitasequeira  I just fix the codegen for the version in manifests

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
@csantanapr , as the PR is for 2.10 release, the release tag should not be `latest`. The generated manifests are expected to fail.

**Comment by csantanapr** [comment]
@ishitasequeira 
>@csantanapr , as the PR is for 2.10 release, the release tag should not be latest. The generated manifests are expected to fail.

I just fixed this in https://github.com/argoproj/argo-cd/pull/17225/commits/7014cbecb4955d0d24f9cc88cbe4d805995401aa

**Comment by ishitasequeira** [comment]
@csantanapr , I see that you updated the tag from `2.10.1` to `latest`. What I am saying is, as this is a cherry-pick PR for release-2.10, we should keep the tag as `2.10.1`. The CI is expected to fail in this case.

**Comment by csantanapr** [comment]
Oh I have it reversed then, I put it back to `2.10.1` but this means codegen was failing for some other reason

**Comment by csantanapr** [comment]
Oh WOW your saying that CI on release branches are supposed to fail? That's crazy why we don't have the github actions compensate and be correct for branch releases?

**Comment by csantanapr** [comment]
reverting the last commit, and now the CI tests on codegen will fail because is not `latest` crazy 🤕

**Comment by csantanapr** [comment]
Oh wow I just checked a couple of PR for released branch and all don't pass the CI check for codegen.
This most be painful for you maintainers to review the failed tests and make sure are the expected failures and not others introduced. 🙏 
image

**Comment by ishitasequeira** [comment]
Yup. It would be good if it can be fixed. But I guess no one has got to the point to fix it. 😅

**Review by ishitasequeira — APPROVED** [review]

**Comment by csantanapr** [comment]
Can you draft a short issue explaining the problem and the pain. I think this is a good candidate for first good issue

**Comment by csantanapr** [comment]
Thank you @ishitasequeira for merging 🙏

**Comment by ishitasequeira** [comment]
> @ishitasequeira @crenshaw-dev Could you draft a short issue explaining the problem and the pain. I think this is a good candidate for first good issue

Sure. I can write up an issue for this.

**Pull request merged**
