### PR TITLE
fix(ci):  fix flaky e2e tests - ignore temporary files when checking for out of bound symlinks

### PR DESCRIPTION
**Pull request by CefBoud**
Addresses part of https://github.com/argoproj/argo-cd/issues/11667

# Description

This PR fixes errors that happen frequently in the CI [1](https://github.com/argoproj/argo-cd/actions/runs/11494345566/job/31991806822#step:16:4377), [2](https://github.com/argoproj/argo-cd/actions/runs/11453505375/job/31866171929#step:16:10272). 

These issues arise when walking through a directory, where temporary files—like Git lock files—are scanned but may be deleted by the time their handlers execute.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
Thank you @CefBoud . This flakiness appeared recently. Had you chance to check what change may introduce this issue? Just wonder why it started to happens

**Comment by CefBoud** [comment]
@pasha-codefresh 
I did not observe any significant changes in this failing code path. However, I did notice that the version of Git being used by the job has been updated recently to 2.47.0, which was released in early October. 
The error `failed to walk for symlinks` in the [path.Walk](https://github.com/argoproj/argo-cd/blob/5c01cf6ebfcaa5116b3a4e7cf3de964591126e23/util/app/path/path.go#L52-L53) function is not new; it has been encountered before, as noted in https://github.com/argoproj/argo-cd/issues/11667.

**Review by crenshaw-dev — APPROVED** [review]
This seems safe and reasonable. If a file doesn't exist, it can't provide a path for traversal.

**Pull request merged**
