### PR TITLE
feat: Add custom resource actions for flux resources

### PR DESCRIPTION
**Pull request by adberger**
As shortly discussed here: https://github.com/argoproj/argo-cd/discussions/18888
This is the first PR to implement custom resource actions for flux resources.

The following 2 actions are available for all flux resources except `ImagePolicy`:
- **suspend**
- **resume**

The **reconcile** action is available for all resources except `Alert`, `Provider` & `ImagePolicy`:

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by adberger** [comment]
Don't know why the tests are failing to be honest:
```
<     reconcile.fluxcd.io/requestedAt: 'By ArgoCD at: 0001-01-01T00:00:00'
---
>     reconcile.fluxcd.io/requestedAt: 'By ArgoCD at: 2024-07-04T10:46:27'
```

This problem for example doesn't exist on https://github.com/argoproj/argo-cd/blob/5c6c0c8c4f1f0c0f75ebb0c0f4765885167bb36c/resource_customizations/apps/DaemonSet/actions/testdata/daemonset-restarted.yaml.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Overall LGTM! Two things:

1) Can you change `ArgoCD` to `Argo CD` in the timestamp annotations?
2) Could you add a 2.13 upgrade note to highlight that these actions have been added? Just in case anyone wants to update their RBAC to allow/deny the new actions. It's in docs/operator-manual/upgrading/.

**Comment by adberger** [comment]
> Overall LGTM! Two things:
> 
> 1. Can you change `ArgoCD` to `Argo CD` in the timestamp annotations?
> 2. Could you add a 2.13 upgrade note to highlight that these actions have been added? Just in case anyone wants to update their RBAC to allow/deny the new actions. It's in docs/operator-manual/upgrading/.

Thanks for your review!
I've made your suggested changes, could you check again?

**Review by crenshaw-dev — APPROVED** [review]
Brilliant work, thank you!

**Pull request merged**
