### PR TITLE
fix: Update bitbucket.org rsa ssh key

### LINKED ISSUE #13604: add latest bitbucket known host...all bitucket repos disconnected...unable to verify known host
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by hligit**
The key change announcement at https://bitbucket.org/blog/ssh-host-key-changes

Fixes #13604

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @hligit!

**Comment by crenshaw-dev** [comment]
@hligit would you mind opening cherry-pick PRs agains the release-2.6 and release-2.5 branches

**Comment by hligit** [comment]
@crenshaw-dev thanks for approving! I've raised PRs for release 2.6 and 2.5. There are some failed checks, seem to be unrelated to the ssh key change.

**Pull request merged**
