### PR TITLE
fix: creds.CAPath passed helm in PullOCI (#13726)

### PR DESCRIPTION
**Pull request by dromie**
Fixes [ #13726 ]

helm pull can accept --ca-file which was passed in Fetch function, but not in PullOCI. This PR enables argocd to work with self signed repositories without defining the repository as insecure.

Checklist:

* [b] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by jaideepr97** [comment]
Thanks @dromie 
Would you mind adding a unit test to verify this behavior?

**Comment by dromie** [comment]
If I may, I would borrow @pasha-codefresh 's description in #13608:
"Adding of unit tests is problematic in this case, because it requires changes in cmd.go, so i decided just better test it manually for now"

**Comment by jaideepr97** [comment]
I suppose that makes sense, it might require passing in actual creds to an OCI repo to verify, which seems out of scope for a unit test 

LGTM otherwise

**Review by jaideepr97 — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]

**Review by alexmt — APPROVED** [review]

**Comment by christianhuening** [comment]
Has this been released yet or is it planned for a release?

**Comment by dromie** [comment]
this commit is included since v2.8.0

**Comment by christianhuening** [comment]
Hm ok it says this would fix #13762 but it is still marked as open?!

**Comment by dromie** [comment]
I've conducted some tests in the past 2 days, and figured out the "problem". You can read my comment on the issue https://github.com/argoproj/argo-cd/issues/13726

**Pull request merged**
