### PR TITLE
fix: Refine resource option evaluation for `argocd app sync` command(#17397)

### LINKED ISSUE #17397: multiple `--resource !` exclusion flags to `argocd app sync` does not work, includes _all_ resources
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using `argocd app sync` specifying the `--resource` flag multiple times with `!` (exclusions) does not work as intended. Instead, all resources are included because the excluded resources essentially shadow each other / cancel each other out by including the other filter's resources.

**To Reproduce**

> The output of each command is a bit long so I've trimmed some of the output to show only relevant parts.

We want to sync all resources except `cert-manager.io` and `cilium.io` so we try to use the `--resource` flag twice:

```console
$ argocd app sync argocd/cilium-p1 --resource '!cilium.io:*:*' --resource '!cert-manager.io:*:*' --dry-run

TIMESTAMP                  GROUP                            KIND                  NAMESPACE                   NAME                 STATUS    HEALTH        HOOK  MESSAGE
2024-03-05T02:20:27+00:00                             ServiceAccount                 cilium        cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium            hubble-peer               OutOfSync  Missing
2024-03-05T02:20:27+00:00                             ServiceAccount                 cilium              hubble-ui               OutOfSync  Missing
2024-03-05T02:20:27+00:00   apps                       DaemonSet                     cilium                 cilium               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium              hubble-ca               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  RoleBinding                    cilium   ops-cilium-cluster-admin           OutOfSync  Missing
2024-03-05T02:20:27+00:00                              ConfigMap                     cilium        hubble-ui-nginx               OutOfSync  Missing
2024-03-05T02:20:27+00:00                              Namespace                                            cilium               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium           hubble-relay               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium   clustermesh-apiserver-server-cert  OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io                Issuer                     cilium          hubble-issuer               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                      clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  RoleBinding                    cilium   admins-cilium-cluster-admin        OutOfSync  Missing
2024-03-05T02:20:27+00:00                              ConfigMap                     cilium          cilium-config               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium   clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00  monitoring.coreos.com      PodMonitor                     cilium           cilium-agent               OutOfSync  Missing
2024-03-05T02:20:27+00:00  monitoring.coreos.com      ServiceMonitor                 cilium        cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRole                                           cilium               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                                    cilium               OutOfSync  Missing
2024-03-05T02:20:27+00:00                             ResourceQuota                  cilium   cilium-resource-quota              OutOfSync  Missing
2024-03-05T02:20:27+00:00   apps                      Deployment                     cilium           hubble-relay               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRole                                  cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium   clustermesh-apiserver-metrics      OutOfSync  Missing
2024-03-05T02:20:27+00:00   apps                       DaemonSet                     cilium       cilium-node-init               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium   clustermesh-apiserver-ca           OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium    hubble-server-certs               OutOfSync  Missing
2024-03-05T02:20:27+00:00                             ServiceAccount                 cilium   clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00   apps                      Deployment                     cilium              hubble-ui               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  RoleBinding                    cilium    cilium-config-agent               OutOfSync  Missing
2024-03-05T02:20:27+00:00                              ConfigMap                     cilium    hubble-relay-config               OutOfSync  Missing
2024-03-05T02:20:27+00:00                             ResourceQuota                  cilium   cilium-operator-resource-quota     OutOfSync  Missing
2024-03-05T02:20:27+00:00                             ServiceAccount                 cilium                 cilium               OutOfSync  Missing
2024-03-05T02:20:27+00:00   apps                      Deployment                     cilium        cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io                Issuer                     cilium      cilium-selfsigned               OutOfSync  Missing
2024-03-05T02:20:27+00:00  monitoring.coreos.com      PrometheusRule                 cilium                 cilium               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cilium.io                  CiliumLocalRedirectPolicy  kube-system  gke-metadata-server-redirect       OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium           cilium-agent               OutOfSync  Missing
2024-03-05T02:20:27+00:00                             ServiceAccount                 cilium           hubble-relay               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium   clustermesh-apiserver-remote-cert  OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium   clustermesh-apiserver-admin-cert   OutOfSync  Missing
2024-03-05T02:20:27+00:00  monitoring.coreos.com      ServiceMonitor                 cilium   clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRole                             clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io            Certificate                    cilium   hubble-relay-client-certs          OutOfSync  Missing
2024-03-05T02:20:27+00:00  monitoring.coreos.com      PrometheusRule                 cilium   clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00  policy                     PodDisruptionBudget            cilium        cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                                 hubble-ui               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium         hubble-metrics               OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io        Role                     cilium    cilium-config-agent               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cert-manager.io                Issuer                     cilium   clustermesh-apiserver-issuer       OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRole                                        hubble-ui               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium              hubble-ui               OutOfSync  Missing
2024-03-05T02:20:27+00:00   apps                      Deployment                     cilium   clustermesh-apiserver              OutOfSync  Missing
2024-03-05T02:20:27+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                           cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00                                Service                     cilium        cilium-operator               OutOfSync  Missing
2024-03-05T02:20:27+00:00  cilium.io                  CiliumNetworkPolicy            cilium                 cilium               OutOfSync  Missing

Message:            one or more synchronization tasks are not valid

GROUP                      KIND                       NAMESPACE    NAME                               STATUS     HEALTH   HOOK  MESSAGE
cert-manager.io            Certificate                cilium       hubble-ca                          OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/hubble-ca. Make sure the "Certificate" CRD is installed on the destination cluster.
cilium.io                  CiliumNetworkPolicy        cilium       cilium                             OutOfSync  Missing        The Kubernetes API could not find cilium.io/CiliumNetworkPolicy for requested resource cilium/cilium. Make sure the "CiliumNetworkPolicy" CRD is installed on the destination cluster.
cert-manager.io            Certificate                cilium       clustermesh-apiserver-server-cert  OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/clustermesh-apiserver-server-cert. Make sure the "Certificate" CRD is installed on the destination cluster.
cert-manager.io            Certificate                cilium       clustermesh-apiserver-ca           OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/clustermesh-apiserver-ca. Make sure the "Certificate" CRD is installed on the destination cluster.
cert-manager.io            Issuer                     cilium       clustermesh-apiserver-issuer       OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Issuer for requested resource cilium/clustermesh-apiserver-issuer. Make sure the "Issuer" CRD is installed on the destination cluster.
cert-manager.io            Certificate                cilium       clustermesh-apiserver-remote-cert  OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/clustermesh-apiserver-remote-cert. Make sure the "Certificate" CRD is installed on the destination cluster.
cert-manager.io            Certificate                cilium       hubble-relay-client-certs          OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/hubble-relay-client-certs. Make sure the "Certificate" CRD is installed on the destination cluster.
cert-manager.io            Certificate                cilium       clustermesh-apiserver-admin-cert   OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/clustermesh-apiserver-admin-cert. Make sure the "Certificate" CRD is installed on the destination cluster.
cert-manager.io            Certificate                cilium       hubble-server-certs                OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Certificate for requested resource cilium/hubble-server-certs. Make sure the "Certificate" CRD is installed on the destination cluster.
cert-manager.io            Issuer                     cilium       hubble-issuer                      OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Issuer for requested resource cilium/hubble-issuer. Make sure the "Issuer" CRD is installed on the destination cluster.
cilium.io                  CiliumLocalRedirectPolicy  kube-system  gke-metadata-server-redirect       OutOfSync  Missing        The Kubernetes API could not find cilium.io/CiliumLocalRedirectPolicy for requested resource kube-system/gke-metadata-server-redirect. Make sure the "CiliumLocalRedirectPolicy" CRD is installed on the destination cluster.
cert-manager.io            Issuer                     cilium       cilium-selfsigned                  OutOfSync  Missing        The Kubernetes API could not find cert-manager.io/Issuer for requested resource cilium/cilium-selfsigned. Make sure the "Issuer" CRD is installed on the destination cluster.
...
```

The `cert-manager.io:*` and `cilium.io:*` resources are not excluded as expected.

Specifying only one resource type to exclude works:
```console
$ argocd app sync argocd/cilium-p1 --resource '!cert-manager.io:*:*' --dry-run
TIMESTAMP                  GROUP                            KIND                  NAMESPACE                   NAME              STATUS    HEALTH        HOOK  MESSAGE
2024-03-05T02:22:16+00:00   apps                      Deployment                     cilium              hubble-ui            OutOfSync  Missing
2024-03-05T02:22:16+00:00  monitoring.coreos.com      PrometheusRule                 cilium   clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                           cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  RoleBinding                    cilium   ops-cilium-cluster-admin        OutOfSync  Missing
2024-03-05T02:22:16+00:00                              ConfigMap                     cilium          cilium-config            OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium         hubble-metrics            OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ServiceAccount                 cilium        cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ServiceAccount                 cilium                 cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ServiceAccount                 cilium   clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00  cilium.io                  CiliumNetworkPolicy            cilium                 cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00  monitoring.coreos.com      ServiceMonitor                 cilium        cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00                              ConfigMap                     cilium        hubble-ui-nginx            OutOfSync  Missing
2024-03-05T02:22:16+00:00                              Namespace                                            cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium           cilium-agent            OutOfSync  Missing
2024-03-05T02:22:16+00:00   apps                       DaemonSet                     cilium                 cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00  monitoring.coreos.com      PodMonitor                     cilium           cilium-agent            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRole                                           cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                                    cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                      clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00                              ConfigMap                     cilium    hubble-relay-config            OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium   clustermesh-apiserver-metrics   OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium           hubble-relay            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRoleBinding                                 hubble-ui            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io        Role                     cilium    cilium-config-agent            OutOfSync  Missing
2024-03-05T02:22:16+00:00  policy                     PodDisruptionBudget            cilium        cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  RoleBinding                    cilium   admins-cilium-cluster-admin     OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ResourceQuota                  cilium   cilium-operator-resource-quota  OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium   clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00  monitoring.coreos.com      PrometheusRule                 cilium                 cilium            OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ResourceQuota                  cilium   cilium-resource-quota           OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium            hubble-peer            OutOfSync  Missing
2024-03-05T02:22:16+00:00   apps                       DaemonSet                     cilium       cilium-node-init            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  RoleBinding                    cilium    cilium-config-agent            OutOfSync  Missing
2024-03-05T02:22:16+00:00   apps                      Deployment                     cilium        cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00   apps                      Deployment                     cilium           hubble-relay            OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRole                                  cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00  monitoring.coreos.com      ServiceMonitor                 cilium   clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRole                                        hubble-ui            OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium              hubble-ui            OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ServiceAccount                 cilium              hubble-ui            OutOfSync  Missing
2024-03-05T02:22:16+00:00   apps                      Deployment                     cilium   clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00  rbac.authorization.k8s.io  ClusterRole                             clustermesh-apiserver           OutOfSync  Missing
2024-03-05T02:22:16+00:00                                Service                     cilium        cilium-operator            OutOfSync  Missing
2024-03-05T02:22:16+00:00                             ServiceAccount                 cilium           hubble-relay            OutOfSync  Missing
2024-03-05T02:22:16+00:00  cilium.io                  CiliumLocalRedirectPolicy  kube-system  gke-metadata-server-redirect    OutOfSync  Missing

Message:            one or more synchronization tasks are not valid

GROUP                      KIND                       NAMESPACE    NAME                               STATUS     HEALTH   HOOK  MESSAGE
cilium.io                  CiliumNetworkPolicy        cilium       cilium                             OutOfSync  Missing        The Kubernetes API could not find cilium.io/CiliumNetworkPolicy for requested resource cilium/cilium. Make sure the "CiliumNetworkPolicy" CRD is installed on the destination cluster.
cilium.io                  CiliumLocalRedirectPolicy  kube-system  gke-metadata-server-redirect       OutOfSync  Missing        The Kubernetes API could not find cilium.io/CiliumLocalRedirectPolicy for requested resource kube-system/gke-metadata-server-redirect. Make sure the "CiliumLocalRedirectPolicy" CRD is installed on the destination cluster.
```

Specifying multiple `--resource`s to _include_ works as intended:

```console
$ argocd app sync argocd/cilium-p1 --resource 'apps:*:*' --resource ':Service:*' --loglevel debug --dry-run
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME             STATUS    HEALTH        HOOK  MESSAGE
2024-03-05T02:23:53+00:00            Service      cilium          cilium-agent           OutOfSync  Missing
2024-03-05T02:23:53+00:00   apps   DaemonSet      cilium      cilium-node-init           OutOfSync  Missing
2024-03-05T02:23:53+00:00   apps  Deployment      cilium  clustermesh-apiserver          OutOfSync  Missing
2024-03-05T02:23:53+00:00   apps  Deployment      cilium          hubble-relay           OutOfSync  Missing
2024-03-05T02:23:53+00:00   apps   DaemonSet      cilium                cilium           OutOfSync  Missing
2024-03-05T02:23:53+00:00   apps  Deployment      cilium             hubble-ui           OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium  clustermesh-apiserver          OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium        hubble-metrics           OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium           hubble-peer           OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium       cilium-operator           OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium  clustermesh-apiserver-metrics  OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium          hubble-relay           OutOfSync  Missing
2024-03-05T02:23:53+00:00            Service      cilium             hubble-ui           OutOfSync  Missing
2024-03-05T02:23:53+00:00   apps  Deployment      cilium       cilium-operator           OutOfSync  Missing

Message:            successfully synced (no more tasks)

GROUP                      KIND                       NAMESPACE    NAME                               STATUS     HEALTH   HOOK  MESSAGE
                           Service                    cilium       cilium-agent                       OutOfSync  Missing        service/cilium-agent created (dry run)
                           Service                    cilium       hubble-ui                          OutOfSync  Missing        service/hubble-ui created (dry run)
                           Service                    cilium       hubble-metrics                     OutOfSync  Missing        service/hubble-metrics created (dry run)
                           Service                    cilium       cilium-operator                    OutOfSync  Missing        service/cilium-operator created (dry run)
                           Service                    cilium       clustermesh-apiserver-metrics      OutOfSync  Missing        service/clustermesh-apiserver-metrics created (dry run)
                           Service                    cilium       hubble-relay                       OutOfSync  Missing        service/hubble-relay created (dry run)
                           Service                    cilium       clustermesh-apiserver              OutOfSync  Missing        service/clustermesh-apiserver created (dry run)
                           Service                    cilium       hubble-peer                        OutOfSync  Missing        service/hubble-peer created (dry run)
apps                       DaemonSet                  cilium       cilium-node-init                   OutOfSync  Missing        daemonset.apps/cilium-node-init created (dry run)
apps                       DaemonSet                  cilium       cilium                             OutOfSync  Missing        daemonset.apps/cilium created (dry run)
apps                       Deployment                 cilium       hubble-ui                          OutOfSync  Missing        deployment.apps/hubble-ui created (dry run)
apps                       Deployment                 cilium       cilium-operator                    OutOfSync  Missing        deployment.apps/cilium-operator created (dry run)
apps                       Deployment                 cilium       hubble-relay                       OutOfSync  Missing        deployment.apps/hubble-relay created (dry run)
apps                       Deployment                 cilium       clustermesh-apiserver              OutOfSync  Missing        deployment.apps/clustermesh-apiserver created (dry run)
```

**Expected behavior**

Specifying multiple `--resource !` exclusions should exclude all resources matching all of the filters.

**Screenshots**

**Version**

```shell
argocd: v2.10.2+fcf5d8c.dirty
  BuildDate: 2024-03-02T00:36:51Z
  GitCommit: fcf5d8c2381b68ab1621b90be63913b12cca2eb7
  GitTreeState: dirty
  GoVersion: go1.22.0
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.1+a79e0ea
  BuildDate: 2024-02-14T17:37:43Z
  GitCommit: a79e0eaca415461dc36615470cecc25d6d38cefb
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.0+g3fc9f4b
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by eugene70**
This update refactors the `IncludeResource` logic to improve accuracy in resource filtering. 
Also, it includes new test cases to ensure the correctness of the changes.

Fixes: #17397

Changes:
- Rewritten `IncludeResource` function for better logic flow.
- Added unit tests to validate the new behavior.
- Found that two existing test cases were incorrect and fixed them. A closer review of this part is needed.

### CODE REVIEW

**Comment by eugene70** [comment]
@jannfis PTAL

**Review by todaywasawesome — COMMENTED** [review]
@pasha-codefresh needs extra 👁️

**Review by reggie-k — CHANGES_REQUESTED** [review]
I think that it makes sense to skip the resources in the syncOperationResource[] that have an Exclude, and then compare only the rest (that are assumed to be marked as Include), like you suggested.
I think that the second loop is not needed and we can just return false if all syncOperationResource are Exclude, or if some were Include but none matched the input. And probably return true if there was an Include and it matched the input.

**Comment by eugene70** [comment]
> I think that it makes sense to skip the resources in the syncOperationResource[] that have an Exclude, and then compare only the rest (that are assumed to be marked as Include), like you suggested. I think that the second loop is not needed and we can just return false if all syncOperationResource are Exclude, or if some were Include but none matched the input. And probably return true if there was an Include and it matched the input.

Let’s first consider the scenario where there are no include filters. In this case, we either have no filters at all or only exclude filters, which means all target resources should be included initially. After that, we can check the exclude filters, and if any of those conditions apply, we can exclude the resource.

I’ve made sure to include only the conditions that don’t need to go into the exclude filter evaluation loop in the existing code. 

Did I miss anything from what you mentioned? I’m a bit confused by the second sentence, as it’s not entirely clear to me at first glance.

**Comment by reggie-k** [comment]
This bug is more complex than it seems from a first glance :)
Thanks a lot for the PR and for such detailed tests!

I have another suggestion for this change, please take a look.
Not sure which one is more readable among the two (both pass all the tests), since the logic is pretty complex anyway, but mine loops over the resources a single time.
WDYT?

``` 
func IncludeResource(resourceName string, resourceNamespace string, gvk schema.GroupVersionKind,
	syncOperationResources []*argoappv1.SyncOperationResource,
) bool {
	includeResource := false
	foundIncludeRule := false
	foundExcludeRule := false
	resourceFoundInList := false

	// The use cases for this allegedly simple function are quite complex.
	for _, syncOperationResource := range syncOperationResources {
		// need to know whether there were any include / exclude rules in the list of resources,
		// for the case when the resource was not found in the list of resources
		if !syncOperationResource.Exclude && !foundIncludeRule {
			foundIncludeRule = true
		} else if syncOperationResource.Exclude && !foundExcludeRule {
			foundExcludeRule = true
		}
		// If the resource is found in the list of resources, and has an exclude rule, it should be excluded.
		// If the resource is found in the list of resources, and has an include rule, it should be included.
		resourceFoundInList = syncOperationResource.Compare(resourceName, resourceNamespace, gvk)
		if resourceFoundInList {
			if syncOperationResource.Exclude {
				includeResource = false
				break
			} else {
				includeResource = true
				break
			}
		}
	}
	if !resourceFoundInList {
		// the resource was not found in the list of resources
		if foundIncludeRule {
			// if there was an include rule, the resource should be excluded (as it was not explicitly included)
			includeResource = false
		} else if foundExcludeRule {
			// if there was an exclude rule, the resource should be included (as it was not explicitly excluded)
			includeResource = true
		} else {
			// if there were no rules at all, which is an edge case and maybe does not even happen, the resource should be included
			includeResource = true
		}
	}

	return includeResource
}
```

**Comment by eugene70** [comment]
@reggie-k , Certainly your code looks good and improved. But as I was reading the code I thought of a more complex test case. That is, if a given resource matches both an include filter and an exclude filter. 
I added one test and both we failed. So I modified the existing code a little and pushed it again.

**Comment by reggie-k** [comment]
LGTM! 
(even though it loops twice, but I don't think there would be many resources inputed to this command, so not a problem). 
Just please add more comments to explain:

-  that if a resource is present both in include and in exclude, the exclude wins
-  that including it here is a temporary decision for the use case when no include rules exist, but it still might be excluded later if it matches an exclude rule:
```
	if !foundIncludeRule {
		includeResource = true
	}
```

**Comment by eugene70** [comment]
> LGTM! (even though it loops twice, but I don't think there would be many resources inputed to this command, so not a problem). Just please add more comments to explain:
> 
> * that if a resource is present both in include and in exclude, the exclude wins
> * that including it here is a temporary decision for the use case when no include rules exist, but it still might be excluded later if it matches an exclude rule:
> 
> ```
> 	if !foundIncludeRule {
> 		includeResource = true
> 	}
> ```

Done!

**Review by reggie-k — CHANGES_REQUESTED** [review]
Sorry for the nit picking and thanks for the patience, can you remove the "that" in the beginning of the new comments sentence?

**Comment by eugene70** [comment]
> LGTM! (even though it loops twice, but I don't think there would be many resources inputed to this command, so not a problem). Just please add more comments to explain:
> 
> * that if a resource is present both in include and in exclude, the exclude wins
> * that including it here is a temporary decision for the use case when no include rules exist, but it still might be excluded later if it matches an exclude rule:
> 
> ```
> 	if !foundIncludeRule {
> 		includeResource = true
> 	}
> ```

Done, again! ^^

**Comment by eugene70** [comment]
@reggie-k I found the other test. I did not know about that app command test. I fixed the test case and added a test. PTAL.

**Comment by reggie-k** [comment]
LGTM

**Review by pasha-codefresh — APPROVED** [review]

**Pull request merged**
