### PR TITLE
fix: docs site version selector broken

### LINKED ISSUE #18239: Version selector in website is broken
**Describe the bug**

The version selector when using `readthedocs.io` is broken. The same issue exist today with https://argo-rollouts.readthedocs.io/en/stable/.

See mkdocs config and corresponding files in docs/
```
extra_css:
- assets/versions.css
extra_javascript:
- assets/versions.js
```

**To Reproduce**

1. Browse to https://argo-cd.readthedocs.io/en/stable/
2. Click on stable to use the version selector

**Expected behavior**

A dropdown with documentation on stable/latest/previous releases should be available

**Screenshots**

image

**Version**

Running on chrome 124

**Logs**

No error in console

### PR DESCRIPTION
**Pull request by yyzxw**
Fixes #18239

image

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by yyzxw** [comment]
cc @sentientmonkey @farcaller

**Review by agaudreault — CHANGES_REQUESTED** [review]
@yyzxw Thanks for the PR! I think some css changes are needed as well. From your screenshot, there seems to be a lot of extra padding in the dropdown.

Also, if you can validate that your PR does not duplicate the banner message, or use the new one, we can close 2 issues from this PR. See https://github.com/argoproj/argo-cd/issues/18407

**Comment by christianh814** [comment]
@yyzxw Did you have a chance to take a look at @agaudreault's suggestions?

**Comment by yyzxw** [comment]
@agaudreault yes, Also fixed #18407 now.

**Review by christianh814 — APPROVED** [review]

**Review by agaudreault — APPROVED** [review]
Not so sure how we can test in local, but the version selector now works!

**Review by ishitasequeira — APPROVED** [review]
LGTM!! Thanks @yyzxw!!

**Pull request merged**
