### PR TITLE
fix: Add namespace to sub-application link URLs (#11945)

### LINKED ISSUE #11518: UI redirect issue from mother app to child app view
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using the new feature of deploying application objects in different namespaces than `argocd` one, the URL for application consists of: 
`https://{{ argocd_server_url }}/applications/{{ application_namespace }}/{{ application_name }}`
i.e.: 
`https://argocd.test.com/applications/test-namespace/app-name?view=tree&orphaned=false&resource=`
and when you're in the UI view of the application which contains other applications there is an icon which redirects you to the child app and when you click on it the namespace is missing in the URL and 403 is returned.

**To Reproduce**

Following application objects should be deployed in other namespace than ArgoCD

(mother application - application which contains other application objects)

1. Open mother application view in the UI
2. Click on the redirect icon in the child app box
3. Get HTTP 403 response - user was redirected to wrong URL (with missing namespace in it)

**Expected behavior**

User should be redirected correctly to the child app view.

**Screenshots**

mother_app_view
icon
url_issue
child_app_view_network
child_app_view_console
### How it should look like
how_url_should_look_like

**Version**

```shell
argocd-server: v2.5.3+0c7de21
  BuildDate: 2022-11-28T16:51:33Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

**Logs**

```
argocd-server-6f7dd94458-zqxpk server time="2022-12-01T11:22:11Z" level=info msg="received unary call /application.ApplicationService/ManagedResources" grpc.method=ManagedResources grpc.request.claims="{\"aio\":\"AVQAq/8TAAAAHFIdDt1xu/2pdKaoNIz3bkv8LMYNiNE0ST5AsR87TXj9qrjvCaOZ2IApiAP7JEctbKtxgB4speVPxdR4mZZof/MowjxZK61+Ei2w1GovNV8=\",\"aud\":\"e9d41d8f-6f08-420e-a3ee-2cd6bd4611bc\",\"exp\":1669895401,\"iat\":1669891501,\"iss\":\"https://login.microsoftonline.com/adf10e2b-b6e9-41d6-be2f-c12bb566019c/v2.0\",\"name\":\"Admin\",\"nbf\":1669891501,\"oid\":\"79a2a4c7-5466-485e-8418-7d20d58e5ff0\",\"preferred_username\":\"ADM\",\"rh\":\"0.AQIAKw7xrem21kG-L8ErtWYBnI8d1OkIbw5Co-4s1r1GEbwCAK4.\",\"sub\":\"mCcqp19_aPRsjpDNvroDcq_JbOgD5X6ZqLurU-T2n6Q\",\"tid\":\"adf10e2b-b6e9-41d6-be2f-c12bb566019c\",\"uti\":\"3EwF-29GsEWfdxkMc-crAA\",\"ver\":\"2.0\"}" grpc.request.content="applicationName:\"tenant2-app-of-apps-nonprod001\" namespace:\"management-tenant2\" name:\"standard-workload-nonprod001\" group:\"argoproj.io\" kind:\"Application\" appNamespace:\"management-tenant2\" " grpc.service=application.ApplicationService grpc.start_time="2022-12-01T11:22:11Z" span.kind=server system=grpc
argocd-server-6f7dd94458-dtvdb server time="2022-12-01T11:22:11Z" level=info msg="received unary call /application.ApplicationService/GetResource" grpc.method=GetResource grpc.request.claims="{\"aio\":\"AVQAq/8TAAAAHFIdDt1xu/2pdKaoNIz3bkv8LMYNiNE0ST5AsR87TXj9qrjvCaOZ2IApiAP7JEctbKtxgB4speVPxdR4mZZof/MowjxZK61+Ei2w1GovNV8=\",\"aud\":\"e9d41d8f-6f08-420e-a3ee-2cd6bd4611bc\",\"exp\":1669895401,\"iat\":1669891501,\"iss\":\"https://login.microsoftonline.com/adf10e2b-b6e9-41d6-be2f-c12bb566019c/v2.0\",\"name\":\"Admin\",\"nbf\":1669891501,\"oid\":\"79a2a4c7-5466-485e-8418-7d20d58e5ff0\",\"preferred_username\":\"ADM\",\"rh\":\"0.AQIAKw7xrem21kG-L8ErtWYBnI8d1OkIbw5Co-4s1r1GEbwCAK4.\",\"sub\":\"mCcqp19_aPRsjpDNvroDcq_JbOgD5X6ZqLurU-T2n6Q\",\"tid\":\"adf10e2b-b6e9-41d6-be2f-c12bb566019c\",\"uti\":\"3EwF-29GsEWfdxkMc-crAA\",\"ver\":\"2.0\"}" grpc.request.content="name:\"tenant2-app-of-apps-nonprod001\" namespace:\"management-tenant2\" resourceName:\"standard-workload-nonprod001\" version:\"v1alpha1\" group:\"argoproj.io\" kind:\"Application\" appNamespace:\"management-tenant2\" " grpc.service=application.ApplicationService grpc.start_time="2022-12-01T11:22:11Z" span.kind=server system=grpc
```

### LINKED ISSUE #11945: UI: Links to Sub-applications in other namespace are broken
**Describe the bug**
At Patreon we use the App-of-Apps pattern combined with "Applications in other namespaces" (#9755 ) for teams to manage applications in their own namespaces. 
However, the UI needs a slight update to make it easy to follow links from the AoA to the sub-application. Currently the path in the  "Open application" link in the tree or list view does not contain the sub-application's namespace.

**To Reproduce**

1. Create an App-of-Apps which creates applications in namespaces other than `argocd`. 
Example in [iandelahorne/argocd-example-apps/apps, namespace branch](https://github.com/iandelahorne/argocd-example-apps/tree/namespace/apps) which creates the applications in the `ns` namespace.
2. Navigate to the application in the UI and sync.
3. Attempt to follow the `Open Application` link in the tree or list view 
Screenshot 2023-01-10 at 18 11 59

4. This will link to `/applications/helm-guestbook`, which 404's
5. Navigating to `/applications/ns/helm-guestbook` manually, however, will work.

**Expected behavior**
The `Open application` link to a sub-application in an app-of-app should include the app's namespace in the path.

**Screenshots**

Tile view of UI, with [iandelahorne/argocd-example-apps/apps, namespace branch](https://github.com/iandelahorne/argocd-example-apps/tree/namespace/apps) application added as Application `aoa`
Screenshot 2023-01-10 at 18 16 38 

Hovering over link to `helm-guestbooks` application, showing lack of namespace in path
Screenshot 2023-01-10 at 18 22 32

Following link showing a 404.
Screenshot 2023-01-10 at 18 22 43

**Version**
This is also present on latest `master`, but I've added the version in our staging cluster where this exhibits itself.

```shell
$ argocd version
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:35:58Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.5.2+148d8da
  BuildDate: 2022-11-07T16:42:47Z
  GitCommit: 148d8da7a996f6c9f4d102fdd8e688c2ff3fd8c7
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.1+g9f88ccb
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
  ```

### PR DESCRIPTION
**Pull request by iandelahorne**
Fixes #11518 and #11945

- ui: Add namespace to sub-application links in list and tree view
- Add Patreon to USERS.md

Screenshots:
<details>
<summary>Tree view with sub-applications in other namespaces</summary>
Screenshot 2023-01-11 at 14 15 03
</details>

<details>
<summary>List view with sub-applications in other namespaces</summary>

Screenshot 2023-01-11 at 14 16 59
</details>

With "apps in other namespaces" disabled, and using [argocd-example-apps/apps](https://github.com/argoproj/argocd-example-apps/tree/master/apps) from HEAD, this is the behavior - the links work as before, but now the namespace (`argocd`) is included before the application name.
<details>
<summary>Tree view with sub-applications, "Apps in other namespaces" disabled</summary>
Screenshot 2023-01-11 at 14 30 12
</details>

Signed-off-by: Ian Delahorne <ian@patreon.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by iandelahorne** [comment]
:wave: I'm new to submitting PRs to ArgoCD, and also not a frontend expert. This will add the namespace to the external link for all sub-applications, not just those in non-argocd namespaces.

**Comment by ashutosh16** [comment]
@iandelahorne  Thanks for submitting the PR, would you be able to provide the screenshot of the UI changes?

**Comment by crenshaw-dev** [comment]
Thanks for the PR @iandelahorne! Have you confirmed that the change works fine for apps-of-apps when apps-in-any-namespace is disabled?

**Comment by iandelahorne** [comment]
@ashutosh16 Sure, I added screenshots to the description

@crenshaw-dev It does indeed work well for app-of-apps when apps-in-any-namespace is disabled, I verified this on my test cluster and added a screenshot.

**Comment by alexef** [comment]
This fixes #11518

**Review by alexef — APPROVED** [review]
I see we also have `appQualifiedName` in `utils.tsx`, but that function seems to be for display purpose.

I cannot find other place where we generate the `applications/` url. 

I confirm the url WITH namespace also works when multiple namespaces are not enabled.

**Comment by iandelahorne** [comment]
Thanks for the review @alexef! I'm not familiar with the devleopment flow - do I need to ping someone on slack or attend a contributor's meeting for this to get reviewed and merged?

**Comment by crenshaw-dev** [comment]
@iandelahorne no need, we're just a little behind on reviews. Folks keep contributing things. 🙂

**Review by rbreeze — APPROVED** [review]
LGTM

**Comment by mikeeq** [comment]
Why it wasn't cherry-pick'ed to v2.5.8 but #12115 was? :(

**Comment by crenshaw-dev** [comment]
@mikeeq I think the other cherry-pick was actually in error. We had a code freeze for the CVE patch. I'll cherry-pick this so it goes out with 2.5.9.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.9 and release-2.6 for 2.6.0-rc6.

**Pull request merged**
