### PR TITLE
chore: upgrade Dex to 2.35.0

### LINKED ISSUE #10615: Upgrade dex to v2.34.0, for adding ppc64le support
# Summary

A recent Dex release([v2.34.0](ghcr.io/dexidp/dex:v2.34.0)) has added ppc64le support. With this ArgoCD can also be fully functional on ppc64le architecture, as already it supports the rest of the images(argocd:v2.4.6, redis:7.0.0-alpine).

# Motivation

PPC64Le users can use Argo CD for their use case

# Proposal

Replace the existing dex image tag with the latest [v2.34.0](ghcr.io/dexidp/dex:v2.34.0).

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Supersedes https://github.com/argoproj/argo-cd/pull/10617

Closes https://github.com/argoproj/argo-cd/pull/10615

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
LGTM

**Review by 34fathombelow — APPROVED** [review]
LGTM Thanks for your prompt response

**Comment by crenshaw-dev** [comment]
Just for a paper trail: this addresses https://github.com/dexidp/dex/security/advisories/GHSA-vh7g-p26c-j2cw for us. Argo CD configures the bundled Dex instance with a public client to be used by the `argocd` CLI. So our users should upgrade Dex to protect themselves from that vulnerability.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.2 for 2.2.13, release-2.3 for 2.3.8, and release-2.4 for 2.4.13.

**Comment by mayurwaghmode** [comment]
[Here](https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml#:~:text=image%3A%20ghcr.io/dexidp/dex%3Av2.32.0) when we can expect argocd dex server image will get updated to 2.35.0 from 2.32.0? - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml#:~:text=image%3A%20ghcr.io/dexidp/dex%3Av2.32.0.
So that ppc64le users don't have to modify any manifest file :)
cc @crenshaw-dev @jannfis @34fathombelow

**Comment by crenshaw-dev** [comment]
@mayurwaghmode I failed to update the `stable` tag to point to `v2.4.14` after the release (I'll create an issue about automating this).

The manifest looks correct now: https://github.com/argoproj/argo-cd/blob/stable/manifests/install.yaml#L9767

I think the raw response must be cached, because it still hasn't updated. Hopefully that'll change in a few minutes.

**Comment by mayurwaghmode** [comment]
Thanks @crenshaw-dev :)

**Pull request merged**
