### PR TITLE
docs: update documentation to reflect the procedure on current keycloak (#12495)

### LINKED ISSUE #12495: docs update: keycloak.md shows an old keycloak version and should be updated
# Summary

The operator-manual to configure SSO with Keycloak seems to use a Keycloak version of ~13. By now, Keycloak version 20 is out and the UI has changed significantly.

# Motivation

If one wants to configure ArgoCD to use Keycloak for SSO, one wants to use this documentation to configure the client.

# Proposal

Go through the process and make new screenshots on how to configure the client properly.

# Additional Info
There is already an updated version Draft in my fork: [mmueller-a9s/argo-cd](https://github.com/mmueller-a9s/argo-cd/tree/docs_update_keycloak)

### PR DESCRIPTION
**Pull request by mmueller-rs**
Closes #12495

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
lgtm! Would you mind running the images through squoosh.app or similar? Trying to keep repo size down. :-)

**Comment by mmueller-a9s** [comment]
@crenshaw-dev I was able to reduce the image size to ~24-26% of the previous ones. Should be okay now.

**Review by todaywasawesome — APPROVED** [review]
Looks good now

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@mmueller-a9s apologies for the delay, and thanks for the contribution! :-)

**Pull request merged**
