### PR TITLE
feat(ui): display sha's revision in every history release (#19962)

### LINKED ISSUE #19962: In history screen, sha1 revision is not displayed by default
Hey! This change is a problem when you want to find a specific hash to rollback to. After the change just CMD+F to find the hash doesn't work anymore and we need to manually open all of the details and look for the hash. This is very suboptimal.

From the code it looks like this behavior is not customizable, so right now we're either stuck with a soboptimal experience or rolling-back to previous ArgoCD release.

_Originally posted by @marcin-wicha in https://github.com/argoproj/argo-cd/issues/16871#issuecomment-2354948344_

### PR DESCRIPTION
**Pull request by Tchoupinax**
Hello,

Following the regression reported by [this issue](https://github.com/argoproj/argo-cd/issues/19962), I made the fix to hide only the params table.

I created a sub component to have the state of the panel (open or closed) isolated for each history.

Closes https://github.com/argoproj/argo-cd/issues/19962

### CODE REVIEW

**Comment by reggie-k** [comment]
Thanks for the quick addressing of the issue, can you please attach a screenshot of how this looks like after the change?

**Review by reggie-k — APPROVED** [review]
Tested locally, now revision, authored by and GPG sig are visible at all times, so the revisions are searchable at all times without clicking on the show details button.

**Review by gdsoumya — COMMENTED** [review]
@Tchoupinax can you just add some screenshots of before and after?

**Comment by Tchoupinax** [comment]
Sure!

Before:
image


After:
image

**Review by todaywasawesome — APPROVED** [review]
Looks great and is a good feature.

**Review by gdsoumya — APPROVED** [review]

**Comment by Tchoupinax** [comment]
Hello @reggie-k,

Could this fix be part of `v2.13.0-rc4` or `v2.13.0` please? The feature has been introduced in `v2.13.0-rc1` and requires this fix for the final release.
Tell me if you need anything 🙏 

Thanks!

**Pull request merged**
