### PR TITLE
fix: reflect expected integers in swagger doc

### PR DESCRIPTION
**Pull request by crenshaw-dev**
### <samp>🤖 Generated by Copilot at 6244463</samp>

This pull request fixes the type of numeric properties in the `assets/swagger.json` file to use `integer` instead of `string`, and adds a script to automate this fix for future updates. This improves the API documentation and validation.

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Comment by iandelahorne** [comment]
@crenshaw-dev I was just bitten by this when trying to generate a python client with [openapi-generator](https://openapi-generator.tech/) - applying the JQ in this PR combined with #14813 managed to generate a correct client.  Would greatly appreciate this getting merged!

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
@crenshaw-dev, I think we should add this to the next release. Can you rebase the PR and resolve the conflicts?

**Comment by crenshaw-dev** [comment]
@ishitasequeira rebased!

**Review by ishitasequeira — APPROVED** [review]
LGTM

**Pull request merged**
