### PR TITLE
feat: show last sync finish time in badge

### LINKED ISSUE #6333: UI: show last sync finish time in badge
The badge would be really useful if the little badge shows the finish time of the last sync operation.

### PR DESCRIPTION
**Pull request by dirien**
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>

Fixes #6333

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks @dirien, I do like the idea to use go templates instead of regexp hell.

I have a few minor requests for change, please see below.

**Review by jannfis — APPROVED** [review]
LGTM from a code perspective, thanks for this contribution @dirien!

I'd appreciate another review from UI/UX perspective here @reginapizza @ciiay @rbreeze

**Review by ciiay — COMMENTED** [review]
I'm a little concerned if it might be hard to read for some users? Otherwise it looks great!
Screen Shot 2021-10-21 at 2 58 27 PM

**Comment by dirien** [comment]
Update: made the lastSyncTime optional via url flag, as @alexmt suggested.

image

**Comment by reginapizza** [comment]
Hi @dirien! Sorry for not reviewing this sooner, I misses the notification for it and it was lost until I found this issue again in open pull requests :sweat: 

I tried it out locally and it seems to work fine, my only issue is with the spacing on the boxes... I'm not sure it really fits with the widths of the boxes correctly in some cases, like this that I just tried: 

lastSyncedStatusBadge

If you make any updates to this I promise to review it much quicker next time :sweat_smile:

**Comment by dirien** [comment]
hi @reginapizza, ok will do the changes and let you now 😄

**Comment by crenshaw-dev** [comment]
Closing for now. @dirien lmk if you want to pick this back up!

**Pull request closed without merging**
