### PR TITLE
docs:  Fix typo in user management doc

### PR DESCRIPTION
**Pull request by sbose78**
Only a minor docs fix 📜 

----
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
I'm unsure about whether it's correct to replace `when` with `with` here, because it changes the meaning of the sentence imho. :thinking: 

But I'm no native speaker, so maybe someone else may want to comment?

**Comment by sbose78** [comment]
@jannfis check now? 🤔 I hope I'm not misreading the sentence altogether.

**Comment by jannfis** [comment]
Awesome, thank you. That keeps the meaning of the sentence, but makes it much more readable/understandable!

**Comment by jannfis** [comment]
The DCO is a diva...

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
