### PR TITLE
fix: update min CLI version to 1.4.0

### LINKED ISSUE #3402: error: code = Unimplemented desc = unknown method ListRepositories
**Describe the bug**

I'm logged into argocd via the cli. I can list/sync/create applications. but I'm receiving an error when I try to list the repos via the cli.

When I run:

`argocd repo list`

I'm receiving:

`FATA[0001] rpc error: code = Unimplemented desc = unknown method ListRepositories`

version:
v1.5.1+8a3b36b

**Expected behavior**

A list of the repositories which I can see are available and authenticated in the GUI.

### PR DESCRIPTION
**Pull request by alexmt**
Closes #3402 

PR updates min required CLI version to 1.4.0

### CODE REVIEW

**Comment by jannfis** [comment]
Hm, I think this change is necessary, but it won't fix the mentioned issue. The issue creator of #3402 uses a 1.5 CLI with a 1.3 server, and the recent CLIs use `ListRepositories()` on repo API, which only exists in server since v1.4. I think the CLI needs to be adapted to use the old API method in order to be downwards compatible.

**Comment by jessesuen** [comment]
In the repo server I see that we have `ListRepositories` and `List`, with `List` being deprecated. I actually don't agree that List should be deprecated, especially since we are keeping the List() methods in the other services. Can we solve this by simply moving back to List?

**Comment by jannfis** [comment]
>  Can we solve this by simply moving back to List?

Yes, that is actually the fix for the issue. However, we really need to find a way to get rid of these annoying swagger mixins IMHO.

**Comment by jannfis** [comment]
Correct fix is submitted via #3418

**Review by jannfis — APPROVED** [review]
I agree we should do this.

**Pull request merged**
