### PR TITLE
feat: display k8s object CREATED_AT time in local time instead of UTC (#4347)

### PR DESCRIPTION
**Pull request by bukbuk1231**
Inspired by #4347 

UI now display the k8s object's CREATED_AT attribute in local time instead of UTC before.
WX20200920-143247@2x

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
Please fix the linting issue and we can merge:
```
yarn lint --fix --project . 
```

**Comment by bukbuk1231** [comment]
I've ran the yarn lint --fix --project .  ​command locally without problem, also pushed, but the yarn lint failed on GitHub. Is it an issue or not?

________________________________

**Comment by alexmt** [comment]
@bukbuk1231 strange. Looks like `yarn lint --fix --project .  ` formatted everything slightly diffrerently. I'm guessing you have a different version of some npm package. 

I would suggest to try install the same node version as CI (v11.15.0), run `yarn install`, and then run `yarn lint --fix --project .  ` again.

**Comment by bukbuk1231** [comment]
@alexmt Great. I've tried node 11.15.0 and it worked.

**Review by alexmt — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
