### PR TITLE
fix:  Drop all references to exec unless the feature is enabled

### LINKED ISSUE #9920: Drop all references to exec unless the feature is enabled
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The UI needs to drop all references to exec unless the feature is enabled.
The pod details page do not show the terminal tab, but context menu doesn't have the same rule.

**To Reproduce**

- Install ArgoCD v2.4.0 or above
- *Do not* enable 'exec' feature trought CofigMap argocd-cm.

**Expected behavior**

The UI shows exec option on context menu of a pod.

**Screenshots**

173369827-e3d05a27-9fd5-48fa-8cc2-74165a2345d6
173369809-37d667e5-31da-42eb-965f-d65307a31d5f

**Version**

```shell
❯ argocd --server xxxxxx version
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:38:43Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.4.0+91aefab
```

### PR DESCRIPTION
**Pull request by Kerwood**
Signed-off-by: Patrick Kerwood <patrick@kerwood.dk>

Fixes #9920

 The "Terminal" tab on a Pod resources details page and the "Exec" option on the Pod action menu, will only show if the exec feature is enabled and the user has the proper exec permissions.

### CODE REVIEW

**Comment by Kerwood** [comment]
Why was the integration testes cancelled?

**Comment by crenshaw-dev** [comment]
@Kerwood I think the rest were cancelled after one failed. The test is flaky. Re-triggering...

**Review by crenshaw-dev — APPROVED** [review]
Local test looks good. Thanks @Kerwood!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.9.

**Pull request merged**
