### PR TITLE
fix: update container log view on select

### LINKED ISSUE #13410: select container to view log UI it's not update.
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

After upgrade argocd to version 2.7.0 when select container to view log UI it's not update correct container log. 

image

**To Reproduce**

**Expected behavior**

update correct container log. 

**Version**

```shell

    "Version": "v2.7.0+c592219.dirty",
    "BuildDate": "2023-05-02T00:14:18Z",
    "GitCommit": "c592219140e5f48b6849f3f9a8f7aed6047d54fa",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by ashutosh16**
fixes: https://github.com/argoproj/argo-cd/issues/13410

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by ashutosh16** [comment]
@rouke-broersma  Would you be able to test the fix?

**Comment by rouke-broersma** [comment]
@ashutosh16 it's midnight here so not until Monday.

**Comment by leoluz** [comment]
> I am not currently able to test this unfortunately.

@rouke-broersma Is this for personal reasons or there is something that we could do to help you with that?

**Comment by rouke-broersma** [comment]
> > I am not currently able to test this unfortunately.
> 
> @rouke-broersma Is this for personal reasons or there is something that we could do to help you with that?

Other priorities at work. I'm testing now however I've never setup argocd local development so might take a while. Not sure if I get it done today with all the tools that need to be installed and such.

**Comment by rouke-broersma** [comment]
@ashutosh16 looks fixed to me:

container 1:

image

Container 2:

image

**Review by leoluz — APPROVED** [review]
LGTM

**Comment by rouke-broersma** [comment]
@leoluz how do we get this merged now? 😁

**Comment by leoluz** [comment]
@rouke-broersma I want to merge this today. @ashutosh16 is working on the e2e tests and will merge as soon as I hear from him. 👍🏻

**Comment by leoluz** [comment]
> Will this land in v2.7.2 by chance?

@booleanbetrayal Yes. This will be part of the v2.7.2 patch release

**Pull request merged**
