### PR TITLE
fix(#18495): Add Alternate color of resources in sync panel

### PR DESCRIPTION
**Pull request by xyq175com**
Fixes [ISSUE #18495]

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
Would like to bring this up in the maintainer's meeting to get feedback before merging. Add this "request changes" as a block for that meeting.

**Review by rbreeze — DISMISSED** [review]
This is great. Only concern: how does it look in dark mode? Based on this CSS, I don't think it would adapt

**Comment by crenshaw-dev** [comment]
Yeah, dark mode needs work: 
image

**Comment by xyq175com** [comment]
@rbreeze @crenshaw-dev I have updated the code for adoption of dark mode, please help review. Thank you.

**Comment by xyq175com** [comment]
@todaywasawesome @rbreeze  Please help review when you have time, thank you.

**Review by todaywasawesome — APPROVED** [review]
Lgtm!

**Comment by xyq175com** [comment]
@rbreeze  Can you help review this, thank you!

**Comment by xyq175com** [comment]
@wanghong230  @christianh814  when you get a chance wonder if you could help review this PR? Many thanks for your help in advance.

**Comment by xyq175com** [comment]
Can someone from this group help review and merge the pr since this pending long time...

**Comment by pasha-codefresh** [comment]
@xyq175com me or @reggie-k will review it until EOW

**Review by reggie-k — CHANGES_REQUESTED** [review]
It looks good! 
The only thing is that for long resource names the green status icon appears out of the line, please see screenshot.

Screenshot 2024-09-04 at 10 05 29

**Comment by xyq175com** [comment]
> It looks good! The only thing is that for long resource names the green status icon appears out of the line, please see screenshot.
> 
> Screenshot 2024-09-04 at 10 05 29

Ok, I will update style to prevent overflow.

**Comment by xyq175com** [comment]
> It looks good! The only thing is that for long resource names the green status icon appears out of the line, please see screenshot.
> 
> Screenshot 2024-09-04 at 10 05 29

Yes make sense, but I dont think this is related to this PR, this PR is address "the Add Alternate color of resources" issue. Could we create another issue for this?

**Comment by pasha-codefresh** [comment]
@xyq175com you are right, but the problem that with your changes this issue start to be visible. I would fix it in this PR if it is not super complex

**Comment by xyq175com** [comment]
@pasha-codefresh I have updated the fix, please help review. thank you

**Comment by xyq175com** [comment]
@pasha-codefresh @reggie-k  please help review when you have time, the issue you methioned is been fixed.

**Review by reggie-k — APPROVED** [review]

**Comment by xyq175com** [comment]
Thanks for the reviews @reggie-k , but i still have @rbreeze request changes which block the PR been merged. @rbreeze Can you help review this, this has been blocked for long time.

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
@rbreeze could you please take a look ?

**Comment by xyq175com** [comment]
@rbreeze Can you take a look this?

**Comment by xyq175com** [comment]
@rbreeze Could you please help review the changes, thank you!

**Comment by xyq175com** [comment]
@rbreeze please help review when you have time, thank you

**Pull request merged**
