### PR TITLE
fix: values should always be visible, even when they are empty (#11676)

### LINKED ISSUE #11676: Parameters > Values text entry broken for applications without existing values by #11316
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

From ArgoCD v2.5.3 -> v2.5.4, the freeform Parameters > Values section does not render the textarea unless there are already values defined. This breaks several operational workflows through the web UX. This appears to be a result of this [new null check](https://github.com/argoproj/argo-cd/pull/11316/files#diff-5aa688c8363519e0872e7dc3c5fec9b665f7b3ee2cc6db59d14e6ac2eeef1907R193-R193) on #11316 .

**To Reproduce**

- Upgrade from v2.5.3 -> v2.5.4. 
- View an application where no freeform value overrides were specified and note that no textarea for input is provided. 
- View an application where freeform value overrides were already provided and note that the textarea is presented.

**Expected behavior**

Textarea is always rendered regardless of existing values.

**Screenshots**

No Pre-Existing Values - No "Values" section
Screenshot 2022-12-12 at 4 49 28 PM

Pre-Existing Values - "Values" section
Screenshot 2022-12-12 at 4 50 18 PM

**Version**

```shell
argocd: v2.5.4+86b2dde
  BuildDate: 2022-12-06T20:09:11Z
  GitCommit: 86b2dde8e4bf1187acd2b4294e94451cd104dad8
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.5.4+86b2dde
```

**Logs**

NA

### PR DESCRIPTION
**Pull request by alexef**
fixes: #11676 

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@alexef with removal of the expandable, are we going to end up with very very large values blocks taking too much vertical UI space?

**Comment by alexef** [comment]
@crenshaw-dev no, the expendable doesn't make sense there. it's already present on `view`, we shouldn't be additionally printing it on `edit`

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc5.

@alexef would you mind opening a PR to apply the change to the release-2.5 branch? I'm getting conflicts and am scared of frontend surgery.

**Comment by alexef** [comment]
I don't mind, will do

**Comment by alexef** [comment]
sorry for the delay: https://github.com/argoproj/argo-cd/pull/12139

**Pull request merged**
