### PR TITLE
fix: Corrected metric name in example grafana dashboard

### PR DESCRIPTION
**Pull request by deepakpunjabi**
Checklist:

* [x] (b) this is a bug fix and (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note). - No issue found
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them. - NA
* [ ] Does this PR require documentation updates? - No
* [ ] I've updated documentation as required by this PR. - NA
* [ ] Optional. My organization is added to USERS.md. - No
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by deepakpunjabi** [comment]
@alexmt please check and let me know if I should add same changes for legacy-dashboard as well: https://github.com/argoproj/argo-cd/blob/master/examples/dashboard-legacy.json

**Comment by jessesuen** [comment]
@deepakpunjabi it's hard to see what this is fixing from the code change, do you have a screenshot of what this is fixing?

**Comment by alexmt** [comment]
I think there is a discrepancy between argocd helm and kustomize manifests. Helm chart uses `argocd-application-controller-metrics` and kustomize `argocd-metrics`. So we cannot just change dashboard but we can change either helm or kustomize.

**Comment by jessesuen** [comment]
Thanks @alexmt

So it seems this PR cannot be accepted since it breaks the "normal" installation of the argo-cd manifests. The proper solution should be to duplicate the dashboard json in the helm repo, and parameterize the metric name in the dashboard to match the helm name.

**Pull request closed without merging**
