### PR TITLE
chore: Remove sleep from when/then in e2e tests

### LINKED ISSUE #21007: Try optimizing e2e tests by removing potentially redundant sleeps from When/Then
# Summary

One example is When, which has a sleep for 1 second, e.g. https://github.com/argoproj/argo-cd/blob/02d6866f8a8276c455986672f2e8709232292e76/test/e2e/fixture/applicationsets/context.go#L29-L33

Maybe it can be removed or reduced. This would require some exploration and experimentation.

# Motivation

Improve e2e tests run time.

# Proposal

Explore why certain sleeps are there and experiment with removing them.

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
These sleeps might be unnecessary, remove them and check the e2e tests.

Closes #21007

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by andrii-korotkov-verkada** [comment]
Turns out we can just do it, saves ~5 min.

Before:
Screenshot 2024-11-29 at 6 36 49 PM
Screenshot 2024-11-29 at 6 36 55 PM

After:
Screenshot 2024-11-29 at 6 36 24 PM
Screenshot 2024-11-29 at 6 36 32 PM

**Comment by revitalbarletz** [comment]
One question, why were the sleep there in the first place?

**Comment by andrii-korotkov-verkada** [comment]
> One question, why were the sleep there in the first place?

I don't know, I couldn't find an explanation, but the code is very old.

**Review by crenshaw-dev — APPROVED** [review]
Seems fine, let's give it a whirl. If we see an increase in flakes, we'll tackle those.

**Pull request merged**
