### PR TITLE
fix: add gofmt to golangci-lint in Makefile and .github/workflows/ci-build.yaml

### PR DESCRIPTION
**Pull request by Calchan**
Out of curiosity I ran `gofmt` at the top of the repo and it found quite a few formatting issues and simplifications. This PR adds `gofmt` to `golangci-lint` in `Makefile` and `.github/workflows/ci-build.yaml` to automatically detect/fix these issues in the future. It also applies the relevant changes provided by running `gofmt`.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]
LGTM 👍

**Review by ishitasequeira — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
I'm gonna save this until after we cut 2.8-rc1. Wanna avoid anything that will reduce PR velocity until then.

**Comment by Calchan** [comment]
> I'm gonna save this until after we cut 2.8-rc1. Wanna avoid anything that will reduce PR velocity until then.

No worries. Let me know when you do it and I'll rebase just before that.

**Comment by Calchan** [comment]
@crenshaw-dev I have manually rebased this in case you want to merge it since v2.8.0-rc1 has been released.

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
