### PR TITLE
feat: Allow force of basic auth for HTTP repositories

### LINKED ISSUE #6289: Use Azure DevOps Git Artefacts with PAT
# Summary

Connect a private AzureDevOps Git Repo, with PAT (Combined Token: Authenticity + Secret). As the documentation stated, I tried:
_Then, connect the repository using any non-empty string as username and the access token value as a password._
where I used the PAT as access token.

The Error I'm getting on the argOCD Side: git did not exit cleanly (exit code 128)

# Use Cases

When having the config (kustomize) stored in an AzureDevOps Git Repo.

My setup:
-  Argo CD: v2.0.1+33eaf11
-  AzureDevops2020 - Version Dev18.M170.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### LINKED ISSUE #6362: Unable to create application from a connected Azure DevOps server repository
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

After not being able to connect a private Azure DevOps server repository to ArgoCD via username and password (with error returned "Unable to connect HTTPS repository: authentication required)", I have successfully connected the repo via Personal Access Token (PAT):

image

When I try to create an application using the repository, I get the following error:

`Unable to create application: application spec is invalid: InvalidSpecError: Unable to get app details: rpc error: code = Internal desc = Failed to fetch 493dd952d54b8817daa972adc056d32a1f31231a: `git fetch origin --tags --force` failed exit status 128: fatal: Authentication failed for '<redacted>/_git/argocd-apps/'`

PAT used has Full Access scope and works with `git` operations to the repo, which was tested locally with `git clone` and `git fetch origin --tags --force` which is reported in the ArgoCD error message.

My guess is that this is related to Azure DevOps not allowing PAT authentication with a non-empty username (tested locally with `git`), while ArgoCD requires username to be a non-empty string when adding repository credentials. ArgoCD is probably passing this username to Azure DevOps which results in the mentioned error. Related issue: #6098  

**To Reproduce**

* Create a repository on Azure Devops server
* Create an Azure DevOps server Personal Access Token (PAT) with Full Access scope
* Add the repository to ArgoCD via HTTPS using the PAT
* Try to create an ArgoCD application using the added repository

**Expected behavior**

ArgoCD application is successfully created.

**Screenshots**

image

**Version**

```shell
argocd-server: v2.0.0+f5119c0
  BuildDate: 2021-04-07T06:00:33Z
  GitCommit: f5119c06686399134b3f296d44445bcdbc778d42
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

### LINKED ISSUE #11914: Add option to force usage of HTTP basic auth for HTTP connections to Git
## Problem statement

Currently, Argo CD does not work with Git repositories hosted on Azure DevOps Server on-premise installations and accessed via HTTPS using a personal access token. When trying to connect such a repository from Argo CD, the authentication will always fail.

After some investigation using a trial installation of Azure DevOps Server on-premise, I came to the conclusion that Git refuses to perform HTTP basic authentication against Azure DevOps. The root cause for this is that Git is using libcurl under the hood, and configures [1] it to "automatically select the one it finds most secure" [2]. The on-premise installation of Azure DevOps provides multiple HTTP authentication schemes for requests to its Git server, namely NTLM, SPNEGO and HTTP basic authentication.

In this scenario, Git will pick NTLM as the authentication scheme for the HTTP request on negotation, but Azure DevOps is not able to authenticate a personal access token using NTLM as it expects the PAT to be sent encoded as HTTP basic auth request. The NTLM authentication will only work with Windows users, and only by using a username and password combination.

Microsoft's official documentation [3] suggests to users that want to use PAT to explicitly pass the basic auth HTTP header when executing Git, thereby bypassing Git's authentication scheme negotiation. This works because authentication negotiation is only performed when the server returns a 401 error on the first (unauthenticated) request, and along with the response the server sends the list of supported authentication methods. If the basic auth HTTP header is passed as part of this initial request, the server will never return a 401 but happily accept the submitted credentials.

There's some ongoing problems with Azure DevOps Server within the community:

* #6289
* #6362

## Possible solutions

I see the following options to make Argo CD work with Git repositories hosted on Azure DevOps Server and accessed via HTTPS:

1. Submit a feature PR (or feature request) to Git that allows to override the preferred usage of HTTP authentication scheme
2. Disable the NTLM authentication provider on the Azure DevOps server
3. Add an option to Argo CD to send the HTTP basic auth header with each request when connecting to Azure DevOps repository

**Option 1** would IMHO be the *correct* fix for this issue and also definitely a fun contribution. However, it's uncertain whether such a change would be accepted by the Git project. And even when such a contribution would be accepted and eventually end up in a Git release, it would also be uncertain when a version containing this feature would land in in the distribution used by Argo CD's container images.

**Option 2** is not supported by Microsoft, and would possibly lock-out legitimate Azure DevOps Server users from the repositories on the server, if they chose to authenticate via username and password (thereby requiring NTLM). Worse yet, their SSH implementation lags behind a couple of years and doesn't work with more recent OpenSSH versions out-of-the-box. Making Azure DevOps work with Argo CD via SSH would require enabling deprecated ciphers in the SSH client [4], which is also considered pretty insecure. They are working on a fix [5], but the issue is open since 2018 [sic].

**Option 3** would be a implementing a change to Argo CD, and could be implemented as an option on the repository configuration, e.g. "Force HTTP basic auth for this connection". However, passing the credentials as a HTTP header on the command line is insecure - not only could a malicious user snoop on the process table to retrieve the credentials, the credentials could end up in some log files if not implemented carefully enough. However, this seems to be the only viable option to have Argo CD and Azure DevOps Server play nicely together.

## Proposed change to Argo CD

I propose that a new option for repository configuration should be introduced, which allows to force the use of HTTP basic auth instead of having Git/libcurl negotiate the preferred authentication method.

In declarative configuration, this option could be named `forceBasicAuth` and accept a boolean value, with the default being `false`.

In the UI's repository configuration page, there should be a corresponding checkbox with a label reading `Force HTTP basic auth for this connection (insecure)` or something around these lines.

In the CLI's `argocd repo` commands, a new switch to enable or disable this setting should exist. The switch could be named `--force-basic-auth`, and also accept a boolean value.

If this option is set to `true` for a repository, then the HTTP basic auth string will be computed by Argo CD (i.e. the base64 encoded value of the `<username>:<password>` string) and the Git client's execution environment modified to include the additional header on the command line with each call, e.g. `git -c http.extraHeader="Authorization: Basic ${computed_string}" clone ...`

Since command execution is logged in Argo CD, we would also have to adapt the log redactor to redact the additional header on the command line before it's being logged, or when an error message is passed back to the user.

## References 

[1] https://github.com/git/git/blob/a38d39a4c50d1275833aba54c4dbdfce9e2e9ca1/http.c#L838
[2] https://curl.se/libcurl/c/CURLOPT_HTTPAUTH.html
[3] https://learn.microsoft.com/en-us/azure/devops/organizations/accounts/use-personal-access-tokens-to-authenticate?view=azure-devops&tabs=Linux#tabpanel_1_Linux
[4] https://learn.microsoft.com/en-us/azure/devops/repos/git/use-ssh-keys-to-authenticate?view=azure-devops#q-what-do-i-do-if-im-still-prompted-for-my-password-and-git_ssh_commandssh--v-git-fetch-shows-no-mutual-signature-algorithm
[5] https://developercommunity.visualstudio.com/t/support-non-rsa-keys-for-ssh-authentication/365980

### PR DESCRIPTION
**Pull request by jannfis**
Change introduces a new boolean setting for repositories: `forceHttpBasicAuth`. If set to true, Argo CD will make the Git client send an `Authorization: Basic ...` header to the repository server, thereby bypassing any authentication scheme negotiation done by Git (or libcurl, to be precise).

Closes #11914
Fixes https://github.com/argoproj/argo-cd/issues/6289
Fixes https://github.com/argoproj/argo-cd/issues/6362

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
lgtm, thanks @jannfis!

**Review by crenshaw-dev — COMMENTED** [review]
Should we also update https://argo-cd.readthedocs.io/en/latest/operator-manual/declarative-setup/ and argocd-repositories.yaml with examples?

**Comment by jannfis** [comment]
Good thinking, I'll update this PR to include some docs. Thanks!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc7.

**Pull request merged**
