### PR TITLE
chore: switch from yarn to pnpm for performance

### PR DESCRIPTION
**Pull request by rbreeze**
Yarn (previous): 
```
yarn install  58.79s user 12.72s system 108% cpu 1:06.12 total
```

pnpm:
```
pnpm i  50.83s user 15.17s system 118% cpu 55.872 total
```

pnpm saves about 10 seconds on installation; however, ~50 seconds of install time comes from the `node-sass` post-install script, which is constant amongst both package managers. Adjusting for this, the yarn install time would be ~16sec, and pnpm ~6sec. This is ~1.6x performance improvement.

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
It seems that the image we're using to build the UI (`docker.io/library/node:12.18.4`) doesn't contain `pnmp`, and thus, image building fails.

**Review by jannfis — CHANGES_REQUESTED** [review]
Can we please hold this to after v2.2 has been released?

**Comment by rbreeze** [comment]
@jannfis Yeah, I updated #7626 to install pnpm in the `ci-build` action, but I didn't update the other action that's erroring for the same reason. Will fix today 

I will close this PR in favor of #7626 (which is a branch of this PR), because most of the performance improvement comes from switching to dart-sass.

**Comment by rbreeze** [comment]
@jannfis Sorry, I just noticed that you posted a comment this morning in addition to your comment yesterday. 

This can definitely wait until after 2.2! I was thinking it should wait until 2.3.

**Pull request closed without merging**
