### PR TITLE
docs: fix deep links docs formatting

### PR DESCRIPTION
**Pull request by crenshaw-dev**
RTD rendered the previous format poorly. This looks nicer.

### CODE REVIEW

**Review by gdsoumya — APPROVED** [review]
Thanks for fixing it @crenshaw-dev. LGTM!

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Review by leoluz — APPROVED** [review]
LGTM

**Pull request merged**
