### PR TITLE
feat: Cassandra Cluster CR health check Closes #6843

### LINKED ISSUE #6843: Feat: Cassandra Cluster Health Check
# Summary

Adding a simple health check for the cassandra cluster CR

# Motivation

Easy visibility for Cassandra cluster state in the argo UI and the ability to incorporate this CR in sync waves

# Proposal

The standard way for CR health checks.

### PR DESCRIPTION
**Pull request by BenManifold**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Hey @BenManifold , thanks for this PR. Can you please check indentation in `health.lua` to be consistent with the other health checks? It looks a little weird to me.

**Comment by BenManifold** [comment]
I see what you mean, the convention seems to be tabs indenting by two
spaces. I'll update it.

**Comment by jannfis** [comment]
Oops, it seems there are some additional changes in your PR that should not be there. Can you please check?

**Comment by BenManifold** [comment]
yeah, I noticed that as well, seems like i need to manually resolve the diff

**Comment by BenManifold** [comment]
My fork is pretty much hosed from trying to rebase, as per the signoff instructions.

**Comment by BenManifold** [comment]
I had to create a new fork and start the PR over again. I would appreciate
it if you gave that one a look. Sorry for the confusion.
https://github.com/argoproj/argo-cd/pull/7017

**Pull request closed without merging**
