### PR TITLE
chore(deps): Upgrade aws-sdk-go to support eks pod identity

### PR DESCRIPTION
**Pull request by csantanapr**
This update the aws-sdk-go so it will support dynamic auth token ([EKS Pod Identities](https://aws.amazon.com/blogs/aws/amazon-eks-pod-identity-simplifies-iam-permissions-for-applications-on-amazon-eks-clusters/)).

**EKS Pod Identity Affects 3 capabilities in ArgoCD:**
* Hub&Spoke model awsAuthConfig (to remote clusters)
    * https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#eks
    * https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/gitops/multi-cluster-hub-spoke-argocd
* Notification via SQS
    * https://argo-cd.readthedocs.io/en/stable/user-guide/subscriptions/
    * https://argocd-notifications.readthedocs.io/en/stable/subscriptions/
    * https://github.com/argoproj/notifications-engine/blob/master/docs/services/awssqs.md
* SCM Provider Generator for codeCommit AWS (Application Set Controller)
    * https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/#aws-iam-permission-considerations

This is a new PR that superseeds PR https://github.com/argoproj/argo-cd/pull/16641
@ROunofF and myself worked on this and the testing of the change on EKS, is just I was having trouble with the rebase and conflicts

This PR picks up the changes to argo-notifications-engine

---------

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]
LGTM - will you guys be updating the EKS docs to show how to make use of Pod Identity?

**Comment by csantanapr** [comment]
@blakepettersson 
>LGTM - will you guys be updating the EKS docs to show how to make use of Pod Identity?

You mean the docs here in argocd? https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#eks
Yes we intend to doc it

**Comment by blakepettersson** [comment]
@csantanapr I think you need to run `make codegen-local`

**Comment by csantanapr** [comment]
@blakepettersson let give it a try to `make codegen-local`

**Comment by csantanapr** [comment]
what I did was
- update the go mod and sum with the new dependencies
- `make image`
- tested the image on EKS and all integrations

**Review by ishitasequeira — APPROVED** [review]
LGTM!! Just needs a `make codegen` fix

**Comment by csantanapr** [comment]
@blakepettersson I don't think something else is need it, the codegen is something about md files not related to go codegen

**Comment by blakepettersson** [comment]
@csantanapr `codegen` invokes `notification-docs` but you could just run that task to be fair, so `make notification-docs`

**Comment by csantanapr** [comment]
@blakepettersson The `make notification-docs` did the trick !

**Comment by blakepettersson** [comment]
@csantanapr good to hear! For future reference, in order to run `codegen-local` you first have to run `make install-tools-local`

**Comment by csantanapr** [comment]
Fixes #17064

**Comment by csantanapr** [comment]
@blakepettersson thanks for the tip on `make install-tools-local`

**Comment by csantanapr** [comment]
@ishitasequeira @blakepettersson let me know what else is required, otherwise I think is good to get merge

**Comment by csantanapr** [comment]
THANK YOU 🙏  @ishitasequeira for merging 🎉

**Pull request merged**
