### PR TITLE
feat: autosync protection

### PR DESCRIPTION
**Pull request by mayzhang2000**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by mayzhang2000** [comment]
fixed #3484

**Comment by loreleimccollum-work** [comment]
@mayzhang2000 can I ask a question about this fix -- prior to the release this is in, we would see our resources automatically sync and prune and delete the resources. Now with this fix we see them stuck with this message and appear as out of sync.
Is there a way to get around this protection feature?

**Comment by mayzhang2000** [comment]
@loreleimccollum-work This is protection for autosync with prune when all resources require pruning. Without this all resources for the app will be pruned. Are you in the situation that your app has resources in repo, but get this message?

https://github.com/argoproj/argo-cd/blob/master/controller/state.go#L463

**Comment by jessesuen** [comment]
@loreleimccollum-work is your use case such that you *want* to allow "empty" applications (applications which have zero resources), and the feature no longer allows that?

**Comment by citizenken** [comment]
@loreleimccollum-work's colleague here. Let me add a bit more detail.

We want to maintain a separation of access from Jenkins and the cluster. To do so, during our PR Jenkins pipeline we commit to an app-of-app-style registry, creating a new entry for the PR build. When Argo syncs the app-of-apps, it creates the PR deployment in the cluster. If the deployment is successful (using argo-workflows to validate), Jenkins commits again to the app-of-app registry, removing the PR app it created. 

This is when the problem happens. We'd expect when Argo syncs the app-of-apps, it would remove the PR app deployment and all the resources created. Instead, we're seeing this message, and the PR app deployment hangs around for at least one more sync.

I think the app-of-apps design is fairly common and would be surprised if others using that design wouldn't run into this issue. Our use-case might be kind of fringe, but if there was a configmap toggle that could be added or something, that would be ideal.

**Comment by mayzhang2000** [comment]
This command can be used to remove the resources. `argocd app sync <your app name> --prune`.

**Comment by citizenken** [comment]
Thanks @mayzhang2000, but we don't want to allow that level of access between Jenkins and Argo, which is why we were relying on the auto sync feature to prune old applications that had been removed from the git repo. I think that if Argo is supposed to use the repo as the source of truth, removing an application from an app-of-apps repo should prune it from the cluster. After all, that change should have followed a review process and is considered a non-accidental delete.

**Comment by jessesuen** [comment]
Would a flag to allow automated syncs for "empty" applications help (default false)? e.g.:

```yaml
  syncPolicy:
    automated:
      allowEmpty: true   # indicates we allow automated sync to zero-resource applications
```

**Comment by jessesuen** [comment]
I think we should revert this change in v1.7 and introduce the new default behavior and flag in v1.8.

**Comment by mayzhang2000** [comment]
This change is reverted from 1.7. https://github.com/argoproj/argo-cd/commit/001c2272222aa353df6a80715fea402207f596e7

New issue is created: https://github.com/argoproj/argo-cd/issues/4464

**Comment by loreleimccollum-work** [comment]
Wow, Thanks for the quick action on this! Yeah I think having the flag to go with it, since it does change default behavior will be super helpful and making sure the sync docs are updated to discuss this. I can see how some would want this enabled, but others may not given your usecase @mayzhang2000

**Comment by mayzhang2000** [comment]
A new PR is created for V1.8: https://github.com/argoproj/argo-cd/pull/4475

**Pull request merged**
