### PR TITLE
fix: Resource list in sync page msg style#10887

### LINKED ISSUE #10887: Resource list in sync panel is jumpy on click
**Describe the bug**

When I uncheck the first item in the sync panel resource list, a warning appears, pushing all the list items down. If a user has scrolled far down the list, they won't see the warning, but they will feel the jump.

The warning is small. I'd propose that we leave the necessary space for the warning when all resources are checked, and then make the warning visible after the first item is unchecked.

**To Reproduce**

1. Create or open an application in the Argo CD UI
2. In the main Applications page, click the Sync button on the application's card
3. In the resources list at the bottom of the sync panel, uncheck any resource
4. Notice the jump

**Expected behavior**

I'd expect the list to remain still while I check and uncheck items.

**Screenshots**

https://user-images.githubusercontent.com/350466/194935637-2b675df6-03b6-4008-8294-782e9f70958c.mov

**Version**

2.5.0-rc1

### PR DESCRIPTION
**Pull request by JessieTeng89**
fix: Resource list in sync panel is jumpy on click
Fixes https://github.com/argoproj/argo-cd/issues/10887

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks @JessieTeng89! Can you check the lint logs in the build check list?

**Comment by JessieTeng89** [comment]
> Thanks @JessieTeng89! Can you check the lint logs in the build check list?

Hi @crenshaw-dev I have fixed the lint issue, but got another e2e testing error, it show install K3s failed, do you have any idea?

**Comment by rbreeze** [comment]
@JessieTeng89 It's most likely a flakey E2E test; we can keep re-running it until it passes

**Review by rbreeze — APPROVED** [review]

**Comment by JessieTeng89** [comment]
> @JessieTeng89 It's most likely a flakey E2E test; we can keep re-running it until it passes

Thanks for your, it is successful now after re-trigger, can I know how I can merge it to master branch?

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.2 for 2.2.15, release-2.3 for 2.3.11, release-2.4 for 2.4.16, and release-2.5 for 2.5.0-rc4.

**Pull request merged**
