### PR TITLE
fix: removed pkce code challange check for WebUI #16649

### LINKED ISSUE #16649: Azure not supported for WebUI PKCE Auth Code Flow
## Describe the bug

In the upcoming `v2.10.0-rc1` release, @Marvin9 added support for using authorization code flow with PKCE in the webUI, which is lovely. :heart: 
 - https://github.com/argoproj/argo-cd/pull/15889

Unfortunately Azure is non-compliant with RFC8414 standard because the `/.well-known/openid-configuration` endpoint is missing the `code_challenge_methods_supported` property. 
The ArgoCD login flow is stopped checking for that specific property here.
https://github.com/argoproj/argo-cd/blob/3224102664b747e88e7330e59b3b44bc9c28cd66/ui/src/app/login/components/utils.ts#L76-L80

Other projects seem to have the same issue, like kubelogin.
 - https://github.com/int128/kubelogin/issues/858

This was brought to the attention of Microsoft in January 2021 and I do not think that they intend to do anything about it.
 - https://learn.microsoft.com/en-us/answers/questions/218113/openid-connect-authorization-code-flow-with-proof

## Proposal
 Maybe have a setting something like, `forcePKCECodeChallengeMethod: S256` that would skip the `code_challenge_methods_supported` property check ?

### PR DESCRIPTION
**Pull request by Kerwood**
Fixes #16649 
Cherry-pick for `2.10.0`

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by Kerwood** [comment]
@alexmt Could I get you to have a look at this very simple PR :)

**Comment by Marvin9** [comment]
I still think that if there is a way to ignore this [check only for Azure](https://github.com/argoproj/argo-cd/issues/16649#issuecomment-1863390579) in frontend itself, we should go with that.

But if there isn't then I think this approach would be better than adding flag in config map if there are no security concerns for this generalisation.

**Comment by Kerwood** [comment]
I do not think that making Azure specific code is a good idea, or any other IDP specific code for that matter.
Either the check should be removed or there should be  a "skip check" setting, but since the CLI does not have the check, we decided to remove it.

**Review by Marvin9 — APPROVED** [review]
Since we follow same approach as in CLI, this LGTM.

@alexmt @crenshaw-dev or any reviewer needs to approve

**Review by alexmt — APPROVED** [review]

**Comment by alexmt** [comment]
Thank you for confirming @Marvin9 !

**Comment by michael-basil** [comment]
I tested this fix off of the master branch.  It worked well!   Would someone be able to point me to determine when this would go into a release?

**Pull request merged**
