### PR TITLE
fix: core-install.yaml always refers to latest argocd image

### LINKED ISSUE #7278: core-install.yaml always refers to latest argocd image
Hi,

when getting the `install.yaml` for a specific version, we get expected behavior:

```console
$ curl -s https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/install.yaml | grep image:
        image: ghcr.io/dexidp/dex:v2.27.0
        image: quay.io/argoproj/argocd:v2.1.2
        image: redis:6.2.4-alpine
        image: quay.io/argoproj/argocd:v2.1.2
        image: quay.io/argoproj/argocd:v2.1.2
        image: quay.io/argoproj/argocd:v2.1.2
```

For `.../argo-cd/v2.1.2/manifests/...` we get `image: ... v2.1.2`

when getting the `core-install.yaml` for a specific version, we always the the `latest` image tag:

```console
$ curl -s https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.2/manifests/core-install.yaml | grep image:
        image: redis:6.2.4-alpine
        image: quay.io/argoproj/argocd:latest
        image: quay.io/argoproj/argocd:latest
```

Does it need to be corrected?

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes #7278

### CODE REVIEW

**Review by mayzhang2000 — APPROVED** [review]
LGTM

**Comment by edwardcookemacu** [comment]
Doesn't this change make it so that if someone uses the v2.1.3 install manifests it would actually install the latest image, like a v2.3.5 or whatever version which may or may not work with the v2.1.3. Or am I missing something?

**Comment by alexmt** [comment]
This change updates the shell script which is used during release time and updates image in manifests in release branch. The most recent release has correct image in core-install.yaml:

```
curl -s https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.3/manifests/core-install.yaml | grep 'image:'                                  
        image: redis:6.2.4-alpine
        image: quay.io/argoproj/argocd:v2.1.3
        image: quay.io/argoproj/argocd:v2.1.3
```

**Comment by edwardcookemacu** [comment]
I was meaning manifest in the v2.1.3 tag. So we need to reference the release-2.1 branch and use that manifest and not the release tag now? Because your release notes reference the v2.1.3 tag and not release-2.1 branch.

**Pull request merged**
