### PR TITLE
fix(health): Handling SparkApplication CRD health status if dynamic allocation is enabled (#7557)

### LINKED ISSUE #7557: sparkoperator.k8s.io/SparkApplication health check does not support dynamicAllocation
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`sparkoperator.k8s.io/SparkApplication` has dynamic allocation mode (`spec.dynamicAllocation.enabled: true`), which does not have key `spec.executor.instances`. However,`spec.executor.instances` is used by current health check script for `sparkoperator.k8s.io/SparkApplication`. So in dynamic allocation mode, `sparkoperator.k8s.io/SparkApplication` will never reach `Healthy` status.

**To Reproduce**

* Setup `sparkoperator.k8s.io/SparkApplication` with `spec.dynamicAllocation.enabled: true` via ArgoCD.
* `sparkoperator.k8s.io/SparkApplication` will never reach `Healthy` status.

**Expected behavior**

* `sparkoperator.k8s.io/SparkApplication` shall reach `Healthy` status when Spark application is running.

**Version**

```shell
argocd: v2.1.5+a8a6fc8
  BuildDate: 2021-10-20T15:16:40Z
  GitCommit: a8a6fc8dda0e26bb1e0b893e270c1128038f5b0f
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

### PR DESCRIPTION
**Pull request by eugen-fried**
Fixes #7557
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by pdrastil** [comment]
Hi @crenshaw-dev can you merge this please?

**Review by pdrastil — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]
That code was a pleasure to read. Very easy to follow. Thanks @eugen-fried!

**Comment by crenshaw-dev** [comment]
I plan to merge and cut a release with this next Wednesday.

**Comment by eugen-fried** [comment]
Thank you!

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Not sure what's up w/ CI. Running again.

Sorry for the delay. Looking to release this today.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc6, release-2.5 for 2.5.9, release-2.4 for 2.4.21, and release-2.3 for 2.3.15

**Pull request merged**
