### PR TITLE
feat: Add support for managedFieldsManagers in ignoreResourceUpdates (solves #15094,#15151)

### PR DESCRIPTION
**Pull request by uriariel**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Closes [ISSUE #15151]
Closes [ISSUE #15094]

### Summary
:zap::sparkles::hammer:

Added a new function to compare application state with cached state using different ignore rules, and used it in the application reconciliation process. This improves the performance and accuracy of state comparisons and reduces unnecessary diffs.

> _`CompareAppState`_
> _Now with more options - how?_
> _`isCompareWithRecent`_

### Walkthrough
*  Add and implement `CompareAppStateWithComparisonLevel` function to improve application state comparisons ([link](https://github.com/argoproj/argo-cd/pull/15137/files?diff=unified&w=0#diff-10c7b3329ba1baf707f1917325609870201d61c16fb8dbcc787c421896bd4319R65), [link](https://github.com/argoproj/argo-cd/pull/15137/files?diff=unified&w=0#diff-10c7b3329ba1baf707f1917325609870201d61c16fb8dbcc787c421896bd4319R345-R348), [link](https://github.com/argoproj/argo-cd/pull/15137/files?diff=unified&w=0#diff-10c7b3329ba1baf707f1917325609870201d61c16fb8dbcc787c421896bd4319R528-R543), [link](https://github.com/argoproj/argo-cd/pull/15137/files?diff=unified&w=0#diff-f952d05ea83b61f771541425e28fa3931af2f2e7950261dd59cab93bdcfe2e9eL1444-R1446))

### CODE REVIEW

**Comment by uriariel** [comment]
solves #15094,#15151

**Comment by uriariel** [comment]
its a "completion" of @agaudreault-jive's feature: https://github.com/argoproj/argo-cd/pull/13912, regarding documentation, its strongly implied today that the current `ignoreResourceUpdates` supports `managedFieldsManagers`. 
@leoluz please take a look at this PR

**Comment by agaudreault-jive** [comment]
I really dont think the behavior of `ignoreResourceUpdates` should be used to ignoreDifferences from the cluster. Ignore resource updates will only filter some cluster events to reduce the quantity of reconcile Argo has to process. It does not and should not in my opinion affect the sync behavior.

ignoreResourceUpdates is currently only configurable on the server and it is not possible to specify it on the Application. 

The documentation does not mention the usage of `managedFieldsManagers` because it is not implemented

I think ignore difference from the cluster is a good idea. I am aware of https://github.com/argoproj/argo-cd/issues/15116 that was created around this Idea, however, I think it should be implemented separately from ignoreResourceUpdates.

**Review by agaudreault — CHANGES_REQUESTED** [review]
I think this PR does not `Add support for managedFieldsManagers in ignoreResourceUpdates`, but instead, changes the semantic of ignoreResourceUpdates to a `ignoreClusterDifferences`. I think both features should not be mutually exclusive and it would be a good idea to implement a `ignoreClusterDifferences`.

**Comment by leoluz** [comment]
> I really dont think the behavior of ignoreResourceUpdates should be used to ignoreDifferences from the cluster. Ignore resource updates will only filter some cluster events to reduce the quantity of reconcile Argo has to process. It does not and should not in my opinion affect the sync behavior.

I also agree with this statement. From the code perspective `CompareAppState` function is already begging for a good refactoring. I wouldn't introduce an additional parameter in that function. 

> I think ignore difference from the cluster is a good idea. I am aware of https://github.com/argoproj/argo-cd/issues/15116 that was created around this Idea, however, I think it should be implemented separately from ignoreResourceUpdates.

I am not sure I understand the cluster ignore difference idea. That sounds like what we tried to accomplish with Ignore diffs with `manageFieldsManagers`.

**Comment by uriariel** [comment]
@leoluz @agaudreault-jive First of all sorry for the delay, I was on a vacation those days.

> I am not sure I understand the cluster ignore difference idea. That sounds like what we tried to accomplish with Ignore diffs with `manageFieldsManagers`.
`manageFieldsManagers` doesn't allow to ignore changes from the cluster only.
e.g. if I want to set `requests` in the application yamls, as so:

client git repo:
```yaml
resources:
  requests:
    cpu: 500m
```

and then ignore changes made to the requests by the VPA inside the cluster only. VPA changes `cpu` from `500m` to `100m`.
I want `argoCD` to be able to ignore those changes but don't ignore changes made to the yaml's in git.

client git repo:
```yaml
resources:
  requests:
    cpu: 600m
```

with `ignoreResourceUpdates.managedFieldsManagers` argoCD should sync this change, with `ignoreDifferences.managedFieldsManagers` argoCD won't sync this change since the `resources.requests.cpu` field is managed by the `VPA-manager`.

@agaudreault-jive I get it that this feature wasn't implemented as `ignoreClusterDifferences`, but practically it does this for `jsonPointers` and `jqPathExpression`(From the tests I've done on my cluster, maybe you can describe a scenario where it would be completely different) , you're right that to implement it for `managedFieldsManagers` in the same manner its implemented for the other specifiers is impossible since we would have to "know" the managed fields in the live object in advance.
I think this implementation gives the closest alternative to implementing `ignoreResourceUpdates.managedFieldsManagers`.

**Comment by zachaller** [comment]
There documentation is quite low on this but it sounds like another way you could think about "defaults" instead of using the requests from the resource itself is to use a policy. They mention this [here](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/README.md#limits-control) 

```
When setting limits VPA will conform to [resource policies](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L100). It will maintain limit to request ratio specified for all containers.

VPA will try to cap recommendations between min and max of [limit ranges](https://kubernetes.io/docs/concepts/policy/limit-range/). If limit range conflicts and VPA resource policy conflict, VPA will follow VPA policy (and set values outside the limit range).

To disable getting VPA recommendations for an individual container, set mode to "Off" in containerPolicies.
```

This eventually leads us to [this](https://github.com/kubernetes/autoscaler/blob/43fd1fac61168afc129310a3a9248c35f4beb445/vertical-pod-autoscaler/pkg/apis/autoscaling.k8s.io/v1/types.go#L190)
```
type ContainerResourcePolicy struct {
	// Name of the container or DefaultContainerResourcePolicy, in which
	// case the policy is used by the containers that don't have their own
	// policy specified.
	ContainerName string `json:"containerName,omitempty" protobuf:"bytes,1,opt,name=containerName"`
	// Whether autoscaler is enabled for the container. The default is "Auto".
	// +optional
	Mode *ContainerScalingMode `json:"mode,omitempty" protobuf:"bytes,2,opt,name=mode"`
	// Specifies the minimal amount of resources that will be recommended
	// for the container. The default is no minimum.
	// +optional
	MinAllowed v1.ResourceList `json:"minAllowed,omitempty" protobuf:"bytes,3,rep,name=minAllowed,casttype=ResourceList,castkey=ResourceName"`
	// Specifies the maximum amount of resources that will be recommended
	// for the container. The default is no maximum.
	// +optional
	MaxAllowed v1.ResourceList `json:"maxAllowed,omitempty" protobuf:"bytes,4,rep,name=maxAllowed,casttype=ResourceList,castkey=ResourceName"`

	// Specifies the type of recommendations that will be computed
	// (and possibly applied) by VPA.
	// If not specified, the default of [ResourceCPU, ResourceMemory] will be used.
	ControlledResources *[]v1.ResourceName `json:"controlledResources,omitempty" patchStrategy:"merge" protobuf:"bytes,5,rep,name=controlledResources"`

	// Specifies which resource values should be controlled.
	// The default is "RequestsAndLimits".
	// +optional
	ControlledValues *ContainerControlledValues `json:"controlledValues,omitempty" protobuf:"bytes,6,rep,name=controlledValues"`
}
```

It would seem then that you could instead of update the resource limits on the object in question `Deployment` etc you could define the min as a policy and adjust that in git

**Comment by zachaller** [comment]
Although after re-reading the docs again it might actually still require the limits/requests on the resource in order to figure out the ratios, is this true?

```
It will maintain limit to request ratio specified for all containers.
```

**Review by leoluz — CHANGES_REQUESTED** [review]
From the discussion we had in the contributor's meeting, it was clarified that this is not the direction that we want to go in Argo CD for a number of reasons:

- It changes the semantics of `ignoreResourceUpdates` by adding extra behaviour to it in order to address an use-case that it wasn't originally designed to.
- It creates a competition for fields ownership that could potentially drive into situations where Argo CD is in eternal sync state depending on how the application is configured.

Please consider the suggestions given during the meeting by finding alternative and better approaches to drive the behaviour you want.

If you still think that this use-case is something that Argo CD should handle, please submit a proposal with the details of how  it would behave in different edge-cases.

**Pull request closed without merging**
