### PR TITLE
feat(ui): Display event timestamps in human readable format

### LINKED ISSUE #6924: UI: change events tab to use "time ago" format to make it easier to use
Consider this:

image

Pretty hard to read eh? Was that recently, I have to stop and think.

Let see how workflows does that:

image

Oh yes! That is quite recenty.

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #6924

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexec** [comment]
Screenshot?

**Comment by rbreeze** [comment]
Screen Shot 2021-09-01 at 8 54 22 AM

**Comment by alexec** [comment]
Thank you. I don't think you need to embolden the text. Maybe instead may the full time smaller. Full time is still unreadable - could be in a human readable format? Unless you think people want to copy-and-paste it?

E.g. 3pm Thu 1st Sep 2021.

**Comment by rbreeze** [comment]
Good point. I kept the original string in case people would be annoyed about it being gone, but I think you're right - a human readable string would be better.

I also think you may be right about the events being out of order. I'll fix that too

**Review by alexmt — APPROVED** [review]
LGTM! @alexec are you fine with updated design?

**Review by alexec — APPROVED** [review]
I approve of this message.

**Pull request merged**
