### PR TITLE
fix(appset): Revert applicationset-name labels

### PR DESCRIPTION
**Pull request by speedfl**
Fixes [ISSUE #15282 ]

Purpose is to revert regression introduced by https://github.com/argoproj/argo-cd/pull/13456

Followup is to open an issue to discuss about new tracking method (using annotations) and the possible impacts

@rbreeze 
@todaywasawesome 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by ishitasequeira** [comment]
I will make sure to review the PR today!!

**Comment by speedfl** [comment]
@ishitasequeira for more context. 
The commit mentioned is introducing a regression which can be quite problematic. By adding appset name as label to the generated apps, it limits the name length to 63 chars (the max label size)

This feature was introduced in 2.8 and from what I understood it is more a nice to have which allows to do:

```
argocd app list -l appset-name=...
```

This has some workarounds

**Review by ishitasequeira — APPROVED** [review]
Thanks @speedfl for the PR!! The PR looks good for reverting the changes.

**Comment by mubarak-j** [comment]
Should this fix be cherry-picked to 2.8 branch? It appears to be missing from v2.8.3 release

**Comment by dyatlov** [comment]
@speedfl It seem didn't work.

**Pull request merged**
