### PR TITLE
fix(cli): support application in any namespace with `argocd app diff`(#13978)

### LINKED ISSUE #13978: `argocd app diff` should support application in any namespace.
# Summary

Now `argocd app diff` does not support [application in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/).
I execute `argocd app diff` in app any namespace environment, always returns diff like bellow.
```diff
-    argocd.argoproj.io/instance: NAMESPACE_APP_NAME
+    argocd.argoproj.io/instance: APP_NAME
```
This reason is that, created local object for diff does not have correct labels.
I executed bellow command.
```bash
app diff "${APP_NAME}" --exit-code=false \ 
  --port-forward \
  --port-forward-namespace "${NAMESPACE}"\
  --auth-token "${ARGOCD_TOKEN}" \
  --server-side-generate \
  --plaintext \
  --local "${PWD}" \
  --local-include "*.yaml"
```

# Motivation

I use app in any namespace and comment diff(live/local) on GitHub PR, the diff will occur every time and become noise.

# Proposal

We should use `app.InstanceName(argoSettings.ControllerNamespace)` instead of `app.Name` in `groupObjsForDiff`.
https://github.com/argoproj/argo-cd/blob/330252dffc9b6fd79724ff93eb0184a39f7389a3/cmd/argocd/commands/app.go#L1038
https://github.com/argoproj/argo-cd/blob/330252dffc9b6fd79724ff93eb0184a39f7389a3/cmd/argocd/commands/app.go#L1047

### PR DESCRIPTION
**Pull request by mugioka**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Closes https://github.com/argoproj/argo-cd/issues/13978.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
Great feature, good work!

**Comment by mugioka** [comment]
@crenshaw-dev pull request is ready for review now

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by crenshaw-dev** [comment]
@mugioka do you have time to add an integration test to avoid regressions?

**Comment by mugioka** [comment]
@crenshaw-dev ok, i will be try. Should I addressed with this PR?

**Review by crenshaw-dev — APPROVED** [review]
A follow-up PR will be fine! Let's get this out with tomorrow's patch.

**Pull request merged**
