### PR TITLE
fix(controller): cache deadlock on delete and re-add cluster

### PR DESCRIPTION
**Pull request by nromriell**
Fixes an issue with a deadlock in the application controller on cluster delete.

How to reproduce: Quickly add, remove, and re-add a cluster using the argo cli to the same application controller shard. Although the fast timing isn't required it is re-produced more reliably that way.

Problem: controller.cache.handleDeleteEvent and gitops-engine.pkg.cache.cluster.EnsureSync have competing locks under the conditions:
- controller.cache.handleDeleteEvent calls cluster.Invalidate()
- EnsureSync calls gitops-engine.pkg.cache.cluster.sync which processes items in the RunAllAsync calling `c.setNode(c.newResource(un))` the issue lies in the `c.newResource` call because of the populateResourceInfoHandler

Since controller.cache sets clustercache's populateResourceInfoHandler whose function requires locking the liveStateCache in the controller handleDeleteEvent ends up waiting on the lock at the top of cluster.Invalidate while clustercache.sync is waiting to get the lock on the liveStateCache

Fix: have handleDeleteEvent release the liveStateCache lock before calling invalidate. Then lock again before deleting the cluster. Also swapped initial lock to a read lock since we are not modifying.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by templarfelix — APPROVED** [review]

**Review by alexmt — APPROVED** [review]
Thank you! LGTM

**Comment by alexmt** [comment]
Manually created cherry-pick PRs for 2.5 and 2.6

**Pull request merged**
