### PR TITLE
fix: create app shows dest URL instead of name

### LINKED ISSUE #11228: Application wizard shows destination URL instead of name
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When creating an Application from YAML that is using the `destination.name` for the cluster, after clicking save, the UI shows the empty cluster destination URL instead of the name.

**To Reproduce**

1. Start creating a new Application, edit as yaml.
2. Paste manifest that uses the `destination.name`
    ```
    apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
        name: my-cluster
        namespace: argocd
    spec:
        destination:
            name: in-cluster
    ```
4. Click save. 

The destination section displays the empty cluster URL instead of the populated name.

**Expected behavior**

When the Application is using the destination name, after clicking save on editing as YAML, the destination section should display the name instead of the URL.

**Screenshots**

https://user-images.githubusercontent.com/4213435/200638541-22352fbd-7dfa-4f5f-b2dc-76f3ad9e89d3.mp4

**Version**

```json
{
    "Version": "v2.5.1+504da42",
    "BuildDate": "2022-11-01T21:14:30Z",
    "GitCommit": "504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

**Logs**
N/A

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #11228

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by keithchong — APPROVED** [review]
LGTM

**Comment by gomgomshrimp** [comment]
Hi, I am currently checking for a problem in argocd v2.7.6 where it is not possible to select the name of the destination in the application creation panel. #13655  

While doing so, I found this PR and issue #11228 

Doesn't this PR affect the issue of not being able to select the name of the destination? 
This was working in previous versions. Below is a video of the issue.


https://github.com/argoproj/argo-cd/assets/12162614/7ed1eaf5-d839-4e69-a5e1-af46e064cdfd

**Comment by slammajamma28** [comment]
I am seeing the same issue as @gomgomshrimp where we cannot select Name as a destination in the dropdown running v2.7.6. 

Will this PR correct that? I noticed there are a couple of other open issues referencing this - #13813 and #13655

**Comment by gomgomshrimp** [comment]
@slammajamma28 
This PR disables the name dropdown for the destination.

Because this PR is the only one that changes the destination dropdown, and I actually found that it work when I removed the code and tested it.

I was going to create a PR to fix it, but there is already in progress that fixes this issue. Please see the following. (https://github.com/argoproj/argo-cd/pull/14216)

**Pull request merged**
