### PR TITLE
fix: detect applicationset webhook events for Matrix and Merge genera…

### LINKED ISSUE #442: Applicationset not refreshed after webhook event using matrix generator
As PR changes (e.g. change the label defined for the pr generator) on GitHub are not immediately picked up by ArgoCD, even though the webhook event is delivered oke according to GitHub, I did some investigating.

**Timeline:**

14:21:38Z: appset-controller log (no pr's labeled with 'preview' at this moment, so 0 apps is correct):
```
time="2021-12-20T14:21:38Z" level=info msg="generated 0 applications" generator="{<nil> <nil> <nil> <nil> <nil> <nil> 0xc000a00000 <nil>}"
time="2021-12-20T14:21:38Z" level=info msg="end reconcile" requeueAfter=3m0s
```

14:22:23Z: Webhook delivery (labeled one pr with 'preview'):
```
Content-Length: 0
Date: Mon, 20 Dec 2021 14:22:23 GMT
Vary: Accept-Encoding
```

14:22:23Z: _Expected some webhook action here to trigger an appset refresh_

14:24:40Z: appset-controller log (requeued reconcile expected at 14:21:38Z + 3mins ~ 14:24:38Z):
```
time="2021-12-20T14:24:40Z" level=info msg="created Application" app=my-app-pr-1-dir1 appSet=my-appset
time="2021-12-20T14:24:40Z" level=info msg="created Application" app=my-app-pr-1-dir2 appSet=my-appset
```

14:24:40Z: app-controller:
```
time="2021-12-20T14:24:40Z" level=info msg="Refreshing app status (spec.source differs), level (3)" application=my-app-pr-1-dir1
```

Based on the [this](
https://github.com/argoproj-labs/applicationset/blob/master/pkg/utils/webhook.go#L86) code, I assume the webhook only works if the git or pr generators are used on their own, but not in combination with the matrix (or the new merge) generator.

I don't see the [refesh log statement](https://github.com/argoproj-labs/applicationset/blob/master/pkg/utils/webhook.go#L99) in the appset-controller logs, but there is no error either.

Example appset spec:
```
spec:
  generators:
  - matrix:
      generators:
      - pullRequest:
          github:
            labels:
            - preview
            owner: me
            repo: my-app
      - git:
          directories:
          - path: '*'
          repoURL: git@github.com:me/my-app-deployments.git
          revision: pr
```

Would it be possible to extend webhook support for 'nested' generators, like the matrix generator?

### PR DESCRIPTION
**Pull request by sboschman**
Had to rewrite the test logic a bit as it did not support more than one appset in the effectedAppSets list.

fixes https://github.com/argoproj/applicationset/issues/442

(moved from https://github.com/argoproj/applicationset/pull/458)

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
lgtm!

**Comment by ejhayes** [comment]
This does not appear to work with #9080 

For example if I create an application set like this   and setup a webhook for pull requests they will not be refreshed when pull request events happen.
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appbundle-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: https
            github: 
              organization: SOME_ORG
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^argocd-test
        - pullRequest:
            github:
              owner: '{{ organization }}'
              repo: '{{ repository }}'
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
  template:
...
```

However if I do not attempt to use `{{organization}}` and `{{repository}}` in the pull request generator then everything works as expected:

```yaml
This does not appear to work with #9080 

An example:
```yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root-appbundle-test
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
        - scmProvider:
            cloneProtocol: https
            github: 
              organization: SOME_ORG
              tokenRef:
                secretName: github-token
                key: token
            filters:
              - repositoryMatch: ^argocd-test
        - pullRequest:
            github:
              owner: 'SOME_ORG'
              repo: 'SOME_REPO'
              labels:
              - preview
              tokenRef:
                secretName: github-token
                key: token
  template:
...
```

I suspect there may be an issue with using the interpolated values that is causing the webhook event to be discarded.

**Comment by sboschman** [comment]
@ejhayes , can you please open a new issue for this? This PR was merged before the implementation of the new feat of #9080. I had a quick glance at the code, and you are correct in your assumption that the webhook logic has not been updated to include the new #9080 feature.

Just a heads up @KojoRising / @crenshaw-dev , but webhook support for #9080 would be a well need addition imo.

**Comment by ejhayes** [comment]
Thanks for checking on this @sboschman. I've opened a new issue for this.

**Pull request merged**
