### PR TITLE
fix: Check tracking annotation for being self-referencing

### LINKED ISSUE #8683: Resources with tracking method annotation incorrectly marked as out-of-sync/requires pruning
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

One of the goals of using annotations for resource tracking is, that the resource should only be considered managed if the values of the annotation match the properties of the resource. However, this does not seem to be the case.

**To Reproduce**

1. Set `application.resourceTrackingMethod` to `annotation`
2. Create a new application, e.g. `kustomize-guestbook` from `https://github.com/argoproj/argocd-example-apps`, with a target namespace of `guestbook`
3. Sync the application. Make sure that Argo CD has put on tracking annotations on the live resources instead of the label, e.g. 
```yaml
  annotations:
    argocd.argoproj.io/tracking-id: 'guestbook:/Service:guestbook/kustomize-guestbook-ui'
```
4. Create a new dummy resource in namespace `guestbook`, for example a `ConfigMap`: 
```
kubectl -n guestbook create configmap foobar
```
5. Add annotations from another resource to dummy resource: 
```
kubectl -n guestbook annotate configmap foobar argocd.argoproj.io/tracking-id='guestbook:/Service:guestbook/kustomize-guestbook-ui'
```
6. Observe this resource being marked as out of sync and pruning required in the application:
image

**Expected behavior**

The resource should be ignored because the properties of the resource don't match the values in the annotation. The resource should not be considered to be managed by Argo CD, and neither marked out of sync nor for be marked for pruning.

**Screenshots**

**Version**

Latest HEAD as of the time of issue creation:

```shell
argocd-server: v2.3.0+f9b7384
  BuildDate: 2022-03-04T07:39:01Z
  GitCommit: f9b7384bf4d5b0197e726ca19e40518c97fd05fd
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #8683

When using the tracking method `annotation` or `annotation+label`, the app controller will now consider the resource properties in the annotation (name, namespace, group and kind) to determine whether the resource should be compared against the desired state. If the tracking annotation does not reference the resource it is applied to, the resource will neither affect the application's sync status nor be marked for pruning.

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by jessesuen — COMMENTED** [review]
This is great! One thing that still needs to be done (as a separate PR?), is that I believe that the UI still indicates "needs pruning" on resources which we have no intention of pruning. This is a source of confusion and is misleading to users.

On a similar note, I wonder if we can improve the behavior such that these type of resources don't even have a Sync status? e.g.:

```golang
resState.Status = ""
```

This might solve the confusion behavior in UI.

**Comment by jannfis** [comment]
@jessesuen Since resources with a non self-referencing tracking annotation will be handled similar to hooks or ignored resources, I believe this change already takes care of that. Such resources won't have a sync status, and thus will neither be marked as pruning.

In below example, there are two additional resources not stored in Git for the Application named `guestbook`:

* The `guestbook-cm` ConfigMap 
* The `guestbook-service` Service

Both resources carry a copy of the tracking annotation from the `guestbook-ui` Service (i.e. `argocd.argoproj.io/tracking-id: guestbook:/Service:guestbook/guestbook-ui`), to emulate a resource including labels and annotations being copied from a managed resource:

image

Neither carries the sync status, but Argo CD will assess the resource's health if applicable - same as for resource hooks. I believe this may be the desired behavior that users want to see.

**Review by jessesuen — APPROVED** [review]
LGTM!

**Comment by jannfis** [comment]
Actually, let me add an end-to-end test for this :)

**Review by crenshaw-dev — APPROVED** [review]
lgtm, not merging since you're gonna add an e2e test

**Comment by jannfis** [comment]
Hm, the end-to-end test I added passes locally when run as a single test (i.e. `go test -run TestAnnotationTrackingExtraResources`). 

I suspect the failure is due to the bug reported in #9781 - I had similar issues when writing e2e tests that should leverage tracking annotation feature in another PR.

**Comment by crenshaw-dev** [comment]
@jannfis would you like to do without the e2e for now and add after #9781 is fixed?

**Comment by jannfis** [comment]
@crenshaw-dev I'm currently working on a fix for #9781, I'm close to finishing it. Probably that fix should go in first, then I'll rebase this PR so that the end-to-end runs fine.

**Comment by jannfis** [comment]
Fix PR for this: #9820

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.6.

**Comment by crenshaw-dev** [comment]
@mzain I think "no." We'd really appreciate a docs PR if you have time!

**Comment by mzain** [comment]
@crenshaw-dev raised a PR for docs update #16021

**Pull request merged**
