### PR TITLE
feat: Add custom resource health for flux resources

### PR DESCRIPTION
**Pull request by adberger**
As shortly discussed here: https://github.com/argoproj/argo-cd/discussions/18888
This is the second PR to implement custom resource health for flux resources.

Note: Since I couldn't get some resources to get in the `Progressing` state, I couldn't write proper tests for them:
- `ImagePolicy`
- `ImageRepository`
- `ImageUpdateAutomation`
- `Receiver`
- `Bucket`
- `GitRepository`
- `HelmChart`
- `HelmRepository`
- `OCIRepository`

All checks were written based on the documenation of Flux, e.g. https://fluxcd.io/flux/components/kustomize/kustomizations/#conditions

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
Looks good. These are always a little tricky to review just because there's so much but overall I don't see any issues.

**Review by pasha-codefresh — APPROVED** [review]

**Comment by adberger** [comment]
> Looks good. These are always a little tricky to review just because there's so much but overall I don't see any issues.

Thank you :)
I'll gladly fix any issues popping up

**Comment by adberger** [comment]
> @adberger I looks like maybe the health checks don't show the `paused` status? Just did a quick test, when I suspend a resource, it's just marked as healthy. I'm not sure if that's intentional.

@crenshaw-dev that's right.
AFAIK Argo CD "only" knows Healthy, Progressing and Degraded.  
What state should a suspended Flux respurce show in your opinion?

**Comment by crenshaw-dev** [comment]
I think "Suspended" might actually be a good status. It's lightly documented here: https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#way-1-define-a-custom-health-check-in-argocd-cm-configmap

> Suspended - the resource is suspended and waiting for some external event to resume (e.g. suspended CronJob or paused Deployment)

**Comment by crenshaw-dev** [comment]
Yeah it's deep lore tbh. Thanks!

**Comment by adberger** [comment]
@crenshaw-dev let me know what you think about it: https://github.com/argoproj/argo-cd/pull/19508 :)

**Pull request merged**
