### PR TITLE
fix: running local failed close #18356

### LINKED ISSUE #18356: argocd-redis secret-init initcontainer timeout
**Describe the bug**

`secret-init`  initContainer is failing to check/init `argocd/argocd-redis` secret

**To Reproduce**

```shell
kubectl apply -k https://github.com/argoproj/argo-cd/raw/master/manifests/install.yaml
```

**Expected behavior**

InitContainer should succeed to check/init secret `argocd/argocd-redis` 

**Screenshots**

**Version**

```shell
$ argocd version
argocd: v2.11.0+bc53266
  BuildDate: 2024-05-21T22:20:05Z
  GitCommit: bc53266591b632f1a1639ae458f31467446ffe48
  GitTreeState: clean
  GoVersion: go1.22.1
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```shell
$ kubectl describe pod/argocd-redis-565687fb7d-68xdd -n argocd 
Name:             argocd-redis-565687fb7d-68xdd
Namespace:        argocd
Priority:         0
Service Account:  argocd-redis
Node:             REDACTED
Start Time:       Wed, 22 May 2024 09:16:31 +0200
Labels:           app.kubernetes.io/name=argocd-redis
                  pod-template-hash=565687fb7d
Annotations:      cni.projectcalico.org/containerID: faff595beac8d993968609af65d1e133d01fa9b970a0e482301ef9b1b55e0b15
                  cni.projectcalico.org/podIP: 100.64.182.116/32
                  cni.projectcalico.org/podIPs: 100.64.182.116/32
                  kubectl.kubernetes.io/restartedAt: 2024-05-14T08:33:16+02:00
Status:           Pending
SeccompProfile:   RuntimeDefault
IP:               100.64.182.116
IPs:
  IP:           100.64.182.116
Controlled By:  ReplicaSet/argocd-redis-565687fb7d
Init Containers:
  secret-init:
    Container ID:    containerd://2e686a331f4f9a483160e70875f0057734a85a63065e48841b974ab5160957ee
    Image:           quay.io/argoproj/argocd:latest
    Image ID:        quay.io/argoproj/argocd@sha256:717a945c52f15cef5659b94bba3ab360f5a7b86685a978ace448f76f71063231
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Command:
      argocd
      admin
      redis-initial-password
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    20
      Started:      Wed, 22 May 2024 09:25:21 +0200
      Finished:     Wed, 22 May 2024 09:25:51 +0200
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nftnx (ro)
Containers:
  redis:
    Container ID:  
    Image:         docker.io/library/redis:7.0.15-alpine
    Image ID:      
    Port:          6379/TCP
    Host Port:     0/TCP
    Args:
      --save
      
      --appendonly
      no
      --requirepass $(REDIS_PASSWORD)
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:
      REDIS_PASSWORD:  <set to the key 'auth' in secret 'argocd-redis'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nftnx (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-nftnx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors: 
Tolerations:         node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  12m                   default-scheduler  Successfully assigned argocd/argocd-redis-565687fb7d-68xdd to REDACTED
  Normal   Pulled     9m23s (x5 over 12m)   kubelet            Container image "quay.io/argoproj/argocd:latest" already present on machine
  Normal   Created    9m23s (x5 over 12m)   kubelet            Created container secret-init
  Normal   Started    9m23s (x5 over 12m)   kubelet            Started container secret-init
  Warning  BackOff    2m45s (x31 over 11m)  kubelet            Back-off restarting failed container secret-init in pod argocd-redis-565687fb7d-68xdd_argocd(e00bcbf4-853f-44fe-8302-82f0997884a9)


$ kubectl logs pod/argocd-redis-565687fb7d-68xdd -c secret-init  -n argocd
Checking for initial Redis password in secret argocd/argocd-redis at key auth. 
time="2024-05-22T07:25:51Z" level=fatal msg="Post \"https://10.32.0.1:443/api/v1/namespaces/argocd/secrets\": dial tcp 10.32.0.1:443: i/o timeout"
```

### PR DESCRIPTION
**Pull request by yyzxw**
Refer to [running-local](https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/running-locally.md) to install and run ArgoCD locally. Because NetworkPolicy,
The Egress of `argocd-redis-network-policy` cannot access `kube-apiserver`.  So initContainer in pod `argocd-redis` fails to initialize the secret `argocd-redis`,
```
Checking for initial Redis password in secret argocd/argocd-redis at key auth.
time="2024-05-22T08:58:54Z" level=fatal msg="Post \"https://10.233.0.1:443/api/v1/namespaces/argocd/secrets\": dial tcp 10.233.0.1:443: i/o timeout"
```
 which in turn causes `argocd-application-controller `, `argocd-repo-server`, `argocd-server` cannot start (because `argocd-secret` cannot be found)

It is worth noting that I tried modifying the Egress to add `podSelector` and `namespaceSelector`, but I was unable to access kube-apiserver. 

Meanwhile, In `argocd-helm`, only Ingress is actually defined: https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/templates/redis/networkpolicy.yaml

just delete Egress, or is there a better way?

close #18356

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
While this does solve the problem it introduces other issues by removing network policy. I don't have a better approach but this one is a bit too nuclear.

**Comment by yyzxw** [comment]
> While this does solve the problem it introduces other issues by removing network policy. I don't have a better approach but this one is a bit too nuclear.

In fact, I have tried the following ways, but none of them work, or there are other ways to solve, I will change the pr, thanks!
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: argocd-redis-network-policy
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-repo-server
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: argocd-application-controller
    ports:
    - protocol: TCP
      port: 6379
  egress:
  - to:
    - podSelector:   # podSelector not working
        matchLabels:
          app.kubernetes.io/name: argocd-repo-server
    - namespaceSelector: # namespace not working
        matchExpressions:
          - key: namespace
            operator: In
            values:
              - default
              - kube-system
    - ipBlock:      # cidr not working 
        cidr: 10.233.0.1/18
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    - port: 443
      protocol: TCP

```

**Comment by pasha-codefresh** [comment]
Resolved here https://github.com/argoproj/argo-cd/pull/18367/files

**Comment by mclanghlin** [comment]
Hi, I have the same problem with this version.

kubectl apply -k https://github.com/argoproj/argo-cd/raw/master/manifests/install.yaml

**Pull request closed without merging**
