### PR TITLE
chore: Set GITHUB_TOKEN in the test container

### PR DESCRIPTION
**Pull request by jannfis**
The ApplicationSet end-to-end tests need to have `GITHUB_TOKEN` set, so that the tests do not run into the unauthenticated rate limiting of GitHub.

Note `GITHUB_TOKEN` needs to be properly exported in the env.

Signed-off-by: jannfis <jann@mistrust.net>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
@rishabh625 This is for running the tests locally, not on the CI :)

**Comment by 34fathombelow** [comment]
@jannfis I was under the impression that a GITHUB_TOKEN was only auto-generated during the run of a workflow only. Would a end user have to use a PAT?  Let me know if I'm missing something

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by rishabh625** [comment]
> @jannfis I was under the impression that a GITHUB_TOKEN was only auto-generated during the run of a workflow only. Would a end user have to use a PAT? Let me know if I'm missing something

I think u need to set variable to run test locally else test skips, take a look at pull request generator test

so it's good to have this var

**Review by rishabh625 — APPROVED** [review]

**Pull request merged**
