### PR TITLE
chore: remove argocd-cm plugin support

### LINKED ISSUE #8117: drop support for argocd-cm Config Management Plugins in favor of sidecars
# Summary

Argo CD should drop support for CMPs installed via argocd-cm. Installing CMPs via sidecars on repo-server should be made as simple as possible (via docs/examples).

# Motivation

1. Having two ways to configure CMPs is confusing.

   The docs are longer, and it's difficult to tell which comments apply to which install method. 
2. Having two ways to _use_ CMPs is confusing.

   argocd-cm CMPs must be referenced by name in the Application spec. But sidecar CMPs _must not_ be referenced by name (they're invoked only according to discovery output). This difference is difficult to document (each place where there's an example `plugin` config must include a comment) and is not intuitive to users (why would one plugin be referenced by name and another plugin not be referenced by name)?

3. Maintaining two CMP installation methods is difficult and error-prone.

   The differing invocation methods is one example. [Differing manifest init processes](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1641574094087900?thread_ts=1641560646.070300&cid=C01TSERG0KZ) is another example.

4. Providing support for two different CMP types is difficult.

   For each question asked about CMPs, the answers may differ based on what _kind_ of plugin. The extra back-and-forth and clarification of terms can introduce frustration.

5. Adding binaries via volumeMount or a custom repo-server image is weird.

   The volumeMount relies on pulling files from an external source. The custom image requires a custom build/update process.

6. Decoupling the repo-server from plugins just makes sense.

   Generating manifests is a distinct task from the other work the repo-server does. Adding separation between repo-server and plugins can help avoid unexpected interaction, especially since the config management tools interact heavily with the filesystem.

# Proposal

1. Deprecate argocd-cm CMPs.
   1. Remove documentation about how to install them.
   2. Add a warning to logs and the UI when an argocd-cm plugin is enabled. Note the version when the feature will be removed.
2. Write a migration guide for modifying an argocd-cm CMP to be a sidecar CMP.
3. Remove the feature in some major release.

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes #8117

### CODE REVIEW

**Comment by todaywasawesome** [comment]
I worry about this one because it's such a widely used feature. Could be perhaps just add a deprecation warning for a few versions before removing?

**Comment by crenshaw-dev** [comment]
It's a fair point though. I fully expect people will be on this thread two years from now saying "aw man, why did y'all do this, I'm just upgrading from 1.9, this sucks." :-P

**Review by todaywasawesome — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
@crenshaw-dev could you please fix conflicts?

**Comment by crenshaw-dev** [comment]
@pasha-codefresh this is ready for another look

**Review by pasha-codefresh — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@pasha-codefresh wanna glance at the e2e test fixes?

**Comment by pasha-codefresh** [comment]
Thank you

**Pull request merged**
