### PR TITLE
receiveFile memory optimization: do not use bytes.buffer but write di…

### PR DESCRIPTION
**Pull request by ls0f**
*receiveFile memory optimization: do not use bytes.buffer but write directly to file*

Signed-off-by: ls0f <lovedboy.tk@qq.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks for the optimization!

I [suggested](https://github.com/argoproj/argo-cd/pull/8600/files#r821732159) this when @leoluz wrote the stream code. This was his response:

> I guess this is a choice we have to make that there isn't a clear best path to take. The choice is between performance vs memory consumption. The file being received is a gzip'ed archive containing text files basically which in the great majority of the cases will be really small. Changing this to write always on disk will slow down the stream reception to address a problem that would happen in 1-5% of cases. If this turn out to be a real problem we could change the gRPC API to send the file size in the header and allow the receiver to decide if it should use a memory buffer or a file buffer. Sounds like a premature optimization at this point. Wdyt?

@leoluz what are your thoughts now? Should we try to choose memory vs. disk based on file size?

**Comment by leoluz** [comment]
> what are your thoughts now? Should we try to choose memory vs. disk based on file size?

@crenshaw-dev if that is becoming a real issue I think we should go in the direction suggested while back:

> ... we could change the gRPC API to send the file size in the header and allow the receiver to decide if it should use a memory buffer or a file buffer

@ls0f are you facing memory issues with large files? Can you pls provide more context in the PR description?

**Comment by leoluz** [comment]
> In addition, i think write file in append mode won't really reduce the efficiency too much

Looking at your implementation one more time, I agree with that. Spoke with @crenshaw-dev and we both agree that defaulting to file-system in append mode is preferable in this case.

**Review by leoluz — APPROVED** [review]
LGTM

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked to 2.4.

**Pull request merged**
