### PR TITLE
chore(deps): Updated otelgrpc to remediate CVE found by JFrog Xray

### PR DESCRIPTION
**Pull request by yitzhtal**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by talitz** [comment]
@blakepettersson what are the issues? where is a failed build? can you please elaborate more?

**Review by gdsoumya — APPROVED** [review]
LGTM

**Comment by gdsoumya** [comment]
@talitz seems like the build was failing initially but after merging master the ci passed. The CI is known to be flaky sometimes.

**Comment by talitz** [comment]
OK, thanks a lot for accepting the PR!

**Comment by blakepettersson** [comment]
> @talitz seems like the build was failing initially but after merging master the ci passed. The CI is known to be flaky sometimes.

Actually that's not the case 😢. Thanks to #16982 the CI on this PR passed, although it shouldn't have. #17101 fixes that, but now it's failing due to this PR 🙈

**Comment by gdsoumya** [comment]
Related changes to fix linting errors https://github.com/argoproj/argo-cd/pull/17103

**Comment by gdsoumya** [comment]
Reverted change in #17107

**Pull request merged**
