### PR TITLE
fix: set default value for users.session.duration (#9962)

### LINKED ISSUE #9962: TOB-ARGO-TM8: Set a reasonable default if UserSessionDuration parsing fails
# Summary

When UserSessionDuration is parsed from `argocd-cm`, failed parsing defaults to 0. Instead, set a reasonable default.

https://github.com/argoproj/argo-cd/blob/fdceed6051f2659adff206498a9417695e23e74c/util/settings/settings.go#L1274

### PR DESCRIPTION
**Pull request by numacci**
Fixes https://github.com/argoproj/argo-cd/issues/9962

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

NOTE:
* Line 672, 1285-1287, 1320-1321, 1325 changes in settings_test.go have been automatically formatted.

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@y-takuya thanks so much for this!

Could you add a quick note to docs/operator-manual/upgrading/2.4-2.5.md to say something to this effect:

> ### Invalid user.session.duration values now fall back to 24h
> 
> Before v2.5, an invalid `user.session.duration` value in argocd-cm would 1) log a warning and 2) result in user sessions having no duration limit.
> 
> Starting with v2.5, invalid duration values will fall back to 24 hours.

**Comment by y-takuya** [comment]
@crenshaw-dev Thank you very much for your comment and for revising the PR title. I added a note with mostly what you proposed.

**Comment by crenshaw-dev** [comment]
@y-takuya the test failure is due to a problem on the master branch. I'll update your branch after the fix is merged (should be in the next ~40min).

**Comment by y-takuya** [comment]
@crenshaw-dev I see. Thank you for updating my branch. The CI is still failing, but the reason was due to a network problem that failed to download the k3s binary (exit code 92). It might be a temporary issue, so I will try to re-trigger this CI again.

**Review by crenshaw-dev — APPROVED** [review]
lgtm. thanks @y-takuya!

**Pull request merged**
