### PR TITLE
docs: better command reference titles (#15567)

### LINKED ISSUE #15567: docs: the command reference headers look bad
# Summary

The leading capital letter is off-putting. And in search results, there's no indication that this is a command reference.

image

image

# Motivation

The header should look good, and search results should show that the link points to a command reference.

# Proposal

Use cobra's custom markdown generation tools to override the default title with something nicer.

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Closes #15567

Doesn't this look nice? 

image

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]
LGTM 👨‍🍳 🤌

**Comment by crenshaw-dev** [comment]
Retrying... maybe it doesn't like the quotes in titles?

**Comment by crenshaw-dev** [comment]
All clear on retry. Was just a flake.

**Review by 34fathombelow — APPROVED** [review]
LGTM

**Review by ishitasequeira — APPROVED** [review]

**Pull request merged**
