### PR TITLE
fix: JS error when using cluster filter in the /application view

### LINKED ISSUE #4134: JS error when using cluster filter in the /application view (TypeError: Cannot read property 'split' of undefined)
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

This is shown after I login with my Github and choose one of the clusters under clusters filter, it throws

```
Something went wrong!

Consider submitting an issue here.

Stacktrace:

TypeError: Cannot read property 'split' of undefined
    at m.match (https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:33:43008)
    at h (https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:33:37816)
    at https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:13:308383
    at Array.some (<anonymous>)
    at https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:13:308358
    at Array.filter (<anonymous>)
    at Js (https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:13:307831)
    at Object.children (https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:13:313287)
    at t.render (https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:13:86283)
    at Oi (https://argocd.core-services.rr.mu/main.a781d839f0adbf108587.js:354:63228)
```

the `view_preferences` in localStorage is this when the error shown:
```
{"version":4,"appDetails":{"view":"tree","resourceFilter":["kind:Deployment","kind:Service","kind:Pod","kind:StatefulSet","kind:Ingress","kind:ConfigMap","kind:Job","kind:DaemonSet","kind:Workflow"],"inlineDiff":false,"compactDiff":false,"resourceView":"manifest","orphanedResources":false},"appList":{"view":"tiles","labelsFilter":[],"projectsFilter":[],"namespacesFilter":[],"clustersFilter":["https://163616C2797C009DB3BA93E8E1B59BC5.yl4.us-east-1.eks.amazonaws.com"],"reposFilter":[],"syncFilter":[],"healthFilter":[],"page":0,"search":""},"pageSizes":{}}
```

**Context**

1. We are using Github login as our auth method. (probably not relevant)
2. but it can work under **incognito mode**.
3. but it can work in safari
4. FIXED by cleaning out the `view_preferences`

**To Reproduce**

Go to argocd app, login, choose one of clusters as filter, error shown, remove the `view_preference`, error gone.

**Expected behavior**

it should not throw errors.

**Screenshots**

none

**Version**

```shell
argocd: v1.6.0+c10ae24
  BuildDate: 2020-06-16T22:41:56Z
  GitCommit: c10ae246ab02f1356147118a1979fedcd1ceb704
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:45:07Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by alexmt**
Closes https://github.com/argoproj/argo-cd/issues/4134

### CODE REVIEW

**Review by mayzhang2000 — COMMENTED** [review]
LGTM

**Comment by yydzhou** [comment]
Any chance to speedup the progressing of this MR? The UI crash, once happened, is very hard to recover unless cleanup the history/cache. This is a big user-experience regression. We have external users and very hard to revert to old version once announced. 
It would be nice to speedup this MR Merging and cherry-picking process.

**Review by mayzhang2000 — APPROVED** [review]

**Comment by yydzhou** [comment]
Thanks for you guys on the fast response. Really appreciate it.

**Comment by alexmt** [comment]
Patch release will be available later today

**Pull request merged**
