### PR TITLE
fix: Run redis container as `redis` user #6040

### LINKED ISSUE #6040: Redis container fails to start
Hello,

The Redis container fails to start while deploying ArgoCD on k3s using the `install.yaml` manifest. 

**To Reproduce**

```
kubectl create namespace argocd
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
```

**k3s version**

```shell
k3s --version
k3s version v1.20.5+k3s1 (355fff30)
go version go1.15.10
```

**Event Log**

```
Error: container has runAsNonRoot and image will run as root (pod: "argocd-redis-869ccb7478-lrxxp_argocd(9cd55b49-6e04-4da1-8d9d-cdd33b39fbef)", container: redis)
```

The [image](https://github.com/docker-library/redis/blob/master/6.2/Dockerfile) from Docker hub does not specify `USER`

**Workaround**

```diff
diff --git a/argoproj/argo-cd/install.yaml b/argoproj/argo-cd/install.yaml
index d691207..d36b0ec 100644
+++ b/argoproj/argo-cd/install.yaml
@@ -2599,7 +2599,7 @@ spec:
         - containerPort: 6379
       securityContext:
         runAsNonRoot: true
+        runAsUser: 999
       serviceAccountName: argocd-redis
 ---
 apiVersion: apps/v1
```

### PR DESCRIPTION
**Pull request by hrpatel**
Fixes #6040

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
Thank you!

I'm able to reproduce the error described in https://github.com/argoproj/argo-cd/issues/6040 and verified that fix is working. 

@hrpatel , can you run `make manifests` to regenerate install.yaml ?

**Comment by hrpatel** [comment]
> Thank you!
> 
> I'm able to reproduce the error described in #6040 and verified that fix is working.
> 
> @hrpatel , can you run `make manifests` to regenerate install.yaml ?

Thanks for the feedback, committed!

**Comment by hrpatel** [comment]
@alexmt 
I re-read the contribution guidelines and couldn't find any reference to `make manifests` (so my plan was to fix the generated files by hand until CI passed) - did I miss a page/instructions?

**Comment by alexmt** [comment]
Hello @hrpatel . The `make manifests` is executed as part of `make codegen`. I've suggested it since it is taking less time than full code generations: https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/contributing.md#generate-api-glue-code-and-other-assets

**Review by alexmt — APPROVED** [review]
LGTM!

**Pull request merged**
