### PR TITLE
docs: refreshed page for sync windows

### PR DESCRIPTION
**Pull request by kostis-codefresh**
Signed-off-by: Kostis Kapelonis <kostis@codefresh.io>

Ongoing work for https://github.com/argoproj/argo-cd/issues/5635

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]
Looking great!

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Should the old page be deleted? https://argo-cd.readthedocs.io/en/stable/user-guide/sync_windows/

**Comment by kostis-codefresh** [comment]
@crenshaw-dev 

This page is not to be merged in main but instead go the the branch "refresh-docs" which has a brand new documentation structure. Almost all pages are empty there.

Or do you mean something different?

**Comment by crenshaw-dev** [comment]
Ah! Nope, you're perfectly correct. Thanks for clarifying!

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
