### PR TITLE
chore: update tool versions

### PR DESCRIPTION
**Pull request by james-callahan**
Bumping to latest tools before 1.8.0 release.

---

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks for your PR @james-callahan - unfortunately, it's too late to update tooling for 1.8 at this point in time, especially for Kustomize. It's fine to go ahead for a target release of v1.9, tho.

Unfortunately, Kustomize is notorious for changing behaviour in patch revisions, and I think this update is again a proof for it (I'm refering to changed syntax of `add label ...`, and maybe there's even more). This is a change that breaks automation.

Since we support multiple versions of Kustomize, I think what would be great is to expand the change regarding on how to set the labels (either comma or white space separated) and use either method for the correct Kustomize version. Reading the Changelog of Kustomize, this change was introduced with v3.8.5.

Would you be willing to contribute this functionality? Our Helm implementation already has a generic interface for running different versions of Helm in a different manner, maybe this is something to get inspired from.

**Comment by jessesuen** [comment]
I agree. kustomize changes are extremely risky. We can target v1.9 though.

**Comment by james-callahan** [comment]
Originally in this PR, I was trying to update several tools. However the tests keep failing for various reasons
  - kustomize `add label` syntax has changed (as you noted)
  - updating protoc resulted in go failures of `github.com/gogo/protobuf/gogoproto/gogo.proto:92:8: "google.protobuf.MessageOptions" is not defined.`
  - even just updating kustomize we seem to get test failures like
    ```
    --- FAIL: TestCreateAppWithNoNameSpaceWhenRequired (5.21s)
    panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
    ```


> Since we support multiple versions of Kustomize, I think what would be great is to expand the change regarding on how to set the labels (either comma or white space separated) and use either method for the correct Kustomize version. Reading the Changelog of Kustomize, this change was introduced with v3.8.5.
> 
> Would you be willing to contribute this functionality?

I don't think so; I'm no a Go programmer (nor do I wish to be).

**Comment by maxbrunet** [comment]
Kustomize has accidentally introduced another breaking change in v3.8.0 (kubernetes-sigs/kustomize#2907) which has been fixed in v3.8.5.

**Comment by alexmt** [comment]
Closing in favor of https://github.com/argoproj/argo-cd/pull/5672

**Pull request closed without merging**
