### PR TITLE
chore: wrap error objects to include context

### PR DESCRIPTION
**Pull request by someOne404**
Signed-off-by: Jiayi Lu <jiayi_lu@intuit.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by someOne404** [comment]
This PR is related to https://github.com/argoproj/argo-cd/issues/10592

**Comment by someOne404** [comment]
@crenshaw-dev Looks like this check failed to pass due to timeout `Integration tests / Run unit tests for Go packages (pull_request) `. It doesn't look like being related to the changes I made. Could you please help me to take a look and retrigger the check if possible?

**Comment by someOne404** [comment]
@crenshaw-dev Do you mind taking a look? Really appreciate it!

**Review by crenshaw-dev — APPROVED** [review]
Looks awesome, thanks @someOne404!

**Pull request merged**
