### PR TITLE
docs: Update USERS.md

### PR DESCRIPTION
**Pull request by djajcevic**
Add https://croz.net/

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
@djajcevic do you mind signing the DCO (`git commit --amend -s`)

**Comment by djajcevic** [comment]
> @djajcevic do you mind signing the DCO (`git commit --amend -s`)

Would like to, but I do not have permission to push to this PR. Any other way? Remove PR and submit a new one?

**Review by alexmt — APPROVED** [review]
Thank you @djajcevic !

Got confirmation that it is ok to skip DCO for docs changes.

**Comment by djajcevic** [comment]
> Thank you @djajcevic !
> 
> Got confirmation that it is ok to skip DCO for docs changes.

Tnx! I'll watch out for the next PRs to have DCOs!

**Pull request merged**
