### PR TITLE
Improve doc rendering for slack

### PR DESCRIPTION
**Pull request by pie-r**
Checklist:

* [x] This does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)

### CODE REVIEW

**Comment by pie-r** [comment]
Hello @alexef do you have any idea what should I do?
I've fixed some type in the md, and the pipeline is failing. Should I change the typo in a different file?

**Comment by alexef** [comment]
Pipeline is failing in: https://github.com/argoproj/argo-cd/pull/11301/checks?check_run_id=9494822249 DCO

But also in https://github.com/argoproj/argo-cd/actions/runs/3468936927/jobs/5795330333 - this is because the md should not be modified here, but in http://github.com/argoproj/notifications-engine (from where it is copied during CI)

**Comment by alexef** [comment]
let's fix: https://github.com/argoproj/notifications-engine/blob/master/docs/services/slack.md instead

**Comment by pie-r** [comment]
Thanks for the help @alexef 

I open:

- https://github.com/argoproj/notifications-engine/pull/117 ✅  green and ready to merge
- https://github.com/argoproj/argo-cd/pull/11336 - I think is going to be green soon 👍

**Pull request closed without merging**
