### PR TITLE
Separate manual sync options

### PR DESCRIPTION
**Pull request by alexmt**
Note on DCO:

PR improves single appication sync panel and multiple applications sync panels design:

* visually separate manual sync options from app-level sync options
* makes sure all checkboxes and labels are aligned in the same way
* uses the same checkbox styling

Sync apps:

After:
image

Before:

image

Sync app:

After
image

Before

image

### CODE REVIEW

**Comment by alexmt** [comment]
Last-minute UI improvements for v2.0. @rbreeze , @reginapizza  can you take look please?

**Review by rbreeze — APPROVED** [review]
LGTM!

**Review by reginaelyse — COMMENTED** [review]
In the last picture you added, is the text supposed to go on a new line apart from the checkbox like that? Would it be better to be truncated or wrap? Otherwise, LGTM!

**Comment by alexmt** [comment]
@reginapizza last picture is before state. I agree: text should be truncated - it is demonstrated in before picture.

**Comment by alexmt** [comment]
thank you for quick review!

**Comment by reginapizza** [comment]
ah, I missed the word "before" above it :) All good then!

**Pull request merged**
