### PR TITLE
feat(health): Implement Proclaim CRD health checks.

### PR DESCRIPTION
**Pull request by jmalloc**
This PR adds a Lua health check for the `proclaim.dogmatiq.io` `DNSSDServiceInstance` CRD.

[Proclaim](http://github.com/dogmatiq/proclaim) is a controller that publishes [RFC 6763](https://www.rfc-editor.org/rfc/rfc6763) (DNS-SD) service discovery records to a DNS provider (Route 53, DNSimple, etc) based on a CRD.

I've opened this PR as a draft to get some early feedback and iron out any potential oversights.  I'll test the health-check logic by [including it in `argo-cm`](https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#way-1-define-a-custom-health-check-in-argocd-cm-configmap) before marking the PR as ready to merge.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
At a glance, no concerns. :-)

**Comment by jmalloc** [comment]
We've been running this in our own Argo CD installation with no issue :)

**Comment by jmalloc** [comment]
Is there anything more I should do to get this merged?

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @jmalloc!

**Pull request merged**
