### PR TITLE
docs: Add synchronizing order for kinds

### PR DESCRIPTION
**Pull request by tapih**
The synchronizing order for kinds is not documented for now, but it's very important to configure sync wave, IMO.

Checklist:

* [x]  (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by sbose78** [comment]
Hi @tapih Thank you for the contribution. 

Do you mind sharing the source of truth for the order of synchronization? In order to avoid making this specific documentation page grow big, do you have ideas on a way to link out to this order of sync?

**Comment by tapih** [comment]
Hi @sbose78 .

The source of truth is [github.com/argoproj/gitops-engine](https://github.com/argoproj/gitops-engine/blob/90979fe432d46043ad753d9503f645f64e31abff/pkg/sync/sync_tasks.go#L22-L50). So, we can link this file to avoid making the document grow big.

**Comment by sbose78** [comment]
Thank you @tapih , I think documenting this is valuable. As suggested, this could be just be about linking to GitOps Engine.

**Comment by sathieu** [comment]
And this list needs an update, see https://github.com/helm/helm/blob/a499b4b179307c267bdf3ec49b880e3dbd2a5591/pkg/releaseutil/kind_sorter.go#L31-L66.

**Pull request closed without merging**
