### PR TITLE
fix: Version warning banner in docs

### LINKED ISSUE #6624: Fix the Unstable Docs Version Warning banner to Header
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
The Unstable docs version warning banner is not fixed to the header. 

When someone lands on Old/Unstable docs page from google search they see a warning banner and a link to stable docs, which is good.  However this disappears as they scroll down on the docs, there is a good chance that someone would not see it on a very first sight and scroll down.

Also, I would suggest if we can change the warning/recommendation banner to a strong font and colour. 

**To Reproduce**

Google search for the Argo CD Docs would mostly land you on the older version of docs and you should see the issue that I mentioned in the description.

**Screenshots**

Screenshot 2021-07-03 at 12 17 21 AM

**Version**
NA

```shell
NA
```

**Logs**
NA

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by saumeya**
Signed-off-by: saumeya <saumeyakatyal@gmail.com>
Closes #6624 
Screenshot from 2021-07-09 16-03-42

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks @saumeya! Can you please fix the DCO check by signing off your commits?

**Comment by saumeya** [comment]
> Thanks @saumeya! Can you please fix the DCO check by signing off your commits?

Done

**Review by jannfis — APPROVED** [review]
LGTM, thank you @saumeya!

**Comment by jannfis** [comment]
Going to cherry-pick this change into release-1.8 and release-2.0 branches so looking at older docs will produce the same sticky banner. FYI @alexmt

**Pull request merged**
