### PR TITLE
fix: uid instead of named user (fixes #2746)

### LINKED ISSUE #2746: Argo CD should specify numeric USER in dockerfiles to support pod security policies
Small thing - but we want to make Argo CD perfect :)
When specifying a Pod Security Policy  MustRunAsNonRoot Argo CD  pods fail to start 

"Error: container has runAsNonRoot and image has non-numeric user (argocd), cannot verify user is non-root" 

This can be be worked around by changing the deployment descriptors, but would be better to fix this in the Dockerfiles I think.
Reference: https://kubernetes.io/docs/concepts/policy/pod-security-policy/#users-and-groups

### PR DESCRIPTION
**Pull request by t-v**
When specifying:
```yaml
containerSecurityContext:
  runAsNonRoot: true
  capabilities:
    drop:
      - all
```

You keep getting the error:
```yaml
    state:
      waiting:
        message: container has runAsNonRoot and image has non-numeric user (argocd),
          cannot verify user is non-root
        reason: CreateContainerConfigError
```

And since we are creating user 999 inside the container, it is better to use this user by UID than by username.

issue: #2746 

Checklist:

* [x] this is a bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Hm, I'm wondering - would  specifying `runAsUser` and `runAsGroup` in the pod's security context have the same effect?

**Comment by t-v** [comment]
it would, but wouldn't it be better support `runAsNonRoot` by default?
I currently run it with the `runAsUser` and `runAsGroup` option, so it works, but I think if it would be cleaner if you didn't need to specify it.

**Review by jannfis — APPROVED** [review]
LGTM - Thank you for your submission and I'm very sorry for the long delay @t-v 

@alexmt Do you have any objections to this change?

**Comment by alex1989hu** [comment]
I would be happy to see it merged (also met this error message). Do you need any assistance?

**Comment by jannfis** [comment]
Slipped through - sorry. Merging now :)

**Pull request merged**
