### PR TITLE
fix: jwtTokens are reset when creating new tokens for new role

### PR DESCRIPTION
**Pull request by BulatSaif**
Fixes https://github.com/argoproj/argo-cd/issues/17294

Normalize JWTTokens before updating them.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by ashutosh16** [comment]
Without fix
```
spec:
  roles:
  - name: role1
  - jwtTokens:
    - iat: 1709056523
      id: 0b2ea58c-c711-4764-92c0-12e48cf4ef9e
    name: role2
status:
  jwtTokensByRole:
    role1: {}
    role2:
      items:
      - iat: 1709056523
        id: 0b2ea58c-c711-4764-92c0-12e48cf4ef9e
```

After fix 
```
spec:
  roles:
  - jwtTokens:
    - iat: 1709056811
      id: a5d31865-40ce-4687-932f-48f69f6a6f2f
    name: role1
  - jwtTokens:
    - iat: 1709056860
      id: a7349d29-e705-4bac-9418-2b72acbdcbb3
    name: role2
status:
  jwtTokensByRole:
    role1:
      items:
      - iat: 1709056811
        id: a5d31865-40ce-4687-932f-48f69f6a6f2f
    role2:
      items:
      - iat: 1709056860
        id: a7349d29-e705-4bac-9418-2b72acbdcbb3
```

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
Thanks! Can this be backed up by a unit test, please?

**Comment by BulatSaif** [comment]
> Thanks! Can this be backed up by a unit test, please?

Hi @jannfis, I'm not very familiar with Golang. I'm just a DevOps who uses Argo,  but I will check what I can do.

**Comment by BulatSaif** [comment]
> Thanks! Can this be backed up by a unit test, please?

@jannfis, I updated the tests, and now they fail without the fix. You can check the commits [
`add tests`](https://github.com/argoproj/argo-cd/pull/17298/commits/080e72e8259a16dbc570833a0cbeb581ba63959a) (fails) and [`add fix`](https://github.com/argoproj/argo-cd/pull/17298/commits/989fa9b6ddba1d30fc4fecdfb97919876925df08) (passed).

**Review by gdsoumya — APPROVED** [review]
LGTM

**Comment by BulatSaif** [comment]
Could someone please merge this? I don't have enough permissions to do it myself.

**Comment by BulatSaif** [comment]
@ashutosh16  @gdsoumya,  can you please merge this PR?

**Pull request merged**
