### PR TITLE
fix: Allow retrieving badges in other namespaces

### LINKED ISSUE #15351: Badges not working with "Applications in any namespace"
**Describe the bug**

When ArgoCD "Application" resource is deployed under namespace other than "argocd" the badge url is not working.
Shows "Not found" or "Unknown".

Badges currently seem to only work when Application resources are deployed to argocd namespace (default way).

**To Reproduce**

Deploy application to namespace other than argocd.

Example: __testnamespace/app1__
```
kind: Application
metadata:
    name: app1
    namespace: testnamespace
```

Generated badge url under the application "app1" (UI):
```
https://<argocd_base_url>/api/badge?name=app1&revision=true <!--- "Badge: Not Found"
```

Try to check status with badge url:
```
<argocd_base_url>/api/badge?name=app1&revision=true <!--- "Badge: Not Found"
<argocd_base_url>/api/badge?name=testnamespace_app1&revision=true <!--- "Badge: Not Found"
```

**Version**
v2.8.2

### PR DESCRIPTION
**Pull request by jannfis**
Fixes https://github.com/argoproj/argo-cd/issues/15351

Additionally, I added some sanity checks around query parameters.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jannfis** [comment]
While I was at this code, I thought it'd be good to replace the clientset for getting Applications by an informer. Will submit another PR soonish.

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Pull request merged**
