### PR TITLE
feat: add support for redis acl username/password authentication

### LINKED ISSUE #8675: Support redis auth
# Summary

Redis has an authentication feature that we are not able to leverage because we don't have a way to supply username/password to the redis client. We should provide a way for users to give redis credentials.

See: https://redis.io/commands/auth

# Motivation

There are two areas where we would want this feature:

1) users who point Argo CD to a self-managed redis (e.g. elasticache) and want authentication to it.

2) there is a proposal to have repo-server level tenancy powered by redis authentication and ACLs. We would need support for redis credentials in order to implement repo-server tenancy.

# Proposal

We currently have CLI flags for various redis options:

```
      --redis string                          Redis server hostname and port (e.g. argocd-redis:6379).
      --redis-ca-certificate string           Path to Redis server CA certificate (e.g. /etc/certs/redis/ca.crt). If not specified, system trusted CAs will be used for server certificate validation.
      --redis-client-certificate string       Path to Redis client certificate (e.g. /etc/certs/redis/client.crt).
      --redis-client-key string               Path to Redis client key (e.g. /etc/certs/redis/client.crt).
      --redis-insecure-skip-tls-verify        Skip Redis server certificate validation.
      --redis-use-tls                         Use TLS when connecting to Redis.
      --redisdb int                           Redis database.
```

For username and password, we would need environment variables to pass the username/password.

### PR DESCRIPTION
**Pull request by gdsoumya**
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>

This PR adds support for the Redis ACL username/password authentication. ref: https://redis.io/topics/acl

Changes:
- Adds an optional `REDIS_USERNAME` env var to take the username required for auth, `REDIS_PASSWORD` is already available. If Username is not passed Redis reverts to the default username keeping it backward compatible with non-ACL auth.

Closes #8675

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]
LGTM

**Review by alexmt — CHANGES_REQUESTED** [review]
thank you @Soumya Ghosh Dastidar! Can you please add redis username & password to [argocd-cmd-params-cm.yaml](https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml) and optional env variable bindings in api/reposerver server and controller manifests (example https://github.com/argoproj/argo-cd/blob/master/manifests/base/server/argocd-server-deployment.yaml#L25)

**Comment by jessesuen** [comment]
@alexmt since password is sensitive, it shouldn't be in a configmap. And we don't have a secret env var binding

**Comment by alexmt** [comment]
Oh, good point. Requested to add into configmap without thinking. LGTM

**Review by alexmt — APPROVED** [review]

**Pull request merged**
