### PR TITLE
feat: argocd-util can now validate RBAC configuration

### LINKED ISSUE #4842: Provide tooling to test & debug RBAC policies
# Summary

We should provide a mechanism/tool so that users can test & validate RBAC policies before configuring them in live Argo CD instances.

# Motivation

RBAC policies currently can be hard to understand, test and troubleshoot. There is no convenient way for users to check whether the RBAC policies they configure actually do what they expect them to do. This can lead to frustration, as well as insecure or unexpected configurations.

# Proposal

We should provide an easy way for users to test & troubleshoot RBAC policies. Currently, what we provide is the `argocd account can-i` command that users can use to check whether they are authorized for certain operations on given resources in the live system. The limit with that is a) that it's working on the live system and b) checks permissions for the logged in user only.

What we need is a similar tooling that is not running against the API, but work on local policy files. 

I can imagine this built into `argocd-util`, i.e. to check whether a group `somegroup` can perform `get` actions for all `applications` resources from a policy in `~/policy.csv`:

```
argocd-util rbac can somegroup get applications '*' --policy-file ~/policy.csv
```

Additionally, if the user has connection to K8s cluster and appropriate permissions, tooling could read-out the current live policy and test against it to answer certain questions about live state (i.e. user calling saying "I cannot create application, I get permission denied")

### PR DESCRIPTION
**Pull request by jannfis**
Closes #4842

This PR adds a new group of commands to `argocd-util`, so that users can validate and test their RBAC policies against a local CSV file, a local YAML representation of a ConfigMap or a live ConfigMap in the cluster.

The first two new commands are:

* `argocd-util rbac can SUBJECT ACTION RESOURCE [SUB-RESOURCE]` - test whether a given subject has permissions to execute given action for given resource (and possibly, sub-resource).
* `argocd-util rbac validate` - test whether a local file contains a valid policy definition to be used by Casbin

Policy can either be given as file, using `--policy-file FILE`, or read from the current cluster context in namespace given by `--namespace NAMESPACE`. In the latter case, the name of the ConfigMap in the cluster is hard wired to `argocd-rbac-cm`.

User can chose to perform the test with the built-in policy augmented to the local policy (`--use-builtin-policy`, defaults to `true`) and set a default role (similar to `policy.default`) using `--default-role ROLE`.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
looking

**Review by alexmt — APPROVED** [review]
Awesome! Thank you @jannfis . 

LGTM

**Comment by kennethtxytqw** [comment]
Is this part of a release yet?

**Comment by jannfis** [comment]
@kennethtxytqw Will be part of [v1.9](https://github.com/argoproj/argo-cd/milestone/21) release.

**Pull request merged**
