### PR TITLE
fix: Fix pod log viewer scrollbars

### PR DESCRIPTION
**Pull request by alexec**
1. Makes the scroll bars work how I wanted, which is visible and all data scrolls correctly. This was not possible with `List`. You must use `Grid`.
2. Don't disable `scrollToBottom` when the user tries to scroll to the bottom.

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
YOLO Approve.

**Comment by alexec** [comment]
@crenshaw-dev can I bump review pls?

**Review by crenshaw-dev — APPROVED** [review]
Local test confirms scrolls are scrollier.

**Comment by crenshaw-dev** [comment]
@alexec can you check the CI lint issue?

**Pull request merged**
