### PR TITLE
feat: upgrade k8s client to v1.23

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

PR upgrades k8s client to v1.23. PR depends on https://github.com/argoproj/gitops-engine/pull/365  (merged)

~Additionally PR upgrades Golang to v1.17 since it is required by https://github.com/kubernetes-sigs/json/issues/8~

### CODE REVIEW

**Comment by jannfis** [comment]
Just a nit: This is supposed to be a `chore`, not a `feat`

**Comment by jannfis** [comment]
Could we please separate the bump of Golang and K8s, just to have a proper revision history for it? Then we first merge Golang bump, then K8s client libraries bump.

**Comment by alexmt** [comment]
It makes sense. Created separate PR for golang upgrade: https://github.com/argoproj/argo-cd/pull/8229

**Comment by alexmt** [comment]
Golang upgrade is merged in separate PR. Now, this PR has only k8s client-related changes.  @jannfis  PTAL

**Review by jannfis — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
