### PR TITLE
fix: Minor cleanup for app errors #5273

### PR DESCRIPTION
**Pull request by emagana-zz**
fix: Minor cleanup for app errors 
Closes [ISSUE #5273]
First timer commit to fix a gramma issue

Signed-off-by: Edgar Magana emagana@gmail.com

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by pasha-codefresh — APPROVED** [review]
LGTM, Thank you

**Review by crenshaw-dev — APPROVED** [review]
LGTM! Can you follow these instructions to signoff the commit? https://github.com/argoproj/argo-cd/pull/8623/checks?check_run_id=5366665713

**Comment by emagana** [comment]
I have added the sign-off. Thanks!

**Comment by emagana** [comment]
No, no yet. Sorry got distracted with other work.. will do it ASAP

**Comment by emagana** [comment]
The force-pushed the signed-off commit is done. Thanks!

**Review by crenshaw-dev — APPROVED** [review]

**Comment by emagana** [comment]
@crenshaw-dev  Could you merge this PR? Thank you!

**Comment by crenshaw-dev** [comment]
@emagana I don't have merge permissions, but someone who does should get to this before long. :-)

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
