### PR TITLE
feat: upgrade Kustomize to v5.0.1

### LINKED ISSUE #12328: Don't use deprecated kustomize `vars` feature
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Kustomize has deprecated `vars` and new versions produce a warning when it is used.

`vars:` is currently used in a single place in this repository: `manifests/base/redis/kustomization.yaml`

**To Reproduce**

```
$ kustomize build manifests/base -o /dev/null
# Warning: 'vars' is deprecated. Please use 'replacements' instead. [EXPERIMENTAL] Run 'kustomize edit fix' to update your Kustomization automatically.
``

**Expected behavior**

No warning from `kustomize`

### PR DESCRIPTION
**Pull request by crenshaw-dev**
* Upgraded Helm
* Upgraded Kustomize
* Proactively refactored some Kustomize manifests which relied on deprecated fields

Closes #12328

### CODE REVIEW

**Comment by adrianlyjak** [comment]
I'm eagerly awaiting kustomize v5 in argoCD! the kustomize helm integration got some nice improvements in kustomize v5

**Review by 34fathombelow — COMMENTED** [review]
Quick first pass, can we mention the upgrade in the upgrade notes ?  Also looks like v5.0.1 is available with some bug fixes.

I'll spin this up tonight and do some local testing.

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Comment by crenshaw-dev** [comment]
Thanks, y'all! @34fathombelow updated as requested.

**Review by 34fathombelow — APPROVED** [review]
LGTM

**Review by pasha-codefresh — APPROVED** [review]

**Comment by thedatabaseme** [comment]
@crenshaw-dev Is this planned to be included in Argo 2.5 and 2.6 or only for future release of 2.7? Cause our Snyk scan complains about `gopkg.in/yaml.v3` vulnerabilities which are fixed in kustomize 5.x. This is marked as a high issue, therefore we have some measures to do to solve this.

**Comment by crenshaw-dev** [comment]
@thedatabaseme it is only planned to be included in >=2.7.

You could [add a custom kustomize version](https://argo-cd.readthedocs.io/en/latest/user-guide/kustomize/#custom-kustomize-versions) to your Argo CD for 5.0+.

Alternatively you could advocate upstream with the Kustomize maintainers to release a new 4.x patch with the vulns fixed.

**Pull request merged**
