### PR TITLE
test: testing gitops-engine fork pr 565

### PR DESCRIPTION
**Pull request by asaf-erlich**
This PR is just for testing https://github.com/argoproj/gitops-engine/pull/565, I don't think it actually needs to be merged but I'm not sure. Following instructions from https://github.com/argoproj/gitops-engine/pull/556#issuecomment-1906254887

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by asaf-erlich** [comment]
@crenshaw-dev any guidance on how to address the failed CI in this PR?

**Comment by crenshaw-dev** [comment]
@asaf-erlich check the logs under the image build details... I see some errors relating to client-go:

> Error: #41 101.8 server/application/application.go:119:40: cannot use appBroadcaster (variable of type Broadcaster) as "k8s.io/client-go/tools/cache".ResourceEventHandler value in argument to appInformer.AddEventHandler: Broadcaster does not implement "k8s.io/client-go/tools/cache".ResourceEventHandler (wrong type for method OnAdd)

(one of several)

After that, I'd pull up argo-cd in some go IDE and just follow the red squigglies to start finding/tackling bugs. My guess is most are related to modified or removed methods in the k8s libraries.

**Comment by crenshaw-dev** [comment]
Ah there are also some helpful messages at the bottom of the diff. https://github.com/argoproj/argo-cd/pull/16967/files

**Comment by blakepettersson** [comment]
Hi @asaf-erlich,

Thanks for the PR! This will be superseded by #17491, and it seems pretty likely that that will be the PR to be merged. Closing for now - if you feel otherwise feel free to reopen.

**Pull request closed without merging**
