### PR TITLE
feat: support managing cluster resources in a namespaced mode

### LINKED ISSUE #4502: Allow control of cluster level resources independent of namespace options
# Summary

ArgoCD should allow some flexibility on managing cluster level resources, independent of what namespaces are selected.

# Motivation

I had an issue deploying cert-manager to a cluster in the `cert-manager` namespace. More details are [here](https://github.com/argoproj/argo-cd/issues/4105#issuecomment-704388745).

It was not apparent from the errors that it was ArgoCD's error, but it raised the question about a limitation of the current namespace support for a cluster.

Currently, if you add a cluster but only allow argocd access in certain namespaces, then it cannot manage cluster level resources. In cert-managers case, it needs to create cluster level resources as part of the helm chart.

So perhaps, rather than linking to the namespace selection, there should be additional settings available when adding a cluster to argocd?

# Proposal

I don't have a concrete solution, but here is a couple possibilities:

1) add another flag to `argocd cluster add` command such as:

```
--cluster-resources=true/false (default: true)
```

2) ~Tie in access to cluster resources to argocd's project permissions?~ Scratch this, you can already limit cluster level resources by project.

From a security perspective, I think this is a `cluster add` configuration issue. I'd want to limit the cluster level access of the argocd service account. By default it'll have all, but then controlled by argocd's rbac... but what if the account is breached.. it can do anything in multiple clusters.

The other side is, I want to control the namespaces allowed to have argocd. But I always want argocd to be able to create some cluster level resources to meet my needs. This was, if the service account were breached, it would only have a limited set of permissions. This is preferable to the scenario above.

2 (2nd attempt) - In the cli, we allow a list of cluster resources to be added, that argocd can control:

eg.

```
--cluster-resource=namespaces,clusterrole,clusterrolebinding
# or
--cluster-resource=namespaces --cluster-resource=clusterrole --cluster-resource=clusterrolebinding
```

With the assumption... you can do whatever with those resources if enabled.
Otherwise this becomes more complicated again.

This follows the namespace pattern i've used:

```
argocd cluster add <SOME_CLUSTER> --namespace="fim" --namespace="rabbit" --namespace="monitoring" --namespace="cert-manager" --namespace="default" --upsert
```

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes https://github.com/argoproj/argo-cd/issues/4502
Depends on https://github.com/argoproj/gitops-engine/pull/297

---

PR introduces an additional setting that enables managing cluster-level resources of a cluster in a namespace mode.
The main use case is k8s cluster addons management when one Argo CD deploys platform level app (e.g. ingress controller, argo rollouts/workflows ) into multiple clusters. In this case, Argo needs to manage resources in 2~3 namespaces and CRDs. So it is beneficial to "watch" only some namespaces instead of whole cluster + cluster level resources. 

Three additional CLI commands had been added to `argocd-util`: 

* `argocd-util cluster namespaces` - prints list of clusters and namespaces managed in each cluster

```
argocd-util cluster namespaces
CLUSTER                         NAMESPACES
https://kubernetes.default.svc  dex,argo,argocd,default (total 15)
```

* `argocd-util cluster namespaces enable-namespaced-mode` - switches clusters into namespaced mode

```
# switch all clusters with 2 or less managed namespaces into namespaced mode
argocd-util cluster namespaces enable-namespaced-mode '*' --cluster-resources --max-namespace-count 2
```

* `argocd-util cluster namespaces disable-namespaced-mode` - disables namespaced mode

```
# disable namespaced mode for all clusters
argocd-util cluster namespaces disable-namespaced-mode '*'
```

### CODE REVIEW

**Comment by alexmt** [comment]
@jessesuen can you take a look please?

**Comment by jannfis** [comment]
I'm wondering what exactly is the benefit of this mode? Will Argo CD still have to have full cluster level permission for this to work? Is the only benefit that we'd need to watch for changes on less namespaces, as opposed to watch for changes on all namespaces in the cluster?

**Comment by alexmt** [comment]
@jannfis , this change is mostly about performance: Argo CD might be configured to "watch" some namespaces and cluster level resources. This is beneficial if Argo CD is used to manage 1~2 namespaces + CRDs in hundreds of clusters. 

Additionally full cluster permissions are not required. Admin can provide token that has permissions to required cluster level resources only and required namespaces. Other cluster level resources can be excluded using resource exclusions.

**Review by mayzhang2000 — APPROVED** [review]
LGTM

**Pull request merged**
