### PR TITLE
feat: Add extraValues field to ApplicationSourceHelm that overrides values

### LINKED ISSUE #8013: Ability to customise values section when deploying a helm chart
# Summary

I want to customise and patch argocd application resources using `kustomize`,
 there's no support for patching values because `spec.source.helm.values` is a string.

The only way is to patch with `spec.source.helm.parameters` but that's annoying when you have many nested values.

# Motivation

I'm maintaining apps of apps for many platforms, and I would avoid DRY.

Using  kustomize to  customise my apps in different platforms/ and environments without the need to replicate manifests. single source of truth for my platforms.

# Proposal

How do you think this should be implemented?

Add a field that holds values as raw yaml instead of string (make it backward compatible of course!)

I was assuming that argocd application has a field that supports yaml (like crossplane provider helm does https://github.com/crossplane-contrib/provider-helm/blob/master/apis/release/v1beta1/types.go#L71)

This is a super important feature!

### PR DESCRIPTION
**Pull request by mcbenjemaa**
Adding `extraValues` field to `ApplicationSourceHelm`, will make it easier when rendering argocd application with kustomize.

The Idea is to apply patches to `extraValues` that essentially will override and merge with `values`. (helm template)

With this approach, we can seamlessly patch our arogcd Application with kustomize.

My team rely on this feature, and I believe many others need it.

(BTW, I was about adding a field e.g. `rawValues` which is in raw YAML format, but since argocd relies on protobuf. I've got an error like this {cannot embed type Object} 
 So, I didn't find a solution.  As I'm just a protobuf noob ).

-- Please share your feedback if you have any?

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Test using this demo repo: https://github.com/mcbenjemaa/argocd-apps

Fixes: #8013
Ref: #2936
Enhancement Proposal Ref: #8579

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@mcbenjemaa just to confirm: the additional field simply provides a place to kustomize-patch values where an Application already has hard-coded `values`?

**Comment by crenshaw-dev** [comment]
Argo Workflows has an example of an arbitrary-type field in a CRD: https://github.com/argoproj/argo-workflows/blob/master/pkg/apis/workflow/v1alpha1/plugin_types.go

I wonder if we could actually just change the type of `values` to accept either a string or an object.

**Comment by mcbenjemaa** [comment]
@crenshaw-dev  I'm not able to add this field as Object, there's some errors in the `codegen`

**Comment by mcbenjemaa** [comment]
> @mcbenjemaa just to confirm: the additional field simply provides a place to kustomize-patch values where an Application already has hard-coded values?

With this approach, we can override `values` via this new field `extraValues`

**Comment by mcbenjemaa** [comment]
Really! 

`extraValues` could be a list? 
I don't have that in my current setup but maybe we need it someday!

So, shall I change it to list?

**Comment by crenshaw-dev** [comment]
@mcbenjemaa yep, I think it could be a list of strings! I'd recommend making that change.

Spec changes usually get reviewed pretty carefully. I'm not sure how other reviewers will feel, so I've asked for opinions [in Slack](https://cloud-native.slack.com/archives/C020XM04CUW/p1646318111102019).

**Comment by alexmt** [comment]
As I understand this change is required for users who users kustomize to produce applications that are using helm to generate manifests. This is a pretty narrow use case so it would be great to avoid adding an additional field.

Instead of adding `extraValues` I'm proposing to change existing `values` field so it would accept string or map. So that user could specify both:

```yaml
  source:
    helm:
      values: |
        ingress:
          enabled: true
```
or 

```yaml
  source:
    helm:
      values:
        ingress:
          enabled: true
```

This can achieved using custom json marshaler and `+protobuf` annotations. I suggest to use k8s `Quantity` as an example:

https://github.com/kubernetes/kubernetes/blob/72232dfb43598e1e4cb3231ef67ed4c6116a9044/staging/src/k8s.io/apimachinery/pkg/api/resource/quantity.go#L83

**Comment by crenshaw-dev** [comment]
Strong agree. @mcbenjemaa let me know if you need help with the typing for the `values` field. Folks should also be able to help in #argo-contributors in [CNCF Slack](https://argoproj.github.io/community/join-slack/).

**Comment by mcbenjemaa** [comment]
I will give it a try!

**Pull request closed without merging**
