### PR TITLE
feat(api+cli): Add new flag to diff command to diff live app against application manifest (#4706)

### LINKED ISSUE #4706: argocd app diff for app-of-apps
# Summary

`argocd app diff --new-application-file app.yaml` should give a diff of what would be generated for a change to an Application object

# Motivation

I'm trying to build a CI pipeline using the app-of-apps pattern, so my git repo contains a bunch of yaml files each of which contains an Application definition. The root app applies this whole directory.

I want to be able to (pre-merge, in a PR), get a diff of the actual changes that would happen, so I want to be able to run a command and pass it a file (or directory would also work), and generate the diff of what would be generated from the new Application object vs the one on the cluster. The current `argocd app diff --local` is very hard to use, because these charts are all being pulled from helm repositories (some internal, some external), so I don't have a convenient chart directory that's matching the version the new application is trying to install.

# Proposal

New CLI flags / command?

### PR DESCRIPTION
**Pull request by okhoshi**
This PR adds an action in the API to generate the resource manifests for a given application manifest. It also adds a flag to the `diff` command so live app can be compared to application manifest without changing state of the cluster.

Closes #4706
Probably helps for #6167 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by eddycharly** [comment]
Looks like a great feature. Would it allow to get a diff when using the app of apps pattern ?

**Comment by Okhoshi** [comment]
> Would it allow to get a diff when using the app of apps pattern ?

I think so yes.

**Comment by eddycharly** [comment]
> I think so.

it would be awesome. I’ll need to try it out !

**Comment by eddycharly** [comment]
I compiled your code and gave it a try.

I'm not sure i'm using it correctly though, I expected it to _recurse_ between parent and child applications. 

Also, is this supposed to work when the parent app itself is a helm chart (or is the `--app` flag supposed to point to a bare manifest) ?

**Comment by Okhoshi** [comment]
Thanks for trying it out !

> I expected it to _recurse_ between parent and child applications. 

I'm actually using the ArgoCD rendering stuff to get the resources that would be created if the application was added to ArgoCD. So yes it might not recurse, at least I don't do it explicitly.

> Also, is this supposed to work when the parent app itself is a helm chart (or is the `--app` flag supposed to point to a bare manifest) ?

The `--app` flag is indeed supposed to point to a bare ArgoCD Application manifest.

**Comment by eddycharly** [comment]
My bad, I just realize that i only built the CLI and didn't update the api server 🤦 
I will have to give it another try, thanks for answering my questions !

**Comment by felippe-mendonca** [comment]
Great feature! Very useful on integration pipelines to verify diff that will be applied! Hope have this on next ArgoCD release!

**Comment by eddycharly** [comment]
Is there a chance to get this in ? 🤞

**Comment by pacoguzman** [comment]
Hi there, is it possible to keep pushing on this? I'm interested in this as a way to validate application definition in topic branches before creating them.

So the idea will be generate the manifests locally and apply then with a dry-run with kubectl

**Comment by crenshaw-dev** [comment]
I found some issues with this PR and wrote an alternative relying on some of @Okhoshi's ideas. Please take a look: https://github.com/argoproj/argo-cd/pull/12813

**Comment by crenshaw-dev** [comment]
Closing for now since the PR has become stale. We can continue discussion on https://github.com/argoproj/argo-cd/pull/12813

**Pull request closed without merging**
