### PR TITLE
chore: Support build on s390x and ppc64le (follow #6441)

### PR DESCRIPTION
**Pull request by samding01**
This PR is following #6441 for supporting s390x and ppc64le. Verified on `amd64/s390x/ppc64le` platforms.

- Changed `esbuild-loader` to version `2.18.0`  as well as  `kustomize` to `4.4.1` to support s390x;
- Added `g++`  in the container to make `node-sass` working for both ppc64le and s390x;

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @samding01 ! Please add new platforms in CI so we can see how much longer image build it going to take: https://github.com/argoproj/argo-cd/blob/c59b8ea51de389dc8ca23017472dc176ba651668/.github/workflows/image.yaml#L83

**Comment by alexmt** [comment]
Codegen changes are not related to PR changes. Please pull latest master into your branch to fix the build failure.

**Comment by samding01** [comment]
> Thank you @samding01 ! Please add new platforms in CI so we can see how much longer image build it going to take:
> 
> https://github.com/argoproj/argo-cd/blob/c59b8ea51de389dc8ca23017472dc176ba651668/.github/workflows/image.yaml#L83
@alexmt 
Is it good to add like follows: 
```
IMAGE_PLATFORMS=linux/amd64,linux/arm64,linux/s390x,linux/ppc64le
```

**Comment by krishvoor** [comment]
Hi @jopit ^^
As discussed, can you take a peek plz?

**Comment by samding01** [comment]
The failure of `Image / publish (pull_request) Failing after 16m `  testing is related to awscli-linux,
`amd64` downloads it from `https://awscli.amazonaws.com/awscli-exe-linux-x86_64-v2.4.6.zip`.
But seems no s390x or ppc64le versions. Here is the github: `https://github.com/aws/aws-cli/tree/2.4.6` 
How to solve this issue?

**Comment by levivic** [comment]
hi @alexmt, seems the aws-cli, the missing dependency on s390x and ppc64le, is still a blocker for us. Without it, the ci workflow check will always fail while s390x/ppc64le platforms specified. I know there is the push of https://github.com/argoproj/argo-cd/pull/8032, besides that, how can we progress this further at this moment?

i am seeing similar requests for Power, blocked for the same reason: at https://github.com/argoproj/argo-cd/pull/6441 and https://github.com/argoproj/argo-cd/pull/8155
and a z request https://github.com/redhat-developer/gitops-operator/issues/278

**Comment by levivic** [comment]
> Thank you @samding01 ! Please add new platforms in CI so we can see how much longer image build it going to take:
> 
> https://github.com/argoproj/argo-cd/blob/c59b8ea51de389dc8ca23017472dc176ba651668/.github/workflows/image.yaml#L83

Not sure if ppc64le and s390x are supported in CI, if not, maybe we could remove them in image.yaml?

**Comment by alexmt** [comment]
@samding01 Sorry for blocking PR for so long. The https://github.com/argoproj/argo-cd/pull/8032 has been merged and AWS CLI is no longer bundled into image. CI should pass after merging master changes

**Comment by samding01** [comment]
@alexmt  After updating the source repo, the CI workflow tests show `Image / publish (pull_request)` is passed, but 
`Integration tests / Check changes to generated code (pull_request) ` is still failed, the error msg is limited and does not show the reason of the error, can you let's know what is this and how to change to avoid it?   Thx.

**Comment by crenshaw-dev** [comment]
@samding01 that error can generally be resolved by running `make codegen`.

**Comment by samding01** [comment]
@crenshaw-dev Thank you for your information, `Integration tests / Check changes to generated code (pull_request) ` is a  CI workflow test, how do I  run `make codegen`? Can you provide more info? Thanks

**Comment by 34fathombelow** [comment]
@samding01 you do this on your local copy of your branch.  More info can be found @ https://argo-cd.readthedocs.io/en/stable/developer-guide/ci/#why-does-the-codegen-step-fail  Make sure you have followed the toolchain setup guide.

**Comment by alexmt** [comment]
@samding01, I've checked the CI logs. Looks like only generated manifests are different. This is happened because of kustomize upgrade. You can run `make manifests` - it requires only docker.   `make codegen` should work too but it will take much more time.

**Review by alexmt — APPROVED** [review]
LGTM! Thank you!

**Comment by samding01** [comment]
Thanks @alexmt  @34fathombelow

**Pull request merged**
