### PR TITLE
fix: admin dashboard doesn't use the right context (#7563)

### LINKED ISSUE #7563: `argocd admin dashboard` errors: Unable to load data: cannot find pod with selector [app.kubernetes.io/name=argocd-redis]
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When trying to use the `argocd admin dashboard`, some pages fail to load, it shows the error
> Unable to load data: cannot find pod with selector [app.kubernetes.io/name=argocd-redis-ha-haproxy app.kubernetes.io/name=argocd-redis]

I found that if I set my default kube context to the one where ArgoCD is running, then things all seem to work.
I assume that there's some call inside of ArgoCD that doesn't use the `--context` passed in arguments to `argocd admin`.

**To Reproduce**

 - Set your `kubectl` context to a cluster other than the one running ArgoCD
 - Run `argocd admin dashboard --context whereargocdis --namespace whereargocdis`
 - Look at an application in your web browser
 - Notice errors

**Expected behavior**

No errors; page loads.

**Screenshots**

Screenshot_2021-10-28_15-44-33

**Version**

```shell
argocd: v2.1.5+unknown
  BuildDate: 2021-10-28T04:06:55Z
  GitCommit: 
  GitTreeState: 
  GitTag: 2.1.5
  GoVersion: go1.17.1
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified    
```

**Logs**

```
ERRO[0233] finished streaming call with code Unknown     error="cannot find pod with selector: [app.kubernetes.io/name=argocd-redis-ha-haproxy app.kubernetes.io/name=argocd-redis]" grpc.code=Unknown grpc.method=WatchResourceTree grpc.service=application.ApplicationService grpc.start_time="2021-10-28T15:44:38+11:00" grpc.time_ms=0.066 span.kind=server system=grpc
```

### PR DESCRIPTION
**Pull request by chetan-rns**
Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Use the context provided by the user while running the argocd admin dashboard command 

Fixes: #7563

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
Thank you!

**Comment by pearj** [comment]
This PR has broken the cli for me:

The cli crashes for me now:

```
goroutine 1 [running]:
github.com/argoproj/argo-cd/v2/cmd/argocd/commands/headless.InitCommand.func2(0xc000319680, 0xc00091ed00, 0x1, 0x10, 0x0, 0x0)
	/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/headless/headless.go:112 +0x377
github.com/spf13/cobra.(*Command).execute(0xc000319680, 0xc00091ec00, 0x10, 0x10, 0xc000319680, 0xc00091ec00)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:831 +0x582
github.com/spf13/cobra.(*Command).ExecuteC(0xc000159b80, 0x12, 0x0, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
	/go/src/github.com/argoproj/argo-cd/cmd/main.go:46 +0xe5
```

2.1.8 works fine for me.

**Comment by ocraviotto** [comment]
I can confirm I have the same issue with this change, and the reason is in the error output.
`/go/src/github.com/argoproj/argo-cd/cmd/argocd/commands/headless/headless.go:112` has
```go
if cmd.Flag("context").Changed {
```
which will cause the nil pointer exception when no "context" flag is set, as cmd.Flag(string) returns a pointer to `flag.Flag` and it will be `nil` in that case. 

The fix seems simple enough in this case, ensure `cmd.Flag("context")`is not nil before using it, for example:
```go
if cmd.Flag("context") != nil && cmd.Flag("context").Changed {
``` 
I got to this error when testing while working on a PR for #7767 and will for now include the fix there, unless someone else wants to fix it separately.

**Comment by chetan-rns** [comment]
@ocraviotto @pearj The nil pointer issue is fixed by PR https://github.com/argoproj/argo-cd/pull/7958

**Pull request merged**
