### PR TITLE
fix: do not replace namespaces

### LINKED ISSUE #12810: managedNamespaceMetadata on app removes namespace when Sync used with Force + Replace combination
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

If the application using `managedNamespaceMetadata` is synced with `Force` and `Replace` method then the whole namespace created with `CreateNamespace=true` gets deleted which is not the desired outcome I believe :D 

**To Reproduce**

Create an app with sync options:
```
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    managedNamespaceMetadata:
      labels:
        some-label: yep
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

```

after the app is created and tracking metadata is put on the namespace:
```
Name:         lpe-test
Labels:       kubernetes.io/metadata.name=lpe-test
              some-label=yep
Annotations:  argocd.argoproj.io/sync-options: ServerSideApply=true
```

go to Argo UI and sync this app with Force + Replace combination:
CleanShot 2023-03-10 at 10 56 28

this results in the namespace being deleted and recreated:
```
kd ns lpe-test
Name:         lpe-test
Labels:       kubernetes.io/metadata.name=lpe-test
              some-label=yep
Annotations:  argocd.argoproj.io/sync-options: ServerSideApply=true
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            False   Fri, 10 Mar 2023 10:47:34 +0100  ResourcesDiscovered     All resources successfully discovered
  NamespaceDeletionGroupVersionParsingFailure  False   Fri, 10 Mar 2023 10:47:34 +0100  ParsedGroupVersions     All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Fri, 10 Mar 2023 10:47:34 +0100  ContentDeleted          All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    True    Fri, 10 Mar 2023 10:47:34 +0100  SomeResourcesRemain     Some resources are remaining: pods. has 1 resource instances
  NamespaceFinalizersRemaining                 False   Fri, 10 Mar 2023 10:47:40 +0100  ContentHasNoFinalizers  All content-preserving finalizers finished
```

**Expected behavior**

namespace not being deleted

**Version**

```shell
argocd: v2.5.5+fc3eaec.dirty
  BuildDate: 2022-12-16T18:47:43Z
  GitCommit: fc3eaec6f498ddbe49a5fa9d215a219191fba02f
  GitTreeState: dirty
  GoVersion: go1.19.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.6.4+7be094f
  BuildDate: 2023-03-07T22:48:16Z
  GitCommit: 7be094f38d06859b594b98eb75c7c70d39b80b1e
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

### PR DESCRIPTION
**Pull request by blakepettersson**
When doing kubectl replace, namespaces should not be affected. This applies the fix from argoproj/gitops-engine#524. Fixes argoproj/argo-cd#12810 and argoproj/argo-cd#12539.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@blakepettersson would you mind running `go mod tidy`?

**Review by crenshaw-dev — APPROVED** [review]
Local test lgtm.

**Comment by blakepettersson** [comment]
@crenshaw-dev sure thing, done!

**Comment by crenshaw-dev** [comment]
@blakepettersson what are your feelings on a cherry-pick? Can we safely get this back to 2.7?

**Comment by blakepettersson** [comment]
@crenshaw-dev for me it would be fine to cherry pick this back into 2.7 👍

**Comment by crenshaw-dev** [comment]
@blakepettersson would you mind opening a cherry pick PR? I doubt the bot is gonna work.

**Comment by blakepettersson** [comment]
@crenshaw-dev I got a PR in #13769, does that look good to you?

**Pull request merged**
