### PR TITLE
fix: list generator elements should be optional

### LINKED ISSUE #17450: Argo CD CLI prevents appset from being created when using list generator with empty array
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

An Akuity customer reported that they are having difficulties creating an ApplicationSet with the Argo CD CLI. The ApplicationSet consists of a matrix generator that uses both the git (file) generator, and a list generator. When they try to apply the ApplicationSet with the command `argocd appset create <file>` they get the following error:

```
time="2024-02-29T12:16:12+05:30" level=fatal msg="rpc error: code = InvalidArgument desc = error creating ApplicationSet: [ApplicationSet.argoproj.io](http://applicationset.argoproj.io/) \"foobar\" is invalid: spec.generators[0].matrix.generators[1].list.elements: Required value
```

This seems to be a bug that occurs only with the CLI. When applying the ApplicationSet using the app-of-apps pattern, the ApplicationSet deploys and generates the expected Application resources.

**To Reproduce**

Here's an ApplicationSet yaml that I tested with works with app-of-apps, but not using the CLI.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: some-random-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - list:
              elements: []

  syncPolicy: {}
  template:
    metadata:
      name: "some-random-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        path: helm-dependency
        targetRevision: main
      destination:
        name: '{{.name}}'
        namespace: 'some-random-app'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

This also applies for a bare list generator (that's not a part of a matrix generator)

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: some-random-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements: []
  syncPolicy: {}
  template:
    metadata:
      name: "some-random-app"
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps.git
        path: helm-dependency
        targetRevision: main
      destination:
        name: '{{.name}}'
        namespace: 'some-random-app'
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

If you apply the first one with `argocd appset create <file>` you'll get

```
rpc error: code = InvalidArgument desc = error creating ApplicationSet: ApplicationSet.argoproj.io "some-random-app" is invalid: spec.generators[0].matrix.generators[0].list.elements: Required value 
```

If you apply the second one with `argocd appset create <file>` you'll get

```
rpc error: code = InvalidArgument desc = error creating ApplicationSet: ApplicationSet.argoproj.io "some-random-app" is invalid: spec.generators[0].list.elements: Required value 
```

**Expected behavior**

No errors.

**Version**

```shell
argocd: v2.9.3+6eba5be.dirty
  BuildDate: 2023-12-02T00:46:25Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: dirty
  GoVersion: go1.21.4
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.9.0+a93f05d.dirty
  BuildDate: 2024-03-08T13:04:27Z
  GitCommit: a93f05d0f0c7583f9a62187b5bf97cc1227adfa4
  GitTreeState: dirty
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.2+gc309b6f
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by blakepettersson**
A bug was reported, where an applicationset with an empty elements array, when created with `argocd appset create <filename>.yaml` gets a `...list.elements: Required value` error.

My hypothesis is that when calling the K8s API, golang JSON marshalling mangles the empty `elements` array to `nil`, rather than creating an empty array when submitting the `POST`.

Still need to figure out why the same setup seemingly works fine when the same appset is in an app-of-apps.

Fixes #17450

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by blakepettersson** [comment]
So, looking at this further the discrepancy between how this works in an app-of-apps setting and when invoked using `argocd appset create` seems to be the following:

1. When invoked from `appset create ..`  the `ApplicationSet` gets marshaled as an `ApplicationSet`, without any indirection, causing `elements` to be `nil`.
2. When synced in `SyncAppState`, the `ApplicationSet` gets marshaled as an **`Unstructured`**, where there is a bunch of weird marshaling logic going on. This causes the marshaled JSON string to have an _empty array_ of `elements`.

Thoughts?

**Comment by blakepettersson** [comment]
An example appset, which without this patch would fail with `appset create ...`. If this appset is in an app-of-apps, it'd instead fail at a later stage (since there's no repo with that name, but that's another story).

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: some-random-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix:
        generators:
          - git:
              repoURL: git@github.com:blakepettersson/some-random-repo.git
              revision: main
              files:
                - path: some-random-file.yaml
          - list:
              elements: []
              elementsYaml: "{{ .clusters | toJson }}"

  syncPolicy: {}
  template:
    metadata:
      name: "some-random-app-{{.env}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:blakepettersson/some-random-repo.git
        path: "some-random-path/{{.env}}"
        targetRevision: main
      destination:
        name: '{{.name}}'
        namespace: 'some-random-app-{{.env}}'
      ignoreDifferences:
        - group: argoproj.io
          jsonPointers:
            - /status
          kind: Application
      syncPolicy:
        automated:
          allowEmpty: true
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
```

**Comment by jannfis** [comment]
> A bug was reported

Reported where? Care to link it, please?

**Comment by blakepettersson** [comment]
> Reported where?

Internally by an Akuity customer - I cannot link to the reported bug sadly 😞

**Comment by jannfis** [comment]
> I cannot link to the reported bug sadly

Care to open a bug on GitHub describing this problem? It would help others in the community who happen to stumble over it.

**Review by alexmt — APPROVED** [review]
LGTM!

**Pull request merged**
