### PR TITLE
docs: Fix app patch doc

### PR DESCRIPTION
**Pull request by lacarvalho91**
The doc currently looks a bit messed up on the docs site:
Screenshot from 2023-01-27 13-37-06

This PR fixes that and aligns the page with other command reference docs (I copied the structure used in the app create doc)

Signed-off-by: Lawrence Carvalho <lacarvalho91@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
There's no diff... was this PR superseded by something else?

**Comment by lacarvalho91** [comment]
@crenshaw-dev not sure how that happened, i've pushed the changes again now but I'm having problems running the codegen make target

**Comment by lacarvalho91** [comment]
OK so it seems that if i run codegen it reverts my change...not sure where i should be making this change then

**Comment by lacarvalho91** [comment]
OK did some digging and noticed that the docs are generated from the cobra commands, so i've updated the command itself

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
