### PR TITLE
fix(sso): Set redirectURI for gitea, google, oauth Dex connectors

### PR DESCRIPTION
**Pull request by xianzheTM**
Just like #4222
Signed-off-by: ylxianzhe <ylxianzhe@outlook.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by blakepettersson** [comment]
Can you update [dex_test](https://github.com/argoproj/argo-cd/blob/master/util/dex/dex_test.go#L273) as well?

**Comment by xianzheTM** [comment]
> Can you update [dex_test](https://github.com/argoproj/argo-cd/blob/master/util/dex/dex_test.go#L273) as well?

Ok

**Review by blakepettersson — APPROVED** [review]

**Comment by fengshunli** [comment]
@crenshaw-dev @alexef can be merged

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@xianzheTM please forgive my ignorance on this... how do we know that the particular connector types require a redirect URI?

**Comment by xianzheTM** [comment]
@crenshaw-dev 
Sorry for taking so long to reply.
I just checked all the connectors of the dex to see which ones need to be configured with "redirectURI".
https://github.com/argoproj/argo-cd/blob/f602e8191f16e2317f9f6bd04393736e7c8f7a92/util/dex/config.go#LL149-L158C2
As noted here.

**Comment by crenshaw-dev** [comment]
@xianzheTM can you point to where in the Dex docs you found this information?

**Comment by xianzheTM** [comment]
@crenshaw-dev I checked the configuration of all connectors。`connectors.type.config.redirectURI`.
For example, OAuth 2.0(https://dexidp.io/docs/connectors/oauth/)：
image

**Comment by jlec** [comment]
How can we get closing this accelerated? Anything we need to do?

**Comment by xianzheTM** [comment]
@crenshaw-dev Is there anything else I need to do?

**Review by crenshaw-dev — APPROVED** [review]
Thanks @xianzheTM!

**Pull request merged**
