### PR TITLE
feat: Add width change and full revision display for badge #8484

### PR DESCRIPTION
**Pull request by choudellier-1A**
Fixes [#8484 ]
Adding two new query parameters for badges:
* keepFullRevision: to display revision without truncate after 7 characters
* width: to adjust badge's width to be compliant with full revision (but it works even without revision)

General goal is to allow display of full git tag when using helm chart when is exceed 7 characters.
It also have to have a correct display.

Examples:

Current, without changes
http://localhost:8080/api/badge?name=apptest&revision=true
badge

With full revision
http://localhost:8080/api/badge?name=apptest&revision=true&keepFullRevision=true
badge

With full revision and width adjust
http://localhost:8080/api/badge?name=apptest&revision=true&keepFullRevision=true&width=220
badge

With a very long full revision, width adjust and app name
http://localhost:8080/api/badge?name=apptest&revision=true&keepFullRevision=true&width=320&showAppName=true
badge

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by Perliz** [comment]
Great, it nicely covers the need expressed in ticket [8484](https://github.com/argoproj/argo-cd/issues/8484): "Helm revision is truncated on status badge".
Thanks [choudellier-1A](https://github.com/choudellier-1A), I'm eager to be able to use it.

**Comment by davidham** [comment]
Looks good @choudellier-1A! Couple of comments:

- I was only able to get the git hash to display as the value for `revision`; I couldn't get it to display the branch or the tag value. Not sure if that's the expected behavior or not but FYI.
- If you use `keepFullRevision` without the `width` parameter, the revision text overlaps and it looks a little janky. Is there a way to derive the width of the text from the length of the text, and not need the width parameter?

image

**Comment by choudellier-1A** [comment]
Hi @davidham, thanks for your feedback!
> Looks good @choudellier-1A! Couple of comments:
> 
> * I was only able to get the git hash to display as the value for `revision`; I couldn't get it to display the branch or the tag value. Not sure if that's the expected behavior or not but FYI.

Yes, actually the behavior change a little bit when you use helm repository instead of git: the revision show the actual helm 'tag'.
My change were more for this case.
But indeed an improvement would be to allow to choose display of git branch instead of commit hash. To check if it's possible. Should I try in this PR while I'm at it ?
It doesn't match the issue requirements.

> * If you use `keepFullRevision` without the `width` parameter, the revision text overlaps and it looks a little janky. Is there a way to derive the width of the text from the length of the text, and not need the width parameter?
> 
> image
Good point ! I could set a default width matching the full git hash length when using it. I'll do it.

**Comment by davidham** [comment]
> Yes, actually the behavior change a little bit when you use helm repository instead of git: the revision show the actual helm 'tag'. My change were more for this case. But indeed an improvement would be to allow to choose display of git branch instead of commit hash. To check if it's possible. Should I try in this PR while I'm at it ? It doesn't match the issue requirements.

No, you're right, if it wasn't in the original issue, probably better not to complicate things.

Your update looks great! My only suggestion would be that if we can automatically set the width based on the text, that the `width` attribute may not be necessary and could be removed.

**Review by davidham — APPROVED** [review]

**Comment by choudellier-1A** [comment]
> > Yes, actually the behavior change a little bit when you use helm repository instead of git: the revision show the actual helm 'tag'. My change were more for this case. But indeed an improvement would be to allow to choose display of git branch instead of commit hash. To check if it's possible. Should I try in this PR while I'm at it ? It doesn't match the issue requirements.
> 
> No, you're right, if it wasn't in the original issue, probably better not to complicate things.
> 
> Your update looks great! My only suggestion would be that if we can automatically set the width based on the text, that the `width` attribute may not be necessary and could be removed.

The width attribute has an hidden advantage compared to automatic width: we have a report that contain a lot of badge from a lot of application, it's way prettier if all of them have the same size !

**Comment by choudellier-1A** [comment]
> @choudellier-1A the CI lint is failing can you fix it?

Sure !

**Comment by choudellier-1A** [comment]
> @choudellier-1A the CI lint is failing can you fix it?

done ! Should be ok now

**Comment by choudellier-1A** [comment]
@gdsoumya 
Hi !
Can you please check again ?

**Review by gdsoumya — APPROVED** [review]
LGTM

**Pull request merged**
