### PR TITLE
fix(controller): copy visited map (#11699)

### PR DESCRIPTION
**Pull request by ornew**
This commit fixed an issue #11699 that caused a warning even if the cycle didn't exist. Fix false cycle discovery by copying the visited resource map before recursively calling of getAppRecursive

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks for the PR @ornew! Is this something we can unit test for?

**Comment by ornew** [comment]
Yes, as soon as I get the time I will add the unit test.

**Comment by Lavanya-Anbalagan** [comment]
we are facing the same cyclic Dependency issue, Can we get this merged?.

**Comment by crenshaw-dev** [comment]
@Lavanya-Anbalagan would you have time to contribute a unit test?

**Comment by ornew** [comment]
I apologize for neglecting this task.
I will update the branch and add unit tests as my hands are free today.

**Comment by ornew** [comment]
@crenshaw-dev (cc @Lavanya-Anbalagan)
I rebased the branch to master and added unit tests.

**Review by gdsoumya — APPROVED** [review]
LGTM

**Review by alexmt — APPROVED** [review]
LGTM!
Thank you

**Pull request merged**
