### PR TITLE
fix(ui): Overlapping content in the app details view on smaller screens

### LINKED ISSUE #14927: ui display is overlapped on pods view when screen width is limited
**Describe the bug**

ui display is overlapped on pods view when screen width is limited

**To Reproduce**

1. Switch to pods view
2. Adjust the width of window to make toolbar wrapped

**Expected behavior**

Display OK

**Screenshots**

Screenshot 2023-08-07 at 13 44 25

**Version**

```shell
argocd version
argocd: v2.7.10+469f257.dirty
  BuildDate: 2023-07-31T23:19:45Z
  GitCommit: 469f25753b2be7ef0905a11632a6382060bcae99
  GitTreeState: dirty
  GoVersion: go1.20.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.7.10+469f257.dirty
  BuildDate: 2023-07-31T22:05:17Z
  GitCommit: 469f25753b2be7ef0905a11632a6382060bcae99
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.4 2022-03-28T23:12:45Z
  Helm Version: v3.8.2+g6e3701e
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

N/A

### LINKED ISSUE #15129: Ui overlapping
image

### PR DESCRIPTION
**Pull request by rpelczar**
Additionally, I fixed the double horizontal scroll issue.

Before:

https://github.com/argoproj/argo-cd/assets/7262558/d10513d5-5f49-493e-b520-391f1c6baf17

After:

https://github.com/argoproj/argo-cd/assets/7262558/dc1c1528-d2cb-4f58-9092-21bcee533c6b

fixes #14927, fixes #15129 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
LGTM

**Review by alexmt — APPROVED** [review]
Thank you! LGTM

**Comment by venkatamutyala** [comment]
@alexmt can we expect to see this fix in 2.8.X or will this be 2.9.X only? I did't see a merge yet in: https://github.com/argoproj/argo-cd/commits/release-2.8/

**Pull request merged**
