### PR TITLE
chore: Remove specification of user id for the Redis workload

### PR DESCRIPTION
**Pull request by sbose78**
Since we've already set `runAsNonRoot: true` for the redis workload, we shouldn't need to set the user id in the manifests anymore. When the user id is not set, the process would get run as USER 999 / redis . See https://github.com/docker-library/redis/pull/275#event-4504951998

Also, some distributions of Kubernetes, example OpenShift "automatically" assign a non-root user id. I've tested this change on OpenShift.

Given that the specification of user id is not needed either way, I feel, we should clean this up. This undoes https://github.com/argoproj/argo-cd/pull/4800/files .

### CODE REVIEW

**Comment by jannfis** [comment]
Can you please fix the unit tests [here](https://github.com/argoproj/argo-cd/blob/75a1ea0c6183dc74d940547ebb220b5a5bb6bd63/reposerver/repository/repository_test.go#L132). We do count the number of manifests generated there, and since you've removed a Role manifest, the number is not equal to the one expected anymore.

**Comment by sbose78** [comment]
Done!

**Review by jannfis — APPROVED** [review]
LGTM, thanks!

**Comment by chrisob** [comment]
Looks like this PR isn't quite working on OpenShift, as of Argo CD 2.1.2 the HA manifests still try to `runAsUser: 1000` for redis-related workloads:

https://github.com/argoproj/argo-cd/blob/v2.1.2/manifests/ha/namespace-install.yaml#L1908
https://github.com/argoproj/argo-cd/blob/v2.1.2/manifests/ha/namespace-install.yaml#L1162

**Pull request merged**
