### PR TITLE
fix: Correction in Rocket.chat documentation 

### PR DESCRIPTION
**Pull request by raghavi101**
Fixed the documentation issue in Rocket.chat that was causing issues with notification setup - changed the rocketchat-email to be the user's SAMAccountName, not the user's email address.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
Hey :) you need to do this change inside [notification-engine](https://github.com/argoproj/notifications-engine)

**Review by christianh814 — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
Please update go.mod with new engine version and run make codegen

**Comment by crenshaw-dev** [comment]
@raghavi101 can you update go.mod to point to the new notifications engine commit?

**Comment by raghavi101** [comment]
> @raghavi101 can you update go.mod to point to the new notifications engine commit?

Hey I see alot of changes in go.mod. This is what I ran :
`go get github.com/argoproj/notifications-engine@latest`
`go mod tidy`

Let me know if I touched any code that shouldn't be disturbed.

**Comment by pasha-codefresh** [comment]
@raghavi101 you still need to run codegen locally, and commit the changes

**Review by christianh814 — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]

**Pull request merged**
