### PR TITLE
feat: Zoom in and out on resource view (#7183)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

About this PR:

Addresses https://github.com/argoproj/argo-cd/issues/7183

- This zoom implementation is strictly transformation, which is option/solution A. Panning is limited to scrolling of the enlarged rectangular area, and isn't truly panning of a view-box typical of SVG graphics.  For option B, we could convert to all SVG but its performance degrades for many rendered objects.  I've investigated this more and there is a bit of work involved.

- Zoom level is not made a view preference on the details page so that the UI in multiple browser tabs can have different zoom values. Drawback is that the zoom level will reset each time you exit and enter the details page, and it's different behavior than the grouped-node button. However, zoom level is maintained when switching from tree view to network view and vice versa.
- Grouped-node button moved to floating graph toolbar.  Zoom buttons similar to the ones seen in the Argo Workflows UI.
- CSS and tool bar can be moved to argo-ui, but is not part of this PR

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by keithchong** [comment]
zoom-01

zoom-02

**Comment by keithchong** [comment]
Hi @alexmt, @rbreeze, @ciiay, please have a look. FYI, @ciiay, I changed the button that you contributed.

**Review by rbreeze — APPROVED** [review]
LGTM! I'd like @alexmt to confirm before merging if he has time

**Review by alexmt — APPROVED** [review]
That is just awesome!

Can we persist zoom settings in user preferences for consistency? This definitely can be done later.

LGTM

**Comment by saumeya** [comment]
This is such a cool feature!

**Pull request merged**
