### PR TITLE
Testing k3s 1.23 with argocd 2.10.9

### PR DESCRIPTION
**Pull request by toby-w**
Run E2E tests on Kubernetes 1.23.17 through Github Action to verify that ArgoCD 2.10.9 can run properly on this Kubernetes version.

Please do not review or ship this PR. It is solely meant to kick off the E2E tests.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
I would gently ask that in general this type of testing be done locally to avoid using OSS runners for a very use-case-specific task.

But no worries regarding this one, will let it run and see how it goes. 🙂

Come to think of it, you might be able to do basically the same thing using a PR within your fork? I think that would count against your personal runner credit, which I think is generally sufficient for this kind of task.

**Comment by toby-w** [comment]
> I would gently ask that in general this type of testing be done locally to avoid using OSS runners for a very use-case-specific task.
> 
> But no worries regarding this one, will let it run and see how it goes. 🙂
> 
> Come to think of it, you might be able to do basically the same thing using a PR within your fork? I think that would count against your personal runner credit, which I think is generally sufficient for this kind of task.

Thank you for letting me run this here. 🙏  I'll look into how to do this within my fork going forward 😄

**Comment by crenshaw-dev** [comment]
Looks like it hit an error. I'll close the PR, but the run logs should still be available to you.

**Comment by crenshaw-dev** [comment]
Boo it hides the links. Here you go: https://github.com/argoproj/argo-cd/actions/runs/9020459988/job/24786539642

**Pull request closed without merging**
