### PR TITLE
fix(helm): oci certificates (#14877)

### LINKED ISSUE #14877: Missing ca-file flag when adding private helm oci repository
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
I have a [Harbor](https://goharbor.io/), which is self-hosted, has a self-signed certificate and neither Harbor nor ArgoCD are connected to the internet. The self-signed certificate is in the argocd-tls-certs-cm.

Trying to connect to a Harbor project helm repository fails with a certificate error. 

The `--ca-file` flag for the `helm registry login` in ArgoCD was removed in #11100 / #11540. 
Since the `--ca-file` flag is now present in helm version v3.12 ([stable helm docs](https://helm.sh/docs/helm/helm_registry_login/)) it should be added back again to Argo CD.

**To Reproduce**

Easiest to replicate in one of the argo pods

Required: self-signed Harbor and the self-signed cert added to the argocd-tls-certs-cm ConfigMap.

The `argocd repo add` fails because of a certificate error with helm:
```
argocd@argocd-server-xyz-xyz:~$ argocd repo add my.registry.com/project --name private-repo --enable-oci --type helm --username user --password pw
Password: 
FATA[0006] rpc error: code = Unknown desc = error testing repository connectivity: `helm registry login my.registry.com/project --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin.
time="2023-08-03T06:40:26Z" level=info msg="Error logging in to endpoint, trying next endpoint" error="Get \"https://my.registry.com/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
Error: Get "https://my.registry.com/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
The `helm registry login` to a Harbor project doesn't work without a cert or with the `--insecure` flag
```
argocd@argocd-server-xyz-xyz:~$ helm registry login my.registry.com/project --username user --password pw
INFO[0005] Error logging in to endpoint, trying next endpoint  error="Get \"https://my.registry.com/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority"
Error: Get "https://my.registry.com/project/v2/": tls: failed to verify certificate: x509: certificate signed by unknown authority

argocd@argocd-server-xyz-xyz:~$ helm registry login my.registry.com/project --username user --password pw --insecure
Error: insecure registry my.registry.com/project is not valid: invalid host "my.registry.com/project"
```
And most important it works to the project with the `--ca-file` flag using the mounted self-signed certificate:
```
argocd@argocd-server-xyz-xyz:~$ helm registry login my.registry.com/project --username user --password pw --ca-file /app/config/tls/my.registry.com
Login Succeeded
```
The login also works to Harbor itself without a project and with the `--insecure` flag (`helm registry login my.registry.com --username ... --insecure`)

**Expected behavior**

Argo CD is able to add a repo to a project of a private helm oci registry/Harbor running with self-signed certificates.

**Version**

```shell
argocd: v2.8.0-rc5+eee1a8a
  BuildDate: 2023-07-19T17:34:51Z
  GitCommit: eee1a8add29c0a0f7e7955534ad1963e4c949e14
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.0-rc5+eee1a8a
  BuildDate: 2023-07-19T17:34:51Z
  GitCommit: eee1a8add29c0a0f7e7955534ad1963e4c949e14
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

<!-- **Logs**

```
Paste any relevant application logs here.
``` -->

### PR DESCRIPTION
**Pull request by sabre1041**
Corrections to how certificates are handled within OCI based Helm charts

* Passing certificates when authenticating to remote registry
* Mutual TLS when pulling charts

Fixes #14877

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by fletch3555** [comment]
Just to confirm, do you not also need to add those args in the RegistryLogout method? They previously existed there (removed in #11540)

**Comment by sabre1041** [comment]
@fletch3555 no it is not needed for Logout as there is no communication with the remote endpoint, plus it is not an option in Helm

**Comment by dhruvy1** [comment]
Are there any updates on this PR?
Would love to use this functionality soon, seems like the PR just needs approval.

**Review by gdsoumya — APPROVED** [review]
LGTM

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by svghadi** [comment]
Will this be backported to 2.10 and older versions?

**Comment by svghadi** [comment]
Hi @ishitasequeira, any update on backporting of this fix? Thanks

**Comment by ishitasequeira** [comment]
@svghadi The PR has been cherry-picked to 2.9 and 2.10. It should be available in next minor releases for 2.9 and 2.10

**Pull request merged**
