### PR TITLE
fix: Allow unsetting the last remaining values file (#3644)

### LINKED ISSUE #3644: CLI: Last remaining values file cannot be unset
**Describe the bug**

When unsetting values files with `argocd app unset` using the `--values` flag, it is not possible to unset a values file if it is the only one remaining.

**To Reproduce**

Have an application with one values file which can be removed without breaking the Helm chart, and try to unset it using `argocd app unset`. Nothing will happen.

**Expected behavior**

The last remaining values file is unset, leaving no values files.

**Version**

```shell
$ argocd version
argocd: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:05:28Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.5.5+0fdef48
  BuildDate: 2020-05-16T04:04:43Z
  GitCommit: 0fdef4861e12026e133224f7c9413072340e2983
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.5.4 GitCommit:3af514fa9f85430f0c1557c4a0291e62112ab026 BuildDate:2020-01-11T03:12:59Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

### PR DESCRIPTION
**Pull request by sfynx**
Because the `setHelmOpt()` function does not act on empty inputs, it 
would do nothing when removing the last remaining values file using `argocd app 
unset`.
The parameter overrides are actually being unset correctly, so this has 
been changed to work the same way by manipulating `app.Spec.Source.Helm` 
directly.

This fixes #3644.

Checklist:

* [b] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — DISMISSED** [review]
Hi @sfynx, thanks a lot for this contribution as well! :) As also noted in #3646, it would be great to ensure that this feature works by adding an end-to-end test.

**Comment by sfynx** [comment]
I have added a more elaborate test that adds and verifies multiple values files, then deletes one to make sure the other one is still left, and finally deletes the last one and makes sure we end up with nothing left. I have verified that this latest check fails on latest master, and succeeds on this PR.

**Comment by sfynx** [comment]
Interesting, the e2e test actually failed on another test I did not touch.

**Comment by jannfis** [comment]
Awesome @sfynx! Thanks a lot for adding the test as well. 

The E2E test that has failed is flaky and should be fixed in current master, so if you rebase your PR, the test should turn green.

**Comment by bitfactory-henno-schooljan** [comment]
I've made this branch up to date, some tests seem to be stuck, perhaps we have to trigger them again.

**Comment by sfynx** [comment]
I've made this branch up to date. The tests seem to be stuck, perhaps we have to trigger them again.

**Comment by jannfis** [comment]
Just push an empty commit to re-trigger the CI, as described in https://argoproj.github.io/argo-cd/developer-guide/faq/#can-i-retrigger-the-checks-without-pushing-a-new-commit :)

**Comment by alexmt** [comment]
Ops, I'm sorry @sfynx . I merged commit that touched imports in  `app.go` and `helm_test.go` files and again caused merged conflicts.

**Comment by sfynx** [comment]
I resolved the conflicts, but tests are still not running.

**Comment by alexmt** [comment]
For some reason CircleCI have issues with this PR. triggered it manually.

**Comment by alexmt** [comment]
tests succeded but status is still not reflected :( trying to close/open PR

**Review by alexmt — APPROVED** [review]

**Pull request merged**
