### PR TITLE
feat: add user-defined css overlay (#3642)

### PR DESCRIPTION
**Pull request by aistein**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

This is a partial solution to the features requested in issue #3642 .  Included here is implementation of the ability to load arbitrary custom CSS to the ArgoCD UI during runtime via the `argocd-cm` configMap.  This dynamic loading of the custom CSS is important as, otherwise, operators would need to rebuild ArgoCD images from source code in order to add new styles.

This code has been tested locally by configuring the `argocd-cm` configMap as follows:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
data:
  ui.cssurl: "./myStyles.css"
  myStyles.css: |
    .nav-bar {
      background: linear-gradient(to bottom, #333, #444, #555, #4666, #212);
    }
```

Users who wish to take advantage of this feature will have to mount files like `myStyles.css` from the configMap above into `argocd-server` container, like this (YAML code shortened with `...` for readability):
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  ...
spec:
  template:
    ...
    spec:
      containers:
      - command:
        ...
        volumeMounts:
        ...
        - mountPath: /shared/app/myStyles.css
          subPath: myStyles.css
          name: my-styles
      ...
      volumes:
      ...
      - configMap:
          name: argocd-cm
          items:
            - key: myStyles.css
              path: myStyles.css
        name: my-styles
```

The above configuration created the UI snapshotted below during testing:
image

### CODE REVIEW

**Comment by astein-te** [comment]
@jannfis @alexmt please review when y'all get a chance

**Review by jannfis — CHANGES_REQUESTED** [review]
I was wondering whether we can go without an additional mount from the ConfigMap. I think of cases where someone removes the key in the ConfigMap and forgets to update the Deployment resource to remove the mount, and the pod won't start because it can't mount the volume.

Since we have access to the values of the ConfigMap from within `argocd-server` process, maybe it would be a better idea to just use an `emptyDir` volume (and mount it by default, to some path in the pod) and write out the contents of a (statically defined) key such as `customUiCss`. Since we also have an informer for the `argocd-cm` ConfigMap, we get notified of changes and can overwrite any existing custom CSS in the container as people change it in the ConfigMap.

So either that, or we might introduce a dedicated ConfigMap just for storing custom CSS files and provide that as directory mount to the pods - so that every key from the ConfigMap will become a unique file within a given path and everything is fine as long as the ConfigMap exists.

What do you think?

**Comment by astein-te** [comment]
> I was wondering whether we can go without an additional mount from the ConfigMap. I think of cases where someone removes the key in the ConfigMap and forgets to update the Deployment resource to remove the mount, and the pod won't start because it can't mount the volume.
> 
> Since we have access to the values of the ConfigMap from within `argocd-server` process, maybe it would be a better idea to just use an `emptyDir` volume (and mount it by default, to some path in the pod) and write out the contents of a (statically defined) key such as `customUiCss`. Since we also have an informer for the `argocd-cm` ConfigMap, we get notified of changes and can overwrite any existing custom CSS in the container as people change it in the ConfigMap.
> 
> So either that, or we might introduce a dedicated ConfigMap just for storing custom CSS files and provide that as directory mount to the pods - so that every key from the ConfigMap will become a unique file within a given path and everything is fine as long as the ConfigMap exists.
> 
> What do you think?

@jannfis The CSS in `myStyles.css` from the above example does not have to be mounted from the `argocd-cm` configMap - it could be mounted from anywhere the user desires;  I just did it in `argocd-cm` in this example for simplicity.   Importantly (and at the behest of @alexmt ) users should also have the option of this CSS being loaded from a remote URL - not being forced to mount a file on the container.

I think you're probably right - the CSS itself (if it is to be mounted on the container) should be stored in a separate configMap, and should be mounted in a distinct directory.   This way we don't have to use subPaths to avoid deleting files in existing directories, and so any live updates to that CM will be immediately propagated into the mounted file ([referring to this doc](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#mounted-configmaps-are-updated-automatically)).

The worry about causing the pod to fail starting up is totally legitimate.   Maybe to deal with that, I can simply add a check (either in the backend or the frontend) that - if the file does not exist - emits a warning to the logger, but does not block the continued operation of the server.   Would that work do you think?

**Comment by alexmt** [comment]
@jannfis  I've suggested using volume mounting + config map because creating custom CSS is a time-consuming process either way and delivering it into the pod is the simplest part.

The real-life CSS is going to be much longer. Most likely it will be developed as a separate project, probably using Argo CD UI dev server, and delivering CSS content into Argo CD pod is the simplest step. So I think developing convenient way to package CSS is probably overkill. 

As @astein-te mentioned we also need to support externally hosted CSS.

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
@astein-te @alexmt Ah, alright. I see the use-case for externally hosted CSS. Also, current method would allow to inject custom CSS using init container. I thought mounting a volume from CM would be a requirement here, but it's not. So thumbs up from me as well :+1:

**Review by jannfis — APPROVED** [review]
LGTM after further discussions.

**Pull request merged**
