### PR TITLE
fix: adds WebSocket ping to interactive terminal (#14191)

### LINKED ISSUE #14191: WebSocket connection for terminal is closed due to lack of keepalives
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The WebSocket functionality used for the interactive terminal does not currently include any sort of keepalive. Because of this, if Argo is behind a load balancer that times out idle connections, the terminal will eventually stop working after being idle for long enough and need to be restarted.

I have a patch ready already that I have tested in my environment and found that it solves the problem - this issue is for bookkeeping purposes.

**To Reproduce**

In my case I have Argo running behind an ALB in AWS, where the default timeout is 60 seconds. If I open a terminal to a pod and leave it alone for 60+ seconds, it will silently stop working and the Argo CD server logs a WebSocket error on the other side. Doing something to keep activity going (e.g. printing something in a loop) prevents it from being closed.

**Expected behavior**

Terminal should remain open and functional until closed by the user.

**Screenshots**

**Version**

2.7.6 (exists in all prior versions with the terminal functionality as well)

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by erhudy**
This adds a WebSocket ping message on a 5-second interval, sent from the server to the client. This ensures that the interactive terminal will remain open and won't be closed by load balancers that are reaping idle connections.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
@erhudy let's get this into 2.8 at least. If it doesn't cause any problems, we can cherry-pick back to previous releases.

**Comment by bradenwright-opunai** [comment]
What version was this added to, I' on `v2.8.0+804d4b8` but we are still running into this issue.

**Comment by bradenwright-opunai** [comment]
Fwiw, I tried to upgrade to v2.8.3+77556d9 but it still seems to hang, any idea of what version got fixed or if there is a further problem.

**Comment by erhudy** [comment]
I am running 2.8.2 and the fix is certainly present there, which I just verified by leaving a terminal open for more than 60 seconds.

**Comment by bradenwright-opunai** [comment]
@erhudy do you have a way for me to confirm that the fix is trying to keep the terminal open or not.  So I can determine if this is a new bug.  Or if some reason the fix isn't working.  B/c it seems like maybe I have an edge case that the fix isn't considering.  

I think the issue maybe that the Terminal is locking before if hits 1 min, like for example I tried to click off and come back after 45 secs and the terminal had locked.  I can check timeouts or anything else people can think of that may effect this with a Load Balancer in GCP b/c it works fine with port-forrwarding to the ArgoCD Server.

**Comment by bradenwright-opunai** [comment]
Alright so in GCP the default timeout for a backend service is 30 secs, with the default settings the terminal was hanging.  After increasing that timeout > 60 secs (currently set for 3600 secs ie 1 hr) and I've been able to wait 10+ mins and return to a working terminal.  Everything is working now as expected.

I would recoomend that the docs https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/ be updated to call out the 60 sec check that now exists and that for LB's the timeout needs to be > 60 secs

**Comment by erhudy** [comment]
That seems unusual. I don't have a Google Cloud environment to test in - I developed this fix against an AWS ALB where the timeout is 60 seconds, and my terminals definitely live longer than that with no activity now. It shouldn't be necessary to set a 1h timeout on your LB. I did check DevTools in Edge/Firefox/Safari to see if they recorded ping/pong activity for WebSocket but did not see anything on any browser I checked.

**Pull request merged**
