### PR TITLE
chore: upgrade base image to ubuntu:22.04

### PR DESCRIPTION
**Pull request by 34fathombelow**
Signed-off-by: Justin Marquis <34fathombelow@protonmail.com>

Part 2 of 3 to upgrade base image to Ubuntu:22.04
This PR upgrades base image to Ubuntu 22.04.

I do believe this will need to be cherry-picked into 2.4, the old base image will no longer recieve security updates after July 14, 2022

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by 34fathombelow** [comment]
> Thanks @34fathombelow !
> 
> I really would prefer to split this up into three separate PRs and merge them in the following order:
> 
>     1. Upgrade base image of main Dockerfile
> 
>     2. The SSH related change
> 
>     3. Upgrade base image of test containers

@jannfis Im fine with that, but the SSH related changes would need to be merged first.  Ubuntu 22.04 now uses the `libssl3` library, e2e test will not pass till this change is made first.

**Comment by 34fathombelow** [comment]
@jannfis Made the changes you requested.  Three separate PRs ( this PR, #9561,  & #9563 ) for the image base upgrade.  Just a reminder #9561 will need to be merged first. 

Our current Github CI is using Ubuntu 20.04 as a testing platform, that is why the e2e test are passing on this current PR.  I would honestly feel much more comfortable with the runners using 22.04 even though the runners are in beta.

I ran all unit and e2e tests through the dockerized toolchain using 22.04.  e2e would not complete successfully till the Kex-algorithms were updated.

**Review by jannfis — APPROVED** [review]
LGTM! Thanks!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto 2.4.

**Pull request merged**
