### PR TITLE
fix: Disable keep alives for helm https connections (#13468) (cherry pick PR release 2.7)

### PR DESCRIPTION
**Pull request by mkekeberg**
PR already merged: https://github.com/argoproj/argo-cd/pull/13695

Was asked to open PR with the commit cherry picked for various release branches. This is for release-2.7

### CODE REVIEW

**Comment by mkekeberg** [comment]
> @mkekeberg looks like there were merge issues with the cherry pick. Can you take a look?

I'm unsure what to look for. Seems to me like some earlier dependencies or similar is missing? Maybe some earlier code that was not included? Some of the variables expected are not there. Seems to be the issue with all the cherry pick PRs...

**Comment by crenshaw-dev** [comment]
It's hard to tell from the error messages. Want to just start fresh by making the changes directly against release-2.7 instead of cherry-picking? Shouldn't be too bad since it's a relatively small change.

**Comment by mkekeberg** [comment]
> It's hard to tell from the error messages. Want to just start fresh by making the changes directly against release-2.7 instead of cherry-picking? Shouldn't be too bad since it's a relatively small change.

Sorry for the late reply. Do you want me to do this to every release-branch I currently have a "cherry-pick PR" for?

**Comment by crenshaw-dev** [comment]
@mkekeberg yep I think that would be best!

**Comment by mkekeberg** [comment]
> @mkekeberg yep I think that would be best!

Did that for all the similar PRs now 🙂

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
