### PR TITLE
chore: add CODEOWNERS

### PR DESCRIPTION
**Pull request by crenshaw-dev**
This is the implementation for [scoped approvers](https://github.com/crenshaw-dev/scoped-approvers)

### CODE REVIEW

**Comment by jannfis** [comment]
I think the `OWNERS` file is not used by GitHub at all, isn't it? I always thought it's a prow thing (which we don't use). 

So, potentially, we should just keep the OWNERS file around?

**Comment by 34fathombelow** [comment]
I think we should keep the `OWNERS` file around, it is referenced multiple times in [membership.md](https://github.com/argoproj/argoproj/blob/master/community/membership.md).

**Comment by crenshaw-dev** [comment]
Updated!

**Review by 34fathombelow — APPROVED** [review]
LGTM, Thanks!

**Review by pasha-codefresh — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Pull request merged**
