### PR TITLE
Issue #10990 : Add `vim` to `docker` image

### LINKED ISSUE #10990: Unable to run `argocd app edit` when using docker image
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

 Receive `FATA[0000] exec: "vi": executable file not found in $PATH` when running `argocd app edit` inside the docker container

tested in `latest`, `v2.3.10`, `v2.4.0`, `v2.4.10`: all versions of docker image have this issue.

**To Reproduce**

 - `docker pull argoproj/argocd:latest`
 - `docker run --rm -it -v $(HOME)/.config/argocd:/home/argocd/.config/argocd argoproj/argocd:v2.4.0` (this issue exists in all the versions I've tested)
 - handle `argocd login` if not already done.
 - `argocd app edit <any_of_your_app>`

=> receive the error message above

**Expected behavior**

a valid `vi` edit screen instead

**Screenshots**

 - running `argocd app edit <any_of_your_app>` inside the container:
Screen Shot 2022-10-18 at 4 10 36 PM

 - running `argocd app edit <any_of_your_app>` on my laptop (with `vim` installed):
Screen Shot 2022-10-18 at 4 11 06 PM

**Version**

```shell
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:23:37Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.1+g5cb9af4
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

**Logs**

N/A

### PR DESCRIPTION
**Pull request by duxing**
Fixes #10990

Signed-off-by: fixit-xdu <solver.xingdu@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
As a general rule, I'd like to keep the images minimal for size and security reasons. @alexmt is full CLI support on the image something we've promised in docs or elsewhere?

**Comment by duxing** [comment]
Hi @crenshaw-dev , I 100% agree with minimizing the size and attack surface area for the docker image. 

The current version of the docker image is not self-contained: one of the commands (`argocd app edit`) is not usable due to dependency failure. 

I *assume* it's expected to work, but in case it's not in the SLA, I guess an alternative is to disable the edit command, preferably remove the `edit` from the command options.

**Comment by alexmt** [comment]
The `argocd` is available in the image primary to enable automation use cases. Most typical use case is to trigger application sync using `argocd app sync` and wait for healthy state after sync using `argocd app wait`. 

A lot of users use unchanged `argocd` image directly in CI tasks that is why we tried very hard to minimize image size and reduce number of dependencies. I agree we should not introduce vim/vi to enable `argocd app edit`

**Comment by duxing** [comment]
@alexmt I can understand the justification.

is it possible to publish a different image with full function support? e.g. `argoproj/argocd-cli`.
The current [`argocli`](https://hub.docker.com/r/argoproj/argocli) image isn't what I expected.

**Comment by crenshaw-dev** [comment]
@duxing I'd only want to maintain that in the argo-cd repo if it were a _very_ common request. It's more maintenance burden for the core dev team for what I perceive as a relatively small usability win.

But I could be underestimating the number of people would find this useful.

**Comment by duxing** [comment]
@crenshaw-dev that's understandable. I've been in similar situations too.
feel free to close this PR / issue.

**Pull request closed without merging**
