### PR TITLE
fix(appset): informer is not a kubernetes informer (#18905)

### LINKED ISSUE #18905: appset: Error `informer is not a kubernetes informer` when controller generate applications
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I think that a regression as been introduced since `2.11.3`. Now, when I run locally the appset controller, each time an application is created/updated I got this message : `informer is not a kubernetes informer` coming from [updateCache](https://github.com/argoproj/argo-cd/blob/master/applicationset/controllers/applicationset_controller.go#L552)

```
func (r *ApplicationSetReconciler) updateCache(ctx context.Context, obj client.Object, logger *log.Entry) {
	informer, err := r.Cache.GetInformer(ctx, obj)
	if err != nil {
		logger.Errorf("failed to get informer: %v", err)
		return
	}
	// The controller runtime abstract away informers creation
	// so unfortunately could not find any other way to access informer store.
	k8sInformer, ok := informer.(k8scache.SharedInformer)
	if !ok {
		logger.Error("informer is not a kubernetes informer")
		return
	}
	if err := k8sInformer.GetStore().Update(obj); err != nil {
		logger.Errorf("failed to update cache: %v", err)
		return
	}
}
```

I haven't knowledge with controller-runtime, but when I run locally on master branch vs commit in 2.11.2, I see that something change in cache implementation : `multiNamespaceCache` vs `informerCache`. Maybe a clue #17491 .

**To Reproduce**

- Create an AppSet, example https://github.com/dacofr/hello-appset/blob/main/appset.yaml 
- Watch logs

If you continue by updating appset spec, each time an application is created or updated, we have an error.

**Expected behavior**

No error log !

**Version**

Running locally based on this commit : b96be4c5e4b44d684182444bc403936ff8505470

**Logs**

```
INFO[0029] generated 3 applications                      applicationset=argocd/hello-appset generator="{&ListGenerator{Elements:[]JSON{{[123 34 110 97 109 101 115 112 97 99 101 34 58 34 100 101 118 34 125]},{[123 34 110 97 109 101 115 112 97 99 101 34 58 34 115 116 103 34 125]},{[123 34 110 97 109 101 115 112 97 99 101 34 58 34 112 114 100 34 125]},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},ElementsYaml:,} nil nil nil nil nil nil nil nil nil}"
ERRO[0029] informer is not a kubernetes informer         app=argocd/dev applicationset=argocd/hello-appset
INFO[0029] created Application                           app=argocd/dev applicationset=argocd/hello-appset
ERRO[0029] informer is not a kubernetes informer         app=argocd/stg applicationset=argocd/hello-appset
INFO[0029] created Application                           app=argocd/stg applicationset=argocd/hello-appset
ERRO[0029] informer is not a kubernetes informer         app=argocd/prd applicationset=argocd/hello-appset
INFO[0029] created Application                           app=argocd/prd applicationset=argocd/hello-appset
INFO[0029] end reconcile                                 applicationset=argocd/hello-appset requeueAfter=0s
INFO[0029] generated 3 applications                      applicationset=argocd/hello-appset generator="{&ListGenerator{Elements:[]JSON{{[123 34 110 97 109 
```

### PR DESCRIPTION
**Pull request by crenshaw-dev**
`updateCache` was introduced in https://github.com/argoproj/argo-cd/pull/15514 to avoid a bug where the appset controller would delete an app's `status` field.

The PR had to changes: 1) use `patch` instead of `update` and 2) write updates back to the informer to avoid stale data.

I think the first change is probably enough to fix the bug.

With the latest controller runtime code, I'm not seeing a way to access the underlying data store to do write-backs. But maybe at this point it's not necessary anyway.

Fixes #18905

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@alexmt does this seem reasonable, or should we dig further to find out how to write back to the informer?

**Comment by alexmt** [comment]
I've wasted a few hours and also could not find a way to access the underlying informer. PR makes sense to get rid of error message.

**Comment by crenshaw-dev** [comment]
Access the Informer Store with this One Easy Trick Kubernetes Maintainers Don't Want You to Know!

**Review by ishitasequeira — APPROVED** [review]
The change LGTM!!

**Pull request merged**
