### PR TITLE
docs: add ARGOCD_API_SERVER_REPLICAS to HA docs

### LINKED ISSUE #11593: No mention of `ARGOCD_API_SERVER_REPLICAS` in the docs
`ARGOCD_API_SERVER_REPLICAS` env var for `argocd-server` has no mention in the docs. It seems like it's used to split the `ARGOCD_MAX_CONCURRENT_LOGIN_REQUESTS_COUNT` between each replica.

https://github.com/argoproj/argo-cd/blob/661afe0ad9653418aa0e3e2cc7939e42e0db40ab/server/server.go#L159

It seems like it would make sense to include it in [the HA docs for the `argocd-server`](https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#argocd-server) since it talks about changing the replica count which would need to be reflected in that env var.

### PR DESCRIPTION
**Pull request by morey-tech**
Closes #11593

Signed-off-by: Nicholas Morey <nicholas@morey.tech>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]

**Review by blakepettersson — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@morey-tech could you rebase?

**Pull request merged**
