### PR TITLE
fix(ui): fix create app panel reappear after closed (issue #18904)

### LINKED ISSUE #18904: New App create panel 'can' reappear unexpectedly, immediately after it is closed
This appears to be introduced in the latest code in master and I suspect it is in the 2.12 RC.

The fix in question was for https://github.com/argoproj/argo-cd/issues/15961 

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

New App create panel 'can' reappear immediately after it is closed by way of the CREATE, or CANCEL buttons, or any other means to close the panel.

1. Launch the New App panel and start typing the name of the app
2. As you finish typing the name, immediately press the Cancel button
--> The New App panel will disappear, and then reappear right away
--> It will  _not_ reappear if sufficient enough time has passed after you stopped typing and before you pressed the Cancel button. (or in other words, after the delay of the debounced function has been completed, see PR of aforementioned issue) 

The issue is reproducible after pressing the CREATE button (after filling out all the required info for the app)

When creating an app (eg. after clicking on the `CREATE` button), I thought the issue was rather misleading, and I thought that the app was not created.  

The PR fix included a video showing that this issue is not reproducible....so perhaps this is not a consistently reproducible problem on demand.  However, I can reproduce it every time.  I used Chrome, Firefox and Safari.

The New App panel should not reappear

**Version**

Latest code from master, and I suspect it is in the 2.12 RC.

### PR DESCRIPTION
**Pull request by lsq645599166**
Fixes #18904

This PR fixes an issue where close the create app panel immediately after typing, the panel will reappear.

### Before

https://github.com/user-attachments/assets/4b79b031-dd97-41a4-8e2c-4034dd8ec682

### After

https://github.com/user-attachments/assets/0b01ecd9-020c-48ed-a285-4cc9ea5947b5

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by christianh814 — APPROVED** [review]

**Review by alexmt — APPROVED** [review]
Thank you!

**Comment by svghadi** [comment]
Can we backport this? It is affecting v2.12.x.

**Comment by alexmt** [comment]
Agree, created cherry-pick PR https://github.com/argoproj/argo-cd/pull/20508

**Pull request merged**
