### PR TITLE
chore: bump otel dependencies

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Dependabot was upgrading one at a time. This gets them all at once.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Is there a way to to configure dependabot to group relevant dependency upgrades?

**Comment by crenshaw-dev** [comment]
@terrytangyuan it's automatic for JS `@types` packages, but otherwise I don't think there's a grouping mechanism. Looks like it might be added soon though: https://github.com/dependabot/dependabot-core/issues/1190#issuecomment-1496603457

**Review by terrytangyuan — APPROVED** [review]
LGTM

**Review by leoluz — APPROVED** [review]
LGTM

**Pull request merged**
