### PR TITLE
feat(appset): add key title to PR generator (#16447)

### LINKED ISSUE #16447: (appset) Filtering by title on Pull Request generator
# Summary

Currently it is only possible to filter pull requests with the PR generator by target and source branches (also labels in case of Github and Gitlab). I think it would be nice to be able to do some filtering based on the PR title - especially for Git providers such as Bitbucket Server which do not support labels.

# Motivation

We use Bitbucket Server and currently we can only filter pull requests based on the source/target branch. Sometimes we would like to perform other actions on the PR before it is picked up by ArgoCD, but as source/target branches are immutable and Bitbucket doesn't support labels, we have no option to do that. Filtering based on the title would allow us to configure ArgoCD to only pick PRs with particular keywords.

# Proposal

I can have a look into this

### PR DESCRIPTION
**Pull request by ggjulio**
Closes #16447 

### Change
Add a new key `title` for all SCMaaS providers on generator `pullRequest`.

### Why
Adding the `title` allow to filter PRs by title.
Which is a must for SCMaaS like `bitbucket` that do not support labels.
(`branch` filtering is not an alternative to labels because branch names are "immutable")

Example (see `crenshaw-dev`'s comment https://github.com/argoproj/argo-cd/issues/16447#issuecomment-1836350117 ):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: preview
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - pullRequest:
            bitbucketServer:
              project: project-name
              repo: repo-name
              api: https://bitbucket.example.com
              basicAuth:
                // ...
       - list:
            elements:
            - titleMatches: '{{ regexMatch ".*[PREVIEW].*" .title }}'
    selector:
      matchLabels:
       titleMatches: "true"
template:
  // ...
```

------

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by jsoref — COMMENTED** [review]
It seems ok to me...

**Comment by ggjulio** [comment]
Thank you for the initial review.

PR rebased, e2e tests failing but not related to the updates.
Waiting for #18543 to be merged.

**Comment by ggjulio** [comment]
rebase conflicts...

**Review by ishitasequeira — APPROVED** [review]
Thanks @ggjulio!!  Overall PR looks good to me!!

**Pull request merged**
