### PR TITLE
ui: Fix delete radio labels/ids

### PR DESCRIPTION
**Pull request by Pluggi**
Signed-off-by: Antoine Bardoux <pluggi512@gmail.com>

This PR fixes the ids of the radio buttons in the delete popup. With this, you can click both the button and the text to toggle the radio button, whereas before you had to specifically click the button.

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
I am not sure that understand the issue, I am using the latest version and can click on a button or label, could you please record a short video with a problem?

**Comment by pasha-codefresh** [comment]
You didn't upload the file, could you please upload him ? @Pluggi

**Comment by Pluggi** [comment]
Github did not like my gif…

https://user-images.githubusercontent.com/1277836/165507506-23e235e3-f5fb-4777-9522-e35e5ed70f82.mp4

**Comment by Pluggi** [comment]
Btw, I am using Google Chrome™ on Linux.

**Comment by pasha-codefresh** [comment]
It is not reproducable for me on macos :(

**Review by pasha-codefresh — APPROVED** [review]
Thank you

**Comment by pasha-codefresh** [comment]
Please fix lint issue 
https://github.com/argoproj/argo-cd/runs/6193348631?check_suite_focus=true

**Comment by Pluggi** [comment]
I don't understand what the linter wants me to do, as I am not a JavaScript dev. Does it want a `.` at the end of the label?

**Comment by pasha-codefresh** [comment]
You need to run 'yarn lint --fix' inside ui folder

**Comment by Pluggi** [comment]
Done!

**Pull request merged**
