### PR TITLE
chore: Optimize e2e tests by improving EnsureCleanState

### LINKED ISSUE #20941: Optimize e2e tests runtime by improving EnsureCleanState
# Summary

Explore various strategies like batching of kubectl commands to reduce the unnecessary operations.

# Motivation

Reduce tests runtime.

# Proposal

Explore and try batching/removing unnecessary commands.

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
Closes #20941

Batch some kubectl operations, create gpg using APIs instead of CLI.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by andrii-korotkov-verkada** [comment]
Hm, namespace deletion is slow, so waiting for it is too bad.

**Comment by andrii-korotkov-verkada** [comment]
Seems to save just about 1 minute, but I'll take it.

**Comment by blakepettersson** [comment]
@andrii-korotkov-verkada it's not clear to me why this change would be faster than the current implementation. If it saves 1m it seems more like background noise than anything else...

**Comment by crenshaw-dev** [comment]
If savings are <5min, I think simpler code is worth the time.

Cleaning up logs is an independently good thing, but also probably not worth more difficult-to-read code.

**Comment by crenshaw-dev** [comment]
New code reads fine to me except the `if len(args) >` stuff. That's difficult to read.

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
