### PR TITLE
feat(metrics): git checkout failure counter (issue #15658)

### PR DESCRIPTION
**Pull request by mikolajpe**
This PR adds git checkout failure counter, that will allow people to monitor the health of repositories they fetch data from and can be alerted on the failure of any one of them.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by blakepettersson** [comment]
@mikolajprzybysz you need to sign-off your commits.

```
git rebase -i --signoff HEAD~2 
```

**Comment by mikolajprzybysz** [comment]
@blakepettersson commit signed

**Review by blakepettersson — APPROVED** [review]
LGTM, thanks!

**Review by pasha-codefresh — APPROVED** [review]
LGTM

**Comment by ebuildy** [comment]
What about the lsRemote errors?

Use case: the git branch dont exist any more, the UI is displaying error:

Capture d’écran, le 2024-04-24 à 08 49 02

But nothing on prom metrics. I could do a PR quickly as we really need alerts on this.

Also, there is `argocd_git_request_total` metric, which contain `request-type` : `fetch` or `ls-remote`, it make more sense to add a new label `status` : `success` or `fail` rather than a new metric isnit?

(relate https://github.com/argoproj/argo-cd/pull/15143)

**Pull request merged**
