### PR TITLE
fix: application stuck in infinite reconciliation loop if using wrong project

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Related to https://github.com/argoproj/argo-cd/issues/8100

Controller keep reconciling application infinitely if application is referencing non-existing project. The reason is that project validation is happening in two place but produces different error conditions. PR resolves it

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Cherry-pick all the way back through 2.3 I assume?

**Comment by alexmt** [comment]
Yeah, I would do it. It seems to be very safe fix to me and exist since 2.3 or even earlier

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Looks like we've already got some testing on `processAppRefreshQueueItem`. Is this something we could test for?

**Comment by alexmt** [comment]
Good point @crenshaw-dev ! Added missing unit test PTAL.

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.3, release-2.4 for 2.4.18, and release-2.3 for 2.3.12.

**Comment by crenshaw-dev** [comment]
@alexmt I'm going to revert in 2.3 and 2.4. I think the bug was introduced by apps-in-any-namespace, which added the second missing-project status. The test fails in 2.3/2.4.

**Pull request merged**
