### PR TITLE
fix(ui): Patch Resource missing appNamespace (#13838)

### LINKED ISSUE #13838: Unable to patch resource using UI when using application in any namespace
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Context: app in any namespace activated (`teamone-cd`, `teamtwo-cd`)

When patching a resource (ie: add label) from UI, I get the following error:

```
Unable to save changes: permission denied
```

Looking at the server log I can see the following:

```log
time="2023-05-30T19:24:55Z" level=warning msg="application does not exist" application=team-one-env namespace=argocd
time="2023-05-30T19:24:55Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied" grpc.code=PermissionDenied grpc.method=PatchResource grpc.service=application.ApplicationService grpc.start_time="2023-05-30T19:24:55Z" grpc.time_ms=6.407 span.kind=server system=grpc
```

The namespace should be `teamone-cd` and not argocd

Looking at the server code it seems that it default to Control plane namespace if query parameter `appNamespace` is not provided

I opened the chrome debugger and saw this:

```
POST https://argocd.project.com/api/v1/applications/teamone-env/resource?name=artifact-repositories&namespace=teamone&resourceName=artifact-repositories&version=v1&kind=ConfigMap&group=&patchType=application%2Fmerge-patch%2Bjson

"{\"metadata\":{\"labels\":{\"test\":\"test\"}}}"
```
We don't have the `appNamespace`

The issue is a typo in `ui/src/app/shared/services/applications-service.ts` method `patchResource`

**To Reproduce**

Deploy argocd with app in any namespace, deploy the `guestbook` app and try to update any resource

**Expected behavior**

Resource must be patched

**Screenshots**

N/A

**Version**

```json
{
    "Version": "v2.7.3+e7891b8.dirty",
    "BuildDate": "2023-05-24T15:05:34Z",
    "GitCommit": "e7891b899a35dca06ae94965ea5ae2a86b344848",
    "GitTreeState": "dirty",
    "GoVersion": "go1.19.6",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.0.1 2023-03-14T01:32:48Z",
    "HelmVersion": "v3.11.2+g912ebc1",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Logs**

N/A

### PR DESCRIPTION
**Pull request by speedfl**
Fixes #13838

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @speedfl!

**Comment by asohnlein-tsy** [comment]
I deployed this version (v2.7.4) and I still get error on manifest editing. The application is name "prom-pushgateway" and it is in "monitoring" namespace. ArgoCD still trys to lookup in "argocd" namespace as following logs show:

`time="2023-06-06T12:27:45Z" level=info msg="Creating client app (argo-cd)"
time="2023-06-06T12:27:45Z" level=info msg="argocd v2.7.4+a33baa3.dirty serving on port 8080 
.
.
.
time="2023-06-06T12:28:56Z" level=warning msg="application does not exist" application=prom-pushgateway namespace=argocd
time="2023-06-06T12:28:56Z" level=warning msg="finished unary call with code PermissionDenied" error="rpc error: code = PermissionDenied desc = permission denied" grpc.code=PermissionDenied grpc.method=UpdateSpec grpc.service=application.ApplicationService grpc.start_time="2023-06-06T12:28:56Z" grpc.time_ms=6.295 span.kind=server system=grpc
`

**Pull request merged**
