### PR TITLE
Upgrade kustomize to 3.8.9

### PR DESCRIPTION
**Pull request by ainmosni**
This fixes issue #5297.

### CODE REVIEW

**Comment by jannfis** [comment]
Hi @ainmosni, thank you for your PR. 

This is basically a dup of #5007, which has not yet been merged for the reasons specified in the issue and also failing CI. Since Kustomize tends to introduce breaking changes in patch revisions, updates are risky and often require more than just bumping up the version.

Please have a look at #5007, maybe you're up to implement the needed changes for making it work?

**Comment by ainmosni** [comment]
Hi @jannfis,

Thanks for the input, and yeah breaking changes on patch releases is not ideal, and I was not aware of that, if I get some time I'll try and look at ways to make it work.

**Comment by qrilka** [comment]
BTW 3.8.10 was just released :)

**Comment by alexmt** [comment]
Kustomize was upgraded by https://github.com/argoproj/argo-cd/commit/8569105d812ddc6fbac5b5478c053d331aa0ee34

**Pull request closed without merging**
