### PR TITLE
fix: grouped node titles no longer wrap- issue #9322

### LINKED ISSUE #9322: [UI] Grouped nodes title no longer wraps
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In the tree view, if you press the toolbar button `Group Nodes` the title any of the grouped nodes tree nodes overflows the boundary of the node.  It used to wrap properly.

See: https://github.com/argoproj/argo-cd/pull/8671/files#diff-6e5f3c7933a578a00d408e1a7d37752e68118a77102e95682f2ff54cf33f2263R177

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications/cert-manager?view=tree&resource=
2. Press the Grouped Nodes toolbar button

**Expected behavior**

The text used to wrap properly.

**Screenshots**

Screen Shot 2022-05-06 at 2 23 11 PM

**Version**

v2.4.0+8b1804c

### PR DESCRIPTION
**Pull request by reginaelyse**
Fixes #9322 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by keithchong — APPROVED** [review]
LGTM. The Grouped Nodes title wraps now.

**Comment by keithchong** [comment]
Hi @reginapizza , they have been working on a 2.4 RC last Thursday.  Since this is a simple, safe change, this might be a good candidate to fix in the `release-2.4` branch, since the text overflow issue is 'glaring' and it didn't happen before.

**Comment by crenshaw-dev** [comment]
@reginapizza could you open a PR to cherry-pick this onto the `release-2.4` branch?

**Comment by reginapizza** [comment]
@crenshaw-dev I opened https://github.com/argoproj/argo-cd/pull/9340

**Pull request merged**
