### PR TITLE
fix: Applications with suspended jobs now marked "Suspended" instead of "Progressing" (#11603)

### LINKED ISSUE #11603: App health progressing when Kubernetes Job has Suspend=true
# Summary

App Health Shows progressing when the Job spec has Suspend=true.
Screen Shot 2022-12-07 at 4 00 33 PM
		}

Please give examples of your use case, e.g. when would you use this.

Job manifest
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: node-app-job
spec:
  suspend: true
  template:
    spec:
      containers:
      - name: node-app-job
        image: alpine   #your docker image
        command: ["echo", "Welcome to my Node app"]
      restartPolicy: Never
```
With Kubernetes 1.21, a new feature was added where use can mark job as suspended
https://kubernetes.io/blog/2021/04/12/introducing-suspended-jobs/

we need to include suspend condition in the health_job.go[ gitops-engine](https://github.com/argoproj/gitops-engine/blob/1ce2acc845d230a279442eb7576203525bced9cc/pkg/health/health_job.go#L34). 

```
case batchv1.JobSuspended:
	complete = true
	message = condition.Message
	if condition.Status == corev1.ConditionTrue  {
		isSuspended = true
	}
```

### PR DESCRIPTION
**Pull request by ashutosh16**
Signed-off-by: ashutosh16 <11219262+ashutosh16@users.noreply.github.com>

Fix [argo-cd/issues/11603]( https://github.com/argoproj/argo-cd/issues/11603)
gitops-engine [PR](https://github.com/argoproj/gitops-engine/pull/484) should merge first 
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by fengshunli** [comment]
update your mod and run ci again @ashutosh16

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Can you add a screenshot showing what the new UX is?

Also, can you add a note to docs/operator-manual/upgrading/2.5-2.6.md?

> ## Applications with suspended jobs now marked "Suspended" instead of "Progressing"
> 
> Prior to Argo CD v2.6, an Application managing a suspended Job would be marked as "Progressing". This was confusing/unexpected behavior for many. Starting with v2.6, Argo CD will mark such Applications as "Suspended".
> 
> If you have processes which rely on the previous behavior (for example, a CI job with an `argocd app wait` call), update those before upgrading to v2.6.

**Comment by ashutosh16** [comment]
There are no Ux changes, the health status is the default provided by argocd.  
Screen Shot 2022-12-14 at 9 49 14 AM
Screen Shot 2022-12-14 at 9 48 59 AM

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc2.

**Pull request merged**
