### PR TITLE
Makes sure that all operation IDs and RESTy verb+noun combo

### PR DESCRIPTION
**Pull request by alexec**
This has been bugging me for ages. This makes sure that each operation ID in `swagger.json` makes sense in a verb+noun style.

### CODE REVIEW

**Comment by jannfis** [comment]
Awesome, @alexec - indeed, it is very annoying to end up with a different swaggerfile after each other `make codegen` even if nothing had changed.

I wonder if this is a breaking change to the API, tho? I guess the majority of the API's consumers are the UI (uses REST?) and the CLI anyway. 

However it is: this is a long overdue change, and I'm glad you took the time to perform this cumbersome refactoring work!

**Comment by jannfis** [comment]
What I wanted to say in the above comment: Maybe for the sake of API stability we should introduce the new verb+noun API methods in parallel to the existing ones, and mark the old ones as `deprecated` for one or more subsequent releases first while internally using the new methods already. 

Then, in one of the next releases, we remove the old flaky ones. I think from an engineering standpoint, this would be a fine way to get rid of this old cruft in the API. Sure, we would have some duplicate code in the `.proto` files for a while (maybe aliasing is possible with protobuf?), and we also would carry around this annoying swagger mixin stuff a little longer, but when the time has come, we simply remove the deprecated methods and are fine.

What do you think about this?

**Comment by alexec** [comment]
Not sure @jannfis. I'd like to get @alexmt 's thoughts.

**Comment by alexec** [comment]
API breaking change.

**Pull request closed without merging**
