### PR TITLE
fix(cli): Add Redis password to `forwardCacheClient` struct (#19035)

### LINKED ISSUE #18426: Local WebUI broken in all 2.11 and 2.10.10 and later if using ArgoCD Core
**Describe the bug**

**Note:** This report explicitly only targets `ArgoCD Core` as described at https://argo-cd.readthedocs.io/en/stable/operator-manual/core/. I do not know if and/or under which circumstances a full deploy is affected too.

When upgrading to any 2.10 release after 2.10.9 or any 2.11 release, the local WebUI (`argocd admin dashboard -n "${NAMESPACE}"`) is unable to fetch child resources and breaks when trying to show resources (as in "click on them to see the overlay with all the details") with `NOAUTH Authentication required.`:

image

I tried to reset Redis credentials as described [here](https://argo-cd.readthedocs.io/en/stable/faq/#how-to-rotate-redis-secret) - had no effect.

**To Reproduce**

* Install ArgoCD Core using:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/argoproj/argo-cd/manifests/core-install?ref=v2.10.10
```
* Deploy anything (e.g. ArgoCD Core itself)
* Start local WebUI
`argocd admin dashboard -n "${NAMESPACE}"`
* Go to localhost:8080 (or wherever local UI is running)
* Open any project
* Click on any resource

**Expected behavior**

* The details of the resource can be displayed.
* All child resources are displayed.

**Screenshots**

* When clicking on any resource that is not `kind: Application`:
image

* The WebUI does not show child resources. As an example, the `kind: Deployment` look like:
image

**Version**

* Local CLI
```shell
argocd: v2.11.2+25f7504
  BuildDate: 2024-05-23T13:58:43Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
FATA[0000] Argo CD server address unspecified    
```
* ArgoCD Core: tested `2.10.10`, `2.10.11`, `2.11.0`, `2.11.1`, `2.11.2` - all affected

### LINKED ISSUE #18464: arogcd cluster add command reports error
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have 3 minikube clusters running on a Fedora release 39 machine:

```
$ minikube profile list
|---------|-----------|------------|-----------------|------|---------|---------|-------|--------|
| Profile | VM Driver |  Runtime   |       IP        | Port | Version | Status  | Nodes | Active |
|---------|-----------|------------|-----------------|------|---------|---------|-------|--------|
| rdr-dr1 | kvm2      | containerd | 192.168.122.164 | 8443 | v1.28.3 | Running |     1 |        |
| rdr-dr2 | kvm2      | containerd | 192.168.122.51  | 8443 | v1.28.3 | Running |     1 |        |
| rdr-hub | kvm2      | containerd | 192.168.122.104 | 8443 | v1.28.3 | Running |     1 |        |
|---------|-----------|------------|-----------------|------|---------|---------|-------|--------|
```

after install argocd into rdr-hub cluster argocd namespace, I login to it and try to add cluster.
```
$ argocd login --core
Context 'kubernetes' updated

$ argocd cluster add rdr-dr1 -y
INFO[0000] ServiceAccount "argocd-manager" created in namespace "kube-system"
INFO[0000] ClusterRole "argocd-manager-role" created
INFO[0000] ClusterRoleBinding "argocd-manager-role-binding" created
INFO[0005] Created bearer token secret for ServiceAccount "argocd-manager"
ERRO[0005] finished unary call with code Unknown         error="NOAUTH Authentication required." grpc.code=Unknown grpc.method=Create grpc.service=cluster.ClusterService grpc.start_time="2024-05-31T17:28:51+08:00" grpc.time_ms=177.03 span.kind=server system=grpc
FATA[0005] rpc error: code = Unknown desc = NOAUTH Authentication required.
```

but the cluster rdr-dr1 is actually added, but just with no version, status info. see:
```
$ argocd cluster list
SERVER                          NAME        VERSION  STATUS  MESSAGE  PROJECT
https://192.168.122.164:8443    rdr-dr1
https://kubernetes.default.svc  in-cluster
```

And no error message could be found in any of the argocd pods.

Later I create application CR on rdr-hub cluster, and argocd could deploy this application to rdr-dr1 cluster without issue.

So why it reports error of "NOAUTH Authentication required“ ？

**Version**

```shell
$ argocd version
argocd: v2.11.2+25f7504
  BuildDate: 2024-05-23T13:58:43Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.11.2+25f7504
  BuildDate: 2024-05-23T13:58:43Z
  GitCommit: 25f7504ecc198e7d7fdc055fdb83ae50eee5edd0
  GitTreeState: clean
  GoVersion: go1.21.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.3.0 2023-12-07T10:45:14Z
  Helm Version: v3.11
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

### LINKED ISSUE #19035: `argocd app diff` fails when Redis is password protected
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Similar to the problem resolved by #18951, `argocd app diff` also will not authenticate when Redis is password protected.

**To Reproduce**

Run `argocd app diff` command on any of the patched versions described in this CVE: https://github.com/argoproj/argo-cd/security/advisories/GHSA-9766-5277-j5hr.

It will throw this error:
```
ERRO[0006] finished unary call with code Unknown         error="error getting cached app managed resources: NOAUTH Authentication required." grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2024-07-12T10:07:34-05:00" grpc.time_ms=545.331 span.kind=server system=grpc
FATA[0006] rpc error: code = Unknown desc = error getting cached app managed resources: NOAUTH Authentication required.
```
**Expected behavior**

I expect diff to behave normally. It was working for me before I upgraded to a version that mitigated the aforementioned CVE.

**Version**

```shell
argocd: v2.11.4+e1284e1
  BuildDate: 2024-07-02T23:16:22Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.11.4+e1284e1
  BuildDate: 2024-07-02T23:16:22Z
  GitCommit: e1284e19e03c9abab2ea55314b14b1e0381c4045
  GitTreeState: clean
  GoVersion: go1.22.4
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.13.3+gc8b9489
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

```
$ argocd app diff <application name>
ERRO[0006] finished unary call with code Unknown         error="error getting cached app managed resources: NOAUTH Authentication required." grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2024-07-12T10:07:34-05:00" grpc.time_ms=545.331 span.kind=server system=grpc
FATA[0006] rpc error: code = Unknown desc = error getting cached app managed resources: NOAUTH Authentication required.
```

### PR DESCRIPTION
**Pull request by NetanelK**
Fixes #19035
Fixes #18426
Fixes #18464

- Added optional `redisPassword` field in the `forwardCacheClient` struct, for headless mode.
- Redis password is being passed from `redisOptions` into `appstateCache` builder

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by jannfis — COMMENTED** [review]
Can we somehow test this, so that we won't run into a regression later on?

**Review by todaywasawesome — COMMENTED** [review]
Agreed, with tests this is a slam dunk.

**Comment by NetanelK** [comment]
How can I test the headless mode, I would be happy to have some help with it

**Comment by tooptoop4** [comment]
:shipit:

**Comment by tooptoop4** [comment]
who gon merge dis

**Review by pasha-codefresh — APPROVED** [review]
Fix is fine, tested it locally also, it solves the issue. 
Checking if here an easy way to cover this issue with e2e

**Comment by pasha-codefresh** [comment]
@jannfis @todaywasawesome i am going to merge this PR. Here no easy way to cover core mode with e2e tests today and same with unit. It definitely makes sense to do it, but it will requires pretty big effort to do it. I think we need to merge it, because this PR fix an issue and making things better. 

@NetanelK thank you, and sorry for delay in review

**Comment by NetanelK** [comment]
@pasha-codefresh, will this be added to older releases as a fix?

**Comment by purajit** [comment]
@pasha-codefresh when should we expect the 2.11/12 releases to come through?

**Comment by pasha-codefresh** [comment]
@purajit it requires manual cherry-picking, i will do it today, and release itself we can do for example next Monday

**Comment by garrmark** [comment]
did this happen @pasha-codefresh ?

**Comment by purajit** [comment]
@pasha-codefresh when should we expect a non-2.13 release with this fix?

**Comment by NetanelK** [comment]
@pasha-codefresh I've created cherrypick PRs (#20261, #20262) for this fix, can you take a look?

**Comment by purajit** [comment]
Thanks! I see the cherry pick branches - when will a release happen?

**Comment by purajit** [comment]
@pasha-codefresh any updates on the release?

**Comment by pasha-codefresh** [comment]
I didnt plan it, better ask in contributions channel

**Comment by purajit** [comment]
@pasha-codefresh Gotcha, I assumed the 

> @purajit it requires manual cherry-picking, i will do it today, and release itself we can do for example next Monday

message meant that a release would be cut.

Do you mean `#argo-cd-contributors` on the CNCF Slack? 

Also how far is the 2.13 release? It's been a month of waiting on releases for this important 
fix, so if there's a lot of process to go through to get it done, I can just wait for 2.13 if 
it's coming soon.

**Comment by pasha-codefresh** [comment]
2.13 GA Monday, Nov. 4, 2024.

**Comment by NetanelK** [comment]
@purajit Actually, this was released with v2.11.10 and v2.12.5 releases

**Pull request merged**
