### PR TITLE
fix(appset): performProgressiveSyncs only when the applicationset is using it (#15297)

### LINKED ISSUE #15297: Bug: Progressive Sync is processing and altering ApplicationSets that aren't using Progressive Sync
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Any ApplicationSet that doesn't use Progressive Sync is still having the status.applicationStatus altered, infinitely adding it when performProgressiveSync is called (due to an if/else bug) and then the logic sees the erroneously added applicationStatus and removes it. This happens in a perpetual loop that also is increasing the resource version which is likely causing https://github.com/argoproj/argo-cd/issues/12374 in part because these applicationsets get a large resource version.

**To Reproduce**

Enable progressive sync on the Argo instance and deploy an application set that doesn't use progressive sync

**Expected behavior**

Progressive Sync not to perform actions on non-Progressive Sync applicationsets, unless cleaning up when removed.

**Version**

v2.7.11+ec195ad.dirty

### PR DESCRIPTION
**Pull request by ericblackburn**
Fixes #15297 

Updates the if/else statement so that the else statement used to call performProgressiveSyncs is only called when the applicationset is using it. 

Note, my build is green. There seems to be some other bugs in Argo ,master, itself unrelated to this change. Those are not in scope for the this PR.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by wmgroot — APPROVED** [review]
This LGTM.

**Comment by blakepettersson** [comment]
Is there a way to do an E2E test to verify that the `Application` isn't jumping from `Healthy` -> `Degraded` -> `Healthy` with this change? Otherwise this LGTM

**Comment by ericblackburn** [comment]
> Is there a way to do an E2E test to verify that the `Application` isn't jumping from `Healthy` -> `Degraded` -> `Healthy` with this change? Otherwise this LGTM

I tried to move all the content in this parent progressive sync is On block to its own function and write up unit tests, but I ran out of time.  There are just no unit test for this area, so I would have to sit down and design that from scratch. Given my time limitations, I decided to just do the one line fix. 

Eventually, I want to dedicate more time to bettering progressive sync functionality and add more unit testing. But, it would be a while until I can do that.  I can push up a branch to my fork, if someone wants to take a look at my failed attempt at unit testing and tune it up.

**Comment by thober35** [comment]
Hi @blakepettersson,
any chance this could get approved and merged? Seeing a lot of performance impact regarding health status flapping.
Thank you!

**Review by crenshaw-dev — APPROVED** [review]
Thanks!

**Pull request merged**
