### PR TITLE
feat: App View extensions

### PR DESCRIPTION
**Pull request by rbreeze**
CleanShot 2023-01-16 at 13 13 24@2x

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexef** [comment]
This is really nice and opens up a capability we were looking for 🙏 

Will the extension view preference be exposed in the URL (i.e. so one can share a link to the view extension?)

**Comment by ashutosh16** [comment]
what would be the use case for this feature?

**Comment by alexef** [comment]
@ashutosh16 for us, devs are really confused by extra objects on the tree view (Secrets, ConfigMaps, Old ReplicaSets with 0 desired replicas etc). Being able to build a customized view would allow us to focus only on objects we want to show. Plus it will allow for tighter integration with Rollouts (better than what can be achieved with a Resource Extension)

**Comment by zeusdeux** [comment]
Seconding what @alexef mentioned. The ability to customize the screen our engineers are greeted with gives us a way of reducing errors and misclicks and optimizing for typically used paths. 
@rbreeze you legend! 🚀

**Review by alexmt — APPROVED** [review]
LGTM!

**Pull request merged**
