### PR TITLE
fix(ui): Safari crashed after upgrading react-diff-viewer

### LINKED ISSUE #6701: UI Unusable on Safari
Caused by #6700

UI Crashes in Safari with error:

```
SyntaxError: Invalid regular expression: invalid group specifier name
```

To reproduce: 
Visit https://cd.apps.argoproj.io in Safari - a white screen appears.

Safari `v14.1.1`

### PR DESCRIPTION
**Pull request by rbreeze**
Fixes #6701 

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
This will revert many of the updated dependency, according to changes on yarn.lock, and I fear ultimately re-introduce many (if not all) of the fixed critical and high severity vulnerabilities.

Don't we want to go for the root cause of this?

**Review by alexmt — APPROVED** [review]

**Comment by alexmt** [comment]
Agree with @jannfis . It would be good to try to avoid rollback. Googled this: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

Looks like something uses [lookbehind](https://caniuse.com/js-regexp-lookbehind) that is not supported by Safari yet. Trying to find if there is polyfill or similar workaround.

**Comment by alexmt** [comment]
It is https://github.com/sindresorhus/normalize-url/issues/105

**Comment by alexmt** [comment]
Another option to fix the crash and avoid reintroducing vulnerability:

https://github.com/argoproj/argo-cd/pull/6703

@rbreeze , @jannfis WDYT?

**Comment by rbreeze** [comment]
@alexmt I think that's perfect. I do think it might be a good idea to eventually replace the `react-diff-view` component, either with an alternative npm package, or our own. 

Also, I've opened an issue in the `react-diff-view` repo: https://github.com/otakustay/react-diff-view/issues/129

**Pull request closed without merging**
