### PR TITLE
feat: Deploy ArgoCD on cluster with security context (#3060)

### PR DESCRIPTION
**Pull request by Leletir**
Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [X] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by Leletir** [comment]
@jannfis do you know why the version of Kustomize is 2.0.3 ? 
In order to avoid code duplication I'm using `kustomize build --load_restrictor LoadRestrictionsNone` to be able to access patches from another directory when I'm building `ha` but it's not available on kustomize 2.x

**Comment by Leletir** [comment]
Hello @jessesuen and @jannfis, I'm looking for a way to not duplicate patches between `manifests/security-context/base/overlays` and `manifests/ha/security-context/base/overlays`, do you have any ideas ? 

Thank you for your help

**Comment by jannfis** [comment]
> @jannfis do you know why the version of Kustomize is 2.0.3 ?
> In order to avoid code duplication I'm using `kustomize build --load_restrictor LoadRestrictionsNone` to be able to access patches from another directory when I'm building `ha` but it's not available on kustomize 2.x

Hi @Leletir, hm, indeed I think it was just forgotten to update Kustomize version in the build tools image to the version that is also included in recent versions of ArgoCD (v3.2.1 currently). I have just submitted #3099 to bring it up-to-date, I'm not sure whether there is a reason behind it that I do not know of :)

However, please restrain from modifying `--load_restrictor` in calls to kustomize, since the Kustomize sources should be compatible with ArgoCD (i.e. manifests should be buildable when using the Kustomize source as an ArgoCD application).

**Comment by Leletir** [comment]
Hi @jannfis, thank you for your PR ! 

I completely agree with you on this point, but I have no idea how to not duplicate the patches between `ha` and `security-context`, maybe using [multiple-bases](https://github.com/kubernetes-sigs/kustomize/tree/master/examples/multibases) with kustomize ... if you have any idea, I'm more than interested !

**Comment by alexmt** [comment]
> @jannfis do you know why the version of Kustomize is 2.0.3 ?
> In order to avoid code duplication I'm using `kustomize build --load_restrictor LoadRestrictionsNone` to be able to access patches from another directory when I'm building `ha` but it's not available on kustomize 2.x

@Leletir we are still using kustomize 2 because of some users install argocd using https://github.com/replicatedhq/ship or `kubectl apply -k`.  Need to check if these tools aready migrated to kustomize 3

**Comment by Leletir** [comment]
Hello @alexmt, you're right kubectl 1.16 is still using kustomize 2.0.3.

So do you have any idea how I can avoid to duplicate the patches between ha et security context?

**Comment by jannfis** [comment]
Hi @Leletir, sorry for the late reply. Unfortunately, I don't know of an elegant or easy way to deduplicate the Kustomize overlays in the current scenario. I think the way you've done is what's possible with 2.0.x, so I'd be fine with this change.

We can (and should) change the overlays once we can incorporate the 3.x branch of Kustomize.

How does that sound to you?

**Comment by Leletir** [comment]
I agree with you on this point.
So what are the next steps ?

**Comment by jannfis** [comment]
> > @jannfis do you know why the version of Kustomize is 2.0.3 ?
> > In order to avoid code duplication I'm using `kustomize build --load_restrictor LoadRestrictionsNone` to be able to access patches from another directory when I'm building `ha` but it's not available on kustomize 2.x
> 
> @Leletir we are still using kustomize 2 because of some users install argocd using https://github.com/replicatedhq/ship or `kubectl apply -k`. Need to check if these tools aready migrated to kustomize 3

Hm, I checked `ship` and this project does not seem to be actively developed anymore in favour of [kots](https://www.github.com/replicatedhq/kots) - looking at their Issue tracker, there are a few requests to support Kustomize v2.10, those are from August last year. So I doubt they will upgrade any time soon. 

As for integration into `kubectl`, sigh. I found some docs at https://github.com/kubernetes-sigs/kustomize#kubectl-integration and it doesn't sound too promising on upgrading their kustomize integration either.

**Review by jannfis — APPROVED** [review]
@alexmt do you have any objections to add a third set of installation manifests as in this PR? If not, I'll merge this change. I think it's something many people would want to have working out-of-the-box.

**Comment by jannfis** [comment]
Hi @Leletir, sorry for the delay with this PR. Can you please merge latest upstream master into your branch and update this PR, because we recently merged https://github.com/argoproj/argo-cd/pull/3147 that touched quite a lot of the HA manifests - otherwise merging this change would break, I think (or at least leave us with a broken security enabled HA manifest).

**Comment by Leletir** [comment]
Hello @jannfis, no problem, I'll have a look this weekend.

**Comment by jessesuen** [comment]
Instead of:

```yaml
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999 
```

I think https://github.com/argoproj/argo-cd/pull/3108/files should be merged and the security context should instead be:

```yaml
      securityContext:
        runAsNonRoot: true
```

This has the advantage of not coordinating the userid/groupid to the Dockerfile.

**Review by jessesuen — CHANGES_REQUESTED** [review]
See above comment. I think this is preferred:

```yaml
      securityContext:
        runAsNonRoot: true
```

**Comment by jannfis** [comment]
Agreed, @jessesuen - actually makes sense.

**Comment by Leletir** [comment]
Totally agree on this one

**Comment by jessesuen** [comment]
@Leletir now that https://github.com/argoproj/argo-cd/pull/3108 is merged, did you want to apply the requested changes?

**Comment by sbose78** [comment]
@jannfis @alexmt  This can be closed .

This PR gets superseded by:

https://github.com/argoproj/argo-cd/pull/5786
https://github.com/argoproj/argo-cd/pull/5819
https://github.com/argoproj/argo-cd/pull/5820

**Pull request closed without merging**
