### PR TITLE
feat: add dark theme to UI

### LINKED ISSUE #4722: Add dark mode
# Summary

Add a dark mode to web console. 

# Motivation

Winter is coming up north and my eyes are hurting.

# Proposal

CSS?

### PR DESCRIPTION
**Pull request by saumeya**
closes #4722

Dependent on argo-ui PR - https://github.com/argoproj/argo-ui/pull/245

Demo video 

https://user-images.githubusercontent.com/17771352/174284549-5c828678-05df-4242-99b9-425a36b3783c.mp4

- There are a few components like dropdowns, popups and autocomplete that are still not themed. They render differently and can use a separate PR and theme variable would be needed to passed as a prop.

should close #4722

Initial Description that is no longer valid
Steps to build and run, checkout to `argo-ui` **PR branch** in your local. 
Run `yalc publish`
Then in this argocd branch `cd ui`
Run `yalc add argo-ui`
`cd ..`
`make start`
- Lint is failing because I'm importing a package from argo-ui that is still not merged.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by reginaelyse — APPROVED** [review]
besides the things you mentioned already in your PR description (dropdowns, popups and autocomplete) that can go into another PR, looks awesome!! Thanks for your hard work on this!

**Review by ciiay — CHANGES_REQUESTED** [review]
Hi Saumeya, great work! I played with the dark theme and found a few titles are a little hard to read in dark theme. Other than that all looks great 👍
Screen Shot 2022-06-29 at 5 53 42 PM
Screen Shot 2022-06-29 at 5 54 12 PM
Screen Shot 2022-06-29 at 5 55 24 PM

**Comment by crenshaw-dev** [comment]
@saumeya do you have time to take a look at the CI failures? Looks like probably some relatively simple linting issues.

**Comment by saumeya** [comment]
> @saumeya do you have time to take a look at the CI failures? Looks like probably some relatively simple linting issues.

@crenshaw-dev , The argo-ui PR needs to be merged first. There is a function I am using from that PR, that is why lint is failing.
Once that is merged, I'll update this PR to take argo-ui latest commit sha and then this won't fail.

**Comment by crenshaw-dev** [comment]
@saumeya sweet! I pinged Remington for a review.  :-)

**Comment by rbreeze** [comment]
@saumeya Argo UI PR is approved, can you update this PR with new commit SHA?

**Comment by saumeya** [comment]
Thanks @rbreeze, could you merge that PR?

**Comment by crenshaw-dev** [comment]
@saumeya merged!

**Comment by crenshaw-dev** [comment]
Do we need to bump the moment version in argo-ui to get past the Snyk check?

**Comment by saumeya** [comment]
@crenshaw-dev @rbreeze Updated the PR, now it can be tested directly.

**Comment by saumeya** [comment]
> Do we need to bump the moment version in argo-ui to get past the Snyk check?

I can't see the snyk check, need some permission. But it was something in the rebase. Let me update the dependency

**Comment by crenshaw-dev** [comment]
@saumeya Snyk is passing now, thanks!

**Comment by crenshaw-dev** [comment]
@saumeya just tested locally, and it looks awesome!

Lighthouse is reporting some remaining contrast issues. I think the only ones I'd want to block merging on are these:

image

This is on the Projects page. The top-right header, the logout button, and the tab headings are all very low-contrast and a bit difficult to read.

**Comment by saumeya** [comment]
> 

Thanks @crenshaw-dev, Will fix these issues!

**Comment by saumeya** [comment]
@crenshaw-dev Could you approve and merge this PR - https://github.com/argoproj/argo-ui/pull/272

**Comment by crenshaw-dev** [comment]
https://user-images.githubusercontent.com/350466/190405426-e320b81b-3b50-4bb6-bc45-c35ac62c656c.mov

The contrast looks great now! I really really hate to add one more request, but I think this one is important - the transition between pages flashes white, which is really hard on the eyes. I'm hoping it's a relatively easy fix.

**Comment by crenshaw-dev** [comment]
Testing locally, looks like setting the `body` element's background color to something dark fixes it. I'm not sure if that's the appropriate fix, but it might be an option.

**Comment by crenshaw-dev** [comment]
@saumeya I'm going to go ahead and merge this, and we'll work out the background color and any other issues in follow-up PRs.  :-)

**Review by crenshaw-dev — APPROVED** [review]

**Comment by saumeya** [comment]
Thanks for merging @crenshaw-dev!! We need to imporve as many times possible, i'll look into the transition issue. Also I see your screen height is bigger and so the end of the background is also white. I'll take a look and create fixes.

**Pull request merged**
