### PR TITLE
chore(deps): bump Helm to 3.13.2 (#16320)

### PR DESCRIPTION
**Pull request by m-over**
This PR will bump helm version to 3.13.2 to fix the [https://github.com/argoproj/argo-cd/issues/16320](https://github.com/argoproj/argo-cd/issues/16320)

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.
-->

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
(https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Comment by blakepettersson** [comment]
Should this be cherry picked into 2.9.x?

**Comment by m-over** [comment]
Would be nice, this would solve our problem with the Azure ACR and private helm charts.

**Comment by blakepettersson** [comment]
@m-over can you open a PR with the same changes pointing to the `release-2.9` branch?

**Comment by m-over** [comment]
@blakepettersson I created a new PR #16344

**Pull request merged**
