### PR TITLE
fix(ui): carry over state when using full screen mode button

### LINKED ISSUE #20012: Show pod names state should be applied when logs popped out
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Log options aren't applied to newly popped out full screen logs view.

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?resource=kind%3APod&podSortMode=topLevelResource&node=apps%2FStatefulSet%2Fargocd%2Fargocd-redis-ha-server%2F0&tab=logs
2. Activate `Show pod names` image
    image
3. Activate `Show logs in fullscreen in a new window` image

**Expected behavior**

`Show pod names` should be active in the logs full screen in the new window

**Screenshots**

https://cd.apps.argoproj.io/applications/argocd/argo-cd/argocd/redis/logs?podName=&group=apps&kind=StatefulSet&name=argocd-redis-ha-server
image

**Version**

```shell
{
    "Version": "v2.11.0+1cffa15",
    "BuildDate": "2024-04-18T08:51:13Z",
    "GitCommit": "1cffa15f0ddecbc241d572e316ea20920fdfdb65",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.9",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Logs**

```
```

### PR DESCRIPTION
**Pull request by linghaoSu**
Fixes https://github.com/argoproj/argo-cd/issues/20012

## Now 

https://github.com/user-attachments/assets/729736cf-ce9f-47e2-b3b5-1e316ccd4651

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by nitishfy — APPROVED** [review]
LGTM! Thanks

**Comment by jsoref** [comment]
* Wrap long lines carried over 😄 
* Wrap show pod names carried over 😄 
* Show timestamps didn't carry over 😦 

You're going to want to change the description to:

`fix(ui): carry over state when using full screen mode button` or something like that.

**Review by christianh814 — APPROVED** [review]

**Review by alexmt — APPROVED** [review]
Awesome. I also wanted this behavior

**Review by ishitasequeira — APPROVED** [review]
Lgtm

**Pull request merged**
