### PR TITLE
Remove Node-kind resources from the hard-coded exclusion list

### PR DESCRIPTION
**Pull request by mihail-milev**
This "small" modification aims to allow ArgoCD users to control
their Nodes using ArgoCD. Sometimes this is needed to apply
taints, custom annotations, etc.

Signed-off-by: Mihail Milev <mihailsmilev@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
Hello @mihail-milev ,

The changes should be committed to "master" branch first and then cherry-picked into release branch. The "master" already as required changes and we plan to create a release candidate in couple days. Can you wait until next release?

**Comment by mihail-milev** [comment]
Hello @alexmt ,

I saw that this modification was done on master as part of a bigger modification two months ago and since then several releases were created, but none of them contained the change.

Since I didn't find any documentation why this is the case and I didn't get an answer on the Slack channel, I decided to add this "smaller" change as a separate PR.

It will be perfectly fine to integrate this in a feature 1.9(?) release. I am not yet in a hurry :) In such case, this PR may be declined / closed.

**Comment by sbose78** [comment]
Curious, what was the reason this was in the exclusion list ( beyond the obvious :) )?

**Comment by alexmt** [comment]
I think Node was added to the list because we had an incorrect assumption that no one manages Nodes manually. It is not true apparently :) 

Closing since 2.0 has been released

**Pull request closed without merging**
