### PR TITLE
fix: Use CredsStore for GoogleCloudCreds

### LINKED ISSUE #12390: GoogleCloud Credentials currently not working (uses old git-ask-pass.sh hack)
Checklist:

* [] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [] I've included steps to reproduce the bug.
* [] I've pasted the output of `argocd version`.

**Describe the bug**

Google Cloud source repositores currently cannot be used. The error message indicates, it tries to use the old mechanism of `git-ask-pass.sh`. When merging the rather old Merge Request, this was forgotten to be refactored.

**To Reproduce**

Connect a repo to Google Cloud Source repositories.

**Expected behavior**

Should be able to sync such repos.

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by david-becher**
git-ask-pass.sh is not longer supported for credentials

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #12390

### CODE REVIEW

**Comment by david-becher** [comment]
Hi guys, please accept my bug fix pull request. When merging and rebasing the feature, I think you forgot to use the credsStore mechanism. When I initially wrote my Feature Request, this was not being used.

The feature as is is currently not usable.

@alexef @crenshaw-dev

**Comment by david-becher** [comment]
@erdenayates This is why you might have trouble to connect your repo.

**Comment by david-becher** [comment]
Once again, please review this PR.

The current Google Cloud Support you merged into the current release *does not work*, since it was overlooked to refactor the `argocd-git-ask-pass` binary for credentials.

**Comment by alexef** [comment]
hey @david-becher. sorry for the delay answering here. 

after rebasing your PR I remember testing it end to end, and being able to connect to a google cloud account I've created just for testing the feature.

not sure on the timeline of removing git-ask-pass, and why I was convinced it worked.

however your changes make a lot of sense 🙏 and are in line with other providers

**Review by alexef — APPROVED** [review]

**Comment by ademariag** [comment]
@david-becher can workload identity be used to authenticated with Cloud Source Repositories ?

**Review by crenshaw-dev — APPROVED** [review]
Thanks @david-becher for the fix and @alexef for the review!

**Pull request merged**
