### PR TITLE
docs: refresh before calling sync

### PR DESCRIPTION
**Pull request by roelandvanbatenburg**
Context:

- https://cloud-native.slack.com/archives/C01TSERG0KZ/p1646908096836719
- Before calling sync the repo needs to be refreshed

Checklist:

* [x] Either ~~(a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or~~ (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — CHANGES_REQUESTED** [review]
@roelandvanbatenburg , can you please clarify why is refresh required? Sync does not use cached manifests/revision. A lot of users rely on it and execute `git push && argocd sync <app> ` in pipelines.

**Comment by roelandvanbatenburg** [comment]
> @roelandvanbatenburg , can you please clarify why is refresh required? Sync does not use cached manifests/revision. A lot of users rely on it and execute `git push && argocd sync <app> ` in pipelines.

I based this on what @jannfis said in slack: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1646913138962229?thread_ts=1646908096.836719&cid=C01TSERG0KZ. I have not checked this in the code.

**Comment by crenshaw-dev** [comment]
@jannfis can you weigh in? I think `argocd app get --refresh appname` could help users who want to visually see the changes before syncing (without waiting on automatic refresh). But I don't think it has any affect in an automation script. Am I missing something?

**Comment by crenshaw-dev** [comment]
Closing because I'm not sure the extra command has any effect. If someone comes across a set of steps to reproduce the issue or writes a test, I think we can re-open/re-consider.

**Pull request closed without merging**
