### PR TITLE
feat: Add example to --help output for "argocd appset get"

### PR DESCRIPTION
**Pull request by mcaci**
This is a try to solve one example for Issue #15690

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@mcaci running `make clidocsgen` and committing the change should clear up the failure. :-)

**Comment by mcaci** [comment]
> @mcaci running `make clidocsgen` and committing the change should clear up the failure. :-)

Thanks @crenshaw-dev , I actually had run `make clidocsgen` but didn't see any output and didn't notice that there was an update in the files :smile: 
I pushed the update now

**Review by crenshaw-dev — APPROVED** [review]
Thanks so much, @mcaci!

**Comment by mcaci** [comment]
I'm glad it went well! I'll try another one at this point with some more examples in one PR. Should I tick the box in the checkbox at the beginning of the issue corresponding to the file where I added this example?

**Comment by crenshaw-dev** [comment]
@mcaci yep I think technically I have to tick it due to edit permissions. Thanks for the contribution!!

**Pull request merged**
