### PR TITLE
Make `group` optional for `ignoreDifferences` setting

### LINKED ISSUE #2298: Make `group` optional for `ignoreDifferences` config
**Is your feature request related to a problem? Please describe.**

Got a warning when applying `ignoreDifferences` setting in `Application`

```
spec.ignoreDifferences.group in body is required
```

**Describe the solution you'd like**

Make `group` optional with default value `core`

**Have you thought about contributing yourself?**

Yes

### PR DESCRIPTION
**Pull request by yujunz**
Close: #2298

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM

**Review by alexec — DISMISSED** [review]
Can you sync with master please (which may fix CI issue) and then we should be ready to merge.

**Comment by yujunz** [comment]
Rebased to `origin/master`. But it seems not solving the CI problem. @alexec

**Comment by alexec** [comment]
Ok. The build prints instructions when it fails. Could you try those out please?

**Pull request merged**
