### PR TITLE
feat: add opentracing support

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

This pr adds opentracing support (only jaeger backend for now) for all ArgoCD components. Right now only grpc requests are traced and I will add more spans later if this pr gets accepted.

Opentracing gets archived recently. Ideally, we are going to support opentelemetry directly in ArgoCD https://github.com/argoproj/argo-cd/issues/4972. However, because of the gRPC version used in ArgoCD, we unable to use opentelemetry directly. So an alternative here is to use opentracing SDK for now to bring tracing observability to ArgoCD first and then we can switch to OTEL later if it is possible.

We have already added opentracing support for our internal argocd and it works well. It helps us a lot when debugging performance issue like https://github.com/argoproj/argo-cd/issues/8428. That's why we want to upstream this feature.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by leoluz** [comment]
Tks for working on this @yeya24 !
As I mentioned in the [main issue](https://github.com/argoproj/argo-cd/issues/4972), I think we should work to get https://github.com/argoproj/argo-cd/pull/7539 merged instead of this PR.

**Comment by yeya24** [comment]
Yeah. Seems the community lacks interests of this one so let's get back to the opentelemetry one maybe.

**Comment by leoluz** [comment]
> Seems the community lacks interests of this one

Not sure if its a lack of interest the main issue. 
The facts are:
- [Jaeger go client is deprecated](github.com/uber/jaeger-client-go)
- [Otel more and more becomes the distributed tracing standard](https://www.jaegertracing.io/docs/1.32/client-libraries/#deprecating-jaeger-clients)

**Comment by yeya24** [comment]
> > Seems the community lacks interests of this one
> 
> Not sure if its a lack of interest the main issue. The facts are:
> 
> * [Jaeger go client is deprecated](github.com/uber/jaeger-client-go)
> * [Otel more and more becomes the distributed tracing standard](https://www.jaegertracing.io/docs/1.32/client-libraries/#deprecating-jaeger-clients)

Yeah I mean this pr. Also I know jaeger client is deprecating as mentioned in this pr description. Just nobody is working on fixing the grpc dependency so I opened this pr intending to support this kind of feature first.

**Pull request closed without merging**
