### PR TITLE
ci: Bump to 2.7.7

### PR DESCRIPTION
**Pull request by shivamgupta211-fx**
Bumping to v2.7.7

Cherrypicked https://github.com/argoproj/argo-cd/commit/8f2750c532c0d8842c28cc5babb5c015e91d9cdf

Issue: #14127 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@shivamgupta211-fx I believe this change is also unnecessary. The release workflow will bump the version when we cut a release. Can you describe what you're trying to solve?

**Comment by crenshaw-dev** [comment]
Oh! This is to cherry-pick back the argocd-notifications upgrade? If so, no need for the 2.7.7 bumps, that's done by the github workflow.

I'm not sure we want to upgrade notifications engine within a minor release, since it introduces new features. Is there a bug fix you need picked back?

**Comment by shivamgupta211-fx** [comment]
@crenshaw-dev thanks for responding.
My main goal is to use the notification engine with the latest commit as it contains the changes which are required for our use-case.

Now the problem is, these changes are present in the master but not in the last stable tag/build i.e. v2.7.6

I raised this PR to fix the issue.

Let me know how can I push the latest notification to either v2.7.6 or to the next release v2.7.7?

**Comment by crenshaw-dev** [comment]
@shivamgupta211-fx which features/fixes do you need? We generally don't add new features to minor release series, so if you need a new feature, it might have to wait for 2.8.

**Comment by shivamgupta211-fx** [comment]
@crenshaw-dev 
specifically, pagerDutyv2 feature

https://github.com/argoproj/notifications-engine/pull/105

**Comment by crenshaw-dev** [comment]
Yeah, I think that'll have to wait for 2.8. The RC is out, GA is scheduled for ~1mo from now.

**Comment by shivamgupta211-fx** [comment]
Thanks, @crenshaw-dev 

We will wait for the 2.8.x release then

**Pull request closed without merging**
