### PR TITLE
docs: improve Keycloak documentation for command line sign-in

### PR DESCRIPTION
**Pull request by fungiboletus**
Documenting what is discussed in #2932

Signed-off-by: Antoine Pultier <antoine.pultier@sintef.no>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by fungiboletus** [comment]
DCO check is broken as always, I signed the commit using my public email but commited in Github which use my hidden email.

**Comment by pasha-codefresh** [comment]
@fungiboletus Hi, could you please fix issue with DCO and also change title to semantic?

**Review by zezeS2 — APPROVED** [review]

**Comment by fungiboletus** [comment]
I changed the title but I'm not sure how I can fix the DCO issue without deleting and creating the pull request again. Is this necessary? I signed the commit correctly.

**Comment by blakepettersson** [comment]
> I changed the title but I'm not sure how I can fix the DCO issue without deleting and creating the pull request again.

You can do `git commit --amend -s` and then you can force push the commit to this PR with `git push -f`.

**Comment by fungiboletus** [comment]
> > I changed the title but I'm not sure how I can fix the DCO issue without deleting and creating the pull request again.
> 
> You can do `git commit --amend -s --author="Antoine Pultier <antoine.pultier@sintef.no>"` and then you can force push the commit to this PR with `git push -f`.

Thanks! I didn't know you could force push commits to fix pull requests.

**Review by blakepettersson — APPROVED** [review]
LGTM! 

cc @crenshaw-dev

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.4.

**Pull request merged**
