### PR TITLE
fix(ci): get correct previous release version for release notes (#19443)

### LINKED ISSUE #19443: Release notes for 2.12.0 only showing changes since 2.12.0-rc5, not since 2.11.x
The release notes are generated by goreleaser.

We should see if there's goreleaser config to make sure that GA releases show all changes since the last non-rc release.

### Discussed in https://github.com/argoproj/argo-cd/discussions/19390

<div type='discussions-op-text'>

<sup>Originally posted by **kastl-ars** August  6, 2024</sup>
Would it be possible to have the release notes on big updates (like 2.12.0) show the changes not only since the last RC release on this line? Most people using 2.11.x are more interested in what changed since the current 2.11 release. And having to go through six releases to collect all changes is... tedious.

Example:
https://github.com/argoproj/argo-cd/releases/tag/v2.12.0 only shows the changes since 2.12.0-rc5, not since 2.11.x.

Also, the full changelog is only compared to the last RC:
`Full Changelog: https://github.com/argoproj/argo-cd/compare/v2.12.0-rc5...v2.12.0`

Kind Regards,
Johannes</div>

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes #19443

The script is overcomplicated, but the tests are simple. 

I tested on my fork, and the code ran and got the correct tag for the test tag. I've probably missed edge cases, but at least this gives us something to iterate.

### CODE REVIEW

**Review by leoluz — COMMENTED** [review]
@crenshaw-dev Can you please confirm if the `hack/get-previous-release/get-previous-version-for-release-notes_test.go` gets executed during `make test-local`?

**Comment by crenshaw-dev** [comment]
@leoluz it doesn't. I think I'm okay with that? If anyone is monkeying with that file, I feel like they'll be aware enough to run the tests.

**Review by christianh814 — APPROVED** [review]

**Comment by nitishfy** [comment]
@crenshaw-dev sorry for the Ping. I'm curious to know how do you test the github actions workflow locally? Do you incorporate those changes to origin first and then raise a PR to upstream?

**Comment by crenshaw-dev** [comment]
@nitishfy I don't run them locally, I run them in my fork. I just remove any conditions that limit actions to running on argoproj/argo-cd, and generally that's enough to get it to run. In this case I also commented out a bunch of irrelevant steps so that I only had to run the one I cared about.

It always depends on precisely what you're running. Probably the easiest way to work is to pretend the argoproj/argo-cd repo doesn't exist and just make whatever changes are necessary to get things working on your fork. Then when it's time to put up a PR, just revert those changes one at a time, making sure they all make sense for argoproj/argo-cd.

**Review by leoluz — APPROVED** [review]
Approving for now. Maybe the test could be executed automatically as a small improvement.

**Comment by crenshaw-dev** [comment]
Meh, will wait for 2.14.

**Pull request merged**
