### PR TITLE
chore: bump helm version to 3.8.1

### PR DESCRIPTION
**Pull request by Exodus**
Signed-off-by: Miguel A. Alvarado V <alvaradoma@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
Could you fix the failing test `TestHelmWithMultipleDependencies`?

**Comment by chetan-rns** [comment]
> Error: repository name (https://localhost:9444/argo-e2e/testdata.git/helm-repo/local) contains '/', please specify a different name without '/'\"" execID=8dbc2

@Exodus I think the e2e test is failing because  Helm v3.8.1 doesn't allow repo names with `/` https://github.com/helm/helm/pull/10462. Please see https://github.com/argoproj/argo-cd/issues/8771#issuecomment-1067387382

**Comment by Exodus** [comment]
> > Error: repository name (https://localhost:9444/argo-e2e/testdata.git/helm-repo/local) contains '/', please specify a different name without '/'"" execID=8dbc2
> 
> @Exodus I think the e2e test is failing because Helm v3.8.1 doesn't allow repo names with `/` [helm/helm#10462](https://github.com/helm/helm/pull/10462). Please see [#8771 (comment)](https://github.com/argoproj/argo-cd/issues/8771#issuecomment-1067387382)

Thanks for input, I'll update the test and remove the `/`

**Review by chetan-rns — APPROVED** [review]
LGTM!

**Review by crenshaw-dev — APPROVED** [review]
lgtm!

**Pull request merged**
