### PR TITLE
fix: codeowners syntax error

### PR DESCRIPTION
**Pull request by crenshaw-dev**
oops

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]

**Review by terrytangyuan — COMMENTED** [review]
LGTM but should be a `docs` or `chore`?

**Comment by crenshaw-dev** [comment]
@terrytangyuan the codeowners file is a bit broken right now, so I think this is a legit `fix`.

**Comment by terrytangyuan** [comment]
Usually for Argo Workflows a fix is something we need to cherry-pick into a patch release but Argo CD has automation so it's ok to not differentiate these.

**Review by terrytangyuan — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Ah sure. We might be a bit more ad-hoc in our cherry-picks :-)

**Pull request merged**
