### PR TITLE
fix: Only processes need root uid will run as root inside test container

### LINKED ISSUE #4209: Repo-server fails to start when running locally (make start)
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
Follow the instructions in [Running ArgoCD Locally
](https://github.com/argoproj/argo-cd/blob/master/docs/developer-guide/running-locally.md)  After running "make start", repo-sever aborts due to permission problem to gpg key folder.  Error log messages are observed (see the Logs section).

**To Reproduce**

1. kubectl create namespace argocd
kubectl apply -n argocd --force -f manifests/install.yaml

2. kubectl -n argocd scale deployment/argocd-application-controller --replicas 0
kubectl -n argocd scale deployment/argocd-dex-server --replicas 0
kubectl -n argocd scale deployment/argocd-repo-server --replicas 0
kubectl -n argocd scale deployment/argocd-server --replicas 0
kubectl -n argocd scale deployment/argocd-redis --replicas 0

3. make start 

4.  Observe log messages about repo-server is terminating.

**Expected behavior**

repo-server should be able to start successfully with the following log messages.

```
00:06:01 repo-server | INFO[0000] Loaded 0 (and removed 0) keys from keyring   
00:06:01 repo-server | INFO[0000] argocd-repo-server v99.99.99+unknown serving on [::]:8081 
00:06:01 repo-server | INFO[0000] Starting GPG sync watcher on directory '/tmp/argocd-local/gpg/source'
``` 

**Screenshots**
If proceed to create an application, connection refused to 127.0.0.1:8081 repo-server is result
connection-refused

**Version**

```shell
unreleased, master  branch
```

**Logs**

```
23:25:45 repo-server | INFO[0000] Initializing GnuPG keyring at /tmp/argocd-local/gpg/keys 
23:25:45 repo-server | FATA[0000] stat /tmp/argocd-local/gpg/keys/trustdb.gpg: permission denied 
23:25:45 repo-server | exit status 20
23:25:45 repo-server | Terminating repo-server
```

### PR DESCRIPTION
**Pull request by wtam2018**
The following fix is implemented in this PR.
Test container are built and added an unprivileged test user which has the host user's UID.  The container image also includes passwordless sudo configuration for the test user.   Test containers are run as the same UID as the unprivileged test user so the test user can be elevated without password.   "goreman start"  does "sudo" only tto the processes that need root permission including sshd, fcgiwrap, and nginix according to  Procfile.  

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [X] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

fixes: #4209

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
I think this is the wrong place for the fix.

If `${USER_ID}` is set, it means we're running within Docker as a certain user ID (i.e. `1000`). Now if `/tmp/argocd-local/gpg/keys` belongs to a different user (say, user ID `0`), the `chown` call will ultimately fail. But also, the `rm -rf ...` in line 403 would have failed already, because permissions would not allow to remove the directory first.

I can just think that the permissions problems appear when trying to run Argo CD locally with different users and possibly as user root -- which should be avoided at all costs.

**Comment by wtam2018** [comment]
> I think this is the wrong place for the fix.
> 
> If `${USER_ID}` is set, it means we're running within Docker as a certain user ID (i.e. `1000`). Now if `/tmp/argocd-local/gpg/keys` belongs to a different user (say, user ID `0`), the `chown` call will ultimately fail. But also, the `rm -rf ...` in line 403 would have failed already, because permissions would not allow to remove the directory first.
> 
> I can just think that the permissions problems appear when trying to run Argo CD locally with different users and possibly as user root -- which should be avoided at all costs
* FWIW, https://github.com/wtam2018/argo-cd/blob/master/Makefile#L370-L371 `start-e2e-local` performs `chown` in the same fashion.   `start-local` is kind of similar except it's purpose is to start things up for local development.  
* If `chown` is not performed, the gpg keys folder is owned by root.   Do you suggest to required running as root user?

**Comment by jannfis** [comment]
>     * FWIW, https://github.com/wtam2018/argo-cd/blob/master/Makefile#L370-L371 `start-e2e-local` performs `chown` in the same fashion.   `start-local` is kind of similar except it's purpose is to start things up for local development.

Oops, and that is even to blame on me :nerd_face: But honestly, the `chown` can only succeed if either the target already is owned by the current user, or the user executing the `chown` is root.

>     * If `chown` is not performed, the gpg keys folder is owned by root.   Do you suggest to required running as root user?

No, I'm suggesting the opposite. I still wonder how/why the files would be owned by root, when they are created by the local user.

**Comment by wtam2018** [comment]
@jannfis It looks like `run-in-test-server` is missing -u uid:gid option to docker run command so the docker container is running as uid 0.   That explains why the files under /tmp/argocd-local is owned by root.  The processes in test Procfile won't need to perform "su" once docker container is run as the current user instead of root.   Please take a look at my revised PR.  Thanks.

**Comment by manuNCL** [comment]
@jannfis @wtam2018, what about something like this:

`sudo -u $USER mkdir -p /tmp/argocd-local`
`sudo -u $USER mkdir -p /tmp/argocd-local/gpg/keys &&
sudo -u $USER chmod 0700 /tmp/argocd-local/gpg/keys`

Using `sudo -u $USER` should create the new dir smoothly and without asking to authenticate the change of user as $USER should be the one who executed the script.
TBH, I (and google) could not explain why argocd-local gets created by root. If you find out the reason, please, let me know.

**Comment by manuNCL** [comment]
@jannfis @wtam2018, probably this workaround is pointless after wtam2018's revised PR, but I thought to post it anyway.
What about something like this:

`sudo -u $USER mkdir -p /tmp/argocd-local`
`sudo -u $USER mkdir -p /tmp/argocd-local/gpg/keys &&
sudo -u $USER chmod 0700 /tmp/argocd-local/gpg/keys`

Using `sudo -u $USER` should create the new dir smoothly and without asking to authenticate the change of user as $USER should be the one who executed the script.

**Comment by jannfis** [comment]
@wtam2018 Sorry for the late reply. Without being UID 0, neither fcgiwrap nor sshd (required for running end-to-end tests) seem to be able to start within the container, thus the end-to-end tests will not run either.

I like the idea to start up the container unprivileged, like in the current iteration of your PR. To make it work, maybe we should follow a slightly changed approach of @manuNCL and configure passwordless sudo within the container, and then use `sudo -u root` to start-up `fcgiwrapper` and `sshd` from the Goreman's `Procfile`. 

What do you think of that?

**Comment by wtam2018** [comment]
@jannfis In this iteration, passwordless sudo is configured and sudo will be performed only to processes that need root access.   I updated description in the PR to describe this fix.    Thanks.

**Comment by jannfis** [comment]
I'd suggest to incorporate the change to `/etc/sudoers` in the [Dockerfile](https://github.com/argoproj/argo-cd/blob/master/test/container/Dockerfile) instead of the entrypoint script and keep starting the container unprivileged (i.e. `-u $(uid -u)`).

**Comment by wtam2018** [comment]
> I'd suggest to incorporate the change to `/etc/sudoers` in the [Dockerfile](https://github.com/argoproj/argo-cd/blob/master/test/container/Dockerfile) instead of the entrypoint script and keep starting the container unprivileged (i.e. `-u $(uid -u)`).

The problem is that uid_entrypoint.sh requires root to perform `useradd`.

**Comment by wtam2018** [comment]
We could incorporate the useradd operation in the Dockerfile as well.

**Comment by wtam2018** [comment]
@jannfis Setting up of passwordless sudo is moved to Dockerfile.   Test containers are run as unprivileged user (host user).   Thanks.

**Comment by wtam2018** [comment]
@jannfis I just thought I would ping to see if you had any further feedbacks.   Thanks.

**Review by jannfis — APPROVED** [review]
Awesome! I have tested both, `make start` and `make start-e2e` and they seem to work fine.

Thanks for your patience, and sorry for the lag w/ review and discussions - unfortunately, I currently have not much time for open source projects next to my day job.

**Pull request merged**
