### PR TITLE
fix!: added security contexts in manifests to secure argocd component

### LINKED ISSUE #9028: applicationset security context not set
These issues should be fixed:

```
manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml: (object: <no namespace>/argocd-applicationset-controller apps/v1, Kind=Deployment) container "argocd-applicationset-controller" does not have a read-only root file system (check: no-read-only-root-fs, remediation: Set readOnlyRootFilesystem to true in the container securityContext.)

manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml: (object: <no namespace>/argocd-applicationset-controller apps/v1, Kind=Deployment) container "argocd-applicationset-controller" is not set to runAsNonRoot (check: run-as-non-root, remediation: Set runAsUser to a non-zero number and runAsNonRoot to true in your pod or container securityContext. Refer to https://kubernetes.io/docs/tasks/configure-pod-container/security-context/ for details.)
```

### PR DESCRIPTION
**Pull request by rishabh625**
Fixes https://github.com/argoproj/argo-cd/issues/9028

Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by rishabh625** [comment]
@crenshaw-dev @alexec : please review

**Comment by alexec** [comment]
Can you run `snyk iac` on the new manifests to see what it reports?

**Comment by rishabh625** [comment]
shows 6 issues in role rest all r fixed
```
snyk iac test manifests/install.yaml  --severity-threshold=medium --policy-path=.snyk      

Testing manifests/install.yaml...

Infrastructure as code issues:
  ✗ Role with dangerous permissions [Medium Severity] [SNYK-CC-K8S-47] in Role
    introduced by [DocId: 9] > role > rules[0] > resources

  ✗ Role with dangerous permissions [Medium Severity] [SNYK-CC-K8S-47] in Role
    introduced by [DocId: 10] > role > rules[3] > resources

  ✗ Role with dangerous permissions [Medium Severity] [SNYK-CC-K8S-47] in Role
    introduced by [DocId: 11] > role > rules[0] > resources

  ✗ Role with dangerous permissions [Medium Severity] [SNYK-CC-K8S-47] in Role
    introduced by [DocId: 12] > role > rules[1] > resources

  ✗ Role with dangerous permissions [Medium Severity] [SNYK-CC-K8S-47] in Role
    introduced by [DocId: 12] > role > rules[3] > resources

  ✗ Role with dangerous permissions [Medium Severity] [SNYK-CC-K8S-47] in Role
    introduced by [DocId: 13] > role > rules[0] > resources


Organization:      rishabh625
Type:              Kubernetes
Target file:       manifests/install.yaml
Project name:      manifests
Open source:       no
Project path:      manifests/install.yaml

Tested manifests/install.yaml for known issues, found 6 issues

```

**Comment by rishabh625** [comment]
Few with low severity i think can be ignored
```
✗ Container is running without liveness probe [Low Severity] [SNYK-CC-K8S-41] in Deployment
    introduced by [DocId: 41] > spec > template > spec > containers[argocd-applicationset-controller] > livenessProbe

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 41] > input > spec > template > spec > containers[argocd-applicationset-controller] > resources > limits > memory

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 41] > input > spec > template > spec > containers[argocd-applicationset-controller] > resources > limits > cpu

  ✗ Container is running with multiple open ports [Low Severity] [SNYK-CC-K8S-36] in Deployment
    introduced by [DocId: 42] > spec > template > spec > containers[dex] > ports

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 42] > input > spec > template > spec > containers[dex] > resources > limits > memory

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 42] > input > spec > template > spec > initContainers[copyutil] > resources > limits > cpu

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 42] > input > spec > template > spec > initContainers[copyutil] > resources > limits > memory

  ✗ Container is running without liveness probe [Low Severity] [SNYK-CC-K8S-41] in Deployment
    introduced by [DocId: 42] > spec > template > spec > containers[dex] > livenessProbe

  ✗ Container is running without liveness probe [Low Severity] [SNYK-CC-K8S-41] in Deployment
    introduced by [DocId: 42] > spec > template > spec > initContainers[copyutil] > livenessProbe

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 42] > input > spec > template > spec > containers[dex] > resources > limits > cpu

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 43] > input > spec > template > spec > containers[argocd-notifications-controller] > resources > limits > memory

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 43] > input > spec > template > spec > containers[argocd-notifications-controller] > resources > limits > cpu

  ✗ Container is running without liveness probe [Low Severity] [SNYK-CC-K8S-41] in Deployment
    introduced by [DocId: 44] > spec > template > spec > containers[redis] > livenessProbe

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 44] > input > spec > template > spec > containers[redis] > resources > limits > cpu

  ✗ Container is running with writable root filesystem [Low Severity] [SNYK-CC-K8S-8] in Deployment
    introduced by [DocId: 44] > input > spec > template > spec > containers[redis] > securityContext > readOnlyRootFilesystem

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 44] > input > spec > template > spec > containers[redis] > resources > limits > memory

  ✗ Container could be running with outdated image [Low Severity] [SNYK-CC-K8S-42] in Deployment
    introduced by [DocId: 45] > spec > template > spec > initContainers[copyutil] > imagePullPolicy

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 45] > input > spec > template > spec > initContainers[copyutil] > resources > limits > cpu

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 45] > input > spec > template > spec > initContainers[copyutil] > resources > limits > memory

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 45] > input > spec > template > spec > containers[argocd-repo-server] > resources > limits > cpu

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 45] > input > spec > template > spec > containers[argocd-repo-server] > resources > limits > memory

  ✗ Container is running without liveness probe [Low Severity] [SNYK-CC-K8S-41] in Deployment
    introduced by [DocId: 45] > spec > template > spec > initContainers[copyutil] > livenessProbe

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 46] > input > spec > template > spec > containers[argocd-server] > resources > limits > memory

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 46] > input > spec > template > spec > containers[argocd-server] > resources > limits > cpu

  ✗ Container is running without memory limit [Low Severity] [SNYK-CC-K8S-4] in Deployment
    introduced by [DocId: 47] > input > spec > template > spec > containers[argocd-application-controller] > resources > limits > memory

  ✗ Container is running without cpu limit [Low Severity] [SNYK-CC-K8S-5] in Deployment
    introduced by [DocId: 47] > input > spec > template > spec > containers[argocd-application-controller] > resources > limits > cpu


```

**Comment by alexec** [comment]
I think that you should probably have a liveness probe, if the controller has a concep of liveness. I think maybe open another issue.

IMHO, we should not provide manifents without resources set. However, determining the correct resource requests is easy, just run it and see what it uses under small load. For limit, run under high load. Again, I think a new issue and PR for that work.

**Comment by alexec** [comment]
LGTM.

**Comment by crenshaw-dev** [comment]
I'm going to read up a bit on the change's implications before merging, but at a glance this looks awesome.

I'd like to modify our Snyk scan to fail on medium-severity issues too, and make sure that our .snyk documents if/why we're ignoring what's there.

But that's a job for another PR. Thanks so much for working on this!

**Comment by rishabh625** [comment]
> I'm going to read up a bit on the change's implications before merging, but at a glance this looks awesome.
> 
> I'd like to modify our Snyk scan to fail on medium-severity issues too, and make sure that our .snyk documents if/why we're ignoring what's there.
> 
> But that's a job for another PR. Thanks so much for working on this!

If u set to fail for medium issues that means we need to address role with dangerous permission issue too

**Comment by rishabh625** [comment]
for implications: it doesn't affect any feature of argocd , but i read below blogs to get understanding, may be helpful

https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
https://linux-audit.com/linux-capabilities-hardening-linux-binaries-by-removing-setuid/
https://kubesec.io/basics/containers-securitycontext-capabilities-drop-index-all/

**Comment by rishabh625** [comment]
> I think that you should probably have a liveness probe, if the controller has a concep of liveness. I think maybe open another issue.
> 
> IMHO, we should not provide manifents without resources set. However, determining the correct resource requests is easy, just run it and see what it uses under small load. For limit, run under high load. Again, I think a new issue and PR for that work.

I created an issue for resources limit set. https://github.com/argoproj/argo-cd/issues/9099

**Comment by crenshaw-dev** [comment]
Noting that this is potentially-breaking, because argocd-cm CMPs might rely on capabilities that are now blocked.

We'll want to note in the upgrade guide that CMP authors should test their CMP in 2.4 before upgrading prod.

**Review by crenshaw-dev — APPROVED** [review]
Ran on docker-desktop for a while, and it's looking good. Thanks again!

**Pull request merged**
