### PR TITLE
fix: env vars with "=" in their values ignored for sidecar CMPs #8792

### LINKED ISSUE #8792: Environment variables with "=" in their values ignored for sidecar CMPs
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Environment variables with "=" in their values passed to sidecar Config Management Plugins via Application CR are ignored and are not available in the CMP environment.

**To Reproduce**

Config Management Plugin running as a sidecar not receiving `$IGNORED` env var, only `$PASSED` env var, for ArgoCD Application like this:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
spec:
  destination:
    namespace: werf-pull-ci-cd-demo-production
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: werf-pull-ci-cd-demo
    plugin:
      env:
      - name: PASSED
        value: val1
      - name: IGNORED
        value: key1=val1
    repoURL: registry.flant.com/werf
    targetRevision: 0.1.148272
```

**Expected behavior**

`$IGNORED` env var passed to the Config Management Plugin environment too, not only `$PASSED`.

**Version**

```shell
argocd: v2.2.4+78d749e
  BuildDate: 2022-02-03T20:41:00Z
  GitCommit: 78d749ec88bea5a5e851fc48b9404fdf067192b6
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.4.0+969c7a1
  BuildDate: 2022-03-16T05:09:55Z
  GitCommit: 969c7a173519618cffbee9aa0b7d0e56e178fcda
  GitTreeState: clean
  GoVersion: go1.17.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

### PR DESCRIPTION
**Pull request by ilya-lesikov**
Fixes #8792

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] ~~Does this PR require documentation updates?~~
* [x] ~~I've updated documentation as required by this PR.~~
* [x] ~~Optional. My organization is added to USERS.md.~~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@ilya-lesikov that PR didn't fix it, just moved the function from one place to another. Want to go ahead and mark this as ready for review? I'll request Leo's review since he did that refactor and might have some additional context.

**Comment by ilya-lesikov** [comment]
@crenshaw-dev Hi, marked as ready.

**Comment by crenshaw-dev** [comment]
@ilya-lesikov sorry to keep bothering for a simple change, but could you merge master?

If you prefer, I can open a new PR w/ the same changes and handle the nitpicky stuff. Either way works for me. :-)

**Review by crenshaw-dev — APPROVED** [review]
LGTM, thanks again! Requesting Leo's review since he recently did some refactoring near this code.

**Review by leoluz — APPROVED** [review]
LGTM

**Pull request merged**
