### PR TITLE
chore: no colons in filenames

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Looks like the colon characters make it impossible to clone the repo (at least for some folks). https://github.com/argoproj/argo-cd/pull/9856#issuecomment-1203251738

### CODE REVIEW

**Comment by jetersen** [comment]
> (at least for some folks)

This includes all windows users 😅

**Review by jetersen — APPROVED** [review]

**Comment by jetersen** [comment]
Tested using `git clone https://github.com/crenshaw-dev/argo-cd.git --branch no-colons-in-filenames --single-branch argocd-no-colons` :)

**Comment by crenshaw-dev** [comment]
Thanks for testing @jetersen!

**Review by notfromstatefarm — APPROVED** [review]
LGTM :shipit:

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
