### PR TITLE
Make build options in Makefile settable from environment

### PR DESCRIPTION
**Pull request by jannfis**
This change enables setting the Makefile's build options from the shell's environment, so that contribution instructions such as "DOCKER_PUSH=true make image" actually work.

### CODE REVIEW

**Comment by alexec** [comment]
Please see why CI is failing.

**Comment by jannfis** [comment]
First I thought it might be because my local branch lagged behind master a few commits. But then I noticed the e2e-test actually fails with a segfault:
```
--- FAIL: TestResourceAction (6.54s)                                                                                                                                                                                                                  
   app_management_test.go:402:                                                                                                                                                                                                                        
        Error Trace:    app_management_test.go:402                                                                                                                                                                                                    
                                                consequences.go:40                                                                                                                                                                                    
                                                app_management_test.go:388                                                                                                                                                                            
        Error:          Received unexpected error:                                                                                                                                                                                                    
                        rpc error: code = NotFound desc = deployments.apps "guestbook-ui" not found                                                                                                                                                   
        Test:           TestResourceAction        

panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                                                                                                   
        panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                                       
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x147d887]                                                                                                                                                                               
```
I am wild guessing, but the e2e-test is being built using DEV_IMAGE=true as argument to make - probably, that didn't work before and now eventually builds the development image, and that might be broken. I have not setup e2e testing at my workstation, but will do so for more investigation and see if I can spot the error.

I'm quite new to argo-cd and just digging my way in, so bear with me please.

**Comment by jessesuen** [comment]
It may be environmental flakiness. Let me try retrying the CI

**Comment by jannfis** [comment]
Running a stock E2E test on my local machine passes:

```
PASS
ok      github.com/argoproj/argo-cd/test/e2e    153.402s

```

**Comment by alexec** [comment]
I think Argo CI is bust.

**Review by jessesuen — APPROVED** [review]

**Comment by jessesuen** [comment]
Agreed. Merging in anyways

**Pull request merged**
