### PR TITLE
feat: add custom resource health checks for trident.netapp.io/TridentOrchestrator and trident.netapp.io/TridentBackendConfig (Closes [ISSUE #6550])

### PR DESCRIPTION
**Pull request by Cajga**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by Cajga** [comment]
@jannfis, may I ask for a review/feedback please?

**Comment by Cajga** [comment]
Hmm... Let's hold this a bit, I will try to get feedback from NetAPP on trident.netapp.io/TridentBackendConfig. Based on the [documentation](https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/managing-backends/tbc.html#step-3-verify-the-status-of-the-tridentbackendconfig-cr) using lastOperationStatus may not be the right approach.

The check for trident.netapp.io/TridentOrchestrator is complete and is correct based on the relevant [documentation](https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/deploying/operator-deploy.html#observing-the-status-of-the-operator).

**Comment by Cajga** [comment]
@jannfis, netapp confirmed the approach on the health monitors (see linked ticket). May I ask you for a feedback on this and let me know if there anything else is missing to get this merged?

Thanks

**Review by alexmt — APPROVED** [review]
Thank you for implementing the health checks and tests! LGTM

**Pull request merged**
