### PR TITLE
Increase test applicationset scm

### PR DESCRIPTION
**Pull request by rishabh625**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* 

link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by rishabh625** [comment]
[This](https://github.com/argoproj/argo-cd/pull/9140) didn't increase the code coverage in [applicationset/services/scm_provider/github.go](https://codecov.io/gh/argoproj/argo-cd/pull/9140/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=argoproj#diff-YXBwbGljYXRpb25zZXQvc2VydmljZXMvc2NtX3Byb3ZpZGVyL2dpdGh1Yi5nbw==)

Targetting code coverage to increase from -17%

**Comment by rishabh625** [comment]
Will make it ready for review once have codecov report

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@rishabh625 I just realized that code coverage probably fluctuates on whether GitHub rate limits are being hit.  :-/

**Comment by rishabh625** [comment]
> @rishabh625 I just realized that code coverage probably fluctuates on whether GitHub rate limits are being hit. :-/

Yes , unfortunate there may be some work around, also integration tests on merge are failing since 1800sec is not enough for all controller to start

**Pull request merged**
