### PR TITLE
fix: supporting OCI dependencies. Fixes #6062

### LINKED ISSUE #6062: OCI chart as dependency
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Just upgraded out argocd from 1.8.x to v2.0.1+33eaf11 so we are trying to use OCI hosted helm charts.
The OCI helm itself works like a charm (as oposed to the 1.8.x version).
However when we have a helm chart in a git repository that has this OCI helm as a dependency it fails. More details below. 

**To Reproduce**
Our application Chart.yaml in the git repository looks like:

```
apiVersion: v2
name: sample-app
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
  - name: chart-name
    repository: "oci://registry.gitlab.com"
    version: 0.2.0
```
This repo happens to be previously added to argocd using the cli:

```shell
argocd repo add registry.gitlab.com --type helm --name repo-name --enable-oci --username [user] --password [password]`
```
There is also a values.yaml with the non-default values I wanna override from the inherited chart.

**Expected behavior**
The git repository should allow an application to be created with this OCI chart dependency.

What we get instead is that this chart (the OCI dependency) could not be found in the charts directory (see the logs)

**Version**

```shell
 v2.0.1+33eaf11
```

**Logs**

Unable to create application: application spec is invalid: InvalidSpecError: Unable to generate manifests in prometheus-contract-first-sample/dev: rpc error: code = Unknown desc = `helm template . --name-template sample-app --namespace apps --values values.yaml --api-versions v1 --api-versions apiregistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions events.k8s.io/v1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api-versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-versions batch/v1beta1 --api-versions certificates.k8s.io/v1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions networking.k8s.io/v1beta1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 --api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1 --api-versions admissionregistration.k8s.io/v1beta1 --api-versions apiextensions.k8s.io/v1 --api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1 --api-versions coordination.k8s.io/v1beta1 --api-versions node.k8s.io/v1beta1 --api-versions discovery.k8s.io/v1beta1 --api-versions crd.k8s.amazonaws.com/v1alpha1 --api-versions vpcresources.k8s.aws/v1beta1 --api-versions metrics.k8s.io/v1beta1 --include-crds` failed exit status **1: Error: found in Chart.yaml, but missing in charts/ directory: chart-name**

### PR DESCRIPTION
**Pull request by m-yosefpor**
fixes: https://github.com/argoproj/argo-cd/issues/6062

see https://github.com/argoproj/argo-cd/issues/6062#issuecomment-898968723 for more details.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them. (**no need**)
* [x] Does this PR require documentation updates? **No**
* [x] I've updated documentation as required by this PR. **no need**
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged. **The e2e tests are already there https://github.com/argoproj/argo-cd/blob/master/test/e2e/testdata/helm-oci-with-dependencies/Chart.yaml**
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by m-yosefpor** [comment]
cc @alexmt

**Comment by chetan-rns** [comment]
@m-yosefpor Thanks for the PR. Could you please resolve the conflict?

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @m-yosefpor . I've noticed `TestRepoPermission` failed. 

Can you please check if we actually broke some existing feature it may be test should be updated?

**Comment by rgeraskin** [comment]
Thank you @m-yosefpor! Looks like the `helm repo add` error is gone. But now I can't pull the chart from my private registry.

Seems like it can't get the creds so the login process is not even started. I tried to specify creds with secret labeled by `argocd.argoproj.io/secret-type: repository`. Also tried legacy method by editing `argocd-cm`

**Comment by rgeraskin** [comment]
I think I found the solution for private registry issues. See #7144 and #7162 for details. Updated argocd manifests to the latest version and seems like all ok.

Btw may be merging master will fix e2e tests also

**Comment by m-yosefpor** [comment]
Sorry I didn't have time to dig into why tests are failing. It seems there is a testcase which should be failed, but now is passing due to this fix. The testcase says when a repository is only allowed to use git, it should fail when have an OCI dependency, but now it is passing as OCI dependency issue is fixed. I don't know how my change can affect that permission check. I wonder if it is sth wrong with the test, and the test was failing previously as OCI dependency did not work at all, or is there a permission issue which should I fix. Moreover, there is another testcase which tests apps with OCI dependency and the previous versions where passing that test!!!! (but clearly it shouldn't, both due to logic, and manual testing in argocd). I think sth needs to be fixed in tests, but as I said, I couldn't spend enough time to dig into this.

I'll try merging master, but I'm afraid it might not help.

**Comment by rgeraskin** [comment]
I fixed my private registry issues. It's a stupid mistake: I forgot to add a subchart repo to permitted sourceRepos in the Application Project. Now it works like a charm, thank you very much!

I built the image from your fork and pushed it to `rgeraskin/argocd:latest` so anyone who is too lazy to do `make image` but who is brave enough to use third-party images could use it =)

Btw I think an error message should be more concrete. This error does not look like *'you forgot to add a subchart repo to permitted sourceRepos'* at all
```
rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not download oci://registry.gitlab.com/asdasd/charts//subchart: failed to authorize: failed to fetch anonymous token: unexpected status: 403 Forbidden
```

Maybe it should look like an error when you didn't add the parent chart to permitted ones? Like this error:
```
application repo git@gitlab.com:asdasd/parent.git is not permitted in project 'apps'
```

**Comment by AustinSmart** [comment]
This is still an issue in v2.1.3. 

@alexmt can workflows be approved to run to see if the `TestRepoPermission` test is still failing?

**Comment by alexmt** [comment]
@m-yosefpor , sorry - it took forever to review. We are still overloaded but it is getting better recently.

I finally understood why `TestRepoPermission` is failing. It appears that the test is invalid. It assumes that manifest generation should fail because repo server don't have credentials to OCI registry. However test OCI registry does not require authentication at all. The manifest generation was failing due to the bug you've fixed in the PR. We just don't have e2e test infra to test the use case of `TestRepoPermission`. 

Can you please merge master into your branch and just remove `TestRepoPermission`. I will merge and cherry-pick PR into v2.1

**Review by alexmt — APPROVED** [review]
Thank you! 

LGTM

**Pull request merged**
