### PR TITLE
feat: adding gocover to e2e tests (tweaks) (#18130)

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Tinkering with Ryan's work.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@rumstead so I split the codecov directories out by component, which seems to keep them from stepping on each other.

I consistently get coverage output from the appset controller, but nothing else.

With the graceful shutdown changes I've added to this PR, we seem to get consistent coverage from api-server too.

I imagine the other components need further graceful shutdown work to consistently produce coverage.

But the overall coverage seems more in line with what I'd expect to see (+50%).

**Comment by rumstead** [comment]
> @rumstead so I split the codecov directories out by component, which seems to keep them from stepping on each other.
> 
> I consistently get coverage output from the appset controller, but nothing else.
> 
> With the graceful shutdown changes I've added to this PR, we seem to get consistent coverage from api-server too.
> 
> I imagine the other components need further graceful shutdown work to consistently produce coverage.
> 
> But the overall coverage seems more in line with what I'd expect to see (+5%).

 Nice! I had a feeling something was getting sig killed or buffers not flushing. Great to see this adding some coverage.

**Comment by crenshaw-dev** [comment]
@rumstead I'll open a PR against yours, then we can go from there!

**Comment by crenshaw-dev** [comment]
Closing in favor of Ryan's PR

**Pull request closed without merging**
