### PR TITLE
Read Casbin configuration at run time #3717

### PR DESCRIPTION
**Pull request by ragarcia26**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by ragarcia26** [comment]
I'm not sure what additional changes need to be made for cli to be on par. The second half of this change would go into the helm chart for actual configuration

**Comment by ragarcia26** [comment]
https://github.com/argoproj/argo-helm/pull/388 for corresponding helm configuration

**Review by jannfis — CHANGES_REQUESTED** [review]
Hi @ragarcia26, thanks a lot for your PR!

While I think that the original enhancement request - allow wildcard/regexp matches for RBAC subjects - is valuable and something we should implement, I also think that we should take care with the Casbin configuration. I'm not sure whether we should allow users to supply their own configuration, because that will be something people can easily get wrong, possibly open up a whole lot of new issues (security issues included).

From reading the [Casbin docs](https://casbin.org/docs/en/function), it's possible to implement a unique matcher function. So maybe it would be better to write such a function which decides at runtime (from a toggle or an environment variable) what kind of match to perform, and use this function in our `model.conf` instead. This would leave us with a single Casbin configuration, no need for mounting another ConfigMap with possible dangerous configuration and a simple way for the user to chose what kind of matching they need.

However, there might be valid reasons for custom Casbin configurations which I don't see yet. I'm open for suggestions and discussions.

**Comment by arroo** [comment]
> However, there might be valid reasons for custom Casbin configurations which I don't see yet.

My use case is ABAC, which I'm struggling to find support for in ArgoCD. Specifically, we're using an SSO for authentication where managing groups is tedious but managing attributes is trivial for us. Afaict, ArgoCD doesn't support using anything from the OIDC access token except the `groups` claim and it'd be nice to use other claims to do authorization.

**Comment by DirtyCajunRice** [comment]
@jannfis  This has been the only PR for referencing new matching models for rbac. Would you consider this DOA? We are in dire need of Regex matching and I can start a PR if this is not going anwhere.

**Pull request closed without merging**
