### PR TITLE
#7144 fix: add custom volume as Helm working dir

### PR DESCRIPTION
**Pull request by irizzant**
Closes [#7144]
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by rwong2888** [comment]
@irizzant I think it would make sense to include `HELM_PLUGIN_DIR` to the env

**Review by alexmt — CHANGES_REQUESTED** [review]
Thanks a lot @irizzant ! Can you please add `HELM_PLUGINS` as suggested in https://github.com/argoproj/argo-cd/issues/7144#issuecomment-914408663 ?

Run `make manifests` to update autogenerated install.yaml files.

**Comment by irizzant** [comment]
@alexmt see https://github.com/argoproj/argo-cd/issues/7144#issuecomment-915083190

**Review by alexmt — APPROVED** [review]
LGTM. thank you for research and the fix

**Pull request merged**
