### PR TITLE
fix: update resolveRevision to use the correct source for multi-source app

### LINKED ISSUE #18120: Sync from UI for Multi source application stopped working on v2.11.0
**Describe the bug**
Since the update to ArgoCD v.2.11.0 my multisource application is not syncing anymore. Reverting back to 2.10.9 makes it work again. The error message is:
```
Unable to sync: error resolving repo revision: rpc error: code = Unknown desc = repository not found
```
Single source application using the public repo works and single source application to the private git repo also still works. The issue only occurs for multisource applications combining the 2.

**To Reproduce**
Create an application that uses a public helm chart and retrieves values files from a private github repository:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: argo-cd
    helm:
      passCredentials: true
      valueFiles:
      - $values/values.yaml
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 6.8.0
  - ref: values
    repoURL: https://github.com/org/some-private-repo
    targetRevision: develop
  syncPolicy:
    automated: {}
```

**Expected behavior**
I would expect the application to be able to sync

**Screenshots**

**Version**

```shell
argocd: v2.11.0+d3f33c0
  BuildDate: 2024-05-07T16:01:41Z
  GitCommit: d3f33c00197e7f1d16f2a73ce1aeced464b07175
  GitTreeState: clean
  GoVersion: go1.21.9
  Compiler: gc
  Platform: linux/amd64
```

**Logs**
```
time="2024-05-08T08:16:41Z" level=warning msg="finished unary call with code FailedPrecondition" error="rpc error: code = FailedPrecondition desc = error resolving repo revision: rpc error: code = Unknown desc = repository not found" │
│  grpc.code=FailedPrecondition grpc.method=Sync grpc.service=application.ApplicationService grpc.start_time="2024-05-08T08:16:41Z" grpc.time_ms=214.932 span.kind=server system=grpc                                                       │
│                                                                                                                                                     
```

### PR DESCRIPTION
**Pull request by ishitasequeira**
Fixes https://github.com/argoproj/argo-cd/issues/18120

cherry-pick release-2.11

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by agaudreault — APPROVED** [review]
LGTM

**Review by todaywasawesome — APPROVED** [review]
Looks good. 

I'm a little unclear why the regression is in 2.11 and not earlier versions though we didn't previously try to handle sourceIndex on the sources. Should we cherry-pick this back to 2.10 and 2.9?

**Comment by ishitasequeira** [comment]
Hey @todaywasawesome, the change for supporting sync for multi-source apps went in 2.11 release. We have been defaulting to the 1st source details alone for earlier versions. 

Reference PR: #17808

**Review by pasha-codefresh — APPROVED** [review]

**Comment by wanddynosios** [comment]
Can confirm that this fixed the issue for me👍

**Pull request merged**
