### PR TITLE
fix(appset): don't emit k8s events for unchanged apps, log at debug (#15659)

### PR DESCRIPTION
**Pull request by ericblackburn**
…nd move that scenario to debug logging level

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Fixes issue https://github.com/argoproj/argo-cd/issues/15659

### CODE REVIEW

**Review by gdsoumya — APPROVED** [review]
LGTM

**Review by alexmt — APPROVED** [review]
Thank you!

**Comment by ericblackburn** [comment]
I won't be able to get the e2e test for v.1.24.3 working since they seem to have a bug in TestDisableManifestGeneration.

This is unrelated to my change

**Comment by ericblackburn** [comment]
Can this get included in 2.9?

**Comment by crenshaw-dev** [comment]
@ericblackburn can you manually open a cherry-pick against release-2.9? Looks like our bot took a hike.

**Pull request merged**
