### PR TITLE
fix: Change underscore (_) back to plus (+) to get valid SemVer when when reading tags from OCI registry

### LINKED ISSUE #14097: Wildcard support in OCI Helm Repos not working if build identifier set in version
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

With https://github.com/argoproj/argo-cd/pull/10641 Argo introduced the "Wildcard support in OCI Helm Repositories targetRevision".

A full semver compatible chart version looks like this: `<version core> "-" <pre-release> "+" <build>`, e.g. `1.2.3-rc1+abcdefgh`.
Bug: Argo fails to resolve the `targetRevision: "*"` wildcard if a build identifier is part of the chart version in the OCI repo.

Background info: OCI tags are not semver compatible. The "+" character is not allowed. Helm worked around this by converting "+" to "_" before pushing to the OCI repo and vice versa when pulling from the repo.

Helm prints the following hint when this happens:
```
OCI artifact references (e.g. tags) do not support the plus sign (+). To support
storing semantic versions, Helm adopts the convention of changing plus (+) to
an underscore (_) in chart version tags when pushing to a registry and back to
a plus (+) when pulling from a registry.
```

Argo CD is not respecting this convention and considers a tag "1.2.3-rc1_abcdefgh" invalid semver.

**To Reproduce**

* Create OCI repo
* Push chart to OCI repo with a version including a build identifier (e.g. 1.2.3+abcdefgh)
* Register OCI repo with Argo CD
* Create Argo Application referencing the chart and setting targetRevision: "*"
* -> Argo CD prints the errors shown below (Logs)

**Expected behavior**

Argo CD respects Helm convention how build identifiers are handled in case of OCI registries and converts "_" back to "+" before trying to find matching versions. Argo CD successfully installs latest Helm chart matching the targetRevision wildcard, even if build identifier is included in the chart version.

**Version**

2.7.4 and master (2023-06-16)

**Logs**

UI Shows:

```
repo-server {"error":"no version for constraints: constraint not found in 1 tags","grpc.code":"Unknown","grpc.method":"GenerateManifest","grpc.service":"repository.RepoServerService","grpc.start_time":"2023-06-16T11:15:56Z","grpc.time_ms":161.567,"level":"error","msg":"finished unary call with code Unknown","span.kind":"server","system":"grpc","time":"2023-06-16T11:15:56Z"}
```

repo-server with debug level:
```
repo-server {"level":"debug","msg":"Invalid semantic version: 1.2.3_553b3905","time":"2023-06-16T11:21:56Z"}
```

### PR DESCRIPTION
**Pull request by xashr**
Fixes #14097: OCI tag handling is now similar to Helm's approach: https://github.com/helm/helm/blob/03911aeab78290394e589cf7705d3fd542a236c9/pkg/registry/client.go#L650
 
Background info: OCI tags are not semver compatible. The "+" character is not allowed. Helm worked around this by converting "+" to "_" before pushing to the OCI repo and vice versa when pulling from the repo.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
The PR looks good!! I would agree to @crenshaw-dev 's comment to have a unit test for this..

**Comment by xashr** [comment]
@crenshaw-dev I have extended the TestGetTagsFromUrl to demonstrate the behavior

**Review by ishitasequeira — APPROVED** [review]
@xashr , The test looks good!! There is no real need to separate it out. The test demonstrates the change to be working.

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@xashr can you manually open cherry-pick PRs against all versions you want to patch?

**Comment by xashr** [comment]
@crenshaw-dev Thanks, only the merge to 2.8 is required as it contains the other OCI improvements as well.

**Pull request merged**
