### PR TITLE
docs: fixed Ingress configuration for kubernetes v1.19+

### PR DESCRIPTION
**Pull request by rsoika**
I fixed the Ingress configuration according to the Kuberentes Version 1.19+ using SSL-Passthrough with cert-manager and Let's Encrypt.

Also the configuration without the Let's Encrypt part should be fixed. But as I was unable to test it I leave it as it was

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by rsoika** [comment]
push

**Comment by sbose78** [comment]
Thank you for the fix, do you mind amending your commit message to have the format "fix: fixed Ingress..." ?

**Comment by sbose78** [comment]
Change looks good to me.

**Comment by rsoika** [comment]
I updated the commit message

**Review by jannfis — APPROVED** [review]
LGTM, thanks @rsoika

**Pull request merged**
