### PR TITLE
fix: use 'git show-ref' to both retrieve and store generated manifests

### LINKED ISSUE #3577: Manifests are incorrectly cached if target revision is tag
**Describe the bug**

Argo CD uses `git show-ref -s <targetVersion>` to get commit sha and retrieve cached manifests. After manifest generation Argo CD uses  `git checkout <targetVersion>; git rev-parse HEAD` to get current commit sha to save generated manifests in cache. 

It appears that `git show-ref -s <targetVersion>` and `git checkout <targetVersion>; git rev-parse HEAD` might return different commits. 🤯

**To Reproduce**

1. Create argocd app using https://github.com/argoproj/argo-rollouts repo and `manifests/cluster-install` as a path.
2. Set target revision to v0.7.0
3. Manifests are supposed to be cached for 24 hours but generated for argo rollouts every 3 minutes. 

```
$ git clone git@github.com:argoproj/argo-rollouts.git
$ cd argo-rollouts
$ git show-ref -s v0.7.0                                                                                                                             
4189b6e95bfdd734dabfb36cd44ff1f9411b3f43
git rev-parse HEAD                                                                                                                               
3b1d4717a1725200698549f5a7f11ba7bef6cb86
```
**Expected behavior**

Manifests should be cached for 24 hours.

**Version**
```shell
v1.5.4
```

### PR DESCRIPTION
**Pull request by alexmt**
Closes #3577

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
Please see my comments in #3577

**Comment by alexmt** [comment]
Thank you for investigation, @jannfis ! I did not know how to even approach it. 

I agree that problem is specific to v0.7.0 tag in rollouts repo. However I think we still need to have protection from this edge case.

Current Argo CD behavior is the following:

* Run `git show-ref -s <tag>`, get commit `a`
* Try to find cached manifests for commit `a` and get nothing
* Run `git checkout v0.7.1; git rev-parse HEAD`, get commit `b`.
* Generate manifests using commit `b` and store result using commit `b` as cache key. Commit `b` is used for caching "just-in-case", assuming that it must be the same as `a`.

Since `a` and `b` are different, Argo CD never caches manifests for application pointing to the affected git tag. As a result we have to keep running the expensive generation every couple minutes. 

PR changes the last step behavior so that Argo CD uses commit `a` to cache generated manifests. This would solve the performance issue. 

What do you think?

**Comment by alexmt** [comment]
To summarize, 

Now Argo CD generates manifests for commit `b` instead of `a` ( because of incorrect git metadata ) and never caches results.

I want to cache results to stop the performance issues.

**Comment by jannfis** [comment]
Understood, and I think you're correct. We should not have a performance penalty or overload on Git servers due to repository issues.

However, I think that we should emit a warning if the commit SHAs for the tag (i.e. `show-ref -s <tag>`) and the actual HEAD of the tag (i.e. `rev-parse HEAD` after `checkout <tag>`) differ - so that there is a chance it gets fixed at the root (because I think it is a "broken" repository)

**Comment by alexmt** [comment]
Nice suggestion! Added warning message.

**Review by jannfis — APPROVED** [review]
LGTM. thank you for adding the warning!

**Pull request merged**
