### PR TITLE
Issue5408- Increase text contrast for improved web accessibility

### LINKED ISSUE #5408: ui: Darken text to increase contrast ratio for visually impaired users
# Summary

The [WCAG 2.0](https://www.w3.org/TR/WCAG20/) recommend a minimum contrast ratio of 4.5:1 (text:background) for its AA standard, and a 7:1 ratio for AAA. The current contrast ratio of `$argo-color-gray-6` (used for most text in the UI) to a white background is [4.15:1](https://webaim.org/resources/contrastchecker/?fcolor=6D7F8B&bcolor=FFFFFF), which while only slightly below the AA standard, falls quite short of the AAA criteria. 

# Proposal

Simply switching from `$argo-color-gray-6` to `$argo-color-gray-7`for text on white backgrounds nets a contrast ratio of [7.42:1](https://webaim.org/resources/contrastchecker/?fcolor=495763&bcolor=FFFFFF). 

Before:
Screen Shot 2021-02-04 at 9 52 58 AM

After:
Screen Shot 2021-02-04 at 9 53 22 AM

### PR DESCRIPTION
**Pull request by reginaelyse**
Closes #5408 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Screenshots of darkened text/icons:

Screenshot from 2021-03-05 17-50-43
Screenshot from 2021-03-05 17-55-11

Darkened and boldened text:

Screenshot from 2021-03-05 18-38-14

Also aligned spacing for current and last status (previously they were slightly off because of an auto margin): 

Screenshot from 2021-03-05 17-55-35

Please try this out and let me know if you find any issues with it, places where this change is not acceptable, or places you think I missed!

### CODE REVIEW

**Review by rbreeze — COMMENTED** [review]
looks good, thanks! 

> Also aligned spacing for current and last status (previously they were slightly off because of an auto margin)

I don't see where this change is in the code though.

**Comment by reginapizza** [comment]
> I don't see where this change is in the code though.

@rbreeze that change is in this commit https://github.com/argoproj/argo-cd/pull/5700/commits/3f71ef365ffc9c8f8bf36432ba0d489d58e7b439

**Comment by rbreeze** [comment]
Ah I see, I was looking for an addition instead of a deletion

**Review by alexmt — APPROVED** [review]
LGTM. @rbreeze , can you please confirm that your comments resolved?

**Comment by rbreeze** [comment]
Yeah, comments are resolved!

**Pull request merged**
