### PR TITLE
feat: store the name of operation initator in the app CRD

### PR DESCRIPTION
**Pull request by alexmt**
PR introduces `status.operationState.operation.initiatedBy` field that stores the name of a user who initiated the operation (or `automated sync policy` if operation started automatically). This is useful for end-users as well as for projects like argocd-notifications (see https://github.com/argoproj-labs/argocd-notifications/issues/30 )

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
@jessesuen , @jannfis what do you think ?

**Review by jessesuen — APPROVED** [review]

**Comment by jannfis** [comment]
I think that's a good idea, @alexmt - I just don't know whether a string is sufficient, future wise. So maybe we should make the initiator a dedicated object in the CRD and start with a single string as sole property?

**Comment by alexmt** [comment]
I agree with you @jannfis . In fact, we already need a better way to distinguish between auto-sync and manual sync. I can imaging that someone might want to get a notifications only about manual syncs and filter-out automated syncs.

**Comment by alexmt** [comment]
@jannfis updated `initiatedBy` struct as you suggested. PTAL

**Review by jannfis — APPROVED** [review]
Awesome @alexmt! LGTM.

**Comment by Shubham1406220** [comment]
When i use the above config in notification cm i can see the author name but it is not coming in correct format

image

**Pull request merged**
