### PR TITLE
fix: Added missing 'alias:' prefix for repository name (#15563)

### LINKED ISSUE #15563: Alias: not working in repository reference in Chart.yaml
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

https://helm.sh/docs/chart_best_practices/dependencies/#repository-urls

> If the repository has been added to the repository index file, the repository name can be used as an alias of URL. Use **alias: or @** followed by repository names.

But in ArgoCD Code only @ ist considered, see the if.
https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1020

**To Reproduce**

Create a Chart.yaml with dependency repository: "alias:my-repo"
```yaml
apiVersion: v2
name: my-app
version: 0.1
description: my-app
dependencies:
- name: some-dep
  version: 0.2.17
  repository: 'alias:my-repo'
```
**Expected behavior**

Repository works with helm dependency build

**Version**
v2.8.4
v2.7.14
**Logs**
```
Unable to save changes: application spec for my-app is invalid: InvalidSpecError: Unable to generate manifests in my-app: rpc error: code = Unknown desc = `helm dependency build` failed exit status 1: Error: could not find protocol handler for: alias
```

As mentioned here:
https://github.com/argoproj/argo-cd/issues/7436#issuecomment-1681884991

Looking forward to a fix,
Regards Philipp

### PR DESCRIPTION
**Pull request by ffppmm**
Fixes #15563
Checklist:

* [x] this is a bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Added missing 'alias:' prefix for repository name as described here:

https://helm.sh/docs/chart_best_practices/dependencies/#repository-urls

### CODE REVIEW

**Comment by ffppmm** [comment]
Can somebody help me why 'Integration tests / Run end-to-end tests (v1.26.9)' is failing?

Regards Philipp

**Comment by ffppmm** [comment]
> Can somebody help me why 'Integration tests / Run end-to-end tests (v1.26.9)' is failing?
> 
> Regards Philipp

SRY works now 😄

**Comment by ffppmm** [comment]
Hi,

could anybody take a look at mit request, I think this is a good addition to use **alias:repo** and @repo. Is there anything missing that I have to provide for getting my request merged?

Regards Philipp

**Comment by mashanm** [comment]
Can someone please review the PR ? It is a blocker for all charts with alias dependencies.

**Review by ishitasequeira — APPROVED** [review]
Thanks @ffppmm for raising the PR. LGTM!!

**Comment by ffppmm** [comment]
Hi,
thanks a lot, very happy to contribute a useful addition to the, imho awesome, project 😄 

Regards Philipp

**Comment by mashanm** [comment]
When can we expect this to be released ?

**Comment by ffppmm** [comment]
Hi,

will this be in the current 2.10 Release?

Regards Philipp

**Pull request merged**
