### PR TITLE
fix: Parse hostname correctly from repoURL to fetch correct CA cert

### LINKED ISSUE #19138: TLS certs not passed correctly if helm repo contains path in repository URL
**Describe the bug**

I am try to deploy a chart from a private OCI Helm registry with self-signed certificates. I have added the tls certificate for my domain `my-registry.default` in `argocd-tls-certs-cm` configmap. 
```yaml
$ kubctl get cm argocd-tls-certs-cm -o yaml -n default
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-tls-certs-cm
data:
  my-registry.default: |-
    -----BEGIN CERTIFICATE-----
    <cert data>
    -----END CERTIFICATE-----
```
When I create a Helm repository with `my-registry.default` repository URL everything works as expected. However, if the repository URL contains a path eg: `my-registry.default/helm-charts`, the tls certificate for the domain i.e `my-registry.default` is not picked up by Argo CD and results into `x509: certificate signed by unknown authority` errors.

**To Reproduce**

1. Add OCI registry certs into Argo CD via UI or CLI
2. Create a Helm OCI repository with path in repo url.  
3. Observe repo connection status and repo server logs 

**Expected behavior**

Argo CD should connect successfully to the registry

**Screenshots**

image

**Version**

```shell
v2.10.11
```
Didn't test with `master` but I think should be reproducible with it.

**Logs**
Repo server logs
```bash
# no path in url
time="2024-07-22T11:14:17Z" level=info msg=Trace args="[helm registry login my-registry --username ****** --password ****** --ca-file /app/config/tls/my-registry]" dir=/tmp/helm2649027701 operation_name="exec helm" time_ms=62.63742499999999
time="2024-07-22T11:14:17Z" level=info msg="took to test helm oci repository" seconds=0.062829967

# path in url
time="2024-07-22T11:15:34Z" level=info msg="helm registry login my-registry/helm-charts --username ****** --password ******" dir=/tmp/helm1150378190 execID=75776
time="2024-07-22T11:15:34Z" level=error msg="`helm registry login my-registry/helm-charts --username ****** --password ******` failed exit status 1: WARNING: Using --password ****** the CLI is insecure. Use --password-stdin.\ntime=\"2024-07-22T11:15:34Z\" level=info msg=\"Error logging in to endpoint, trying next endpoint\" error=\"Get \\\"https://my-registry/v2/\\\": tls: failed to verify certificate: x509: certificate signed by unknown authority\"\nError: Get \"https://my-registry/v2/\": tls: failed to verify certificate: x509: certificate signed by unknown authority" execID=75776```

### PR DESCRIPTION
**Pull request by svghadi**
Fixes #19138

`getCAPath` func doesn't correctly return the path for the tls cert if the repoURL passed contains path or port number without a schema. This is mainly because how the `url.Parse()` treats a url without schema.  [Stackoverflow REF](https://stackoverflow.com/a/62083424)
eg:
```text
'registry.default/helm-charts' ---parsed-as---> 'registry.default/helm-charts'   #should be 'registry.default'
'registry.example.com:5000' ---parsed-as---> ''    # should be 'registry.example.com'
```
Below changes are made to ensure the hostname is correctly parsed to return a valid cert path(if present) belonging to the repoURL. The new change works like before for oci case where the schema `oci://` is not part of repoURL string, no separate handling is required.

Change:
- Prepend repoURL with dummy schema if not present to ensure `net/url` correctly parse the hostname.
- Strip port number from hostname if any using `net/url`'s `Hostname()` func.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
LGTM!

**Comment by svghadi** [comment]
Thanks @jannfis. 

@ishitasequeira - It would be great if this could be backported to 2.12.x and 2.11.x.

**Pull request merged**
