### PR TITLE
docs: k8s version in Ingress Configuration documentation

### LINKED ISSUE #5726: Documentation ingress has incorrect version API
Fix Argo-cd documentation:

- Operator Manual 
    - Ingress Configuration

Section _AWS Application Load Balancers (ALBs) And Classic ELB (HTTP Mode)_ 

The Ingress code snippet says:

_apiVersion: networking.k8s.io/v1 # Use extensions/v1beta1 for Kubernetes **1.14** and older_

The version is wrong the right version is 1.18 and older.

_apiVersion: networking.k8s.io/v1 # Use extensions/v1beta1 for Kubernetes **1.18** and older_

Screenshot 2021-03-10 at 14 55 18

### PR DESCRIPTION
**Pull request by isaacloal**
Resolves #5726

Fix k8s version in ingress documentation, specifically:

- Operator Manual
  - Ingress Configuration
 
Section _AWS Application Load Balancers (ALBs) And Classic ELB (HTTP Mode)_ in Ingress snippet the right version is 1.18 and older.

### CODE REVIEW

**Review by sbose78 — APPROVED** [review]
Looks good to me, wonder why it was 1.14 :) ?

**Comment by namku** [comment]
@sbose78 Did you approve this PR, didn't it? I don't know why it's marked as pending review.

**Comment by sbose78** [comment]
I'm not an approver :)
@jessesuen would you be able to take a look?

**Review by alexmt — APPROVED** [review]
LGTM. Thank you for review @sbose78 !

**Pull request merged**
