### PR TITLE
feat: Implement GKE ManagedCertificate CRD health checks

### PR DESCRIPTION
**Pull request by micke**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by micke** [comment]
I'm having some issues setting up my local environment, i'm following https://argoproj.github.io/argo-cd/developer-guide/contributing

I will continue to try and make it work but i figured that health checks tests run in the CI too?

**Comment by jannfis** [comment]
Hi @micke, thanks for your contribution! If you need any support with setting up your toolchain, feel free to ask anything and also to suggest improvements to the documentation! 

As for your question, yes, the health checks will run in the CI too (or when running `make test` in your toolchain). I'm not sure why the CI on this PR is in pending state, I can only imagine that CircleCI was having issues at the time you submitted the PR. Please try to retrigger it according to https://argoproj.github.io/argo-cd/developer-guide/faq/#can-i-retrigger-the-checks-without-pushing-a-new-commit

**Comment by micke** [comment]
@jannfis Thanks for the quick response!
Thanks, will do!

I triggered another build and it looks like it's running now! Cheers!

**Comment by micke** [comment]
I'm not sure but i think the last failing check is something i can't really do anything about.

So i guess this is ready for review!

**Review by jannfis — APPROVED** [review]
LGTM, thanks a lot @micke

**Pull request merged**
