### PR TITLE
feat: Support drag and drop to delete resources/applications (#9619)

### LINKED ISSUE #9619: UI: Support drag and drop of Pods to trash bin to delete pods.
# Summary

Support drag and drop of Pods to a trash bin to quickly delete pods.  Implement drag and drop.

# Motivation

Please give examples of your use case, e.g. when would you use this.

@alexc opened https://github.com/argoproj/argo-cd/issues/9524 which has points that are quite forward thinking.  This enhancement aims to implement point number 4 which is doable in the current UI and in the 2D space.

# Proposal

How do you think this should be implemented?
- Add drag and drop
- Add a 2D trash can as the drop target

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

Fixes #9619

### Notes for reviewer

Design Points:
- This solution uses drag and drop support from HTML5 and CSS.  We aren’t affecting components and their props directly. Also, the actual resource deletion is taken care of by the action. (Currently it is not necessary to use libraries like React DnD.  The graph view is currently not using a Dagre renderer like D3 which has DnD support. )
- The Trash Can is available only in the Tree and Network Details Views.
- Identifying the target node uses name, namespace, kind and uid.  Probably could just use uid and kind.  See DataTransfer object

Tests considered:
- Tested drag and drop of both applications and resources
- Load balancer/ingress/external nodes are not draggable
- Compared confirmation dialog with the dialog launched from the popup context menu of the resource.  (Dialog for Managed versus unmanaged resources is different)
- Basic drag and drop testing (eg. drag in and drag out, drop, etc.)

Tested this with Safari 15.5, Firefox 91.10.0, and Chrome 102.0.5005.61 on Mac.

### Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by keithchong** [comment]
DragAndDropDelete

**Review by ciiay — COMMENTED** [review]
Hi Keith, I tested it and it works perfectly! And codewise it looks good to me too. I only have one small concern about the "Delete" icon. When I hover on it, it changes background color which makes me feel it's clickable and then I click on it nothing happens. Is there a way we can make the style changes when user start dragging a resource? Just for better UX.

**Comment by keithchong** [comment]
Thanks @ciiay.  That is a good point. I'll try different styles.

**Comment by keithchong** [comment]
Updated trash can based on Yi's comments:

TrashCan

**Review by reginaelyse — APPROVED** [review]
works and LGTM, great work Keith!

**Review by ciiay — APPROVED** [review]
LGTM 👍

**Comment by rbreeze** [comment]
Hi Keith, thanks for contributing this PR. I think the implementation looks good. However, I'm not sure this is a direction we want to take with the Argo CD UI. While in this case it doesn't do harm, I think adding this paradigm to support drag and drop will clutter/confuse the overall UX, and for the use cases that Argo CD needs to solve, I don't think it's a crucial feature.

I'm all for making the user experience easier and better, but I think drag and drop would mostly serve to surprise users in the context of Argo CD. That being said I'm happy to hear / discuss counterpoints 🙂

**Comment by keithchong** [comment]
Hi Remington, you should see Alex's vision of the UI from his original request: https://github.com/argoproj/argo-cd/issues/9524 ;-) . It's true though, that if we want to impress users, a 3D view can be added to show all the different nodes.

It's likely that this is the first use case where drag and drop applies, and these are graphical, tree-based views with nodes after all.  In theory, the layout does not have to be fixed like it is now, and it can be free form/flowing where users could drag nodes around to however way they want to position their resources.  One click of a button could reset the layout to 'our' default layout, for example.

**Comment by keithchong** [comment]
@rbreeze, @alexc, perhaps we can add this to the next SIG UI meeting agenda if we don't reach a decision.

**Comment by alexec** [comment]
I concur with @rbreeze. While I’m actually amazed you managed to do this, it’s a huge shift in how the UI works and I don’t think we’re there yet as a community, on as an industry.

As we move towards the “meta-verse”, I do think that 3D is the future of UI. I don’t think the paradigms have been worked out yet.

**Comment by crenshaw-dev** [comment]
Going to close this for now, excellent work that it is, to wait for a time when we're ready for a larger concerted shift.  :-)

**Pull request closed without merging**
