### PR TITLE
fix: resolve the double scroll bars in the application view. fixes #14588

### LINKED ISSUE #14588: ArgoCD Horizontal Scrollbar only available once bottom of screen reached.
Checklist:

* [x ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ x] I've included steps to reproduce the bug.
* [x ] I've pasted the output of `argocd version`.

**Describe the bug**

The horizontal scrollbar is not available in Firefox until you reach the very bottom of the screen.

Previous closed issue #8298 describes this happening before.

**To Reproduce**

1. Open a large application with ArgoCD UI
2. There will not be horizontal scrollbar available
3. The vertical scrollbar cannot be used to get down to the bottom of screen
4. Have to use mouse scroll wheel to get to the bottom for horizontal scrollbar to be available
5. Then use vertical scroll bar again to go back up to see what you are looking for
6. Horizontal scrollbar remains available

If you select a different application, the horizontal scrollbar is gone and have to use the steps above to get it back.

**Expected behavior**

Expect a horizontal scroll be to be available, whenever the application does not fit within the current window size.

**Screenshots**

No horizontal scrollbar available:
image

Cannot use vertical scrollbar, this is as far as it will go:
image

Use mouse scroll wheel to reach the bottom, now I have scroll bar:
image

**Version**

```shell
argocd-server: v2.7.7+4650bb2.dirty
  BuildDate: 2023-07-05T19:42:32Z
  GitCommit: 4650bb2817c3c81405f40cf77e93ef2b5fb275fb
  GitTreeState: dirty
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.0.1 2023-03-14T01:32:48Z
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

Firefox:  115.0.2 (64-bit), Manjaro KDE.

### PR DESCRIPTION
**Pull request by djeebus**
If the applications page is sufficiently large, the page has double scrollbars (see below). I believe the root cause of this was #12068, and was mentioned by @n9 [in that same PR](https://github.com/argoproj/argo-cd/pull/12068/files#r1210054139). This PR cleans that up, and tweaks a few margin/paddings that were probably tweaked to try and work around this issue. 

Before:
image

After:
image

Fixes #14588

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jannfis** [comment]
@keithchong @alexmt @rbreeze could one of you please review and possibly approve this PR?

**Review by rbreeze — APPROVED** [review]
LGTM

**Comment by djeebus** [comment]
@rbreeze  any chance of getting this merged/released, or are we waiting for a merge window or something? not sure what the release process is here.

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
@djeebus can you rebase the PR and resolve conflicts??

**Comment by djeebus** [comment]
I'm  running 2.9.3 and I don't see this issue any more. Must have been fixed in someone else's PR recently. I'll close mine.

**Pull request closed without merging**
