### PR TITLE
docs: revert appset path.path and path.segments docs

### PR DESCRIPTION
**Pull request by crenshaw-dev**
I think the find/replace when just slightly too far in https://github.com/argoproj/argo-cd/pull/10026.

@speedfl could you take a look and confirm that this reversion is correct?

### CODE REVIEW

**Comment by speedfl** [comment]
Ah yes I remember, I did this change and finally we added a dedicated section for GoTemplate. However I did not rollback changes

**Review by speedfl — APPROVED** [review]
Ok for me.

**Comment by crenshaw-dev** [comment]
Thank you @speedfl!

**Review by speedfl — CHANGES_REQUESTED** [review]
This might be missing as well: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/applicationset/Generators-Git.md?plain=1#L48

**Comment by crenshaw-dev** [comment]
Good catch, fixed!

**Review by leoluz — APPROVED** [review]

**Pull request merged**
