### PR TITLE
fix(appset): Don't use revision cache when reconciling after webhook (#16062)

### LINKED ISSUE #16062: ApplicationSet not generating new Application on webhook with Git file generator
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

https://cloud-native.slack.com/archives/C01U45M2SVB/p1697465637463289

When the applicationset controller receives a webhook, it only refreshes existing applicationsets, it does not rescan the repository for new applications when using the Git file generator.

**To Reproduce**

Add the following applicationset:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-service
  namespace: argocd-ops
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/someorg/argocd.git
        revision: HEAD
        files:
          - path: "environments/**/test-service/config.json"
  template:
    metadata:
      name: "{{.namespace}}-{{.serviceName}}"
    spec:
      project: default
      sources:
        - chart: kubernetes-dashboard
          repoURL: https://kubernetes.github.io/dashboard/
          targetRevision: "{{.chartVersion}}"
      destination:
        name: "in-cluster"
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
```

And add the following `config.json` to the source argocd repo described in the applicationset, in the following path - `environments/staging/test-namespace/services/test-service/config.json`:
```json
{
  "serviceName": "test-service",
  "namespace": "test-namespace",
  "env": "staging",
  "chartVersion": "*"
}
```
Push and look at the logs.

**Expected behavior**
The webhook should cause argocd to scan the repo again and to generate missing applications.

**Version**
```shell
argocd: v2.8.1+2bc94af.dirty
  BuildDate: 2023-08-22T23:51:03Z
  GitCommit: 2bc94af7bd081bc4682c2c6dc005f6336c754c2b
  GitTreeState: dirty
  GoVersion: go1.21.0
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.8.4+c279299\
```

**Logs**

```
######## START Webhook logs
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:30:14Z" level=info msg="refresh ApplicationSet argocd-ops/test-service from webhook"
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:30:14Z" level=info msg="generated 0 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/someorg/argocd-applicative.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:environments/**/test-service/config.json,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:30:14Z" level=info msg="end reconcile" applicationset=argocd-ops/test-service requeueAfter=3m0s
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:30:14Z" level=info msg="generated 0 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/someorg/argocd-applicative.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:environments/**/test-service/config.json,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:30:14Z" level=info msg="end reconcile" applicationset=argocd-ops/test-service requeueAfter=3m0s
######## END Webhook logs

######## START Interval scan logs
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="generated 1 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/someorg/argocd-applicative.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:environments/**/test-service/config.json,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="created Application" app=test-namespace-test-service appSet=test-service
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="end reconcile" applicationset=argocd-ops/test-service requeueAfter=3m0s
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="generated 1 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/someorg/argocd-applicative.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:environments/**/test-service/config.json,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="unchanged Application" app=test-namespace-test-service appSet=test-service
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="end reconcile" applicationset=argocd-ops/test-service requeueAfter=3m0s
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="generated 1 applications" generator="{nil nil &GitGenerator{RepoURL:https://github.com/someorg/argocd-applicative.git,Directories:[]GitDirectoryGeneratorItem{},Files:[]GitFileGeneratorItem{GitFileGeneratorItem{Path:environments/**/test-service/config.json,},},Revision:HEAD,RequeueAfterSeconds:nil,Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},PathParamPrefix:,Values:map[string]string{},} nil nil nil nil nil nil nil}"
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="unchanged Application" app=test-namespace-test-service appSet=test-service
argocd-applicationset-controller-56664994d5-bszbt applicationset-controller time="2023-10-22T07:31:30Z" level=info msg="end reconcile" applicationset=argocd-ops/test-service requeueAfter=3m0s
######## END Interval scan logs
```

We can see that the webhook itself did not cause the application to be generated, and only the interval scan about a minute or so later caused it to be generated.

### PR DESCRIPTION
**Pull request by dhruvang1**
Repo Server is using ref caching in `GetGitFiles` which prevents AppSet from seeing the new commit. There are few approaches to solve it:

- Disable Ref caching for `GetGitFiles`. 
  -  For each AppSet reconciliation, both from webhook & periodic sync, poll the Git Server to return the latest refs.
- Disable Ref caching only for webhook requests (Implemented here)
  -  Add `noRevisionCache` parameter in `GitFilesRequest`. On reconciliation triggered from webhook, pass `noRevisionCache: true` to repo server to force the Git Server polling to get the latest commit.
- ~~Explicitly pass the commit sha in request~~ (complex as an AppSet can have multiple git generator)
  -  ~~We store the commit sha obtained from the webhook in AppSet annotation. On next reconciliation, pass the commit sha as revision. Repo server has the logic to handle commit sha and no changes are required there.~~

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Fixes #16062

### CODE REVIEW

**Comment by ericblackburn** [comment]
LGTM, but I am not a Code Owner

**Comment by dhruvang1** [comment]
@crenshaw-dev could you take a look when you are available.

**Comment by Laakso** [comment]
Awesome! Thanks for the fix! We've been waiting for this :) ❤️

**Review by alexmt — APPROVED** [review]
LGTM!

**Comment by jmalloc** [comment]
Any chance of getting a tag of 2.9.x that includes this fix? :pray:

**Comment by jolet** [comment]
hi we are experiencing same issue with AppSets not reconciliating new Apps, currently we found temp fix is to do manual hard refresh on any existing App from AppSet which triggers reconcilliation immediately, but thats cumbersome and prone to pointing teams to overuse hard refresh for everything

**Pull request merged**
