### PR TITLE
feat: exclude Endpoints and EndpointSlices Kubernetes resource by default

### LINKED ISSUE #20013: Ignore known Kubernetes internal resources by default with `resource.exclusions`
### Summary

Exclude `Endpoints` and `EndpointSlices` by default.

### Motivation

`Endpoints` and `EndpointSlices` are Kubernetes internal resources that most users will never directly create. They can clutter the UI and decrease Argo performance due to high churn.

### Proposal

Specify the resources by default in the `resource.exclusions` configuration.

### PR DESCRIPTION
**Pull request by jaehanbyun**
Fixes #20013 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

## What I have done:
* Exclude Endpoints and EndpointSlices by default.

### CODE REVIEW

**Review by nitishfy — APPROVED** [review]
LGTM!

**Review by ishitasequeira — COMMENTED** [review]
@jaehanbyun The PR looks good. Can you resolve conflicts?

**Comment by jaehanbyun** [comment]
@ishitasequeira I've resolved the conflicts. Thank you!

**Review by nitishfy — APPROVED** [review]

**Review by gdsoumya — APPROVED** [review]

**Comment by agaudreault** [comment]
I think this should be reverted. The behavior of this pull request is not configurable by the users and a user that wants to display Endpoint or Endpoint Slices in the UI of Argo  cannot do it anymore. 

The proposal on the issue suggested to add it to the default configuration for the 3.0 version.

**Comment by crenshaw-dev** [comment]
@agaudreault if you open the revert PR, I'll merge

**Pull request merged**
