### PR TITLE
fix(server): handle PATCH in http/s server (#2677)

### LINKED ISSUE #2677: Sending HTTP request using PATCH verb to REST API results in connection reset
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Sending a HTTP request using the PATCH verb, the connection gets closed unexpected by the API server without any trace why.

**To Reproduce**

You can use curl to reproduce, below example is against local `argocd-server` listening on port 8081 in insecure mode:

```shell
$ curl -d '{}' -v -XPATCH http://127.0.0.1:8081/api/v1/session
*   Trying 127.0.0.1:8081...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> PATCH /api/v1/session HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.65.3
> Accept: */*
> Content-Length: 2
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 2 out of 2 bytes
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer

```

**Expected behavior**

Server should send back appropriate error message, such as `HTTP 405 - Method not allowed` or even better `HTTP 501 - Not implemented` if we don't support `PATCH` verb at all.

**Version**
Build from latest master:

```shell
argocd-server: v1.3.0+ac6413c.dirty
  BuildDate: 2019-11-09T12:16:35Z
  GitCommit: ac6413c63668a8850605c06f235e473e907303f7
  GitTreeState: dirty
  GoVersion: go1.12.5
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: vdev-2019-05-15T19:48:06+0200
  Kustomize Version: Version: {KustomizeVersion:3.1.0 GitCommit:95f3303493fdea243ae83b767978092396169baf BuildDate:2019-07-26T18:11:16Z GoOs:linux GoArch:amd64}
  Helm Version: v2.13.1
  Kubectl Version: v1.15.2

```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by mmerrill3**
Handle PATCH HTTP verb in HTTP/s server for argocd.  
Fixes #2677
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by mmerrill3** [comment]
@crenshaw-dev, could you give a PR review?

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @mmerrill3!

**Pull request merged**
