### PR TITLE
chore(deps): bump kustomize to v5.2.1 

### PR DESCRIPTION
**Pull request by MPV**
This PR upgrades `kustomize` from `5.1.1` to `5.2.1`:
- https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.2.1

The main benefit I see is the new support for OCI based helm repos:
- https://github.com/kubernetes-sigs/kustomize/pull/5167

---

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

---

Also note this upstream issue preventing me from using `hack/installers/checksums/add-kustomize-checksums.sh`:
- https://github.com/kubernetes-sigs/kustomize/issues/5403

Thus I:
1. `cd hack/installers/checksums`
2. commented out this line:
https://github.com/argoproj/argo-cd/blob/973565e194c094d163d2fd0873364d0e36951806/hack/installers/checksums/add-kustomize-checksums.sh#L7
3. downloaded them manually:
```shell
$ wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_darwin_amd64.tar.gz
$ wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_darwin_arm64.tar.gz
$ wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_amd64.tar.gz
$ wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_arm64.tar.gz
$ wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_ppc64le.tar.gz
$ wget https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_s390x.tar.gz
```
4. calculated checksums manually:
```
$ sha256sum kustomize_v5.2.1* > checksums.txt
```
5. ran `./add-kustomize-checksums.sh 5.2.1`
6. this PR

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Yep, let's get this into 2.9. Thanks, @MPV!

**Comment by crenshaw-dev** [comment]
@MPV would you mind opening a PR directly against release-2.9 to cherry-pick?

**Comment by MPV** [comment]
@crenshaw-dev Yes, please see:
- https://github.com/argoproj/argo-cd/pull/16082

**Pull request merged**
