### PR TITLE
fix: Tooltips point in wrong direction#11935

### LINKED ISSUE #11644: ui: incomplete confirmation dialogue
Depending on where you are in the UI when requesting a resource delete, you will see either the:
- yellow confirmation dialogue with 3 options (background, foreground, noncascade)
- this white dialogue that seems incomplete:

Screenshot 2022-12-10 at 05 47 48

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Version**

```shell
master
```

### PR DESCRIPTION
**Pull request by JessieTeng89**
fix: incomplete confirmation dialogue
Fixes https://github.com/argoproj/argo-cd/issues/11644

### CODE REVIEW

**Comment by JessieTeng89** [comment]
Hi @jsoref @saumeya @alexmt 
As discussed in another PR https://github.com/argoproj/argo-cd/pull/12200, I fixed the issue https://github.com/argoproj/argo-cd/issues/11644 with this PR using media query way. 
Could you please check and approve it if no other issues? Or please let me know if any other action is needed.
Thanks!

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by JessieTeng89** [comment]
> LGTM!!

Thanks for your approval, can I know how we can merge the PR?

**Comment by metavida** [comment]
Question: Does this PR really fix really address issue https://github.com/argoproj/argo-cd/issues/11644 which is about a missing checkbox label in the "Delete pod" confirmation dialogue?

I ask because the changes in this PR seem related to a Tooltip component and the the related PR https://github.com/argoproj/argo-cd/pull/12200 [mentioned](https://github.com/argoproj/argo-cd/pull/12578#issuecomment-1831772367) by @JessieTeng89 above does indeed contain a screenshot of a tooltip and **not** the "Delete pod" confirmation dialog.

Maybe this PR instead fixes issue https://github.com/argoproj/argo-cd/issues/11935 ?

**Comment by JessieTeng89** [comment]
> Question: Does this PR really fix really address issue #11644 which is about a missing checkbox label in the "Delete pod" confirmation dialogue?
> 
> I ask because the changes in this PR seem related to a Tooltip component and the the related PR #12200 [mentioned](https://github.com/argoproj/argo-cd/pull/12578#issuecomment-1831772367) by @JessieTeng89 above does indeed contain a screenshot of a tooltip and **not** the "Delete pod" confirmation dialog.
> 
> Maybe this PR instead fixes issue #11935 ?

I think you are right, this PR is to fix issue https://github.com/argoproj/argo-cd/issues/11935

**Pull request merged**
