### PR TITLE
Certmanager docs

### PR DESCRIPTION
**Pull request by genebean**
This is a docs update to show how to configure SSL-Passthrough with cert-manager and Let's Encrypt. The second commit in this PR simply adds some clarification to existing examples to remove confusion that tripped me up.

### CODE REVIEW

**Review by alexec — APPROVED** [review]
Lgtm

**Review by alexmt — APPROVED** [review]
Thank you!

**Comment by genebean** [comment]
Question @alexmt - what happens post merge to make things like this show up on your docs site? Just curious.

**Comment by alexmt** [comment]
We need to run `mkdocs gh-deploy -r upstream` to push updated docs to github pages. This process is still manual, unfortunately.

**Comment by genebean** [comment]
@alexmt you might want to checkout https://github.com/peaceiris/actions-gh-pages

**Comment by bukowa** [comment]
I am following this example and it's not working.

**Pull request merged**
