### PR TITLE
chore: Reduce e2e tests runtime by using better sleep intervals in Expect

### LINKED ISSUE #20923: Optimize e2e tests runtime by a better Expect waiting strategy
# Summary

Right now, Expect checks for the condition immediately and then sleeps for 3 seconds before next each attempts. The idea is start small, e.g. 50-100ms first wait, 200-250ms seconds wait, etc.

# Motivation

e2e tests are relatively slow, taking 45-50 min. There are a lot of Then calls, so shaving several seconds off a lot of them would be very helpful.

# Proposal

Experiment with a gradual increase of sleep time in Expect, starting with small values.

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
Closes #20923

Right now the condition is checked immediately and then only after 3 seconds and so on. But sometimes the need for a wait may be much smaller than 3 seconds. So, try using smaller intervals with exponential increase up to 3 seconds instead.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by andrii-korotkov-verkada** [comment]
It saved about 3 minutes with
```
	sleepIntervals := []time.Duration{
		10 * time.Millisecond,
		50 * time.Millisecond,
		200 * time.Millisecond,
		500 * time.Millisecond,
		1 * time.Second,
		2 * time.Second,
		3 * time.Second,
	}
```

Before:
Screenshot 2024-11-24 at 1 50 53 PM
Screenshot 2024-11-24 at 1 51 04 PM

After:
Screenshot 2024-11-24 at 1 51 15 PM
Screenshot 2024-11-24 at 1 51 25 PM

**Comment by andrii-korotkov-verkada** [comment]
Slightly faster with more granular windows, but still about 3 min savings. I'll try to tune more.

Screenshot 2024-11-24 at 2 46 07 PM
Screenshot 2024-11-24 at 2 46 12 PM

**Comment by andrii-korotkov-verkada** [comment]
With these it's about the same improvement

```
	sleepIntervals := []time.Duration{
		10 * time.Millisecond,
		20 * time.Millisecond,
		40 * time.Millisecond,
		70 * time.Millisecond,
		100 * time.Millisecond,
		150 * time.Millisecond,
		250 * time.Millisecond,
		400 * time.Millisecond,
		700 * time.Millisecond,
		1 * time.Second,
	}
```

Screenshot 2024-11-24 at 5 20 33 PM
Screenshot 2024-11-24 at 5 20 43 PM

**Comment by andrii-korotkov-verkada** [comment]
Similar savings with
```
	sleepIntervals := []time.Duration{
		10 * time.Millisecond,
		20 * time.Millisecond,
		50 * time.Millisecond,
		100 * time.Millisecond,
		200 * time.Millisecond,
		300 * time.Millisecond,
		500 * time.Millisecond,
		1 * time.Second,
	}
```

Screenshot 2024-11-24 at 6 17 46 PM
Screenshot 2024-11-24 at 6 17 53 PM

**Comment by andrii-korotkov-verkada** [comment]
The test failures seem to be sporadic, re-running.

**Comment by andrii-korotkov-verkada** [comment]
Overall savings are 3-4 minutes, micro-tuning doesn't seem to affect things that much.

**Comment by andrii-korotkov-verkada** [comment]
Though sometimes the old test runs are several minutes slower than baseline as well, making measurements hard. Maybe 3-5 minutes is a decent estimate.

**Review by nitishfy — COMMENTED** [review]
Nice, I spent a good time understand this piece of code. I've couple of questions, feel free to answer:

1. On running a single e2e test locally (something like [this](https://github.com/argoproj/argo-cd/blob/master/test/e2e/deployment_test.go#L31)), I encounter the following logs:

```
time="2024-11-25T11:54:25+05:30" level=info msg=initialized apiServerAddress="localhost:8080"
=== RUN   TestDeploymentWithLabelTrackingMode
time="2024-11-25T11:54:25+05:30" level=info msg="kubectl delete ns -l e2e.argoproj.io=true --field-selector status.phase=Active --wait=false" dir= execID=fdb16
time="2024-11-25T11:54:25+05:30" level=debug msg="namespace \"argocd-e2e--test-deployment-vnulb\" deleted\n" duration=143.206404ms execID=fdb16
time="2024-11-25T11:54:25+05:30" level=info msg="kubectl delete crd -l e2e.argoproj.io=true --wait=false" dir= execID=86a56
time="2024-11-25T11:54:26+05:30" level=debug msg="No resources found\n" duration=117.688318ms execID=86a56
time="2024-11-25T11:54:26+05:30" level=info msg="kubectl delete clusterroles -l e2e.argoproj.io=true --wait=false" dir= execID=c2ebb
time="2024-11-25T11:54:26+05:30" level=debug msg="No resources found\n" duration=81.021291ms execID=c2ebb
time="2024-11-25T11:54:27+05:30" level=info msg="../../dist/argocd proj create gpg --plaintext --server localhost:8080 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTczMjYwMjI2NiwibmJmIjoxNzMyNTE1ODY2LCJpYXQiOjE3MzI1MTU4NjYsImp0aSI6ImU3OWM5ZWMxLTk3ODYtNGIyMS1iZDEyLTUzY2FjZjU0YThhNSJ9.OfztfBfG6yts8CF6tu4cwm2G7uRN_80KWHAhm3KxyyE --insecure" dir= execID=6426e
time="2024-11-25T11:54:27+05:30" level=debug duration=128.311226ms execID=6426e
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e" dir= execID=1b9ae
time="2024-11-25T11:54:27+05:30" level=debug duration=1.039824ms execID=1b9ae
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e/app/config/tls" dir= execID=2da2d
time="2024-11-25T11:54:27+05:30" level=debug duration=1.243132ms execID=2da2d
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e/app/config/ssh" dir= execID=5d2c7
time="2024-11-25T11:54:27+05:30" level=debug duration="753.82µs" execID=5d2c7
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e/gpg" dir= execID=e5ede
time="2024-11-25T11:54:27+05:30" level=debug duration="670.437µs" execID=e5ede
time="2024-11-25T11:54:27+05:30" level=info msg="chmod 0700 /tmp/argo-e2e/gpg" dir= execID=099e5
time="2024-11-25T11:54:27+05:30" level=debug duration="535.013µs" execID=099e5
time="2024-11-25T11:54:27+05:30" level=info msg="pkill -9 gpg-agent" dir= execID=031ce
time="2024-11-25T11:54:27+05:30" level=debug duration=9.17055ms execID=031ce
time="2024-11-25T11:54:27+05:30" level=error msg="`pkill -9 gpg-agent` failed exit status 1" execID=031ce
time="2024-11-25T11:54:27+05:30" level=info msg="gpg --import ../fixture/gpg/signingkey.asc" dir= execID=67c16
time="2024-11-25T11:54:27+05:30" level=debug duration=8.935482ms execID=67c16
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e/app/config/gpg/source" dir= execID=9486e
time="2024-11-25T11:54:27+05:30" level=debug duration=1.15376ms execID=9486e
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e/app/config/gpg/keys" dir= execID=71187
time="2024-11-25T11:54:27+05:30" level=debug duration="781.983µs" execID=71187
time="2024-11-25T11:54:27+05:30" level=info msg="chmod 0700 /tmp/argo-e2e/app/config/gpg/keys" dir= execID=ba52e
time="2024-11-25T11:54:27+05:30" level=debug duration="745.268µs" execID=ba52e
time="2024-11-25T11:54:27+05:30" level=info msg="mkdir -p /tmp/argo-e2e/app/config/plugin" dir= execID=405c9
time="2024-11-25T11:54:27+05:30" level=debug duration="788.302µs" execID=405c9
time="2024-11-25T11:54:27+05:30" level=info msg="chmod 0700 /tmp/argo-e2e/app/config/plugin" dir= execID=3256d
time="2024-11-25T11:54:27+05:30" level=debug duration="650.971µs" execID=3256d
time="2024-11-25T11:54:27+05:30" level=info msg="cp -Rf testdata /tmp/argo-e2e/testdata.git" dir= execID=4f28a
time="2024-11-25T11:54:27+05:30" level=debug duration=4.577191ms execID=4f28a
time="2024-11-25T11:54:27+05:30" level=info msg="chmod 777 ." dir=/tmp/argo-e2e/testdata.git execID=e71dc
time="2024-11-25T11:54:27+05:30" level=debug duration="516.539µs" execID=e71dc
time="2024-11-25T11:54:27+05:30" level=info msg="git init -b master" dir=/tmp/argo-e2e/testdata.git execID=029f7
time="2024-11-25T11:54:27+05:30" level=debug msg="Initialized empty Git repository in /tmp/argo-e2e/testdata.git/.git/\n" duration=2.282931ms execID=029f7
time="2024-11-25T11:54:27+05:30" level=info msg="git add ." dir=/tmp/argo-e2e/testdata.git execID=d829f
time="2024-11-25T11:54:27+05:30" level=debug duration=17.402916ms execID=d829f
time="2024-11-25T11:54:27+05:30" level=info msg="git commit -q -m initial commit" dir=/tmp/argo-e2e/testdata.git execID=17542
time="2024-11-25T11:54:27+05:30" level=debug duration=9.159429ms execID=17542
time="2024-11-25T11:54:27+05:30" level=info msg="kubectl create ns argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw" dir= execID=cddc6
time="2024-11-25T11:54:27+05:30" level=debug msg="namespace/argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw created\n" duration=125.434843ms execID=cddc6
time="2024-11-25T11:54:27+05:30" level=info msg="kubectl label ns argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw e2e.argoproj.io=true" dir= execID=367ba
time="2024-11-25T11:54:27+05:30" level=debug msg="namespace/argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw labeled\n" duration=167.493165ms execID=367ba
time="2024-11-25T11:54:27+05:30" level=info msg="clean state" duration=2.492015017s id=TestDeploymentWithLabelTrackingMode-uvbtw name=TestDeploymentWithLabelTrackingMode password=password username=admin
time="2024-11-25T11:54:28+05:30" level=info msg="../../dist/argocd app create test-deployment-with-label-tracking-mode --repo file:///tmp/argo-e2e/testdata.git --dest-server https://kubernetes.default.svc --path deployment --project default --dest-namespace argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw --plaintext --server localhost:8080 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTczMjYwMjI2NiwibmJmIjoxNzMyNTE1ODY2LCJpYXQiOjE3MzI1MTU4NjYsImp0aSI6ImU3OWM5ZWMxLTk3ODYtNGIyMS1iZDEyLTUzY2FjZjU0YThhNSJ9.OfztfBfG6yts8CF6tu4cwm2G7uRN_80KWHAhm3KxyyE --insecure" dir= execID=b28cc
time="2024-11-25T11:54:29+05:30" level=debug msg="application 'test-deployment-with-label-tracking-mode' created\n" duration=445.797326ms execID=b28cc
time="2024-11-25T11:54:29+05:30" level=info msg="expectation succeeded: no error and output contained ''"
time="2024-11-25T11:54:29+05:30" level=info msg="../../dist/argocd app sync test-deployment-with-label-tracking-mode --timeout 20 --prune --plaintext --server localhost:8080 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTczMjYwMjI2NiwibmJmIjoxNzMyNTE1ODY2LCJpYXQiOjE3MzI1MTU4NjYsImp0aSI6ImU3OWM5ZWMxLTk3ODYtNGIyMS1iZDEyLTUzY2FjZjU0YThhNSJ9.OfztfBfG6yts8CF6tu4cwm2G7uRN_80KWHAhm3KxyyE --insecure" dir= execID=3b3f2
time="2024-11-25T11:54:30+05:30" level=debug msg="TIMESTAMP                  GROUP        KIND   NAMESPACE                                                                  NAME    STATUS    HEALTH        HOOK  MESSAGE\n2024-11-25T11:54:29+05:30   apps  Deployment  argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw      nginx-deployment  OutOfSync  Missing              \n2024-11-25T11:54:30+05:30   apps  Deployment  argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw      nginx-deployment  OutOfSync  Missing              deployment.apps/nginx-deployment created\n2024-11-25T11:54:30+05:30   apps  Deployment  argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw      nginx-deployment    Synced  Progressing              deployment.apps/nginx-deployment created\n\nName:               argocd-e2e/test-deployment-with-label-tracking-mode\nProject:            default\nServer:             https://kubernetes.default.svc\nNamespace:          argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw\nURL:                http://localhost:8080/applications/test-deployment-with-label-tracking-mode\nSource:\n- Repo:             file:///tmp/argo-e2e/testdata.git\n  Target:           \n  Path:             deployment\nSyncWindow:         Sync Allowed\nSync Policy:        Manual\nSync Status:        Synced to  (8998098)\nHealth Status:      Healthy\n\nOperation:          Sync\nSync Revision:      8998098802e66423dbbe14defe99f20e1b51d78f\nPhase:              Succeeded\nStart:              2024-11-25 11:54:29 +0530 IST\nFinished:           2024-11-25 11:54:30 +0530 IST\nDuration:           1s\nMessage:            successfully synced (all tasks run)\n\nGROUP  KIND        NAMESPACE                                                   NAME              STATUS  HEALTH   HOOK  MESSAGE\napps   Deployment  argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw  nginx-deployment  Synced  Healthy        deployment.apps/nginx-deployment created\n" duration=1.169976245s execID=3b3f2
time="2024-11-25T11:54:30+05:30" level=info msg="expectation succeeded: no error and output contained ''"
time="2024-11-25T11:54:30+05:30" level=info msg="expectation succeeded: operation phase should be Succeeded, is Succeeded"
time="2024-11-25T11:54:30+05:30" level=info msg="expectation succeeded: sync status to be Synced, is Synced"
time="2024-11-25T11:54:30+05:30" level=info msg="expectation succeeded: health to should Healthy, is Healthy"
time="2024-11-25T11:54:30+05:30" level=info msg="../../dist/argocd app manifests test-deployment-with-label-tracking-mode --plaintext --server localhost:8080 --auth-token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcmdvY2QiLCJzdWIiOiJhZG1pbjpsb2dpbiIsImV4cCI6MTczMjYwMjI2NiwibmJmIjoxNzMyNTE1ODY2LCJpYXQiOjE3MzI1MTU4NjYsImp0aSI6ImU3OWM5ZWMxLTk3ODYtNGIyMS1iZDEyLTUzY2FjZjU0YThhNSJ9.OfztfBfG6yts8CF6tu4cwm2G7uRN_80KWHAhm3KxyyE --insecure" dir= execID=18280
time="2024-11-25T11:54:30+05:30" level=debug msg="---\napiVersion: apps/v1\nkind: Deployment\nmetadata:\n  labels:\n    app: nginx\n    app.kubernetes.io/instance: test-deployment-with-label-tracking-mode\n  name: nginx-deployment\n  namespace: argocd-e2e--test-deployment-with-label-tracking-mode-uvbtw\nspec:\n  replicas: 0\n  selector:\n    matchLabels:\n      app: nginx\n  template:\n    metadata:\n      labels:\n        app: nginx\n    spec:\n      containers:\n      - image: quay.io/argoprojlabs/argocd-e2e-container:0.1\n        name: nginx\n        ports:\n        - containerPort: 80\n\n" duration=127.181839ms execID=18280
--- PASS: TestDeploymentWithLabelTrackingMode (5.47s)
```

I can't see any logs for a pending state. This means the sleepIntervalsIdx never got incremented. How is the code you wrote useful for a single e2e test in case like the one i shared above?

2. If you look at logs carefully, `expectation succeeded:` got printed 5 times for the above e2e test. Do you have an idea about why is this happening even though the `Expect()` func is called thrice in the e2e-test?

```
Expect(OperationPhaseIs(OperationSucceeded)).
Expect(SyncStatusIs(SyncStatusCodeSynced)).
Expect(HealthIs(health.HealthStatusHealthy)).
```

**Comment by andrii-korotkov-verkada** [comment]
> I can't see any logs for a pending state.

That's normal if we succeeded immediately - the first try would be with no delay.

> Do you have an idea about why is this happening even though the Expect() func is called thrice in the e2e-test?

Yes, runCli calls verifyAction, which has Expect inside.

**Comment by andrii-korotkov-verkada** [comment]
I also found that application sets has its own Expect, need to update that too.

**Comment by andrii-korotkov-verkada** [comment]
New runs show ~10 min wins!

**Review by blakepettersson — APPROVED** [review]
Great stuff!

**Review by ishitasequeira — APPROVED** [review]
That's a great improvement to make our CI faster.

**Review by crenshaw-dev — APPROVED** [review]
Great stuff, thank you!

**Pull request merged**
