### PR TITLE
fix(ui): Change group/grouped visualization argoproj#13565

### LINKED ISSUE #13565: Change group/grouped visualization
# Summary

The number of objects in a group should be shown on the group tile and the hover hint text should be terser

# Motivation

I shouldn't have to hover over an ℹ️ to find out how many objects are in a collapsed tile
The hint shouldn't tell me the kind of object when the tile itself tells me exactly that

# Proposal

How do you think this should be implemented?

### Current behavior

image

#### Proposed

image

### PR DESCRIPTION
**Pull request by vipin-m-s**
Fixes: argoproj#13565 

I have added the count of resources on resource tile. Please let me know if it needs ant changes 

Demo:- 

Uploading argo-cd-grouping.mp4…

### CODE REVIEW

**Comment by ashutosh16** [comment]
@vipinachar would you be able to add a screenshot of ui change?

**Comment by vipinachar** [comment]
oh sorry, I had uploaded a video seems like there was some error.

https://github.com/argoproj/argo-cd/assets/40431065/09fc78ad-7ca6-48c8-ab76-06938656d2db

**Comment by vipinachar** [comment]
@ashutosh16 I have uploaded video of my changes

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Pull request merged**
