### PR TITLE
feat(ui): Add sourceNamespaces field to projects UI (#15196)

### LINKED ISSUE #15196: Add `sourceNamespaces` field to the Projects UI
# Summary

The Projects edit page in the UI doesn't include the `sourceNamespaces` field. We should add that field.

# Motivation

Apps-in-any-namespace is a popular feature. Full UI support is good.

# Proposal

Just add a little section at the bottom of the Project UI to allow viewing/setting the sourceNamespaces field. Ideally, only show the field if apps-in-any-namespace is enabled.

### PR DESCRIPTION
**Pull request by jdvgh**
Closes #15196
 - This PR adds the field `sourceNamespaces` which is already defined in the `AppProject` CRD to the `ProjectDetails` UI
- 
image

- it is defined as follows (see manifests/crds/appproject-crd.yaml):
```
              sourceNamespaces:
                description: SourceNamespaces defines the namespaces application resources
                  are allowed to be created in
                items:
                  type: string
                type: array
```
- From what I figured there is no test for the `AppProject` UI yet so I'd have to write one from scratch which would rely not only on my change but on the whole AppProject UI - maybe this would be a whole other issue/feature.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged. 
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jdvgh** [comment]
Copying from the issue:

@crenshaw-dev Could you give me a pointer on how I'd check whether apps-in-any-namespace is enabled?
I noticed application-tiles.tsx uses `useAuthSettingsCtx?.appsInAnyNamespaceEnabled`
where
`const useAuthSettingsCtx = React.useContext(AuthSettingsCtx);` however I'm not that deep into TypeScript and React to know whether this could and should be re-used in `settings/components/project-details/project-details.tsx`

**Comment by crenshaw-dev** [comment]
@jdvgh I think it's safe to reuse here. Checking w/ a colleague...

**Comment by crenshaw-dev** [comment]
Checked w/ Ashutosh Singh, you should be good to go using that Ctx.

**Comment by jdvgh** [comment]
@crenshaw-dev added it to be specific to `appsInAnyNamespaceEnabled`. Tested it by (un)setting:
```
data:
  application.namespaces: test-*
```
in `argocd-cmd-params-cm`.

**Comment by ashutosh16** [comment]
UI seems good

Screenshot 2023-11-30 at 9 38 18 AM
Screenshot 2023-11-30 at 9 38 00 AM

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Comment by jdvgh** [comment]
@ashutosh16 @crenshaw-dev  thanks for the Review :clinking_glasses: - do I need to do anything more now? For me it still says:
``` 
Merging is blocked
Merging can be performed automatically with 1 approving review.
```

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @jdvgh!

**Pull request merged**
