### PR TITLE
docs: 20 min video

### PR DESCRIPTION
**Pull request by vfarcic**
I just created a video with a hands-on introduction to Argo CD. Does it make sense to include it in the docs?

### CODE REVIEW

**Comment by jannfis** [comment]
This is an awesome video, @vfarcic! 

However, I personally think we should put it into the README (within the community contribution section) or replace the existing (and rather old) video in the docs.

@jessesuen What do you think?

**Review by alexmt — CHANGES_REQUESTED** [review]
Just finished watching video. It is awesome! thank you @vfarcic 

I agree with @jannfis . We have `Community Blogs and Presentations` section in README: https://github.com/argoproj/argo-cd/blob/master/README.md#community-blogs-and-presentations  

It is better to add the link there.

**Comment by vfarcic** [comment]
Done. It's added to the "Community Blogs and Presentations" section.

**Review by jannfis — APPROVED** [review]
LGTM!

**Review by alexmt — APPROVED** [review]

**Pull request merged**
