### PR TITLE
fix: oidc should set samesite cookie

### PR DESCRIPTION
**Pull request by junorouse**
https://github.com/argoproj/argo-cd/blob/76bacfdea4d9bbce774887f18a62e3ebc27d486c/util/oidc/oidc.go#L252-L261

oidc callback handler should set samesite cookie as same as the server.go does for security issue.

https://github.com/argoproj/argo-cd/blob/fe8d47e0eae9fe5bd9dbcf52ca898fe4b4ba9ce1/server/server.go#L535-L542

---

Checklist:

* [x] (b) this is a bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
Good catch! Thank you for this fix, @junorouse!

**Review by jannfis — CHANGES_REQUESTED** [review]
Sorry for early approval and now requesting a change - but I feel we should also adapt the path value in the cookie to match the actual configuration as well. 

Would you be willing to implement that too, @junorouse ?

**Comment by junorouse** [comment]
🤔

**Comment by alexmt** [comment]
Failed e2e test is flaky. Added it to the list  https://github.com/argoproj/argo-cd/issues/3635

**Comment by junorouse** [comment]
https://github.com/argoproj/argo-cd/blob/ac097f143cf763081db59919eec04a44c6a8fe65/cmd/argocd-server/commands/root.go#L98-L103

according to upper codes, rootPath is equal to baseHref. it can be changed rootPath with baseHRef?

**Comment by jannfis** [comment]
@junorouse Yes, it should be sufficient to use value of `baseHref` for the cookie path, if `baseHref != ""`

**Comment by junorouse** [comment]
@jannfis I don't know why tc fails, but the code works properly

**Comment by jannfis** [comment]
@junorouse Some of the tests are flaky and intermittently fail from time to time (we're working on fixing them). I have restarted the CI manually, in the future you can also do it via Git as described in https://argoproj.github.io/argo-cd/developer-guide/faq/#can-i-retrigger-the-checks-without-pushing-a-new-commit

**Review by jannfis — APPROVED** [review]
LGTM, thank you for also implementing the requested changes!

The unit test that is failing is flaky and has nothing to do with the code changes of this PR.

**Pull request merged**
