### PR TITLE
feat: remove ksonnet from codebase

### PR DESCRIPTION
**Pull request by gdsoumya**
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>

Linked to #5256 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by ishitasequeira** [comment]
LGTM so far!!

I guess we still have ksonnet in some places that we might want to remove:
- unit/e2e tests and testdata files
- [tools-versions.sh](https://github.com/gdsoumya/argo-cd/blob/feat/rem_ksonnet/hack/tool-versions.sh#L14)
- docs like [high_availability.md](https://github.com/gdsoumya/argo-cd/blob/feat/rem_ksonnet/docs/operator-manual/high_availability.md), [ci_automation.md](https://github.com/gdsoumya/argo-cd/blob/feat/rem_ksonnet/docs/user-guide/ci_automation.md)
- [ApplicationDestination in model.ts](https://github.com/gdsoumya/argo-cd/blame/feat/rem_ksonnet/ui/src/app/shared/models.ts#L149-L155) - maybe just need to update comments
- [test/remote/README.md](https://github.com/gdsoumya/argo-cd/blob/feat/rem_ksonnet/test/remote/README.md?plain=1#L218-L219)
- [run-e2e-remote.sh](https://github.com/gdsoumya/argo-cd/blob/feat/rem_ksonnet/test/remote/run-e2e-remote.sh#L39-L40) 

Also, do we want to remove ksonnet.io from [url_allow_list](https://github.com/gdsoumya/argo-cd/blob/feat/rem_ksonnet/docs/url-allow-list#L16)?

There might be some other places I might have missed out. Let me know WDYT.

**Comment by gdsoumya** [comment]
Thanks @ishitasequeira for the review I have updated all the places I previously missed.

**Review by terrytangyuan — COMMENTED** [review]
Watch out for more required changes after https://github.com/argoproj/argo-cd/pull/8514 and https://github.com/argoproj/argo-cd/pull/8507

**Comment by ishitasequeira** [comment]
@gdsoumya, It seems the above PRs have been merged. Can we get this PR rebased and the merge conflicts resolved?

**Comment by gdsoumya** [comment]
@ishitasequeira @terrytangyuan I couldn't rebase this PR properly there were too many changes, I have raised a new PR that is in sync with master. Will be great if we can review this and get it merged before conflicting changes are merged into master again.

**Pull request closed without merging**
