### PR TITLE
chore: update gitops engine for force sync option (#5882) - 2.9

### PR DESCRIPTION
**Pull request by digitalyuki**
Cherry-pick for argocd for 2.9 release, related to: https://github.com/argoproj/argo-cd/pull/17866

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
@digitalyuki could you please run "go mod tidy" and commit changes, also if you add me to your fork i can help you fix this PR

**Comment by digitalyuki** [comment]
@pasha-codefresh , I ran `go mod tidy` in my forked branch and I don't see any changes:
```
$ go mod tidy
go: finding module for package k8s.io/api/networking/v1alpha1
go: finding module for package k8s.io/api/admissionregistration/v1alpha1
go: finding module for package github.com/chai2010/gettext-go/gettext
go: finding module for package k8s.io/api/authentication/v1alpha1
go: finding module for package k8s.io/api/flowcontrol/v1beta3
go: github.com/argoproj/argo-cd/v2/cmd/argocd/commands imports
	github.com/argoproj/gitops-engine/pkg/utils/kube imports
	k8s.io/kubectl/pkg/cmd/apply imports
	k8s.io/kubectl/pkg/util/i18n imports
	github.com/chai2010/gettext-go/gettext: module github.com/chai2010/gettext-go@latest found (v1.0.3), but does not contain package github.com/chai2010/gettext-go/gettext
go: github.com/argoproj/argo-cd/v2/util/argo/diff imports
	github.com/argoproj/gitops-engine/pkg/utils/kube/scheme imports
	k8s.io/kubernetes/pkg/apis/admissionregistration/install imports
	k8s.io/kubernetes/pkg/apis/admissionregistration/v1alpha1 imports
	k8s.io/api/admissionregistration/v1alpha1: module k8s.io/api@latest found (v0.30.1, replaced by k8s.io/api@v0.24.17), but does not contain package k8s.io/api/admissionregistration/v1alpha1
go: github.com/argoproj/argo-cd/v2/util/argo/diff imports
	github.com/argoproj/gitops-engine/pkg/utils/kube/scheme imports
	k8s.io/kubernetes/pkg/apis/authentication/install imports
	k8s.io/kubernetes/pkg/apis/authentication/v1alpha1 imports
	k8s.io/api/authentication/v1alpha1: module k8s.io/api@latest found (v0.30.1, replaced by k8s.io/api@v0.24.17), but does not contain package k8s.io/api/authentication/v1alpha1
go: github.com/argoproj/argo-cd/v2/util/argo/diff imports
	github.com/argoproj/gitops-engine/pkg/utils/kube/scheme imports
	k8s.io/kubernetes/pkg/apis/flowcontrol/install imports
	k8s.io/kubernetes/pkg/apis/flowcontrol/v1beta3 imports
	k8s.io/api/flowcontrol/v1beta3: module k8s.io/api@latest found (v0.30.1, replaced by k8s.io/api@v0.24.17), but does not contain package k8s.io/api/flowcontrol/v1beta3
go: github.com/argoproj/argo-cd/v2/util/argo/diff imports
	github.com/argoproj/gitops-engine/pkg/utils/kube/scheme imports
	k8s.io/kubernetes/pkg/apis/networking/install imports
	k8s.io/kubernetes/pkg/apis/networking/v1alpha1 imports
	k8s.io/api/networking/v1alpha1: module k8s.io/api@latest found (v0.30.1, replaced by k8s.io/api@v0.24.17), but does not contain package k8s.io/api/networking/v1alpha1

$ git diff

$ 
```

**Comment by pasha-codefresh** [comment]
@digitalyuki i will try resolve it tomorrow, looks like it also requires k8s client update

**Comment by pasha-codefresh** [comment]
@digitalyuki , it requires update gitops-engine , it also includes upgrade of kubernetes api, and i also trigger a lot of other changes . Is it possible that you just update to 2.10?

**Comment by pasha-codefresh** [comment]
Closing it for now, let me know if it is impossible for you to upgrade

**Pull request closed without merging**
