### PR TITLE
chore: update notifications-engine to f4856710

### PR DESCRIPTION
**Pull request by lukaspj**
Updates to https://github.com/argoproj/notifications-engine/commit/f48567108f01c67938355f4ff704866ceed6e7fd, changes since current version:

* Security
  * argoproj/notifications-engine#283
* Deps
  * argoproj/notifications-engine#273
  * argoproj/notifications-engine#246
  * argoproj/notifications-engine#262
* Telegram
  * argoproj/notifications-engine#265
* Opsgenie
  * argoproj/notifications-engine#271
  * argoproj/notifications-engine#268
  * argoproj/notifications-engine#267
* GitHub
  * argoproj/notifications-engine#235
  * argoproj/notifications-engine#225

In order to achieve this I had to align the telegram reference by adding:
https://github.com/argoproj/argo-cd/pull/17971/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R300

And permanently replace whilp/git-urls with chainguard-dev/git-urls to avoid a conflict between notifications-engine and the dependencies in ArgoCD:
https://github.com/argoproj/argo-cd/pull/17971/files#diff-9bf515f23994401fc8c2f43c5f95b5dcb70a5df95fe7f6ba106d87b809cc9568R16

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

I think this might be more a request than an actual PR since I'm not sure exactly what to test for here to validate the changes.
notifications-engine hasn't been updated since February, and we'd really like some of the changes made, especially the one from the 7th of February. We can also see that there have been at least one CVE fixed. 
I don't know if there's a reason that notifications-engine hasn't been updated but I wanted to at least highlight it. Feel free to close this PR if I'm missing some obvious reason that updates of notifications-engine has been stalled.

### CODE REVIEW

**Comment by lukaspj** [comment]
I’m struggling with getting the codegen to work on my laptop, various permission errors,I will try and dig around and see if I can get it to run.

**Comment by gazidizdaroglu** [comment]
hey @lukaspj, maybe you can take [this](https://github.com/argoproj/argo-rollouts/pull/3384) pr as reference.

**Comment by pasha-codefresh** [comment]
@lukaspj , you can add me as collaborator to your fork, so i can help you with codegen

**Comment by lukaspj** [comment]
> hey @lukaspj, maybe you can take [this](https://github.com/argoproj/argo-rollouts/pull/3384) pr as reference.

I will update this  PR to have a similar layout, thanks!

**Comment by lukaspj** [comment]
> @lukaspj , you can add me as collaborator to your fork, so i can help you with codegen

Thanks! I suspect I’m having issues because my container runtime is not running with root access

**Review by pasha-codefresh — APPROVED** [review]

**Comment by mubarak-j** [comment]
Is it too late to cherry pick this PR into 2.11 release?

**Pull request merged**
