### PR TITLE
fix: docs js regex can't parse selected version from url (#18755)

### LINKED ISSUE #18755: [Docs] incorrect regex to get currentVersion
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
Incorrect Regex for Extracting CurrentVersion on Docs
The current regex `/\/en\/(release-(?:v\d+|\w+)|latest|stable)\//` doesn't allow versions with a dot (.). As a result, versions like release-2.11 are not matched correctly.

**To Reproduce**

**Expected behavior**
The regex should match versions that include dots, such as release-2.11. This would ensure that all valid version formats are correctly processed.

**Screenshots**
Screenshot 2024-06-21 at 3 55 30 PM
Screenshot 2024-06-21 at 3 55 58 PM

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by ft-jasong**
Closes #18755

Hi ! I found some bug about ArgoCD's documentation which javascript file cannot parse the right version.
I fixed the regex and deleted not working variable `window['READTHEDOCS_DATA]`.
Thank you !
## Changes
- removed `window['READTHEDOCS_DATA']` which mentioned #18407.
- fixed regex

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]
LGTM

**Comment by suzaku** [comment]
It seems like this fix is not deployed.

https://argo-cd.readthedocs.io/en/stable/assets/versions.js is still the old version.

**Comment by ft-jasong** [comment]
@suzaku It seems so. I realized that problem and made issue #18757, but not fixed yet

**Comment by crenshaw-dev** [comment]
@ft-jasong can you open a cherry-pick PR for release-2.12, release-2.11, release-2.10, and release-2.9? Looks like the cherry-pick bit isn't functioning.

**Comment by ft-jasong** [comment]
@crenshaw-dev I'm not sure if this is correct, but according to the answer to my question on Slack, it seems correct.

**Pull request merged**
