### PR TITLE
chore: update dependencies before starting e2e server

### PR DESCRIPTION
**Pull request by chetan-rns**
The e2e test server will show errors if there are irregular vendor and UI dependencies. This PR updates the Makefile to update the dependencies before starting the e2e server.

Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Good catch. I think we might revisit the complete build process sooner or later for some major improvements, and untying all the chaos within. One of the goals should be to get rid of the necessity to vendor and to have to build within `GOPATH` (codegen being one of the major reasons here).

On a note, can you please use the `chore` prefix for such changes to the build tool chain in the future? I think we use `fix` and `feat` exclusively for user visible changes that will make it in the Changelog. :)

**Comment by chetan-rns** [comment]
Didn't know about the changelog, will update the prefix

**Comment by wtam2018** [comment]
LGTM

**Review by pasha-codefresh — APPROVED** [review]
LGTM

**Review by alexmt — APPROVED** [review]

**Pull request merged**
