### PR TITLE
chore: helm2 verison bump

### PR DESCRIPTION
**Pull request by igaskin**
upgrading to 2.17.0

#4511

Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).

### CODE REVIEW

**Comment by jessesuen** [comment]
Seems like this broke this test. Do you understand why?

```
    --- FAIL: TestHelmDependencyBuild/Helm2 (0.33s)
        helm_test.go:113: 
            	Error Trace:	helm_test.go:113
            	Error:      	Received unexpected error:
            	            	`helm2 dependency build` failed exit status 1: Error: no repository definition for https://kubernetes-charts.storage.googleapis.com/. Please add the missing repos via 'helm repo add'
            	Test:       	TestHelmDependencyBuild/Helm2
        helm_test.go:115: 
            	Error Trace:	helm_test.go:115
            	Error:      	Received unexpected error:
            	            	`helm2 template . --name wordpress` failed exit status 1: Error: found in requirements.yaml, but missing in charts/ directory: mariadb
            	Test:       	TestHelmDependencyBuild/Helm2

```

**Comment by alexmt** [comment]
@igaskin , apparently https://kubernetes-charts.storage.googleapis.com/ is deprecated and replaced with https://charts.helm.sh/stable in next helm version: https://helm.sh/blog/charts-repo-deprecation/

Sent PR that fixes it https://github.com/igaskin/argo-cd/pull/1 to your fork :)

**Comment by igaskin** [comment]
Thank you gentlemen.  Ironically enough I was reading about the deprecation of "stable" yesterday.  Posting this link here for future travelers:
https://helm.sh/blog/new-location-stable-incubator-charts/

**Review by alexmt — APPROVED** [review]
LGTM!

**Pull request merged**
