### PR TITLE
feat: allow webhook settings to be referenced by external secret

### LINKED ISSUE #16261: External secrets values are not replaced in webhook settings
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

You can't reference other secrets in all the webhook settings with the the syntax $<secretName>:<key>.

**To Reproduce**

Have something like that:
```
apiVersion: v1
kind: Secret
stringData:
  webhook.github.secret: "mysecrethere"
metadata:
  labels:
    app.kubernetes.io/part-of: argocd
  name: argocd-helm-values
  namespace: argocd
type: Opaque
```

And set "webhook.github.secret" in "argocd-secret" to "$argocd-helm-values:webhook.github.secret". The value will not be replaced and you can check that by configuring the webhook with litterally "$argocd-helm-values:webhook.github.secret" (while any other value will not work meaning that the secret is not correctly replaced).

**Expected behavior**

The secret to be replaced

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by MrFreezeex**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates? -- No I believe referencing external secret is covered and it's "logical" that webhook secret should be covered by that as well
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Allow webhook settings to be referenced by external secrets to match existing behaviors with other secrets config (i.e.: oidc).

Fixes #16261

### CODE REVIEW

**Comment by fstr** [comment]
I'm in strong favour of getting this merged.

I just want to add a note that the existing functionality of replacing `$secretname:secretproperty` so far only applies ConfigMaps, as far as I can tell. 

The [OIDC example](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/#configuring-argocd-oidc) you mention uses this pattern and so does the [alternatives](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative) section of the user management guide.

> ArgoCD knows to check the keys under data in your Kubernetes Secret for a corresponding key whenever a value in a configmap starts with $, then your Kubernetes Secret name and : (colon).

The docs should be updated too.

**Comment by MrFreezeex** [comment]
> I just want to add a note that the existing functionality of replacing `$secretname:secretproperty` so far only applies ConfigMaps, as far as I can tell.
> 
> The [OIDC example](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/keycloak/#configuring-argocd-oidc) you mention uses this pattern and so does the [alternatives](https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/#alternative) section of the user management guide.
> 
> > ArgoCD knows to check the keys under data in your Kubernetes Secret for a corresponding key whenever a value in a configmap starts with $, then your Kubernetes Secret name and : (colon).
> 
> The docs should be updated too.

Indeed thanks! I thought it was already somewhat documented but you're right it only applies to configmap so far indeed! I added some documentations for that :+1:

**Review by fstr — APPROVED** [review]

**Comment by MrFreezeex** [comment]
> This change is what I needed too. Thanks @MrFreezeex . Do we need to wait for something else before merging?

Not really, it just needs a review from maintainers

**Review by pasha-codefresh — APPROVED** [review]
LGTM, great job!

**Comment by cblaindnsf** [comment]
+1 for this change :)

**Pull request merged**
