### PR TITLE
feat(controller): support Istio ServiceEntry network node #20270

### LINKED ISSUE #20270: Add istio `ServiceEntry` support into networking chart
# Summary
Currenty there is a partial built-in support for `istio` related resource `VirtualService` in ArgoCD UI. Istio has several networking related resource but this proposal is focusing on adding `ServiceEntry` support

# Motivation
Because networking is really useful for a quick overviewing the consistent of the configuration. I would like to add a missing important istio network component

# Proposal
As like `VirtualService` support. `ServiceEntry` should be add into the network diagram and reference to a workload by `workloadSelector`

TLDR; ServiceEntry works as same as traditional k8s service but with some extra feature

Reference: [Istio ServiceEntry API](https://istio.io/latest/docs/reference/config/networking/service-entry/#ServiceEntry)

### before
image

### after
Screenshot 2024-10-08 at 0 15 33

### PR DESCRIPTION
**Pull request by zapkub**
PR adds istio service entry to network diagram support.

Closes #20270

Checklist:
* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by pasha-codefresh — COMMENTED** [review]
Please fix linter issues

**Comment by zapkub** [comment]
@pasha-codefresh thanks, I have fixed the lint issue but look like some benchmark test is failed 🤔 I don't think it is related to my change

**Comment by crenshaw-dev** [comment]
@zapkub the failure was a flake. Restarted the test

**Review by christianh814 — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
LGTM, thank you @zapkub

**Pull request merged**
