### PR TITLE
fix: argocd login just hangs on 2.4.0 (#9679)

### LINKED ISSUE #9679: argocd login just hangs on 2.4.0
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Running `argocd login <server> --sso` does nothing and just hangs. The exact same command works on 2.3.

**To Reproduce**

* Download the 2.4.0 binary (https://github.com/argoproj/argo-cd/releases/tag/v2.4.0).
* Run `argocd login <server-name> --sso`.
* It doesn't seem like it's related to my specific Argo instance, because it even hangs if I run something like `argocd login random.com --sso`.
* Adding `--loglevel debug` doesn't show anything either.

**Expected behavior**

A browser tab is opened to go through the SSO login flow.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.4.0+91aefab
  BuildDate: 2022-06-10T17:38:43Z
  GitCommit: 91aefabc5b213a258ddcfe04b8e69bb4a2dd2566
  GitTreeState: clean
  GoVersion: go1.18.3
  Compiler: gc
  Platform: darwin/amd64
```

**Logs**

N/A

### PR DESCRIPTION
**Pull request by muma378**
Fixes #9679

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by muma378** [comment]
Not sure if it is correct to add an option (such as --dial-timeout 10s) to the client, any suggestions is appreciated.

**Review by crenshaw-dev — APPROVED** [review]
lgtm. Thanks @muma378 !

**Comment by crenshaw-dev** [comment]
@muma378 If you'd like to make it configurable, that works for me! Otherwise, I think 30s is a very reasonable/generous timeout.

**Comment by ashutosh16** [comment]
I don't think we need to make the timeout configurable, and yes  30s is reasonable. Changes LGTM!

**Pull request merged**
