### PR TITLE
fix: improvements to keyboard navigation

### PR DESCRIPTION
**Pull request by reginaelyse**
Related to #5466 (doesn't fix it entirely but works towards solving it)
This would allow the user to tab through the nav bar and changes the login button to an actual button that the user can tab to. 

Also incorporates changes in argo-ui including [my PR for more visual focus.](https://github.com/argoproj/argo-ui/pull/93) 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

https://user-images.githubusercontent.com/50851526/111832039-a5b5f680-88c6-11eb-9790-f9a5e474650f.mp4

### CODE REVIEW

**Review by alexmt — CHANGES_REQUESTED** [review]
Sorry for the delay in review.
I think package.json and yarn.lock files were added by mistake .

Please remove them and run `yarn add git+https://github.com/argoproj/argo-ui.git` in `ui` directory, not the root directory.

**Comment by reginapizza** [comment]
@alexmt my bad, I've fixed it now!

**Review by alexmt — APPROVED** [review]
Thank you!

**Pull request merged**
