### PR TITLE
chore: Add more logs with timing information to application controller [#18923]

### LINKED ISSUE #18923: Add more logs and/or duration fields to existing logs to give more visibility into slow reconciliations
# Summary

There's some logging for different steps taken during reconciliation, as well as some duration fields on "Reconciliation completed" log entries. However, they aren't enough to tell where the slowness may be coming from.

# Motivation

Sometimes reconciliation takes 30+ min and it's unclear why. Logs don't give enough info.
Screenshot 2024-07-03 at 11 38 01 AM
Screenshot 2024-07-03 at 11 38 22 AM

# Proposal

Add more log entries through different steps of reconciliation and/or add more timing/duration information to "Reconciliation completed".

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
Closes #18923
There are some gaps in debugging information for long reconciliations. Fill in a lot of those gaps by adding more debug logs with timing information about different code execution steps.
Also, fix a flaky test in app_test.go.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by andrii-korotkov-verkada** [comment]
I've tested in in a live staging environment and it seems to work well, e.g. 
Screenshot 2024-07-03 at 5 10 43 PM

**Comment by andrii-korotkov-verkada** [comment]
Note, that v1.28.11 has failed earlier, for some sync tests which timeouts or app becoming degraded instead of healthy. But I don't think those were related, unless there's a weird timing-based race condition when logs slow down some things just a tiny bit.

**Comment by andrii-korotkov-verkada** [comment]
Already discovered slowness/optimization opportunity! https://github.com/argoproj/argo-cd/issues/18929

**Review by pasha-codefresh — APPROVED** [review]
Thank you Andrii!

**Pull request merged**
