### PR TITLE
refactor: Replace `status.observedAt` with redis pub/sub channels for resource tree updates (#1340)

### LINKED ISSUE #1340: Replace `status.observedAt` with redis pub/sub channels for resource tree updates
Currently, to support the Application watch API, which powers the UI view which displays live  changes in a resource tree, the controller updates the k8s application object with a new `observedAt` timestamp whenever any of the application's resources changes. The Argo CD API server have  a K8s watch, and are notified about the update, which forwards the updated application object to the argocd client watchers.

The problem with this approach is:
1. It causes application objects to get updated very frequently (as frequent as an app's resources are updated). This causes a lot of chatter to k8s and unnecessarily bumps the resourceVersion of app objects

2. we unnecessarily involve the k8s api server for notifications about a change in an applications resource tree.

3. for a very active application, sometimes 1-second level granularity of observedAt is not sufficient, and we miss the last event(s) that happened (e.g. a pod going from terminating to missing). A manual refresh fixes this.

The solution is that instead of updating `status.observedAt` to notify the Argo CD API server about changes in the resource tree view, the API server could subscribe to a redis channel about changes in the resource tree (in addition to the application watch). By doing this, we:
1. no longer need to update the application object which is simply updating a timestamp.
2. we should no longer miss the last event(s) that happens with an application resources

### PR DESCRIPTION
**Pull request by alexmt**
Closes #1340 

More information about why this PR is required now:

The Application CRD status has two fields `observedAt` and `reconciledAt`. 

* the `reconciledAt` is updated when application resources are compared with Git and sync/health status got refreshed. 
* the `observedAt` is updated every time when `reconciledAt` is updated and when any "child" application resource (e.g. Pod, ReplicaSet etc) has changed. 

The `observedAt` is changed very frequently and change is required just to notify UI that it should reload resources tree. If Argo CD manages thousands of application then `observedAt` field updates cause thousands of K8S PATCH requests every minute. This slowdown K8S API server and affects all controllers installed in the cluster. 

This PR deprecates `observedAt` - controller no longer updates it. The UI is using `/v1/stream/applications/<app-name>/resource-tree` stream API which is powered by redis [pub-sub](https://redis.io/topics/pubsub).

### CODE REVIEW

**Comment by alexmt** [comment]
PR should resolve or at least improve https://github.com/argoproj/argo-cd/issues/3924 and https://github.com/argoproj/argo-cd/issues/3556 . Argo CD should make significantly less K8S requests and reduce etcd load.

**Review by jannfis — APPROVED** [review]
LGTM, quite awesome fix!

**Comment by darshanime** [comment]
The cache is throwaway in the current implementation, we can delete it and nothing will break. Will that change by this patch?

**Comment by alexmt** [comment]
@darshanime , it is still safe to lose cache. Redis recreates pub-sub channel on the fly. Also `redis-go` automatically re-connect to channel, so UI won't notice if redis restart.

**Comment by alexmt** [comment]
The change significantly improved the performance of the busy Argo CD. Number of K8S requests reduced by 5x ~ 7x times:

image (3)

Avg reconciliation duration changes from 1s~2s to < 0.25s:

image (4)

**Pull request merged**
