### PR TITLE
use updated ingress routing rules in docs

### PR DESCRIPTION
**Pull request by BrianHicks**
the previous ALB example did not set the rules in a way the Kubernetes controller would accept. This updates them for networking.k8s.io/v1

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by joaopaulosr95 — APPROVED** [review]
Thanks @BrianHicks

**Comment by ishitasequeira** [comment]
Thanks @BrianHicks for the PR. Can you add the new ingress routing rules instead of updating it?

**Comment by BrianHicks** [comment]
@ishitasequeira not sure what you mean here. Can you say more?

**Comment by ishitasequeira** [comment]
@BrianHicks It looks like the format of ingress rules has been merged in https://github.com/kubernetes-sigs/aws-load-balancer-controller but not released yet. So, IMO, instead of updating the existing Ingress, it would be wise to add the new Ingress rule separately. WDYT?

**Comment by BrianHicks** [comment]
I'm not sure what would be the best thing to do, actually. We're using the AWS load balancer controller at 2.0 at K8s 1.23 and this change was necessary to get Argo CD working. But, to be honest, it's been long enough since I opened this now that I'm no longer super familiar with the details. I'm happy to leave this open for a while longer if y'all want the code, but I don't think I'll be getting back to moving it forward anytime soon!

**Comment by pasha-codefresh** [comment]
Duplication with https://github.com/argoproj/argo-cd/pull/6842

**Pull request closed without merging**
