### PR TITLE
fix: defaulting to in-cluster is misleading for disconnected clusters

### PR DESCRIPTION
**Pull request by rbreeze**
Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
Maybe this is a dumb question but will it have any impact of not showing the in-cluster cluster correctly?

**Comment by rbreeze** [comment]
Not a dumb question at all, I'll have to double check to make sure that's not the case.

It appears the local cluster is explicitly named `in-cluster` in the API: https://github.com/argoproj/argo-cd/blob/c1d81738d3089958832908e9a2460e28387cc46a/util/db/cluster.go#L28

which would lead me to believe this `name` var would be populated explicitly as well, but I want to test to confirm first.

**Comment by crenshaw-dev** [comment]
@rbreeze did you have a chance to test? Would be happy to review.

**Comment by rbreeze** [comment]
@crenshaw-dev tested! `in-cluster` is explicitly set when the cluster is in fact `in-cluster`.

**Review by alexmt — APPROVED** [review]

**Pull request merged**
