### PR TITLE
fix(ui): User Info blob is too far to the right relative to Applications/Settings/Documentation

### PR DESCRIPTION
**Pull request by shijiadong2022**
Fix issue #11936

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@shijiadong2022 would you mind posting before/after screenshots?

**Comment by shijiadong2022** [comment]
> @shijiadong2022 would you mind posting before/after screenshots?

Before
image
After
after

**Comment by shijiadong2022** [comment]
@crenshaw-dev when you get a chance, can you take a look at the screenshot? The width of user info icon is smaller than other icons so the fix is to make them all the same width.

**Comment by brianwarner** [comment]
Hi @crenshaw-dev, is this ready to be merged? Thanks!

**Review by crenshaw-dev — APPROVED** [review]
Thanks for the bump!

**Comment by crenshaw-dev** [comment]
@shijiadong2022 would you mind rebasing?

**Comment by brianwarner** [comment]
Thanks for having a look!

**Comment by shijiadong2022** [comment]
Thanks @brianwarner  and @crenshaw-dev. Rebased and merged now.

**Pull request merged**
