### PR TITLE
fix(ui): add namespace in badge url for apps-in-any-namespace (#15655)

### LINKED ISSUE #15655: UI: badges url not containing namespace with "Applications in any namespace"
**Describe the bug**

The badge url generated under "**App Details**" view does not include the "**&namespace=**" parameter when using the "**Applications in any namespace**" setup with ArgoCD.

Badge "Not Found" label is shown when app is deployed to other namespace than the default "argocd".

PS. 
Backend part was fixed by issue https://github.com/argoproj/argo-cd/issues/15351.
This added the support for "**&namespace=**" parameter in badge url.

**To Reproduce**

1. Configure "Applications in any namespace":
    - Set ArgoCD tracking method to **annotation+label**.
    - Add RBAC **ClusterRole + ClusterRoleBinding**

2. Deploy application to namespace other than argocd.

   Example: **testnamespace/app1**

    ```
    kind: Application
    metadata:
        name: app1
        namespace: testnamespace
    ```

3. Check the generated badge url in UI under "**App Details**" view.\
It still shows "Not Found" because **&namespace=** parameteri is not included in the url.

**Expected behavior**

Generated working url should be:
```
<argocd_base_url>/api/badge?name=app1&namespace=testnamespace&revision=true
```

**Version**

v2.8.4

### PR DESCRIPTION
**Pull request by asapekia**
closes #15655
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by asapekia** [comment]
@crenshaw-dev please review.

**Comment by asapekia** [comment]
Please let me know if any change is required.

**Comment by asapekia** [comment]
the integration tests passed just by updating the branch. Don't understand why.

**Comment by asapekia** [comment]
@jannfis Please review this PR.

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Comment by sonamkshenoy** [comment]
UI isn't working/loading with the changes made.
Has been fixed by https://github.com/argoproj/argo-cd/pull/16739

**Comment by ishitasequeira** [comment]
closing this as the changes are already fixed in PR https://github.com/argoproj/argo-cd/pull/16739

**Pull request closed without merging**
