### PR TITLE
fix: switch to promauto and fix repo server grpc metrics registration

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

This pr mainly fix the problem that repo server cannot get the grpc server metrics. 
The reason of that is grpc server metrics by default are registered to the default global prometheus registry so that the default gatherer needs to be added for rendering those metrics.  Besides, line https://github.com/argoproj/argo-cd/pull/8245/files#diff-be7b600fde443a933e46d01013410637a279932444ab6e96e2652e8712af88e4R102 has been added.

Besides those changes, other changes are mainly refactoring for the metrics registration. Now metric definitions are initialized as global variables. This is not a good practise so I use `promauto` library to make metrics non-global and register them to the registry at the same time of definition.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by yeya24** [comment]
I don't get why this [test](https://github.com/argoproj/argo-cd/blob/master/controller/metrics/metrics_test.go#L424) could pass on master. If a new metrics registry starts with no apps. Then how does it get argo apps already? Unless the metrics are registered to a global registry 
before and the metrics are kept in this test case. If that's the case then maybe the test itself is wrong.

```go
func TestMetricsReset(t *testing.T) {
	cancel, appLister := newFakeLister()
	defer cancel()
	metricsServ, err := NewMetricsServer("localhost:8082", appLister, appFilter, noOpHealthCheck, []string{})
	assert.NoError(t, err)

	appSyncTotal := `
# HELP argocd_app_sync_total Number of application syncs.
# TYPE argocd_app_sync_total counter
argocd_app_sync_total{dest_server="https://localhost:6443",name="my-app",namespace="argocd",phase="Error",project="important-project"} 1
argocd_app_sync_total{dest_server="https://localhost:6443",name="my-app",namespace="argocd",phase="Failed",project="important-project"} 1
argocd_app_sync_total{dest_server="https://localhost:6443",name="my-app",namespace="argocd",phase="Succeeded",project="important-project"} 2
`

	req, err := http.NewRequest("GET", "/metrics", nil)
	assert.NoError(t, err)
	rr := httptest.NewRecorder()
	metricsServ.Handler.ServeHTTP(rr, req)
	assert.Equal(t, rr.Code, http.StatusOK)
	body := rr.Body.String()
	assertMetricsPrinted(t, appSyncTotal, body)
```

**Comment by jannfis** [comment]
Thanks for the effort you put in this PR, @yeya24 

IMHO, a change like this should have had a broader discussion before. Can you please elaborate a little more on the problem you are trying to fix with it? What do you mean by

> This pr mainly fix the problem that repo server cannot get the grpc server metrics.

Is there a bug issue for that describing the problem further?

**Comment by yeya24** [comment]
> Thanks for the effort you put in this PR, @yeya24 
> 
> 
> 
> IMHO, a change like this should have had a broader discussion before. Can you please elaborate a little more on the problem you are trying to fix with it? What do you mean by
> 
> 
> 
> > This pr mainly fix the problem that repo server cannot get the grpc server metrics.
> 
> 
> 
> Is there a bug issue for that describing the problem further?

Yeah, the grpc server metrics of repo server don't registered properly:
1. it should use grpc reflection to register the grpc methods.
2. The promhttp gatherer should contain the global default gatherer because the grpc server metrics are registered to that global registry.

That's why repo server can't get grpc server metrics in Prometheus. It is a bug.

Other changes are mainly refactoring for metrics related code.

**Comment by yeya24** [comment]
This pr does two things. One is to fix the repo server grpc metrics registration issue and another one is to switch to promauto.
The second change is a little bit large and I decide to fix the first bug first. Will open another pr to fix it.

**Pull request closed without merging**
