### PR TITLE
fix(app): use jsonpatch to check for changes in status field (#15126)

### LINKED ISSUE #15126: Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"autoscaling\"
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

We've switched some applications to the new `valuesObject` syntax, and those apps have gotten "stuck". They go into a refreshing status and never finish

**To Reproduce**

Not clear to us how to reproduce. We deleted the entire `.status` of an affected application and it seemed to start working again. Not left it long enough yet to determine if it'll break again

**Expected behavior**

**Screenshots**

**Version**

```shell
argocd-server: v2.8.0+804d4b8
  BuildDate: 2023-08-07T14:25:33Z
  GitCommit: 804d4b8ca6bc4c2cf02c5c971aa923ec5b8623f0
  GitTreeState: clean
  GoVersion: go1.20.6
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.1.0 2023-06-19T16:58:18Z
  Helm Version: v3.12.1+gf32a527
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```
{"application":"argocd/istio-gateway-iap","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:10Z"}
{"application":"argocd/istio-gateway-public","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:10Z"}
{"application":"argocd/istio-gateway-vpn","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:25Z"}
{"application":"argocd/istio-gateway-public","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:25Z"}
{"application":"argocd/istio-gateway-vpn","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:39Z"}
{"application":"argocd/istio-gateway-public","level":"error","msg":"Error constructing app status patch: unable to find api field in struct RawExtension for the json field \"service\"","time":"2023-08-21T09:01:40Z"}
```

### PR DESCRIPTION
**Pull request by vladfr**
This PR changes the way patches are computed for annotations and status. Because Helm source can have unstructured fields in `helm.valuesObject`, the strategic patching gives unpredictable behaviour. It was never meant to be used without a `struct` ([see Helm Issue](https://github.com/helm/helm/pull/3459)). So we use `jsonpatch` instead. This should yield the same results, and the library is already present in Argo as a dependency.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates? No
* [ ] I've updated documentation as required by this PR. N/A
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Fixes #15126

### CODE REVIEW

**Review by mikebryant — APPROVED** [review]

**Review by jannfis — APPROVED** [review]
LGTM, thanks for fixing this!

I agree that it should move into gitops-engine later on. We probably need to revive lifecycle management between gitops-engine and Argo CD before, or migrate gitops-engine back into Argo CD though.

For now, I'm fine with this code living in the application controller.

Just for clarification and my understanding, this only affects `valuesObject` introduced in 2.8, right?

**Comment by crenshaw-dev** [comment]
@jannfis this fixes a problem with the new field, but it changes how we calculate the app status for every field, so it's pretty darn central.

**Comment by jannfis** [comment]
@crenshaw-dev Yes, I was rather referring to the bug it fixes. So the bug is only in 2.8, and we need to cherry-pick only into that?

**Comment by crenshaw-dev** [comment]
@jannfis yep!

**Comment by jannfis** [comment]
And I would assume that since every test, including end-to-end, pass without changes that the change itself is fine. The only concern might be a performance impact of `CreateTwoWayMergePatch` (which is part of the Kubernetes distribution) and the JSON merge patch we pull in from `github.com/evanphx/json-patch` (and we seem to pull a pretty outdated version).

**Comment by vladfr** [comment]
@jannfis the `helm.valuesObject` field was added in 2.8.0, so I can confirm that the bugfix is meant only for 2.8.x

You have valid points about adding changes to a critical point. I figured it's safe since `jsonpatch` is so widely used, and it's already a dep, and tests pass :) We could definitely do a series of benches to see how performance looks. 

I can dig a bit to see if there's another way to handle this fix. It seems the problem lies in how the object is being stored in `status`, so we can look at the way it's stored; or perhaps transform `valuesObject` before the patching is done (load it up and marshal again). 

PS: I'm out next week, but I can take another approach after I'm back, or if someone else has input until then, feel free.

**Comment by jannfis** [comment]
@vladfr I think a good first step would be to use a recent version of jsonpatch, e.g. `github.com/evanphx/json-patch/v5`

**Comment by Zeratoxx** [comment]
Hi, is this PR still watched? :)

**Comment by vladfr** [comment]
Hi, sorry for my big delay here. 

I've looked for a different way to address this. Unfortunately, it's not really clear how I can change the logic to store the valuesObject field separately; besides which, I'm not really sure what's causing the issue with the quotes.

So I've modified the patching code to: 
 - ignore `valuesObject` when computing the strategic merge patch
 - compute diff on `valuesObject` using `jsonpatch`
 - apply two patches if needed

PS: I'd like to add an e2e test for this, but I'm still struggling a bit with running these locally.

**Comment by vladfr** [comment]
@crenshaw-dev The new code now uses `jsonpatch` only for `valuesObject`. I've managed to arrive at a workable solution, not very happy on how it looks. Pointers appreciated!

PS: Sorry about this, I've mistakenly ran a rebase. We can cut another PR once this is closer to being merged. (i.e. add tests)

**Comment by PaulSonOfLars** [comment]
Thanks for the hard work @vladfr, I think that should work! 

I added some tests on the my branch on #16602. Wasn't sure how you wanted to go forward regarding merging - feel free to cherry pick my changes here if you'd prefer the merge attribution in your name for finding the "fix" itself.

**Comment by vladfr** [comment]
Closing in favor of #16602

**Pull request closed without merging**
