### PR TITLE
Expose Application labels in prometheus metric

### LINKED ISSUE #4997: Add k8s labels to argocd_app_info metric
# Summary

I'm curious what the impact would be to add the labels under `metadata.labels` on an argocd `Application` to the metric `argocd_app_info`.

# Motivation

Most of our resources have a label identifying the owner of that resource. We'd like to take that owner label in order to handle routing alerts for a given application.

# Proposal

How do you think this should be implemented?
Not really sure, but was also pondering whether it should be optional and the default should be off in case it blows up the cardinality (not an expert in this area.)

### PR DESCRIPTION
**Pull request by leoluz**
Fixes https://github.com/argoproj/argo-cd/issues/4997

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM.

Please run `make clidocsgen` to re-generate CLI commands documentation and it is good to go.

**Review by alexmt — COMMENTED** [review]
Can you please document the flag and new metric in https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/metrics.md

**Comment by leoluz** [comment]
@alexmt documentation added

**Review by alexmt — APPROVED** [review]
Looks awesome! Thanks for updating list of metrics in the documentation.

**Pull request merged**
