### PR TITLE
fix: retain count and order of revisions for multi source apps (#14108)

### LINKED ISSUE #14108: Mix up of targetRevisions in multi source app starting in 2.7.5
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We experience that in multi source apps starting in 2.7.5, the targetRevision is mixed up across the sources:

Example multisource: 

```
sources:
  - repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.17.2
    helm:
      releaseName: istio-base
    chart: base
  - repoURL: 'https://istio-release.storage.googleapis.com/charts'
    targetRevision: 1.17.2
    helm:
      releaseName: istio-istiod
      values: |
        pilot:
          autoscaleMin: 2
    chart: istiod
  - repoURL: 'https://cert-manager.github.io/aws-privateca-issuer'
    targetRevision: v1.2.4
```

we see the following error in the UI:    

```

rpc error: code = Unknown desc = `helm pull --destination /tmp/3bbb499c-1875-4dc6-b36d-10c6465141ce --version v1.2.4 --repo https://istio-release.storage.googleapis.com/charts istiod` failed exit status 1: Error: chart "istiod" version "v1.2.4" not found in https://istio-release.storage.googleapis.com/charts repository
```
    
 out of completeness and for further searches an alternative error looks like that   
    
 ```
 rpc error: code = Unknown desc = invalid revision 'ff2ca7291c435c934782189b18d775697ec9f148': improper constraint: ff2ca7291c435c934782189b18d775697ec9f148
 ```

This also results in endless loops of apps in the "Unknown" state.

**To Reproduce**

**Expected behavior**

Should not mix up the targetRevisions across the sources

**Screenshots**

Bildschirmfoto 2023-06-17 um 18 11 41

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

We didn't experience that error in 2.7.4. Downgrading fixed the issue.

### LINKED ISSUE #14109: Helm values file from external Git repository source and revision missing in Application sourceTypes and revisions
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

We experience that in multisource apps starting in v2.7.5, when using helm values file from external Git repository, the source revision is missing in the application revisions.

**To Reproduce**

Example multisource:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: prometheus
    helm:
      valueFiles:
      - $values/values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.7.1
  - ref: values
    repoURL: https://github.com/RafaelBroseghini/temp.git
    targetRevision: HEAD
  - chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
```

when inspecting the application, we get:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"guestbook","namespace":"argocd"},"spec":{"destination":{"namespace":"default","server":"https://kubernetes.default.svc"},"project":"default","sources":[{"chart":"prometheus","helm":{"valueFiles":["$values/values.yaml"]},"repoURL":"https://prometheus-community.github.io/helm-charts","targetRevision":"15.7.1"},{"ref":"values","repoURL":"https://github.com/RafaelBroseghini/temp.git","targetRevision":"HEAD"},{"chart":"elasticsearch","repoURL":"https://helm.elastic.co","targetRevision":"8.5.1"}]}}
  creationTimestamp: "2023-06-17T20:40:54Z"
  generation: 3
  name: guestbook
  namespace: argocd
  resourceVersion: "8893"
  uid: 926cff44-1759-4590-b897-6863d23f19b6
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - chart: prometheus
    helm:
      valueFiles:
      - $values/values.yaml
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 15.7.1
  - ref: values
    repoURL: https://github.com/RafaelBroseghini/temp.git
    targetRevision: HEAD
  - chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
status:
  health:
    status: Progressing
  reconciledAt: "2023-06-17T20:40:54Z"
  resources:
 <snip>
  sourceTypes:
  - Helm
  - Helm
  summary:
    images:
    - docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    - jimmidyson/configmap-reload:v0.5.0
    - k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.3.0
    - prom/pushgateway:v1.4.2
    - quay.io/prometheus/alertmanager:v0.23.0
    - quay.io/prometheus/node-exporter:v1.3.0
    - quay.io/prometheus/prometheus:v2.34.0
  sync:
    comparedTo:
      destination:
        namespace: default
        server: https://kubernetes.default.svc
      sources:
      - chart: prometheus
        helm:
          valueFiles:
          - $values/values.yaml
        repoURL: https://prometheus-community.github.io/helm-charts
        targetRevision: 15.7.1
      - ref: values
        repoURL: https://github.com/RafaelBroseghini/temp.git
        targetRevision: HEAD
      - chart: elasticsearch
        repoURL: https://helm.elastic.co
        targetRevision: 8.5.1
    revisions:
    - 15.7.1
    - 8.5.1
    status: Synced

```

**Expected behavior**

I would expect the application revisions to return:

```yaml
revisions:
  - 15.7.1
  - 627613d1906e57984e0443049e48f5b789852bdf
  - 8.5.1
```

**Screenshots**

**Version**

```shell
Paste the output from `argocd version` here.

argocd: v2.7.5+a2430af
  BuildDate: 2023-06-16T15:00:03Z
  GitCommit: a2430af1c356b283e5e3fc5bde1f5e2b5199f258
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.7.5+a2430af
  BuildDate: 2023-06-16T15:00:03Z
  GitCommit: a2430af1c356b283e5e3fc5bde1f5e2b5199f258
  GitTreeState: clean
  GoVersion: go1.19.10
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.11.2+g912ebc1
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by woehrl01**
Fixes #14108
Fixes #14109

Supersedes #14081

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by cjc7373 — APPROVED** [review]

**Comment by ishitasequeira** [comment]
One thing to note is that, for the repo used just as a reference to values files (e.g. In below example, `ref-repo`), we do not generate any manifests and thus do not end up printing revision for the same. This leads to not mentioning the revision of the referenced repository used for external values files.

See below example,

```
spec:
  sources:
  - helm:
      valueFiles:
      - $values_test/values.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  - ref: values_test                          <--------------------------------- ref-Repo
    repoURL: https://github.com/ishitasequeira/values-test.git
    targetRevision: HEAD
status:
    revisions:
    - 53e28ff20cc530b9ada2173fbbd64d48338583ba
```
Also, if there are more than one repositories, it is difficult to associate which revision belongs to which repository. (below example)

```
spec:
  sources:
  - helm:
      valueFiles:
      - $values_test/values.yaml
    path: helm-guestbook
    repoURL: https://github.com/argoproj/argocd-example-apps.git
    targetRevision: HEAD
  - ref: values_test
    repoURL: https://github.com/ishitasequeira/values-test.git
    targetRevision: HEAD
  - path: guestbook
    repoURL: https://github.com/ishitasequeira/argocd-example-apps.git
    targetRevision: HEAD
status:
      revisions:
      - 53e28ff20cc530b9ada2173fbbd64d48338583ba
      - 86f65c1eacddba892814445f88631101b55f4bcf
```

In my opinion, it was okay to show `revision` directly earlier when we had only one source. But with multiple sources, we should add source to the revision as well (only for status.revisions). Something like below:

```
status:
      revisions:
      - repoUrl: https://github.com/argoproj/argocd-example-apps.git
        revision: 53e28ff20cc530b9ada2173fbbd64d48338583ba
      - repoUrl: https://github.com/ishitasequeira/argocd-example-apps.git
        revision: 86f65c1eacddba892814445f88631101b55f4bcf
```

Let me know what do you think.

**Comment by woehrl01** [comment]
@ishitasequeira there is a place in the code with skips the revision if there is no manifest, I suggest removing that case for the revision output. Then the revisions always align up by index.

**Comment by woehrl01** [comment]
I just pushed the changes. This will also directly fix a recurring cache invalidation bug, where the results would never be cached in the mentioned case of @ishitasequeira , becase the length of the array will never be the same.

https://github.com/argoproj/argo-cd/blob/b392917e8defa94ac349cb6af45b28b8932b3bdf/controller/state.go#L532-L536

**Comment by crenshaw-dev** [comment]
The second revision is appearing as an empty string for me. 

image

**Comment by woehrl01** [comment]
@ishitasequeira I see. But we still have to process this method to return the resolving of the ref (e.g. HEAD) to commit hash, don't we?

**Comment by woehrl01** [comment]
@ishitasequeira after looking at the code, and getting a bit familiar with it, my suggestion would be to slightly modify this part:

https://github.com/argoproj/argo-cd/blob/b392917e8defa94ac349cb6af45b28b8932b3bdf/reposerver/repository/repository.go#L512-L528

So that it has a new argument to not generate a manifest, but it returns the correct "ManifestResponse", instead of this:

https://github.com/argoproj/argo-cd/blob/b392917e8defa94ac349cb6af45b28b8932b3bdf/reposerver/repository/repository.go#L546-L548

Thoughts?

**Comment by woehrl01** [comment]
like this https://github.com/argoproj/argo-cd/commit/93b027366e9d7868d502872f5aeb5ad806ad0535  @ishitasequeira CC: @crenshaw-dev 

Created that in my fork, to get your opinion.

**Comment by ishitasequeira** [comment]
I think that should work.. Thanks @woehrl01 !!

**Comment by crenshaw-dev** [comment]
@woehrl01 how do you feel about this slightly simplified version? https://github.com/woehrl01/argo-cd/pull/1

**Comment by woehrl01** [comment]
looks great I'll pick that

**Comment by crenshaw-dev** [comment]
One downside of my change is that we'll be running some unnecessary manifest-generation-related operations for ref sources (e.g. checking for out-of-bounds symlinks) which could be skipped. But for now I think the performance hit is worth it for a relatively simple fix.

**Comment by woehrl01** [comment]
@crenshaw-dev we also have to handle https://github.com/argoproj/argo-cd/blob/41dc06d90318b8b01978a66cefc8ebb1567f8fe2/reposerver/repository/repository.go#L1984

Do you have an idea what would be the best behaviour here? Should we just duplicate the check and return `nil`?

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by crenshaw-dev** [comment]
@woehrl01 I don't think the UI currently hits that endpoint for multi-source apps, precisely because it's not equipped to handle stuff like the ref-only sources. I think it's safe to ignore until someone starts working on multi-source UI support.

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Fixes will be in 2.6.11 and 2.7.6.

**Pull request merged**
