### PR TITLE
fix: sync repository certificates UI with other pages(#4609)

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Sync the Repository Certificates pages(ADD SSH KNOWN HOST, ADD TLS CERTIFICATE) with other argo ui pages as mentioned in #4609 

After changes.
Screenshot 2020-12-04 at 2 18 17 AM
Screenshot 2020-12-04 at 2 18 06 AM

Signed-off - aveerama@redhat.com

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]
LGTM

**Comment by rbreeze** [comment]
Can you sign the DCO so we can merge this?

**Comment by iam-veeramalla** [comment]
> Can you sign the DCO so we can merge this?

Sure, I will do that.

**Comment by iam-veeramalla** [comment]
> Can you sign the DCO so we can merge this?

@rbreeze  Signed the DCO. You can merge the changes now 👍

**Comment by iam-veeramalla** [comment]
@rbreeze, @jessesuen, @alexmt  Can you merge the PR?

**Pull request merged**
