### PR TITLE
chore: update gitops engine for force sync option (#5882)

### LINKED ISSUE #5882: A way to cause resources to be deleted and recreated
# Summary

There should be a way to specify that resources should be deleted and recreated on a change to all/part of the spec

# Motivation

Some resources can't be changed in place, e.g.
```
        Group:       iam.cnrm.cloud.google.com
        Hook Phase:  Failed
        Kind:        IAMPolicyMember
        Message:     admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: the IAMPolicyMember's spec is immutable
        Name:       key-access
        Namespace:   default
        Status:      SyncFailed
        Sync Phase:  Sync
        Version:     v1beta1
```

# Proposal

Add an option to the `argocd.argoproj.io/sync-options` annotation for this behaviour?

### LINKED ISSUE #7459: enhancement: annotation for Force Syncing
i would like to be able to set this on specific manifests rather than everywhere

### Discussed in https://github.com/argoproj/argo-cd/discussions/5172

<div type='discussions-op-text'>

<sup>Originally posted by **rumstead** January  4, 2021</sup>
Hi all! I want to be able to automatically “kubectl apply --force” my Kubernetes manifests so I don't have to force sync via the UI when a label or something immutable changes. I saw the [SyncOptions](https://github.com/argoproj/argo-cd/blob/v1.8.1/pkg/apis/application/v1alpha1/types.go#L590) and tried adding “--force”, “force=true”, and “Force=true” but none seemed to work. I then stumbled across [SyncStrategy](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L735). I was able to set this on the Application Resource and it seems to work but I want to make sure this is the best way to do it.</div>

### LINKED ISSUE #9163: New Sync Option DeleteResourceBeforeCreation
# Summary

The proposal introduces a new sync option to control resource deletion before creation

# Motivation

Working with K8 jobs can be a nightmare especially when updating the job command due to its immutable nature. When using jobs as resource hooks ArgoCD already supports the great feature of different hook deletion policies. In some cases, it might not be possible to run jobs as hooks and must be managed during the normal sync lifecycle. To ease this as it is already possible with hooks, we propose to introduce a new sync option `DeleteResourceBeforeCreation` that can be applied to all resources during the normal sync process. 

We also considered using `ttlSecondsAfterFinished` to delete the job after a certain amount of time after job completion. But with active self-healing, ArgoCD will automatically recreate the deleted job, which does not work for us. 

Furthermore, we also investigated the usage of sync option `argocd.argoproj.io/sync-options: Replace=true`, but doesn’t work since updating a job with replace only works when run with `--force`, which is currently only supported via the UI. 

# Proposal

Introduce a new sync option `argocd.argoproj.io/sync-options: DeleteResourceBeforeCreation` to control resource deletion. 

```
apiVersion: batch/v1
kind: Job
metadata:  
  annotations:
    argocd.argoproj.io/sync-options: DeleteResourceBeforeCreation=true
...
```

# Releated Issues
This enhancement is related to #5882

### PR DESCRIPTION
**Pull request by kkk777-7**
Update gitops-engine for enable force sync option. Also, add e2e and docs.
Ref: https://github.com/argoproj/gitops-engine/pull/560

Related Issue number  
Closes #5882
Closes #7459
Closes #9163 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by kkk777-7** [comment]
@pasha-codefresh , Could you please review  when you have some time?

**Comment by pasha-codefresh** [comment]
@CodiumAI-Agent /review

**Review by pasha-codefresh — CHANGES_REQUESTED** [review]

**Comment by pasha-codefresh** [comment]
LGTM, just small comment @kkk777-7

**Review by pasha-codefresh — APPROVED** [review]

**Comment by tybook** [comment]
Thank you for implementing this! Could we please get this set up for release as part of v2.10.8? Not familiar with the release process for this repo.

**Comment by tybook** [comment]
Gentle nudge :) Could this be included in a patch release soon? This is the last piece needed for ArgoCD to handle jobs for us well.

**Comment by eitan-papaya** [comment]
Same, looks like it didn't make it into the 2.11.0 release, was really waiting for this change. Any status update on when should we expect this?

**Comment by pasha-codefresh** [comment]
We need cherry-pick it the, let me see if i can help here @eitan-papaya

**Comment by eitan-papaya** [comment]
@pasha-codefresh 
For me 2.10+2.11 is great, don't need for 2.8/2.9. Thank you very much!  :)

**Comment by digitalyuki** [comment]
@pasha-codefresh , I just found this thread, is there any chance you could also cherry-pick it into the 2.9 release? I've seen your 2 PRs to the 2.10 and 2.11 release branches, it looks straightforward and I could give it a shot if you prefer, but as a non-contributor I suspect it would take me longer to get it all approved / merged in, etc.

**Comment by pasha-codefresh** [comment]
@digitalyuki could you please just cherry-pick it? i will make sure that it is reviewed and merged. Let me know if you meed any issues

**Comment by digitalyuki** [comment]
@pasha-codefresh here's my attempt to cherry-pick it to for 2.9... Not sure why it failed the CI but committing to this repo is new for me.
https://github.com/argoproj/argo-cd/pull/18259

**Comment by eitan-papaya** [comment]
@pasha-codefresh Thanks again for the quick response. When could we expect a release including this (either 2.10/2.11)? I saw [in the docs](https://argo-cd.readthedocs.io/en/stable/developer-guide/release-process-and-cadence/):
> Argo CD patch releases occur on an as-needed basis.
So wanted to understand better if it's expected in the upcoming days or that it can happen sooner given a request.

**Comment by pasha-codefresh** [comment]
I will do release during next week, approximately Tuesday

**Comment by ishaan-tf** [comment]
@pasha-codefresh Wanted to know, if we included this in a patch release for 2.10/2.11?

**Pull request merged**
