### PR TITLE
feat: add examples to --help output for admin.go file

### PR DESCRIPTION
**Pull request by akagami-harsh**
- added exmples to admin.go
- updated the docs
- Resolves one tasks in #15690 
- [x] https://github.com/argoproj/argo-cd/tree/a93477277/cmd/argocd/commands/admin/admin.go#L44

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
LGTM!

**Comment by ChristianCiach** [comment]
I am so confused by this PR... The examples advertise a bunch of commands that just don't exists.

For example:

```
argocd admin cluster list
```

The command `argocd admin cluster` has no subcommand `list`.

Similarly, there is no `argocd admin cluster add`, `argocd admin cluster remove`.

There isn't even a `argocd admin project` to call `argocd admin project list` on.

The same is true for many, *many* other examples added to `argocd admin`. 

I also cannot find any references to the mentioned commands inside the source code.

I am using this version of the CLI, but as far as I can see, the commands mentioned in the examples of `argocd admin` didn't exist for a very long time (possibly ever):

```
$ argocd version
argocd: v2.10.7+b060053.dirty
  BuildDate: 2024-04-15T12:31:44Z
  GitCommit: b060053b099b4c81c1e635839a309c9c8c1863e9
  GitTreeState: dirty
  GoVersion: go1.22.2
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.10.7+b060053
  BuildDate: 2024-04-15T08:45:08Z
  GitCommit: b060053b099b4c81c1e635839a309c9c8c1863e9
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.14.3+gf03cc04
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Comment by crenshaw-dev** [comment]
@ChristianCiach I'm guessing this was just ChatGPT garbage then. I'll clean it up.

**Comment by crenshaw-dev** [comment]
@akagami-harsh lmk if I'm wrong, but otherwise... yikes.

**Comment by crenshaw-dev** [comment]
https://github.com/argoproj/argo-cd/pull/17924

**Comment by akagami-harsh** [comment]
@crenshaw-dev, omg i am so sorry 😔, i should have tested it before making a PR, deeply regret it now 😔. again i am so sowwy for the trouble i caused @ChristianCiach. I'm working on fixing the problem and will submit a follow-up PR as soon as possible. In the meantime, please let me know if there's anything I can do to help minimize any disruption this may have caused.

**Comment by crenshaw-dev** [comment]
@akagami-harsh no worries, we cleaned it up. If you'd like to submit a PR adding docs for `argocd admin` commands that exist, I'd happily review.

**Pull request merged**
