### PR TITLE
fix: ui add tooltips on repository urls and names (#9868)

### PR DESCRIPTION
**Pull request by xieyanke**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by saumeya — COMMENTED** [review]
Hi @xieyanke LGTM, one small comment this adds a tooltip to all the repo names and urls, not just the long one. Is that the required behavior?

**Comment by xieyanke** [comment]
Hi @saumeya , I only want to add tooltips on all repository names and urls, my comment is inaccurate, and I have fix it.

ps: I don't think it is necessary to hide tooltips  when repository names or urls isn't too long.

**Comment by saumeya** [comment]
Hi @xieyanke , could you remove the extra commits you have added in this. Also could you sign the DCO based on the instructions in the failing tests. 
Thanks

**Comment by xieyanke** [comment]
Hi, @saumeya Due to my mistake, this PR was closed, I re-created a new one and removed the extra commits, Please re-review it, Thank You ^_^

#10108

**Pull request closed without merging**
