### PR TITLE
fix: UI Error caused by missing RBAC Permission

### LINKED ISSUE #10916: UI Error caused by missing RBAC Permission
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Opening / showing a resource within the application view to which the Argo CD server has no access to leads to the UI error and its stack trace being shown.

**To Reproduce**

1. Create / modify the service account used for the Argo CD server so that it cannot read a certain resource kind of a resource managed by Argo CD.
1. Open / show that resource in the application view.

**Expected behavior**

This case should be handled properly by showing a warning / error message without the UI crashing.

**Screenshots**

image

**Version**

```yaml
argocd: v2.4.12+41f54aa
  BuildDate: 2022-09-16T00:45:01Z
  GitCommit: 41f54aa556f3ffb3fa4cf93d784fb7d30c15041c
  GitTreeState: clean
  GoVersion: go1.18.6
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Chrome console:
```
GET https://<hidden>/api/v1/applications/azure-cli/resource?name=azure-cli-bcbbf67f8&namespace=demo-tenant-project1&resourceName=azure-cli-bcbbf67f8&version=v1&kind=ReplicaSet&group=apps 403 (Forbidden)

TypeError: Cannot read properties of null (reading 'kind')
    at p (main.d73b393b850229804000.js:2:1474214)
    at Object.children (main.d73b393b850229804000.js:2:1477768)
    at t.render (main.d73b393b850229804000.js:2:1117363)
    at Hs (main.d73b393b850229804000.js:2:805069)
    at js (main.d73b393b850229804000.js:2:804864)
    at ya (main.d73b393b850229804000.js:2:840345)
    at pl (main.d73b393b850229804000.js:2:831820)
    at dl (main.d73b393b850229804000.js:2:831745)
    at il (main.d73b393b850229804000.js:2:828775)
    at main.d73b393b850229804000.js:2:780554
```

Argo CD server error message in above 403 response:
```
error getting resource: replicasets.apps "azure-cli-bcbbf67f8" is forbidden: User "system:serviceaccount:demo-tenant-argocd:argocd-server" cannot get resource "replicasets" in API group "apps" in the namespace "demo-tenant-project1"
```

Chrome console (With UI hosted by webpack-dev-server, which proxies Argo CD API requests to the Argo CD server where the error occures):
```
GET http://localhost:4000/api/v1/applications/azure-cli/resource?name=azure-cli-bcbbf67f8&namespace=demo-tenant-project1&resourceName=azure-cli-bcbbf67f8&version=v1&kind=ReplicaSet&group=apps 403 (Forbidden)

Uncaught TypeError: Cannot read properties of null (reading 'kind')
    at getResourceTabs (resource-details.tsx?ee2e:115:83)
    at Object.eval [as children] (resource-details.tsx?ee2e:280:69)
    at DataLoader2.render (data-loader.tsx?58f1:102:31)
    at finishClassComponent (react-dom.development.js?61bb:17160:31)
    at updateClassComponent (react-dom.development.js?61bb:17110:24)
    at beginWork (react-dom.development.js?61bb:18620:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js?61bb:188:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237:16)
    at invokeGuardedCallback (react-dom.development.js?61bb:292:31)
    at beginWork$1 (react-dom.development.js?61bb:23203:7)

The above error occurred in the <DataLoader2> component:
    in DataLoader2 (created by ResourceDetails)
    in div (created by ResourceDetails)
    in ResourceDetails (created by DataLoader2)
    in div (created by RenderSlidingPanel)
    in div (created by RenderSlidingPanel)
    in div (created by RenderSlidingPanel)
    in RenderSlidingPanel (created by SlidingPanel)
    in KeybindingProvider (created by SlidingPanel)
    in SlidingPanel (created by DataLoader2)
    in div (created by Page)
    in div (created by Page)
    in Page (created by Page)
    in div (created by Page)
    in Page (created by DataLoader2)
    in div (created by DataLoader2)
    in DataLoader2 (created by ObservableQuery2)
    in ObservableQuery2 (created by ApplicationDetails2)
    in ApplicationDetails2 (created by Route2)
    in Route2 (created by ApplicationsContainer)
    in Switch2 (created by ApplicationsContainer)
    in ApplicationsContainer (created by Route2)
    in DataLoader2 (created by Banner)
    in Banner (created by Route2)
    in div (created by Layout)
    in Layout (created by Route2)
    in Route2 (created by App2)
    in Switch2 (created by App2)
    in Router2 (created by App2)
    in App2

React will try to recreate this component tree from scratch using the error boundary you provided, App2.
```

**Affected code**

https://github.com/argoproj/argo-cd/blob/v2.4.12/ui/src/app/applications/components/resource-details/resource-details.tsx#L100

**Related issues**
- #10647

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes https://github.com/argoproj/argo-cd/issues/10916

### CODE REVIEW

**Review by crenshaw-dev — COMMENTED** [review]
@alexmt I was unable to reproduce the error. https://github.com/argoproj/argo-cd/issues/10916#issuecomment-1282937587

Any suggestions?

**Review by rbreeze — APPROVED** [review]
LGTM

**Review by todaywasawesome — APPROVED** [review]
I didn't check for the UI crash but adding the `?` is safe and better so 👍

**Comment by pasha-codefresh** [comment]
@crenshaw-dev also didnt reproduce it, but looks like it is pretty safe change, could you please check it one more time?

**Review by pasha-codefresh — APPROVED** [review]

**Pull request merged**
