### PR TITLE
Adds CLI support for adding and removing groups from project roles. C…

### PR DESCRIPTION
**Pull request by alexec**
…loses #1851

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by alexec** [comment]
@alexmt I'm thinking of moving all of `util.go` to `types.go` and changing the functions to be recievers on `*AppProject` - thoughts?

**Comment by alexec** [comment]
@alexmt I've added a new commit that is a lift-and-shift of `util/project` into `types.go` - can you re-review please?

**Comment by alexmt** [comment]
Nice refactoring. LGTM!

**Pull request merged**
