### PR TITLE
feat: add scrollbar to live manifest

### LINKED ISSUE #10457: When modifying the live manifest, a save button should be visible at the top of the page.
# Summary
When argocd user edits the resource live manifest too frequently on the ui, the user needs to scroll up to save the changes. The save button should be accessible w/o having to scroll  up

# Motivation

Normally save buttons should be fixed at the top of documents that are not scrolled off the screen when one scrolls their resource manifest.

# Proposal

How do you think this should be implemented?
Add a scrollbar in the live manifest yaml editor

### PR DESCRIPTION
**Pull request by ashutosh16**
Signed-off-by: Ashutosh <mail.ashutosh8@gmail.com>
fix : https://github.com/argoproj/argo-cd/issues/10457
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by ashutosh16** [comment]
vertical_scrollbar_in_livemanifest

**Comment by ashutosh16** [comment]
@keithchong  Can you review this PR?

**Comment by ashutosh16** [comment]
@rbreeze  Would you be able to review and provide your feedback?

**Review by rbreeze — APPROVED** [review]
I think this change is good, but it doesn't address the issue linked (https://github.com/argoproj/argo-cd/issues/9928). Can you remove it from the PR description so the issue doesn't get closed?

**Comment by ashutosh16** [comment]
@rbreeze  thanks for reviewing, I update the description with the correct issue.
fix #10457

**Pull request merged**
