### PR TITLE
feat: support extra attributes for opentelemetry

### LINKED ISSUE #1570: Application controller is unable to delete self-referenced app
**Describe the bug**
It is impossible to delete self-referenced application. 

**To Reproduce**
1. Create and deploy an application which deploys itself
2. Try to delete it
3. App deletion never completes

### LINKED ISSUE #15070: Add extra otlp attrs for OpenTlemetry tracing
# Summary

ArgoCD now support OpenTlemetry with grpc by parameter `otlp-address`. But users cannot set extra attributes. We propose adding a param `otlp-attrs` to support it.

Because some users may have some requirements, such as: add token, carry cluster information, etc.

# Motivation

Please give examples of your use case, e.g. when would you use this.

```
argocd-application-controller --otlp-address report-otlp.example.com --otlp-attrs "token:fake,cluster:test"
```

# Proposal

With this proposal,  need do:
- Add command line execution parameters to input otlp attributes, such as `otlp-attrs`
-  Function `trace.InitTracer()` add `otlpAttrs([]string)` param support.

### PR DESCRIPTION
**Pull request by penglongli**
Fixes #15070  

This pr will add `otlp-attrs` parameter support to input extra attributes for opentelemetry. 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks for your PR! The CI is failing. Please run `make clidocsgen` to regenerate CLI documentation and commit those changes to the PR after you changed command line arguments, descriptions, etc.

**Comment by penglongli** [comment]
> Thanks for your PR! The CI is failing. Please run `make clidocsgen` to regenerate CLI documentation and commit those changes to the PR after you changed command line arguments, descriptions, etc.

Hi @jannfis , i have fixed

**Comment by jannfis** [comment]
Hi @penglongli, one or more of your commits are not signed off and thus, DCO is failing. A passing DCO is a strict requirement for a merge. Can you PTAL and fix this?

**Comment by penglongli** [comment]
@jannfis fixed

**Review by jannfis — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
