### PR TITLE
docs: Added detail on how to use the caData field with Okta SAML #3352

### PR DESCRIPTION
**Pull request by saranicole**
Checklist:

* [x] I've created an [enhancement proposal #3352 ](https://github.com/argoproj/argo-cd/issues/3352) and am waiting on the community discussion
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by saranicole** [comment]
I'm not sure why the CLA shows as not signed, I've tried to sign it and it's not completing for me

Screen Shot 2020-04-03 at 10 09 12 AM

**Comment by jannfis** [comment]
Hi @saranicole, thanks a lot for your PR! I think the CLA failure is because your commit was done with a different e-mail address than used for the GitHub. You have to ammend the Git commit using your GH registered e-mail address. If you need help with fixing that, let us know.

**Comment by saranicole** [comment]
Got it - done!  Just waiting on all the CI to do its thing now ...

**Review by jannfis — APPROVED** [review]
Thank you!

**Pull request merged**
