### PR TITLE
fix: ssh repo url match failed when webhook gitlab http custom port

### PR DESCRIPTION
**Pull request by lonfme**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

When the gitlab http address has a defined port number, such as http://example.com:8080, the webhook ssh repo will fail to match. This fixed it for me and should not affect anyone who already had it working.

### CODE REVIEW

**Comment by wtam2018** [comment]
@lonfme  It looks like a good fix as the regexp tries to match any port number with.`(:[0-9]+|)`.   Can you please add some description to describe the issue?   Also, is it possible to provide a unit test?   Thanks.

**Comment by lonfme** [comment]
> @lonfme It looks like a good fix as the regexp tries to match any port number with.`(:[0-9]+|)`. Can you please add some description to describe the issue? Also, is it possible to provide a unit test? Thanks.

When the github http address has a defined port number, such as http://example.com:8080/group/name, and using ssh type repo such as ssh://git@example.com/group/name.git, webhook The ssh repo will fail to match, because the regular use of Host example.com:8080 causes the match to fail. We should only use Hostname to filter out the port number when generating the regularity. urlObj.Hostname() helps us achieve this very well.

**Comment by wtam2018** [comment]
@lonfme  Thanks for test case.   The proposed fix will basically ignore port numbers in the regexp matching.  Suppose webURL in the webhook event is `https://example.com:8080/foo/bar.git`  The new regexp built from webURL will match app repoURL `https://example.com:7777/foo/bar.git`.  I am not sure it is an expected behaviour.    Can you please file an issue?

**Comment by lonfme** [comment]
@wtam2018 You are right. My match app repoURL is ssh://git@example.com/foo/bar.git, but the truth is similar.

**Review by jessesuen — COMMENTED** [review]
Could we have a unit test for this?

**Comment by lonfme** [comment]
@jessesuen Sorry, my coding skills are limited and I cannot write unit tests.

**Comment by wtam2018** [comment]
@lonfme  Is it possible to create an issue to include steps to reproduce it?

**Comment by lonfme** [comment]
@wtam2018 Sorry, the above description should be gitlab instead of github.
The steps to reproduce are:
* gitlab web url is `http://example.com:8080/foo/bar`
* argo-cd config repo is `ssh://git@example.com:foo/bar.git`
* gitlab repo config settings push event webhook

argocd-server logs:

```
time="2020-10-14T05:30:45Z" level=info msg="Received push event repo: http://example.com:8080/foo/bar, revision: master, touchedHead: true"
time="2020-10-14T05:30:45Z" level=debug msg="ssh://git@example.com:foo/bar.git does not match"
```

**Review by alexmt — APPROVED** [review]
Tested change manually. It does fix the error.  thank you @lonfme !

Will send PR with the test change after merging this PR.

**Pull request merged**
