### PR TITLE
refactor: add indexes to secret informers to speedup settings parsing

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

PR improves settings parsing - introduces 3 indexes to secret informer: repo by project, cluster by project, cluster by server URL. The indexes allow the controller to avoid iterating an in-memory list of secrets which reduces CPU usage by 40%~50% on an instance which have ~400 secrets and 3k apps.

Additionally PR fixes a security issue: shared credentials are not supported but project repositories still "inherit" credentials configured in shared credentials. This is incorrect since the user can use project scoped repo to "steal" shared credentials.

### CODE REVIEW

**Review by mayzhang2000 — APPROVED** [review]
LGTM

**Comment by yeya24** [comment]
Hello @alexmt, does this pr help with https://github.com/argoproj/argo-cd/issues/7531?

**Comment by alexmt** [comment]
@yeya24 , yes - it addresses this issue as well as some other performance bottlenecks. 

I was fixing it in rush, since we also run into it in production and forgot to notify you. BTW I discovered some additional bottlenecks using your pprof endpoints - thank you!

**Comment by yeya24** [comment]
I am still seeing a lot of time spent on this function. Does ArgoCD still serialize secret after this pr has been merged?
image

**Comment by alexmt** [comment]
It might be that I missed something and we still have a method in controller that doesn't use the index to access the cluster. 
@yeya24 , can you please share full stack trace so I can see which method calls `secretToCluster`?

**Comment by yeya24** [comment]
Hi @alexmt, that's the profile https://share.polarsignals.com/fbdddca/. You can switch to `Icicle graph` if you need to view the flamegraph.

**Comment by alexmt** [comment]
Thank you @yeya24 ! Yes, there is an issue I did not notice. It affects applications that use cluster name instead of URL. The fix is trivial - I need to introduce one more index (by cluster name). Working on fix. Will cherry-pick it into v2.2

**Pull request merged**
