### PR TITLE
Add missing labels to configmap/secret in documentation

### PR DESCRIPTION
**Pull request by alexmt**

### CODE REVIEW

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Please don't forget to `git checkout master && mkdocs gh-deploy`

**Comment by eric-isakson** [comment]
I would suggest the following changes to declative-setup.md as well.

```
Index: docs/operator-manual/declarative-setup.md
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- docs/operator-manual/declarative-setup.md	(revision be56670519b86996e5c3431b32937b819c196f23)
+++ docs/operator-manual/declarative-setup.md	(date 1566411995520)
@@ -134,6 +134,9 @@
 metadata:
   name: argocd-cm
   namespace: argocd
+  labels:
+    app.kubernetes.io/name: argocd-cm
+    app.kubernetes.io/part-of: argocd
 data:
   repositories: |
     - url: https://github.com/argoproj/my-private-repository
@@ -153,6 +156,9 @@
 metadata:
   name: argocd-cm
   namespace: argocd
+  labels:
+    app.kubernetes.io/name: argocd-cm
+    app.kubernetes.io/part-of: argocd
 data:
   repositories: |
     - url: git@github.com:argoproj/my-private-repository
@@ -177,6 +183,9 @@
 metadata:
   name: argocd-cm
   namespace: argocd
+  labels:
+    app.kubernetes.io/name: argocd-cm
+    app.kubernetes.io/part-of: argocd
 data:
   repositories: |
     - url: https://github.com/argoproj/private-repo
@@ -416,6 +425,9 @@
 metadata:
   name: argocd-cm
   namespace: argocd
+  labels:
+    app.kubernetes.io/name: argocd-cm
+    app.kubernetes.io/part-of: argocd
 data:
   helm.repositories: |
     - url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts

```

**Comment by eric-isakson** [comment]
One more spot here:
./docs/user-guide/kustomize.md:29:  name: argocd-cm
./docs/user-guide/kustomize.md-30-  namespace: argocd
./docs/user-guide/kustomize.md-31-data:
./docs/user-guide/kustomize.md-32-    kustomize.buildOptions: --load_restrictor none

**Comment by alexmt** [comment]
👍 https://github.com/argoproj/argo-cd/pull/2189

**Pull request merged**
