### PR TITLE
feat: add ability to auto label clusters from k8s clusterinfo

### PR DESCRIPTION
**Pull request by blakepettersson**
This gives the ability to automatically label cluster secrets on a cluster-by-cluster basis. ~If `enableClusterInfoLabels` is set~ the label `argocd.argoproj.io/auto-label-cluster-info` is set to `true` on a cluster secret, the controller will (eventually) label the cluster secret with the current k8s version detected by the cluster info.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by christianh814 — APPROVED** [review]

**Review by jannfis — APPROVED** [review]
Yup, this looks useful :)

LGTM, thanks @blakepettersson

**Comment by mgoodness** [comment]
Thanks indeed, @blakepettersson!

**Comment by llavaud** [comment]
this could have been interesting to extend this feature to also add others labels like the `apiVersions`, it will offer the possibility to send this information through an environment variable to a custom plugin that could use it, like `helm template --api-versions ${ARGOCD_ENV_APIVERSIONS}`

**Comment by csantanapr** [comment]
Cool feature @blakepettersson I'm already labeling my cluster secret with `kubernetes_version` in gitops-bridge https://github.com/gitops-bridge-dev/gitops-bridge-argocd-control-plane-template/blob/main/bootstrap/control-plane/addons/aws/addons-aws-oss-cluster-autoscaler-appset.yaml#L39-L92

I can move to use the argocd proper label, and one more label I don't have to worry to set in terraform

**Pull request merged**
