### PR TITLE
fix: set GOMAXPROCS automatically with uber-go/automaxprocs

### PR DESCRIPTION
**Pull request by Brightside56**
This PR adds https://github.com/uber-go/automaxprocs, which automatically sets CPU quota (GOMAXPROCS) what helps to utilize resources more effectively and avoid unnecessary CPU throttling

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jannfis** [comment]
I'm sorry, but what does this actually fix? Is there a related bug? Did you perform any tests for this?

**Comment by dee-kryvenko** [comment]
@jannfis Go is not cgroups aware. It means that by default (unless certain provisions was applied at code level) Go is going to use number of cores at the underlying Kubernetes node to decide how many threads it will span up. Not pod requests/limits.

It can be easily reproduced with something like:

```bash
# mkdir /experiment
# cd /experiment
# echo $'
package main
import (
    "fmt"
    "runtime"
)
func main() {
    fmt.Println("Number of CPUs:", runtime.NumCPU())
}
' > main.go
# go mod init main
# go mod tidy
# go run ./main.go
Number of CPUs: 16
```

You can imagine what a disaster it may cause if ArgoCD components happen to get scheduled on a particularly large node, say 64 vCPU. You can watch yours using something like:

```promql
sum(container_threads{namespace="argocd",pod!="",container!=""}) by (pod,container)
```

Unfortunately, this library by Uber is only taking into account CPU limits. Which is not necessarily a good thing in clusters that as a general rule are defining only CPU requests with no limits, leaving CFS to do what it is best at. I think a proper thing to do would be to document this somewhere, as not every ArgoCD user is a Go developer to just know this.

**Review by agaudreault — APPROVED** [review]
LGTM. It would be nice if you can test and show before/after graph on an instance with some load.

**Comment by Brightside56** [comment]
```
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              containerName: argocd
              divisor: "0"
              resource: limits.cpu
        - name: GOMEMLIMIT
          valueFrom:
            resourceFieldRef:
              containerName: argocd
              divisor: "0"
              resource: limits.memory
```
Can be done like that tho

**Comment by dee-kryvenko** [comment]
Can it? `GOMAXPROCS` is an int, while CPU resources on the pod can be milicores, and on `GOMEMLIMIT` documentation says

> GOMEMLIMIT is a numeric value in bytes with an optional unit suffix. The supported suffixes include B, KiB, MiB, GiB, and TiB.

Which are different from `Mi` and `Gi` used by Kubernetes https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/.

**Pull request merged**
