### PR TITLE
feat: add support for server-side apply

### LINKED ISSUE #2267: Option to perform K8s v1.16 server-side apply
Kubernetes v1.16 supports the ability server-side apply. A huge benefit of server-side apply is that it which will support strategic merge patching of CRDs. I imagine that many users will want to do server side applies for this reason alone.

We need a way to configure Argo CD to support server-side applies. This option probably needs to be configured globally -- I don't see a reason to have this granular to an application. It also needs to decide to do this based on the version of the cluster. In other words, we cannot attempt server-side applies for kubernetes clusters < 1.16.

Related to this is the ability to do server-side dry runs:
https://github.com/argoproj/argo-cd/issues/804

### PR DESCRIPTION
**Pull request by sathieu**
Fixes: https://github.com/argoproj/argo-cd/issues/2267
Requires: https://github.com/argoproj/gitops-engine/pull/363

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks a lot for this effort, @sathieu. 

We have discussed this in yesterday's contributors meeting and came to the conclusion that we may need some more design thoughts around integrating SSA into Argo CD. Many people are waiting for Server Side Apply feature for various use-cases, and therefore we should look at all the known requirements before we pull it into Argo CD. Worst case at a quick shot would be that we may end up in a situation having to introduce breaking changes for going forward.

Would you be willing to collaborate with us in this design, and then adapt the PRs to reflect the design decisions?

**Comment by sathieu** [comment]
@jannfis I would happily collaborate for the design, and I'll try to find some time to update the PR :rocket:.

**Comment by hikhvar** [comment]
Any updates on the design? Can one participate or give feedback on the design somewhere?

**Comment by leoluz** [comment]
@hikhvar The design is available in the following link:
https://github.com/argoproj/argo-cd/pull/8812

@sathieu This PR and the [gitops-engine one](https://github.com/argoproj/gitops-engine/pull/363) are already implementing good part of the proposal. Do you want/have time to continue to work on this feature?

**Comment by sathieu** [comment]
@leoluz Thanks for the info. I won't have the time to work on this soon. The priority is now lower (we have workarounds).

**Comment by bradj** [comment]
Hey, @sathieu !

We're running into issues that are solved by `serverside-apply`. Wondering what your workarounds are?

**Comment by sathieu** [comment]
@bradj My workaround for prometheus CRD being too big when applied with argocd is here: https://gitlab.com/kubitus-project/kubitus-installer/-/commit/9edaf429bb7181d2b79a81fe14ce154fbdcdc93c.

**Comment by asafhm** [comment]
Would really love to see this PR gets merged, regardless of the workaround :)

**Comment by Jacobious52** [comment]
@sathieu I gave this a try using the `ServerSideApply=true` annotation with 2.4.3 and sync fails with 
```
PatchOptions.meta.k8s.io "" is invalid: fieldManager: Required value: is required for apply patch
```

**Comment by leoluz** [comment]
Closing this PR as SSA is being implemented as part of https://github.com/argoproj/argo-cd/pull/9711

**Pull request closed without merging**
