### PR TITLE
fix(server): not need send application if it is not under enabled namespaces

### PR DESCRIPTION
**Pull request by pasha-codefresh**
I have installed two argocd instances , and in one of them i can see applications that not part of enabled namespaces list. 

Снимок экрана 2023-07-12 в 18 37 50

This is response from application watch api
Снимок экрана 2023-07-12 в 18 37 56

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Can you add a unit test to cover this? Might be tricky since it's a Watch endpoint. If so, you could probably pull the `allowed` function out and test it.

**Review by ishitasequeira — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
@crenshaw-dev done

**Comment by pasha-codefresh** [comment]
@crenshaw-dev could you please review again?

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@pasha-codefresh something like this:

```shell
git checkout release-2.7
git pull
git checkout -b release-2.7-ns-fix
git cherry-pick 2094404e0bdb759aaa8fd11be98ba2dacbf206f4
# resolve conflicts if necessary
git push  # and then open a PR against release-2.7
```

And then repeat for release-2.6 and release-2.5. It's tedious. :-)

**Pull request merged**
