### PR TITLE
chore(manifests): add ClusterRole/ClusterRoleBinding for applicationset controller.

### LINKED ISSUE #16698: Add ClusterRole/ClusterRoleBinding for argocd-applicationset-controller to cluster installation manifests to support ApplicationSet in any namespace feature.
# Summary

Now, cluster installation manifests does not include ClusterRole/ClusterRoleBinding for argocd-applicationset-controller.
So we need to add ClusterRole/ClusterRoleBinding manually to enable [ApplicationSet in any namespace feature](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Appset-Any-Namespace/).

# Proposal

Add ClusterRole/ClusterRoleBinding for argocd-applicationset-controller to manifests/cluster-rbac.

### PR DESCRIPTION
**Pull request by mugioka**
Closes https://github.com/argoproj/argo-cd/issues/16698.

I have added ClusterRole/ClusterRoleBinding for argocd-applicationset-controlller to support ApplicationSet in any namespace feature.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — APPROVED** [review]
Great addition! Thank you!

**Review by ishitasequeira — APPROVED** [review]
Thanks @mugioka!! LGTM!!

**Comment by anandf** [comment]
@mugioka @ishitasequeira Shouldn't the newly added subdirectory be included in the parent `kustomization.yaml` file ? Was it missed out or is it by design ? 
https://github.com/argoproj/argo-cd/blob/20246596962814b732f20b8cc638156df80c4066/manifests/cluster-rbac/kustomization.yaml#L5

**Comment by mugioka** [comment]
Oh, sorry. i will fix it.

**Pull request merged**
