### PR TITLE
fix(notifications-controller): Set cert resolver to use injected "argocd-tls-certs-cm"(#15392)

### LINKED ISSUE #15392: `notifications-controller` doesn't trust certs from `argocd-tls-certs-cm` configmap
**Describe the bug**
`notifications-controller` doesn't trust custom certs added into `argocd-tls-certs-cm` causing failures to send notifications to webhook endpoints with self-signed/custom certificates. 

**To Reproduce**

1. Configure notification in `argocd-notifications-cm`
   ```yaml
   apiVersion: v1
   kind: ConfigMap
   metadata:
     name: argocd-notifications-cm
   data:
     service.webhook.display: |-
       url: https://<endpoint-with-custom-cert>
     trigger.on-created: |-
       - description: Application is created.
         oncePer: app.metadata.name
         send:
         - app-created
         when: "true"
   ```
2. Add custom tls cert in  `argocd-tls-certs-cm`
3. Restart the `notifications-controller` deployment
4. Create an application with following annotation
   ```yaml
   annotations:
     notifications.argoproj.io/subscribe.on-created.display: ""
   ```
5. Check `notifications-controller` deployment for `tls: failed to verify certificate: x509`

**Expected behavior**

`notifications-controller` should send notifications successfully to endpoint by trusting custom certs from  `argocd-tls-certs-cm` configmap

**Version**

```shell
latest/master
```

**Logs**

```
time="2023-09-07T05:01:49Z" level=info msg="Start processing" resource=argocd-e2e/new-app
time="2023-09-07T05:01:49Z" level=info msg="Trigger on-created result: [{[0].X_5TO4MPCKAyY0ipFgr6_IraRNs new-app [app-created] true}]" resource=argocd-e2e/new-app
time="2023-09-07T05:01:49Z" level=info msg="Sending notification about condition 'on-created.[0].X_5TO4MPCKAyY0ipFgr6_IraRNs' to '{display }' using the configuration in namespace argocd-e2e" resource=argocd-e2e/new-app
time="2023-09-07T05:01:49Z" level=error msg="Failed to notify recipient {display } defined in resource argocd-e2e/new-app: Get \"https://endpoint.webhook/hooks/display\": tls: failed to verify certificate: x509: certificate signed by unknown authority using the configuration in namespace argocd-e2e" resource=argocd-e2e/new-app
time="2023-09-07T05:01:49Z" level=info msg="Processing completed" resource=argocd-e2e/new-app
```

**Additional Info**
The certs from `argocd-tls-certs-cm` are correctly mounted into `notifications-controller` pod at `/app/config/tls` path however seems like controller is not reading them.

### PR DESCRIPTION
**Pull request by svghadi**
Fixes #15392

`notifications-engine` includes functionality to use custom certs for notification services. However, in current `notifications-controller` code we are missing the initialization of cert resolver function. 
Previously, when notification-controller was in a separate repo, the initialization of cert resolver was happening [here](https://github.com/argoproj-labs/argocd-notifications/blob/059c1b6c08212b23f5aee612028aa8783bd94eb8/cmd/main.go#L15-L18). 

This PR adds the missing initialization of cert resolver function in notifications-controller so that controller trusts custom certs for notification services.

I could not come up with a unit/e2e test because of dependency on external notification service with custom cert, but I validated the change local following the steps from linked issue and it worked as expected.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by reginaelyse — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]
LGTM!

**Comment by svghadi** [comment]
Thanks @ishitasequeira. Will this fix be backported to 2.9 & 2.8?

**Comment by ishitasequeira** [comment]
@svghadi , the change has been cherry-picked in 2.8 and 2.9

**Pull request merged**
