### PR TITLE
feat: Added the ability to filter MRs by 'state' to Gitlab PR Generator

### LINKED ISSUE #9539: Add the ability to filter MRs by 'state' to Gitlab PR Generator
# Summary

In the Gitlab PR Generators, I wanted to give the developer the ability to provide the 'state' (usually opened) of Gitlab merge requests he wants to create an ephemeral environment for.

# Motivation

In the current Gitlab PR Gen, it grabs all the MRs even those with state 'closed' or 'merged'. We wanted to limit it to only 'opened' MRs so when the MRs gets closed or merged the ephemeral environment dies.

# Proposal

This should be implemented by simply adding an attribute like `pullRequestState` to the GitlabPullRequestGenerator with the state that the developer wants to track. 
This enhancement proposal is only for Gitlab PR Gen since each SCM provider has its own way to filter MRs or PRs and its own state naming style.

### PR DESCRIPTION
**Pull request by Aym3nTN**
Signed-off-by: Aymen Ben Tanfous <aymen.bentanfous@cimpress.com>

Closes: #9539 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — COMMENTED** [review]
LGTM! Can you add a line to the docs mentioning the filter?

**Review by crenshaw-dev — APPROVED** [review]

**Comment by Aym3nTN** [comment]
@crenshaw-dev would this feat and this one #9462 be release in the next release?

**Comment by crenshaw-dev** [comment]
@Aym3nTN this will be in 2.5, which is expected in August.

**Comment by Aym3nTN** [comment]
@jannfis @crenshaw-dev I wanted to make sure that this feat and this one https://github.com/argoproj/argo-cd/pull/9462 are going to be included in v2.5  😅

**Pull request merged**
