### PR TITLE
fix(ui): add `state` parameter in the pkce flow

### PR DESCRIPTION
**Pull request by js3692**
Fixes #17217 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, **(b) this is a bug fix**, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by blakepettersson** [comment]
Hi @js3692!

Could you add unit tests for this? And can you add docs / comments in regards to this (similar to what you did in #17217)?

**Comment by js3692** [comment]
Hello @blakepettersson! Thanks for the pointers - I was largely going off of the original PR https://github.com/argoproj/argo-cd/pull/15889 in terms of tests / docs / comments. I'll see what I can add

**Comment by csantanapr** [comment]
Hi @js3692 would be very useful to get this PR merge, if you could you take a look again to the request from @blakepettersson

**Comment by js3692** [comment]
Argh yes, sry, I'll take another look.

I didn't see any existing tests around this functionality last time. Let me see what makes sense here

**Comment by js3692** [comment]
> Hi @js3692 would be very useful to get this PR merge, if you could you take a look again to the request from @blakepettersson

Hmm, I might be missing something here, but what exactly are you looking for? 😅 

I can add some comments in the code, but I can't find any docs or unit tests for the UI. I'd appreciate some pointers.

**Comment by blakepettersson** [comment]
Hi @js3692!

Sorry about that - I missed that this was just a UI change (there definitely should be UI tests IMO, but that's another matter and not pertaining to anything you need to do).  LGTM 👍

**Comment by csantanapr** [comment]
Thank you @blakepettersson for the reply and clarification 

What's the next step for the PR to progress?

**Comment by amcinnes** [comment]
Is there anything blocking this PR? I'd love to see it merged so I can have the PKCE flow working with Okta - because then I can hopefully have Argo's web UI and CLI both working using one Okta app.

**Review by christianh814 — APPROVED** [review]

**Review by Marvin9 — CHANGES_REQUESTED** [review]
Apologies for late response. I have tested it and it works as expected. 

You would need to remove the state from session storage after verification. You can add [here](https://github.com/argoproj/argo-cd/blob/master/ui/src/app/login/components/pkce-verify.tsx#L20)

**Review by Marvin9 — APPROVED** [review]
Will raise the followup PR. The changes I requested should not block this long pending PR

**Comment by js3692** [comment]
Thanks all - almost forgot about this PR 😅. Updated with the `unset` + made it more consistent with the other state handler.

**Review by Marvin9 — APPROVED** [review]
Thank you! LGTM. Needs an approval from someone with access. @blakepettersson can you please approve or tag relevant user who can approve?

**Comment by blakepettersson** [comment]
I don't have the prerequisite powers, but @gdsoumya does 😄

**Review by gdsoumya — APPROVED** [review]

**Pull request merged**
