### PR TITLE
fix(reposerver): fix OCI repository matching (#12436)

### LINKED ISSUE #12436: Unable to use OCI Registry with sub helm charts
**Describe the bug**
You cannot create a new app which uses a GIT repo URL as a source and use a sub helm chart with an OCI Registry.
The Chart.yaml looks like this:

```
apiVersion: v2
name: les-service
type: application
version: 1.0.0

dependencies:
  - name: les-service
    version: "1.0.0"
    repository: oci://registry.app.corpintra.net/les
```

**To Reproduce**
See screenshot

**Expected behavior**
The sub helm chart needs to work with the OCI registry like before with a chart repo URL --> https://registry.app.corpintra.net/chartrepo/les

**Screenshots**
image

**Version**
v2.6.1+3f143c9

**Logs**

`Unable to create application: application spec for ass is invalid: InvalidSpecError: Unable to generate manifests in env: rpc error: code = Unknown desc = helm dependency build failed exit status 1: Error: could not download oci://registry.app.corpintra.net/les/les-service: failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://s3-edc.emea.svc.corpintra.net/edcs3dhccaasprodb/docker/registry/v2/blobs/sha256/24/2431b3f41cb1c457ca3828492ab626f446096b6205e297694a913e8e534416c2/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=7cbc312f5c926f7fc1ad%2F20230113%2Feddhcbuckets%2Fs3%2Faws4_request&X-Amz-Date=20230113T153231Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=e9c0e391e10a05307d4a27286ccec4c46553f5fba7fb4751a355fefbdec7c549": Forbidden`

### PR DESCRIPTION
**Pull request by MioOgbeni**
When an OCI repository is used as a Helm Chart dependency, there must not be an exact match for the dependency URL and the repo URL. This PR fixes usage for OCI registry located deeper in the registry structure.

I also created a unit test for this case

Fixes #12436

This issue is also in older version v2.10.7, it would be great if the PR was cherry-picked into the v2.10.x patch.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by MioOgbeni** [comment]
Still without review :/ It's really simple fix, can someone look at this?

**Review by pasha-codefresh — APPROVED** [review]
LGTM, thank you for fixing this

**Comment by DjinNO** [comment]
Hello, I am using ArgoCD version v2.12.0+ec30a48. The deployment goes through, but ArgoCD still shows an error:

`ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: 
rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` 
failed exit status 1: Error: could not download oci://ghcr.io/example/app-values/base: 
failed to authorize: failed to fetch anonymous token: unexpected status from GET request to 
https://ghcr.io/token?scope=repository%3Aexample%2Fapp-values%2Fbase%3Apull&service=ghcr.io: 403 Forbidden`

**Comment by PhamQuang-512** [comment]
i'm getting same issue

> Hello, I am using ArgoCD version v2.12.0+ec30a48. The deployment goes through, but ArgoCD still shows an error:
> 
> `ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `helm dependency build` failed exit status 1: Error: could not download oci://ghcr.io/example/app-values/base: failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Aexample%2Fapp-values%2Fbase%3Apull&service=ghcr.io: 403 Forbidden`

**Comment by DjinNO** [comment]
The problem remains with OCI ghcr.io repositories

**Pull request merged**
