### PR TITLE
refactor: decompose Repository.GetAppDetails, remove interface{}.

### PR DESCRIPTION
**Pull request by askreet**
This refactor aims to resolve two code quality points:

1. Reduces `GetAppDetails` function cyclomatic complexity from 28 to < 10.
   a. No introduced sub-functions exceed cyclomatic complexity of 10.
2. Removes the use of `interface{}` from `runRepoOperation` by passing closures around result structures for `cacheFn` (formerly `getCached`) and `operation`.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] ~~The title of the PR states what changed and the related issues number (used for the release note).~~
* [ ] ~~I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.~~
* [ ] ~~I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~~
* [ ] ~~Does this PR require documentation updates?~~
* [ ] ~~I've updated documentation as required by this PR.~~
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] ~~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~~
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by askreet** [comment]
Having a hard time reasoning about why e2e tests would fail on a single version of k8s. Will try re-triggering the jobs.

**Review by alexmt — APPROVED** [review]
Thank you @askreet . 

Great change. The `interface{}` in `runRepoOperation` caused a bug recently: https://github.com/argoproj/argo-cd/pull/4668

I'm glad we can get rid of it. Sorry for delay in review, had to prioritize v2.0 bug fixes. Can you please resolve merge conflicts?

**Comment by askreet** [comment]
Thanks @alexmt glad to hear you like the changes. I can take a look, looks like some non-trivial changes to repository.go that need to be moved around. Will take a look when I have a few spare moments.

**Comment by askreet** [comment]
@alexmt I think I've resolved all the conflicts, the repository tests pass locally. Need approval to run the full suite in CI.

**Pull request merged**
