### PR TITLE
chore: bump helm version to 3.9.0

### PR DESCRIPTION
**Pull request by carbohydrates**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
lgtm! I see some thumbs-up. Does this need to be cherry-picked to 2.4?

**Comment by trigger305** [comment]
please add to 2.4 - the merge in helm 3.9.0 has some improvements in it

**Comment by crenshaw-dev** [comment]
@jannfis @alexmt any opposition to cherry-picking?

**Comment by crenshaw-dev** [comment]
If we do cherry-pick, we should add a note to https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.3-2.4.md

**Comment by jannfis** [comment]
I'm not very fond of bumping a minor tool version after 2 RCs have been out already, unless there's a very good reason.

**Comment by crenshaw-dev** [comment]
I'm going to merge so this PR doesn't sit. @trigger305 if you feel very strongly, can you open an issue making the case for cherry-picking and then link it here?

**Pull request merged**
