### PR TITLE
fix: TestFailedConversion and turn back on in e2e

### PR DESCRIPTION
**Pull request by zachaller**
This fixes the TestFailedConversion test that was broken due to
v1beta1 being deprecated in k8s 1.22 https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122

Signed-off-by: zachaller <zachaller@hotmail.com>

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Review by terrytangyuan — CHANGES_REQUESTED** [review]
v1.23.3 coverage needs to be added back before merging

**Comment by zachaller** [comment]
Ok after looking into this a bit more and reading the history here https://github.com/argoproj/argo-cd/issues/1414 and then noticing that apiregistration.k8s.io/v1beta1 is no longer [served](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#apiservice-v122) in Kubernetes 1.22 I am wondering if this test should even exits. Unless we can find another resource that would fail conversions that we could use however if we can find one then we would also need to always keep updating it as k8s deprecates resources.

**Comment by zachaller** [comment]
Closing this PR after talking to @alexmt in order to fix this for local e2e we will probably have to move test over to something like mocked unit tests.

**Comment by crenshaw-dev** [comment]
@zachaller do you have an explanation of what this test is checking / how we might mock it?

I can put some time into fixing the test. We don't get CI checks when testing security patches, so we have to rely on local e2e testing. I'd like to avoid asking people to comment out this test when running locally.

**Pull request closed without merging**
