### PR TITLE
fix: Adding noscript tag to index.html issue #5478

### PR DESCRIPTION
**Pull request by anais-codefresh**
Fixes [ISSUE #5478]

This is my first PR so not I am not too sure how to fill out the below checklist.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Hi @anais-codefresh, and many thanks for helping to improve Argo CD with your PR!

To make the CI happy, please:

* [Prefix the PR title](https://argo-cd.readthedocs.io/en/latest/developer-guide/contributing/#title-of-the-pr) using `fix: ` (this indicates that the PR resolves a bug issue), so the Semantic PR title check is happy
* Sign-off your commit in Git so that the DCO check is happy

**Comment by anais-codefresh** [comment]
Hey @jannfis lmk if this is ok like that :)

**Comment by jannfis** [comment]
Thank you, @anais-codefresh. Somehow, CodeQL complains now about an already fixed issue. I believe this can be fixed by rebasing your PR to latest `master`-branch code. Once you've done that, and CodeQL is happy too, I'll merge the change.

**Review by jannfis — APPROVED** [review]
LGTM, thank you @anais-codefresh !

**Pull request merged**
