### PR TITLE
docs: reorganize and clarify CMP docs

### PR DESCRIPTION
**Pull request by crenshaw-dev**
The biggest change is to reorder the CMP docs to read more like a step-by-step installation/use guide.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Since the only changes are docs changed, I think the failures must be flakey tests.

**Comment by alexmt** [comment]
@crenshaw-dev , master branch was actually broken. It is fixed now: https://github.com/argoproj/argo-cd/pull/8147

Can you please pull lastest master changes into your branch please?

**Comment by crenshaw-dev** [comment]
I think the Snyk errors can be safely ignored. Looks like those were for hitting usage limits.

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
