### PR TITLE
fix: update github rsa ssh key (argo-cd#12992)

### LINKED ISSUE #12992: Github RSA SSH key rotation
# Summary

GitHub has [rotated its RSA SSH key](https://github.blog/2023-03-23-we-updated-our-rsa-ssh-host-key/), which is a key that ships with ArgoCD.  This key should be updated within ArgoCD.

# Motivation

During install, ArgoCD will install common known hosts including GitHub, which is now an incorrect key.

# Proposal

Effectively, a sweeping `sed`.  I have a fork that I've done this in, if it's as simple as that with the tooling (I'm unfamiliar with this repo aside from being a user).

### PR DESCRIPTION
**Pull request by Matt1360**
Fixes #12992 via `sed` to replace all occurrences of the old GitHub RSA SSH key.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by morey-tech — APPROVED** [review]

**Review by 34fathombelow — APPROVED** [review]

**Comment by 34fathombelow** [comment]
Verified correct new key is used.

**Comment by Matt1360** [comment]
Looks like `codegen` didn't like this, I see a change in newline at the end of file in `manifests/base/config/argocd-ssh-known-hosts-cm.yaml` (likely done with `vi` when I patched our internal clusters).

I'll run `make codegen` against it, though I think it will just change the YAML `ssh_known_hosts: |-` to `ssh_known_hosts: |`, which is what the test appears to be complaining about.  I'll also wait to make sure this is the only thing that's unhappy.

**Review by todaywasawesome — APPROVED** [review]
Great work.

**Comment by Matt1360** [comment]
All green this time!

**Review by Amauche — APPROVED** [review]

**Review by jannfis — APPROVED** [review]
LGTM! Thank you @Matt1360 !

**Pull request merged**
