### PR TITLE
feat: Added toggle button for compact view #7836

### LINKED ISSUE #7836: Compact application resource tree - Implement Toggle button instead of a view
# Summary

This is a follow-on enhancement to https://github.com/argoproj/argo-cd/issues/7349
In its initial design and implementation, a new Compact view was added to show the compact/collapsed resource tree.

Instead of using a new Compact view, add a toggle button to collapse/expand the resource tree to the existing Tree view.

# Motivation

In some cases, the tree has no collapsed nodes so the content in this view ends up being the same as in the Tree view.

Therefore it is probably better to use a collapse/expand toggle and add it to the existing Tree view instead.

# Proposal

Add a toggle.

### PR DESCRIPTION
**Pull request by ciiay**
Closes #7836 
Signed-off-by: ciiay yicai@redhat.com

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Preview:
Screen Shot 2021-12-10 at 10 22 58 AM
Screen Shot 2021-12-10 at 10 24 15 AM

### CODE REVIEW

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you @ciiay !

The button looks great on real applications but a little weird if application does not have many resources and if filter is applied:

image

Can you change style so that button always rendered in left/rigth top corner?

**Comment by ciiay** [comment]
@alexmt Thanks for the view and the feedback. Here's the screenshots of the updated button style.
Without fixed filter panel:
Screen Shot 2021-12-13 at 3 16 43 PM

With fixed filter panel:
Screen Shot 2021-12-13 at 3 18 35 PM

**Comment by alexmt** [comment]
Looks great. Thank you!

**Review by alexmt — APPROVED** [review]
LGTM

**Pull request merged**
