### PR TITLE
chore: repo command give more hints.

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

Give more hints by cobra command help info.

### CODE REVIEW

**Comment by yanggangtony** [comment]
This pr have been a time for review.
Would you have time to review it?
@crenshaw-dev @jannfis @rbreeze

**Review by jannfis — APPROVED** [review]
LGTM, thanks!

**Comment by jannfis** [comment]
Oh sorry, I have seen that one of the CI test has failed (the codegen one). The generated CLI docs differ, because you changed help text for command line arguments.

Please run `make clidocsgen` and commit/push the changes, so that CI will pass.

**Comment by yanggangtony** [comment]
@jannfis 
thanks for quick review..
rebased it.

**Comment by yanggangtony** [comment]
image

a ci error shows up.
may have no business with the pr.

**Pull request merged**
