### PR TITLE
fix: Automated smoke test that mimics user behavior UI (#4393)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

This is part II of the automated UI tests for https://github.com/argoproj/argo-cd/issues/4393

The PR simply adds the unique identifiers to the relevant UI components, plus some formatting changes so as to not exceed 180 characters per line.  Feel free to suggest a new format of the identifiers, but they should be unique. I used the page/source as the 'prefix' to ensure there are no id clashes with similarly named components in other pages.

For example, if it is the `New App` button shown on the applications list page (application-list.tsx), the identifier is:
`applications-list-button-add-new`

For example, if it is the `Application Name` field shown on the application create sliding panel (application-create-panel.tsx), the identifier is:  `application-create-field-app-name`

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by keithchong** [comment]
Hi @alexmt, does the PR build pull in the latest ArgoUI?  When I build the UI, I don't see these build error.

**Comment by alexmt** [comment]
hello @keithchong , it does not. You need to run `yarn add https://github.com/argoproj/argo-ui.git` to pull latest version and regenerate yarn.lock file.

**Comment by keithchong** [comment]
Thanks @alexmt, the previous build step passed now.  Looks better now.

Recall my addition here when dealing with the gitops-engine changes: https://argoproj.github.io/argo-cd/developer-guide/dependencies/

Do you think it's a good idea, for the benefit of others, to add a paragraph to the above dependencies doc, on what to do when making ArgoUI changes?  I will open an issue and add something like:

1. Make changes to ArgoUI.
2. Make your changes to ArgoCD
3. After your ArgoUI PR is merged to master, then as part of your commit for ArgoCD, run `yarn add https://github.com/argoproj/argo-ui.git`
4. Check in the regenerated`yarn.lock` file as part of your commit.
5. Create the ArgoCD PR when you are ready.

**Review by alexmt — APPROVED** [review]
LGTM!

**Comment by alexmt** [comment]
> Do you think it's a good idea, for the benefit of others, to add a paragraph to the above dependencies doc, on what to do when making ArgoUI changes and if you have dependencies on those changes from ArgoCD (Not sure if there are many cases)?

@keithchong I agree. This would be very useful documentation for everyone who wants to contribute.

**Pull request merged**
