### PR TITLE
fix: remove not existing repo

### LINKED ISSUE #7279: Unit tests not passing inside master branch
git_test.go TestNewFactory not working anymore because https://jsuen0437@dev.azure.com/jsuen0437/jsuen/_git/jsuen no longer exist

### PR DESCRIPTION
**Pull request by pasha-codefresh**
Closes: #7279

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
LGTM. Thanks for fixing it @pasha-codefresh, I think we should not access remote Git repositories in unit tests anyway.

**Comment by jessesuen** [comment]
Probably the repo got pruned since it may have been associated with my old corporate e-mail which is probably gone by now.

Anyways, I added this test because of following issues:
https://github.com/argoproj/argo-cd/issues/1067
https://github.com/src-d/go-git/issues/1058

I think if we are settled on a fork/exec model of git (and I don't ever see us realistically moving away from this), it will be okay to remove this test.

**Comment by jessesuen** [comment]
@alexec suggested we create an `argoproj` organization and make this an e2e test instead of unit. I went ahead and created the org and repo:

https://dev.azure.com/argoproj/argocd-example-apps

**Comment by pasha-codefresh** [comment]
i will create e2e test for this

**Pull request merged**
