### PR TITLE
fix: applications/resources filter improvement and bug fixes

### LINKED ISSUE #6945: Horizontal filters on applications screen waste space
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

There are two positions of the filters, the top and the side. On the side view, space is efficiently used. On the top view however, each non-standard filter they form a single column which is
a) taller than everything else, and nearly even in height when collapsed
b) wastes space to the right

**To Reproduce**

1. Go to https://cd.apps.argoproj.io/applications?proj=&sync=&health=&namespace=&cluster=&labels=
2. Press "Show" next to the filters funnel
3. Zoom out until the filters are above the content area
4. Collapse Labels, Projects, Clusters, and Namespaces
5. Observe the wasted space to the right as well as the trapped whitespace to the left. 

**Expected behavior**

Space should be used more efficiently

**Screenshots**
Screenshot from 2021-08-10 16-54-24

**Version**

```shell
{
    "Version": "v2.1.0+c5eb25c",
    "BuildDate": "2021-08-10T02:22:42Z",
    "GitCommit": "c5eb25cebac5c8a48f2f6db8bd2136a1672fbb2f",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

Closes https://github.com/argoproj/argo-cd/issues/6945

More fixes for applications and resource filters: 

* drops Age and Ownership filters from resources page: 
  * Age filter became unusable after 1 hr; additionally the intention was to find recently updated resources, not created but modification time is not available. 
  * Ownership filter is only useful in combination with a filter that is applied to nonroot resource. For example user could filter child pods by label and then find it's parents. But we don't have such filter
* fixes Sync and Health filter: element should be shown if it matches to the filter or it's root matches to the filter. E.g. In-Progress should show all in-progress deployments and replicas with pods of such deployments.

### CODE REVIEW

**Review by rbreeze — CHANGES_REQUESTED** [review]
Looks good to me. Just a couple comments: 

1. 
> Ownership filter is only useful in combination with a filter that is applied to nonroot resource. For example user could filter child pods by label and then find it's parents

This is true, but @alexec has [a PR open that adds a label filter](https://github.com/argoproj/argo-cd/pull/6723). So it might be useful to add back later. Or, we could wait for the label filter to get merged.

2. The Health Status filter is much taller than the other filters for the small screen width view. We can do this in another PR, but perhaps we could break those filters into 2-3 columns for small screen widths?
Screen Shot 2021-08-09 at 10 21 12 AM

3. This could also be another PR, but could we switch the `SHOW ORPHANED` checkbox to the `argo-ui/v2` component? In my browser, there is a visual artifact on the current one: 
Screen Shot 2021-08-09 at 10 25 30 AM

**Comment by rbreeze** [comment]
Just thought of another comment. At large screen widths, the filters column does not scroll with the resource tree. However, at small screen widths this doesn't hold true.

Additionally, the `SHOW ORPHANED` option hovers over the tree at all times, but has no visual demarcation, which can result in things like this: 
Screen Shot 2021-08-09 at 10 31 38 AM

One solution is to add another row to the top bar (with a white background) to contain filters and the `SHOW ORPHANED` checkbox. What do you think?

**Comment by rbreeze** [comment]
Another idea is to widen the navigation sidebar so that we can use it for more things. The layout could look something like this (forgive the drawing): 

IMG_82FB73A0A812-1

DigitalOcean has a similar layout in their portal: 

Screen Shot 2021-08-09 at 10 44 16 AM

I think this would utilize screen space much better for small screen widths, and same as before for large screen widths.

**Comment by alexmt** [comment]
Thanks for review @rbreeze ! 

> Ownership filter is only useful in combination with a filter that is applied to nonroot resource. For example user could filter child pods by label and then find it's parents

 We are super close to the 2.1 release. I would prefer to re-add labels and ownership filter in 2.2. My concern is that we forgot to think about how ownership filter is going to work with existing "Health" and "Sync" filters. These filters already assume "include children" but ownership filter has it's own "include" children which makes it confusing. I guess the solution is to make "include children" checkbox checked by default. Do you agree to postpone it till 2.2 , @rbreeze  ?

> The Health Status filter is much taller than the other filters for the small screen width view. We can do this in another PR, but perhaps we could break those filters into 2-3 columns for small screen widths?

> Just thought of another comment. At large screen widths, the filters column does not scroll with the resource tree. However, at small screen widths this doesn't hold true.

I agree - this is a bigger issue. User would has to scroll back and fourth to make a filter change - this is extremely inconvenient. As we discussed offline let's try to change filter behavior as following: 

* filters stays on left side always 
* on smaller screen filters panel collapses into smaller narrow panel that can be expanded using expand button (similar to outlook web navigation)

**Comment by alexec** [comment]
Can I refresh you with my original use cases? It feel we've been distracted by UI polish, and forgotten why I did this in the first place.

I have to work with large apps. These apps have many kinds of resources and span multiple namespaces.

I don't care about out-of-sync resources. I don't need to search for unhealthy resources. I’m aware that other users need to, and they are already catered for, I just don't have much opinion on them.

I care about finding sub-groups of my resources in my app. Specifically, I want to see all pods in my app, and their owners so I can to navigate to their deployment or stateful set quickly.

*Kind filter*: I think this is now broken in terms of usability. This can be fixed by removing the autocomplete and reinstating the check boxes. It would be acceptable for this to be folded up by default.

*Age filter*: I found that I did not end up using it. I agree that it should be removed.

*Ownership filter*:

> Ownership filter is only useful in combination with a filter that is applied to non-root resource.

This not enough reason to remove this filter. This the only way to achieve the "show me pods and their owners" use case.

As a middle-ground, I propose we remove the "owned" option, I did not find this useful in the end.

**Comment by alexec** [comment]
> We are super close to the 2.1 release. I would prefer to re-add labels and ownership filter in 2.2.

I did not see this comment. I think this is fine. I agree it would be better to remove them and revisit them. I don't have bandwidth for this myself.

**Comment by alexmt** [comment]
@rbreeze , filters say on left side now and collapse if page size is too small. Please see the recording:

https://user-images.githubusercontent.com/426437/128804991-4b6efdba-561f-4b85-a5e8-eb7de0a87cbf.mov

WDYT?

**Comment by rbreeze** [comment]
@alexmt I think that looks great! Thanks

**Review by rbreeze — CHANGES_REQUESTED** [review]
A couple small things:

1) At small screen widths, when the filters panel is pinned, it causes the Application Tiles to get cut off. This doesn't affect functionality much and is really just a visual annoyance, so we could always fix it later. 

Screen Shot 2021-08-10 at 3 09 04 PM

2) If the filters panel on the Applications List page is pinned, the filters panel on the Application Tree is also pinned by default. I think this is because the expanded state for both is stored in a single variable in ViewPrefs. I think it makes more sense for each to be independent, but I think either way is okay.

Let me know your thoughts, both comments are minor so I can approve as-is.

**Comment by alexmt** [comment]
Thanks for review!

> At small screen widths, when the filters panel is pinned, it causes the Application Tiles to get cut off. This doesn't affect functionality much and is really just a visual annoyance, so we could always fix it later.
 I've changed styles to collapse both refresh and delete buttons a bit earlier. WDYT?

image

> If the filters panel on the Applications List page is pinned, the filters panel on the Application Tree is also pinned by default. I think this is because the expanded state for both is stored in a single variable in ViewPrefs. I think it makes more sense for each to be independent, but I think either way is okay.
 
Double checked but could not reproduce it. I think "pinned" states are stored separately.

**Comment by rbreeze** [comment]
> Double checked but could not reproduce it. I think "pinned" states are stored separately.

You're right, I wasn't paying attention 😅 Thanks!

> I've changed styles to collapse both refresh and delete buttons a bit earlier. WDYT?

Looks great!

**Review by rbreeze — APPROVED** [review]

**Pull request merged**
