### PR TITLE
fix(cli): fix header in resource-overrides list-actions output

### PR DESCRIPTION
**Pull request by maxbrunet**
The boolean in the output is `action.Disabled`, so its header should be `DISABLED`, not `ENABLED`.

Closes #12774

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by jannfis — COMMENTED** [review]
Thanks for this PR! 

Not sure if changing the header is the right fix, though. What do you think about negating the bool value using `strconv.FormatBool(!action.Disabled)` instead?

**Comment by maxbrunet** [comment]
Since the Go struct field is called `Disabled` and when writing Lua we use the `disabled` table key, I think it makes sense to be consistent and continue using `DISABLED` as the header instead of inverting the logic, no?

**Review by jsoref — APPROVED** [review]

**Comment by jsoref** [comment]
I'm fine w/ this form, fwiw, `cronjobs` have:

```
NAME                                        SCHEDULE                SUSPEND   ACTIVE   LAST SCHEDULE   AGE
test-transactions                           0 0 1 * *               True      0        <none>          6d1h
```

`SUSPEND` is the opposite of an enabled flag.

**Comment by jannfis** [comment]
Alright, I have no strong feelings about either way of displaying this.

**Review by jannfis — APPROVED** [review]
LGTM

**Comment by maxbrunet** [comment]
Thank you @jannfis!

Should we backport to supported releases? Seems really easy and safe

**Pull request merged**
