### PR TITLE
fix(ui): Add tooltips to Role JWTs view (#4633)

### PR DESCRIPTION
**Pull request by tetchel**
- Improve error message for invalid 'Expires In'
- Remove extra space next to 'Create' button

Signed-off-by: Tim Etchells <tetchell@redhat.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by tetchel** [comment]
Fixes https://github.com/argoproj/argo-cd/issues/4633

**Comment by rbreeze** [comment]
Would you mind adding a couple screenshots?

**Review by rbreeze — APPROVED** [review]
LGTM!

**Comment by tetchel** [comment]
image

**Review by jannfis — APPROVED** [review]
LGTM too, thank you!

**Pull request merged**
