### PR TITLE
fix: provide nameNormalized param for local cluster in ApplicationSet cluster generator (#9727)

### LINKED ISSUE #9727: ApplicationSet Cluster Generator: nameNormalized is not provided for local cluster
# Summary

I'm trying to create a very simple application set that will generate an application for every cluster, including the local cluster. The problem is that the names of my remote clusters have slashes so I need to use `nameNormalized`. But then it always fails to generate the application for the local cluster. The logs show:
```
\"{{nameNormalized}}-my-app\" is invalid
```

Below is the `ApplicationSet`:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app
spec:
  generators:
  - clusters: {} # Automatically use all clusters defined within Argo CD
  template:
    metadata:
      name: '{{nameNormalized}}-my-app'
    spec:
      project: default
      source:
        repoURL: ''
        targetRevision: HEAD
        path: .
      destination:
        server: '{{server}}'
        namespace: default
```

# Motivation

I would really rather avoid having to do what is suggested in https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster, my case is very simple - I don't need to distinguish clusters from one another, I want the generator to work for local and remote clusters.

# Proposal

I had a look at the code and saw that `nameNormalized` is [provided for remote clusters](https://github.com/argoproj/argo-cd/blob/952230eaf86e580b5a7f88fcf61ac50d942651f0/applicationset/generators/cluster.go#L123) but [not for the local cluster](https://github.com/argoproj/applicationset/blob/c8fb714a35fc66805fdb184dd5e6455637d5a8b4/pkg/generators/cluster.go#L106). In my case I'd just want `nameNormalized` to equal `name` for the local cluster.

### PR DESCRIPTION
**Pull request by lacarvalho91**
Closes #9727

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

I don't believe this requires documentation updates.

### CODE REVIEW

**Comment by lacarvalho91** [comment]
@crenshaw-dev any idea when someone will be able to review this? i resolved a conflict yesterday

**Comment by rishabh625** [comment]
Hi @lacarvalho91 , Thanks for PR,

but this PR doesn't looks good to me
1) even if u add that normalized param it will not be normalized as it doesn't get appended in secretsFound
2) you will need to add label           argocd.argoproj.io/secret-type: cluster as described here https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster for it to get appended in secretsFound

imho, this changes looks redundant

**Comment by lacarvalho91** [comment]
@rishabh625 the description in the PR should properly explain the motivation but this is simply to provide `nameNormalized` as a template variable when using local cluster. I don't think I should need to do what is documented on https://argocd-applicationset.readthedocs.io/en/stable/Generators-Cluster/#deploying-to-the-local-cluster just to be able to do that. The sanitize method doesn't need to be called as we know the local cluster always has the same name, but I can easily change this to call sanitize method.

**Comment by rishabh625** [comment]
I got you @lacarvalho91 , that's my worry u just need a nameNormalized param which contains value similar to name. 

I feel let's include that param but atleast populate normalised value in it.

@crenshaw-dev  what's your opinion?

**Review by crenshaw-dev — APPROVED** [review]
@rishabh625 thanks for the ping! lgtm. I'm gonna treat this as a bugfix so we can get it into 2.4.x.

**Comment by rishabh625** [comment]
Ok @crenshaw-dev

**Comment by crenshaw-dev** [comment]
@rishabh625 I think @lacarvalho91 is correct that the name is already normalized by definition because it is always `in-cluster`.

**Comment by rishabh625** [comment]
> @rishabh625 I think @lacarvalho91 is correct that the name is already normalized by definition because it is always `in-cluster`.

Ohh, i thought if we change the name of in-cluster, it still picks the local cluster as local one , it distinguishs local and remote by label and not name.

**Pull request merged**
