### PR TITLE
docs: Fixed indentation Error

### PR DESCRIPTION
**Pull request by iflan7744**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by ashutosh16** [comment]
@iflan7744  Can you update the title of the PR  https://argo-cd.readthedocs.io/en/stable/developer-guide/toolchain-guide/#title-of-the-pr

**Review by crenshaw-dev — APPROVED** [review]
Thank you @iflan7744!

Looks like everything under the top-level `data` key should be indented as well. Could you make that change?

**Comment by iflan7744** [comment]
> Thank you @iflan7744!
> 
> Looks like everything under the top-level `data` key should be indented as well. Could you make that change?

Changes has been done has requested @crenshaw-dev

**Review by crenshaw-dev — APPROVED** [review]
Awesome, thank you @iflan7744!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.9.

**Pull request merged**
