### PR TITLE
feat(appset): Advanced templating for ApplicationSet

### LINKED ISSUE #9177: Support for multiple sources in application set with generators
# Summary
I used argoCD application-set to  deploy my helm charts from one source and my k8s manifests from another source. But there is no support for multiple sources in application-set in `argoproj.io/v1alpha1` API  version. 

# Motivation
To deploy different application sourced from different points, like helm charts from some repo at bitnami and customize packages from my own private repo. 
# Proposal

Multiple sources must be support in applicationset so that we can deploy multiple application by getting deployment files from different sources.

### LINKED ISSUE #11164: Allow advanced templating in ApplicationSet
People want to be able to do advanced things in ApplicationSet templates.

One way to accomplish this is to provide a plain ol' string field for the template instead of an Application spec. But then you lose nice IDE support.

Another way, which I think would require fewer changes, is to allow templating _keys_ instead of just values in the Application spec.

Something like this:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - automated: "true"
      - automated: "false"
  template:
    spec:
      syncPolicy:
        "{{ ternary "automated" "turtles" (eq .automated "true") }}": {}
```

When `automated` is not `"true"`, the key nested under `syncPolicy` evaluates to `turtles`. Since that's not part of the Application spec, it'll be dropped when the Application is unmarshaled. 

Similar strategies could be applied to toggle, for example, fields under `source`. That would allow a git files generator to generate applications both for Helm and Kustomize.

**Changes required:**

First, we'd have to change the ApplicationSet CRD to preserve unknown fields. `"{{ ternary "automated" "turtles" (eq .automated "true") }}"` would otherwise be rejected as an invalid key (or, if validation is disabled, dropped).

Second, we'd have to change the ApplicationSet controller to handle the ApplicationSpec as an unstructured until the very last moment, when _all_ templating has been applied. If we unmarshal to an Application spec before then, we'll lose the templated key.

Inspiration for this strange idea comes from fixing this bug, when I realized we can template keys: https://github.com/argoproj/argo-cd/pull/11163

### PR DESCRIPTION
**Pull request by speedfl**
Signed-off-by: gmuselli <geoffrey.muselli@gmail.com>

@crenshaw-dev I think you were interested by this one

Closes #11164
Closes https://github.com/argoproj/argo-cd/issues/9177

Main purpose is to have an ApplicationSet Template as `map[string]interface{}` which can be fully templatable

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  generators:
  - list:
      elements:
      - cluster: engineering-dev
        url: https://kubernetes.default.svc
        automated: true
        prune: true
      - cluster: engineering-prod
        url: https://kubernetes.default.svc
        automated: true
        prune: false
      - cluster: engineering-debug
        url: https://kubernetes.default.svc
        automated: false
        prune: false
  template:
    metadata:
      name: '{{.cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
        path: applicationset/examples/list-generator/guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: guestbook
      syncPolicy:
        # If automated == true, it will generate a key 'automated' which is part of the Application Spec model. It will then be retained
        # If automated == false, it will generate a key 'noAuto' which is not part of the Application Spec model. It will then be ignored
        '{{ ternary "automated" "noAuto" .automated }}':
          # If prune == true, it will generate a key 'prune' which is part of the Application Spec model. It will then be retained
          # If prune == false, it will generate a key 'noprune' which is not part of the Application Spec model. It will then be ignored
          '{{ ternary "prune" "noprune" .prune }}': true
``` 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@speedfl you're a force of nature.

I doubt I'll personally have time to review this in time for 2.6. But if the community likes the approach, I'd love to get it into 2.7.

**Comment by michalschott** [comment]
@crenshaw-dev can you explain how can we as community motivate you more to "merge it asap as this is what we need"? 😄

**Comment by boedy** [comment]
Interesting approach. I think this is exactly what I need. Would we be to toggle `automated` by using only a single variable as in the example bellow?

```yaml
syncPolicy:
  '{{ ternary "automated" "noAuto" .automated }}':
    prune: true
    selfHeal: true
```

**Comment by speedfl** [comment]
@boedy yes. You Can take a look to examples and e2e

**Comment by mubarak-j** [comment]
apologies if this repeating the same question, but can parameter values provided by various generators be used as a condition here, e.g labels provided by cluster generator?
```yaml
kind: ApplicationSet
spec:
  goTemplate: true
  template:
    spec:
      syncPolicy:
{{- if eq (index .metadata.labels "env") "staging" }}
        automated: {}
{{- end }}
````

**Comment by crenshaw-dev** [comment]
> @crenshaw-dev can you explain how can we as community motivate you more to "merge it asap as this is what we need"? 😄

@michalschott pay Intuit to clone me. ;-) But seriously, I'll be advocating with my PM to get my time assigned to this before 2.7. 

@mubarak-j templates outside of keys or string-type values are not part of this PR. For that, you'll need this: https://github.com/argoproj/argo-cd/pull/11183

**Comment by crenshaw-dev** [comment]
Oh! But @mubarak-j, you could accomplish the same thing by doing this:

```yaml
kind: ApplicationSet
spec:
  goTemplate: true
  template:
    spec:
      syncPolicy:
        '{{ ternary "automated" "noAuto" (eq (index .metadata.labels "env") "staging")}}': {}
```

My bad, I was looking at the exact text of your example instead of the intention. :-)

**Comment by speedfl** [comment]
@crenshaw-dev Hope you are doing well. A little present :), I rebased from master with small improvments compared to previous version. 

Initially only the spec in the template was fully templatable. Now the entire template is a raw Json so that we can as well template metadata (ie: conditional finalizers)

Added documentation + e2e

**Comment by crenshaw-dev** [comment]
@speedfl that's awesome, thanks!

I just got approval to spend time reviewing this for 2.7. It'll be a couple weeks before I can dive in.

A couple notes:

1) it would be nice to still build a "full CRD" for folks to use in their IDEs - but I'd consider that nice-to-have
2) with the whole Application being templateable, I think we'll need to add code to protect the `status` field (and maybe one or two other top-level fields that might exist - I need to look at the Application CRD).

**Comment by speedfl** [comment]
@crenshaw-dev 

Thanks a lot for the suggestion. I will add the status field protection in `applicationset_controller.validateGeneratedApplications` + unit tests

Let me know if you have other fields in mind

Concerning the CRD I will try to think about it. If you have suggestion they are welcome. 
The main problem is that `map[string]interface{}` is not working with kubebuilder. That's why I had to use the JSON with Raw String https://github.com/kubernetes-sigs/controller-tools/issues/636. And I don't think it is possible to declare fields inside the Json

**Comment by crenshaw-dev** [comment]
@speedfl would you mind resolving conflicts?

Makes sense w.r.t. the CRD. I think it's fine to leave it plain-json.

**Comment by speedfl** [comment]
@crenshaw-dev Thanks for your time. I just rebased and solved conflicts.

**Comment by crenshaw-dev** [comment]
@speedfl I like the code. But I think this is a big enough change that it deserves a proposal. Want to make sure I'm not missing any major design drawbacks. I wrote a draft here: https://github.com/argoproj/argo-cd/pull/12843

I still think the loss of CRD validation is a fairly major drawback. Is there some way we could leave the full spec in the CRD but enable "preserveUnknownFields"? Of course, in the controller code we'd need to unmarshal to a "fake" version of the CRD structs with the `template` field containing plain-JSON. But it seems like that should be possible w/ kubebuilder?

**Comment by speedfl** [comment]
@crenshaw-dev I did like usual a `make codegen-local` but I get an error in the integreation tests checj changes to generated code. Do you know what could be the reason ?

**Comment by crenshaw-dev** [comment]
Probably a version difference. Try running `make install-go-tools-local && make install-codegen-tools-local`.

**Comment by speedfl** [comment]
All done @crenshaw-dev Have a good weekend :)

**Comment by vl-kp** [comment]
any update?

**Comment by speedfl** [comment]
@vl-kp I will take it back soon. I think it could be interesting to merge it just after the official release 2.7 so that we have time to test it for 2.8. it is a quite big PR. what do you think @crenshaw-dev

**Comment by crenshaw-dev** [comment]
Yep, that makes sense. I also wanna make some quick effort to see if we can still use the ApplicationSpec struct for CRD generation but use preserve-fields to make sure the code can access all fields. I just haven't had time to try it.

**Comment by speedfl** [comment]
@FCosta999 I am sorry but I am not sure I will be able to work on this one for 2.8 but I can prioritize.
@crenshaw-dev did you have time to check the crd generation ?

**Comment by blakepettersson** [comment]
This has been superceded by #14893 right?

**Pull request closed without merging**
