### PR TITLE
feat: add support for gzipped policy files

### PR DESCRIPTION
**Pull request by erhudy**
This PR adds support for gzipping the policy files to reduce the size of the ConfigMap. Because the policy is stored in a ConfigMap, the gzipped content must be base64-encoded first, but it still ends up quite a bit smaller than plaintext.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by erhudy** [comment]
A little more detail on this; we have a quite large RBAC policy that ended up exceeding the 1 MiB maximum ConfigMap size. While this probably constitutes a horror of some sort and indeed I have questioned some of the choices that led me to this point, implementing this feature was trivial and I am PRing it here because others who have created similar messes for themselves might also find it useful.

I did not file an issue for it because I did not perceive the problem to be an Argo CD issue itself.

**Comment by crenshaw-dev** [comment]
@erhudy would this be an attractive alternative to you? https://github.com/argoproj/argo-cd/pull/17828

I'm not sure which I prefer, but I'm curious about your thoughts.

**Comment by erhudy** [comment]
> @erhudy would this be an attractive alternative to you? #17828
> 
> I'm not sure which I prefer, but I'm curious about your thoughts.

I think the other one is a more extensible solution long-term; my solution here just delays how long it'll be before somebody hits the maximum ConfigMap size again by a factor proportional to the gzip compression ratio of their policy CSVs. That being said, I don't think they're mutually exclusive options and can easily coexist together.

The genesis of my problem is that our RBAC CSV is programmatically generated by a controller of my own devising that sutures together various data sources like our internal LDAP and Gitlab repos and such, and the autogenerated CSV finally breached the 1 MiB limit, so I needed to come up with a quick workaround.

**Comment by crenshaw-dev** [comment]
To be honest, I'm not really inclined to merge. I know it's a small change, and I'm sure it functions fine, but small features add up to large maintenance burden. I'd consider this problem a far-enough edge case to not be worth the extra maintenance.

What do your options look like absent this change?

**Comment by jannfis** [comment]
> I'd consider this problem a far-enough edge case to not be worth the extra maintenance.

I agree. To me, there seems not to be too much value for the casual Argo CD user. The compressed data is neither easily readable nor writeable by means of common tooling. Also, compressing the RBAC data just shifts hitting the limit to a later point in time without solving the problem, IMHO.

**Comment by erhudy** [comment]
That's fine, then this can be closed. I will carry this as a local patch on my Argo until the other PR is merged and switch to using that mechanism at a later date.

**Pull request closed without merging**
