### PR TITLE
fix(ui): Dark theme improvements

### PR DESCRIPTION
**Pull request by rpelczar**
This PR is part of dark theme improvements along with https://github.com/argoproj/argo-ui/pull/462

Before:
image

After:
image

Before:
image

After:
image

Before:
image

After:
image

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
LGTM

**Comment by ashutosh16** [comment]
@rpelczar  The changes look good, however, could you please provide screenshots of the intended changes?

**Comment by rpelczar** [comment]
> @rpelczar The changes look good, however, could you please provide screenshots of the intended changes?

@ashutosh16 I've uploaded all screenshots to [PR in argo-ui repo](https://github.com/argoproj/argo-ui/pull/462)(I added info about that in the description), because most of the changes were there. I can upload the same screenshots here if you want.

**Comment by blakepettersson** [comment]
@rpelczar that would be good, just so we can get an idea what is different here vs the PR in argo-ui

**Comment by rpelczar** [comment]
@blakepettersson @ashutosh16 I added the screenshots.

**Review by alexmt — APPROVED** [review]
LGTM! Thank you for attaching screenshots!

**Pull request merged**
