### PR TITLE
test: bump k8s versions for e2e tests (#15765)

### LINKED ISSUE #15765: Compatibility with Kubernetes version 1.28
# Summary

The [latest version](https://kubernetes.io/releases/#release-v1-28) of Kubernetes is 1.28. In the Argocd docs the highest compatible and tested version is 1.27. See link here -> https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions

# Motivation

Argo is currently running in a cluster of ours that is on v1.27 and we would like to upgrade the cluster to v1.28, however we are unsure if this will break any functionality in argo.

# Proposal

Test Argo on Kubernetes v1.28, fix and publish any related issues, include v1.28 in the list of tested Kubernetes versions.

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Closes #15765

I think we should cherry-pick this back to release-2.9.

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
LGTM!

**Comment by louiscb** [comment]
🤘

**Comment by vini-intenseye** [comment]
Hello
has anyone deployed argocd latest version on 1.28 cluster? I continuously get the error that the 
```
Failed to load live state: failed to get cluster info for "https://kubernetes.default.svc/": error synchronizing cache state : error getting openapi resources: the server is currently unable to handle the request
Failed to load target state: failed to get cluster version for cluster "https://kubernetes.default.svc/": failed to get cluster info for "https://kubernetes.default.svc/": error synchronizing cache state : error getting openapi resources: the server is currently unable to handle the request
error synchronizing cache state : error getting openapi resources: the server is currently unable to handle the request
``
`

**Pull request merged**
