### PR TITLE
docs: fix missing type helm in doc (#7074)

### LINKED ISSUE #7074: Doc: Missing `type: helm` in repo-creds example
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have used the new `repo-creds` secret to manage helm and dependencies deployment. Authentication to main helm chart repo is managed with `repository` secret, and authentication to dependencies repositories is managed with `repo-creds` secret. 

The examples https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-repositories.yaml show how to configure private helm repo, but not https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-repo-creds.yaml

It appears from the code, the `repo-creds` for helm charts repo need the `type`
https://github.com/argoproj/argo-cd/blob/57abbf95ed160c88b2634ec4d37df9555cc74fb3/util/db/repository_legacy.go#L244

So the secret should something like : 

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: harbor-xxx-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  password: xxx=
  username: xxx==
stringData:
  url: https://registry.xxx.io
  type: helm
```

**To Reproduce**

n/a
Related to doc

**Expected behavior**

The specific helm configuration, ie the required `helm` type, should be documented 

**Screenshots**

n/a

**Version**

Doc from 
```
Commit a80656d345ca7e83d20900a04cd59c52b84f2566
```

argocd
```json
{
    "Version": "v2.1.0+d0b2d55",
    "BuildDate": "2021-08-20T05:30:54Z",
    "GitCommit": "d0b2d55e3fb7fe8b17385d6687886de41651f31b",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

n/a

### PR DESCRIPTION
**Pull request by michael12312**
Closes #7074

Signed-off-by: Wang, Mike <Jun.Wang@fmr.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@michael12312 can you explain this change a bit more? It's not clear to me that all those credential configs are meant for helm repos rather than git repos.

**Comment by michael12312** [comment]
@crenshaw-dev 
I think: as the code https://github.com/argoproj/argo-cd/blob/master/util/db/repository_legacy.go#L244 indicates, the the repo-creds for helm charts repo need the type.
So put this change in the doc.

**Comment by crenshaw-dev** [comment]
@michael12312 ah gotcha! Can you rebase and make the commit message semantic?

**Review by crenshaw-dev — APPROVED** [review]
lgtm! Just needs CI check fixes

**Comment by michael12312** [comment]
@crenshaw-dev 
I created another PR https://github.com/argoproj/argo-cd/pull/9085 
Changes are exactly the same, just commit messages are clean and semantic.
I think it's ok if you merge that PR, and close this PR without merger. Up to you.
Thanks!

**Comment by pasha-codefresh** [comment]
Closing due duplication

**Pull request closed without merging**
