### PR TITLE
Conditional resource diff customization (addresses #2382)

### PR DESCRIPTION
**Pull request by jannfis**
This PR addresses #2382 and extends resource diff customization with conditional expressions. If defined, conditions have to match (according to the match strategy) in order for the resource diff customization to be applied.

Each expression can evaluate against a given JSON pointer in the resource's spec. Currently, it supports the `is defined` and `not defined` expressions, but could be extended by other expressions in the future.

The following example would remove `/rules` part of the spec from the diff, if resource is of type `rbac.authorization.k8s.io/ClusterRole` and has both, a section for `/aggregationRule/clusterRoleSelectors` and a label `/metadata/labels/app.kubernetes.io/instance` defined.

```yaml
resource.customizations: |
    rbac.authorization.k8s.io/ClusterRole:
      ignoreDifferences: |
        conditions:
        - /aggregationRule/clusterRoleSelectors is defined
        - /metadata/labels/app.kubernetes.io~1instance is defined
        jsonPointers:
        - /rules
        matchStrategy: all
```

Also works in the application spec as follows:
```yaml
spec:
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
    - /rules
    conditions:
    - /aggregationRule/clusterRoleSelectors is defined
    - /metadata/labels/rules.my-app.org~1ignorerbac is defined
    matchStrategy: any
```

Match strategies can be one of `all` (the default, all expressions must evaluate to true), `any` (at least one expressions has to evaluate to true) or `none` (none of the expressions may evaluate to true).

### CODE REVIEW

**Comment by jannfis** [comment]
Hm, the E2E test that fails is `TestExcludedResource` which runs fine in my local tests, but failed twice in the CircleCI tests now.

**Comment by jannfis** [comment]
@alexec The tests execute successfully on CI now - sometimes, sometimes not. I suspect the failing tests were due to timeouts regarding to k3s within CircleCI being too unresponsive by times. However, I am not able to remove the label.

**Comment by jessesuen** [comment]
>  Currently, it supports the is defined and not defined expressions, but could be extended by other expressions in the future.

My first take is that I don't think we shouldn't be inventing our own expression language, nor mixing that expression language with json pointers. 

In our other projects we use: https://github.com/Knetic/govaluate and https://github.com/antonmedv/expr for argo workflows and argo rollouts, respectively.

My second thought is that the behavior of aggregated roles is well defined behavior in Kubernetes, so instead of giving users more knobs in ignoreDifferences, could we instead simply handle the diff case implicitly with understanding of aggregate roles, so that it benefits all users without additional configuration?

**Comment by jannfis** [comment]
Thanks for taking the time to review this PR and some food for thought.

> My first take is that I don't think we shouldn't be inventing our own expression language, nor mixing that expression language with json pointers.
> 
> In our other projects we use: https://github.com/Knetic/govaluate and https://github.com/antonmedv/expr for argo workflows and argo rollouts, respectively.

I fully agree with the thought about (re-) inventing an expression language. My take on this was a quick one,  but you're right, we should not reinvent any wheels here. Thanks for the pointers to the libraries. While `govaluate` looks suitable for this simple use-case, `expr` seems to be a bit over-the-top for just comparing two values once in a while.

I don't know what you mean by mixing json pointers with expression language, but isn't the json pointer just a reference to an actual value within the resource object in our case? It's like a pointer to the lvalue of the expression, so from my point of view, should be perfectly valid. 
 
> My second thought is that the behavior of aggregated roles is well defined behavior in Kubernetes, so instead of giving users more knobs in ignoreDifferences, could we instead simply handle the diff case implicitly with understanding of aggregate roles, so that it benefits all users without additional configuration?

That'd be a viable path to go, on the other hand it might not be what the users expect (i.e. automagically skip a diff). If we do this, it should be well-documented that we do it and we need to be careful whenever upstream K8s changes this behaviour.

But even if we choose to handle aggregated cluster roles natively, I think giving the user more ways than ApiGroup/Kind/Name combination to control when to skip diffing of resources would be a handy feature to have.

However, I'm not very opinionated about this, and my original use-case is to ignore a bunch of aggregated cluster roles anyway.

So how to proceed?

**Comment by jannfis** [comment]
Closing this PR because it seems not what we want.

**Pull request closed without merging**
