### PR TITLE
feat: tests for build policy and conditions in app cmd

### PR DESCRIPTION
**Pull request by pasha-codefresh**
More tests for app cmd

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
LGTM! Waiting to merge, because I want to see what the coverage bot says. :-)

**Comment by pasha-codefresh** [comment]
Haha, i don't think it will increase coverage so much, but each percent is important! :)

**Comment by crenshaw-dev** [comment]
@pasha-codefresh looks like there's some non-deterministic ordering being tested. Can you take a look? https://github.com/argoproj/argo-cd/runs/5670591963?check_suite_focus=true

**Comment by pasha-codefresh** [comment]
@crenshaw-dev checking it right now

**Pull request merged**
