### PR TITLE
fix: update help info about argcd account can-i

### PR DESCRIPTION
**Pull request by haoshuwei**
fix issue [#3309](https://github.com/argoproj/argo-cd/issues/3309)
Signed-off-by: Shuwei Hao <haoshuwei24@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
Awesome, thanks a lot @haoshuwei !

**Comment by haoshuwei** [comment]
> Awesome, thanks a lot @haoshuwei !

Thanks for your approval. By the way, how can I retrigger the `Semantic Pull Request` check

**Comment by jannfis** [comment]
> Thanks for your approval. By the way, how can I retrigger the `Semantic Pull Request` check

You can re-trigger it by editing the title of the PR. It was missing a whitespace after `fix:`, I already changed that.

**Comment by haoshuwei** [comment]
> > Thanks for your approval. By the way, how can I retrigger the `Semantic Pull Request` check
> 
> You can re-trigger it by editing the title of the PR. It was missing a whitespace after `fix:`, I already changed that.

It's so kind of you, thanks again.

**Pull request merged**
