### PR TITLE
refactor: update gitops engine version (issue #3781)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by keithchong** [comment]
The ArgoCD test changes that I made must be part of this PR.

**Review by alexmt — CHANGES_REQUESTED** [review]
@keithchong can you please fix unit tests: https://github.com/argoproj/argo-cd/pull/4489/checks?check_run_id=1211039320 . I guess just remove failed `TestAppOfAppsHealth` since we don't have a built-in app health assessment anymore.

**Comment by keithchong** [comment]
Hi @alexmt, the test change is now included.  Checks have passed.

**Review by alexmt — APPROVED** [review]
LGTM. Thank you @keithchong !

**Pull request merged**
