### PR TITLE
feat:  Extra Helm values from external git repo #5826

### LINKED ISSUE #5826: independent version controlled helm values file
# Summary

followup on #2719 reopening this proposal. The author closed it but I disagree with the conclusion and believe this should still be pursued.

# Motivation

To not allow the values file to be independently version controlled and checked into git in my opinion goes against the spirit of gitOps and forces design that is not ideal. In abandoning this proposal you closely couple the snowflake values/desired results of a single install to the chart itself.

This means either

a) for every given set of values files for an install the entire helm chart has to be replicated just for the values file.
or
b) the helm chart itself requires every possible desired values file preexisting within it.

so if I have three environments managed by 3 teams, but all three of those teams can reference a chart I designed, this means either all 3 of these teams must replicate the entire chart and modify it uniquely for their scenario even though I've given read/pull access to the chart and their argocd instance can reference it directly. Why do that when they can reference the chart and check in just the values?

or the reverse:
for each of these 3 teams I have to preload their values files in my chart. so they can update it, I now have to give them push/write access to my repo, or they have to tell me what they want if thats not their role and I have to add it.

Furthermore this seems to be intentional with helm. With helm, we can reference a chart, designed by someone else and version control our values file. Not allowing this takes away an option we have with helm itself although I admit having the inline values in the app object helps bridge that gap...but an independent values file route can be used both by someone just using regular helm AND someone using argocd.

In my mind decoupling the two is superior in many ways...maybe not every way, but many.
Indeed, this is a design choice and I think you should do w/e works best for your situation but I think version controlling the values file independently should at least be an option, alongside having the inline values of the argo app object, or cloning the entire chart and putting your own values file in it. Right now we don't have that option.

# Proposal

same as 2719 something like this:

Proposal
```
...
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: my-chart
    targetRevision: 1.0.0
    helm:
      valuesRepo: https://gitlab.com/someproject/path.git
      valuesFiles:
        - values/some/value.yaml
```

### PR DESCRIPTION
**Pull request by KaiReichart**
# Feature: External Helm values from git

CLOSES #5826

This PR allows for external values.yaml from other git repos in a helm installation. 

**Sample application.yaml**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-test
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.5.8
    helm:
      valueFiles:
        - values.yaml
      externalValueFiles:
        - repoURL: https://github.com/KaiReichart/argo-test-values.git
          targetRevision: main
          valueFiles:
            - values.yaml
    chart: mysql
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
```

Current State:

 - [x] Created API changes
 - [x] correct rendering in repo-server
 - [x] UI changes
 - [x] documentation

**CAVEATS:**
Due to the way the caching system works, changes in external repos will only be checked when performing a hard refresh. Will address this in another PR.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by topikachu** [comment]
@KaiReichart This change is very useful. Would you please fix the conflict and work with argocd team?
Thanks

**Comment by KaiReichart** [comment]
Could a maintainer please have a look at what is going on with the `Check changes to generated code` test? I don't really understand what the problem is or how to fix it...

**Comment by wilddeuces** [comment]
I highly upvote this feature! Its necessary for ArgoCD to use different repos for configuring values!

Thanks @KaiReichart for this approach

**Comment by andrejpetras** [comment]
Hi @alexmt could help us with the fix here?

**Comment by kofl91** [comment]
does this branch need a rebase to pass the test against the latest code gen test?

**Review by kofl91 — APPROVED** [review]
A very compelling feature for ArgoCD with Helm. Often configurations are stored independent of the official Helm Chart releases. Recreating Helm Charts only to add domain specific configurations is tedious and with this approach unnecessary. 

The ArgoCD installation with this Branch worked in my environment and I am eagerly waiting for this to be in the official ArgoCD release. Tested and approved.

**Review by andrejpetras — APPROVED** [review]

**Review by wilddeuces — APPROVED** [review]

**Comment by topikachu** [comment]
@alexmt Would you please merge this to the master?

**Review by mbevc1 — APPROVED** [review]

**Comment by tinkerborg** [comment]
I ran into one issue trying to test this PR: the new code replaces `/` with `_` when generating local repo paths, where the git client code replaces both `:` and `/`. This caused the repo to be checked out, but `helm template` to receive an incorrect path to the values file.

Also this did not support private repos.

@KaiReichart - I opened a PR to your feature branch fixing the path issue and adding private repo support.

**Review by arturkasperek — APPROVED** [review]
lgtm

**Comment by hi-usui** [comment]
Related: https://github.com/argoproj/argo-cd/issues/1413 https://github.com/argoproj/argo-cd/issues/2719 https://github.com/argoproj/argo-cd/issues/2789 https://github.com/argoproj/argo-cd/issues/3988  https://github.com/argoproj/argo-cd/issues/5065

Think many people would be excited to test this feature—looks very useful. Is the merge conflict for generated API docs `pkg/apis/application/v1alpha1/generated.pb.go` an issue? Can submit a PR to @KaiReichart's branch to refresh docs just to get this through

**Comment by seizadi** [comment]
I had some questions about the externalValueFiles array, I see from the unit tests that the higher order values files override lower number in array. I also wanted to know if they are processed by a helm template engine? I would like the multiple externalValueFiles like:
- https://github.com/seizadi/dc-repo/blob/main/envs/values.yaml
- https://github.com/seizadi/dc-repo/blob/main/envs/dev/values.yaml
- https://github.com/seizadi/dc-repo/blob/main/envs/dev/minikube/values.yaml

They would get built to resolve the template values:
https://github.com/seizadi/dc-repo/blob/main/build/dev/minikube/cmdb.yaml#L5

**Comment by rouke-broersma** [comment]
I'm very excited for this feature but I have some concerns about keeping the chart and the values.yaml versions in sync with each other without some kind of dynamic version control for the values target revision. See my comment here:

https://github.com/argoproj/argo-cd/issues/3988#issuecomment-885727046

**Comment by KaiReichart** [comment]
> I had some questions about the externalValueFiles array, I see from the unit tests that the higher order values files override lower number in array. I also wanted to know if they are processed by a helm template engine? I would like the multiple externalValueFiles like:
> 
> * https://github.com/seizadi/dc-repo/blob/main/envs/values.yaml
> * https://github.com/seizadi/dc-repo/blob/main/envs/dev/values.yaml
> * https://github.com/seizadi/dc-repo/blob/main/envs/dev/minikube/values.yaml
> 
> They would get built to resolve the template values:
> https://github.com/seizadi/dc-repo/blob/main/build/dev/minikube/cmdb.yaml#L5

@seizadi this basically does exactly the same as `helm template XXX ./chart -f values1.yaml -f values2.yaml -f values3.yaml `, with later yamls overwriting earlier ones. No templating is done, just basic helm functionality

**Comment by KaiReichart** [comment]
> I'm very excited for this feature but I have some concerns about keeping the chart and the values.yaml versions in sync with each other without some kind of dynamic version control for the values target revision. See my comment here:
> 
> [#3988 (comment)](https://github.com/argoproj/argo-cd/issues/3988#issuecomment-885727046)

@rouke-broersma this is exactly what the field `targetRevision` is for. You could have tags (or branches) in your repos that contain the version specific value files, and then reference these in your `application.yaml`. 
So you can either reference `main` in `application.yaml` and manually keep your 2 repos in sync or reference a specific version branch and update `application.yaml` when you want to update the application. 

However this isn't a problem specific to this implementation, but rather to the whole approach of splitting chart and values into different repos.

**Comment by rouke-broersma** [comment]
> > I'm very excited for this feature but I have some concerns about keeping the chart and the values.yaml versions in sync with each other without some kind of dynamic version control for the values target revision. See my comment here:
> > [#3988 (comment)](https://github.com/argoproj/argo-cd/issues/3988#issuecomment-885727046)
> 
> @rouke-broersma this is exactly what the field `targetRevision` is for. You could have tags (or branches) in your repos that contain the version specific value files, and then reference these in your `application.yaml`.
> So you can either reference `main` in `application.yaml` and manually keep your 2 repos in sync or reference a specific version branch and update `application.yaml` when you want to update the application.
> 
> However this isn't a problem specific to this implementation, but rather to the whole approach of splitting chart and values into different repos.

We are planning to put the application.yaml and the values.yaml in the same repo. Argo could theoretically (perhaps argo already does this?) tag the application with the git revision it comes from. If I could then specify in the application something akin to

```
externalValueFiles:
- fromApplicationRepo: true
  withApplicationRevision: true
  valueFiles:
   - values.yaml
```

That would be epic and solve the problem of keeping them in sync (if you use the same repo for the application and values).

I understand of course that this is not what you're contributing in the PR but do you think it would be a feasible solution to the sync issue?

**Comment by tinkerborg** [comment]
@KaiReichart Did you want me to send you another PR to fix the codegen conflict since I caused it? We really need to coordinate this w/ approval and merge, or else it's going to keep cropping up as other PRs get merged.

**Comment by KaiReichart** [comment]
@tinkerborg sure please do, this is only going to be a case of running `make codegen` to generate the necessary files.

**Comment by tinkerborg** [comment]
> @tinkerborg sure please do, this is only going to be a case of running `make codegen` to generate the necessary files.

Hmm, actually your repo needs to be updated w/ upstream master. I tried fetching your branch, merging argoproj/master and running the codegen. The conflict resolved fine but the commit history on the PR was a mess. Might be easier for you to do it. This is going to need to be repeated every time an upstream change involves codegen, until this branch is merged though...

**Comment by KaiReichart** [comment]
I'll do it, but this is the 3rd time I'm doing this and none of the ArgoCD maintainers has even acknowledged this PR, so I'm a bit hesitant about always keeping it up to date with the generated code until the maintainers at least signal any kind of interest in this feature...

**Comment by KaiReichart** [comment]
> > @rouke-broersma this is exactly what the field `targetRevision` is for. You could have tags (or branches) in your repos that contain the version specific value files, and then reference these in your `application.yaml`.
> > So you can either reference `main` in `application.yaml` and manually keep your 2 repos in sync or reference a specific version branch and update `application.yaml` when you want to update the application.
> > However this isn't a problem specific to this implementation, but rather to the whole approach of splitting chart and values into different repos.
> 
> We are planning to put the application.yaml and the values.yaml in the same repo. Argo could theoretically (perhaps argo already does this?) tag the application with the git revision it comes from (app-of-apps pattern). If I could then specify in the application something akin to
> 
> ```
> externalValueFiles:
> - fromApplicationRepo: true
>   withApplicationRepoRevision: true
>   valueFiles:
>    - values.yaml
> ```
> 
> That would be epic and solve the problem of keeping them in sync (if you use the same repo for the application and values).
> 
> I understand of course that this is not what you're contributing in the PR but do you think it would be a feasible solution to the sync issue?

I think that would actually be a really good approach. This would have to be a separate Feature Request though after this PR has been merged

**Comment by tinkerborg** [comment]
> I'll do it, but this is the 3rd time I'm doing this and none of the ArgoCD maintainers has even acknowledged this PR, so I'm a bit hesitant about always keeping it up to date with the generated code until the maintainers at least signal any kind of interest in this feature...

It was mostly a plea for attention from the maintainers rather than an expectation that you'd keep doing this.

@alexmt , @jessesuen could you weigh in here? This feature would be very useful for deploying third party charts, deploying multiple workloads across different repos with a common chart, etc. The latter is my current use case, we have one standard chart shared across a few hundred microservices. We also have an additional layer of helm values stored in a separate repo managed by our infrastructure team. 

Currently we need to use plugin scripts to achieve this. This introduces a lot more complexity but also makes a poor UX for developers, as they can't easily see or override helm values in the Argo UI.

**Comment by rubenssoto** [comment]
Hello guys,

Is there any chance this will be merged soon?

Very useful feature!

**Comment by yosefkri** [comment]
Anyone know when this feature will be merge?
Very important feature!

**Comment by catalinpan** [comment]
This is a great feature, thanks everyone for your contribution!
There is a [pending DCO](https://github.com/argoproj/argo-cd/pull/6280/checks?check_run_id=3244935469) for this PR, @Reuuke can we have some help with this please?

**Comment by tuananh** [comment]
I need this. THank you for the hard work :)

**Comment by namcxn** [comment]
Hello, very useful feature! when this feature will be merge?

**Comment by michalziobro** [comment]
me and my team are also really looking forward to have this feature, huge improvement!

**Comment by guy-frontegg** [comment]
We are waiting for this so much. It's super important

**Comment by guy-frontegg** [comment]
How do you guys solving this issue without this feature?

**Comment by tinkerborg** [comment]
> How do you guys solving this issue without this feature?

I ended up writing a controller inspired by the [application set controller](https://argocd-applicationset.readthedocs.io/en/stable/), but with I think more flexibility. Basically it allows us to pull in values from a number of sources, merge them, and then use them anywhere in an application spec, e.g. in the helm.values field. Hopefully my employer will let us open source it.

**Comment by guy-frontegg** [comment]
> > How do you guys solving this issue without this feature?
> 
> I ended up writing a controller inspired by the [application set controller](https://argocd-applicationset.readthedocs.io/en/stable/), but with I think more flexibility. Basically it allows us to pull in values from a number of sources, merge them, and then use them anywhere in an application spec, e.g. in the helm.values field. Hopefully my employer will let us open source it.

I didn't fully understand. You wrote a controller that gather the values from external sources, but how did you merged them into the source.helm resource? I wonder

**Comment by tinkerborg** [comment]
> > > How do you guys solving this issue without this feature?
> > 
> > 
> > I ended up writing a controller inspired by the [application set controller](https://argocd-applicationset.readthedocs.io/en/stable/), but with I think more flexibility. Basically it allows us to pull in values from a number of sources, merge them, and then use them anywhere in an application spec, e.g. in the helm.values field. Hopefully my employer will let us open source it.
> 
> I didn't fully understand. You wrote a controller that gather the values from external sources, but how did you merged them into the source.helm resource? I wonder
> 
> Oh wait. Your controller created the application resource by it self from your input as I understand?

Correct, check out the application set controller I linked. It's the same idea, we just needed something more flexible for our use case. But maybe it can solve yours.

**Comment by randomvoids** [comment]
> This is a great feature, thanks everyone for your contribution!
> There is a [pending DCO](https://github.com/argoproj/argo-cd/pull/6280/checks?check_run_id=3244935469) for this PR, @Reuuke can we have some help with this please?

@Reuuke can you please take a look at the DCO?

@KaiReichart What would be the next steps if he doesn't come back to sign off on the DCO?

**Comment by shuker85** [comment]
Still nothing ?

**Comment by jessesuen** [comment]
Hey there, I'll bring up this PR enhancement in tomorrow's contributor's meeting to discuss the approach. I think there are some RBAC considerations that need to be in place (e.g. the repo should be in the allow list in the project). But I do recognize the usability improvements that this feature will bring in.

**Comment by jessesuen** [comment]
Also, there are some technical considerations that this feature will need to address. Namely, the manifest caching which Argo CD does with respect to repositories (both helm and git). Until now, Argo CD benefited from the assumption of a single repo per application to detect changes and to cache the results. But this enhancement now requires us to look at both the Helm repo "HEAD" as well as the external git repo HEAD and invalidate the cache if either one of them changes.

I'm not sure if this enhancement takes that into consideration. The desired behavior is: if a new commit is pushed to the external values in git, we would want to detect this upon next app refresh and invalidate the existing cache entry.

**Comment by rouke-broersma** [comment]
> Also, there are some technical considerations that this feature will need to address. Namely, the manifest caching which Argo CD does with respect to repositories (both helm and git). Until now, Argo CD benefited from the assumption of a single repo per application to detect changes and to cache the results. But this enhancement now requires us to look at both the Helm repo "HEAD" as well as the external git repo HEAD and invalidate the cache if either one of them changes.
> 
> I'm not sure if this enhancement takes that into consideration. The desired behavior is: if a new commit is pushed to the external values in git, we would want to detect this upon next app refresh and invalidate the existing cache entry.

I don't think the caching concerns are implemented in this pr.

From the pr description:

> CAVEATS:
> Due to the way the caching system works, changes in external repos will only be checked when performing a hard refresh. Will address this in another PR.

**Comment by eytanhanig** [comment]
@KaiReichart Can you please update/rebase this so there are no conflicts and sign-off on your contribution to resolve the DCO? Instructions for doing so can be found [here](https://github.com/argoproj/argoproj#news).

**Comment by rouke-broersma** [comment]
> @KaiReichart Can you please update/rebase this so there are no conflicts and sign-off on your contribution to resolve the DCO? Instructions for doing so can be found [here](https://github.com/argoproj/argoproj#news).

The DCO is caused by @Reuuke and not @KaiReichart

**Comment by tyrken** [comment]
FWIW I suspect my teams' use case aligns more with @rouke-broersma [comment](https://github.com/argoproj/argo-cd/pull/6280#issuecomment-888929627) earlier, and was a bit surprised in this PR to see the main ArgoCD Application CRD's `source` field & `targetrevision` used to point to the helm chart, rather than the more "local" thing which would be the values file we fine-tune for our deployment.

I did later look a bit at the Application CRD's `spec.source.chart` property, as Helm (the binary) is actually quite flexible as regards the  chart "name" you pass in - if it's actually a URL then it would download & unpack that URL to use as the chart data.  Unfortunately our chart repo at the time required authentication so I never completed hacking/testing, but would seem more in keeping a way of allowing the app to get it's config from two places.

Re caching/invalidation - helm charts built for distribution are meant to be immutable (see https://github.com/helm/helm/issues/3084) though the physical spec doesn't absolutely enforce this.  Hence I'd like ArgoCD to monitor & update if it see changes to the git repo storing the values file (if targetRevision == HEAD), but don't see any need to monitor/invalidate cache if the repo target changes.

**Comment by karma-git** [comment]
Hi everyone, any updates here?
Our team is waiting for this PR more than 2 months, is there any chance that PR will be merged soon?
Thanks.

**Comment by kopaygorodsky** [comment]
I would like to help with this PR to speed up the process :)

**Comment by odelreym** [comment]
Hi there and good job

Wanted to ask a question regarding the PR. Then the following ApplicationSet should work when merged, right?

``` 
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: services
spec:
  generators:
  - list:
      elements:
      - appName: 'app1'
        repo: 'git@bitbucket.org:repo1/path.git'
        version: branch
      - appName: 'app2'
        repo: 'git@bitbucket.org:repo2/path.git'
        version: branch
  template:
    metadata:
      name: '{{appName}}'
    spec:
      project: default
      source:
        repoURL: '{{repo}}'
        targetRevision: '{{version}}'
        path: deployment
        helm:
          valueFiles:
           - values.yaml
        externalValueFiles:
        - repoURL: 'git@bitbucket.org:repo3/path.git'
          targetRevision: version: master
          valueFiles:
            - values.yaml
      destination:
        namespace: default
        server: https://kubernetes.default.svc

**Comment by ishitasequeira** [comment]
Hi @KaiReichart , are you still working on this PR? Is it still in your list?

**Comment by loeken** [comment]
will this be merged? where are we stuck?

**Comment by ArshiAAkhavan** [comment]
@tyrken approach seems more reasonable to me 
is it taken into consideration?

**Comment by ArshiAAkhavan** [comment]
@tyrken approach seems more reasonable to me 
is it taken into consideration?

**Comment by ashish1099** [comment]
any idea when is this going to get merged ?

**Comment by KlavsKlavsen** [comment]
Soo looking forward to this feature.. We use a central repo - that we sync to every location - which has helm charts etc. and common value files.. and then for each team - they have their own cluster they manage and store values files "to override defaults" - and decide which applications they run - in their own repo.
This way we can be strict about what we merge (and review properly) in the central repo that ALL teams use - which also means we have coordination of versions across all clusters.. But at the same time, each team has their own repo - that applies to ONLY their cluster, where they can manage exactly which applications they run and have override valuesfile in there. 
Works great - without having it be "wild west" where anyone can merge in the repo that affects every cluster :)

**Comment by begemotik** [comment]
@alexmt, Is it officially out of scope for the release v2.3 now? The community seems to be craving for that feature

**Comment by ltmleo** [comment]
I also use helm chart as a central repo, and each microservice has its own value, this feature will work great for me.

**Comment by lucaslobolp** [comment]
I also use helm chart as a central repo, and each microservice has its own value, this feature will work great for me.

**Comment by ArshiAAkhavan** [comment]
could any one give us an update about this pr?
perhaps if the pr is not well implemented, the community can provide you with another one

or if its not towards argocds main goals, let us know so we can make our own forks

**Comment by ishitasequeira** [comment]
@ArshiAAkhavan , we have an ongoing [proposal doc](https://github.com/argoproj/argo-cd/pull/8322) on this PR that has been started and is being discussed in the community. Reviews on it would be helpful.

**Comment by YperXristis** [comment]
@kostis-codefresh @romulus-ai
Here is the solution I came up with which works for me, please share it.

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: ska
  source:
    chart: kube-prometheus-stack
    helm:
      version: v3
      values: |
{{ .Files.Get "prometheus-stack-vaules.yaml" | indent 8 }}
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 34.9.0
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
    - CreateNamespace=true

**Comment by crenshaw-dev** [comment]
Closing in favor of multi-source repos, which is currently expected in 2.5.

Sorry for the wait folks, we really want to get this right.  😃

**Comment by zakkg3** [comment]
ppl reading this is looking for:  https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository

**Pull request closed without merging**
