### PR TITLE
fix(cli): copy ServerName into clientOpts in login command

### LINKED ISSUE #16266: `argocd login --port-forward` fails with `cannot find pod with selector: [app.kubernetes.io/name=]`
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

when trying to create a new argocd context using `port-forward`, the login commands fails with a new error. it worked fine in `v2.8.4`

**To Reproduce**
1. install a standard argo-cd instance to `argocd` namespace
2. extract the initial-admin-password from `argocd-initial-admin-secret` secret
3. run `argocd login --port-forward --port-forward-namespace argocd --username admin --password <pwd> --name whatever`

result:
```shell
FATA[0000] cannot find pod with selector: [app.kubernetes.io/name=] - use the --{component}-name flag in this command or set the environmental variable (Refer to https://argo-cd.readthedocs.io/en/stable/user-guide/environment-variables), to change the Argo CD component name in the CLI
```

**Expected behavior**

a new argo-cd context is created, with the name of `whatever`

**Version**

```shell
argocd: v2.9.0+9cf0c69.dirty
  BuildDate: 2023-11-06T15:07:24Z
  GitCommit: 9cf0c69bbe70393db40e5755e34715f30179ee09
  GitTreeState: dirty
  GoVersion: go1.21.3
  Compiler: gc
  Platform: darwin/arm64
```

### PR DESCRIPTION
**Pull request by noam-codefresh**
Fixes #16266

this will pass the `ServerName` flag value (or `ARGOCD_SERVER_NAME` env var) from the `globalClientOpts` to the options used by the login command. when trying to login using `--port-forward` this value is needed.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
LGTM!!!

**Review by pasha-codefresh — APPROVED** [review]

**Comment by thesuperzapper** [comment]
@crenshaw-dev @pasha-codefresh it seems like something went wrong as this has not made its way into the `2.9.2` argocd cli version.

**Comment by thesuperzapper** [comment]
@pasha-codefresh I think this is still not chery-picked into 2.9, are we only going to fix this bug in 2.10?

**Comment by noam-codefresh** [comment]
the fix was merged to the main branch before `release-2.10` started, so it is included in 2.10.
i don't know why it never got cherry-picked to 2.9. i guess right now it doesn't matter much.

**Pull request merged**
