### PR TITLE
chore(deps): upgrade nhooyr.io/websocket dependency

### PR DESCRIPTION
**Pull request by jmeridth**
Upgrade nhooyr.io/websocket from 1.8.6 to 1.8.7 due to **high** security issue

Was solved in dependency with https://github.com/nhooyr/websocket/pull/291

`Fix DOS attack from malicious pongs`

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @jmeridth!

**Comment by jmeridth** [comment]
@crenshaw-dev can we cherry-pick this to 2.8/2.7? we do something like [this](https://github.com/argoproj/argo-cd/pull/14917#issuecomment-1668040404) right? Or does this need to wait for next CVE release?  Thank you.

**Comment by crenshaw-dev** [comment]
@jmeridth yep, we should cherry-pick! Dependency cherry-pick confuse the bot. Can you open PRs manually for release branches release-2.6 through release-2.8?

**Pull request merged**
