### PR TITLE
feat: add versioning to argocd docs

### PR DESCRIPTION
**Pull request by reginaelyse**
This PR is to add versioning to the Argo CD docs. The core functionality of this versioning is done through [mike](https://github.com/jimporter/mike). Related to issue #5031.

Additional functionality:
- if the user is on version of the docs NOT called "latest", they get an a warning message (seen below) that will provide a link to the most current docs.
- if the user clicks on a link where version is not specified in the URL, they will be redirected to the latest version of the docs.

Screenshots:
argocddocs-latest
argocddocs-olderversion

https://user-images.githubusercontent.com/50851526/102788557-cd9dc880-4370-11eb-93d4-8bdf80feddf7.mp4

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
Thank you for implementing the version selector and banner! The only concern I have is the maturity of mike and maintenance overhead.

I want to propose to use https://readthedocs.org/ instead of mike. It automates version management and supports mkdocs . 
We did not know how to add a version selector before. I was inspired by your PR and implemented it for [argocd-notifications](https://github.com/argoproj-labs/argocd-notifications/blob/master/docs/assets/versions.js) docs

image

What do you think? @reginapizza

**Comment by alexmt** [comment]
Changes in argocd-notifications still don't have banner that notifies users about the latest version. We could use code implemented in this PR to add it.  https://readthedocs.org/  inject information about current version into `READTHEDOCS_DATA.version` global javascript variable. 

If you like the idea to use https://readthedocs.org/  I would suggest implement banner in argocd-notifications and then we can re-use this JS file in argocd and argocd-image-updater.

**Comment by reginapizza** [comment]
Hey @alexmt ! This should be good now, but in order to move it to the argocd project the project name in versions.js will just need to be changed out of my project, unless you want to keep it there since I made you a maintainer of it anyway. Up to you. 

Here are screenshots of it, but you can also [see it in action here](https://argo-cd.readthedocs.io/en/latest/). 
argocd-docsversioning
argocd-docsversioning2

**Comment by jannfis** [comment]
Hey, this really awesome @reginapizza! I really like how you integrated the versions in the top bar, instead of having the default black float of RTD. And the banner is awesome, too.

I have one minor request for change: Since we want to redirect the user to the current `stable` version of the documentation by default (`latest` may contain information about yet unreleased stuff), we should IMHO change the logic to display the banner if the selected version is not `stable`. And maybe change the banner for `latest` version to reflect that some of the information in the documentation might not yet be released.

I also wonder if it is possible to find out which version of the docs in RTD corresponds to `stable` programmatically, and if a user selects the specific version, will not display the banner?

**Comment by reginapizza** [comment]
@jannfis Thank you! Regarding your requests,

>we should IMHO change the logic to display the banner if the selected version is not stable. And maybe change the banner for latest version to reflect that some of the information in the documentation might not yet be released.

I can totally do this no problem. There is a setting you change (see below) in RTD project settings and I can easily change the default version to stable. I can also change the link so that it redirects from other versions to stable, and I can add a banner to warn the user when they are on latest branch that information might not yet be released. 

> if it is possible to find out which version of the docs in RTD corresponds to stable programmatically, and if a user selects the specific version, will not display the banner?

I'm not sure about this though... this what RTD gives you to work with, I don't think that I can have an alias for anything besides "latest", but I'm not positive. I can try to look into it, unless @alexmt knows?
RTDsettings

**Comment by alexmt** [comment]
That looks awesome @reginapizza! Thank you!

Agree with @jannfis comment. We should assume default version is `stable`.  I've tried to find if RTD inject value of `default` version but looks like this is not available. I think it is ok if we just hardcode `stable` in javascript

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
:tada:

Can we cherry-pick this into 1.8 branch, so we can already activate a 1.8 version of the docs in addition to master :)

I have re-configured RTD default branch to `master`,  so `latest` version of RTD now points there.

**Comment by alexmt** [comment]
You are reading my minds :) doing it right now

**Pull request merged**
