### PR TITLE
Adds support for /api/v1/account* via HTTP. Fixes #2664

### LINKED ISSUE #2664: update account password from API resulted 404
Checklist:

* [x] I've searched in the docs and FAQ for my answer: http://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**
I'd like to update argocd account password via argocd API; however, I am getting 404s. What am I missing?
```
$ curl -X PUT https://x.com/api/v1/account/password -d '{"currentPassword": "argocd-server-7c95d549d4-m56b7", "newPassword": "xxx"}' --cookie "argocd.token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzMxNjM0MDMsImlzcyI6ImFyZ29jZCIsIm5iZiI6MTU3MzE2MzQwMywic3ViIjoiYWRtaW4ifQ.GRIntetarjn_GAj1jt5cPyLBpwpHfgcwdq9z5QRiyrc"
Not Found
```

**To Reproduce**
Run the curl against any argocd 1.2.4 deployment

**Expected behavior**

The PUT command should be able to update account password

**Version**

```shell
argocd: v1.2.1+a6a394b
  BuildDate: 2019-09-12T17:16:32Z
  GitCommit: a6a394ba93a2a56981a45b9395e245e5210eaa35
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.2.4+ad7a69a
  BuildDate: 2019-10-23T20:06:50Z
  GitCommit: ad7a69a79883b7767cbeb88ca9a36d28277bd4ab
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Fixes #2664

### CODE REVIEW

**Comment by alexec** [comment]
Should we back-port?

**Comment by jannfis** [comment]
> Should we back-port?

I think: yes.

**Review by jannfis — APPROVED** [review]
LGTM.

**Comment by dontreboot** [comment]
When will the changes be ready?

**Review by alexmt — APPROVED** [review]

**Comment by alexec** [comment]
Back-ported to v1.3

**Pull request merged**
