### PR TITLE
fix(appset): Post selector with Go templates in ApplicationSet (cherry-pick #13584)

### PR DESCRIPTION
**Pull request by m13t**
Cherry-picked fix(appset): Post selector with Go templates in ApplicationSet (#13584)

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@m13t looks like the unit test merge had issues. Can you check that CI failure?

Some CI failures are expected on cherry-picks (like codegen). We need to fix those. But unit tests should pass.

**Comment by m13t** [comment]
@crenshaw-dev I'm struggling with this to be honest. I've created the manual PRs to cherry-pick the original PR onto master, but it looks like these release branches are so out of sync. Doing a comparison of the release branches and master shows the tests to be significantly different. Not sure what the best course of action is with this.

**Comment by crenshaw-dev** [comment]
> I checkout out each of the release branches and cherry-picked

Yep, that's the correct way to do it!

**Comment by crenshaw-dev** [comment]
I'll take a look, maybe I can sort it. It helps having more context about the surrounding changes. :-)

**Comment by crenshaw-dev** [comment]
@m13t I think I fixed it! Let's see how tests go.

**Comment by m13t** [comment]
> @m13t I think I fixed it! Let's see how tests go.

I see, so just a case of manually adding back in the missing bits.

**Comment by crenshaw-dev** [comment]
I think the problem was that you modified a new test (`TestMatchValuesGoTemplate`) which doesn't yet exist in release-2.7. So when you tried to merge, it applied those changes to an unrelated test (`TestTransForm`). 

My first attempt to fix the problem inadvertently deleted `TestTransForm`. So my second commit just added it back.

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@m13t do you think you could mimic my fixes on the other two cherry-pick PRs?

**Pull request merged**
