### PR TITLE
fix: add tooltip for long title in list view ui

### LINKED ISSUE #9752: Long application names become unreadable in the UI - List view
# Summary

Would be nice to have a tooltip for application name on List view.

# Motivation

Long application names become unreadable in the UI in List view

# Proposal

Issue #9241 addressed this for Tiles view.

### PR DESCRIPTION
**Pull request by saumeya**
closes #9752 

Screenshot from 2022-06-27 17-38-30

Signed-off-by: saumeya <saumeyakatyal@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by ciiay — CHANGES_REQUESTED** [review]
Hi Saumeya, I see you hard coded the length where you want to add the tooltip. There should be a better/smarter way to decide whether or not to display the tooltip. Check this [link](https://thewebdev.info/2021/04/17/how-to-check-for-text-overflow-ellipsis-in-an-html-element/) out and see if it makes sense to you.

**Comment by saumeya** [comment]
> Hi Saumeya, I see you hard coded the length where you want to add the tooltip. There should be a better/smarter way to decide whether or not to display the tooltip. Check this [link](https://thewebdev.info/2021/04/17/how-to-check-for-text-overflow-ellipsis-in-an-html-element/) out and see if it makes sense to you.

Makes sense Yi, I would look into this. Thanks!

**Comment by saumeya** [comment]
Hi @ciiay I took a look at this suggestion, the problem to implement that is we need to use useRef hook to get the div to check if ellipsis exists. Given that this field is within a table (loop) the ref doesn't get updated each time. There could be other possible solutions, but I guess given that this issue is minor, a constant length is fine.

**Comment by keithchong** [comment]
I agree with @ciiay .  The constant there doesn't fit in all situations.  For example, if you adjust the browser's zoom (zoom out), so that there is no truncation, then the tooltip still appears.

Why not just show the tooltip all the time, whether it is needed or not?  The Source URL in the column to the right of the Name, does that:

https://github.com/argoproj/argo-cd/blob/3f858f58f42aeafd4029872e1fe7690d5c7d1cbd/ui/src/app/applications/components/applications-list/applications-source.tsx#L10

**Comment by saumeya** [comment]
@keithchong @ciiay  could you review and merge?

**Review by keithchong — APPROVED** [review]
LGTM. Something that is independent of this fix, but the layout of the row seems unpolished when the width of the table is decreased.

**Pull request merged**
