### PR TITLE
fix: make test-tools-image target work on apple silicon (#9807)

### LINKED ISSUE #9807: make test-tools-image fails on Apple silicon
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

On any M1 Mac, the `test-tools-image` make target fails with the following error:

```
 => ERROR [stage-5 13/21] COPY --from=redis /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/                         0.0s
 => ERROR [stage-5 14/21] COPY --from=redis /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/                      0.0s
------
 > [stage-5 13/21] COPY --from=redis /usr/lib/x86_64-linux-gnu/libssl.so.1.1 /usr/lib/x86_64-linux-gnu/:
------
------
 > [stage-5 14/21] COPY --from=redis /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 /usr/lib/x86_64-linux-gnu/:
------
failed to compute cache key: "/usr/lib/x86_64-linux-gnu/libcrypto.so.1.1" not found: not found
make: *** [test-tools-image] Error 1
```

The issue is due to lib paths being different from one CPU architecture to the next.

**To Reproduce**

Run `make test-tools-image` (or any target that depends on that one) on an M1 Mac.

**Expected behavior**

The target should work equally well for all CPU architectures; not just amd64.

### PR DESCRIPTION
**Pull request by krancour**
Fixes #9807

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
Manually tested on my laptop as well. It works thank you! 

LGTM.

**Comment by alexmt** [comment]
@crenshaw-dev just to be safe can you please try it as well?

**Comment by crenshaw-dev** [comment]
Unfortunately I'm still on Intel.  :-( @zachaller can you try?

**Comment by notfromstatefarm** [comment]
@crenshaw-dev @alexmt confirmed working on my M1!
```
 => CACHED [stage-5 12/22] COPY --from=redis /usr/local/bin/* /usr/local/bin/                                                                           0.0s
 => [stage-5 13/22] COPY --from=redis /usr/lib/linux-gnu/libssl.so.1.1 /usr/lib/linux-gnu/                                                              0.0s
 => [stage-5 14/22] COPY --from=redis /usr/lib/linux-gnu/libcrypto.so.1.1 /usr/lib/linux-gnu/                                                           0.0s
 => [stage-5 15/22] RUN mv /usr/lib/linux-gnu/libssl.so.1.1 /usr/lib/$(uname -m)-linux-gnu/ &&     mv /usr/lib/linux-gnu/libcrypto.so.1.1 /usr/lib/$(u  0.3s
 => [stage-5 16/22] COPY --from=registry /bin/registry /usr/local/bin/                                                                                  0.1s
 => [stage-5 17/22] COPY --from=registry /etc/docker/registry/config.yml /etc/docker/registry/config.yml                                                0.0s
 => [stage-5 18/22] COPY --from=node /usr/local/lib/node_modules /usr/local/lib/node_modules                                                            0.8s
 => [stage-5 19/22] COPY --from=node /usr/local/bin/node /usr/local/bin                                                                                 0.1s
 => [stage-5 20/22] COPY --from=node /opt/yarn-v1.22.4 /opt/yarn-v1.22.4                                                                                0.0s
 => [stage-5 21/22] COPY ./test/container/entrypoint.sh /usr/local/bin                                                                                  0.0s
 => [stage-5 22/22] RUN useradd -l -u 502 -d /home/user -s /bin/bash user &&     echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/user &&     mkdi  63.1s
 => exporting to image                                                                                                                                  9.6s
 => => exporting layers                                                                                                                                 9.6s
 => => writing image sha256:ffdbb73595f278952467625d5a3404dbe9f4964f61cc5bf60cb2048686a7798b                                                            0.0s
 => => naming to docker.io/library/argocd-test-tools
 ```

**Review by jessesuen — APPROVED** [review]

**Pull request merged**
