### PR TITLE
feat: Add labelSelector style to filter all generators

### LINKED ISSUE #361: Allow to filter each generator by a selector like a labelSelector
We are currently use applicationset to deploy multiple applications into a same set of clusters, but some application are just need in certain clusters. It would be greated to use a selector to post filter any generator output.

Idea:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
        - cluster: engineering-dev
          url: https://kubernetes.default.svc
          env: staging
        - cluster: engineering-prod
          url: https://kubernetes.default.svc
          env: prod
    selector:
      matchLabels:
        env: staging
  template:
    metadata:
      name: '{{cluster}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/argoproj-labs/applicationset.git
        targetRevision: HEAD
        path: examples/list-generator/guestbook/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: guestbook
```

### PR DESCRIPTION
**Pull request by farodin91**
Fixes https://github.com/argoproj/applicationset/issues/361

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@farodin91 could you run `make lint-local`?

**Comment by giepa** [comment]
Hi guys, this is a great feature, any progress on this?

**Comment by crenshaw-dev** [comment]
@giepa thanks for the bump. I think the lint error was transient. I can't figure out how to re-run the check, so I'll reopen the PR on my fork.

**Comment by crenshaw-dev** [comment]
Closing in favor of https://github.com/argoproj/argo-cd/pull/9312

**Pull request closed without merging**
