### PR TITLE
fix(ui): show orphaned as gray. fixes: #11180

### LINKED ISSUE #11180: Orphaned resources no longer have a distinct color in the UI
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

Orphaned resources no longer have a distinct color in the UI.

**To Reproduce**

View an application in the UI, and select "Show Orphaned"

**Expected behavior**
In the past, orphaned resources were grayed out, and could be visually distinguished from non-orphaned objects.

**Screenshots**

image

**Version**

```shell
v2.5.1+504da42
```

**Logs**

```
N/A
```

### PR DESCRIPTION
**Pull request by alexef**
Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

fixes: #11180 

Screenshot 2022-11-07 at 16 21 59

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Comment by alexef** [comment]
@rbreeze tiny one for your 👀 . if you know how to make the gray darker on light theme and lighter on the dark theme, I'm all ears.

**Comment by crenshaw-dev** [comment]
Did you take a peek at dark mode's behavior as well?

**Comment by alexef** [comment]
I did. it changes color, but a bit more contrast would be great

**Review by rbreeze — APPROVED** [review]
LGTM

**Pull request merged**
