### PR TITLE
fix: remove Egress NetworkPolicy for argocd-redis and argocd-redis-ha-haproxy

### PR DESCRIPTION
**Pull request by mayzhang2000**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by mkilchhofer — APPROVED** [review]

**Comment by todaywasawesome** [comment]
Rather than changing network policy could we move the init container to something that already has access like Argo CD itself?

**Comment by leoluz** [comment]
> Rather than changing network policy could we move the init container to something that already has access like Argo CD itself?

This is an interesting idea and in theory it should work. However all our tests were done with the init container defined as part of Redis itself. I'm not sure if switching it to the Argo CD pods would be the best strategy at this point as it could introduce more edge cases.
cc @mayzhang2000

**Comment by todaywasawesome** [comment]
I don't want to hold it up so I think we should move ahead and take it as an enhancement to move it later. Modifying the policy will get people unblocked but I think it's a security issue to give access for what should be a once in a lifetime execution.

**Review by todaywasawesome — APPROVED** [review]

**Comment by todaywasawesome** [comment]
On a side note I think the docs are excellent here @mayzhang2000

**Review by crenshaw-dev — APPROVED** [review]

**Comment by pramodsetlur** [comment]
I think I am hitting this (timeout) issue on v2.8.19. Is there a plan to release this as a patch to v2.8?
```
$ k logs -f argocd-redis-ha-haproxy-75449b8544-nk4t4 secret-init
Checking for initial Redis password in secret foundry/argocd-redis at key auth. 
time="2024-05-23T00:05:40Z" level=fatal msg="Post \"https://250.7.132.1:443/api/v1/namespaces/foundry/secrets\": dial tcp 250.7.132.1:443: i/o timeout"
```

**Comment by agnut92** [comment]
When this fix will be available in release?

**Pull request merged**
