### PR TITLE
feat: Added the comment to support CLI message to get extended output

### PR DESCRIPTION
**Pull request by nikzayn**
#18226
Added the comment to support CLI message to get extended output

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #18226]" or "Fixes [ISSUE #18226]" in the description to automatically close the associated issue.
* [x] I have signed off all my commits as required by [DCO]

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
@nikzayn you need to run `make codegen` locally and push generated manifests

**Comment by nikzayn** [comment]
> @nikzayn you need to run `make codegen` locally and push generated manifests

Thanks, for updating. I will do that.

**Review by ishitasequeira — COMMENTED** [review]
@nikzayn , it seems the manifests are not generated properly. Can you execute `make manifests` or `make manifests-local` and push the changes?

**Comment by nikzayn** [comment]
> make manifests

Hey @ishitasequeira, I tried running both commands but no changes are happening at the repo which I can commit.

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
Can you execute `make codegen-local`? That should fix the generated code.

**Comment by nikzayn** [comment]
> make codegen-local

I tried running this, and it gave me this error:
```
unknown flag: --output-base
make: *** [protogen-fast] Error 2
```

**Review by ishitasequeira — COMMENTED** [review]
Can you make sure you have the correct `protogen` version installed locally?

You could use `install-tools-local` to have all the correct version of tools installed

**Comment by nikzayn** [comment]
> Can you make sure you have the correct `protogen` version installed locally?
> 
> You could use `install-tools-local` to have all the correct version of tools installed

Thanks for this, I have run this command and added the changes.

**Review by ishitasequeira — APPROVED** [review]
Thanks @nikzayn !! LGTM!!

**Pull request merged**
