### PR TITLE
util/localconfig: prefer HOME env var over os/user

### PR DESCRIPTION
**Pull request by gpaul**
The os/user package is a rather hard-handed approach to acquiring the current user's home directory: it forces the current user to be in /etc/passwd combined with a `USER` environment variable, or other workarounds.

That complicates executing the argocd command in a docker container
when the UID:GID of the executing user is overridden.

This is often done in order to have files generated inside a docker
container have their ownership set to match the uid/gid of the host
user.

For example,

```sh
docker run -ti -u "$(id -u "${USER}"):$(id -g "${USER}")" argocd:latest ...
```

This PR also modifies the `make lint` target to execute inside the `dev-tools` docker container. This ensures that the tools are pinned to the correct versions and avoids moving dependencies leading to unexpected code generation changes and triggering linting errors in CI.

### CODE REVIEW

**Comment by gpaul** [comment]
I think the CI failures are unrelated to my PR

**Comment by alexec** [comment]
CI failed due to linting errors. Run ‘make lint’

**Comment by gpaul** [comment]
I see - looks like `make lint` actually passed but the `Check nothing has changed` CI step is failing. I'll look into it.

**Comment by gpaul** [comment]
I guess `make lint`, et al. are changing files, causing the `git diff` to fail. I notice that the circleci config.yaml installs `goimports` using a bare `go get` with no version pinning. I'll see if I can use the `./hack` directory to pin those versions in CI.

**Comment by gpaul** [comment]
OK - I've modified the `lint` job to execute inside the dev-tools container. This fixes the linting issues we've been seeing.

**Review by alexmt — APPROVED** [review]
LGTM! @alexec ?

**Comment by alexec** [comment]
LGTM

**Pull request merged**
