### PR TITLE
default to no gpg for Procfile - avoids missing temp dir failure

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Procfile currently assumes you're invoking it from the `start-local`, which initializes a temporary directory. 

To test:

```sh
# On master branch...
rm -rf /tmp/argocd-local
goreman start api-server controller redis repo-server ui  # This should throw an error about missing tmp dir
# On feature branch...
goreman start api-server controller redis repo-server ui  # repo-server should start up fine
```

Signed-off-by: Michael Crenshaw <michael_crenshaw@intuit.com>

### CODE REVIEW

**Comment by leoluz** [comment]
@crenshaw-dev do you see that target been invoked in any of the github actions? If it isn't there maybe @alexmt could clarify?

**Comment by crenshaw-dev** [comment]
@leoluz I'm not super familiar with github actions, but I'm guessing they're configured under .github/workflows. If so, `make run` does not appear in that directory, and it doesn't look like the run target is invoked by any github actions.

**Comment by crenshaw-dev** [comment]
@alexmt I think it already is: https://github.com/argoproj/argo-cd/blob/f46ac844b8d131863a8d583a2383ac752e1acea5/Makefile#L450

The env var is set to `true` on line 128.

**Comment by jannfis** [comment]
What exactly is the problem?

**Comment by crenshaw-dev** [comment]
@jannfis if you run `goreman start` directly (common for Argo CD devs because it's faster than `make start-local`) without having first initialized the `/tmp/argocd-local` directory, it'll fail with `repo-server | FATA[0000] stat /tmp/argocd-local/gpg/keys: no such file or directory`.

This change defaults to disabling the feature which requires that directory. `make start-local` and the e2e tests override that default and enable the gpg feature.

**Review by alexmt — APPROVED** [review]

**Pull request merged**
