### PR TITLE
chore: upgrade golangci-lint to v1.46.2

### PR DESCRIPTION
**Pull request by cippaciong**
Because:

* Installation of golangci-lint v1.45.2 is currently broken and fails
  silently due to a redacted dependency
  (https://github.com/blizzy78/varnamelen/issues/13)

This commit:

* Upgrades golangci-lint to v1.46.2

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Review by terrytangyuan — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@cippaciong cherry-picking this (https://github.com/argoproj/argo-cd/pull/9444) should fix three of those issues. The other two might require additional attention.

**Comment by cippaciong** [comment]
@crenshaw-dev I cherry picked the commit from your fork and indeed three issues were fixed. Not sure how to address the other two though, any suggestion? Should I take care of that in this PR?

**Comment by crenshaw-dev** [comment]
@cippaciong yeah let's try to get it fixed in this PR if you have time. Just run `make lint-local`. The command will print the locations of the issues and give a short description. The fixes should be reasonably clear from the error messages.

**Comment by cippaciong** [comment]
@crenshaw-dev the two missing issues have been fixed. For `S1023` I removed the superfluous return statement, while for `SA1029` I added a `// nolint:staticcheck` comment because I found it multiple times in the rest code.

I also replaced `go get` with `go install` to install `golangci-lint`.

Let me know if it looks good or if there is anything else I should change 🙂

**Comment by crenshaw-dev** [comment]
@cippaciong thanks! Looks like the last commit needs to be signed. I'm going to kick off the integration tests again. Hopefully just a flaky test.

**Comment by cippaciong** [comment]
@crenshaw-dev woops, signed it :)

**Comment by Aym3nTN** [comment]
@cippaciong @crenshaw-dev I noticed that pipelines after this one are failing when performing race testing, is that the case or am I missing something? 
Here's my failing PR #9462

**Comment by crenshaw-dev** [comment]
@Aym3nTN just merged a fix: https://github.com/argoproj/argo-cd/pull/9469

**Comment by crenshaw-dev** [comment]
Cherry-picked onto 2.3.

**Pull request merged**
