### PR TITLE
chore: improve error logs in server/cluster/cluser.go

### PR DESCRIPTION
**Pull request by SuminSSon**
fixes part of #20710

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by andrii-korotkov-verkada — APPROVED** [review]
Typo in the PR name imporve -> improve

**Review by ishitasequeira — COMMENTED** [review]
Changes look good to me!! Rebased the PR to rerun the unit tests. Will wait for CI to pass for approving and merging the change.

**Review by ishitasequeira — COMMENTED** [review]
@SuminSSon can you take a look at the failing tests?

**Comment by SuminSSon** [comment]
@ishitasequeira Thank you! I’ll check the failing tests and make any necessary adjustments. I’ll work on getting the CI to pass.

**Review by andrii-korotkov-verkada — APPROVED** [review]

**Comment by SuminSSon** [comment]
@ishitasequeira I’ve fixed the failing tests, and everything is passing now. Please let me know if there’s anything else I should address. Thank you!

**Review by ishitasequeira — APPROVED** [review]

**Pull request merged**
