### PR TITLE
fix(notification): Add `AppName` to the RepoServerAppDetailsQuery

### PR DESCRIPTION
**Pull request by wd**
The repo server will add a few environment variables to the kustomize build command, [1], [2]. It will retrieve the app name from the request [3]. This PR will add `AppName` to the request sent to the repo server.

1. https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L2133
2. https://argo-cd.readthedocs.io/en/stable/user-guide/build-environment/
3. https://github.com/argoproj/argo-cd/blob/master/reposerver/repository/repository.go#L1468

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by wd** [comment]
hi @crenshaw-dev could you help to take a look? I'm sorry if I tagged the wrong person.

**Review by pasha-codefresh — COMMENTED** [review]
@wd PR looks good to me, but could you please point me to issue that you solving? It takes incorrect application base on source or what? could you please open github issue and describe the problem

**Comment by wd** [comment]
oh @pasha-codefresh , from the doc of argo-cd(link #2 in the first post), it will provide some build environment variables to the kustomize build command(link #1, #3 in the first post). 
The PR adds the AppName to the request sent to repo-server at here https://github.com/argoproj/argo-cd/pull/17233/files#diff-c9bc9d40ba588ada6e71aa4fbbf8bfefaed8155efb666dd8b2b446073184c956R98

We used the build environment variables for our customized build script, hence it is very important to add the `AppName` to the request sent to repo-server.

**Comment by pasha-codefresh** [comment]
Sorry, but this change in notifications, how it is related to kustomize ? It is just change how you communicate with argo-cd when execute notification expression, am i miss something ? @wd

**Comment by wd** [comment]
@pasha-codefresh If people put `(call .repo.GetAppDetails)` in their template, the notification controller will send a request to the repo-server [here](https://github.com/argoproj/argo-cd/pull/17233/files#diff-c9bc9d40ba588ada6e71aa4fbbf8bfefaed8155efb666dd8b2b446073184c956R97) 

If there is no `AppName` field in the request, the repo-server cannot generate the correct `ARGOCD_APP_NAME` build environment for the kustomize command.

**Comment by pasha-codefresh** [comment]
Thank you for explanation @wd  !

**Review by pasha-codefresh — APPROVED** [review]

**Comment by wd** [comment]
I don't have merge permission. Please help me to merge it. Thank you.

**Pull request merged**
