### PR TITLE
fix: applicationset controller should respect logging flags (#10399)

### LINKED ISSUE #10399: applicationset-controller logging not respecting `logformat` and `loglevel` flags
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I'm not able to have applicationset-controller respect the `--logformat` and `--loglevel` flags. Logging format seems to be `text` even though I specify `json` and logging level is `info` even though I specify `warn`.

**To Reproduce**

1. Start the applicationset-controller with the flags `--logformat=json --loglevel=warn`.
2. Observe that log output is in text format and includes info level log.

**Expected behavior**

I would expect application-set controller to log in json format and only log warn level and higher as the other ArgoCD applications do.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.4.10+2ccc17a
  BuildDate: 2022-08-17T21:03:50Z
  GitCommit: 2ccc17afcbad78651cf7cd76891cdf7728cd488e
  GitTreeState: clean
  GoVersion: go1.18.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

Example output from the pod above:
```text
time="2022-08-19T08:06:48Z" level=info msg=Trace args="[git fetch origin HEAD --tags --force]" dir=/tmp/https___github.com_*** operation_name="exec git" time_ms=906.7991010000001
time="2022-08-19T08:06:49Z" level=info msg=Trace args="[git checkout --force 4824fb31972bb94fdfc72d4185131fb4f371ad1a]" dir=/tmp/https___github.com_*** operation_name="exec git" time_ms=3.373673
time="2022-08-19T08:06:49Z" level=info msg=Trace args="[git clean -fdx]" dir=/tmp/https___github.com_*** operation_name="exec git" time_ms=3.036766
```
Note: my private github repo name was replaced with `***` in the output.

**More details**
I'm deploying applicationset-controller in Kubernetes using version `4.10.7` of the `argo-cd` helm chart from https://argoproj.github.io/argo-helm.

I have verified that the flags are picked up and evaluated in two ways:
1. Deployed with `--logFormat=json` (notice the uppercase F) and the app would not boot
3. Deployed with an invalid value for `--loglevel` and the app would not boot

Part of the resulting container spec (from `kubectl describe pod` after deploy) showing the flags:
```yaml
spec:
  containers:
    - command:
        - entrypoint.sh
        - argocd-applicationset-controller
        - --metrics-addr=:8080
        - --probe-addr=:8081
        - --namespace=argocd
        - --argocd-repo-server=argocd-repo-server:8081
        - --policy=sync
        - --debug=false
        - --dry-run=false
        - --logformat=json
        - --loglevel=warn
      image: quay.io/argoproj/argocd:v2.4.10
```

### PR DESCRIPTION
**Pull request by toVersus**
Signed-off-by: Tsubasa Nagasawa <toversus2357@gmail.com>

Fixes: #10399

This PR fixes applicationset controller to respect the log level and format passed as flags by reusing logging utils adopted in other Argo CD components.

I confirmed that the log format flag (`--logformat json`) got to work as expected after this change:

```console
{"built":"2022-09-03T04:32:09Z","commit":"75acdcc15db79fa02e19c254007723dda86a06d3","level":"info","msg":"ArgoCD ApplicationSet Controller is starting","namespace":"argocd","time":"2022-09-03T04:40:29Z","version":"v2.5.0+75acdcc.dirty"}
{"level":"info","msg":"Starting configmap/secret informers","time":"2022-09-03T04:40:30Z"}
{"level":"info","msg":"Configmap/secret informer synced","time":"2022-09-03T04:40:30Z"}
{"level":"info","msg":"Starting manager","time":"2022-09-03T04:40:30Z"}
{"level":"info","msg":"Starting webhook server","time":"2022-09-03T04:40:30Z"}
(...)
{"applicationset":{"Namespace":"argocd","Name":"kube-state-metrics"},"level":"info","msg":"end reconcile","requeueAfter":31536000000000000,"time":"2022-09-03T04:40:48Z"}
```

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@toVersus thanks for this! Can you resolve conflicts!

**Comment by toVersus** [comment]
Thanks for letting me know, resolved! PTAL

**Comment by vgrigoruk** [comment]
it is gonna be possible to specify `applicationset-controller` loglevel and log format via [argocd-cmd-params-cm.yaml](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cmd-params-cm.yaml)?

**Comment by toVersus** [comment]
@crenshaw-dev 
Hi, sorry to disturb you. Is there anything I can do before merging this?

**Review by crenshaw-dev — APPROVED** [review]
Thanks @toVersus!

I'm going to only cherry-pick this to 2.5 to avoid changing behavior on a patch release. If folks really need this fix in 2.4 or prior, I'll check with #argo-contributors on Slack to see how folks feel about cherry-picking further back.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.0-rc2.

**Pull request merged**
