### PR TITLE
fix: parsed url is not exposed (#11816)

### LINKED ISSUE #11816: 2.6 RC1 - 'URL parsing failed' error when opening application sourced from OCI registry (ECR)
**Describe the bug**

I am using the latest nightly build (quay.io/argoproj/argocd@sha256:3e3890cd3614fff9d86db4facd99349cad0241fee7f974fefdd97fdca8c13ef2). Same happens with [v2.6.0-rc1](https://github.com/argoproj/argo-cd/releases/tag/v2.6.0-rc1).

All my applications from the ECR OCI registry fail to open with an error "**URL parsing failed**".
It seems to me that it expects to have a protocol in the repoURL, because if I use - "**repoURL: 1234567890.dkr.ecr.us-west-1.amazonaws.com**" - the UI crashes. When I add "**oci://**" or "**https://**" - the UI works but, of course, the application is in an unknown state due to the "**unsupported protocol scheme "oci"**".

**To Reproduce**

Use OCI registry without protocol in the URI

**Expected behavior**

Either allow adding "oci://" prefix to the repoURL or support URLs without a protocol

**Screenshots**

image

**Version**

```json
{
    "Version": "v2.6.0+43c928e",
    "BuildDate": "2022-12-21T19:47:17Z",
    "GitCommit": "43c928e2e5f474f8e78f66f73cd0ee2bf91a0cd1",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.9",
    "Compiler": "gc",
    "Platform": "linux/arm64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

### LINKED ISSUE #11922: ArgoCD returns ReferenceError when opening an application
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I am trying to view manifests on my applications but when opening an application from ArgoCD renders an error page with a stacktrace. The stacktrace is in the Logs heading.

**To Reproduce**

1. Log into ArgoCD.
2. Open an application to view the manifests
3. Instead of rendering the tree and the application details page, ArgoCD renders the error page–screenshot included below.

**Expected behavior**

I would expect ArgoCD to open the detailed Application page, with the associated manifests accessible.

**Screenshots**

Screen Shot 2023-01-09 at 10 40 18 AM

**Version**

```shell
argocd: v2.4.15+05acf7a.dirty
  BuildDate: 2022-10-17T22:52:44Z
  GitCommit: 05acf7a52e377eacfee29c68e3e5e79a172ea013
  GitTreeState: dirty
  GoVersion: go1.19.2
  Compiler: gc
  Platform: darwin/amd64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.6.0+052a5d2
  BuildDate: 2023-01-06T22:52:34Z
  GitCommit: 052a5d2f69aa6bcc61a9a744d1e46e99490fda59
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
ReferenceError: parsed is not defined
    at https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:1649153
    at kh (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:1649261)
    at Jr (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:807467)
    at ya (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:853372)
    at pl (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:846148)
    at dl (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:846073)
    at il (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:843103)
    at https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:794882
    at t.unstable_runWithPriority (<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:869930)
    at Uo (https://<path-to-our-argo-instance>/main.419eb18f2124a92eb38d.js:2:794591)
```

### PR DESCRIPTION
**Pull request by alexef**
follow up on: https://github.com/argoproj/argo-cd/pull/11819 according to @Romanbats
fixes: #11816 
fixes: https://github.com/argoproj/argo-cd/issues/11922

~Now the code of `revisionURL` is consistent with `repoURL` above it.~ not anymore after subtler fix

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@alexef could I trouble you for some unit tests on this function? :-)

**Comment by crenshaw-dev** [comment]
Also, am I correct to only cherry-pick this to 2.6?

**Comment by crenshaw-dev** [comment]
Related? So 2.5 as well. https://github.com/argoproj/argo-cd/issues/11922

**Comment by alexef** [comment]
@crenshaw-dev yes, this is 2.6 only. I'll add the unit tests

**Comment by alexef** [comment]
@crenshaw-dev nevermind, the tests already exists: https://github.com/argoproj/argo-cd/blob/master/ui/src/app/shared/components/urls.test.ts#L7

now the question is why they didn't fail when the previous change was introduced that changed the scope of `const parsed`?

**Comment by crenshaw-dev** [comment]
@alexef good question... I'll leave that as an exercise for later, since this fixes an important issue. :-)

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc3.

**Comment by jannfis** [comment]
@alexef May I ask why you set the `breaking/high` label on this bug? Is it by mistake, or is this a breaking change?

**Comment by alexef** [comment]
@jannfis the UI was completely broken (unable to view application details, presented stacktrace, no workaround) in master and in the 2.6 branch until rc3. If this doesn't grant a `breaking/high` I'm happy to remove it - also from related PR/issues, there were a few around this same story.

**Comment by jannfis** [comment]
@alexef Ah. Just as a heads-up for the future, the `breaking/*` labels indicate that a given change itself is breaking (e.g. is not backwards-compatible). For classifying bugs' severity, you can use the `severity/*` labels.

**Pull request merged**
