### PR TITLE
feat: Slugified the branch name in PR generators

### LINKED ISSUE #9461: Cleanup branch name in PR Generators
# Summary

In PR generators, I noticed that when a branch name contains special characters or is too long to be used in a resource name (by using `{{branch}}`), the applicationset controller fails to create the resource throwing the below exception.

`
argocd-applicationset-controller-647f5948d6-bq7sn time="2022-05-20T08:58:18Z" level=error msg="failed to unchanged Application" action=unchanged app=nginx-github-feat/pr_special+character-2 appSet=test-app-set-github error="Application.argoproj.io \"nginx-github-feat/pr_special+character-2\" is invalid: metadata.name: Invalid value: \"nginx-github-feat/pr_special+character-2\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"    
`

# Motivation

In order to follow the DNS label standard as defined in RFC 1123, manifests' name metadata should not exceed 63 and must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character.

Docs: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names

# Proposal

For that I suggest limiting and cleaning the 'branch' name to contain only 50 characters to give room to append/suffix-ing it with 13 more characters.

### PR DESCRIPTION
**Pull request by Aym3nTN**
Enhancement proposal/Fix: #9461

Fixes #9461

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates? Yes, WIP
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@Aym3nTN thanks for the PR! Instead of changing the `branch` variable, can you introduce a new `branchSlug` field? I'd rather this not be a breaking change for users of the original field.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
+branchSlug

**Comment by Aym3nTN** [comment]
I agree with you.. I'd suggest also making `branchSlug` field boolean defaulting to false to not cause a breaking change what do you think?

**Comment by crenshaw-dev** [comment]
@Aym3nTN instead of introducing a new config field that toggles the `branch` contents, how would you feel about calculating both and just dropping the slugified version into a new `branchSlug` param? That would be helpful if someone wants both versions.

**Comment by Aym3nTN** [comment]
@crenshaw-dev I totally agree with you on; and also it's less risky that way.. keeping the old `branch` value for those who already using it will avoid us from having a breaking change.

**Review by crenshaw-dev — APPROVED** [review]
Thanks @Aym3nTN!

**Pull request merged**
