### PR TITLE
Fix: Kuberenetes manifest to have new Github.com ssh known host keys for ArgoCD deployments

### PR DESCRIPTION
**Pull request by smark88**
## Issue: Applications now in Unknown state due to the link below

https://github.blog/2021-09-01-improving-git-protocol-security-github/

## fix: Add new github.com ssh known host key

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crisp2u** [comment]
I was just banging my head with this, thanks!

**Comment by mfridman** [comment]
I was just banging my head with this, thanks! x2

**Comment by rizzza** [comment]
saved our day, thank you!

**Review by joaopaulosr95 — APPROVED** [review]
Thanks for being so fast @smark88

**Comment by smark88** [comment]
Should i wait on the tests to merge?

**Comment by Kampe** [comment]
looks like tests need to be updated

**Review by mythxn — APPROVED** [review]

**Review by devanshmshah — APPROVED** [review]

**Comment by alexmt** [comment]
Thanks a lot for a quick @smark88 ! CI failed due to codegen minor difference in generated install.yaml files. The `make manifests` should fix it. For the sake of time, I pushed the fix into your fork. Merging PR as soon as CI is green.

**Review by alexmt — APPROVED** [review]

**Pull request merged**
