### PR TITLE
feat: add a button to show parameter details (#12183)

### LINKED ISSUE #12183: History and Rollback : Don't display details of last deployed revision when opening the screen.
# Summary
In History and Rollback, the details on last deployed revision are displayed.
I would like the last deployed revision to be displayed as a summary (like the other ones) when the window is opened.

The user could click on it to have the details.

# Motivation
I would like to avoid to scroll to the bottom of the page to see previous deployed revisions.
It will be more readable.

# Proposal
Display the last deployed version like the other ones.

I attached a screenshot of an application with 2 deployed devisions.
I would like the latest revision to be displayed has the second one.

### PR DESCRIPTION
**Pull request by Tchoupinax**
Hello,

This work aims to not display parameter details by default in the history view. We might have hundreds of parameters and the original view to see old versions is not pratical due to the scroll. The issue is already opened here: #12183

Closes #12183

I would ask some feedback about the way to do it. Please find a record of the feature below.

Currently, the index in `rollback` query param is used to determine which history loads. That's said, with this new behavior  the index won't be useful anymore: we load basics information for each history and display additional parameters details on demand.

I'm asking if the design is good to load all metadata or if I add to continue to ask for a click before loading data. What do you think?

_Edited overview_
https://github.com/user-attachments/assets/a1fbe606-8334-4a24-b729-f866645300b8

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by pasha-codefresh — CHANGES_REQUESTED** [review]
I like this change. But could you please change how button is look. I think it is not super intuitive that it is a button

**Comment by Tchoupinax** [comment]
Hello @pasha-codefresh I rebased and I used argocd default buttons style, tell me what you think!

**Review by reggie-k — COMMENTED** [review]
I like how the button looks, and I think the "Click to see source details" should be also a similar button, maybe "show/hide source details" and "show/hide parameter details" for the button you have already added.

**Comment by Tchoupinax** [comment]
I agree with the idea! Do you think it makes sense to do it in this PR?

**Comment by reggie-k** [comment]
No, this can be done separately. LGTM!

**Review by reggie-k — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Comment by Tchoupinax** [comment]
Hello @marcin-wicha,
Thank you for your report I made the merge request to fix this. The button "Click to see details" was pretty confusing. I hope I did not add another regression.
Now, the first part is loaded by default (revision, author, etc) and only the params table is hidden.

**Pull request merged**
