### PR TITLE
feat: reduce redis traffic caused by app resource tree updates in redis

### PR DESCRIPTION
**Pull request by alexmt**
PR reduces the amount of traffic sent from the controller to redis while updated application resource tree.

The application resource tree contains metadata of all resources that belongs to application and stored in redis. Currently, it replaces the whole resources tree in Redis every time any app resource changes. This causes exponential growth of traffic sent from the controller to Redis: the more resources the application has, the more frequently they change, and the more frequently the controller needs to update the resources tree, and the tree is bigger with each resource.

The PR allows to optionally split resources tree into shards using `ARGOCD_APPLICATION_TREE_SHARD_SIZE` env variable. If `ARGOCD_APPLICATION_TREE_SHARD_SIZE` is bigger then 0 then controller split app resources into shards and store each shard in a separate Redis key. When any app resource changes then only related shard is updated which significantly reduces amount of Redis  traffic.

### CODE REVIEW

**Review by wanghong230 — APPROVED** [review]
lgtm

**Review by gdsoumya — APPROVED** [review]
LGTM

**Review by gdsoumya — CHANGES_REQUESTED** [review]
Should we document this `ARGOCD_APPLICATION_TREE_SHARD_SIZE` ? in the deployment env or docs?

**Comment by alexmt** [comment]
@gdsoumya agree - updated the docs

**Review by gdsoumya — APPROVED** [review]

**Review by blakepettersson — APPROVED** [review]

**Review by christianh814 — COMMENTED** [review]
Thanks Alex!

**Pull request merged**
