### PR TITLE
docs: fix slack.md formatting issues

### PR DESCRIPTION
**Pull request by GalvinGao**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or **(c) this does not need to be in the release notes**.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?: This PR is just a documentation update.
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks for the PR, @GalvinGao! These docs are pulled from upstream. Can you open a PR there? https://github.com/argoproj-labs/argocd-notifications/

**Comment by GalvinGao** [comment]
@crenshaw-dev Sorry but I'm a bit confused here: it seems that previously the docs are indeed being synced with the repo, but commit https://github.com/argoproj/argo-cd/commit/595b82546bda5da8ed9e64a4c944ba3e07f514ea seems to have break such synchronization and the current docs in https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/notifications/services/slack.md?plain=1 are now different than the one in https://github.com/argoproj-labs/argocd-notifications/blob/master/docs/services/slack.md?plain=1.

Seems that there's an ongoing effort on fixing this at #8776. Going to check how things goes on that side.

**Comment by crenshaw-dev** [comment]
@GalvinGao I believe the synchronization is based on the notifications-engine version in go.mod: https://github.com/argoproj/argo-cd/commit/595b82546bda5da8ed9e64a4c944ba3e07f514ea#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L12

So updates in the argo-cd master will be synched to a particular commit in the notifications repo.

**Comment by GalvinGao** [comment]
I see. Thanks for the clarification. I'll go ahead and file a PR over there then.

**Pull request closed without merging**
