### PR TITLE
feat: Supported set metadata annotations with `argocd-util app generate-spec` command

### PR DESCRIPTION
**Pull request by takumakume**
Hello!

Added support for set metadata annotations with the `argocd-util app generate-spec` command.
My use case is to generate Annotations for use with the ArgoCD Image Updater.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks @takumakume for this PR. I agree that this would be useful.

However, I think the command line option should be moved to a different part in the code. `AddAppFlags()` sets flags for the `.spec` part of the `Application` resource, not for its `.metadata` section.

I think the right place - despite some redundancy - would be [here](https://github.com/argoproj/argo-cd/blob/f12650c32bc6e3cfc169e80d75bcb1501cecb47a/cmd/argocd/commands/app.go#L158) and [here](https://github.com/argoproj/argo-cd/blob/f12650c32bc6e3cfc169e80d75bcb1501cecb47a/cmd/argocd-util/commands/app.go#L103)

**Comment by takumakume** [comment]
@jannfis Thank you for the review!
That's right.
I removed this option from `AddAppFlags()` and changed it to the location indicated.

**Comment by takumakume** [comment]
I implemented two more

- [fix: set an empty value if there is no `=` in `--annotations`](https://github.com/argoproj/argo-cd/pull/6633/commits/e7c42f7b597961bd92ebcd231dc7605013ac3e35)
- [docs: added an example `--annotations` are `=` delimited](https://github.com/argoproj/argo-cd/pull/6633/commits/eec024729459dc8ff6aae2e7acf1eef826576da8)

Please check

**Review by jannfis — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
