### PR TITLE
fix: higher git client timeout

### PR DESCRIPTION
**Pull request by tooptoop4**
Fixes https://github.com/argoproj/argo-cd/issues/13347

### CODE REVIEW

**Comment by ebuildy** [comment]
well this is a high value.

We should add this as git-repository config, like do flux --> https://fluxcd.io/flux/components/source/gitrepositories/#timeout

**Comment by ebuildy** [comment]
> > well this is a high value.
> 
> I agree, it should be configurable the one or other way. A per-repository configuration probably would be the best option.

I can do it this week if you want ?

**Comment by blakepettersson** [comment]
This is a duplicate of #15646, which one will be the winner?

**Comment by blakepettersson** [comment]
Thanks for your contribution but it looks like this PR got superseded with #15646.

**Pull request closed without merging**
