### PR TITLE
Document safe concurrent processing of sidecar CMP

### LINKED ISSUE #10335: Document concurrent-safe aspects of sidecar CMP since 2.4
# Summary

When using the config management plugin, is was not clear to me what the best option was for enabling concurrent processing of applications that share a repository and use a custom config management plugin. When I asked about thus in slack @crenshaw-dev gave me some really useful information that could not be found in the documentation.

> For plugins installed via sidecar (for Argo CD version 2.4 and later), concurrent processing is always safe. In this scenario, a temporary copy of the repo contents is send as a tarball over grpc to the sidecar for each manifest generation request. Concurrent processes will always operate on different copies of the repo.

This should be added to the documentation in these places, to help others in future:
* https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#installing-a-cmp
* https://argo-cd.readthedocs.io/en/stable/operator-manual/high_availability/#enable-concurrent-processing

### PR DESCRIPTION
**Pull request by jsmcnair**
Closes #10335 

Signed-off-by: jsmcnair <john.mcnair@yellowdog.co>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Thanks @jsmcnair! Can you drop the "from v2.4" qualifiers? We're trying to rely more on versioned docs to communicate version differences.

I'll cherry-pick the change back to 2.4 so the info will be present for all applicable versions of the docs.

**Comment by jsmcnair** [comment]
Ah yeah - I was mentions of the version elsewhere, so just assumed. Now removed.

Is there a plan for removing the pre-2.4 content form [here](https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#environment)? Does is just need to be removed?

**Comment by crenshaw-dev** [comment]
@jsmcnair fixed that one this morning.  :-) https://github.com/argoproj/argo-cd/pull/10338/files#diff-16370636772309512011fc9134f70595151d74e71ce3aa6eb71048fd088dc73e

**Review by crenshaw-dev — APPROVED** [review]
Thanks @jsmcnair!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.10.

**Pull request merged**
