### PR TITLE
fix: Enhance securityContext in ha manifests (#9810)

### LINKED ISSUE #9810: Enhance securityContext in ha manifests
# Summary

Enhance securityContext in HA installs to comply with PSS/restricted level.

https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

This is the part of #9743 that was not fixed by #9765

# Motivation

The following ha manifests do not comply with PSS/restricted policies:
* `manifests/ha/cluster-install`
* `manifests/ha/namespace-install`

The following command reports 6 failures for `manifests/ha/namespace-install`:

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/argoproj/argo-cd//manifests/ha/namespace-install) \
  -
```

(With similar results for `manifests/ha/cluster-install`, and for manifests that are generated from these `ha` folders as well.)

The 6 failures are because 3 properties are missing from the `securityContext` in each of the 2 deployments: `argocd-redis-ha-haproxy` and `argocd-redis-ha-server`

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
    add:
    - NET_BIND_SERVICE
  seccompProfile:
    type: RuntimeDefault
```

NOTE: Adding NET_BIND_SERVICE is not required by PSS but it is permitted, and it looks like haproxy needs this capability:

[haproxy/templates/deployment.yaml#L112](https://github.com/haproxytech/helm-charts/blob/d8ded40f078f96267ac637d1be780068292f103e/haproxy/templates/deployment.yaml#L112)

# Proposal

Add the missing parts to the securityContext in these deployments and verify that they still function.

Eventually the [upstream](https://github.com/DandyDeveloper/charts/issues/204) should provide these security contexts.

### PR DESCRIPTION
**Pull request by joebowbeer**
Fixes #9810 

Adds container-level securityContext to the `argocd-redis-ha-haproxy` and `argocd-redis-ha-server` containers.

In a static check using kyverno-cli, these updated manifests report no PSS/restricted policy failures:

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/joebowbeer/argo-cd//manifests/ha/cluster-install\?ref=patch-2) \
  -
```

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/joebowbeer/argo-cd//manifests/ha/namespace-install\?ref=patch-2) \
  -
```

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(wget -qO- https://raw.githubusercontent.com/joebowbeer/argo-cd/patch-2/manifests/ha/install.yaml) \
  -
```

```bash
kustomize build https://github.com/kyverno/policies//pod-security | \
  kyverno apply --policy-report -r \
  <(wget -qO- https://raw.githubusercontent.com/joebowbeer/argo-cd/patch-2/manifests/ha/namespace-install.yaml) \
  -
```

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@joebowbeer ready for review?

**Comment by crenshaw-dev** [comment]
@joebowbeer not at all, unfortunately.  :-( Might see if I can test this out at Intuit for a day or two before merging.

**Comment by souravsk** [comment]
So I copied the changes you made then I run the in my minikube 

it did run but some of the posts are pending

**Comment by joebowbeer** [comment]
@souravsk how many workers are in your cluster? I suggest 3 for high availability (HA)

**Comment by souravsk** [comment]
I'm my have one control panel and one workar node i tried to create one more node but i get failed.

**Comment by joebowbeer** [comment]
@crenshaw-dev it looks like NET_BIND_SERVICE may be problematic:

https://github.com/haproxytech/helm-charts/issues/150#issuecomment-1185395182

https://github.com/kubernetes/kubernetes/issues/56374

At a glance, however, I'm not sure it is actually needed. If ArgoCD/HA is not binding privileged ports then this capability can be omitted.

**Comment by joebowbeer** [comment]
@crenshaw-dev PTAL

**Review by crenshaw-dev — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
