### PR TITLE
fix: do not interpolate env variables in helm template options when forceString is true

### PR DESCRIPTION
**Pull request by daengdaengLee**
related issue : #19269 (1 problem / 2 problems)

* AS-IS: It performs environment variable interpolation for all parameters of the helm template, regardless of the `forceString` option.
* TO-BE: When the `forceString` option is set to `true`, the environment variable interpolation is not performed.
* REASON: I think the value of the helm parameter should be treated as a string when the `forceString` option is `true`. (explained in the [docs](https://argo-cd.readthedocs.io/en/stable/user-guide/application-specification/#application-specification)) If this PR is merged, it will resolve part of the issue #19269 (the problem where the `$` character is incorrectly encoded even when the `forceString` option is `true`).

If I've misunderstood something, please let me know in the comments or close the PR. Thank you! :)

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by reggie-k — COMMENTED** [review]
Thanks for the PR and for providing a workaround on the issue!
Can you add separate tests for the new functionality and preserve the original test?

**Comment by daengdaengLee** [comment]
Hello, @reggie-k.

I add/edit tests for changed code.
Please check the PR.

Thanks!

**Review by agaudreault — CHANGES_REQUESTED** [review]
The goal of `forceString` is not to decide if the variable should be interpolated or not. 

The main goal is to decide when boolean value, either the result of an interpolation or not, should be converted to a string. 
This is because the quoting will be removed, and it is impossible to specify `myparams: "true"` where the value must be a string.

**Comment by agaudreault** [comment]
Closing as this is not the desired behavior. The discussion on the correct implementation to fix the issue should happen in https://github.com/argoproj/argo-cd/issues/19269

**Pull request closed without merging**
