### PR TITLE
fix(cli): wrong variable to store --no-proxy value

### LINKED ISSUE #21194: argocd repo add with --no-proxy does not work
Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd repo add` with `--no-proxy` (the feature was introduce in #18526) does not work as the argument values are stored in the wrong variable.

**To Reproduce**

Try adding a new repo with the `--no-proxy` flag.

**Expected behavior**

The repository should be added with =noProxy= settings. Instead the `--no-proxy` values are written in the `proxy` values and argocd tries to access them as proxy and fails.

This is the trivial fix for `cmd/util/repo.go`:
```go
        command.Flags().StringVar(&opts.Proxy, "proxy", "", "use proxy to access repository")
-       command.Flags().StringVar(&opts.Proxy, "no-proxy", "", "don't access these targets via proxy")
+       command.Flags().StringVar(&opts.NoProxy, "no-proxy", "", "don't access these targets via proxy")
```

**Version**

```shell
$ argocd version
argocd: v2.13.2+dc43124
  BuildDate: 2024-12-11T19:01:33Z
  GitCommit: dc43124058130db9a747d141d86d7c2f4aac7bf9
  GitTreeState: clean
  GoVersion: go1.22.9
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.2+dc43124
```

Please add this trivial fix for 2.13.3.

### PR DESCRIPTION
**Pull request by the-technat**
Simple fix to save the `--no-proxy` value in the right variable.

Closes #21194 

Cherry-pick for 2.12 and 2.13.

Thanks @knweiss for spotting this!

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by keithchong — COMMENTED** [review]
LGTM. There's a unit test failing, but it doesn't look like it's related to this change.

**Review by reggie-k — APPROVED** [review]
The checks seem to be failing unrelated to the current change, but related to another issue:
https://github.com/argoproj/argo-cd/pull/21204

**Review by pasha-codefresh — APPROVED** [review]

**Comment by knweiss** [comment]
This was reported by me for argocd 2.13.2 and AFAICS argocd 2.13.6 is still broken. Wasn't it cherry-picked to 2.13.x?

**Comment by blakepettersson** [comment]
>Wasn't it cherry-picked to 2.13.x?

It was not.

**Pull request merged**
