### PR TITLE
fix(kustomize): set build dir (#15057) #16229 #16652

### LINKED ISSUE #15057: Kustomize build ComparisonError (unable to make loader)
**Describe the bug**
App templated with kustomize ends in error state (ComparisonError)

We encountered problem with kustomize (v4.5.7 and v5.1.1) and argocd **v2.8.0**. 
First, restarting `argocd-repo-server` solved the problem. However, the error reappeared and the restart did not fix it.
I did not find anything useful in the `debug` logs. With argocd v2.7.x everything worked fine.

Did not help:
- disabling redis compression
- update kustomize to v5
- restarting controllers

**To Reproduce**

The problem appears with kustomize templated apps. I have not been able to find the key to reproduce accurately, but with a `hard refresh` action, the error should appear. But it depends on how long the repo-server is running. 

In my case, app ends in the error state after hard-refresh triggered between 15-60minutes after repo-server restart.
Once kustomize build get `permission denied`, it never recovered without restarting repo-server.
 
**Expected behavior**

Kustomize apps do not fall in the error state after (hard)refresh.

**Version**

```shell
v2.8.0+804d4b8
```

**Logs**

```
Failed to load target state: failed to generate manifest for source 1 of 1: rpc error: code = Unknown desc = Manifest generation error (cached): `kustomize build <path to cached source>/path/to/my/app` failed exit status 1: 2023/08/15 12:31:20 unable to make loader at '.'; not a valid directory: abs path error on '.' : stat .: permission denied
```

### PR DESCRIPTION
**Pull request by prune998**
Make kustomize use the project root dir as a base path.

Fixes #15057

### CODE REVIEW

**Comment by prune998** [comment]
@crenshaw-dev it seems some e2e tests are failing, but not on the patch (e2e namespace creation failure ?)

I tested the patch for few weeks now and I also managed to replicate the bug, which is solved by this patch.

**Comment by crenshaw-dev** [comment]
@prune998 not sure what's up here... 

```
        	            	time="2024-01-03T14:27:11Z" level=error msg="`kustomize build ./testdata/guestbook_local` failed exit status 1: Error: must build at directory: not a valid directory: evalsymlink failure on './testdata/guestbook_local' : lstat /testdata: no such file or directory" execID=70b51
```

Looks like the `./` prefix got stripped off somewhere?

**Comment by prune998** [comment]
> @prune998 not sure what's up here...
> 
> ```
>         	            	time="2024-01-03T14:27:11Z" level=error msg="`kustomize build ./testdata/guestbook_local` failed exit status 1: Error: must build at directory: not a valid directory: evalsymlink failure on './testdata/guestbook_local' : lstat /testdata: no such file or directory" execID=70b51
> ```
> 
> Looks like the `./` prefix got stripped off somewhere?

Well, I guess the tests made an assumption of where the command is running (CWD), which is not the root of the project, and this is breaking because of the relative path ? 
i'm trying to understand how the `e2e` tests works...

**Comment by prune998** [comment]
I made some debug, and when run manually using `argocd` commandline, like in `argocd app diff`, the `repoRoot` is `/`, and any relative file path, like `testdata/config-map` from the e2e test, translated to `/testdata/config-map`, which does not exist.
I'll keep looking tomorrow to understand how things are built with this `--local` flag versus when the build is called from the repo-server...  but my guess is that the `argocd` command line should set the `repoRoot` correctly, which is not the case right now.

**Comment by prune998** [comment]
turns out we need to set `--local-repo-root` to locate the path of the repo. Let's say that it was previously working by chance more than by design...

**Comment by prune998** [comment]
@crenshaw-dev I got it working by changing the defaults `--local-repo-root` of the `app diff` and `app sync` commands from `/` to `.`. This was already the default for the `manifests` command.

I don't see how this change would be a problem to anyone... unless you expect the commands to use your manifest files in the root of your disk...

**Comment by prune998** [comment]
@crenshaw-dev are we good for adding this to release 2.10 ? 
thx !

**Comment by prune998** [comment]
@crenshaw-dev should I keep this PR rebased ? 
Could we prioritize the merge for 2.10 ? 

thanks !

**Comment by prune998** [comment]
@crenshaw-dev I know I'm kind of being insistent, but I really need that merged in 2.10. This is a real bug impacting users !.

Thanks

**Comment by crenshaw-dev** [comment]
@prune998 apologies for the lack of response! And no worries, reminders are appreciated.

> @crenshaw-dev I got it working by changing the defaults --local-repo-root of the app diff and app sync commands from / to .. This was already the default for the manifests command.
> 
> I don't see how this change would be a problem to anyone... unless you expect the commands to use your manifest files in the root of your disk...

I'd rather not change the default. There may be CI jobs which assume the default directory is root (weird, but probably happens).

Instead, I think we should:

1) Open an issue requesting the defaults to be changed in 3.0
2) Switch the default back to the current value
3) Update any tests necessary to explicitly set the dir

**Comment by glasser** [comment]
just to check — does this mean with the latest version of the PR, avoiding this bug will mean *both* upgrading *and* setting some configuration?

or is the thing about defaults just about manual use of the `argocd` CLI (which we don't really use)?

**Comment by prune998** [comment]
> just to check — does this mean with the latest version of the PR, avoiding this bug will mean _both_ upgrading _and_ setting some configuration?
> 
> or is the thing about defaults just about manual use of the `argocd` CLI (which we don't really use)?

you don't have to change anything. It's just to keep compatibility for some users that were doing strange things and using the `argocd` CLI, mostly... In a normal K8s deployment, the patch will handle the bug, nothing to change on your side. (I hope) :)

**Comment by glasser** [comment]
I've been running this branch for a few days (ended up building my own tag from this PR) and it appears to fix our kustomize problem! It would be great to see this in v2.10.

**Review by crenshaw-dev — APPROVED** [review]
Thanks for your persistence, @prune998!

**Comment by crenshaw-dev** [comment]
@prune998 if you'd like this further back than 2.10, looks like you'll have to manually open cherry-pick PRs.

**Comment by glasser** [comment]
Awesome! Looking forward to v2.10.1.

**Comment by prune998** [comment]
backport to 2.9 is PR https://github.com/argoproj/argo-cd/pull/17132

**Comment by glasser** [comment]
Specifically, is there any sort of release ticket or milestone to follow so I can see progress on a potential v2.10.1 where this is released?

**Comment by crenshaw-dev** [comment]
@glasser patch releases are very ad-hoc. There's a regression in 2.10 I've been waiting for a patch for before cutting 2.10.1. If the patch isn't ready by Monday, I'll probably just cut a release to get other stuff out the door.

**Pull request merged**
