### PR TITLE
fix: Running on Openshift 4.x with readOnlyRootFilesystem

### LINKED ISSUE #6968: Regression in Release Candidate 2.1
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
 
PR #5814 changes the root file system to read-only. During startup in Openshift the entrypoint script `uid_entrypoint.sh` is called, the attempt to add an [additional line in `/etc/passwd`](https://github.com/argoproj/argo-cd/blob/97e8c7d00db8c4bd4a532ab99e5f0bbdc2243234/uid_entrypoint.sh#L8) fails because of the read-only file system. After that git+ssh checkouts fail.

**To Reproduce**

Start argocd-repo-server in Openshift and try to clone a repository with ssh.

**Expected behavior**

argocd-repo-server should be able to check out Git repositories via ssh.

**Version**

```shell
argocd: v2.1.0-rc2+b067879
  BuildDate: 2021-08-03T17:08:07Z
  GitCommit: b067879892d3586bb2392dfc2f0932e9bde231dd
  GitTreeState: clean
  GoVersion: go1.16.5
  Compiler: gc
  Platform: linux/amd64
```

**Logs**

```
time="2021-08-12T07:41:12Z" level=error msg="`git fetch origin --tags --force` failed exit status 128: No user exists for uid 1000690000\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists." execID=oFo59
```

### PR DESCRIPTION
**Pull request by Reamer**
This PR removes the `/etc/passwd` adjustments that were required for Openshift 3.x. These changes are not required in Openshift 4.x.

Fixes  #6968
Checklist:

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] ~I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~
* [ ] ~Does this PR require documentation updates?~
* [ ] ~I've updated documentation as required by this PR. ~
* [ ] ~Optional. My organization is added to USERS.md.~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] ~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by sbose78** [comment]
Looks good to me, from an upstream perspective, I support removal of support for Openshift 3.x in order to be uncompromising with security best practices for deploying Argo CD on Openshift 4.x and Kubernetes.

As always, I'll be happy to help/assist anyone who's interested in finding solution that would also work for Openshift 3.x.

**Review by jannfis — CHANGES_REQUESTED** [review]
Hey @Reamer, thanks for this PR. 

I see you opened this PR against `release-2.1` branch, but we only accept PRs for the master branch. Can you please rebase or re-open this PR for the `master` branch?

**Comment by Reamer** [comment]
@jannfis 
I changed the base to master.

**Comment by jannfis** [comment]
Thanks @Reamer. For some reason, GitHub doesn't fire the required CI checks, and I see no means to start them either. I suspect this is due to the change in base branch. Also, the DCO check fails.

Can you please close the PR, ensure that your commits are signed off and then open a new PR so that CI will get unconfused?

**Comment by Reamer** [comment]
I have performed a rebase to the current master followed by a force push. This seems to have helped.

**Review by jannfis — APPROVED** [review]
LGTM, @Reamer. Thanks for this improvement!

**Comment by alexmt** [comment]
Thank you !

**Comment by kjvellajr** [comment]
This change causes a regression with the ArgoCD Helm chart v2.9.0+

https://github.com/argoproj/argo-helm/commit/03aecd7af94172b04e94a967662c62cb3b83103f

The Helm chart expects `uid_entrypoint.sh` on the PATH.

`container_linux.go:380: starting container process caused: exec: "uid_entrypoint.sh": executable file not found in $PATH: unknown`

**Comment by jannfis** [comment]
@kjvellajr I think jumping to a new minor release with a Chart written for a previous version is not a supported upgrade path. Upgrade instructions for Argo CD from one minor version to the next always includes to update manifests as well (exactly for such kind of changes).

**Comment by kjvellajr** [comment]
@jannfis To be clear I noticed this issue with the current version of the Helm chart v3.12.1 https://github.com/argoproj/argo-helm/blob/argo-cd-3.12.1/charts/argo-cd/templates/argocd-repo-server/deployment.yaml#L44 which uses ArgoCD v2.0.5 . 

In the mean time I am using a temporary fix for the Helm chart that is compatible with ArgoCD v2.1.0. I will keep an eye out for future updates to the Helm chart to include fixes to the repo-server deployment command.

**Pull request merged**
