### PR TITLE
docs: remove numbers from proposals documents

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

It typically takes several days to merge the proposal so it is hard to guess which number filename should have. Can we just remove the number to avoid confusion?

### CODE REVIEW

**Comment by alexmt** [comment]
@sbose78  WDYT?

**Review by sbose78 — APPROVED** [review]
I think that's fair 👍  I'd avoid removing the number from the proposal template since the idea is to ensure it remains on the top and discoverable. Otherwise, I'm good.

**Comment by alexmt** [comment]
Good point about discoverability. I agree this is important - maybe replaced number with creation date ? e.g. `08-06-21_config-management-plugin-v2.md` ?

**Comment by jannfis** [comment]
I'd think that a properly sortable date string may be more suitable for this, e.g. `YYYY-MM-DD`

**Pull request closed without merging**
