### PR TITLE
Fix API version for Deployment resources in e2e tests to app/v1

### LINKED ISSUE #2371: End-to-End tests not working with Kubernetes v1.16
**Describe the bug**

With version 1.16, Kubernetes has removed many resource types from `app/v1beta2` and moved them to `app/v1` instead (see also https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement/). The ArgoCD end-to-end tests fail when being run against a Kubernetes v1.16 cluster, because many of the test data still use `app/v1beta2` API. 

This might also apply to applications in `argocd-example-apps`, as @alexmt pointed out in Slack.

**To Reproduce**

Run end-to-end tests against a Kubernetes v1.16 cluster. As an example, apply one of the resource definitions to the cluster manually:

```
$ kubectl apply -f test/e2e/testdata/crashing-guestbook/guestbook-deployment.yaml
error: unable to recognize "test/e2e/testdata/crashing-guestbook/guestbook-deployment.yaml": no matches for kind "Deployment" in version "apps/v1beta2"
```

**Expected behavior**

End-to-End tests run successfully against Kubernetes v1.16 clusters.

**Version**

ArgoCD HEAD from 09/27/19

```
argocd: v1.3.0+c55a7f7.dirty
  BuildDate: 2019-09-27T15:20:30Z
  GitCommit: c55a7f7600ca3f2022a5c42d2a52e6a76d985e47
  GitTreeState: dirty
  GoVersion: go1.12.5
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.3.0+bd2c4f1
  BuildDate: 2019-09-27T00:34:20Z
  GitCommit: bd2c4f116105dcae4c9bbd30e7bc5c735d74b713
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: 0.13.1
```
Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-16T14:14:51Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Logs**

```
Paste any relevant application logs here.
```

**Have you thought about contributing a fix yourself?**

Open Source software thrives with your contribution. It not only gives skills you might not be able to get in your day job, it also looks amazing on your resume. 

If you want to get involved, check out the 
[contributing guide](https://github.com/argoproj/argo-cd/blob/master/docs/CONTRIBUTING.md), then reach out to us on [Slack](https://argoproj.github.io/community/join-slack) so we can see how to get you started.

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #2371

### CODE REVIEW

**Comment by jannfis** [comment]
Oh, actually broke `TestDeprecatedExtensions` - gotta have to look into that one.

**Comment by jannfis** [comment]
CircleCI E2E test fails with `Install and start K3S v0.5.0`, but on my local e2e test, something else failed too (`TestExcludedResource`). Investigation continues..

**Comment by jannfis** [comment]
Turns out that on a second local run, `TestExcludedResource` ran through fine. 

PR ready for review/merge at your discretion.

**Review by alexec — APPROVED** [review]
I approve!

**Pull request merged**
