### PR TITLE
feat: add refresh/hard refresh apps button #7256

### LINKED ISSUE #7256: ui: Add refresh/hard refresh apps button
# Summary

To have a Refresh/Hard Refresh Apps button next to the Sync Apps button, so multiple apps can be selected to be refreshed.

# Motivation

We frequently run into situations where we have hundreds of apps that need to be refreshed or hard refreshed due to some upstream issue like the repository was not reachable. Currently some users who are heavy web-ui users have to click through each app that needs to be refreshed.

# Proposal

It would be helpful to have a refresh button next to the Sync Apps button, so multiple apps can be refreshed.

### PR DESCRIPTION
**Pull request by ciiay**
Note on DCO:
Closes #7256 

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Preview:
refresh apps button and refresh apps panel

### CODE REVIEW

**Review by ishitasequeira — COMMENTED** [review]
Thanks @ciiay for the PR. I think the list of applications could be abstracted as a reusable component as it’s also used by the sync apps sliding panel. WDYT?

**Review by ishitasequeira — APPROVED** [review]
LGTM
@rbreeze PTAL

**Comment by chrisob** [comment]
We've really been looking forward to a global refresh button :heart_eyes:  

Any chance this PR could be reviewed & sneak into a near-future release? @rbreeze @ishitasequeira

**Review by alexmt — APPROVED** [review]
Thanks for attaching screenshot!

**Pull request merged**
