### PR TITLE
Fixes issue diffing secrets

### LINKED ISSUE #2206: 1.2.0-rc2 Warning during secret diffing
It's all the same as #1923, but version is 1.2.0-rc2. Logs while refreshing application:

```
time="2019-08-23T12:33:19Z" level=info msg="Refreshing app status (normal refresh requested), level (2)" application=app-staging
W0823 12:33:19.405876       1 listers.go:77] can not retrieve list of objects using index : Index with name namespace does not exist
time="2019-08-23T12:33:19Z" level=info msg="Comparing app state (cluster: https://??.??.??.??, namespace: staging)" application=app-staging
time="2019-08-23T12:33:19Z" level=warning msg="Could not unmarshal to object of type /v1, Kind=Secret: illegal base64 data at input byte 0"
time="2019-08-23T12:33:19Z" level=warning msg="Could not unmarshal to object of type /v1, Kind=Secret: illegal base64 data at input byte 0"
time="2019-08-23T12:33:19Z" level=info msg="Skipping auto-sync: application status is Synced" application=app-staging
time="2019-08-23T12:33:19Z" level=info msg="Update successful" application=app-staging
time="2019-08-23T12:33:19Z" level=info msg="Reconciliation completed" application=app-staging fields.level=2 time_ms=571.727666
```

Correct: https://github.com/argoproj/argo-cd/blob/master/util/diff/diff.go#L390
Incorrect: https://github.com/argoproj/argo-cd/blob/v1.2.0-rc2/util/diff/diff.go#L390

Looks like it must be fixed before 1.3.

### PR DESCRIPTION
**Pull request by alexec**
Closes #2206

### CODE REVIEW

**Review by alexmt — CHANGES_REQUESTED** [review]
The `KioqKioq` showup in UI . It will concern users since it looks like password. Why '+++++' does not work?

**Comment by leominov** [comment]
@alexmt `KioqKioq` used only in tests.

**Comment by alexec** [comment]
I _think_ that `++++++++` is valid base64, but is non-printable.
I _think_ that `++++++++` is not valid as base 64 encodings must be multiples of 4 characters long (that is 9 characters long).  
I think you have a good point about looking too much like a password. I'll have a deeper think.

**Review by alexmt — APPROVED** [review]

**Comment by leominov** [comment]
@alexec we can't find this changes in 1.2.0 or... 1.2.1

**Pull request merged**
