### PR TITLE
fix: return a `codes.NotFound` error when trying to get a non-existent repository

### LINKED ISSUE #5951: Get() Repository returning confusing reply for non-existing repositories
**Describe the bug**

I want to check if a specific `repository` exists via api. This was implemented as part of https://github.com/argoproj/argo-cd/issues/2618. In case the `repository` exists, all is good. If it doesn't exists, I'm getting confusing error messages.

Requesting a non-existing `https` repository:
```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k https://localhost:8080/api/v1/repositories/https%3A%2F%2Fgitlab.com%2Ffoo%2Fexample-project.git | jq
```
Instead of a `404` I'm getting a somewhat empty repository back:
```json
{
  "repo": "https://gitlab.com/foo/example-project.git",
  "connectionState": {
    "status": "Failed",
    "message": "Unable to connect to repository: failed to get index: 503 Service Temporarily Unavailable",
    "attemptedAt": "2021-04-02T11:33:48Z"
  },
  "type": "git"
}
```
Pretty similar for `git` repositories:
```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k https://localhost:8080/api/v1/repositories/git%40gitlab.com%3Afoo%2Fexample-project.git | jq
```
```json
{
  "repo": "git@gitlab.com:foo/example-project.git",
  "connectionState": {
    "status": "Failed",
    "message": "Unable to connect to repository: parse \"git@gitlab.com:foo/example-project.git\": first path segment in URL cannot contain colon",
    "attemptedAt": "2021-04-02T12:24:45Z"
  },
  "type": "git"
}
```
**To Reproduce**
```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k https://localhost:8080/api/v1/repositories/git%40gitlab.com%3Afoo%2Fexample-project.git | jq
```

**Expected behavior**

I would expect a `404` for curl, and for the go [RepositoryServiceClient](https://pkg.go.dev/github.com/argoproj/argo-cd@v1.8.7/pkg/apiclient/repository#RepositoryServiceClient) `Get()` call to return a `nil` pointer instead and an appropriate `error`, much like the `DeleteRepository()` call:

```go
	repoQuery := repository.RepoQuery{
		Repo: "git@gitlab.com:foobar/example-project.git",
	}
	_, err := e.client.DeleteRepository(ctx, &repoQuery)
```
> cannot delete Argocd repository: rpc error: code = NotFound desc = repo 'git@gitlab.com:foobar/example-project.git' not found

**Version**

```shell
argocd: v2.0.1+33eaf11.dirty
  BuildDate: 2021-04-17T04:23:35Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: dirty
  GoVersion: go1.16.3
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v2.0.1+33eaf11
  BuildDate: 2021-04-15T22:31:51Z
  GitCommit: 33eaf11e3abd8c761c726e815cbb4b6af7dcb030
  GitTreeState: clean
  GoVersion: go1.16
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.9.4 2021-02-09T19:22:10Z
  Helm Version: v3.5.1+g32c2223
  Kubectl Version: v0.20.4
  Jsonnet Version: v0.17.0
```

### PR DESCRIPTION
**Pull request by Cylix**
### Context
Addressing #5951. More details can be found in the issue discussion, but as a quick summary:
- `argo repo get <repo>` and `/api/v1/repositories/{repo}` are documented as `Get a **configured** repository by URL`.
- However, `Get() Repository` does not return an error when querying a repo that is not configured in Argo.
- Instead, it initializes an empty repository object, and tests the connectivity: errors returned to the user only come from the connectivity test.

In particular, `Get() Repository` relies on this [db.getRepository](https://github.com/argoproj/argo-cd/blob/master/util/db/repository.go#L87-L105).  However, this function [returns a valid repository object when no configured repository is found](https://github.com/argoproj/argo-cd/blob/master/util/db/repository.go#L104), rather than nil with an error. This contrasts with `db.DeleteRepository` that does [return an error for unconfigured repositories](https://github.com/argoproj/argo-cd/blob/master/util/db/repository.go#L171)

### Change
`db.GetRepository` is called in different places, so I decided to avoid touching it, and instead implement a new `db.RepositoryExists` function that returns whether a repository matching the query is configured in Argo.

I then called this function from `Get() Repository` and propagated a `codes.NotFound` error as appropriate.

### Alternatives
I thought about a couple of alternative implementations, let me know if an approach is preferred:
- Modifying `db.GetRepository` to return an error when a repository is not found, rather than an empty repository object. This would need to be done carefully to avoid breaking things for logic that relies on that current behavior of `db.GetRepository`. A few approaches I can think about:
  - Adding a `default` parameter to `db.GetRepository` that would be the default return value if no repository is found
  - Moving the default empty repository initialization outside of `db.GetRepository` to every call site when `repo == nil && err == nil`
 - Keep the existing logic, but add a new field in the repository object to identify whether a repository is configured in Argo
 - Keep the existing logic without any change, but update the documentation to correctly reflect the expectation (basically, change the `Get a **configured** repository by URL`).

#### Manual Testing
Configured Repo (API):

```bash
$ curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k http://localhost:8080/api/v1/repositories/https%3A%2F%2Fgithub.com%2Fcylix%2Fcpp_redis | jq

{
  "repo": "https://github.com/cylix/cpp_redis",
  "connectionState": {
    "status": "Successful",
    "message": "",
    "attemptedAt": "2021-10-26T05:41:17Z"
  },
  "type": "git",
  "project": "default"
}
```

Configured Repo (CLI):

```bash
$ argocd --server localhost:8080 --plaintext --grpc-web repo get https://github.com/cylix/cpp_redis
TYPE  NAME  REPO                                INSECURE  OCI    LFS    CREDS  STATUS      MESSAGE
git         https://github.com/cylix/cpp_redis  false     false  false  false  Successful
```

Unconfigured Repo (API):

```bash
$ curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k http://localhost:8080/api/v1/repositories/https%3A%2F%2Fgithub.com%2Ffoo%2Fexample-project.git | jq

{
  "error": "repo 'https://github.com/foo/example-project.git' not found",
  "code": 5,
  "message": "repo 'https://github.com/foo/example-project.git' not found"
}
```

```bash
$ curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k http://localhost:8080/api/v1/repositories/https%3A%2F%2Fgitlab.com%2Ffoo%2Fexample-project.git | jq

{
  "error": "repo 'https://gitlab.com/foo/example-project.git' not found",
  "code": 5,
  "message": "repo 'https://gitlab.com/foo/example-project.git' not found"
}
```

```bash
curl -s -H "Authorization: Bearer $ARGOCD_TOKEN" -k http://localhost:8080/api/v1/repositories/git%40gitlab.com%3Afoo%2Fexample-project.git | jq

{
  "error": "repo 'git@gitlab.com:foo/example-project.git' not found",
  "code": 5,
  "message": "repo 'git@gitlab.com:foo/example-project.git' not found"
}
```

Unconfigured Repo (CLI):

```bash
$ argocd --server localhost:8080 --plaintext --grpc-web repo get https://github.com/foo/example-project.git
FATA[0000] rpc error: code = NotFound desc = repo 'https://github.com/foo/example-project.git' not found
```

#### Unit Tests
Added unit tests coverage ✅ 

### Checklist

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

### Misc.
Fixes #5951

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks for this PR @Cylix and also for the detailed description into your train of thoughts. That is much appreciated!

I have a change request, please see below.

**Comment by jannfis** [comment]
> Do you know what's the way to trigger the pending workflows? Thanks!

The pending CI workflows need to be triggered manually by someone with write permissions by the repo. This is a GitHub actions security feature and applied for first-time contributors to a given repository. I have triggered the workflow.

**Comment by Cylix** [comment]
> The pending CI workflows need to be triggered manually by someone with write permissions by the repo. This is a GitHub actions security feature and applied for first-time contributors to a given repository. I have triggered the workflow.

Got it, thanks for the explanation and for triggering the pipeline!

It seems the CI passed this time around 🎉  Let me know if there is anything I should adjust (code logic, unit tests, whatever...) 🙃

**Review by jannfis — APPROVED** [review]
LGTM, thank you @Cylix !

**Pull request merged**
