### PR TITLE
feat: Make spec.source.helm.values field accepts either a string or a rawExtension

### LINKED ISSUE #2936: Make Helm values field templatable using Kustomize
# Summary

Use a YAML structure for `argoproj.io/v1alpha1/Application.spec.source.helm.values` instead of `string` to allow Kustomize to change properties per environment

# Motivation

Helm allows to template charts using YAML files typically called `values.yaml` files

I found myself repeating code across environments for charts that include their configuration on these `values.yaml` files, like Prometheus chart. 
It happens that loads of apps are using YAML files themselves to be configured

ArgoCD currently supports Kustomize which is a great tool to template YAML files and could solve this problem easily but since `argoproj.io/v1alpha1/Application.spec.source.helm.values` is a string Kustomize can't change few properties.

In this particular case, it could be even better since Prometheus configuration itself is expressed on YAML format so I could tweak tiny bits thanks to Kustomize

```
- prometheus-kustomize
  |- base
  |  |- kustomization.yaml
  |  |- prometheus.yaml
  |- ci
  |  |- kustomization.yaml
  |  |- patch.yaml
...
```

`prometheus.yaml` would contain all the common configuration
- chart repo
- chart version
- release name
- Alertmanager global webhook shared across all environments but without receivers
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    chart: prometheus
    helm:
      releaseName: prometheus
      values:
        alertmanagerFiles:
          alertmanager.yml:
            global:
              slack_api_url: https://hooks.slack.com/services/xxxxxxx
  ```

`patch.yaml` little changes like which channel on Slack will receive the notifications

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  source:
    helm:
      values:
        alertmanagerFiles:
          alertmanager.yml:
            receivers:
              - name: prometheus-alert
                slack_configs:
                  - channel: '#ci-alerts'
```

# Proposal

Change the field [`spec.source.helm.values`](https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L182) to be a generic YAML structure (`map`?) to allow Kustomize to template these values

### PR DESCRIPTION
**Pull request by crenshaw-dev**
https://github.com/argoproj/argo-cd/pull/8794 plus some changes I'd requested.

Fixes https://github.com/argoproj/argo-cd/issues/2936

This change makes it possible to store either a string or a map in `spec.source.helm.values`. Using a map will allow people to kustomize-patch the values field.

### CODE REVIEW

**Comment by tiagomeireles** [comment]
Curious if this will make it into 2.4?

**Comment by crenshaw-dev** [comment]
@tiagomeireles I doubt it. It's very close, but I want to try using a `RawExtension` at the root of `values` instead of nesting it. That'll make the code easier to read and will avoid an ugly `jq` hack in the swagger generation code.

**Comment by crenshaw-dev** [comment]
Closing until I have time to give this another shot.

**Comment by therapy-lf** [comment]
seeking for this feature 😞

**Comment by crenshaw-dev** [comment]
Taking volunteers to pick this back up! I'd happily provide guidance. Just don't have time to finish it.

**Comment by alexef** [comment]
@crenshaw-dev I would like to pick this up 👋

**Pull request closed without merging**
