### PR TITLE
fix: ui cluster server url overlaps #11600

### LINKED ISSUE #11600: ui: cluster server url label overlaps
When the Cluster Server URL is long, it overlaps. 
The server URL information is redundant. There are multiple places on the cluster web page where this information can be found. We can remove the label on the right or wrap the server URL when it is too long.
Screen Shot 2022-12-07 at 2 49 14 PM

### PR DESCRIPTION
**Pull request by jiwonaid**
Signed-off-by: Jiwon Kim <jiwonaid0@gmail.com>

Note on DCO:

Closes #11600

1. This PR will make the `Clusters(cluster-details.tsx)` the same as the `Projects(project-details.tsx)` so that the cluster server url is not overlapped

```tsx
// ref: https://github.com/argoproj/argo-cd/blob/master/ui/src/app/settings/components/project-details/project-details.tsx#L141-L146
    public render() {
        return (
            <Consumer>
                {ctx => (
                    <Page
                        title='Projects'
```

2. Also, path `Cluster` is changed to `Clusters`

Before change
before

After change
after

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jiwonaid** [comment]
cc. @saumeya

**Review by saumeya — APPROVED** [review]
LGTM, thanks.
Do add screenshots of your change.

**Comment by jiwonaid** [comment]
Before change
before

After change
after

**Review by rbreeze — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@rbreeze should this be cherry-picked back to 2.5 and/or 2.6 since it's a bug fix?

**Comment by rbreeze** [comment]
@crenshaw-dev I think that's a good idea 👍🏻

**Pull request merged**
