### PR TITLE
feat(ui): add status panel extensions

### LINKED ISSUE #15775: Add status panel extensions
# Summary

Add a new status panel extension hook to customize the status panel.

# Motivation

Mentionned in #14463, it would be nice to be able to extend the status panel of an application to display extra information on the application's status. Here is an example of what it would look like for the progressive sync feature:

image

Similar to optional status such as the sync windows notification.

# Proposal

Add a new type of extension in: https://github.com/argoproj/argo-cd/blob/9d48b7a198efadd2016c41f39a599c3abb9ab2fa/ui/src/app/shared/services/extensions-service.ts#L4

The Application should be passed to the extensions

Very similar to other types of extension.

### PR DESCRIPTION
**Pull request by alexymantha**
Adds an extension hook to the status panel. Here is an example of 2 dummy extensions using this feature: 
image

Closes #15775

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
	* Could not find any tests for what I changed, is there no tests or did I miss them?
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by alexymantha** [comment]
I tested with this: https://github.com/alexymantha/argocd-progressive-sync-extension

**Comment by alexymantha** [comment]
Sure @ashutosh16! I'll try to join this week's meeting if I find the time

**Comment by ashutosh16** [comment]
@alexmt  What are your thoughts on this feature? Do you expect any widget to be presented differently?

**Comment by ashutosh16** [comment]
Here's my proposal for making this feature into a generic external plugin on the status panel. It's similar to the existing plugin that renders as a `more` tab on the  resource, where Argocd operator can add plugins as tabs. When a user clicks on a plugin in Argocd's status panel, a fly-out widget containing the plugin is displayed.  
There are a lot of potential uses for developing plugins on the Argocd tree-view status panel.

@alexymantha  Would you be interested in extending the feature to incorporate the above changes? Let me know.

**Comment by alexymantha** [comment]
@ashutosh16 Yes I'd be happy to extend it with your suggestion! I will be working on that in the next few days

**Comment by ashutosh16** [comment]
@alexymantha Is the PR ready for review? It would be great if we get this feature in 2.10

**Comment by alexymantha** [comment]
> @alexymantha Is the PR ready for review? It would be great if we get this feature in 2.10

I just have a bug to iron out and it will be ready to review. I will try to get it done this week.

**Comment by alexymantha** [comment]
@ashutosh16 Figured it out, the bug was coming from my extension, not this PR so the PR is ready to review.

Here's a short video showing the flyout panel:

https://github.com/argoproj/argo-cd/assets/1365231/7a1d6243-e79c-414d-ade7-d2e1215e864a

**Comment by ashutosh16** [comment]
@alexymantha  I pulled in the latest changes and I'm seeing few issues.
- The panel extension UI is not working as expected. I used the [repo](shttps://github.com/alexymantha/argocd-progressive-sync-extension/tree/main/ui/src) to test the change
  - Banner seems to incorrect
  - Slider is not working
Screenshot 2023-12-11 at 10 14 58 AM

- Extension on the other resource is broken. 
Error
```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at initLegacyExtensions (webpack-internal:///./src/app/shared/services/extensions-service.ts:33:10)
<img width="1481" alt="Screenshot 2023-12-11 at 10 14 58 AM" src="https://github.com/argoproj/argo-cd/assets/11219262/28cccddc-ebac-4588-a336-69659665f025">
```

**Comment by alexymantha** [comment]
My bad @ashutosh16, I forgot to merge the newest changes into the extension. Can you try the latest version? Tried a similar setup as yours and it works on my side with the up to date extension

**Comment by ashutosh16** [comment]
@alexymantha  The UI appears to be broken when I load the panel extension, the other tabs like App details, or any other resource like rollout/svc. Could you please confirm that the other parts of the UI are working for you as well?


Stacktrace:

TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at initLegacyExtensions (webpack-internal:///./src/app/shared/services/extensions-service.ts:33:10)
    at ExtensionsService.getResourceTabs (webpack-internal:///./src/app/shared/services/extensions-service.ts:40:5)
    at ResourceDetails (webpack-internal:///./src/app/applications/components/resource-details/resource-details.tsx:263:142)
    at renderWithHooks (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10031:22)
    at updateFunctionComponent (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11760:24)
    at beginWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:12752:18)
    at beginWork$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:15657:18)
    at performUnitOfWork (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14999:16)
    at workLoopSync (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:14984:26)

**Comment by ashutosh16** [comment]
@alexymantha  Thanks for your wonderful contributions. The feature looks awesome to me and looking forward in using  many ways!

https://github.com/argoproj/argo-cd/assets/11219262/edbea67f-ce0a-411a-aa42-531c8785cc80

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
