### PR TITLE
feat(appset): add Support for AzureDevops Webhooks

### LINKED ISSUE #15046: Add support for Azure DevOps webhooks in appsets
# Summary

Add support for Azure DevOps webhooks in appsets.

# Motivation

Azure DevOps webhook support was already implemented with #14969. This change did not include appsets.

# Proposal

Add the relevant cases in https://github.com/argoproj/argo-cd/blob/master/applicationset/webhook/webhook.go
Add testdata and tests in the corresponding test file.

### PR DESCRIPTION
**Pull request by robinlieb**
Closes #15046

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by todaywasawesome** [comment]
Wonder why this is throwing errors.

**Review by ishitasequeira — COMMENTED** [review]
I see below errors:

```
Error: applicationset/webhook/webhook.go:88:12: undefined: errBasicAuthVerificationFailed
Error: applicationset/webhook/webhook.go:153:12: undefined: a
Error: applicationset/webhook/webhook.go:154:7: undefined: errors
Error: applicationset/webhook/webhook.go:154:22: undefined: errBasicAuthVerificationFailed
Error: applicationset/webhook/webhook.go:203:3: undefined: change
Error: applicationset/webhook/webhook.go:204:3: undefined: change
```

**Comment by robinlieb** [comment]
@ishitasequeira thanks for the hint! Issues are resolved and tests are green, I think this is now ready for review.

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

@alexmt @crenshaw-dev could you take another look at this?

**Review by crenshaw-dev — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
