### PR TITLE
docs(webhook): use real cm name instead of placeholder

### PR DESCRIPTION
**Pull request by dosmanak**
The document says I should registed configMap named argocd-notifications-cm but then uses placeholder in examples.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by morey-tech — APPROVED** [review]

**Review by gdsoumya — APPROVED** [review]

**Comment by gdsoumya** [comment]
@dosmanak can you run `make codegen` to fix the ci failures?

**Comment by blakepettersson** [comment]
Looks like a duplicate of #16440

**Comment by blakepettersson** [comment]
I think the docs change actually needs to be done in notifications-engine first 😢 

see https://github.com/argoproj/notifications-engine/blob/84b9f79136041bf0d6854c151b5bbad031c4b053/docs/services/webhook.md

**Comment by dosmanak** [comment]
> Looks like a duplicate of #16440

Related but not the same file.

**Comment by dosmanak** [comment]
> @dosmanak can you run `make codegen` to fix the ci failures?

Oh, when I run `make codegen` it reverted my changes.... I have not realized the file was generated.

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Comment by dosmanak** [comment]
Here is the PR to notifications repo https://github.com/argoproj/notifications-engine/pull/264

**Pull request merged**
