### PR TITLE
docs(declarative/repo-ssh): url needs git suffix

### PR DESCRIPTION
**Pull request by IzioDev**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by morey-tech** [comment]
> interesting @morey-tech, do you know for which argocd version this test was run against?

I referenced the latest, so v2.7 would definitely have it, but it looks like the normalization of the URLs has been a part of Argo CD since v0.

> without the `.git` it didn't work on my end, but I might have a specific configuration or version that didn't do it?

I see now that some Git providers require that the `.git` extension be used. What's your provider?
https://github.com/argoproj/argo-cd/blob/8840929187f4dd7b9d9fd908ea5085a006895507/docs/operator-manual/declarative-setup.md?plain=1#L171

> Shall we close this PR and move to an issue if I can reproduce it?

This might not be an issue, more of a nuance of how some Git providers work. But creating an issue would make this more discoverable for anyone who runs into it in the future.

**Comment by IzioDev** [comment]
> What's your provider?

It's Github, private repository, repo isn't at an organization level but as a user repository

**Comment by IzioDev** [comment]
Here is my configuration:
```yaml
apiVersion: v1
kind: Secret
metadata:
    name: private-repo
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    type: git
    url: git@github.com:IzioDev/test-argocd.git
    sshPrivateKey: |-
```

**Review by morey-tech — APPROVED** [review]
It makes sense to add the suffix if even GitHub requires it.

**Comment by IzioDev** [comment]
@morey-tech Do you know if other repository reference are impacted too by this change? Shall we change it for all mentioning of reference or only the secret part is enough?

**Review by jenting — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Review by jenting — APPROVED** [review]

**Review by todaywasawesome — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]
LGTM

**Pull request merged**
