### PR TITLE
chore: move dependencies to dev dependencies

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Justification:

There are a lot of Snyk issues for "vulnerabilities" which aren't actually applicable since these libraries aren't bundled into user code.

How I decided what to move:

1. if it said webpack, I moved it
2. if it started with "@types", I moved it 
2. if it looked like an obvious dev dependency (unit test libraries, webpack loaders, ...) I moved it

How I tested:
I built the image, loaded the UI, created an app, looked at a diff, looked at logs, and poked around the Swagger UI.

I'd appreciate if a UI person could take a good look at this and make sure I'm not doing anything silly.

### CODE REVIEW

**Comment by pasha-codefresh** [comment]
actually as i understand it wasnt goal of this PR, but wanted let you know

**Review by pasha-codefresh — APPROVED** [review]
LGTM

**Comment by crenshaw-dev** [comment]
@pasha-codefresh yep, this is more about making Snyk only report user-relevant vulnerabilities rather than developer-relevant vulnerabilities. Thanks for the review!

**Review by rbreeze — APPROVED** [review]
LGTM!

**Review by alexmt — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@alexmt merged!

**Comment by crenshaw-dev** [comment]
Apparently I messed up things, working on it...

**Comment by crenshaw-dev** [comment]
@alexmt fixed. Looks like I messed something up during merge. Should be good to go when the checks pass.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.2 for 2.2.12 and release-2.3 for 2.3.7.

**Pull request merged**
