### PR TITLE
fix: Update Azure identity services (1.1.1 -> 1.11.1) and pygments (2.15.0 -> 2.15.1)

### PR DESCRIPTION
**Pull request by harshitasao**
Fixed the 2 vulnerabilities which are reported by the [scorecard report.](https://scorecard.dev/viewer/?uri=github.com/argoproj/argo-cd)

1. https://osv.dev/PYSEC-2023-117
2. https://osv.dev/GHSA-m5vv-6r4h-3vj9

Part of #18921 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
Looks like tests are failing on change. These are pretty big version changes. Is there a version change that's closer and closes cves?

**Comment by jannfis** [comment]
https://osv.dev/vulnerability/GHSA-m5vv-6r4h-3vj9 states that for the Go Azure SDK, the flaw was fixed in v1.6.0, while this PR pulls in 1.11 (which is probably the latest stable release). 

However, I think it might be worthwhile to fix the compatibility issue.

**Comment by wanghong230** [comment]
Better has an Azure environment to do a validation.

**Comment by todaywasawesome** [comment]
We got pyments done in #19784 - this azure change is significant though and needs real testing.

**Comment by blakepettersson** [comment]
This has been solved with #20578.

**Pull request closed without merging**
