### PR TITLE
docs: add api field example in the appset security doc

### LINKED ISSUE #9352: AppSets allow arbitrary `api` fields for SCM generators - document risk to secrets
# Summary

I think we should edit documentation to further emphasize that ApplicationSets should _only_ be createable/editable by admins. 

There are numerous risks (including arbitrary `Project` fields). One risk is that a malicious user could set the `api` field for an API endpoint to something that they control. They could then read the secret which is sent to that endpoint by the ApplicationSet controller.

# Motivation

As an Argo CD admin I might be tempted to grant non-admins access to create or update ApplicationSet resources. It would be good to know that secret exfiltration is a risk.

# Proposal

The information described above should be added to the ApplicationSet documentation, and links to that documentation should be added to each place in the Argo CD docs that suggest ApplicationSet use cases.

### PR DESCRIPTION
**Pull request by spzala**
It seems like most of the work for the mentioned issue below is done
under the PR #9466 but from the issue description, it's probably
worth to mention the example as added here.

Closes #9352

Signed-off-by: Sahdev Zala <spzala@us.ibm.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by spzala** [comment]
cc @crenshaw-dev

**Review by crenshaw-dev — APPROVED** [review]
Very helpful clarity. Thanks @spzala!

**Comment by spzala** [comment]
Thank you, @crenshaw-dev

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.8.

**Pull request merged**
