### PR TITLE
feat(prom): Add prometheus metrics reset support #5287

### LINKED ISSUE #5287: Prometheus metrics cache causes scaling issues with ephemeral projects and apps
# Summary

When a project and/or application is deleted, it is not deleted from Prometheus metrics and stays in cache until the ArgoCD application controller's next rolling-update.

# Motivation

We use ArgoCD in our QA environment with temporary projects and associated applications.
Each time we create a custom branch on a repository, it creates the resources in ArgoCD to bootstrap a dedicated QA environment. However, when the ArgoCD resources are deleted, they are kept in Prometheus metrics.
We have about 2000 to 4000 applications, and we delete/create about 500 times every day.

Prometheus endpoint `/metrics` sometimes timeout after 10 seconds due to the huge amount of metrics. It also put pressure on metrics retention.

# Proposal

I see three ways of addressing this:
- from time to time within the app, resetting metrics with the Prometheus client
- use a specific API endpoint to allow resetting the Prometheus metrics
- add support on app/project deletion to also remove the associated metrics

There are probably other solutions as well. In the meantime, we did something very naive to mitigate by scheduling a cronjob to delete the argocd-application-controller pod every night.

### PR DESCRIPTION
**Pull request by victorboissiere**
Add support for Prometheus metrics reset schedule to fix #5287

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
Is there a use case for using a cron expression over something simpler such as an interval? We're thinking to make this simpler to use, as well as more consistent with our other controller flags (e.g. resync period, cache durations) and control this using an interval instead.

**Comment by victorboissiere** [comment]
@jessesuen, the only use case would be to make it explicit when the reset schedule runs.
But you're absolutely right. I haven't thought of using an interval. I will make the changes.
To keep it consistent with other flags, I propose to use `--metrics-cache-expiration`.

**Comment by victorboissiere** [comment]
@jessesuen I've updated the PR with the changes

**Review by alexmt — APPROVED** [review]
Thank you @victorboissiere . LGTM

**Pull request merged**
