### PR TITLE
fix: update rbac validation to support applications in different namespaces

### LINKED ISSUE #15333: Can't create project token for policies using applications in namespaces
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

This is related to [Applications in any namespace](https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/). 
When creating a project that leverages `spec.sourceNamespaces`, an operator might want to create an API token that is scoped to a single namespace inside the project, or even further to a specific application prefix inside a project. 

For example, in this project definition, we are allowing applications to be created in `my-namespace` and `my-other-namespace`. We want to create a role, `my-role` that can only create applications in the namespace `my-namespace` that start with `app-prefix`:

```yaml

apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  sourceNamespaces:
    - my-namespace
    - my-other-namespace
  roles:
    - name: my-role
      policies:
        - p, proj:my-project:my-role, applications, create, my-project/my-namespace/app-prefix-*, allow
```

When attempting to create a token with `argocd proj role create-token my-project my-role`, this will fail with:
```
FATA[0000] rpc error: code = InvalidArgument desc = invalid policy rule 'p, proj:my-project:my-role, applications, create, my-project/my-namespace/app-prefix-*, allow': object must be of form 'my-project/*' or 'my-project/<APPNAME>', not 'my-project/my-namespace/app-prefix-*' 
```

This can be worked around by removing the policy definition, creating the token, and adding the policy back to the project again.

**To Reproduce**
1. Apply manifest above.
2. Run  `argocd proj role create-token my-project my-role`

**Expected behavior**

The expectation is that the token can be created.

**Version**

```shell
$ argocd version
argocd: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.8.2+dbdfc71
  BuildDate: 2023-08-24T20:37:23Z
  GitCommit: dbdfc712702ce2f781910a795d2e5385a4f5a0f9
  GitTreeState: clean
  GoVersion: go1.20.7
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: could not get kustomize version: exec: "kustomize": executable file not found in $PATH
  Helm Version: v3.12.3+g3a31588
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by brycelowe**
When attempting to create a policy that allows or denies privileges for an application within a namespace you get the following error:

```
FATA[0000] rpc error: code = InvalidArgument desc = invalid policy rule 'p, proj:my-project:my-role, applications, get, my-project/my-namespace/app-prefix-*, allow': object must be of form 'my-project/*' or 'my-project/<APPNAME>', not 'my-project/my-namespace/app-prefix-*'
```

However, if you don't use the `project/namespace/application` format in the policy you don't get the appropriate privileges access the api:

```
➜  project-scratch-space k get appproject my-project -o=jsonpath='{.spec.roles}' | jq .
[
  {
    "name": "my-role",
    "policies": [
      "p, proj:my-project:my-role, applications, get, my-project/my-deployment-1, allow"
    ]
  }
]
➜  project-scratch-space curl -s -H "Authorization: Bearer <token>" "http://localhost:8080/api/v1/applications/my-deployment-1?appNamespace=my-namespace" | jq .
{
  "error": "permission denied",
  "code": 7,
  "message": "permission denied"
}
```

Update the regex validation of the policy object to include the namespace format.

With the namespace specified the appropriate information is returned:

```
➜  project-scratch-space k get appproject my-project -o=jsonpath='{.spec.roles}' | jq .
[
  {
    "name": "my-role",
    "policies": [
      "p, proj:my-project:my-role, applications, get, my-project/my-namespace/my-deployment-1, allow"
    ]
  }
]
➜  project-scratch-space curl -s -H "Authorization: Bearer <token>" "http://localhost:8080/api/v1/applications/my-deployment-1?appNamespace=my-namespace" | jq .
{
  "metadata": {
    "name": "my-deployment-1",
    "namespace": "my-namespace",
    "uid": "5894e229-7d87-4437-9d97-4e14515cec2d",
    "resourceVersion": "34648",
    "generation": 111,
    ... snip ...
    "controllerNamespace": "argocd"
  }
}
```

Fixes #15333

I looked to update the documentation for this, but based on what I saw it seems like the docs seem to indicate that this is the way it should work to begin with.  Though if I missed something, I'd be happy to update any documentation that needs it.

https://github.com/argoproj/argo-cd/blob/4abc9929281296122db0eace1607583187dd9944/docs/operator-manual/app-any-namespace.md#L136

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by gdsoumya — CHANGES_REQUESTED** [review]

**Review by gdsoumya — APPROVED** [review]
LGTM

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by muneebcui** [comment]
I noticed that this pull request was merged a while ago, but I couldn't find it in any of the recent releases. Could you please confirm if it's included in a release or if there's anything else needed for it to be included?

**Comment by muneebcui** [comment]
I noticed that this pull request was merged some time ago, but I couldn't find it in any of the recent releases. Could you please confirm if it's included in a release or if there's anything else needed for it to be included?

**Pull request merged**
