### PR TITLE
doc: update argocd-cm.yaml instructions for okta integration

### PR DESCRIPTION
**Pull request by msuthar-splunk**
- data.oicd has no effect on the integration
- SSO flow did not initiate at all without putting the URL for argocd at `data.url` in `argocd-cm.yaml`. This is specified in the keycloak integration instructions as well.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by tukak** [comment]
This helped me a lot, thank you

**Comment by pasha-codefresh** [comment]
@msuthar-splunk could you please restart checks?

**Comment by msuthar-splunk** [comment]
@pasha-codefresh I don't have permission to run Actions.

**Comment by pasha-codefresh** [comment]
just do empty commit please @msuthar-splunk

**Comment by msuthar-splunk** [comment]
@pasha-codefresh I have merged the upstream branch as the MR is quite old. If merge commits are not preferred, I can rebase.

**Comment by pasha-codefresh** [comment]
@msuthar-splunk you have failed docs generation because you missed in the end 
like this 

`
```yaml
data:
  url: https://path-to-argocd.io
```
`

**Comment by msuthar-splunk** [comment]
@pasha-codefresh I have added the missing `<!-- markdownlint-disable MD046 -->` at the end and followed the same pattern as other code blocks on the page. But the actions workflow is still failing. Not sure what I am missing here.

**Comment by pasha-codefresh** [comment]
@msuthar-splunk you have used restricted domain in example, if you change to such it will work

```<!-- markdownlint-disable MD046 -->
yaml
data:
  url: https://argocd.example.com

<!-- markdownlint-enable MD046 -->```

**Comment by pasha-codefresh** [comment]
@msuthar-splunk could you please do update? so we will be able to merge it?

**Comment by msuthar-splunk** [comment]
@pasha-codefresh I have updated the PR.

**Review by emagana-zz — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Comment by msuthar-splunk** [comment]
@pasha-codefresh What is needed to get this merged?

**Comment by pasha-codefresh** [comment]
Wait for approvers, i will handle this

**Review by alexmt — APPROVED** [review]

**Pull request merged**
