### PR TITLE
refactor: upgrade github.com/improbable-eng/grpc-web to most recent version

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

### CODE REVIEW

**Review by mayzhang2000 — APPROVED** [review]
LGTM

**Comment by sbose78** [comment]
Why aren't there any go.sum changes? 🤔

**Comment by alexmt** [comment]
Good point. There are two commits in https://github.com/improbable-eng/grpc-web and both have the v0.14.0 tag:

https://github.com/improbable-eng/grpc-web/commit/e757cdbb2b76
https://github.com/improbable-eng/grpc-web/commit/16092bd1d58a

So go mod thinks that nothing changed. Looks like I don't know how git works 😕

**Comment by alexmt** [comment]
Ah, nevermind. We just had a replace in go.mod .  Moving PR to draft.

**Pull request closed without merging**
