### PR TITLE
feat: make argocd installation manifests Istio compatible #2784

### PR DESCRIPTION
**Pull request by Cajga**
Checklist:

* [ X ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ X ] The title of the PR states what changed and the related issues number (used for the release note).
* [ X ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ Partially ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

I've signed the CLA no test build was done as I did not touch code.

This PR makes argocd installation manifests compatible with Istio. It implements this request: https://github.com/argoproj/argo-cd/issues/2784

In case this is accepted I will make a PR to have 2 examples with Istio ingress:
* TLS termination at Istio Ingress gateway
* TLS termination at ArgoCD server (Istio ingress gateway is configured to TLS PASSTHROUGH)

### CODE REVIEW

**Comment by Cajga** [comment]
So based on the tests, it seems I am modifying some code which are generated. Could someone give me a pointer how that code is generated?

**Comment by Cajga** [comment]
The failing test is false positive. The manifests files are changed by intention (that is the whole purpose of the PR).

**Comment by jannfis** [comment]
Hi @Cajga, after changing the Kustomization files and running `make manifests` (or `make manifests-local`), the resulting installation manifests have to be commited to your branch as well.

**Comment by Cajga** [comment]
> Hi @Cajga, after changing the Kustomization files and running `make manifests` (or `make manifests-local`), the resulting installation manifests have to be commited to your branch as well.

Ahh, got it, thanks for the pointer

**Comment by Cajga** [comment]
So, my PR is good for the `normal` installation but does not cover the `ha` manifests properly. I will need to work on it a bit more to have those covered as well.

**Comment by Cajga** [comment]
Ok, so according [this issue](https://github.com/istio/istio/issues/10724) Istio started to support the [recommended](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/) labels as well such as app.kubernetes.io/name and app.kubernetes.io/version.
As ArgoCD already using app.kubernetes.io/name I will close this PR now and open up a new one which adds only app.kubernetes.io/version.

**Pull request closed without merging**
