### PR TITLE
docs: add FOSSA badge to README

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Added newlines for readability.

Added the FOSSA scanning badge.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@jannfis how about this?

image

**Comment by jannfis** [comment]
Hm, I'm not sure whether I like the term *Code quality* there :thinking:  Maybe just have it read *Code*? But then, I'm not very opinionated about that either. What triggers me a little is the alignment of the font with the badges, though :joy:

**Comment by crenshaw-dev** [comment]
Yep, I like "code" better as well.

Truuue, the alignment sucks. I looked at using a table, but I couldn't do so without a header, which also feels weird.

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
