### PR TITLE
feat: added shorthand flags for follow and conatainre in app logs

### PR DESCRIPTION
**Pull request by ashupednekar**
Fixes [ISSUE https://github.com/argoproj/argo-cd/issues/15398]

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks for this PR, @ashupednekar. I agree that it would be good to have those shorthand flags similar to kubectl.

When you change CLI usage, you need to regenerate the CLI docs by `make clidocsgen` and push the changes to your PR, so that the CI will pass.

**Comment by ashupednekar** [comment]
Thanks, will do that in some time.

**Comment by ashupednekar** [comment]
Hi, added the doc update as described, one E2E test seems to be failing... but that's in the cluster command...


I've only changed the app log file... what could it be?

**Comment by jannfis** [comment]
@ashupednekar It's a flaky test, let me re-run the CI.

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
