### PR TITLE
fix: pss restricted securityContext

### LINKED ISSUE #9743: securityContext corrections and enhancements
The `securityContext` declarations in manifests should be as follows:

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

The three intended changes are:
1. Add `allPrivilegeEscalation: false` to redis containers
1. Drop `ALL` **not** `all`
1. Add `seccompProfile` type `RuntimeDefault`

These changes bring the argocd pods and controllers into compliance with PSS/restricted level.

https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

**To Reproduce**

Apply kyverno PSS/restricted policies to the ArgoCD manifests:

```bash
kustomize build https://github.com/kyverno/policies.git/pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/argoproj/argo-cd.git/manifests/ha/namespace-install) \
  -
```

Search for `result: fail`

**Expected behavior**

0 failures

**Actual behavior**

15 failures:

Missing `allowPrivilegeEscalation: false`
* argocd-redis-ha-haproxy
* argocd-redis-ha-server

Missing `drop: ALL`
* argocd-application-controller
* argocd-redis-ha-haproxy
* argocd-redis-ha-server
* argocd-repo-server
* argocd-server

Missing `seccompProfile type: RuntimeDefault`
* argocd-application-controller
* argocd-applicationset-controller
* argocd-dex-server
* argocd-notifications-controller
* argocd-redis-ha-haproxy
* argocd-redis-ha-server
* argocd-repo-server
* argocd-server

**Version**

argocd master commit hash [2b53716](https://github.com/argoproj/argo-cd/commit/2b5371681f611ca05c1884000bd236a38e02f167)

### PR DESCRIPTION
**Pull request by joebowbeer**
Fixes #9743 

This PR addresses most of the issues with PSS/restricted compliance. Specifically, the following kustomize folders are fixed:
* `manifests/cluster-install`
* `manifests/cluster-rbac`
* `manifests/core-install`
* `manifests/namespace-install`

It does not modify the securityContext for the haproxy containers. I'll leave this for a subsequent PR. As a result, the following kustomize folders still have 6 failures each:
* `manifests/ha/cluster-install`
* `manifests/ha/namespace-install`

The 6 failures are because 3 properties are missing from the `securityContext` in each of the 2 deployments: `argocd-redis-ha-haproxy` and `argocd-redis-ha-server`

```yaml
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  seccompProfile:
    type: RuntimeDefault
```

The following command verifies the fix for `manifests/namespace-install`:

```bash
kustomize build https://github.com/kyverno/policies.git/pod-security | \
  kyverno apply --policy-report -r \
  <(kustomize build https://github.com/joebowbeer/argo-cd//manifests/namespace-install\?ref=pss) \
  -
```

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@joebowbeer good catch on the casing issue! Do you happen to know if the feature is case-sensitive? 

I'm curious on the seccompProfile change. If I'm reading [this](https://kubernetes.io/docs/tutorials/security/seccomp/#create-pod-that-uses-the-container-runtime-default-seccomp-profile) correctly, the making `RuntimeDefault` explicit should have no effect:

> Note: If you have the SeccompDefault [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) enabled, then Pods use the RuntimeDefault seccomp profile whenever no other seccomp profile is specified. Otherwise, the default is Unconfined.

Is the idea just to be explicit so it's even more clear if someone tries to change to a less secure default?

**Comment by joebowbeer** [comment]
> @joebowbeer good catch on the casing issue! Do you happen to know if the feature is case-sensitive?

Yes, this feature is case-sensitive. The [docs](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) clearly states `ALL` and the [implementation](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/pod-security-admission/policy/check_capabilities_restricted.go#L30
) in PSA checks for `ALL` - not to mention that [kyverno](https://kyverno.io/policies/pod-security/restricted/disallow-capabilities-strict/disallow-capabilities-strict/) and other tests will fail unless it is `ALL`.

> I'm curious on the seccompProfile change. If I'm reading [this](https://kubernetes.io/docs/tutorials/security/seccomp/#create-pod-that-uses-the-container-runtime-default-seccomp-profile) correctly, the making `RuntimeDefault` explicit should have no effect:
> 
> > Note: If you have the SeccompDefault [feature gate](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) enabled, then Pods use the RuntimeDefault seccomp profile whenever no other seccomp profile is specified. Otherwise, the default is Unconfined.
> 
> Is the idea just to be explicit so it's even more clear if someone tries to change to a less secure default?

The requirement for an explicit type is also part of the [restricted standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted):

> Seccomp profile must be explicitly set to one of the allowed values. Both the Unconfined profile and the absence of a profile are prohibited.

Note that this is for Kubernetes v1.19 or later, but that's not an issue, right? AFAICT, ArgoCD supports two previous versions, so its minimum version is currently 1.21.

By the way, here is the corresponding kyverno policy:

https://kyverno.io/policies/pod-security/restricted/restrict-seccomp-strict/restrict-seccomp-strict/

**Comment by crenshaw-dev** [comment]
@joebowbeer thanks for the thorough response! All makes sense. On the k8s version question, I'm actually not sure. @alexmt I didn't see anything in the docs about supported k8s versions. Am I missing it?

**Review by crenshaw-dev — APPROVED** [review]
Approving, waiting for Alex's comments on k8s version support. Thanks again @joebowbeer!

**Pull request merged**
