### PR TITLE
feat: Merge image updater into core Argo CD 

### PR DESCRIPTION
**Pull request by jaideepr97**
Fixes https://github.com/argoproj/argo-cd/issues/7385

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by Jojoooo1** [comment]
Are we aiming for argo 2.9 ?

**Comment by crenshaw-dev** [comment]
This is still in the [proposal](https://github.com/argoproj/argo-cd/pull/11787) stage, I can't imagine it will be in 2.9.

We want to put a lot of careful thought into how we merge this upstream, because we want it to be truly first-class. Other efforts are currently taking priority.

**Comment by ishitasequeira** [comment]
Closing this one as we decided to move in a different path and not merging image updater in Argo CD

**Comment by bakito** [comment]
> Closing this one as we decided to move in a different path and not merging image updater in Argo CD

@ishitasequeira What is this new path?

**Comment by BennyC** [comment]
> Closing this one as we decided to move in a different path and not merging image updater in Argo CD

@ishitasequeira Do we have an update on this? Is Image Updater remaining outside of ArgoCD?

**Pull request closed without merging**
