### PR TITLE
docs: mention that the argocd diff command does not include secrets

### PR DESCRIPTION
**Pull request by ario0**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

---

This is a minor addition to the existing doc, that would have saved our team some time knowing that "this behavior is intended by default".

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Thanks, @ario0! Could you edit the string [here](https://github.com/argoproj/argo-cd/blob/f8f9ae9accd413b417be1d188418f2b3b7c25e63/cmd/argocd/commands/app.go#L1036) and then run `make clidocsgen`? That'll bring the CLI code in line with the docs.

**Comment by ario0** [comment]
We should be fine now. Note : this will be outdated once https://github.com/argoproj/argo-cd/pull/16483 is merged.

**Review by todaywasawesome — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Comment by ario0** [comment]
@crenshaw-dev, I think the change request is blocking the merge of this PR ?

**Comment by alexis-renard** [comment]
> @crenshaw-dev, I think the change request is blocking the merge of this PR ?

Up :)

@todaywasawesome @pasha-codefresh @ishitasequeira, if you have an idea on how to finally merge this one

**Comment by jannfis** [comment]
I know @crenshaw-dev  is pretty busy with Kubecon this week and the previous weeks, so I was taking the freedom to override his request for change block, because it has been addressed.

**Pull request merged**
