### PR TITLE
docs: Add CSI secret driver to the secret management options

### PR DESCRIPTION
**Pull request by duncan485**
When investigating secret management options I found that CSI secret store is not in this list. It's something I've been using for a while and it definately has its use cases. 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]

**Comment by jacksgt** [comment]
@duncan485 Could you elaborate how exactly you are using the CSI secret driver for secrets management in ArgoCD?

**Comment by duncan485** [comment]
@jacksgt Hi Jack, 

Just like externalsecrets  and others, you create a reference to an external store which is safe to store in Git.

In short, you create a SecretProviderClass, the SecretProviderClass can be used to sync the secret value to a volume. Also see the following walkthrough: 

https://azure.github.io/secrets-store-csi-driver-provider-azure/docs/demos/standard-walkthrough/#5-deploy-secretproviderclass

**Comment by jacksgt** [comment]
@duncan485 Thanks for your response. I am aware that "ExternalSecrets" can be mounted as volumes.
But where / how are you mounting those volumes? Into the `argocd-repo-server` pod (such that ArgoCD has access to the secrets) or directly into each application deployment?

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.4.

**Pull request merged**
