### PR TITLE
feat: A way to display the diff of resource hooks

### LINKED ISSUE #5979: A way to display diff of resource hooks
# Summary
Resource hooks are currently excluded when running `argocd app diff` but it should have an option to include resource hook.

# Motivation
We want to know the difference of resource hook manifests before sync by CLI.

# Proposal
Add an option which enables to include resource hooks to `argocd app diff` command (NewApplicationDiffCommand in https://github.com/argoproj/argo-cd/blob/master/cmd/argocd/commands/app.go).

### PR DESCRIPTION
**Pull request by TomeHirata**
PR for add an option to display resource hooks in the cli command `argocd app diff`.
Because there are few case to compare target resource hooks and live state, include-resource-hook option is limited when comparing to a local manifests or particular revision.
closes https://github.com/argoproj/argo-cd/issues/5979 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by 13013SwagR** [comment]
Will this be merged at some point ?

**Comment by chetan-rns** [comment]
@TomeHirata Could you please resolve the conflicts?

**Comment by toyamagu-2021** [comment]
@chetan-rns 

Hi, I'm very interested in this feature.
Can I take over this?

**Comment by TomeHirata** [comment]
@chetan-rns Sorry for the late reply, I just realized this comment. Would you still like me to fix the merge conflict?
I looked at @toyamagu-2021 's PR and it looks comprehensive.

**Comment by todaywasawesome** [comment]
Closing this in favor of #15971

**Pull request closed without merging**
