### PR TITLE
Update to kustomize 3.8.1

### PR DESCRIPTION
**Pull request by james-callahan**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
@alexmt do you see any issues bumping this up before v1.7. It is an 11th hour change and it is with kustomize which is known to cause issues.

**Comment by james-callahan** [comment]
I'm asking for the bump before 1.7 as we're having issues with kustomize 3.6.1 putting initContainers out of order: a bug that is fixed in 3.8.1.

**Comment by jannfis** [comment]
I think this would be a risky change to sneak into 1.7, given the recent backwards incompatibilities and bugs that happened with Kustomize updates. 

However, we have mechanisms in place to override the Kustomize version to use: https://argoproj.github.io/argo-cd/user-guide/kustomize/#custom-kustomize-versions

We could think about shipping both version of Kustomize in the images, and having 3.6.1 the default version to use. However, this would increase the size of our already very bloated image by another 40MB or so.

**Review by jessesuen — APPROVED** [review]

**Comment by james-callahan** [comment]
heh; merged just as I was about to update the PR to 3.8.2

**Pull request merged**
