### PR TITLE
feat: autocompletion for resource shortnames

### LINKED ISSUE #7214: Filters should favor matching on short names
# Summary

What change you think needs making.

# Motivation

Entering `sts`, or `pvc` or `cr` or `crd` should filter/highlight matching short names

# Proposal

1. Visit https://cd.apps.argoproj.io/applications/argo-cd?resource=
2. In kinds, enter `svc` or `crd` or `rs` or `cm` or `rb` or `sts`
3. Expect to see first and foremost in the list the item whose shortname corresponds to the entered short form.

# Current behavior

image

```
{
    "Version": "v2.2.0+3df6be7",
    "BuildDate": "2021-09-14T05:19:41Z",
    "GitCommit": "3df6be73e79a2cab8a04bf659e1d7e432aa2b60c",
    "GitTreeState": "clean",
    "GoVersion": "go1.16.5",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v4.2.0 2021-06-30T22:49:26Z",
    "HelmVersion": "v3.6.0+g7f2df64",
    "KubectlVersion": "v0.21.0",
    "JsonnetVersion": "v0.17.0"
}
```

### PR DESCRIPTION
**Pull request by saumeya**
closes #7214 , this PR is dependent on merging of argo-ui PR [PR-160](https://github.com/argoproj/argo-ui/pull/160/) to add abbreviation prop to autocomplete
STEPS TO RUN (these steps are not needed anymore! )
1. checkout to this branch in argo-ui - https://github.com/saumeya/argo-ui/tree/autocomplete-abbreviations
2. Install yalc for linking - `npm i -g yalc`
3. Run `cd argo-ui` , `yalc publish` this will create the link to the updates argo-ui dependency
4.  To update the npm dependency to local argo-ui link in argo-cd `cd argo-cd/ui` , `yalc add argo-ui` 
4. Now compile and run `cd argo-cd` , `make start`
filter-resource

Signed-off-by: saumeya <saumeyakatyal@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]
LGTM, thank you!

**Review by reginaelyse — APPROVED** [review]
Gotchya, okay LGTM then!

**Review by alexmt — CHANGES_REQUESTED** [review]

**Comment by saumeya** [comment]
Dependent on merging of https://github.com/argoproj/argo-ui/pull/163

**Review by alexmt — APPROVED** [review]
LGTM

**Pull request merged**
