### PR TITLE
increase liveness timeout

### PR DESCRIPTION
**Pull request by cleverhu**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Hey @cleverhu - if you want to change something in the installation manifests, you have to edit the kustomize sources (e.g. here: https://github.com/argoproj/argo-cd/blob/194414157ebc5cab7b884d341201b1c50ff22492/manifests/base/repo-server/argocd-repo-server-deployment.yaml#L149), then run `make manifests` and commit all changes to your PR.

**Comment by cleverhu** [comment]
> Hey @cleverhu - if you want to change something in the installation manifests, you have to edit the kustomize sources (e.g. here:
> 
> https://github.com/argoproj/argo-cd/blob/194414157ebc5cab7b884d341201b1c50ff22492/manifests/base/repo-server/argocd-repo-server-deployment.yaml#L149
> 
> ), then run `make manifests` and commit all changes to your PR.

ok,thanks

**Comment by crenshaw-dev** [comment]
@cleverhu can you explain the importance of this change and why it should be made upstream instead of applied for individual deployments?

**Comment by cleverhu** [comment]
> can you explain the importance of this change and why it should be made upstream instead of applied for individual deployments?

In my practical use, I have encountered the problem that single-copy server often restarts. If I remove liveness, it will not restart again. Therefore, the default timeout of 1 second is not very reasonable. borrowed from the company's internal projects and the practices of some open source communities, so it should be reasonable to set a longer timeout to prevent the container from restarting.

**Review by crenshaw-dev — APPROVED** [review]
I think this is reasonable. Thanks @cleverhu!

**Pull request merged**
