### PR TITLE
Set cookie policy to SameSite=lax and httpOnly (partial mitigation for #2496)

### PR DESCRIPTION
**Pull request by jannfis**
Checklist:

* [x] ~~I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and I feel I've gotten a green light from the community.~~ This fixes a bug
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

This PR sets the attributes `SameSite=lax` and `httpOnly` for the authentication cookie used by the web UI. It **partially** mitigates the CSRF vulnerability reported in #2496. It will work with most more or less up-to-date browsers in the wild, but not with all (IE 10 and IE11 on some platforms, most notably).

I chose `lax` as `SameSite` policy so that links to ArgoCD (i.e. from a company internal documentation or bookmark page) will still work when the user accidentally closed the tab without logging out, and opening ArgoCD via `href` link. I tested basic reproduction steps as mentioned in #2496 and found the solution protects against this scenario (although giving 401 response, not 403, which I consider fine and appropriate).

Cross-site requests using `GET`, `HEAD`, `TRACE` and `OPTIONS` methods will also still work, but since we obey REST principles everywhere (no data manipulation using those methods), this should be "fine".

Also as mentioned in discussion in #2496, this is no complete CSRF protection but only a "quick win" that we should also keep when thinking about things like CSRF tokens for all data manipulating HTTP methods.

### CODE REVIEW

**Comment by jannfis** [comment]
GolangCI step fails with error message:
```bash
$ GOLANGCI_COM_RUN=1 golangci-lint run --out-format=json --issues-exit-code=0 --timeout=5m --new=false --new-from-rev= --new-from-patch=../changes.patch
    Can't get config for command line: can't parse args: unknown flag: --timeout
```

**Comment by jannfis** [comment]
It seems GolangCI changed the option `--deadline` for `--timeout` when calling `golangci-lint`, but didn't consider that the rather old version we use (and request via configuration) does not support `--timeout` option. 

Wait for them to fix (hopefully), or update our version request of `golangci-lint` to something more recent?

**Comment by jannfis** [comment]
Well, whatever we do, I have opened an issue with them: https://github.com/golangci/golangci/issues/48

**Comment by jannfis** [comment]
They fixed support for old versions, so this build turned green automatically.

**Review by alexmt — APPROVED** [review]

**Comment by alexmt** [comment]
Thank you @jannfis . Cherry-picking it into 1.3

**Pull request merged**
