### PR TITLE
fix(#12862): Update FlinkDeployment health check to support Flink v1.x

### LINKED ISSUE #12862: FlinkDeployment stuck in Progressing state
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

When a `FlinkDeployment` resource is in a healthy, running state, it still shows as "Progressing" in the ArgoCD UI. This causes the application health to also be in a "Progressing" state.

This bug is caused by the custom health check for FlinkDeployment resources, committed in PR #9300. The health check is looking for a field that is not present in the `FlinkDeployment` [CRD](https://github.com/apache/flink-kubernetes-operator/blob/main/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml#L9141-L9156). For more information on this, see **Findings** below.

**To Reproduce**

1. Commit a `FlinkDeployment` to a source-controlled application monitored by ArgoCD
2. Refresh the application in ArgoCD UI
3. `FlinkDeployment` eventually becomes healthy, but status still shows "Progressing" and health details show "Waiting for Flink operator"

**Expected behavior**

`FlinkDeployment` and parent application should both be in a Healthy state.

**Screenshots**

image

**Version**

Couldn't log into the CLI, so here's the version info from the UI.
```shell
{
    "Version": "v2.6.1+3f143c9",
    "BuildDate": "2023-02-08T18:51:05Z",
    "GitCommit": "3f143c9307f99a61bf7049a2b1c7194699a7c21b",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.10",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.3+g835b733",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.19.1"
}
```

**Findings**

My teammates were able to work around this for our use case by adding the below custom health check to our `argocd-cm` configmap.
Possible values for lifecycleState were taken from the [FlinkDeployment CRD](https://github.com/apache/flink-kubernetes-operator/blob/release-1.4.0/helm/flink-kubernetes-operator/crds/flinkdeployments.flink.apache.org-v1.yml#L9247-L9257).
Possible values for jobStatus.state were taken from the [JobStatus enum in Flink's API](https://github.com/apache/flink/blob/master/flink-core/src/main/java/org/apache/flink/api/common/JobStatus.java)
```
    resource.customizations: |
      flink.apache.org/FlinkDeployment:
        health.lua: |
          hs = {}

          if obj.status == nil or obj.status.jobStatus == nil then
            hs.status = "Progressing"
            hs.message = "Waiting for Flink operator"

            return hs
          end

          if obj.status.lifecycleState == "STABLE" 
            and obj.status.jobStatus.state == "RUNNING"
          then
            hs.status = "Healthy"
            hs.message = "Flink deployment is running"
            return hs
          end

          if obj.status.lifecycleState == "SUSPENDED" 
            and obj.status.jobStatus.state == "FINISHED"
          then
            hs.status = "Suspended"
            hs.message = "Flink deployment has been suspended or all jobs have finished running"
            return hs
          end

          if obj.status.lifecycleState == "FAILED" then
            hs.status = "Degraded"
            hs.message = obj.status.error
            return hs
          end

          hs.status = "Progressing"
          -- This will display the same status information as a `kubectl get --watch` command
          hs.message = "Waiting for deployment's lifecycleState/jobStatus.state to be STABLE/RUNNING; currently in " .. obj.status.lifecycleState .. "/" .. obj.status.jobStatus.state .. " state"

          return hs
```

Since I am not a Flink expert, I'm hoping that someone more familiar with Flink can verify whether this approach would work in the general case.

### PR DESCRIPTION
**Pull request by dylanslavin**
Fix health check for FlinkDeployment resources so that it will work for v1.x versions of the Flink Kubernetes Operator.

Fixes #12862

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by rbreeze — APPROVED** [review]
LGTM

**Comment by marcemv90** [comment]
Hi @rbreeze,

Is it planned to cut a release including this change soon? As the PR has been merged a month ago, but none of the recent 2.8.3 nor 2.8.4 releases include this fix.

Just mentioning in case it's been accidentally forgotten.

Regards!

**Comment by crenshaw-dev** [comment]
Thanks for the reminder, @marcemv90! :-)

**Pull request merged**
