### PR TITLE
chore: adding tests for apiclient package: clientset tests

### PR DESCRIPTION
**Pull request by zhaque44**
`TestNewRepoServerClient_CorrectClientReturned:`

This test verifies that when `NewRepoServerClient` is called on using the existing mocked clientset, ensuring that the client returned matches the mock implementation of the RepoServerServiceClient.

`TestNewRepoServerClientset_InvalidInput:`

Tests the function when provided with invalid inputs.

`TestNewConnection_TLSWithStrictValidationAndCertificates:`

verifies that the `NewConnection` function successfully creates a TLS connection with strict certificate validation and no provided certificates. It checks that the function returns a non-error result and a non-nil connection object.

`TestNewConnection_InsecureConnection:`

Testing the `NewConnection` function successfully creates an insecure connection when TLS is explicitly disabled in the TLS configuration. It asserts that the function returns a non-error result and a non-nil connection object, representing the expected behavior for an insecure connection.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by jannfis** [comment]
Codecov says:

> Patch and project coverage have no change.

So it seems this might already be tested elsewhere?

**Comment by zhaque44** [comment]
https://app.codecov.io/gh/argoproj/argo-cd/pull/15193/indirect-changes

**Review by jannfis — APPROVED** [review]
LGTM, thanks @zhaque44 !

**Comment by zhaque44** [comment]
> LGTM, thanks @zhaque44 !

appreciate it!

**Pull request merged**
