### PR TITLE
chore(deps): bump Helm to 3.14.0 (#17031)

### LINKED ISSUE #17031: Speed-up helm templating when lots of tpl are used
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**
See https://github.com/helm/helm/issues/8002 fixed in helm 3.14.0 via https://github.com/helm/helm/pull/11351
Previous to 3.14.0 `helm template` time is quadratic regarding number of `tpl` used in helm templates. This is especially impacting umbrella charts having lots of sub-charts, each one using some `tpl`.
Due to this, Refresh in argo-cd is lasting minutes instead of seconds.

**To Reproduce**
Create an helm chart with hundreds of tpl
Create the app in argo-cd
Refresh

**Expected behavior**
Refresh to last seconds

**Screenshots**
n/a

**Version**

```shell

```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by simonhege**
This PR will bump helm version to 3.14.0
Fixes https://github.com/argoproj/argo-cd/issues/17031

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by blakepettersson — APPROVED** [review]
LGTM, thanks!

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Sounds like an awesome fix. Let's try to get this into 2.10.

Would you mind adding a small note here just saying that the Helm version was bumped? 
https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.9-2.10.md

A Kustomize example for inspiration: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/upgrading/2.8-2.9.md

**Review by todaywasawesome — APPROVED** [review]
I don't see any breaking changes in the Helm release notes, looks good!

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
