### PR TITLE
feat: Go template with sprig for application template render in applicationset

### PR DESCRIPTION
**Pull request by rishabh625**
Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

This is the PR moved from argoproj/applicationset 

https://github.com/argoproj/applicationset/pull/513

Thanks to @vavdoshka for all the efforts and @crenshaw-dev for pushing it this close

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@rishabh625 can you write some usage docs? Having a bit of trouble following the code, and I think that'll help.

**Comment by mrmm** [comment]
@iamnoah Is this PR still worked on ?

**Comment by mrmm** [comment]
@crenshaw-dev I would be happy to try to push something but it might be sloppy attempt. As I have a limited experience with Golang.

Would that be good for you ?

**Comment by crenshaw-dev** [comment]
@mrmm I'd be happy to review and help with any local dev setup issues!  :-)

**Comment by crenshaw-dev** [comment]
Closing for now, until someone has time to pick it back up.  :-)

**Comment by mrmm** [comment]
Hello @crenshaw-dev, I hope you are doing great !

I've started working on this (in my fork) but I am really struggling on how to test this following the same way in (applicationset/utils/utils_test.go).

Do you have any recommendations please ?

**Pull request closed without merging**
