### PR TITLE
feat: add proxy to kustomize build operations

### LINKED ISSUE #18487: Add proxy support to kustomize build operations
# Summary

Inherit the proxy settings from repo-creds into the kustomize build function(s) so that not only pulling the repo is done via proxy but also builing of the kustomize code (since kustomize might pull other git resources via proxy).

# Motivation

We @swisspost are using GH in combination with a cluster behind a corporate proxy. To reach GH from Argo CD we have created a repo-cred matching our GH org, specifying the proxy to use in the repo-cred. If developers specify git repositories in their kustomize `resources`, kustomize won't be able to pull these, since the specified proxy is only used when pulling the initial repo containing the kustomize code but not to build kustomize afterwards.

# Workaround

Of course we can add the proxy using `HTTP_PROXY`/`HTTPS_PROXY` to the repo-server, but then it would be available to all applications unconditionally and we consider this to be too risky. 

# Proposal

First-class proxy support was added in #6286, passing the proxy from the repo-creds struct down to helm commands. A similar approach could be added to kustomize as well (might require refactoring the kustomize code a bit since there's no central wrapper for cmd.Exec that could be used to inject this).

In case the enhancement gets accepted @swisspost is willing to contribute this feature.

### PR DESCRIPTION
**Pull request by the-technat**
This PR adds the proxy variables from the repository struct to all kustomize build commands.

Closes #18487 

I tested a custom built image inside Swiss Post's EKS environment (dev stage) and we clearly see that it's working.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by the-technat** [comment]
Two points to discuss might be:
- now that we pass the `fromRepo` + `proxy` from the `v1alpha1.Repository` struct to the `NewKustomizeApp` constructor, we might as well just pass the entire struct in (or is there any information stored in there we don't want the kustomize package to have access to?)
- `proxy.UpsertEnv` is called in a number of places and it's easy to forget to add this to another new kustomize feature. To avoid this, a wrapper similar to [this one](https://github.com/argoproj/argo-cd/blob/master/util/helm/cmd.go#L54) might be a good thing to refactor

I've intentionally not done both of these points to keep the diff as small as possible, but let me know if I should do it.

**Review by LinoSteffen — APPROVED** [review]

**Review by mkilchhofer — APPROVED** [review]
🚀 same as on #18526, @the-technat gave me a demo of this PR inside a Swiss Post env. Worked perfectly.👌

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
I'd suggest adding a note to the 2.13 upgrade notes.

Also provided one more suggestion on Slack (easier to have conversations there): https://cloud-native.slack.com/archives/C020XM04CUW/p1719002071151439?thread_ts=1718955886.898839&cid=C020XM04CUW

**Review by blakepettersson — APPROVED** [review]
LGTM

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
