### PR TITLE
fix(ui): Stop using the deprecated url format for gitlab instances

### PR DESCRIPTION
**Pull request by tete17**
The legacy URLs format has been deprecated since february 2023 and now gitlab is make these urls invalid.

Ref: https://docs.gitlab.com/ee/update/deprecations.html#legacy-urls-replaced-or-removed

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @tete17!

**Comment by tete17** [comment]
Hey @crenshaw-dev thanks for the review.

Do you want me to fix the merge conflicts on the 2.5 & 2.6 branhces?

**Comment by crenshaw-dev** [comment]
That would be great, thanks! You can just open PRs against those branches directly.

**Comment by tete17** [comment]
Not entirely sure what is the workflow here.

I will cherry pick the commit on local branch on my repo and propose 2 MR against the different release branches. Let me know if I should do it differently.

2.5: https://github.com/argoproj/argo-cd/pull/13797
2.6: https://github.com/argoproj/argo-cd/pull/13796

**Pull request merged**
