### PR TITLE
fix: ensure certificate gets updated on reload

### LINKED ISSUE #10707: argocd-server services randomly new / old / expired cerificate from secret argocd-server-tls
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.

**Describe the bug**

Since version 2.4.3 I noticed argocd-server is sometimes serving older / expired certs that should not be served any more. We first noticed this after the upgrade from 2.2.5 to 2.4.11. The problem exists in 2.4.12 too.

**To Reproduce**
Use this https://github.com/vx-github/vx-argocd-cert-bug to easily reproduce the issue locally in a kind cluster.

**Expected behavior**

Expected behavior would be that argcd-server only serves / uses the cert in `argocd-server-tls` secret if it exists and doesn't serves / uses certs it was not supposed to (old / expired ones).

### PR DESCRIPTION
**Pull request by blakepettersson**
Fixes #10707. `GetCertificate` ensures that the most current version of
 `a.settings.Certificate` is used. It's still a bit of a mystery to me
 as to why the reloading of the server does not work for this, since it
 should fulfill the same function.

I'm not sure of the best way to test that this works the way as intended,
but I tested this locally with the test suite given in #10707 and this works
fine.

Signed-off-by: Blake Pettersson <blake.pettersson@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
I think this is the change that broke it: https://github.com/argoproj/argo-cd/commit/9d4c940a5afb19a08af1e4ab315fb32c13a6297a

I don’t completely understand what causes us to move through the loop. But prior to that change, we’d initialize ArgoCDServer on each iteration. Now we initialize it outside that loop. The certificates are set in NewServer and then never updated.

**Comment by blakepettersson** [comment]
> I don’t completely understand what causes us to move through the loop. But prior to that change, we’d initialize ArgoCDServer on each iteration. Now we initialize it outside that loop. The certificates are set in NewServer and then never updated.

I haven't had time to look into this in depth but this probably means that the webhook reloading doesn't work either. I modified `watchSettings` to not to break out of the loop on cert changes, but `watchSettings` itself probably needs an overhaul. IMO this could be handled in another PR though.

**Review by drpaneas — APPROVED** [review]
/lgtm

I've tested this locally and indeed it fixes the regression. I've used the testsuite from @vx-github :

Step 1: Get the current certificate

```
2023-03-02 11:17:13
subject= /C=NL/O=Argo CD Cert Test number 1/CN=localhost
notBefore=Mar  2 10:16:12 2023 GMT
notAfter=Mar 12 10:16:12 2023 GMT
serial=ECD5483932CD2E8C <--- old
```

Step 2: Update the certificate `secret/argocd-server-tls`

```
2023-03-02 11:17:14
subject= /C=NL/O=Argo CD Cert Test number 2/CN=localhost
notBefore=Mar  2 10:17:14 2023 GMT
notAfter=Mar 12 10:17:14 2023 GMT
serial=B850266BA30BFB68

secret/argocd-server-tls configured
````

Check if the certificate has indeed changed

```
2023-03-02 11:17:14
subject= /C=NL/O=Argo CD Cert Test number 2/CN=localhost
notBefore=Mar  2 10:17:14 2023 GMT
notAfter=Mar 12 10:17:14 2023 GMT
serial=B850266BA30BFB68 <--- new
```

Notice the change now it so fast it happens even within the same second.

This is also visible from the logs:

```
[argocd-server] time="2023-03-02T10:17:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
[argocd-server] time="2023-03-02T10:17:14Z" level=info msg="Notifying 1 settings subscribers: [0xc00135a960]"
[argocd-server] time="2023-03-02T10:17:14Z" level=info msg="tls certificate modified. reloading certificate"
[dex] time="2023-03-02T10:17:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
[dex] time="2023-03-02T10:17:14Z" level=info msg="Notifying 1 settings subscribers: [0xc0001866c0]"
[dex] time="2023-03-02T10:17:14Z" level=info msg="dex config unmodified"
[argocd-applicationset-controller] time="2023-03-02T10:17:14Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls"
[argocd-application-controller] time="2023-03-02T10:17:19Z" level=info msg="Loading TLS configuration from secret argocd/argocd-server-tls
```

In the previous version, the `tlsConfig` variable was set with a single certificate using Certificates field.

However, in this PR's updated version, the `TlsConfig.GetCertificate` method is set instead, which returns the certificate from the `a.settings.Certificate` variable that contains the latest version of certificates. This hook dynamically reloads the certificate as needed, without restarting the server, which could be more efficient and less disruptive to ongoing operations.

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
