### PR TITLE
chore(go-jsonnet): update go-jsonnet to a newer version

### PR DESCRIPTION
**Pull request by BondAnthony**
This updates go-jsonnet to a newer version that address some bugs within the templating language. Specifically this issue https://github.com/google/go-jsonnet/pull/248

Checklist:

* [x] This is a bug fix
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by alexec — CHANGES_REQUESTED** [review]
Thank you @BondAnthony - do you think you could please sign the CLA so I can approve and merge?

**Comment by BondAnthony** [comment]
@alexec, I'm working through the CLA process right now. I'll ping once I have this approved. Thank you

**Comment by alexec** [comment]
Ok. Please re-request review once signed.

**Comment by alexmt** [comment]
jsonnet dependency has been upgraded

**Pull request closed without merging**
