### PR TITLE
fix(ui): pod count tooltip fix (#15767)

### LINKED ISSUE #15767: Pod count tooltip appearing above details flyout
**Describe the bug**

In a big app where the pods get collapsed by default, the details pod collapse tooltip appears above any details flyout I click.

**To Reproduce**

Navigate to an app with a lot of pods and then click any resource to view the details.

**Expected behavior**

I'd expect the flyout to appear above the tooltip.

**Screenshots**

image

**Version**

2.8.2

### PR DESCRIPTION
**Pull request by smriti0710**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Issue: https://github.com/argoproj/argo-cd/issues/15767
Fixes #15767

https://github.com/argoproj/argo-cd/assets/29578254/f0819b94-e77c-45da-b2b4-417cc3994c3c

### CODE REVIEW

**Comment by smriti0710** [comment]
@crenshaw-dev please review. Thanks !!

**Comment by crenshaw-dev** [comment]
Looks great! Can you resolve the [DCO check failure](https://github.com/argoproj/argo-cd/pull/15928/checks?check_run_id=17650252945)?

**Comment by smriti0710** [comment]
> Looks great! Can you resolve the [DCO check failure](https://github.com/argoproj/argo-cd/pull/15928/checks?check_run_id=17650252945)?

Fixed :)

**Comment by smriti0710** [comment]
Tippy doc: https://atomiks.github.io/tippyjs/v5/all-props/

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Thanks so much @smriti0710!

**Pull request merged**
