### PR TITLE
 fix: run  argo-cd repo server as non-root with read-only-root-fs

### PR DESCRIPTION
**Pull request by sbose78**
~Run server, controller, repo-server as non-root~
~Read Only Root File System for server & controller only~
~Mount /home/argocd for plugins' usage~
~Investigating what needs to be done for repo-server, will make a different PR to reduce impact~

Given that the discussion in this PR has been on repo-server, let's make this a repo-server-specific PR.
part of #3648 

---
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by sbose78** [comment]
@mayzhang2000 I wasn't planning on doing this, but thought of proposing this change since I noticed it :)

**Review by jannfis — CHANGES_REQUESTED** [review]
Hey @sbose78 - I think this won't work for the one or other reasons:

* Some clusters (like OpenShift) assign random UIDs from a range in very high numbers to the pods and will conflict with UID 999
* Read-only filesystem will definitely break things without additional `emptyDir` volume mounts on certain paths, for example the `argocd-repo-server` workload will require write permissions to `/tmp` and `/app/config/gpg/keys` at least. Other pods probably need likewise places to write somewhere.

**Comment by jgwest** [comment]
:+1:  to what @jannfis said re: read-only FS, and FWIW the only reason the E2E tests are passing is they _don't_ run on a k8s cluster (and thus aren't running with the new constraints). All E2E tests run Argo CD (and the test themselves) outside k8s where these constraints would not apply (and this is part of the work that Jann is working on re: adding ability to test Argo CD running on a cluster).

**Comment by sbose78** [comment]
Yea, OpenShift complains about the user id and moves on with it's own uid in the range for the namespace - as per my experiment last evening. I'll remove it nevertheless. 


> All E2E tests run Argo CD (and the test themselves) outside k8s 

>  workload will require write permissions to /tmp and /app/config/gpg/keys at least. 

Ah yes, I was so hoping stuff would fail, glad that @jannfis  is working on getting tests to run against an openshift cluster.

**Comment by sbose78** [comment]
Ok, `/app/config/gpg/keys` already has `emptyDir{}` 🚶

**Comment by sbose78** [comment]
Also, digging deeper, I can't seem to reason why application controller wouldn't work with a `readOnlyRootFilesystem`.

**Comment by sbose78** [comment]
possibly part of https://github.com/argoproj/argoproj/issues/40

**Review by alexmt — APPROVED** [review]
Looks good to me. @jannfis is it ok to merge it now?

**Review by jannfis — APPROVED** [review]
LGTM

**Pull request merged**
