### PR TITLE
fix: make exec feature opt-in

### LINKED ISSUE #9143: Add RBAC docs for new `exec` resource
# Summary

Add RBAC docs for new `exec` resource, pointing out the specific risks associated with that resource.

# Motivation

https://github.com/argoproj/argo-cd/pull/8905 added support for a new `exec` resource. That resource gives users extra capabilities which have unique security implications. 

# Proposal

The RBAC page should describe the risks posed by granting exec privileges. There should be a description of _equivalence_ to other privileges (e.g. if a Pod is running or can be made to run under a ServiceAccount with privileges beyond what the user would otherwise have, the user effectively has those privileges). Take care to point out the particular risks posed by granting `exec` privileges on project(s)/app(s) which manage Argo CD resources.

### PR DESCRIPTION
**Pull request by crenshaw-dev**
We could make this either opt-in or opt-out, but I think at least having a flag is a good idea.

Fixes #9143

### CODE REVIEW

**Comment by zachaller** [comment]
I personally really like the idea of this being opt-in exec is a very powerful feature that has many security implications I think when we start wrapping k8s permissions with argocd rbac people don't always expect that behavior by default. Say I have a complex security setup within my Kubernets cluster where people are rbac'ed into specific namespaces and or have turned exec off completely but now I have this backdoor exec via ArgoCD that I also have to configure and now lock down in ArgoCD as well as K8s.

**Comment by zachaller** [comment]
Will also want to decide how we handle rbac for argocd-server role it currently dose not have permissions to exec it would need the snippet below to allow it.

```
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
```

I think just documenting the required rbac changes in the same place we document enabling exec would make sense?

**Comment by crenshaw-dev** [comment]
Should we consider switching our RBAC action name to ‘create’ to mimic the Kubernetes RBAC name?

**Comment by zachaller** [comment]
> Should we consider switching our RBAC action name to ‘create’ to mimic the Kubernetes RBAC name?

Yea I think I like matching k8s permissions here as well.

**Review by alexmt — APPROVED** [review]
LGTM. Thank you!

**Pull request merged**
