### PR TITLE
fix: Child apps should not affect parent app's health by default (#3781)

### PR DESCRIPTION
**Pull request by keithchong**
Signed-off-by: Keith Chong <kykchong@redhat.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Fix is for https://github.com/argoproj/argo-cd/issues/3781
For checklist item 3 above, from what I could tell, no UI or CLI changes are necessary.

See screenshots in the issue that show the before and after behaviour.

### CODE REVIEW

**Comment by OmerKahani** [comment]
Would there by a way to change this default? the idea that there is one place to see the state of the whole cluster is something we rely on

**Comment by alexmt** [comment]
I propose to delete the built-in application health check instead of introducing special for child application health.

@OmerKahani, in this case, you can add custom health check using lua script. Given that application CRD health assessment causes confusion for so may Argo CD users , this seems like a good compromise.

What do you think?

**Comment by keithchong** [comment]
@alexmt, I presume you mean to essentially remove that if statement at line 51, because that specifically checks for the Application.  If you remove that, then the App will revert back to missing or unknown, if the children are worse than healthy (missing or unknown).

**Comment by keithchong** [comment]
@alexmt , is this what you had in mind?  Because you don't want any child application's unhealthy state (unknown, missing, and degraded)  to affect the parent, then if _at least one_ child is healthy, then the parent is healthy, like in the screenshot below?  There is also the case where if _all_ child apps have missing states, then it seems acceptable that the parent should have a missing state too.

BestHealthOfAllTheChildApps

**Comment by keithchong** [comment]
Thanks Alex for clarifying what you wanted.  The intended behaviour is that the health status no longer appears on the child apps.

**Comment by keithchong** [comment]
Closing this PR because the fix is in the gitops-engine.  See https://github.com/argoproj/gitops-engine/pull/153

@OmerKahani, please add your comments to issue #3781, regarding @alexmt 's question.

**Comment by keithchong** [comment]
The refactor piece to pull in the newer version of the gitops-engine will be done in a different PR.

**Pull request closed without merging**
