### PR TITLE
fix: support 'project' filter field for backwards-compatibility

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Resolves a breaking change in the API. https://github.com/argoproj/argo-cd/pull/8929#discussion_r1112187288

### CODE REVIEW

**Review by alexef — APPROVED** [review]

**Review by jannfis — APPROVED** [review]
LGTM!

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.6.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.5 for 2.5.15.

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.4 for 2.4.27.

**Pull request merged**
