### PR TITLE
docs: updated the supported version policy in the operator manual installation doc

### PR DESCRIPTION
**Pull request by mooneeb**
The supported version policy mentioned in the operator manual installation document diverges from the official policy that is mentioned in the [security policy](https://github.com/argoproj/argo-cd/security/policy#supported-versions) and the [release cadence](https://argo-cd.readthedocs.io/en/stable/developer-guide/release-process-and-cadence/).

This change brings the version policy in line by referring the readers to the [release process and cadence](https://argo-cd.readthedocs.io/en/stable/developer-guide/release-process-and-cadence/) documentation to check the specified policy.

Related Slack Discussion: https://cloud-native.slack.com/archives/C01TSERG0KZ/p1695295262763389

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by blakepettersson** [comment]
It generally LGTM, but the Release Cadence and Process page says nothing about the supported Kubernetes versions. Perhaps it's worth adding an extra column outlining the Kubernetes versions supported for each Argo version?

**Comment by mooneeb** [comment]
> It generally LGTM, but the Release Cadence and Process page says nothing about the supported Kubernetes versions. Perhaps it's worth adding an extra column outlining the Kubernetes versions supported for each Argo version?

@blakepettersson This is the line I was referring to in the release cadence ([source](https://argo-cd.readthedocs.io/en/stable/developer-guide/release-process-and-cadence/#:~:text=Only%20the%20three%20most%20recent%20minor%20versions%20are%20eligible%20for%20patch%20releases.)) which mentions the support policy. I could change the link to point to: https://argo-cd.readthedocs.io/en/stable/developer-guide/release-process-and-cadence/#patch-releases-eg-25x

Regarding your other point, do you mean this compatibility table: https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions? If so, the community

**Review by christianh814 — APPROVED** [review]
Looks good! Thanks!

**Comment by blakepettersson** [comment]
> Regarding your other point, do you mean this compatibility table: https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#tested-versions?

Yes, I missed that the table was right under 😄

**Review by blakepettersson — APPROVED** [review]

**Pull request merged**
