### PR TITLE
feat: Add Opennkruise Workload Integration with lua Health_Check scripts

### PR DESCRIPTION
**Pull request by maheshkasabe**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Review by ashutosh16 — APPROVED** [review]
LGTM

**Comment by maheshkasabe** [comment]
@crenshaw-dev & @todaywasawesome Can you please approve and merge my changes??

**Review by todaywasawesome — APPROVED** [review]
Looks good, glad to have additional support.

**Comment by maheshkasabe** [comment]
Hello @todaywasawesome can you tell me why is it failing even after passing all the checks intially

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
@maheshkasabe , it looks like the generated code is failing. You would need to regenerate manifests.

**Comment by crenshaw-dev** [comment]
@maheshkasabe looks like the DCO check is failing now

**Comment by maheshkasabe** [comment]
I am closing this pull request since a lot of messed up is happend here! and will open a new pull request!

**Pull request closed without merging**
