### PR TITLE
feat: add labels and annotations to cluster details page (#9704)

### LINKED ISSUE #9704: View/edit cluster secret metadata from the cluster details page in the UI.
# Summary

View/edit cluster secret metadata from the cluster details page in the UI.

# Motivation

To see what labels are set on a cluster secret we have to check the actual Secret object in Kubernetes. This can be a bit cumbersome when Argo is managing many clusters. It also requires access to the cluster that Argo runs in, which prevents developers to view this information themselves (in our case).

Having the cluster secret metadata viewable/editable from the UI would make life easier when it comes to testing/troubleshooting ApplicationSets using cluster generators.

# Proposal

Add labels and annotations to the `General` section of the cluster details page.

### PR DESCRIPTION
**Pull request by msoderberg**
Closes #9704

Signed-off-by: Marcus Söderberg <msoderb@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by saumeya** [comment]
Hi @msoderberg, thanks a lot for the contribution! Could you add a screenshot of the change to the PR

**Review by saumeya — COMMENTED** [review]
LGTM, thanks!

**Review by saumeya — APPROVED** [review]

**Comment by msoderberg** [comment]
Thank you! Here are a couple of screenshots (I reused the style and edit component from the project page):
Cluster general overview
Cluster general edit

**Comment by pavshu** [comment]
@keithchong Could you please review this fairly simple but very useful PR? :pray:

**Review by crenshaw-dev — APPROVED** [review]
Thanks @msoderberg!

**Comment by soostdijck** [comment]
As of argocd 2.5.2 labels are still not visible in the UI, when will this make it further?

**Comment by blakepettersson** [comment]
It's targeted for 2.6.

**Pull request merged**
