### PR TITLE
chore: fix typos in googlechat.md

### PR DESCRIPTION
**Pull request by emirot**
Signed-off-by: emirot <emirot.nolan@gmail.com>

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@emirot please look at the failing CI for `changes to the generated code`.

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla I did, I was hoping you will tell me more about that, the CI fails because of a git change but I need to do that change except if it's generated from somewhere else but don't find any other references in this project.

@emirot did you run the `make codegen` target in your local ? Please run and see if it will address this change

**Comment by emirot** [comment]
> > @iam-veeramalla I did, I was hoping you will tell me more about that, the CI fails because of a git change but I need to do that change except if it's generated from somewhere else but don't find any other references in this project.
> 
> @emirot did you run the `make codegen` target in your local ? Please run and see if it will address this change

Yes I did that and after doing a `git diff` I couldn't see a change, maybe I'm missing something.
Maybe @crenshaw-dev would know, also what about adding https://github.com/client9/misspell to CI to avoid this kind of PR?

**Comment by alexef** [comment]
@emirot please see also this comment: https://github.com/argoproj/argo-cd/pull/11275#issuecomment-1312401495

**Comment by emirot** [comment]
@alexef I did
```
git clean -dfx
export GOPATH=~/go
make install-codegen-tools-local
make install-go-tools-local
make codegen-local```
Then git diff master

```
diff --git a/docs/operator-manual/notifications/services/googlechat.md b/docs/operator-manual/notifications/services/googlechat.md
index 04484691..6d8be56d 100755
--- a/docs/operator-manual/notifications/services/googlechat.md
+++ b/docs/operator-manual/notifications/services/googlechat.md
@@ -51,7 +51,7 @@ You can send [simple text](https://developers.google.com/chat/reference/message-
 
 ```yaml
 template.app-sync-succeeded: |
-  message: The app {{ .app.metadata.name }} has succesfully synced!
+  message: The app {{ .app.metadata.name }} has successfully synced!
 ```
 
 A card message can be defined as follows:
@@ -65,7 +65,7 @@ template.app-sync-succeeded: |
         sections:
           - widgets:
               - textParagraph:
-                  text: The app {{ .app.metadata.name }} has succesfully synced!
+                  text: The app {{ .app.metadata.name }} has successfully synced!
           - widgets:
               - keyValue:
                   topLabel: Repository
```
I still don't see what is generated or why it fails. I'm wondering if any change in that fail will make CI fail.

**Comment by alexef** [comment]
@emirot I'm sorry, I didn't look into the details of the failure, so my comment does not apply.

The notification docs (even though stored in git in this repo) are coming from the notification-engine repo. So fixing the typo should be done there.

For details, please check the Makefile and the `hack/gen-docs/main.go`. Closing this, if you want, please fix the original docs at: https://github.com/argoproj/notifications-engine/blob/master/docs/services/googlechat.md

**Comment by emirot** [comment]
Thanks @alexef, https://github.com/argoproj/notifications-engine/pull/116 not sure it's still maintained though

**Pull request closed without merging**
