### PR TITLE
feat(appset): add support for missingkey=error in ApplicationSets (#13731)

### LINKED ISSUE #13731: Support for missingkey=error in ApplicationSets with goTemplate: true
# Summary

Currently, ArgoCD does not offer any customization of the [options used for Go templating](https://pkg.go.dev/text/template#Template.Option):

https://github.com/argoproj/argo-cd/blob/5e543518dbdb5384fa61c938ce3e045b4c5be325/applicationset/utils/utils.go#L234

It would be nice if it were possible to set a key on the ApplicationSet spec that would customize the `missingkey` option.

# Motivation

We find that it is easy to forget to set a key in the cluster generator, or there is a typo that leads to the wrong key being set. This results in the use of that key in the appset manifest being expanded to null or an empty string, which is usually not what we want. If we could tell ArgoCD to abort on a templating error we would catch issues earlier rather than potentially after they are already deployed.

# Proposal

I would suggest a new key at the top level of the appset spec, next to `goTemplate`, which lists options to be passed to the template engine, in the same format as [the underlying function](https://pkg.go.dev/text/template#Template.Option). This ensures that work is not needed to keep up with new options that are added to Go.

If there are security concerns, we can add an allowlist for the supported options.

The existing behavior would remain the same as the default behavior would be to pass no extra options, which is what happens today.

### PR DESCRIPTION
**Pull request by ghost**
Closes https://github.com/argoproj/argo-cd/issues/13731.

The implementation is pretty straightforward. I just introduce a new optional parameter `goTemplateOptions` which is a list of options for the template engine. They are passed as is. The new parameter is threaded through most places that `goTemplate` is.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] ~Optional. My organization is added to USERS.md.~
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Could you update the git files generators docs to specifically call out this feature? To me, it has the most intuitive use case: I want to make sure my devs are fully populating their `app.yaml` file, and I want the AppSet to fail if they forget to set a field.

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Could you update the git files generators docs to specifically call out this feature? To me, it has the most intuitive use case: I want to make sure my devs are fully populating their `app.yaml` file, and I want the AppSet to fail if they forget to set a field.

**Comment by crenshaw-dev** [comment]
Yep, that's the file!

> do you think it is better to update all the examples to use go templates instead

I do. We'll eventually want to deprecate and then remove fasttemplate support, since that library is no longer maintained.

**Comment by raxod502-plaid** [comment]
Updated! I think I translated all the syntax correctly but let me know if I made any mistakes.

**Comment by crenshaw-dev** [comment]
I tried to rebase, fingers crossed that I didn't break anything. 😬

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
