### PR TITLE
fix: remove deprecated default cipher for golang >=1.22

### LINKED ISSUE #17571: Default cipher values are invalid for newer versions of go.
This is not a bug with a current release, and I'm happy for it to be reclassified as such!

This is simply a proposed (hopefully simple) fix for a future problem that will arise when the project upgrades the version of go used to build.

Checklist:

* [ ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ ] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Default cipher values are invalid for newer versions of go.

**To Reproduce**

Build with newer versions of go.

**Expected behavior**

N/A

**Screenshots**

N/A

**Version**

N/A

**Logs**

```
level=fatal msg="error retrieving TLS cipher suites: invalid cipher suite specified: TLS_RSA_WITH_AES_256_GCM_SHA384"
```

### PR DESCRIPTION
**Pull request by joshrwolf**
Closes https://github.com/argoproj/argo-cd/issues/17571

newer versions of go remove the `TLS_RSA_WITH_AES_256_GCM_SHA384` as an available cipher.

this PR simply removes it in favor of the existing default `TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384`, which remains a valid default option for the existing go toolchain version, and future ones

Checklist:

* [] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by blakepettersson** [comment]
Have you run `make codegen`? Which versions of Go does this apply for BTW?

**Comment by blakepettersson** [comment]
I see, golang/go#63413

**Comment by blakepettersson** [comment]
@joshrwolf I'll mark this PR as a draft until you run `make codegen-local` on your machine and commit those changes.

**Comment by agaudreault** [comment]
FYI, I had go 1.22 installed and running the codegen locally gave me errors with packages downloaded with go 1.22. After installing 1.21, re-downloading all the local toolings in `dist/`, I don't have the error anymore. Not sure if there is a bigger issue on upgrading argo to 1.22, but this might affect you.

See https://github.com/kubernetes-sigs/controller-tools/issues/888


```
+ ./dist/gen-crd-spec
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x100ef4450]
```
Ref: https://github.com/kubernetes-sigs/controller-tools/issues/888

**Comment by alexmt** [comment]
I took the liberty, run codegen and pushed changes to the branch (`make clidocsgen` to regenerate docs only)

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by ashinsabu3** [comment]
Is this there in any released versions yet? @alexmt

**Comment by blakepettersson** [comment]
This is slated for 2.12.

**Pull request merged**
