### PR TITLE
docs: use period instead of parenthesis (#12042)

### LINKED ISSUE #12042: Fix markdown for numbered lists
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [ ] I've pasted the output of `argocd version`.

**Describe the bug**

Markdown in 
https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#debugging-a-cmp leads to hard to read prose.

**To Reproduce**

Visit https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/#debugging-a-cmp

The code (on the `release-2.5` branch is using `1)` instead of `1.`:
https://github.com/argoproj/argo-cd/blob/4bd9f3618241ac9ad1eb6597c20016123ecfe703/docs/user-guide/config-management-plugins.md?plain=1#L259-L268
**Expected behavior**

Numbered lists should be numbered lists instead of jumbled into a paragraph

**Screenshots**

image

**Version**

```shell
Paste the output from `argocd version` here.
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by drozd-A**
Closes #12042

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Hi @drozd-A, thanks for this PR. Can you please change the target branch to `master` instead? We'll cherry-pick from the default branch to release branches where required.

**Comment by drozd-A** [comment]
@jannfis This file and content aren't present as is on master

**Comment by jannfis** [comment]
Oops. That means they must have been removed (or moved to a different place).

**Comment by jannfis** [comment]
It's been moved to `operator-manual` by a change in https://github.com/argoproj/argo-cd/pull/11888

Can you please open an additional PR against that file in master, so we'll also cherry-pick into 2.6 (the next stable)

**Comment by drozd-A** [comment]
@jannfis The changes in the PR are not present in master
https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/config-management-plugins.md

**Comment by jannfis** [comment]
I see. 

Then this PR seems to be a duplicate of https://github.com/argoproj/argo-cd/pull/11245. It was marked for cherry-picking into 2.5, but probably we forgot to cherry-pick it.

**Comment by drozd-A** [comment]
@jannfis Found some other instances of `)` being used instead of `.`. I've updated the PR accordingly.

**Review by jannfis — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
