### PR TITLE
docs: corrected argocd app set command

### PR DESCRIPTION
**Pull request by rakhbari**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by terrytangyuan — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
@rakhbari could you please fix checks?

**Comment by pasha-codefresh** [comment]
@rakhbari you have messed up something in git, you have a lot of changes

**Comment by rakhbari** [comment]
> @rakhbari you have messed up something in git, you have a lot of changes

@pasha-codefresh I simply followed the instructions on how to fix the DCO signed-off-by issue for my very simple documentation commit. Those instructions said to rebase my local fork of the repo by `git rebase HEAD~3 --signoff` and do a `git push --force-with-lease origin master`, which I did. I'll be happy to close/delete this PR if need be. I don't want to cause any issues/problems for the project. I was simply reading the docs and noticed that typo and wanted to contribute a correction.

**Comment by pasha-codefresh** [comment]
@rakhbari yes please reopen it . Thanks

**Comment by rakhbari** [comment]
Closing PR at the request of the project maintainers. Will re-open a new PR with only the docs correction.

**Pull request closed without merging**
