### PR TITLE
fix(ui): Polish pod logs viewer (#14050)

### LINKED ISSUE #14050: Pod log viewer should not scroll to bottom, if user has scrolled up
I think this is a pre-existing issue but it is quite annoying.

1. Open the pod log viewer.
2. Scroll up to find whatever you care about.
3. Wait for new log line.
4. Viewer scrolls to bottom. Cannot see what you care about.
5. Go to 2

### PR DESCRIPTION
**Pull request by alexec**
Fixes #14050

Improves the following:

**The vertical scroll bar was hidden**. You need is so you know where you are is the log file, confusing without. This is now visible.

Screenshot 2023-06-16 at 2 19 03 PM

**Automatically scrolling was annoying**, because you often scroll up to look at a problem, and it would scroll you to the end 1/2 second later, preventing you looking at the problem. Now, when you scroll up, auto-scroll is disabled. There is a scroll status icon at the bottom which uses `fa-beats` so it pulses when auto-scrolling.

image

**Fixed the min-height of the application tree**. This was screwing up the panels.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@alexec I'm focusing on merging features for 2.8, but I'll merge and cherry-pick this after we cut 2.8-rc1.

**Comment by alexec** [comment]
why has this closed itself?

**Comment by alexec** [comment]
wft?

**Comment by alexec** [comment]
re-open

**Comment by alexec** [comment]
re-open!

**Comment by alexec** [comment]
unbelievable, it has lost ALL my changes

**Comment by alexec** [comment]
.

**Comment by alexec** [comment]
I've moved the auth-scroll button to the toolbar and make it consistent with the other icons:

image

image

I'm not sure the best position, so I put it next to the follow button.

I did not add a scroll to top button. I think you can do this by rapidly moving you mouse wheel is most cases.

LMK if you feel strongly.

**Review by rbreeze — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
