### PR TITLE
do not ignore ipv6 in 2k22

### PR DESCRIPTION
**Pull request by borislitv**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by borislitv** [comment]
simple fix to work on ipv6only clusters

**Comment by jannfis** [comment]
Hi @borislitv,

thanks for your PR!

As far as I can tell, all the changes affect the Redis HA installation. We use an [upstream Helm chart ](https://github.com/DandyDeveloper/charts/tree/master/charts/redis-ha) to generate the manifests for Redis HA, so most likely the changes for the health scripts should go there so we can pull them in.

For the changes to the listeners, these can be controlled through config values, i.e. https://github.com/argoproj/argo-cd/blob/master/manifests/ha/base/redis-ha/chart/values.yaml

Then, installation manifests need to be generated and all changes submitted as PR.

**Comment by borislitv** [comment]
I apologize for my carelessness, I looked superficially at the rest of the files. I will fix "bind" variables in this pr. And I'll watch the helm chart of radis-ha.

**Comment by mkilchhofer** [comment]
The upstream helm chart fixed it like this for helm based installations of Argo CD: https://github.com/DandyDeveloper/charts/pull/186/files

**Comment by borislitv** [comment]
great news, they really forgot to correct the ipv4only regex in grep args, I wrote to them about it, probably you can close this pr,  must remember to check the helm chart values in argocd repo.

**Pull request closed without merging**
