### PR TITLE
chore: enforce PR assignee

### PR DESCRIPTION
**Pull request by alexmt**
Signed-off-by: Alexander Matyushentsev <AMatyushentsev@gmail.com>

PR adds adds  augustohp/github-action-pr-assignee action to the CI to enforce PR assignee

### CODE REVIEW

**Comment by jannfis** [comment]
I think `augustohp/github-action-pr-assignee` is quite stale (maybe even abandoned), and it does have a bug in status retrieval (https://github.com/augustohp/action-pr-assignee/pull/7). I was thinking we should either pull this in as local action and fix the bug in-tree, or fork it somewhere and use the fork.

**Comment by alexmt** [comment]
@jannfis , it appears that we can just script the same logic using `gh` CLI. Implemented bash script that fails if PR is approved but has not assignee.

Need your help to test it end to end: Once you approve PR the check should fail with message `PR must be assigned before merging`. Next I can assign myself and script should pass.

**Review by jannfis — APPROVED** [review]
Test approval

**Review by jannfis — DISMISSED** [review]
Test

**Pull request closed without merging**
