### PR TITLE
Update slack.md to render yaml properly

### PR DESCRIPTION
**Pull request by pie-r**
Render properly `yaml` syntax.

In the doc webpage is not rendered correctly: 
https://argo-cd.readthedocs.io/en/release-2.4/operator-manual/notifications/services/slack/

Signed-off-by: Pier <53210578+pie-r@users.noreply.github.com>

### CODE REVIEW

**Review by ashutosh16 — APPROVED** [review]
LGTM
https://argo-cd--10611.org.readthedocs.build/en/10611/operator-manual/notifications/services/slack/

**Comment by pie-r** [comment]
> LGTM https://argo-cd--10611.org.readthedocs.build/en/10611/operator-manual/notifications/services/slack/

Should I do something more?

**Comment by ashutosh16** [comment]
> > LGTM https://argo-cd--10611.org.readthedocs.build/en/10611/operator-manual/notifications/services/slack/
> 
> Should I do something more?

not required, LGTM.  I've added the link for others to view the change in doc format.

**Comment by pie-r** [comment]
Can someone review this simple change?

**Pull request closed without merging**
