### PR TITLE
feat(metric): add ls-remote request fail metric(#17956)

### LINKED ISSUE #17956: [metrics] git ls-remote failure counter
# Summary

Relate to https://github.com/argoproj/argo-cd/issues/15658, be able to monitor if git ls-remote fail, use case: if git branch dont exist any more.

# Motivation

We would like to be able to detect wrong app config, wrong git branch.

# Proposal

As the good job done at https://github.com/argoproj/argo-cd/pull/15657, I propose a new metric `argocd_git_lsremote_fail_total` or a new label `status` for existing metric `argocd_git_request_total`.

### PR DESCRIPTION
**Pull request by Jack-R-lantern**
Added argocd_git_lsremote_fail_total metric.
Increment this metric if a git ls-remote request fails.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Closes #17956

### CODE REVIEW

**Review by csantanapr — COMMENTED** [review]
This is a useful error metric to expose

**Comment by Jack-R-lantern** [comment]
@csantanapr 
Is there anything else I need to implement?

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
Thank you for your contribution

**Comment by ebuildy** [comment]
Wonderful many thanks!

**Pull request merged**
