### PR TITLE
fix(cli): `admin settings rbac can` has inconsistency among project resources

### LINKED ISSUE #17563: CLI: `argocd admin settings rbac can` doesn't report logs permissions correctly
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The ArgoCD CLI reports that users and roles cannot `get logs` despite built-in and explicit custom policies granting access. It doesn't matter if I test a role (e.g. `role:admin`) or a user who's been granted a role (e.g. `admin`).

I saw a note about RBAC enforcement for logs being delayed until ArgoCD 3.0, and I see the `server.rbac.log.enforce.enable` flag in the [sample ArgoCD configmap](https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/), but that flag's description still leads me to believe that `get logs` should always return `Yes` for `role:readonly` and `role:admin` in 2.x unless explicitly denied:

```
  # Application pod logs RBAC enforcement enables control over who can and who can't view application pod logs.
  # When you enable the switch, pod logs will be visible only to admin role by default. Other roles/users will not be able to view them via cli and UI.
  # When you enable the switch, viewing pod logs for other roles/users will require explicit RBAC allow policies (allow get on logs subresource).
  # When you disable the switch (either add it to the configmap with a "false" value or do not add it to the configmap), no actual RBAC enforcement will take place.
  server.rbac.log.enforce.enable: "false"
```

**To Reproduce**

The `argocd admin settings rbac can` command will segfault unless the provided policy file has at least one valid line, so let's create a dummy placeholder. We'll be querying the builtin policies (`--use-builtin-policy` defaults to `true`), not this one:

```
$ echo 'g, readonly-user, role:readonly' > /tmp/rbac-default.csv
```

Given that `get logs` is granted to the `role:readonly` role in the [built-in policy CSV for v2.10.3](https://github.com/argoproj/argo-cd/blob/v2.10.3/assets/builtin-policy.csv), this test should succeed, but fails:

```
$ argocd admin settings rbac can --policy-file /tmp/rbac-default.csv role:readonly get logs
No
```

Likewise, the admin role should definitely have `get logs` access, but this also fails:

```
$ argocd admin settings rbac can --policy-file /tmp/rbac-default.csv role:admin get logs
No
```

At least part of the builtin policy is in effect:

```
$ argocd admin settings rbac can --policy-file /tmp/rbac-default.csv role:admin create applications
Yes
```

This test fails even when I download `builtin-policy.csv` and use it with `--policy-file`, which makes even less sense.

```
$ argocd admin settings rbac can --policy-f
ile <(curl https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.3/assets/builtin-policy.csv 2>/dev/null) role:readonly get logs
No
$ argocd admin settings rbac can --policy-f
ile <(curl https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.3/assets/builtin-policy.csv 2>/dev/null) role:readonly get applications
Yes
```

Or using  a custom policy:

```
$ cat <<EOF
p, role:readonly, applications, get, */*, deny
p, role:readonly, logs, get, */*, allow
p, role:logtest, logs, get, */*, allow
EOF > /tmp/rbac-explicit.csv
$ argocd admin settings rbac can --policy-file /tmp/rbac-explicit.csv role:readonly get applications
No
$ argocd admin settings rbac can --policy-file /tmp/rbac-explicit.csv role:readonly get logs
No
$ argocd admin settings rbac can --policy-file /tmp/rbac-explicit.csv role:logtest get logs
No
```

**Expected behavior**

Testing log permissions with `argocd admin settings rbac can` should reflect the [built-in policy](https://github.com/argoproj/argo-cd/blob/v2.10.3/assets/builtin-policy.csv) and custom policies granting `get logs` permissions.

Expected:

```
$ argocd admin settings rbac can --policy-file /tmp/rbac-default.csv role:readonly get logs
Yes
$ argocd admin settings rbac can --policy-file /tmp/rbac-default.csv role:admin get logs
Yes
```

**Version**

```shell
argocd: v2.10.3+0fd6344.dirty
  BuildDate: 2024-03-13T21:01:52Z
  GitCommit: 0fd6344537eb948cff602824a1d060421ceff40e
  GitTreeState: dirty
  GoVersion: go1.22.1
  Compiler: gc
  Platform: darwin/arm64
```

### PR DESCRIPTION
**Pull request by hanxiaop**
Fixes https://github.com/argoproj/argo-cd/issues/17563

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by pasha-codefresh — APPROVED** [review]

**Review by reggie-k — APPROVED** [review]

**Comment by reggie-k** [comment]
Please run lint

**Comment by kencochrane** [comment]
@hanxiaop thanks for fixing that, it looks like the linter found some errors that you will need to fix.

**Review by christianh814 — APPROVED** [review]

**Review by wanghong230 — APPROVED** [review]

**Review by alexmt — APPROVED** [review]
LGTM, please fix the test and PR can be merged

**Review by todaywasawesome — APPROVED** [review]
Now that this lints properly, it's ready to go : D

**Comment by hanxiaop** [comment]
@pasha-codefresh Thank you for helping me fix the lint issues. However, resolving the lint didn’t pass the tests, as you can see https://github.com/argoproj/argo-cd/actions/runs/10704179817/job/29676741607?pr=17805. Due to the changes in https://github.com/argoproj/argo-cd/pull/19264, I need to revise the if/else condition to ensure it passes the test cases, rather than just addressing the lint issue. For convenience, I will remove your commits and redo the changes myself, but I really appreciate your help!

**Comment by hanxiaop** [comment]
Thank you all for the help with this PR! I appreciate the feedbacks.

**Review by gdsoumya — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
@hanxiaop thank you, and amazing work!

**Pull request merged**
