### PR TITLE
fix: add missing download CLI tool link for ppc64le, s390x

### PR DESCRIPTION
**Pull request by KENNYSOFT**
Follow up of #7755, for ppc64le and s390x.

QUESTION: the above part has not matched href(`download/argocd-linux-${process.env.HOST_ARCH}`) and button name("Linux (amd64)"). Could I unify this to `${process.env.HOST_ARCH}`?

https://github.com/argoproj/argo-cd/blob/f219888d9672c6e4779bd1d6001146a91b675d57/ui/src/app/help/components/help.tsx#L40-L41

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by KENNYSOFT** [comment]
Can be cherry-picked to 2.4

**Review by alexmt — APPROVED** [review]
Thank you ! LGTM

**Comment by crenshaw-dev** [comment]
@alexmt I'll plan to cherry-pick this onto 2.4.6. Let me know if you have any concerns!

**Comment by KENNYSOFT** [comment]
@crenshaw-dev Cool, but why not 2.4.5?

**Comment by crenshaw-dev** [comment]
@KENNYSOFT the release-2.4 branch is frozen for the 2.4.5 release tomorrow. We sometimes have a code freeze on release branches to help downstream users simplify their release process.

I'll cherry-pick after the release and also push 2.4.6 tomorrow.

**Comment by KENNYSOFT** [comment]
@crenshaw-dev I see, thanks for the clarification and looking forward for the release!

**Pull request merged**
