### PR TITLE
fix: add argocd-redis SA to nonroot security context constraint

### LINKED ISSUE #4236: v1.7.x redis version has forbidden security context constraint on openshift 4.x
**Describe the bug**
With ArgoCD v1.7x, the redis replicaset fails to deploy due to a forbidden security context constraint on Openshift 4.x (specifically 4.4.18 when testing). This issue does not appear in v1.6.2.

```shell
$ oc describe replicaset.apps/argocd-redis-54b6ff7bf6
Name:           argocd-redis-54b6ff7bf6
Namespace:      argocd
Selector:       app.kubernetes.io/name=argocd-redis,pod-template-hash=54b6ff7bf6
Labels:         app.kubernetes.io/name=argocd-redis
                pod-template-hash=54b6ff7bf6
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/argocd-redis
Replicas:       0 current / 1 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app.kubernetes.io/name=argocd-redis
           pod-template-hash=54b6ff7bf6
  Containers:
   redis:
    Image:      redis:5.0.8
    Port:       6379/TCP
    Host Port:  0/TCP
    Args:
      --save

      --appendonly
      no
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                 From                   Message
  ----     ------        ----                ----                   -------
  Warning  FailedCreate  34s (x24 over 44m)  replicaset-controller  Error creating: pods "argocd-redis-54b6ff7bf6-" is forbidden: unable to validate against any security context constraint: [fsGroup: Invalid value: []int64{1000}: 1000 is not an allowed group spec.containers[0].securityContext.securityContext.runAsUser: Invalid value: 1000: must be in the ranges: [1003970000, 1003979999]]
```

**To Reproduce**

kubectl apply any current manifest in the v.1.7.x range on Openshift 4.x. Stable, v1.7.3, v1.7.2:

```shell
$ oc apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v1.7.3/manifests/install.yaml
```

**Expected behavior**

Expected redis to deploy without issue, as seen here in v1.6.2:

```shell
$ oc describe replicaset argocd-redis-8c568b5db
Name:           argocd-redis-8c568b5db
Namespace:      argocd
Selector:       app.kubernetes.io/name=argocd-redis,pod-template-hash=8c568b5db
Labels:         app.kubernetes.io/name=argocd-redis
                pod-template-hash=8c568b5db
Annotations:    deployment.kubernetes.io/desired-replicas: 1
                deployment.kubernetes.io/max-replicas: 2
                deployment.kubernetes.io/revision: 1
Controlled By:  Deployment/argocd-redis
Replicas:       1 current / 1 desired
Pods Status:    1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:  app.kubernetes.io/name=argocd-redis
           pod-template-hash=8c568b5db
  Containers:
   redis:
    Image:      redis:5.0.3
    Port:       6379/TCP
    Host Port:  0/TCP
    Args:
      --save

      --appendonly
      no
    Environment:  <none>
    Mounts:       <none>
  Volumes:        <none>
Events:
  Type    Reason            Age   From                   Message
  ----    ------            ----  ----                   -------
  Normal  SuccessfulCreate  41m   replicaset-controller  Created pod: argocd-redis-8c568b5db-zkqkt
```

**Version**

```shell
$ argocd version
argocd: v1.7.3+b4c79cc
  BuildDate: 2020-09-01T23:17:31Z
  GitCommit: b4c79ccb88173604c3786dcd34e83a9d7e8919a5
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v1.6.2+3d1f37b
  BuildDate: 2020-07-31T23:45:07Z
  GitCommit: 3d1f37b0c53f4c75864dc7339e2831c6e6a947e0
  GitTreeState: clean
  GoVersion: go1.14.1
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: {Version:kustomize/v3.6.1 GitCommit:c97fa946d576eb6ed559f17f2ac43b3b5a8d5dbd BuildDate:2020-05-27T20:47:35Z GoOs:linux GoArch:amd64}
  Helm Version: version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
  Kubectl Version: v1.14.0
```

### PR DESCRIPTION
**Pull request by wtam2018**
Fixes: #4236

By default, Security Context Constraint (SCC) is set at the highest level "restricted" which only allows a specific UID range.  Pdd request with e.g. runAsUser 1000 will get rejected.   The fix here is to add "nonroot" SCC to service account of argocd-redis so that argocd-redis pod can be started using UID using RBAC.  
See: https://www.openshift.com/blog/managing-sccs-in-openshift for more details.

The fix involves adding Role to grant access to `security.openshift.io` apiGroups.   It will be ignored by non-openshift clustes.
```
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - nonroot
  resources:
  - securitycontextconstraints
  verbs:
  - use
```
For the ha installs, they are bit out of scope of this issue as manifests are driven by the upstream redis-ha charts.  The issue should be addressed in the upstream charts.    I will document `oc adm policy` commands to add service accounts to scc.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jessesuen** [comment]
Could this more easily be solved by changing the id of the user to be in the range acceptable by OpenShift?

**Comment by wtam2018** [comment]
> Could this more easily be solved by changing the id of the user to be in the range acceptable by OpenShift?

That would be easier but I found that accepted UID range can be different from Openshift cluster to cluster.   This is a sure way to fix it.

**Comment by wtam2018** [comment]
@alexmt @jetersen WDYT?  Is it a right fix?

**Review by alexmt — APPROVED** [review]
Thank you for the explanation @wtam2018 ! 

I think our options are either include openshift specific RBAC by default or introduce a two new kustomize bases for openshift (HA, not HA ).

I definitely prefer the first option. I think it is not so bad to have role and service account that is used only in openshift.

**Pull request merged**
