### PR TITLE
feat: Adding more health checks for Keycloak, Postgres, Grafana, SolrCloud

### PR DESCRIPTION
**Pull request by rezellme**
Summary:

Contributing with a few more custom health-checks that we needed for our setup.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] Does this PR require documentation updates?
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks for the PR!

I see that some of the test resources YAMLs are hand-crafted. Would it be possible to use actual (redacted) CRs for each scenario? That'll improve test reliability and give us something to check against if/when health checks are modified to take more info into account.

**Comment by rezellme** [comment]
> Would it be possible to use actual (redacted) CRs for each scenario?
Hi Michael, I rebased and then force-pushed actual/redacted CRs.

**Comment by rezellme** [comment]
Oops, forgot the GrafanaDatasource part 👼. force-pushed again.

**Review by crenshaw-dev — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
