### PR TITLE
chore: minor upgrade kustomize to most recent version (v4.5.3)

### PR DESCRIPTION
**Pull request by m-brgs**
Kustomize just released some great enhancements in [`v4.5.3`](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.3
)

- Allow setting every array element in replacements
- Support for multiple replacements in a single file

I'd be great to have it in the next release of ArgoCD !

Checklist:

* [c] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
*  I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
*  I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by m-brgs** [comment]
What am I missing ?

I added checksums in [hack/installers/checksums/kustomize_4.5.3_linux_amd64.tar.gz.sha256](https://github.com/argoproj/argo-cd/pull/8904/files#diff-9465bf51b110c3f5ac875140a715c953a11f791a7f1430dc4a386890961091b2) and [hack/installers/checksums/kustomize_4.5.3_linux_arm64.tar.gz.sha256](https://github.com/argoproj/argo-cd/pull/8904/files#diff-c861b6144826a678ee246a8bb3e2a7b45481aaf210ba993befc90af2d278e116) but CI breaks on "no checksum found"

Newly added checksums seems a bit shorter than old ones. I found them in https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.3 `checksums.txt`

@alexmt @jannfis I've seen you did an upgrade recently of kustomize in https://github.com/argoproj/argo-cd/pull/8227. Could you guide me in the right direction please ?

**Comment by jannfis** [comment]
Hi,

the checksum file in your PR contains `kustomize_v4.5.3_linux_amd64.tar.gz` as the file name, but it is downloaded as `kustomize_4.5.3_linux_amd64.tar.gz` (note the additional `v` in the checksum file you provided).

Also, you modified historical changelog information for 2.3. Please revert those changes, as this change won't be merged into the 2.3 branch. It will be part of 2.4. We do not upgrade Kustomize minor versions in patch releases, because it was breaking lots of people's things in the past :)

**Comment by m-brgs** [comment]
Thx for your input :) much appreciated

I've fixed the `v` typo. CI looks good except for _Integration tests / Check changes to generated code (pull_request)_ job but it doesn't seem related to my changes. Maybe this comes from the state master was in (I tried merging back master but this create a merge commit and I don't know what I should say in this merge commit message considering DCO and Semantic Pull Request).

Do I need to configure stuff in the MR settings in order for it to be merged and integrated into argocd `2.4` ?

Do you know when `2.4` is expected to be released ? Is there a release schedule somewhere ? (just to get an idea when I'll need to upgrade and plan some upgrades on our systems)

**Comment by crenshaw-dev** [comment]
> CI looks good except for Integration tests / Check changes to generated code (pull_request) job but it doesn't seem related to my changes. 

I wonder if the new kustomize version has different behavior for null/empty annotations. I think it would be safe to include those changes in the PR. Just run `make codegen`.

> Do you know when 2.4 is expected to be released ?

I think the plan is to release it early May, but I'm not aware of any firm date.

**Comment by crenshaw-dev** [comment]
@m-brgs closing for now. Ping me if you'd like to reopen, and I'll be happy to help get past the CI checks!

**Pull request closed without merging**
