### PR TITLE
chore(deps): bump k8s libs from 0.29.6 to 0.30.4

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Based on: https://github.com/argoproj/gitops-engine/pull/579/files

### CODE REVIEW

**Comment by sivchari** [comment]
The option of go-to-protobuf may be changed, so this CI would fail. This problem occur in https://github.com/argoproj/argo-cd/pull/18506 , too.

**Comment by crenshaw-dev** [comment]
@sivchari ah gotcha. Want to just update that PR, and I'll close this one?

**Comment by sivchari** [comment]
@crenshaw-dev 
Sure. I want to progress the way to resolve the issue in #18506 with us. Perhaps, this problem is just resolved to solve the `go-to-protobuf`.

**Comment by crenshaw-dev** [comment]
Codegen failure:

```
+ go-to-protobuf --go-header-file=/home/runner/go/src/github.com/argoproj/argo-cd/hack/custom-boilerplate.go.txt --packages=github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1 --apimachinery-packages=+k8s.io/apimachinery/pkg/util/intstr,+k8s.io/apimachinery/pkg/api/resource,+k8s.io/apimachinery/pkg/runtime/schema,+k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/api/core/v1,k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1 --proto-import=/home/runner/go/src/github.com/argoproj/argo-cd/vendor --proto-import=/home/runner/go/src/github.com/argoproj/argo-cd/dist/protoc-include --output-dir=/home/runner/go/src/
2024/07/19 14:28:27 protoc -I . -I /home/runner/go/src/ -I /home/runner/go/src/github.com/argoproj/argo-cd/vendor -I /home/runner/go/src/github.com/argoproj/argo-cd/dist/protoc-include --gogo_out=/home/runner/go/src/ /home/runner/go/src/k8s.io/api/core/v1/generated.proto
2024/07/19 14:28:27 Could not make proto path relative: /home/runner/go/src/k8s.io/api/core/v1/generated.proto: No such file or directory
```

Caused by this change in go-to-protobuf: https://github.com/kubernetes/code-generator/commit/e52957c054010e9f5c6951aa2556f929531ccf68

Not sure yet how to fix it.

**Comment by crenshaw-dev** [comment]
I just modified the script to copy dependencies from the vendor directory to the location go-to-protobuf expects them to be at.

**Comment by sivchari** [comment]
Sorry for not being able to respond. Brilliant, thanks.

**Comment by crenshaw-dev** [comment]
You're good! No real rush, just wanna sort it in time for 2.13.

**Comment by crenshaw-dev** [comment]
Questions I may or may not have time to answer before pushing to get this merged:

1) do we need the `toolchain` line in go.mod?
2) why does `go-to-protobuf` modify the stuff in `vendors` (specifically, why does it delete generated.pb.go files, breaking codegen) so that we have to re-run `go mod vendor`?
3) why is the violations exception list file now empty?

A lot of this codegen stuff is deep lore that goes back before my time, so I'm not sure how safe it is to ignore these oddities.

**Review by agaudreault — COMMENTED** [review]
LGTM. Tested locally (not checked out in gopath) and it works with updated tools. But i don't know what the violation list is for. Maybe @jannfis know?

**Review by agaudreault — APPROVED** [review]
LGTM. Future improvement on codegen can be done in other PRs

**Pull request merged**
