### PR TITLE
fix(ui): fix select destination cluster type in create app (issue #20961)

### LINKED ISSUE #20961: Cluster name selection is not working in New Application. Only cluster URL is working for Destination section.
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

By default, the dropdown selection for URL or Name in the Destination section for New Application does not work. Only URL is working until you click Edit as YAML and then enter any character in the `name` field and hit Save. This will go back to the UI and now the default selection for the dropdown is now Name and you can see in the field dropdown the cluster names defined in the Cluster page.

**To Reproduce**

1. Create a new Application
2. Scroll down to Destination section
3. Select Name in the dropdown. Nothing Happens
4. Select an existing cluster destination URL and then select Name in the dropdown. Field clears up and displays an error message "Cluster URL is required"
5. Click Edit As YAML and update the `name` field with any character (ex. `name: '.'`) and then hit Save
6. Destination is now defaulting to cluster name and can be selected.
7. Delete the selected cluster name in the field and it will revert again back to URL and it won't be change again to Name until you Edit As YAML again.

**Expected behavior**

Destination dropdown when clicking field should change depending on selection of URL or Name.

**Screenshots**

image
image
image
image

**Version**

```shell
argocd: v2.12.4+27d1e64
  BuildDate: 2024-09-26T06:58:55Z
  GitCommit: 27d1e641b6ea99d9f4bf788c032aeaeefd782910
  GitTreeState: clean
  GoVersion: go1.22.7
  Compiler: gc
  Platform: windows/amd64
time="2024-11-26T21:35:01+08:00" level=warning msg="Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web."
argocd-server: v2.13.1+af54ef8
  BuildDate: 2024-11-20T15:58:16Z
  GitCommit: af54ef8db5adfa77a08d4d05b1318a2198084c22
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v5.4.3 2024-07-19T16:40:33Z
  Helm Version: v3.15.4+gfa9efb0
  Kubectl Version: v0.31.0
  Jsonnet Version: v0.20.0
```

### PR DESCRIPTION
**Pull request by lsq645599166**
Fixes #20961 

This PR fixes an issue when the cluster type selection cannot change to name in create app panel.

### Before

https://github.com/user-attachments/assets/3fc072c2-3651-4b4d-ae64-11f76781d186

### After

https://github.com/user-attachments/assets/1d6f5b32-bc0f-4c04-8537-022f9d2dc167

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by andrii-korotkov-verkada — APPROVED** [review]

**Review by linghaoSu — APPROVED** [review]

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
@lsq645599166 , do you mind resolving the conflicts?

**Comment by lsq645599166** [comment]
> @lsq645599166 , do you mind resolving the conflicts?
Hi @ishitasequeira , thanks for you review. I have already resolved the conflicts by rebase

**Review by ishitasequeira — APPROVED** [review]
Thanks @lsq645599166 !!

**Pull request merged**
