### PR TITLE
feat: Clicking on filter bar should expand filter

### LINKED ISSUE #4790: clicking filters widget doesn't expand filters
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The filters widget is so far from the expander, and clicking it just focuses it which is pretty useless. It'd be much better if it expanded the box (clicking anywhere in an application opens the application; clicking any resource shows details for the resource)

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications
1. Click the funnel

**Expected behavior**

Expand the filters view (if it's collapsed)

If it's expanded, I'm flexible -- one could argue that it should collapse the view.

**Screenshots**

image

**Version**

```shell
{
    "Version": "v1.8.0+7947b59",
    "BuildDate": "2020-11-07T18:09:27Z",
    "GitCommit": "7947b59eeb559c7c9bb717716e9a6992cac66676",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.1",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.0+g7090a89",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.16.0"
}
```

**Logs**

### PR DESCRIPTION
**Pull request by chetan-rns**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Clicking on the filter bar should expand filters if it's collapsed.

Fixes: #4790
filter-bar

### CODE REVIEW

**Comment by chetan-rns** [comment]
I'm new to React and happy to learn if there's a better way to fix this cc @keithchong @reginapizza

**Comment by reginapizza** [comment]
@chetan-rns looks good to me!

**Comment by keithchong** [comment]
Sorry about the delay @chetan-rns , just saw this.  I'm not quite sure why that filter icon is even focussable too.  I'm guessing the purpose of that is just for decoration only, something like the icon that is in the top left corner of each application tile.  So if it is just for decoration only, then you will have to make the whole whitespace area clickable as well to expand/collapse the filter.

**Comment by rbreeze** [comment]
I agree with @keithchong , I think clicking anywhere on the filter bar should expand it. Otherwise, looks good!

**Comment by chetan-rns** [comment]
Thanks! Making the entire bar clickable is a good idea. Will update it

**Comment by chetan-rns** [comment]
I've updated the PR to make the entire bar clickable. Please consider it for review

**Review by rbreeze — COMMENTED** [review]
LGTM. @alexmt could you approve this?

**Review by alexmt — APPROVED** [review]
LGTM. Thank you

**Pull request merged**
