### PR TITLE
fix: AppSet Progressive sync fixes, docs, and logging improvements

### LINKED ISSUE #11924: 2.6 RC2: ApplicationSet RollingSync Deploys all Apps at once
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Trying out the new [RollingSync](https://argo-cd.readthedocs.io/en/latest/operator-manual/applicationset/Progressive-Rollouts/#progressive-rollouts) alpha feature isn't working as expected.

When I try to use this feature, it seems that the ApplicationSet Controller creates them all at once (instead of one at a time as my configuration suggests)

**To Reproduce**

1. [Install 2.6 RC2](https://github.com/argoproj/argo-cd/releases/tag/v2.6.0-rc2)
2. Apply my example: `kubectl apply -f https://raw.githubusercontent.com/christianh814/gitops-examples/main/applicationsets/rollingsync/appset-rollingsync.yaml`

An example of the config I used:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pricelist
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - srv: config
        path: applicationsets/rollingsync/apps/pricelist-config
      - srv: db
        path: applicationsets/rollingsync/apps/pricelist-db
      - srv: frontend
        path: applicationsets/rollingsync/apps/pricelist-frontend
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: srv
              operator: In
              values:
                - config
        - matchExpressions:
            - key: srv
              operator: In
              values:
                - db
        - matchExpressions:
            - key: srv
              operator: In
              values:
                - frontend
  template:
    metadata:
      name: 'pricelist-{{srv}}'
      labels:
        pricelist-component: '{{srv}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
      source:
        repoURL: https://github.com/christianh814/gitops-examples
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: pricelist
```

**Expected behavior**

I expected the ApplicationSet controller to create the Applications as needed/defined in the config. In my case, I expected the first Application to deploy and finish before the second one is even created, and so on.

**Screenshots**

All applications appeard all at once, instead of one at a time

image

**Version**

```shell
$ argocd version
argocd: v2.5.3+0c7de21
  BuildDate: 2022-11-28T17:11:59Z
  GitCommit: 0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96
  GitTreeState: clean
  GoVersion: go1.18.8
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.0-rc2+6a9f37c
  BuildDate: 2023-01-05T15:10:14Z
  GitCommit: 6a9f37ca7d9cabfde298d69e8731874e3e5347cf
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

I see the following, which indicates  every app being created at once.

```
time="2023-01-09T19:10:56Z" level=info msg="generated 3 applications" generator="{&ListGenerator{Elements:[]JSON{{[123 34 112 97 116 104 34 58 34 97 112 112 108 105 99 97 116 105 111 110 115 101 116 115 47 114 111 108 108 105 110 103 115 121 110 99 47 97 112 112 115 47 112 114 105 99 101 108 105 115 116 45 99 111 110 102 105 103 34 44 34 115 114 118 34 58 34 99 111 110 102 105 103 34 125]},{[123 34 112 97 116 104 34 58 34 97 112 112 108 105 99 97 116 105 111 110 115 101 116 115 47 114 111 108 108 105 110 103 115 121 110 99 47 97 112 112 115 47 112 114 105 99 101 108 105 115 116 45 100 98 34 44 34 115 114 118 34 58 34 100 98 34 125]},{[123 34 112 97 116 104 34 58 34 97 112 112 108 105 99 97 116 105 111 110 115 101 116 115 47 114 111 108 108 105 110 103 115 121 110 99 47 97 112 112 115 47 112 114 105 99 101 108 105 115 116 45 102 114 111 110 116 101 110 100 34 44 34 115 114 118 34 58 34 102 114 111 110 116 101 110 100 34 125]},},Template:ApplicationSetTemplate{ApplicationSetTemplateMeta:ApplicationSetTemplateMeta{Name:,Namespace:,Labels:map[string]string{},Annotations:map[string]string{},Finalizers:[],},Spec:ApplicationSpec{Source:nil,Destination:ApplicationDestination{Server:,Namespace:,Name:,},Project:,SyncPolicy:nil,IgnoreDifferences:[]ResourceIgnoreDifferences{},Info:[]Info{},RevisionHistoryLimit:nil,Sources:[]ApplicationSource{},},},} nil nil nil nil nil nil nil nil}"
time="2023-01-09T19:10:56Z" level=info msg="unchanged Application" app=pricelist-config appSet=pricelist
time="2023-01-09T19:10:56Z" level=info msg="unchanged Application" app=pricelist-db appSet=pricelist
time="2023-01-09T19:10:56Z" level=info msg="unchanged Application" app=pricelist-frontend appSet=pricelist
time="2023-01-09T19:10:56Z" level=info msg="end reconcile" applicationset=argocd/pricelist requeueAfter=0s
```

### PR DESCRIPTION
**Pull request by wmgroot**
Closes https://github.com/argoproj/argo-cd/issues/11924.

Summary of changes:
* Bug fix to default Applications that have not had ApplicationStatus created to Healthy instead of Waiting if they're already healthy, this avoids an edge case where Applications can become stuck in Pending incorrectly during a RollingSync.
* Bug fix to catch a case where the controller would fail to notice an Application had been synced and become healthy, blocking further syncs.
* Adding a step field to note which step of the RollingSync the Application belongs to, just for debugging.
* A few more logging spots, with clearer wording.
* Documentation updates to remove some confusion around the use of label selectors.

Signed-off-by: wmgroot <wmgroot@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @wmgroot!

**Comment by wmgroot** [comment]
Thanks for the review, I'll keep an eye out for when you'd like me to rebase with master.

**Comment by crenshaw-dev** [comment]
Hopefully there won't be any need to rebase. Once the CI checks pass, I should be able to merge and cherry-pick.

**Comment by wmgroot** [comment]
Awesome.

**Comment by crenshaw-dev** [comment]
@wmgroot actually, looks like I gotta ask for that rebase. :-)

**Comment by crenshaw-dev** [comment]
Cherry-picked onto release-2.6 for 2.6.0-rc8.

**Pull request merged**
