### PR TITLE
docs: Add Crédit Agricole CIB to list of production users.

### PR DESCRIPTION
**Pull request by balchua**
Requesting to add Crédit Agricole CIB as list of production users.

### CODE REVIEW

**Comment by sbose78** [comment]
Please use the format 'docs: ...."

**Comment by balchua** [comment]
I modified the title to include `docs:`

Is it normal that the "Sematic Pull Request" fails?

**Comment by sbose78** [comment]
You'll need to modify the commit message :)

**Comment by balchua** [comment]
thanks @sbose78! i think i fixed it. :)

**Review by jannfis — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
