### PR TITLE
fix: Disable keep alives for helm https connections (#13468)

### LINKED ISSUE #13468: argocd-repo-server does not close https connections to helm server
**Checklist:**

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**

`argocd-repo-server` will leave open https sessions towards a helm `RepoURL` which are never closed.
A keepalive packet is sent, every 15 seconds it seems, but on the next iteration a new sessions is opened.

In the end each `argocd-repo-server` will have several hundred open sessions
but since we have multiple argocd instances **and** multiple clusters the **proxy** ends up with **thousands** of sessions which never closes, but neither **produce** anything.

This problem seems like it's the **exact** same problem described for **git** in issue in #3522, which was fixed in #3531
Analyzing (briefly) and comparing the code for **git**, with the code for **helm** shows that there is no similar reference to `DisableKeepAlives: true`

* Git: https://github.com/argoproj/argo-cd/blob/master/util/git/client.go#L220
* Helm: https://github.com/argoproj/argo-cd/blob/master/util/helm/client.go#L303 and https://github.com/argoproj/argo-cd/blob/master/util/helm/client.go#L475

github repositories are also configured pr `Application`, but do not produce the same problem.

_Background info:_

The helm repository is proxied through our Nexus (Sonatype Nexus Repository manager) instance (to handle auth, caching, etc.), which in turn is proxied through an F5 BIGIP (proxy henceforth). The problem is **not** related to these components, but led to us discovering the underlying issue.

**To Reproduce**

Configure a `repositories` entry of `type: helm` in the `argocd-cm` ConfigMap, for instance in the `argocd` configuration with the Argo CD Operator

```yaml
initialRepositories: |
  - type: helm
    name: evryfs
    url: https://nexus.internalserver.local/nexus/repository/internalrepo-helm/
```

Configure at least **one** `Application` which use the configured chart.
An argocd-instance with many `Application`'s configured have way more sockets, since all source the same helm chart proxy.

PS! I'm referring to a fictitious internal helm chart, but this will apply to all helm charts.

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-application
  namespace: internal-argocd
spec:
  destination:
    namespace: internal-namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: internal-chart
    helm:
      values: |
        key1: value
        key2: value
    repoURL: https://nexus.internalserver.local/nexus/repository/internalrepo-helm/
    targetRevision: 0.1.2
  syncPolicy:
    automated:
      prune: true
```

Observe that the number of file descriptors for the running `argocd-repo-server` pods of type `socket` is growing steadily.

1. Log into the worker node running the `argocd-repo-server` at the moment, at the "bare metal"
2. Get the PID of the running process
3. Count the number of sockets
4. Observe over time that the number of sockets increase
5. Restart `argocd-repo-server` - observe that the number of sockets drops, then increases steadily

```bash
# ssh into a worker-node running the repo-server, in this instance there are multiple
# List the number of file descriptors of type "socket" and print a total and a pr PID count
# List each 60 seconds
$ for i in {1..10}; do for PID in $(pgrep -f "^argocd-repo-server"); do    ls -lah /proc/${PID}/fd/* ; done | awk '
/socket/ {
    split($i,L,"/")
    pr_pid[L[3]]++
    total++
}

END {
    printf("%s Total: %6i - Pr PID: ", d, total)
    for (i in pr_pid) {
        printf("%3i ", pr_pid[i])
    }
    print ""
}
' d=$(date +%F-%T); sleep 60 ; done
2023-05-05-09:57:46 Total:   2267 - Pr PID:   5   9 334 339 209 332  12  15 216 207 208 335  14   7  25 
2023-05-05-09:58:46 Total:   2263 - Pr PID:   5   8 331 339 209 332  12  15 216 207 208 335  14   7  25 
2023-05-05-09:59:46 Total:   2261 - Pr PID:   5   8 331 342 209 332  12  10 216 207 208 335  14   7  25 
2023-05-05-10:00:47 Total:   2263 - Pr PID:   5   8 331 342 210 332  11  13 216 206 208 335  14   7  25 
2023-05-05-10:01:47 Total:   2280 - Pr PID:   5   8 334 342 210 332  11  13 216 206 209 342  20   7  25 
2023-05-05-10:02:47 Total:   2281 - Pr PID:   5   8 334 343 210 332  11  13 216 206 209 342  20   7  25 
2023-05-05-10:03:47 Total:   2271 - Pr PID:   5   8 334 343 210 333  11  13 213 207 209 342  20   7  16 
2023-05-05-10:04:47 Total:   2274 - Pr PID:   5   8 335 343 210 333  11  13 213 207 210 343  20   7  16 
2023-05-05-10:05:47 Total:   2274 - Pr PID:   5   8 335 343 210 333  11  13 213 207 210 343  20   7  16 
2023-05-05-10:06:47 Total:   2283 - Pr PID:   5   8 335 343 211 335  11  13 210 207 210 343  20   7  25 
```

Learning from the connected issue (#)3522 we can adjust the `nsenter`-command and see similar info, and that (almost) all the connections go towards the proxy IP

```bash
# 1. Get the argocd-repo-server PID for the one with the _most_ open sockets
# 2. anonymize the IP-adresses
# 3. and group and see that almost all sockets go towards _one_ IP, the proxy IP
# (verfied by analyzing the actual IP-adresses and output)
for PID in $(pgrep -f "^argocd-repo-server")
do
    echo ${PID} $(ls -lah /proc/${PID}/fd/* | grep -c socket)
done |
  sort -k2n |
  tail -1 |
  awk '{ print $1 }' |
  while read TOP_PID
  do
     nsenter -t ${TOP_PID} -n netstat -pantu
  done |
  awk '{
    sub(/^[0-9]+\.[0-9]+\.[0-9]+\./,"<source>.",$4)
    sub(/:[0-9]+$/,"<srcport>",$4) 
    sub(/^[0-9]+\.[0-9]+\.[0-9]+\./,"<dest>.",$5) 
    print
  }' |
  sort |
  uniq -c |
  sort -n
```

Output

```bash
      1 Active Internet connections (servers and established)
      1 Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
      1 tcp6 0 0 <source>.85<srcport> <dest>.10:37518 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.14:50196 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45250 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45300 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45310 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45390 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45432 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45468 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45478 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45496 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45526 ESTABLISHED 52889/argocd-repo-s
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45546 ESTABLISHED -
      1 tcp6 0 0 <source>.85<srcport> <dest>.64:45560 ESTABLISHED -
      2 tcp 0 0 <source>.85<srcport> <dest>.1:8080 ESTABLISHED -
      2 tcp6 0 0 ::<srcport> :::* LISTEN 52889/argocd-repo-s
      4 tcp 0 0 <source>.85<srcport> <dest>.146:6379 ESTABLISHED 52889/argocd-repo-s
      9 tcp 0 0 <source>.85<srcport> <dest>.1:8080 ESTABLISHED 52889/argocd-repo-s
    343 tcp 0 0 <source>.85<srcport> <dest>.168:443 ESTABLISHED 52889/argocd-repo-s
```

The last line, with 343 connections (and counting) is towards the proxy server for the helm chart.

**Expected behavior**

That `argocd-repo-server` is either able to re-use a socket or don't leave old sockets laying around.

**Screenshots**

Helm chart proxy is run in Nexus, which in turn is proxied through an F5 BIGIP.
Yesterday evening we restarted **all** the `argocd-repo-server` components in all our clusters and as we can see from the BIGIP graphs the number of sessions, and thus memory consumption on it, dropped **significantly**.
We have historical data which correlate to similar efforts, at the time unknown connection, during upgrades of ArgoCD - which in turn resulted in restarts of `argocd-repo-server`

image

**Version**
We currently run `argocd-2.6.7`, but the same symptoms was present in `argocd-2.3.x` as we upgraded recently.

```shell
argocd: v2.7.1+5e54351.dirty
  BuildDate: 2023-05-02T18:52:29Z
  GitCommit: 5e543518dbdb5384fa61c938ce3e045b4c5be325
  GitTreeState: dirty
  GoVersion: go1.20.3
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.6.7+unknown
  BuildDate: 2023-04-03T17:35:00Z
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 1970-01-01T00:00:00Z
  Helm Version: v3.10.0+ge534a5d
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

N/A

### PR DESCRIPTION
**Pull request by mkekeberg**
Fixes #13468

Like for git (#3531), it seems that we don't re-use the connection. Keeping them alive only ends up with many stale http connections after a while, like the issue mentions.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
LGTM. Thanks, @mkekeberg!

**Comment by crenshaw-dev** [comment]
@mkekeberg would you mind opening cherry-pick PRs against the release-2.5, release-2.6, and release-2.7 branches? The bot is finicky.

**Comment by mkekeberg** [comment]
@crenshaw-dev , did that in my latest PRs 🙂 
https://github.com/argoproj/argo-cd/pull/13847
https://github.com/argoproj/argo-cd/pull/13848
https://github.com/argoproj/argo-cd/pull/13849

**Comment by sastorsl** [comment]
@crenshaw-dev is there anything left out here to get these fixes into a release?
@mkekeberg ?

**Comment by mkekeberg** [comment]
@sastorsl , I created the "cherry pick" PRs for specific releases. Seems like nothing ever happened on those:
https://github.com/argoproj/argo-cd/pull/13849
https://github.com/argoproj/argo-cd/pull/13848
https://github.com/argoproj/argo-cd/pull/13847


If the build issues on those important, I have no way of knowing. No reply from any maintainers on this project.  Release-branches in the dozens like this is always tedious...

**Comment by crenshaw-dev** [comment]
Apologies for the slow responses! Merged for 2.7 and 2.6. Skipping 2.5 since it went EOL. 

@sastorsl this change is already in 2.8.0. It will be in 2.7.13 and 2.6.14 when we cut those.

**Pull request merged**
