### PR TITLE
feat: get pod logs

### PR DESCRIPTION
**Pull request by mayzhang2000**
Signed-off-by: May Zhang <may_zhang@intuit.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by rbreeze** [comment]
This looks like a great feature. I think it would also be super useful in the UI - any chance you'd want to add an API server endpoint for combined application pod logs, in this PR too?

**Comment by alexmt** [comment]
I had the same though @rbreeze . We discussed that feature offline and agreed to re-use existing `PodLogs` API: add `group`, `kind` parameters and make `podName` optional. This way the same API can be used to get logs of one pod as well as all child pods of a parent resource , such as ReplicaSet or Deployment.

**Comment by rbreeze** [comment]
Oh awesome, great idea!

**Review by alexmt — CHANGES_REQUESTED** [review]

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by johnmarcou** [comment]
@mayzhang2000 Thanks for this new `log` command!

I got an issue though when the pod has multiple containers like here:
```
# argocd app logs demo03
FATA[0004] stream read failed: rpc error: code = FailedPrecondition desc = a container name must be specified for pod nginx-9f5566c44-n6d5n, choose one of: [nginx2 nginx]
```

I works well if I remove the second container in the pod.

**Comment by LiorLieberman** [comment]
Hi @mayzhang2000 any reason for setting maxPodLogsToRender to 10 [here](https://github.com/argoproj/argo-cd/blob/8b6af8b3d374fc0de79691058abc3dc83a23b60f/server/application/application.go#L61)?
What if I need to see logs for more than 10 pods?

Thank you?

**Pull request merged**
