### PR TITLE
docs: Fix docs for `destinations` in `AppProjects` (fixes #15153)

### LINKED ISSUE #15153: Mismatch between documentation and API (CRD) for `AppProject`
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

In [the documentation for `AppProjects`](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#projects), it says (bold emphasis is mine):

> `destinations` reference to clusters and namespaces that applications within the project can deploy into **(don't use the `name` field, only the `server` field is matched)**.

But `kubectl explain` says that it's a valid field:

```console
$ kubectl explain appproject.spec.destinations.name
KIND:     AppProject
VERSION:  argoproj.io/v1alpha1

FIELD:    name <string>

DESCRIPTION:
     Name is an alternate way of specifying the target cluster by its symbolic
     name
```

Something is wrong, either in the documentation or in the CRD.

**To Reproduce**

n/a

**Expected behavior**

Consistent descriptions in documentation and API.

**Screenshots**

n/a

**Version**

n/a

**Logs**

n/a

### PR DESCRIPTION
**Pull request by lindhe**
This change removes an out-of-date notice in the documentation for `AppProjects`.

Fixes #15153

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

### CODE REVIEW

**Comment by lindhe** [comment]
I feel pretty innocent for the e2e test crash. :)

**Comment by crenshaw-dev** [comment]
@lindhe nah this is a very suspicious docs change. 😆 I'll re-trigger until it passes. Thanks!

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
