### PR TITLE
chore: portable and simpler codegen toolchain install

### PR DESCRIPTION
**Pull request by jessesuen**
I recently went through the process of setting up a brand new dev environment and found that the way we install argo-cd codegen dependencies to be inconsistent, error prone, and with conflicting sources of truth. There are also newer techniques to install golang CLIs with recent versions of go (namely the ability to do `GOBIN=<path> go install <pkg>@<version>`). I made the following changes:

1. Consolidated all golang codegen CLI installations into `install-codegen-go-tools.sh`. Previously we would install our tooling in many different scripts using different methods (e.g. `go build`, `go install`, etc...).
2. Codegen CLIs will now be built under `argo-cd/dist` as opposed to a mix of `$GOBIN` and `argo-cd/dist`. This makes the toolchain more portable and unaffected when working across projects (e.g. argo-rollouts vs. argo-cd). Codegen scripts have been modified to use the binaries under `dist`.
3. For each codegen CLI, there will only be one source of truth of the desired version. The desired version will either be recorded in:
     * the `go.mod` file,  if we actually need to vendor the dependency
     * in `install-codegen-go-tools.sh`, if we can avoid vendoring and explicitly install a version with `go install <package>@<version>`

NOTE: this change only improves the golang toolchain install experience, but not the non-golang CLIs (e.g. protoc, jq).

Signed-off-by: Jesse Suen <jesse@akuity.io>

### CODE REVIEW

**Comment by alexmt** [comment]
Awesome. I have a fresh laptop without code-gen tools - testing it today !

**Comment by jessesuen** [comment]
I think there's still a problem with `protoc` version being inconsistent on macOS and CI, which causes a diff to happen when running `make codegen-local`. So it's still not there yet. The goal should be that we can run `make codgen-local` on Apple Silicon and the generated files will not have a diff in the CI.

Unfortunately `protoc` is less portable to be installed because we also depend on the protoc include paths created under /usr/local/include.

However, I do think it's possible to also install `protoc` under `argo-cd/dist` and maybe the include path under `argo-cd/dist/protoc-include`. This way we should achieve close to 100% portability across environments, without resorting to Docker.

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
This unfortunately broke the dockerized build & test toolchain, because we now need the `vendor` directory within that container.

Is there a reason you chose to install from vendor directory, and not from the Go public repository?

**Comment by ocraviotto** [comment]
@jessesuen I'm a grateful user who's currently trying to contribute back with a little enhancement. In doing so, I updated my branch and pulled this change, just to find that it appears to break the flow when working with the so called virtualized toolchain, as various make targets will build the docker test image locally, but the build would fail because of the changes introduced in this PR. (Just noticed @jannfis comment above with the same problem)

The main issue is with the test/container/Dockerfile and the fact that it uses the install.sh (and the copied installers) *without* having the argo-cd contents (and so no vendor or go.mod or go.sum files for that matter) copied over to the container when installing the tools. The flow is so that the repository will be mounted only at runtime, but we would not want to have to install deps on every run.  

I worked around it by modifying the mentioned Dockerfile and hack/update-codegen.sh (to set GOBIN depending on whether it's running inside the container or not) and managed to build the test image without errors again and without much additions to the Dockerfile (or changes elsewhere). Not sure if it's the best way around this, but I'll link what I did that from my commit once ready, hopefully within a couple of hours as I'm going for dinner now.

**Comment by jannfis** [comment]
@ocraviotto I'm interested into the solution you came up with. I had done something along the lines of https://github.com/jannfis/argo-cd/tree/chore/update-test-tools-build, which feels like a hack (and therefore, I have not yet submitted a PR)

**Comment by jessesuen** [comment]
> This unfortunately broke the dockerized build & test toolchain, because we now need the vendor directory within that container.

Oops. Sorry about that.

> Is there a reason you chose to install from vendor directory, and not from the Go public repository?

There were two reasons:
1. Currently we vendor some of the libraries for which we also install a CLI binary from. So the source of truth for some of our tooling needed to be duplicated in multiple places (install script as well as go.mod). This was an attempt to get to a single source of turn

2. I wanted to remove our dependency of GOPATH/src, and so `vendor` seemed like the appropriate place to get it from.

However, thinking about it more, I think we can have it both ways. I think we can determine the desired version from `go.mod` followed by a normal `go install @<version>`. Let me try that as a solution.

**Comment by ocraviotto** [comment]
> @ocraviotto I'm interested into the solution you came up with. I had done something along the lines of https://github.com/jannfis/argo-cd/tree/chore/update-test-tools-build ([master...jannfis:chore/update-test-tools-build](https://github.com/argoproj/argo-cd/compare/master...jannfis:chore/update-test-tools-build)), which feels like a hack (and therefore, I have not yet submitted a PR)

Not sure my way of working around this was not [hackish](https://github.com/ocraviotto/argo-cd/commit/08dbd3f511bfa2b9bd241b9f29885595a3bdf8da). The fix above seems much simpler though still a bit hackish too IMHO :) 
I'll give it a try though.

**Comment by ocraviotto** [comment]
FYI, tested #8000 and still has issues and won't build the test image. Commented in the PR code directly.

**Pull request merged**
