### PR TITLE
feat: ApplicationSet controller sharding (#9002)

### LINKED ISSUE #9002: Performance of ApplicationSet Controller
# Summary

We are heavily using ApplicationSet in our company. At the time of writing, we have 1296 ApplicationSet, 5155 Application created in the ArgoCD cluster. Most of the time, making a change on ApplicationSet and generation of a new application takes approximately 30 minutes. Because of that making a new deployment via ApplicationSet initially takes 30 minutes. Can we analyze and improve this one (btw, glad to work on the subject if you can guide us)? 

# Proposal

If the controller is managing too many ApplicationSet then can we implement a sharding option similar to the ArgoCD application controller?

We saw that the maximum number of concurrent Reconciles which can be run defaults to 1 in the ApplicationSet controller. Can we speed up processing ApplicationSets by increasing this number? Would it cause any concurrency-related issues for ApplicationSet? If not, would it be possible to make this option configurable? Somehow similar to "--operation-processors" or "--status-processors" options in ArgoCD application controller.

### PR DESCRIPTION
**Pull request by hcelaloner**
Fixes #9002
Co-authored-by: Erkan Zileli <erkan.zileli@trendyol.com>
Co-authored-by: Doğukan Tuna <dogukan.tuna@trendyol.com>
Signed-off-by: Celal Öner <celal.oner@trendyol.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by hcelaloner** [comment]
Hi, we tried to provide an initial implementation for sharding based on ArgoCD's existing implementation. However, I guess it is not completed, we may need to convert deployment to statefulset as in ArgoCD application controller. If this feature is ok for you guys, can you guide us about missing parts or any preferred approaches on the codebase. We are using appsets heavily (~2k appsets ~8k apps) and facing some scalability issue, we would like to contribute as much as we can.

**Comment by rishabh625** [comment]
Hey @hcelaloner , I would request you to create proposal and discuss it before doing any architectural changes

**Comment by hcelaloner** [comment]
> Hey @hcelaloner , I would request you to create proposal and discuss it before doing any architectural changes

@rishabh625 could you give me an example to understand the expectation from the proposal? In #9002, I tried to propose this as a solution but it was a one-sentence, I can try to give some details on the idea in that issue.

**Comment by rishabh625** [comment]
> > Hey @hcelaloner , I would request you to create proposal and discuss it before doing any architectural changes
> 
> @rishabh625 could you give me an example to understand the expectation from the proposal? In #9002, I tried to propose this as a solution but it was a one-sentence, I can try to give some details on the idea in that issue.

I meant enhancement propsal , probably you could add more of your thinking in #9002 or here itself, i m good for now

**Pull request closed without merging**
