### PR TITLE
feat(appset): Add stringTemplate field to spec

### LINKED ISSUE #11213: feat(ApplicationSet): Templating - Add possibility of using advanced templating across template field
# Summary

Currently, with the ApplicationSet templating system, we cannot use the advanced function (although we have https://github.com/argoproj/argo-cd/pull/10026) on the whole body of the `template` field as the rendering is scoped per field.

# Motivation

* Usecase 1: When using `git` generator with the `files.path` set we can delegate some specific configs to the maintainer of the path with `*.yaml` or `*.json` files

```json
{
  "appConfig": {
    "selfHeal": true
  }
}
```

```yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-app-set
spec:
  generators:
    - git:
        files:
          - path: path/**/config.json
        repoURL: https://github.com/argoproj/argo-cd.git
        revision: HEAD
  goTemplate: true
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      destination:
        name: "in-cluster"
      project: "default"
      source:
        helm:
          valueFiles:
            - values.yaml
        path: "{{ .path.path }}"
        repoURL: https://github.com/argoproj/argo-cd.git
        targetRevision: HEAD
      syncPolicy:
        automated:
          selfHeal: {{ .appConfig.selfHeal }} # This is not possible as the field should be bool
```

* Usecase 2: When you want to have dynamically generated annotations/labels like the below (from https://github.com/argoproj/argo-cd/pull/10026#issuecomment-1236518978), the current way is not enough the schema of the ApplicationSet is not valid this way

```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
spec:
  goTemplate: true
  template:
    metadata:
      annotation:
        {{ range .annotations -}}
        {{ .key }}: "{{ .value }}"
        {{ end -}}
```
# Proposal

Introduce a new field in the `ApplicationSet` CRD of type `string` let's call it `stringTemplate` that will contain the go template.

A quick overview of the implementation:

1. Render using `Replace` method implemented in `Render` struct (thanks to @speedfl for the suggestion here https://github.com/argoproj/argo-cd/pull/11183#issuecomment-1302518633)
2. Marshal the previously rendered template to an `Application` inside `RenderTemplateParams` 
3. If the `tmpl` is not nil it will be merged with the previously Marshaled `stringTemplate`

### PR DESCRIPTION
**Pull request by mrmm**
Closes: #11213

This will introduce a new field `stringTemplate` that will allow a less restrictive templating of the Application to be generated as the current design is limited by field.

Related discussions:
- https://github.com/argoproj/argo-cd/pull/10026#issuecomment-1236888623

*This work was started in https://github.com/argoproj/argo-cd/pull/9873*

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by speedfl** [comment]
@mrmm are you sure you want to create the method `renderWithGoTemplate`. Can the `Replace` in utils do the job ?

Concerning your tests as you are passing the stringTemplate string you need to add test with `stringTemplate != nil` in the `utils_test.go`
- One test success
- One test with UnmarshalStrict failure

You can add a test on yaml templating error

https://github.com/argoproj/argo-cd/blob/master/applicationset/utils/utils_test.go#L60

Something like

```golang
template := "hello: {{ .one }}"

	tests = append(tests, struct {
		name        string
		fieldVal    string
		template    *string
		params      map[string]interface{}
		expectedVal string
	}{
		name:        "test",
		fieldVal:    "",
		template:    &template,
		expectedVal: "hello: world",
		params: map[string]interface{}{
			"one":   "world",
			"three": "four",
		},
	})
```

**Comment by mrmm** [comment]
Hello @speedfl, thanks for the prompt reply,

> @mrmm are you sure you want to create the method `renderWithGoTemplate`. Can the `Replace` in utils do the job ?

Yes totally, I have just tried to use the work of @rishabh625 (as it was his idea) but using `r.Replace` does the job (which I have updated in b91759c)

> Concerning your tests as you are passing the `stringTemplate` you need to add test with `stringTemplate != nil` in the `utils_test.go`

Thanks for the pointer on how to test, here is my try https://github.com/mrmm/argo-cd/blob/b91759cfb49af40cfddd989bdd202ea15cc30183/applicationset/utils/templating_test.go#L463-L560 but I seem to be running into an Unmarshaling issue for some reason I couldn't find.

```
                Error Trace:    templating_test.go:554
                Error:          Received unexpected error:
                                yaml: unmarshal errors:
                                  line 1: field metadata not found in type v1alpha1.Application
                                  line 6: field repoURL not found in type v1alpha1.ApplicationSource
                                  line 7: field targetRevision not found in type v1alpha1.ApplicationSource
                                  line 12: field syncPolicy not found in type v1alpha1.ApplicationSpec
                Test:           TestRenderTemplateParamsStringTemplate/text_template
```

(Please let me know if you don't have the time to check this I will gladly stop pinging here 🙏 )

**Comment by mrmm** [comment]
Hey @crenshaw-dev (really sorry for the multiple pings) is this feature still relevant to work on or not?

**Comment by adabuleanu** [comment]
@mrmm I encountered a situation that may benefit from this feature. This is described in: https://github.com/argoproj/applicationset/issues/609. I would be very grateful if you can take this scenario into consideration when developing this feature (if you did not do that already). 

From your experience is there any existing feature that might help with my use-case? I have been going over lots of argocd docs and tickets and ended up here.

**Comment by crenshaw-dev** [comment]
@mrmm this feature is definitely still relevant, I just haven't had a chance to dig into the code yet. Hopefully for 2.7?

**Comment by mrmm** [comment]
> @mrmm this feature is definitely still relevant, I just haven't had a chance to dig into the code yet. Hopefully for 2.7?

@crenshaw-dev Thanks for the reply, and sorry again for the multiple pings. I just wanted confirmation from a main contributor before dedicating more time to it 🙏 (Thanks for the confirmation).

I will work on this by the end of the week and the next week, hopefully, will have some tests implemented and refined a little bit of the code.

**Comment by crenshaw-dev** [comment]
@mrmm sounds great!

The main thing I'd want to see in this PR (besides working code, tests, the usual :-D) is documentation clarifying when it makes sense to use `stringTemplate` vs `template`.

Specifically, `template` allows the ApplicationSet author to strictly enforce certain field values (like `project`) without having to think too long about user input validation. `stringTemplate` opens things up a bit, so it might not make as much sense when an AppSet author wants to clearly lock things down.

**Comment by brunocascio** [comment]
Hey there!

I have also this use case where this PR would help: https://github.com/argoproj/argo-cd/discussions/11589

**Comment by crenshaw-dev** [comment]
I'm personally not going to be able to prioritize this for 2.7.

If you'd like to advocate for the PR, I'd recommend dropping into one of the contributor meetings. https://github.com/argoproj/argoproj#contributing

Sorry I can't help you out this release cycle, I know you've put a lot of work into it!

**Comment by StepanKuksenko** [comment]
@mrmm you did a great job I hope you will find time to continue working on this PR to finally deliver the feature

**Comment by Gitopolis** [comment]
This would work nicely with image updater annotations. Currently we have to hardcode all the annotation keys, which deprives us the flexibility of image lists and update strategies

**Comment by blakepettersson** [comment]
I think this will be superceded with #14893?

**Comment by mrmm** [comment]
For everyone watching this PR, due to personal circumstances I was not able to finish up this feature so sorry 🙏.
Thanks @crenshaw-dev for all the help during this PR and hopefully my next PR to go to fulfillment 👌

**Comment by crenshaw-dev** [comment]
@mrmm thank you for all your effort on this! We'll get some version of it merged sooner or later. 🙂

**Pull request closed without merging**
