### PR TITLE
fix(ui): Add namespace in badge-url for apps in any namespace

### LINKED ISSUE #15655: UI: badges url not containing namespace with "Applications in any namespace"
**Describe the bug**

The badge url generated under "**App Details**" view does not include the "**&namespace=**" parameter when using the "**Applications in any namespace**" setup with ArgoCD.

Badge "Not Found" label is shown when app is deployed to other namespace than the default "argocd".

PS. 
Backend part was fixed by issue https://github.com/argoproj/argo-cd/issues/15351.
This added the support for "**&namespace=**" parameter in badge url.

**To Reproduce**

1. Configure "Applications in any namespace":
    - Set ArgoCD tracking method to **annotation+label**.
    - Add RBAC **ClusterRole + ClusterRoleBinding**

2. Deploy application to namespace other than argocd.

   Example: **testnamespace/app1**

    ```
    kind: Application
    metadata:
        name: app1
        namespace: testnamespace
    ```

3. Check the generated badge url in UI under "**App Details**" view.\
It still shows "Not Found" because **&namespace=** parameteri is not included in the url.

**Expected behavior**

Generated working url should be:
```
<argocd_base_url>/api/badge?name=app1&namespace=testnamespace&revision=true
```

**Version**

v2.8.4

### PR DESCRIPTION
**Pull request by sonamkshenoy**
Fixes #15655

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @sonamkshenoy!

**Review by crenshaw-dev — DISMISSED** [review]
Hm, looks like the rebase got messed up

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Pull request merged**
