### PR TITLE
feat: Adding author/creator as a template key for Pull Request Generator

### PR DESCRIPTION
**Pull request by vfaergestad**
Fixes [ISSUE #18826].

Adding an ´author´ template key for the pull request generator. This is retrieved from the SCM api together with the other template keys.  This makes it possible to reference the author of an pull-request in the generator-template, for example in the image tag.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by vfaergestad** [comment]
The tests that fials are the e2e integration-tests. They error while waiting for an application. Not sure how to fix this.
```
=== FAIL: test/e2e TestMergeTerminalMergeGeneratorSelector (32.18s)
time="2024-07-09T14:53:01Z" level=info msg="mkdir -p /tmp/applicationset-e2e" dir= execID=f1fe6
time="2024-07-09T14:53:01Z" level=debug duration=1.643737ms execID=f1fe6
time="2024-07-09T14:53:02Z" level=info msg="clean state" duration=1.130094059s id= name=TestMergeTerminalMergeGeneratorSelector *** username=admin
time="2024-07-09T14:53:03Z" level=info msg="action: creating ApplicationSet '/merge-generator-nested-merge'"
time="2024-07-09T14:53:03Z" level=info msg="expectation succeeded: no error and output contained ''"
time="2024-07-09T14:53:03Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:06Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:09Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:12Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:15Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:18Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:21Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:24Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:27Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
time="2024-07-09T14:53:30Z" level=info msg="expectation pending: missing app 'argocd-e2e/kustomize-guestbook-1'"
    consequences.go:26: timeout waiting for: missing app 'argocd-e2e/kustomize-guestbook-1'
```

**Comment by vfaergestad** [comment]
Other then that, I think this PR is ready for review. Atleast ready for some critique of the PR itself, all comments are welcome.

**Comment by ggjulio** [comment]
@vfaergestad  for e2e failing please look at the PR #17907 for files to update, they are similar.

Btw @agaudreault, I saw you updated some files I rebased to fix conflicts, any way I could get a review of #17907 ?

**Comment by vfaergestad** [comment]
All test are now successful, and the PR is ready for review.

**Review by agaudreault — APPROVED** [review]
LGTM!

**Review by ishitasequeira — CHANGES_REQUESTED** [review]
The changes LGTM. 
@vfaergestad the commit history looks messed up. Could you try to fix that?

**Review by ishitasequeira — APPROVED** [review]

**Comment by vfaergestad** [comment]
@ishitasequeira Good point! I cleaned it up now.

**Comment by ggjulio** [comment]
Hey @vfaergestad , there is an issue with the number of files changed.
Wrong master ? (`origin/master` vs `upstream/master`)

```
git remote add upstream https://github.com/argoproj/argo-cd.git`
git checkout master # origin master
git rebase upstream/master
```

**Comment by vfaergestad** [comment]
Thank you for the notice @ggjulio . I did not release I had made that error. Thank you for your patience, I learn something new everyday.

I believe I have fixed it now. Let me know if there is anything else.

**Review by ishitasequeira — APPROVED** [review]

**Pull request merged**
