### PR TITLE
chore(deps): upgrade `argo-ui`, including breaking changes

### LINKED ISSUE #16745: UI error message layout issue
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
Error message popup cannot be displayed properly

**To Reproduce**

1. At project level, add new role
2. Grant "get" to all resources under the related app
3. Project --> edit --> save

**Expected behavior**
Error message should be displayed properly, at least all the text should be visible

**Screenshots**
image

**Version**
appVersion: v2.9.3
```shell

argocd: v2.5.1+504da42.dirty
  BuildDate: 2022-11-02T01:24:38Z
  GitCommit: 504da424c2c9bb91d7fb2ebf3ae72162e7a5a5be
  GitTreeState: dirty
  GoVersion: go1.19.3
  Compiler: gc
  Platform: darwin/amd64
WARN[0002] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web. 
argocd-server: v2.9.3+6eba5be
  BuildDate: 2023-12-01T23:05:50Z
  GitCommit: 6eba5be864b7e031871ed7698f5233336dfe75c7
  GitTreeState: clean
  GoVersion: go1.21.3
  Compiler: gc
  Platform: linux/arm64
  Kustomize Version: v5.2.1 2023-10-19T20:13:51Z
  Helm Version: v3.13.2+g2a2fb3b
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.20.0
```

**Logs**

```

```

### PR DESCRIPTION
**Pull request by agilgur5**
### Motivation

As requested in https://github.com/argoproj/argo-ui/pull/535#pullrequestreview-2255320205
Upgrade to the latest version of `argo-ui`, resolve breakage, and fix a bug in CD via the upgrade

### Modifications

- upgrade to https://github.com/argoproj/argo-ui/tree/a7b01f9f009aa9161da21f450b5aab2f0732eb74

- Per https://github.com/argoproj/argo-ui/pull/535, `moment` is no longer used internally by `argo-ui`, so change `Ticker` usage to account for this
  - CD should also remove the `moment` library for as it is deprecated. see also the downstream PR and Workflows PRs (https://github.com/argoproj/argo-workflows/pull/12097, https://github.com/argoproj/argo-workflows/pull/12611)
  
- Per https://github.com/argoproj/argo-ui/pull/577, the `Duration` component had an erroneously named `durationMs` prop, which has now been changed to `durationS`
  
Fixes #16745 via https://github.com/argoproj/argo-ui/pull/546, which is included in this upgrade

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [n/a] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [no] Does this PR require documentation updates?
* [n/a] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [n/a] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [n/a] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [n/a] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by agilgur5** [comment]
Ah [type-checking failed](https://github.com/argoproj/argo-cd/actions/runs/10516846738/job/29139870127?pr=19655) as I appear to have forgotten to make `durationS` / `durationMs` optional in the types upstream, woops:

```
yarn run v1.22.22
$ tsc --noEmit --project ./src/app && eslint
Error: src/app/applications/components/application-deployment-history/application-deployment-history.tsx(43,56): error TS2[7](https://github.com/argoproj/argo-cd/actions/runs/10516846738/job/29139870127?pr=19655#step:7:8)41: Property 'durationS' is missing in type '{ durationMs: number; }' but required in type '{ durationMs: number; durationS: number; }'.
Error: src/app/applications/components/application-deployment-history/application-deployment-history.tsx(55,30): error TS2741: Property 'durationS' is missing in type '{ durationMs: number; }' but required in type '{ durationMs: number; durationS: number; }'.
Error: src/app/applications/components/application-operation-state/application-operation-state.tsx(63,31): error TS2741: Property 'durationS' is missing in type '{ durationMs: number; }' but required in type '{ durationMs: number; durationS: number; }'.
```

I'll push a workaround here, but should also fix those types there. Unfortunately can't quite do "one of" in TS though

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Everything looks good except maybe the sync operation panel. Looks like the duration is missing there. 
image

lmk if you want to test in the Bunnyshell instance, I can send you the credentials.

**Comment by agilgur5** [comment]
Huh since it already finished, that should've actually short-circuited the changed code here 🤔



> lmk if you want to test in the Bunnyshell instance, I can send you the credentials

Yea that would be helpful!

**Comment by agilgur5** [comment]
> Everything looks good except maybe the sync operation panel. Looks like the duration is missing there.

Oh, this is an edge case: it's a 0 second duration apparently. I suppose that's a bug in my refactor; the previous logic did handle 0 on [this line](https://github.com/argoproj/argo-ui/pull/535/files#diff-1091e5e3ad42ccca0ca1091ad66302c1a1c1c3969d759a56e4c8e45c53d23954L10), although not sure if it intentionally handled that 😅 

I'll add that to the `Duration` component fixes in https://github.com/argoproj/argo-ui/pull/577 then

**Comment by agilgur5** [comment]
No wait, the new logic (or well, newly switched to logic, the logic is still old) handles the `0` case [as well](https://github.com/argoproj/argo-ui/blob/e76346fdd7f26f596e9bec4404fe251a5449bbf1/v2/utils/utils.tsx#L109). 🤔

**Comment by agilgur5** [comment]
Oh, I think this will be fixed by https://github.com/argoproj/argo-ui/pull/577 as well, the `0` edge case causes the parameter into `formatDuration` to be a little wacky due to the backward-compatible `||`:

```
❯ node
Welcome to Node.js v20.6.0.
Type ".help" for more information.
> 0 || undefined
undefined
> 0 || null
null
> 0 || 0
0
```

**Comment by agilgur5** [comment]
Now that https://github.com/argoproj/argo-ui/pull/577 has been merged, I've updated the code here as well

**Comment by crenshaw-dev** [comment]
> ### 🔴 Preview Environment stopped on [Bunnyshell](https://www.bunnyshell.com)
> See: [Environment Details](https://environments.bunnyshell.com/b/environment/omXj2GJXNn) | [Pipeline Logs](https://environments.bunnyshell.com/b/pipeline/dV6Znxay6N)
> 
> Available commands (reply to this comment):
> 
> * 🔵 `/bns:start` to start the environment
> * 🚀 `/bns:deploy` to redeploy the environment
> * ❌ `/bns:delete` to remove the environment

/bns:deploy

**Review by crenshaw-dev — APPROVED** [review]
Local test checks out, thanks!

**Pull request merged**
