### PR TITLE
feat: added wildcard to match top level group for namespaceResourceWhitelist

### LINKED ISSUE #4914: Enable wildcard for *ResourceWhitelist/Blacklist
# Summary

Enable wildcard for *ResourceWhitelist/Blacklist

# Motivation

Today I let my different application teams sync on specific AppProjects where i define namespaceResourceWhitelist & Blacklist.

But it's kind of a pain to manage. For example I use tekton in my cluster and as you can see bellow it have a few crd:s and thus a rather big number of groups.

```
kubectl get crd |grep tekto
clustertasks.tekton.dev                                     2020-11-18T14:14:23Z
clustertriggerbindings.triggers.tekton.dev                  2020-11-18T14:14:57Z
conditions.tekton.dev                                       2020-11-18T14:14:23Z
config.operator.tekton.dev                                  2020-11-18T14:13:54Z
eventlisteners.triggers.tekton.dev                          2020-11-18T14:14:57Z
pipelineresources.tekton.dev                                2020-11-18T14:14:24Z
pipelineruns.tekton.dev                                     2020-11-18T14:14:24Z
pipelines.tekton.dev                                        2020-11-18T14:14:24Z
runs.tekton.dev                                             2020-11-18T14:14:24Z
taskruns.tekton.dev                                         2020-11-18T14:14:24Z
tasks.tekton.dev                                            2020-11-18T14:14:24Z
triggerbindings.triggers.tekton.dev                         2020-11-18T14:14:57Z
triggers.triggers.tekton.dev                                2020-11-18T14:14:57Z
triggertemplates.triggers.tekton.dev                        2020-11-18T14:14:57Z
````

I would have to do something like:
````
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: 'tekton.dev'
    kind: '*'
  - group: 'triggers.tekton.dev'
    kind: '*'
... etc
````

# Proposal

Enable wildcards on groups.
So i can do something like:
````
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-project
  namespace: argocd
spec:
  namespaceResourceWhitelist:
  - group: '*.tekton.dev'
    kind: '*'
````
**Notice * in-front of .tekton.dev**

I know this will potentially issues since we are not being as specific but I think the bad parts/risks will be outweighs by the administrative work being saved.

### PR DESCRIPTION
**Pull request by shubhamagarwal19**
Signed-off-by: Shubham Agarwal <shubhamagarawal19@gmail.com>
fixes #4914 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
@jannfis can I ask for review please? PR looks good to me, according to  https://github.com/argoproj/argo-cd/issues/4914#issuecomment-779654543 but want to double-check

**Review by alexmt — APPROVED** [review]
LGTM

**Review by jannfis — CHANGES_REQUESTED** [review]
I think two things need to be resolved here:
1. Documentation
2. I believe that with the logic introduced here, further wildcards will not be allowed (e.g. `**.tekton.*`). Is that what we want? If yes, needs to be documented as well.

**Comment by crenshaw-dev** [comment]
Closing for now. Feel free to reopen, or if someone wants to pick it up, open a new PR based on this one.

**Pull request closed without merging**
