### PR TITLE
Add support for dex prometheus metrics

### PR DESCRIPTION
**Pull request by bclermont**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Once next release of argocd is out, I will create a PR for helm chart and expose that metric

### CODE REVIEW

**Comment by bclermont** [comment]
I fixed commit msg to be semantic release. can someone review this?

**Comment by jannfis** [comment]
Hi @bclermont, the CI is failing at the codegen step. Did you run `make codegen` before pushing your changes, or have you updated installation manifests manually?

**Comment by bclermont** [comment]
ran `codegen` and rebase on master

**Comment by bclermont** [comment]
fixed testunit assert

**Comment by bclermont** [comment]
This time the test failed and I feel it's unrelated to my change.
But the thing is `master` build passed just before I rebased

**Comment by bclermont** [comment]
@jannfis 

there was a conflict with generated file, rebased

**Review by alexmt — APPROVED** [review]

**Pull request merged**
