### PR TITLE
docs: --app-resync flag is in docs even though it's deprecated

### PR DESCRIPTION
**Pull request by TheSwarnim**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

This pr removes the --app-resync as an option from the [documentation](https://argo-cd.readthedocs.io/en/stable/operator-manual/server-commands/argocd-application-controller/) which has been deprecated in the newer version of argocd. It is the sub task of the issue #13265

Closes #13265

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
Thanks, @TheSwarnim!

I'd like to suggest some changes:

1) Instead of deleting the option from docs, just update the CLI code to add something like `(DEPRECATED: use timeout.Reconciliation instead)` to the CLI flag description.
2) Run `make clidocsgen` to update all the docs to reflect the change
3) Open a new issue something like "Remove `--app-resync` option," and I'll add it to the 3.0 milestone.

**Review by csantanapr — APPROVED** [review]

**Comment by csantanapr** [comment]
This would be useful to address. please follow @crenshaw-dev suggestion on how to proceed with this PR

**Comment by TheSwarnim** [comment]
Thanks, @crenshaw-dev. 
Will update pr as per you suggested

**Comment by TheSwarnim** [comment]
Hey @crenshaw-dev/ @csantanapr,
I've updated the pr as per your suggestions. Please review this
I've also raised a new issue #14267 to remove this flag

**Pull request closed without merging**
