### PR TITLE
fix: cache helm-index in Redis cluster (#12314)

### LINKED ISSUE #12314: ArgoCD start to DDoS related Helm Repository
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Our ArgoCD Application start to DDoS our Helm Repositories.

For our deployment we use gitops, which uses an app of apps approach to create nearly 64 different ArgoCD Applications. For our gitops we have multiple branches and do multiple deployments on same argocd environment in one AWS EKS Cluster.

We have 32 Deployments means 2048 ArgoCD Applications based on same helm repository + 32 Argo CD Application running as app of apps over gitops.

**To Reproduce**

1. Configure a Gitops Repository with a set of ArgoCD Applications using same Helm Chart Repository and a sync policy of 1 minute.
1. Greate multiple of this ArgoCD Applications by using gitops. 
1. Check access log on Helm Chart Repository (I use jFrog Artifactory), for calls to `index.yaml` File.

**Expected behavior**

After ArgoCD calls always the same `index.yaml` File in the Helm Chart Repository I would expect that it is cached in ArgoCD and used as shared resource between ArgoCD Applications. Not that every single ArgoCD Application calls the index.yaml File itself.

Our `index.yaml` has 20.26 MB x 2048 ArgoCD Applications calling one time per Hour for 12 hours. That makes 20.26 MB x 2048 x 12 = 497.909,76 MB ~= 486,24 GB per Day.

That is what we also see from our access logs in our Helm Repository.

Our expectation is 20,26 MB x 24 x 60 to check file onces per minute which should result in 28,49 GB per day, so that file is cached centrally.

**Version**

```shell
argocd: v2.6.0+acc554f
  BuildDate: 2023-02-06T21:44:18Z
  GitCommit: acc554f3d99010e0353b498a595844b30090556f
  GitTreeState: clean
  GoVersion: go1.18.10
  Compiler: gc
  Platform: linux/amd64
Handling connection for 8081
Handling connection for 8081
argocd-server: v2.5.6+9db2c94
  BuildDate: 2023-01-10T19:30:17Z
  GitCommit: 9db2c9471f6ff599c3f630b446e940d3a065620b
  GitTreeState: clean
  GoVersion: go1.18.9
  Compiler: gc
  Platform: linux/amd64
  Kustomize Version: v4.5.7 2022-08-02T16:35:54Z
  Helm Version: v3.10.3+g835b733
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.18.0
```

### PR DESCRIPTION
**Pull request by jenting**
Fixes #12314 that use the Redis cluster as the helm index.yaml cache as well.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by todaywasawesome — COMMENTED** [review]
Needs some testing but looks good. I'll try to run through it.

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Review by jannfis — APPROVED** [review]
LGTM, thanks!

**Review by wanghong230 — APPROVED** [review]

**Review by christianh814 — APPROVED** [review]

**Comment by jenting** [comment]
@crenshaw-dev PTAL

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Comment by ericblackburn** [comment]
I think we are hitting this. What release is this being placed in? Was this cherry picked to older versions?

**Comment by ericblackburn** [comment]
I see the change in the [2.13 branch](https://github.com/argoproj/argo-cd/blob/release-2.13/reposerver/repository/repository.go#L2511) but not the [2.12 release branch](https://github.com/argoproj/argo-cd/blob/temp-cherry-pick-02c5e3-release-2.12/reposerver/repository/repository.go#L2467). It would be nice to cherry pick that into 2.12.

**Pull request merged**
