### PR TITLE
fix(ui): Unscrollable error message when saving YAML (#4152)

### LINKED ISSUE #4152: Error message truncated in UI when it is very long
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a
question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

The error box is huge and yet nowhere near big enough to actually read the error. And it doesn't scroll well.

**To Reproduce**

1. Navigate argocd to a pod
1. Click the pod
1. Click Edit in the Live Manifest
1. Go to `spec:` > `containers:` > `env:`
1. Add or otherwise change the environment
1. Click save 

**Expected behavior**

1. Ideally if you know my changes aren't valid, don't let me try to save them
1. The view should scroll wrap/something so I can read the content, it doesn't -- I have to select all and copy to a text editor to read it.

**Screenshots**

image

> Unable to save changes: Pod "github-runner-76cff478cd-8bfqg" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)   

**Version**

v1.6.1+159674e

**Logs**

### LINKED ISSUE #5221: Error message truncated in UI when it is very long
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Error message could get truncated in UI when it is too long

**To Reproduce**

Generate a very long error message

**Expected behavior**

Show the complete error message or at least the reason part.

```
failed exit status 1: Error: render error in \"static-site/templates/configmaps.yaml\": template: static-site/templates/configmaps.yaml:55:167:
  executing \"static-site/templates/configmaps.yaml\" at <.Values.prefix>: wrong type for value; expected string; got interface {}
```

**Screenshots**

Screen Shot 2021-01-11 at 5 03 10 PM

Only the command part is visible and it is not as helpful as the error reason followed.

**Version**

```shell
❯ argocd version
argocd: v1.8.1+c2547dc.dirty
  BuildDate: 2020-12-10T05:00:12Z
  GitCommit: c2547dca95437fdbb4d1e984b0592e6b9110d37f
  GitTreeState: dirty
  GoVersion: go1.15.5
  Compiler: gc
  Platform: darwin/amd64
argocd-server: v1.9.0+7613d9a
  BuildDate: 2021-01-11T03:10:33Z
  GitCommit: 7613d9a85295e15fcbaf0b5f6ba9ed69a74a0919
  GitTreeState: clean
  GoVersion: go1.14.12
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.8.7 2020-11-11T23:14:14Z
  Helm Version: v3.4.1+gc4e7485
  Kubectl Version: v1.17.8
  Jsonnet Version: v0.17.0
```

**Logs**

```
 time="2021-01-11T09:02:30Z" level=error msg="finished unary call with code Unknown" error="Manifest generation error (cached): `helm2 template . --name ui-auditor --n  amespace ui --kube-version 1.13 --set staticFilesSourcePath=s3://humanloop2-test/ --values values.yaml --values dev.values.yaml --api-versions v1 --api-versions apire
 gistration.k8s.io/v1 --api-versions apiregistration.k8s.io/v1beta1 --api-versions extensions/v1beta1 --api-versions apps/v1 --api-versions apps/v1beta2 --api-versions apps/v  1beta1 --api-versions events.k8s.io/v1beta1 --api-versions authentication.k8s.io/v1 --api-versions authentication.k8s.io/v1beta1 --api-versions authorization.k8s.io/v1 --api
 -versions authorization.k8s.io/v1beta1 --api-versions autoscaling/v1 --api-versions autoscaling/v2beta1 --api-versions autoscaling/v2beta2 --api-versions batch/v1 --api-vers  ions batch/v1beta1 --api-versions certificates.k8s.io/v1beta1 --api-versions networking.k8s.io/v1 --api-versions policy/v1beta1 --api-versions rbac.authorization.k8s.io/v1 -
 -api-versions rbac.authorization.k8s.io/v1beta1 --api-versions storage.k8s.io/v1 --api-versions storage.k8s.io/v1beta1 --api-versions admissionregistration.k8s.io/v1beta1 --
 api-versions apiextensions.k8s.io/v1beta1 --api-versions scheduling.k8s.io/v1beta1 --api-versions coordination.k8s.io/v1beta1 --api-versions mutators.kubedb.com/v1alpha1 --a
 pi-versions validators.kubedb.com/v1alpha1 --api-versions packages.operators.coreos.com/v1 --api-versions acme.cert-manager.io/v1 --api-versions cert-manager.io/v1 --api-ver
 sions getambassador.io/v2 --api-versions getambassador.io/v1 --api-versions getambassador.io/v1beta2 --api-versions getambassador.io/v1beta1 --api-versions jaegertracing.io/
 v1 --api-versions monitoring.coreos.com/v1 --api-versions nvidia.com/v1 --api-versions operators.coreos.com/v1 --api-versions operators.coreos.com/v1alpha2 --api-versions op
 erators.coreos.com/v1alpha1 --api-versions appcatalog.appscode.com/v1alpha1 --api-versions argoproj.io/v1alpha1 --api-versions caching.internal.knative.dev/v1alpha1 --api-ve
 rsions catalog.kubedb.com/v1alpha1 --api-versions dashboard.tekton.dev/v1alpha1 --api-versions kubedb.com/v1alpha1 --api-versions tekton.dev/v1alpha1 --api-versions metrics.
 k8s.io/v1beta1` failed exit status 1: Error: render error in \"static-site/templates/configmaps.yaml\": template: static-site/templates/configmaps.yaml:55:167:
  executing \"static-site/templates/configmaps.yaml\" at <.Values.prefix>: wrong type for value; expected string; got interface {}" grpc.code=Unknown grpc.method=Gener
 ateManifest grpc.request.deadline="2021-01-11T09:03:30Z" grpc.service=repository.RepoServerService grpc.start_time="2021-01-11T09:02:30Z" grpc.time_ms=1.18 span.kind=server
 system=grpc
```

### PR DESCRIPTION
**Pull request by rbreeze**
Closes #4152

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by RichiCoder1** [comment]
Considering it's possible that this error could contain actionable or verbose info, would it be possible to move this information out of a notification and put it inline? Maybe in a collapsable, with the notification just being a more present indicator that something failed and link to the div containing error information

**Comment by rbreeze** [comment]
@RichiCoder1 This issue made me think of this as well. I think some of the error messaging could benefit from a better design.

**Comment by RichiCoder1** [comment]
@rbreeze Currently spinning up a local dev env (and attempting to recruit my UX Designer BF) so I can assist with that. I think for this specifically there's a easy fix, I'll see if I can throw together an example or design.

**Review by jsoref — APPROVED** [review]
rubber stamp 💮

**Comment by crenshaw-dev** [comment]
@rbreeze can you fix DCO on this?

**Review by alexmt — CHANGES_REQUESTED** [review]
Can you please attach a screenshot?

**Comment by pasha-codefresh** [comment]
After fix : 
Снимок экрана 2022-04-29 в 19 52 38

Before: 
Снимок экрана 2022-04-29 в 19 54 44
And not scroll

Actually i like this improvement, but also would be nice apply it to all error notifications, maybe wrap in some component

**Review by pasha-codefresh — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]
lgtm!

**Review by alexmt — APPROVED** [review]

**Pull request merged**
