### PR TITLE
fix: trigger refresh on changed ignoreDifferences

### LINKED ISSUE #12610: ignoreDifferences is not automatically refreshed.
Checklist:

* [X] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [X] I've included steps to reproduce the bug.
* [X] I've pasted the output of `argocd version`.

**Describe the bug**
When applying a helm chart that only contains CRDs, it will show OutOfSync due to a diff in the manifests.
When I add the `ignoreDifferences` to ignore that mismatch, and hit `Sync`, the application still shows as OutOfSync, until I click refresh.

**To Reproduce**
Create a new App via UI. Click `Edit as YAML`. Paste this code:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-test-app
spec:
  destination:
    namespace: test-crds
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://helm.linkerd.io/stable'
    targetRevision: 1.4.0
    chart: linkerd-crds
  project: cluster-infra
  syncPolicy:
    automated: null
    syncOptions:
      - CreateNamespace=true
```
Then Save, Create, and Sync.
After sync, everything will be OutOfSync. Click on refresh, and a few of them become in Sync. (Also a bug here)

If you inspect the diff, you should see only this:
image

Now go to App Details -> Manifest and click EDIT. Right in the end, paste this:
```
ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/names/shortNames
```
Hit Save, close it and sync.
The application will still be OutOfSync.
Clicking refresh will make mark it as synced.

**Expected behavior**

After setting `ignoreDifferences` I'd expect the refresh to be automatic.

**Screenshots**
Screen Recording 2023-02-24 at 3 02 19 PM (1)

**Version**
Please note the version below seems incorrect. See screenshot:
image

```shell
argocd version
argocd: v2.6.2+6e02f8b.dirty
  BuildDate: 2023-02-16T18:43:27Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: darwin/arm64
argocd-server: v2.6.2+6e02f8b.dirty
  BuildDate: 2023-02-16T18:43:27Z
  GitCommit: 6e02f8b23201b0620a4ff1bce5d38229ba1eb02e
  GitTreeState: dirty
  GoVersion: go1.19.6
  Compiler: gc
  Platform: darwin/arm64
  Kustomize Version: v4.5.7 2022-08-02T16:28:01Z
  Helm Version: v3.10.0+gce66412
  Kubectl Version: v0.24.2
  Jsonnet Version: v0.19.1
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by crenshaw-dev**
Fixes https://github.com/argoproj/argo-cd/issues/12610

Tested locally and confirmed I can't reproduce the reported issue.

### CODE REVIEW

**Comment by jannfis** [comment]
Because this PR contains a CRD change, I'm not sure whether we should cherry-pick it except for the upcoming 2.7 release.

Personally, I would expect patch releases not to touch any CRDs or deployment manifests (with certain exceptions).

**Comment by crenshaw-dev** [comment]
@jannfis agreed, dropped the cherry-pick comments. LGTY otherwise?

**Review by jannfis — APPROVED** [review]
LGTM!

**Pull request merged**
