### PR TITLE
FIX /usr/local/bin directory require sudo

### PR DESCRIPTION
**Pull request by timactive**
without sudo command
``curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/download/$VERSION/argocd-linux-amd64``
 curl: (23) Failed writing body (0 != 16360)

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by jannfis** [comment]
Thanks for your submission, @timactive! You are correct that the commands in the docs would not work as non-root user. 

However, I think we should not run `curl` via `sudo`, but rather instruct the user to do something like the following:

```bash
curl https://.../argocd-linux-amd64
sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
```

What do you think about that? Would you update your PR for these instructions rather? Thanks!

**Review by jannfis — CHANGES_REQUESTED** [review]
Thanks for your submission, @timactive! You are correct that the commands in the docs would not work as non-root user. 

However, I think we should not run `curl` via `sudo`, but rather instruct the user to do something like the following:

```bash
curl https://.../argocd-linux-amd64
sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
```

What do you think about that? Would you update your PR for these instructions rather? Thanks!

**Comment by sbose78** [comment]
Hi @timactive, would you be willing to pursue this ?

**Comment by pasha-codefresh** [comment]
@timactive are going to work on this? i think this is good PR , you just need add changes that Jan has asked, otherwise I will deliver this

**Comment by crenshaw-dev** [comment]
Closing in favor of https://github.com/argoproj/argo-cd/pull/9944

**Pull request closed without merging**
