### PR TITLE
chore: Reused argo define api Kind and Group

### PR DESCRIPTION
**Pull request by yanggangtony**
Signed-off-by: yanggang <gang.yang@daocloud.io>

Replaced by argo's const Kind and Group parm.

### CODE REVIEW

**Comment by yanggangtony** [comment]
This pr have been a time for review.
Would you have time to review it?
@crenshaw-dev @jannfis @rbreeze

**Review by blakepettersson — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @yanggangtony!

**Comment by crenshaw-dev** [comment]
@yanggangtony would you mind resolving conflicts?

**Comment by yanggangtony** [comment]
> @yanggangtony would you mind resolving conflicts?

thanks for review.
rebased it.

**Pull request merged**
