### PR TITLE
chore: add skaffold dev configuration

### PR DESCRIPTION
**Pull request by blakepettersson**
This adds a Skaffold configuration for quickly standing up an Argo CD for development purposes.

Signed-off-by: Blake Pettersson <blake.pettersson@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* ~[ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* ~[ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by drpaneas — CHANGES_REQUESTED** [review]
I've tested it out and it works great. However, I did run into one small issue. It seems that the `argocd` namespace needs to be created before running Skaffold. 

```
#41 DONE 2.7s
Build [quay.io/argoproj/argocd] succeeded
Tags used in deployment:
 - quay.io/argoproj/argocd -> quay.io/argoproj/argocd:d137b2680f58f7794c3aad39421cd62f49e55fe5ec3cf3e033f954d0be7c3924
Starting deploy...
Loading images into kind cluster nodes...
 - quay.io/argoproj/argocd:d137b2680f58f7794c3aad39421cd62f49e55fe5ec3cf3e033f954d0be7c3924 -> Loaded
Images loaded in 26.848 seconds
 - customresourcedefinition.apiextensions.k8s.io/applications.argoproj.io created
 - customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io created
 - customresourcedefinition.apiextensions.k8s.io/appprojects.argoproj.io created
 - clusterrole.rbac.authorization.k8s.io/argocd-application-controller created
 - clusterrolebinding.rbac.authorization.k8s.io/argocd-application-controller created
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
 - Error from server (NotFound): error when creating "STDIN": namespaces "argocd" not found
Cleaning up...
 - customresourcedefinition.apiextensions.k8s.io "applications.argoproj.io" deleted
 - customresourcedefinition.apiextensions.k8s.io "applicationsets.argoproj.io" deleted
 - customresourcedefinition.apiextensions.k8s.io "appprojects.argoproj.io" deleted
 - clusterrole.rbac.authorization.k8s.io "argocd-application-controller" deleted
 - clusterrolebinding.rbac.authorization.k8s.io "argocd-application-controller" deleted
kubectl apply: exit status 1
```

To make things even easier, you could either add this information to the documentation or include the creation of the argocd namespace as part of the Skaffold configuration.

Overall, this is fantastic work and I'm excited to see this get merged in. Great job!

**Comment by blakepettersson** [comment]
@drpaneas I added a `make skaffold` task which creates the `argocd` if it doesn't already exist? WDYT?

**Comment by drpaneas** [comment]
> @drpaneas I added a `make skaffold` task which creates the `argocd` if it doesn't already exist, WDYT?

Good thinking. The next step would be to automate the installation of Skaffold as a binary, but I don't think this is required for this PR. It's already good enough in my opinion.

**Review by drpaneas — APPROVED** [review]
/lgtm

**Comment by drpaneas** [comment]
@blakepettersson is there anything else needed here or can we merge? I like using this workflow and I think others will benefit as well. It's not breaking anything (no regressions) just adding additional (ease) functionality.

**Pull request closed without merging**
