### PR TITLE
fix: application details panel page background color in dark theme

### PR DESCRIPTION
**Pull request by shijiadong2022**
Fix (https://github.com/argoproj/argo-cd/issues/19094) and (https://github.com/argoproj/argo-cd/issues/18742)

### CODE REVIEW

**Comment by shijiadong2022** [comment]
per https://github.com/argoproj/argo-cd/issues/18742
before change
image
after change
image

**Comment by shijiadong2022** [comment]
@wanghong230 @christianh814 when you get a chance wonder if you could help review this PR? Many thanks for your help in advance.

**Review by ishitasequeira — APPROVED** [review]
LGTM

**Review by christianh814 — COMMENTED** [review]
Awesome thanks!

**Pull request merged**
