### PR TITLE
chore: update yarn to node container's version

### LINKED ISSUE #12951: test-container build uses wrong yarn version
**Describe the bug**

The update to the latest node LTS (https://github.com/argoproj/argo-cd/pull/12779) container seems to have broken the test container build, since the container provides yarn v1.22.19 but the dockerfile searches for v1.22.4.

**To Reproduce**

Checkout the mainline and try to build with "make build".

### PR DESCRIPTION
**Pull request by Roshick**
Fixes https://github.com/argoproj/argo-cd/issues/12951

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
Would you mind adding a comment above the node image tag noting that when it’s updated we should also update the yarn version?

**Comment by Roshick** [comment]
sure thing!

**Comment by Roshick** [comment]
done

**Review by crenshaw-dev — APPROVED** [review]
Thanks, @Roshick!

**Pull request merged**
