### PR TITLE
moved (un)install to argocd-util

### LINKED ISSUE #254: Remove `argocd (un)install` into argocd-util
Because they require direct access to Kubernetes, these commands should not be in `argocd`, but rather `argocd-util`.

### PR DESCRIPTION
**Pull request by JazminElkan-Gonzalez**
This resolves #254 

(moved commands and updated getting started docs)

Am wondering about the user experience since this will mean needing to change anything set to argocd install to argocd-util install. since this is prerelease for open source is there any further communication we need to make externally? internally?

### CODE REVIEW

**Comment by JazminGonzalez-Rivero** [comment]
@jessesuen added you as a reviewer since Andrew is still out.

**Comment by jessesuen** [comment]
I think there is an option 4 here...

------
4. `kubectl apply -f`. 

We remove installer/uninstaller. Upon startup, if the *API server* does not see `server.secretkey` in the argocd-secret, then it automatically generates it. As for the admin password, we will default to something like `password` or the pod name, which then will be encrypted using the `server.secretkey` which was just generated. We will have a convenient way to change the password via API/CLI/UI, but still have the ability to reset password and server.secretkey using `argocd-util` in case the password is forgotten.

I think the only downside is that part of install logic is baked into API server.

**Comment by alexmt** [comment]
I really like option 4. I think it is good practice to gracefully handle missing secrets/config maps (this would help to avoid issues like https://github.com/argoproj/argo-cd/issues/308 ).

**Comment by merenbach** [comment]
@alexmt @jessesuen @JazminGonzalez-Rivero just weighing in, a bit late to the party.  Wondering if a hybrid option is ideal?  Use `kubectl apply -f`, like in options 3 and 4, but don't autogenerate anything server-side in terms of passwords.

Instead, we could replace `./argocd install` with an `./argocd firstrun` command that requests, and sets, a username and password, along with server secret key, if any of these are unset, printing out all values.  If they are set, it could error out, but maybe shouldn't, so as to allow idempotency.

**Comment by jessesuen** [comment]
> we could replace ./argocd install with an ./argocd firstrun command that requests and/or generates any relevant settings, passwords, and secret keys

This is really not different than `install` other than name. And it wouldn't remove the dependency `argocd` would have on a kubeconfig, which was one of the big motivators of removing install.

**Comment by JazminGonzalez-Rivero** [comment]
@jessesuen ok sounds good, I'm also in favor of option 4, so I have begun investigating that implementation. 

for a bit of clarity... 

1) Question about usage: My only concern is this might open people up to a security vulnerability if they fail to change the default password, I was thinking of adding a warning that keeps popping up if they are still using the default password? I'm thinking this will show up whenever they boot up the API server? 

2) Question about uninstall: For uninstall I am thinking we will still want to add this to argocd-util since we would not want the namespace/Application-CRD to be deleted everytime the server went down. sounds good? 

3) To verify I am on the correct track, I am adding this new verification to `argocd-server` since that interfaces with `argo-cd/server` and from the procfile seems to be the boot up point for the server.

**Comment by JazminGonzalez-Rivero** [comment]
Just met with @jessesuen  and got some clarity on the questions above. I will proceed on this with the following prioritized goals. 

1) move namespace and CRD generation to be handled by kubectl apply -f  
-  move manifest directory so it is no longer under install (for customer clarity 
- uninstall will be handled by kubectl delete 

2) handle secret / password generation at server startup 
- use the pod name to create the password, this will make it more secure 

3) create API endpoint (profile?) backed by server that allows for overwriting the admin password 
- If we go with this model, this would also allow you to change the password of any other profile since admin will be treated like any other just with a special name

closing this PR since the work is no longer relevant

**Pull request closed without merging**
