### PR TITLE
feat: add git url cache to keep normalized git url

### PR DESCRIPTION
**Pull request by yeya24**
Signed-off-by: Ben Ye <ben.ye@bytedance.com>

Why is this needed?

same-url

From the profiling graph, you can find out that most of the time are spent on the `SameURL` function. Basically, it is calculating the normalized URL multiple times and there are duplications. Besides, the normalized url results are static so we can use a thread safe map to save them.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by yeya24** [comment]
This pr should be ready for review

**Comment by yeya24** [comment]
We are still seeing a lot of resource consumptions on the git url normalization process. @alexmt Any idea to push this pr forward?

**Comment by yeya24** [comment]
image
This is still a problem to us @alexmt

**Comment by alexmt** [comment]
hello @yeya24 ,

Which Argo CD version are you using? According to the stack in the screenshot it is v2.1. Can you try to upgrade to v2.2 to see if it resolves the problem?

**Comment by yeya24** [comment]
> hello @yeya24 ,
> 
> 
> 
> Which Argo CD version are you using? According to the stack in the screenshot it is v2.1. Can you try to upgrade to v2.2 to see if it resolves the problem?

This screenshot is taken from the latest 2.2.0 release and this is still an issue

**Comment by alexmt** [comment]
Hello @yeya24 ,

I just double-checked the v2.2.0 code (and published v2.2.0 image). In v2.2.0 the `getResourceTree` method does not call `argo.GetAppProject`, it calls `getAppProj` method. 

https://github.com/argoproj/argo-cd/blob/6da92a8e8103ce4145bb0fe2b7e952be79c9ff0a/controller/appcontroller.go#L372

The `getAppProj` caches project returned by `argo.GetAppProject` and significantly improve performance. In the attached screenshot the `getResourceTree` still calls `argo.GetAppProject` directly . This code exists only in pre v2.2 versions

https://github.com/argoproj/argo-cd/blob/2fdaf7a9add4ba6d6657d28dc32228419cb8b8f5/controller/appcontroller.go#L319

I hope I'm not missing something obvious

**Comment by yeya24** [comment]
@alexmt Thanks for checking! I think the image we are using is outdated. I updated the image and seems it is working now.

**Pull request closed without merging**
