### PR TITLE
fix: Summary Colors don't match key and numbers don't match colors #5200

### LINKED ISSUE #5200: Summary Colors don't match key and numbers don't match colors
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

1. The numbers in the summary column don't correspond to the pie slices of the two pies
2. The colors of the pie slices don't correspond to the keys for the pies

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications?view=summary

**Expected behavior**

1. If the summary numbers don't relate to the count of the items in the pies, then include numbers in the legends for the pies
2. the colors in the pies should correspond to the labels for the pies (specifically the second pie has black, and the labels for missing and unknown are both grew)
3. The colors for pie slices should be unique/distinct

**Screenshots**

image

**Version**

```shell
{
    "Version": "v1.9.0+eb9216f",
    "BuildDate": "2021-01-06T10:27:19Z",
    "GitCommit": "eb9216f8e15ca11f9d372312a675844974a43e48",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by ciiay**
Fixes: #5200 

Signed-off-by: ciiay <yicai@redhat.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by rbreeze — CHANGES_REQUESTED** [review]
I really like the new purple color. However, currently the Applications List displays the Health Status color for each app on the left: 

(Consistent Health Status colors:)
Screen Shot 2021-08-20 at 12 50 50 PM

(Inconsistent Health Status colors:)
Screen Shot 2021-08-20 at 12 50 39 PM


With this change, the colors no longer match. I'm in favor of changing the `Suspended` color to purple, but if we do it I think we should do it everywhere consistently.

**Comment by ciiay** [comment]
@rbreeze Good catch! I searched with "Suspended" in code and thought I covered everywhere but missed this one. I will make a PR against argo-ui repo to add this new suspended color.

I looked into the application-table component code, and I see we are applying both health status color and comparison status for the left border color. In the [style sheet](https://github.com/argoproj/argo-cd/blob/master/ui/src/app/applications/components/applications-list/applications-table.scss) it's missing style definition of `applications-list__entry--health-Suspended {}`, so the health status color is not applied. As you mentioned, the health status color is preferred to be used for the left border color, can I safely remove the `applications-list__entry--comparison-${app.status.sync.status}` class name? So that only health status color will matter for the left border.

Code reference: https://github.com/argoproj/argo-cd/blob/d12eafa8261df3178ce59bc52fa34954e50edeed/ui/src/app/applications/components/applications-list/applications-table.tsx#L42

**Review by alexmt — APPROVED** [review]
LGTM

**Review by rbreeze — APPROVED** [review]
LGTM

**Pull request merged**
