### PR TITLE
fix: Use math.MaxInt (instead of math.MaxInt64) to fix builds on 32bit platforms

### PR DESCRIPTION
**Pull request by ondrejsika**
Just a fix of the wrong type

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
Thanks, @ondrejsika! Can you fix the DCO check?

**Comment by chengfang** [comment]
There are other occurrences of `ParseNumFromEnv(MathInt64)`, besides what's already fixed in this PR. Are these also causing problem in 32bit platforms? Looks to me they should also be fixed.

https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-applicationset-controller/commands/applicationset_controller.go#L258

https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-server/commands/argocd_server.go#L243

https://github.com/argoproj/argo-cd/blob/master/cmd/argocd-application-controller/commands/argocd_application_controller.go#L192

**Comment by ondrejsika** [comment]
@crenshaw-dev DCO is fixed, i've also rebased on the master, but there is something broken :(

**Comment by ondrejsika** [comment]
@crenshaw-dev can u merge it, please?

**Pull request merged**
