### PR TITLE
docs: fixes the YAML codefence for `Slack` notification service #8776

### PR DESCRIPTION
**Pull request by omBratteng**
Signed-off-by: Ole-Martin Bratteng <1681525+omBratteng@users.noreply.github.com>

Fixes [#8776]

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by rishabh625 — APPROVED** [review]
LGTM

**Comment by omBratteng** [comment]
Noticed that the docs are copied from https://github.com/argoproj/notifications-engine, so I've created a [PR there](https://github.com/argoproj/notifications-engine/pull/80) to update the YAML.

**Review by pasha-codefresh — APPROVED** [review]
LGTM

**Comment by pasha-codefresh** [comment]
@omBratteng could you please fix pr checks?

**Comment by omBratteng** [comment]
@pasha-codefresh the PR checks that are failing, are because the step gets the markdown files from https://github.com/argoproj/notifications-engine, hence why I opened a PR https://github.com/argoproj/notifications-engine/pull/80 in that repo, which is needed before the failing check can be addressed.

**Comment by omBratteng** [comment]
I would've liked if the `overview` page from notifications-engine was at the top, but the code in https://github.com/argoproj/argo-cd/blob/master/hack/gen-docs/main.go prevents it

**Comment by pasha-codefresh** [comment]
Thank you

**Pull request merged**
