### PR TITLE
fix: upgrade to kustomize 4.2.0

### PR DESCRIPTION
**Pull request by jkroepke**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Motivation for this PR

To bundle multiple resource into one ArgoCD Application, I'm mainly use kustomize, import helm charts like (kube-prometheus-stack) with [HelmChartInflationGenerator](https://kubectl.docs.kubernetes.io/guides/extending_kustomize/builtins/#_helmchartinflationgenerator_) and enrich such release with additional resource like SealedSecret and oauth2-proxy.

kustomize 4.2.0 introduce the flag to import CRDs from helm charts. https://github.com/kubernetes-sigs/kustomize/pull/3898

I would like to use kustomize 4.2.0 to close the current gap with the CRD installation. Kustomize 4 is already present in the master, this change should not be consider as breaking change.

Workaround:

Provide kustomize 4.2.0 via [custom tooling](https://argo-cd.readthedocs.io/en/stable/operator-manual/custom_tools/).

### CODE REVIEW

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you for PR! Please update kustomize versions in one more file: https://github.com/argoproj/argo-cd/blob/master/hack/installers/install-codegen-tools.sh#L4

And minor merge conflict in upgrading instructions doc

**Comment by jkroepke** [comment]
PR rebased and install-codegen-tools.sh updated.

**Comment by jkroepke** [comment]
@alexmt About the final newline at the end of file, I would recommend an [.editorconfig](https://editorconfig.org/) file at the root of the project that defines if a final newline is wanted or not.

**Review by alexmt — APPROVED** [review]
LGTM.

Thank you @jkroepke . I agree about .editorconfig - it makes sense to add it.

**Pull request merged**
