### PR TITLE
Fix degraded proxy support for http(s) git repository (#2243)

### PR DESCRIPTION
**Pull request by mitsutaka**
Signed-off-by: Mitz Amano <mitz@linux.com>

Fix degraded proxy support for https(s) git repository. solves #2243

### CODE REVIEW

**Comment by mitsutaka** [comment]
I don't have yet idea how to implement e2e test for proxy/

**Review by jannfis — APPROVED** [review]
Thank you for this PR! The change looks good to me, and I also like the optimization in HTTP client settings.

Regarding the E2E tests: I guess this is a somewhat bigger operation. We'd have to integrate a HTTP proxy server into the `argo-cd-ci-builder` Docker image (@alexmt I'm struggling to find the Dockerfile for this, can you give us a pointer please?) started from `test/fixture/testrepos`, and then adapt/extend the tests and test fixtures in `test/e2e` so that we test at least one repository connection via the HTTP proxy.

However, from my point of view, this fix is small enough so it can be incorporated without an existing E2E test and we'll provide such a test later on, so that we can avoid regress in the future.

**Comment by mitsutaka** [comment]
Thank you for approval. I agree with you that the enhancement of the e2e test environment would spend more time.

**Review by alexec — APPROVED** [review]
I'll approve as @jannfis does not have perms.

**Pull request merged**
