### PR TITLE
fix: misc css fixes for mobile (#5705)

### LINKED ISSUE #5705: Mobile Friendly UI
# Summary

Right now, the UI doesn't display very well on mobile devices since it was designed for desktop usage.  Curious to see if there's enough interest in a Mobile friendly UI to warrant some design work/effort there, so opening this to gather interest since I didn't see another existing issue.

# Proposal

No idea yet, just interested in seeing if there's interest!

### PR DESCRIPTION
**Pull request by alexef**
noticed while browsing argo on my phone that a few elements could render differently to fit the screen

fixes: #5705 

# before
Screenshot 2022-11-30 at 17 19 16

# after

Screenshot 2022-11-30 at 17 18 01

# before

Screenshot 2022-11-30 at 17 19 24

# after

Screenshot 2022-11-30 at 17 17 50

# before

Screenshot 2022-11-30 at 17 19 36

# after

Screenshot 2022-11-30 at 17 17 23

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@zachaller someone's looking out for you mobile users. :-)

**Comment by zachaller** [comment]
Yea!!!!! This is awesome!!

**Comment by alexef** [comment]
@rbreeze I'm sending you a demo screencast on slack, with latest changes.

**Review by rbreeze — APPROVED** [review]
LGTM

**Comment by alexef** [comment]
@rbreeze can this be merged?

**Pull request merged**
