### PR TITLE
fix: Empty resource whitelist allowed all resources (#5540)

### LINKED ISSUE #5540: AppProjects allow cluster resources to be applied by default and when clusterResourceWhitelist is "[]"
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [ X ] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [ X ] I've included steps to reproduce the bug.
* [ X ] I've pasted the output of `argocd version`.

**Describe the bug**

After some extensive testing and confusion, we discovered that in the AppProject resource, the default behavior with no included whitelist or blacklist allows Applications that belong to the AppProject to apply cluster resources.

Additionally, setting `clusterResourceWhitelist: []` in the AppProject does not restrict Applications from applying any cluster resource.

The default AppProject documented implies that removal of the clusterResourceWhitelist entry will revoke access to deploy cluster resources.
https://argoproj.github.io/argo-cd/user-guide/projects/#the-default-project
```
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
```

The declarative setup docs also imply that an empty list should prevent any cluster resource from being applied.
https://argoproj.github.io/argo-cd/operator-manual/declarative-setup/#projects
```
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
```

**To Reproduce**

Apply the following resources.
```
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: perm-test1
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perm-test1
spec:
  project: perm-test1

  source:
    repoURL: <>
    targetRevision: master
    path: manifests/test

  destination:
    name: <my-cluster>
    namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: perm-test2
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist: []
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perm-test2
spec:
  project: perm-test2

  source:
    repoURL: <>
    targetRevision: master
    path: manifests/test

  destination:
    name: <my-cluster>
    namespace: default
```
Create a cluster resource manifest in the `manifests/test` directory to verify this.
```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: User
  name: oidc:test
```

Notice that ArgoCD successfully applies the cluster resource using either AppProject.

**Expected behavior**

I expect ArgoCD to deny all cluster resources by default, based on the available documentation.
I expect a `clusterResourceWhitelist` of `[]` to also deny all cluster resources, based on the available documentation.

**Code**

I believe this line is where this logic occurs. A length of zero (default) is treated as an allow.
https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go#L2523

This is also likely an issue for namespaced resources, though I personally do not mind that these are allowed by default.

**Version**

```shell
v1.7.3+b4c79cc
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by jangraefen**
Fixes #5540

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by jangraefen** [comment]
The CodeQL fail seems to be unrelated to my change, so here goes nothing.

**Comment by jannfis** [comment]
Thanks for your PR, @jangraefen.  Before reviewing & merging this one, we should make sure that it's the correct intended behavior as discussed in #5540.

> The CodeQL fail seems to be unrelated to my change, so here goes nothing.

FWIW, I submitted two PRs (#5563, #5564) to fix the CodeQL complaints.

**Comment by jangraefen** [comment]
Sure, let's first see the result of #5540 before we proceed. Still, I fast-forwared the master onto the branch to fix the CodeQL problem. Thanks for the hint @jannfis 🙂.

**Comment by jangraefen** [comment]
@jannfis I adapted to code to match the result of the discussion in #5540. Feel free to have a look again 🙂

**Review by jannfis — APPROVED** [review]
LGTM, thank you for this fix, @jangraefen!

**Comment by jannfis** [comment]
@alexmt Shall we cherry-pick this into 1.8 (and possibly 1.7) as well?

**Comment by alexmt** [comment]
agree, cherry-picking

**Pull request merged**
