### PR TITLE
fix: consistent forms for UI

### LINKED ISSUE #5443: Remove colons from summary view
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

ArgoCD doesn't really use `:`s..., except in this view

**To Reproduce**

1. Visit https://cd.apps.argoproj.io/applications?view=summary

**Expected behavior**

ArgoCD is fairly `:`-averse, so there shouldn't be any here.

**Screenshots**

image

**Version**

```shell
{
    "Version": "v1.9.0+bb15a49",
    "BuildDate": "2021-02-06T00:55:32Z",
    "GitCommit": "bb15a4996e327fb27ad91f3f6fa24f831f7754e0",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.5.1+g32c2223",
    "KubectlVersion": "v0.20.1",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by saumeya**
closes #5443 #5262 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

**Before**
https://user-images.githubusercontent.com/17771352/160873344-3ada56ad-3026-41e5-ba26-0eb82b84e36f.mp4

**After**

https://user-images.githubusercontent.com/17771352/161121865-75364118-f53d-40a3-9f04-f2306454d997.mp4

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by terrytangyuan — COMMENTED** [review]
It might be helpful to provide a screenshot of the change.

**Review by ciiay — COMMENTED** [review]
It's a big task and you did a great job! It looks much better now. I only have two things I want to mention, and you may don't have to finish it within this scope.

1, How about for required fields, can we add “\*” to the label as an indicator? It’s just an easier way to apply across the app. E.g. Repo URL is required.  On project details page, there are a few “*”s, what does it mean there? If it means required as well, we can make it consistent across the app.
2, Warning message doesn’t match the label name. E.g. “Name” v.s. “Project name is required”, “Repository URL” v.s. “Repo URL is required”, “Repository Server Name” v.s. “Repository server name is required”

**Comment by saumeya** [comment]
> It's a big task and you did a great job! It looks much better now. I only have two things I want to mention, and you may don't have to finish it within this scope.
> 
> 1, How about for required fields, can we add “_” to the label as an indicator? It’s just an easier way to apply across the app. E.g. Repo URL is required.  On project details page, there are a few “_”s, what does it mean there? If it means required as well, we can make it consistent across the app. 2, Warning message doesn’t match the label name. E.g. “Name” v.s. “Project name is required”, “Repository URL” v.s. “Repo URL is required”, “Repository Server Name” v.s. “Repository server name is required”

Thanks Yi, I definitely noticed these, but wasn't sure - as this would involve a lot more changes. Let me sync up with you today and we could go over these points quickly.

**Review by reginaelyse — APPROVED** [review]
Hey Saumeya! Tested it out and it looks great, thanks :)

**Review by ciiay — APPROVED** [review]
LGTM
Thanks for the update! Looks great 👍

**Review by terrytangyuan — APPROVED** [review]
Looking great!

**Review by alexmt — APPROVED** [review]
LGTM. Thank you for cleaning up UI!

**Pull request merged**
