### PR TITLE
Make application watch stream send keepalive packets (fixes #2518)

### LINKED ISSUE #2518: HTTP request timeouts breaks updating application list/details in UI
Checklist:

* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When opening the application overview or application details page in the UI, the UI starts observing changes to the application states using a HTTP stream to `/api/v1/stream/applications`, which pushes update events to the UI.

In some cases, an active component in the path might enforce timeouts on HTTP requests. In my case, it's HAproxy using a `timeout http-request 10s` directive to prevent stapling up stale connections. If there are no updates sent by the ArgoCD API in the period between the original request and the configured timeout, HAproxy terminates the connection and the Web UI will never pick up the stream again until a page reload. 

**To Reproduce**

Can be reproduced even without HAproxy, because behavior can also be observed with the default webpack web server that is serving the UI. It has a default connection timeout for proxy requests of 2 minutes. 

* Run `make start` to locally start ArgoCD and the UI

Using curl:

* Run "timestamped" curl on the streaming endpoint of the UI proxy: `time; curl http://127.0.0.1:4000/api/v1/stream/applications; time`:
* Wait >=2 minutes and notice how the connection gets terminated (Webpack's Express HTTP server default timeout)
* Run "timestamped" curl on the streaming endpoint of the API: `time; curl http://127.0.0.1:8080/api/v1/stream/applications; time`:
* Wait >=2 minutes and notice how the connection stays alive (API has no request timeout on stream endpoint)

Using UI:

* Open two browser tabs to http://127.0.0.1:4000/applications and web developer tools
* Wait more than two minutes
* In one tab, delete an application
* Notice how the list of applications does not get updated in the other tab
* See in web developer tools how the request to `/api/v1/stream/applications` has been terminated and not re-established

**Expected behavior**

The streaming request is not terminated and the UI keeps updating the application list.

**Version**

Recent build of `latest`:

```shell
argocd-server: v1.3.0+0f2a881
  BuildDate: 2019-10-17T04:51:46Z
  GitCommit: 0f2a88102dcd3212161454f8d431445e1cdee538
  GitTreeState: clean
  GoVersion: go1.12.6
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v3.1.0
  Helm Version: v2.12.1
  Kubectl Version: v1.14.0

```

**Logs**

```
Paste any relevant application logs here.
```

### PR DESCRIPTION
**Pull request by jannfis**
Checklist:

* [x] This fixes a bug
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Fix for #2518 by having the application watch stream send keepalive packets. 

The interval how often this packet should be sent can be configured setting the `ARGOCD_STREAM_KEEPALIVE_INTERVAL` environment variable to a non-negative integer value, specifying the interval in seconds. 

The default for the interval is 60 seconds. If set to 0, keepalive packets will be disabled.

### CODE REVIEW

**Comment by alexec** [comment]
This looks fine to me. I'd like @alexmt to give it the once over because he knows this code well.

**Comment by jannfis** [comment]
@alexmt mind taking a look at this please? The bug hits me in a pretty annoying way, and I'd love to get this fixed.

**Review by alexmt — CHANGES_REQUESTED** [review]
Thank you for working on fix, @jannfis ! 

I think there is a way to add keep-alive for all streaming api calls in a generic way. We already have grpc `StreamForwarder` which is responsible for proper serialization when stream requested by the browser:

https://github.com/argoproj/argo-cd/blob/958096aaa8fa35a968b0691f3e6c1ff7a3f71305/util/http/forwarders.go#L153

It should be possible to write a fake sse message every few seconds. The fake message can be filtered out on client-side here: https://github.com/argoproj/argo-cd/blob/a0f39034182e4a82f53bb5ce684e4e0d45bcb1c8/ui/src/app/shared/services/requests.ts#L72

**Comment by jannfis** [comment]
Thank you for the pointers, @alexmt ! Guess it's time to get into gutty details of gRPC then, but you are absolutely correct - probably the core stream handlers in the server and the client are the right place to fix it!

I think it's better to close this PR and open a new one once I have some usable code then.

**Pull request closed without merging**
