### PR TITLE
add sunbit to who uses list

### PR DESCRIPTION
**Pull request by gevalter**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexec** [comment]
Hi! Thank you for submitting your PR. I can’t find enough information in your profile to confirm your relationship with Sunbit. Any change you can provide a bit more info please?

**Comment by gevalter** [comment]
Hi! not sure what kind of information you need but i guess an email with
the company domain is enough.... i'm at the devops team and we just
upgraded to 1.3.4... following argo for a while and it's great for us! we
are a startup company that growth really fast and argoCD is way faster and
reliable then jenkins..

**Comment by alexec** [comment]
Cool. Can you just drop me an email at alex_collins@intuit.com from your work address? It's like headed paper I guess!

**Comment by alexmt** [comment]
@gevalter can you please sign a CLI as well?

**Pull request closed without merging**
