### PR TITLE
feat(ui): support auto theme

### LINKED ISSUE #20105: Theme support auto mode
# Summary

The Appearance Settings theme supports 'Auto mode, which will follow the OS theme settings.

# Motivation

Wants the theme to be set automatically and to automatically change to a darker colour at night like the OS theme.
[related comment](https://github.com/argoproj/argo-cd/issues/4722#issuecomment-1252583106)

# Suggestions

Browsers have matchMedia to help use listen to OS theme changes

### PR DESCRIPTION
**Pull request by linghaoSu**
Fixes https://github.com/argoproj/argo-cd/issues/20105

image

## Before
Only support set theme manually

## Now
Support set auto theme, would show theme determined by system theme.

https://github.com/user-attachments/assets/5b9cc7a4-d8b4-4719-808d-fcec5bfe6273

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by reggie-k** [comment]
@CodiumAI-Agent /review

**Comment by reggie-k** [comment]
> ### ✅ Preview Environment deployed on [Bunnyshell](https://www.bunnyshell.com)
> Component	Endpoints
> argocd	https://argocd-5hxsdn.bunnyenv.com/
> argocd-ttyd	https://argocd-web-cli-5hxsdn.bunnyenv.com/
> See: [Environment Details](https://environments.bunnyshell.com/b/environment/M1X1v5pErQ) | [Pipeline Logs](https://environments.bunnyshell.com/b/pipeline/nx6yr8PnMa)
> 
> Available commands (reply to this comment):
> 
> * 🔴 `/bns:stop` to stop the environment
> * 🚀 `/bns:deploy` to redeploy the environment
> * ❌ `/bns:delete` to remove the environment

/bns:deploy

**Review by reggie-k — COMMENTED** [review]
I tested the change locally and it looks really good!
I wonder whether we should change the default preference to 'auto' though or leave it light as it was.
Also, PTAL at the Codium AI review, this is also an opportunity to test how accurate it is.
And could you change the title of the to PR feat(ui) from feat(theme)?

**Comment by linghaoSu** [comment]
@reggie-k Thanks for your review!

I've changed the title.

Maybe it would be better to set the default theme to ‘light’.

## codiumAI
1. useSystemTheme is just used to register a listener to watch for changes in the OS theme and destroy the listener when the component is destroyed, that's why I used this feature in `useEffect`.
2. for `useTheme`, it does need to be optimised, now it only watches the system theme change when the theme is `auto`. And fixed the issue with themeWrapper not using the preferred theme.

**Review by todaywasawesome — APPROVED** [review]
I would be fine with auto being the default but I don't think it's that important and not worth stalling the merge.

**Review by reggie-k — APPROVED** [review]

**Review by pasha-codefresh — APPROVED** [review]

**Comment by jeremych1000** [comment]
Has this been released? I tried searching for #20080 in the release notes but couldn't find anything.

**Comment by reggie-k** [comment]
> Has this been released? I tried searching for #20080 in the release notes but couldn't find anything.

This would be released as part of 2.14

**Pull request merged**
