### PR TITLE
chore: Upgrade aws-sdk-go from 1.44.317 to 1.49.4.

### PR DESCRIPTION
**Pull request by ROunofF**
This update the aws-sdk-go so it will support dynamic auth token (EKS Pod Identities).

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by tybook** [comment]
Thank you for creating this! I wonder if any of the `aws-sdk-go-v2` deps [here](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/go.mod#L117-L128) also need to be updated to fully support EKS Pod Identities? Referencing https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html and its link to https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-14

**Comment by ROunofF** [comment]
> Thank you for creating this! I wonder if any of the `aws-sdk-go-v2` deps [here](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/go.mod#L117-L128) also need to be updated to fully support EKS Pod Identities? Referencing https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html and its link to https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-14

You may be right, not that familiar with // indirect, I'm taking a look

**Comment by csantanapr** [comment]
I'm collaborating with @ROunofF and we made progress, I was able to authenticate to a remote EKS cluster using the new [Pod Identity feature released Nov 2023](https://docs.aws.amazon.com/eks/latest/userguide/pod-identities.html) instead of using IRSA. There is no code changes required just bumping the version of the aws sdk.

image

**EKS Pod Identity Affects 3 capabilities in ArgoCD:**
* Hub&Spoke model awsAuthConfig (to remote clusters)
    * https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/#eks
    * https://github.com/aws-ia/terraform-aws-eks-blueprints/tree/main/patterns/gitops/multi-cluster-hub-spoke-argocd
* Notification via SQS
    * https://argo-cd.readthedocs.io/en/stable/user-guide/subscriptions/
    * https://argocd-notifications.readthedocs.io/en/stable/subscriptions/
    * https://github.com/argoproj/notifications-engine/blob/master/docs/services/awssqs.md
* SCM Provider Generator for codeCommit AWS (Application Set Controller)
    * https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/Generators-SCM-Provider/#aws-iam-permission-considerations

**Comment by ROunofF** [comment]
> Thank you for creating this! I wonder if any of the `aws-sdk-go-v2` deps [here](https://github.com/argoproj/argo-cd/blob/1975074de5fb80cb56c94add93ba55979df67b98/go.mod#L117-L128) also need to be updated to fully support EKS Pod Identities? Referencing https://docs.aws.amazon.com/eks/latest/userguide/pod-id-minimum-sdk.html and its link to https://github.com/aws/aws-sdk-go-v2/releases/tag/release-2023-11-14

The aws-sdk-go-v2 are coming from the notifications-engine. I opened a PR for this : https://github.com/argoproj/notifications-engine/pull/259 (Draft while testing this)

Let us know if this is the right approach to have notifications-engine updated.

**Comment by csantanapr** [comment]
There is a new PR that supersedes this one https://github.com/argoproj/argo-cd/pull/17063

**Comment by blakepettersson** [comment]
Closing

**Pull request closed without merging**
