### PR TITLE
fix: directory source include/exclude should match relative file path

### PR DESCRIPTION
**Pull request by alexmt**
PR improves `app.source.directory.include`/`app.source.directory.exclude` behavior. The filter should be applied to a relative file path, not the absolute file path that includes the temp repo directory

### CODE REVIEW

**Comment by jannfis** [comment]
Why have the e2e tests been removed?

**Comment by alexmt** [comment]
I've decided to replace e2e tests with unit tests since e2e tests are expensive. I think in this case unit tests give more flexibility and verify functionality better. 

Also both deleted e2e tests were only verifying that the application is synced successfully. Did not really test that filter is applied correctly.

**Comment by jannfis** [comment]
> I've decided to replace e2e tests with unit tests since e2e tests are expensive. I think in this case unit tests give more flexibility and verify functionality better.
> 
> Also both deleted e2e tests were only verifying that the application is synced successfully. Did not really test that filter is applied correctly.

OK, that's fine for me.

Could you please extend unit tests with glob matching (e.g. `**/*.yaml`), too? And also, with filters on `Include` and `Exclude` that should not match?

**Comment by alexmt** [comment]
Thank you for review @jannfis ! added more tests.
PTAL

**Comment by jannfis** [comment]
> I added more tests. PTAL
Awesome, thank you!

**Review by jannfis — APPROVED** [review]
LGTM.

I'm fine with the cherry-pick to 1.8, if this doesn't change existing behaviour of `Include` and `Exclude` for people.

**Pull request merged**
