### PR TITLE
fix: update ARGOCD_REPO_SERVER_PLUGIN_USE_MANIFEST_GENERATE_PATHS env…

### PR DESCRIPTION
**Pull request by kpanter**
… for argocd-repo-server deployment

our validation workflow detected below error
  ❌ FAIL: stdin - Deployment argocd-repo-server is invalid: problem validating schema. Check JSON formatting: jsonschema: '/spec/template/spec/containers/0/env/21' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json#/properties/spec/properties/template/properties/spec/properties/containers/items/properties/env/items/additionalProperties: additionalProperties 'configMapKeyRef' not allowed

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@kpanter good catch. The install.yaml is rendered based on Kustomize manifests, so the primary problem is in a different file. Once you find that file, you can run `make manifests-local` to regenerate install.yaml.

**Comment by blakepettersson** [comment]
This is a duplicate of #20139 right?

**Comment by kpanter** [comment]
> @kpanter good catch. The install.yaml is rendered based on Kustomize manifests, so the primary problem is in a different file. Once you find that file, you can run `make manifests-local` to regenerate install.yaml.

Updated argocd-repo-server-deployment.yaml under manifgest/base/repo-server and executed make manifests-local

**Comment by kpanter** [comment]
> This is a duplicate of #20139 right?

yes, right

**Comment by kpanter** [comment]
duplicate of https://github.com/argoproj/argo-cd/pull/20139

**Pull request closed without merging**
