### PR TITLE
feat(ui): Adds resource filter panel. Fixes #6379 #6331 #6081

### LINKED ISSUE #6081: UI: resource filtering options
I'd like some more options to filter resources in the UI. I have 200 resources in a single app.

* What about filtering on labels?
* What about a filter to show only recently synced resources?
* What about a filter to show only recently changed resources? This would include recently synced ones.

### LINKED ISSUE #6331: UI: filter with ownership
I often just care about pods and the resources that own them.

When I filter resources, please show their parents too.

### LINKED ISSUE #6379: UI: recently synced resources filter
I'd like to just see recently synced resources (last 15m or last 30m). 

This will allow me to see what just happened when I do a sync. 

I'd like to combine this with the out-of-sync resources, so I can see what just changed, and what will shortly change.

### PR DESCRIPTION
**Pull request by alexec**
Fixes #6379 
Fixes #6331 
Fixes #6081

image

### CODE REVIEW

**Comment by alexec** [comment]
@rbreeze @alexmt as discussed, this is the first of two PRs, that is lower risk and targeted for v2.1. It contains only UI changes, which were almost all just lift-and-shift from the previous PR, but with improvements to the styling to make it more consistent with the filters an the application list page.

**Comment by alexec** [comment]
I've just noted one bug due to re-using the filters, when the filter grows to `xxlarge up` `display: none` is applied. I.e. with a big viewport, the button is hidden.

**Comment by alexec** [comment]
Fixed by replacing action button with <a/>

image

**Review by rbreeze — CHANGES_REQUESTED** [review]
Looks great! Love that the new filters match the apps list filter. Thanks! One tiny nitpick, could we change this to "Clear all"?

Screen Shot 2021-07-14 at 3 02 25 PM

**Comment by alexec** [comment]
> Looks great! Love that the new filters match the apps list filter. Thanks! One tiny nitpick, could we change this to "Clear all"?
> 
> Screen Shot 2021-07-14 at 3 02 25 PM

Ah. Thats two separate links: "clear" and "all" (i.e. select all).

**Comment by rbreeze** [comment]
Oh I see. Never mind then! I'll delineate the buttons more clearly when I make design changes in a separate PR

**Review by rbreeze — APPROVED** [review]

**Pull request merged**
