### PR TITLE
fix: Excessive HTTP requests when navigating in list view - 17756

### LINKED ISSUE #17756: Excessive HTTP requests and therefore API calls when navigating in list view
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

It seems that when navigating in list view, the ArgoCD UI make several requests for each resource even if it's not necessary.  
For example if exec is enabled, every resource is checked if exec is allowed, even if it's not a pod.  

On tree view this happens only when clicking on the 3 dots.
On list view this happens in the overview.

The following endpoints are called too many times:
1. `/api/v1/settings`
2. `/api/v1/applications/guestbook/resource/actions?appNamespace=argocd&namespace=default&resourceName=guestbook-ui-56c646849b-2qsm5&version=v1&kind=Pod`
3. `/api/v1/applications/guestbook/resource/links?name=guestbook-ui-56c646849b-2qsm5&appNamespace=argocd&namespace=default&resourceName=guestbook-ui-56c646849b-2qsm5&version=v1&kind=Pod&group=`
4. `/api/v1/account/can-i/exec/create/default/<resource name>`

**To Reproduce**

- `kind create cluster --name argocd`
- `kubectl create namespace argocd`
- `kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml`
- [Create Application](https://argo-cd.readthedocs.io/en/stable/getting_started/#creating-apps-via-ui)
- `kubectl scale --replicas 10 -n default deploy guestbook-ui` (to better see the extent of the problem)

**Expected behavior**

1. The endpoints (at least `/api/v1/account/can-i/exec/create/default/<resource name>`) should only be called when clicking on the 3 dots.
2. The endpoint `/api/v1/account/can-i/exec/create/default/<resource name>` should only be called when clicking on a pod.

Be careful not to introduce old bugs, see references in **Related** heading.

**Video**

https://github.com/argoproj/argo-cd/assets/43774417/2ba329b9-9d78-4b65-a4cc-1f597a9eaf6a

**Version**

```shell
{
    "Version": "v2.10.4+f5d63a5",
    "BuildDate": "2024-03-18T08:09:23Z",
    "GitCommit": "f5d63a5c77d2e804e51ef94bee3db441e0789d00",
    "GitTreeState": "clean",
    "GoVersion": "go1.21.3",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v5.2.1 2023-10-19T20:13:51Z",
    "HelmVersion": "v3.14.3+gf03cc04",
    "KubectlVersion": "v0.26.11",
    "JsonnetVersion": "v0.20.0"
}
```

**Related**

- https://github.com/argoproj/argo-cd/issues/16165
- https://github.com/argoproj/argo-cd/pull/16168

### PR DESCRIPTION
**Pull request by adberger**
Fixes #17756

As for tree view [renderResourceMenu](https://github.com/argoproj/argo-cd/blob/496ac5e2943d1cc7768a1680ec70a5014674300f/ui/src/app/applications/components/utils.tsx#L530) now should only get triggered when clicking on the resource menu in the list view as well.

Please be careful about the review since this is my first contribution.  
If you want to backport it, is up to you to decide.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by adberger** [comment]
@ashutosh16 Do I need to do anything else for a reviewer to look into it?

**Comment by ashutosh16** [comment]
LGTM

https://github.com/argoproj/argo-cd/assets/11219262/c26f0d4b-74f7-4821-ad3a-00894cee13e4

**Review by ashutosh16 — APPROVED** [review]

**Comment by ashutosh16** [comment]
@ishitasequeira  Changes look to me, Can you take a second look at the changes?

**Review by pasha-codefresh — APPROVED** [review]
LGTM, thank you for your first contribution!

**Comment by adberger** [comment]
@pasha-codefresh Where do I see starting from which version this change will be active?

**Pull request merged**
