### PR TITLE
fix: Serve ReDoc JS from Argo CD server instead of from CDN

### LINKED ISSUE #4520: Manipulation of argocd possible through third party scripts
We have the following finding from our pentesters, we like to know what can be done to mitigate the risk

**Description**
JavaScript code from external domains is included in several parts of the website. In
two cases, JavaScript from an external domain is loaded to offer a user interface for
the API.
Included JavaScript executes in the security context of the including website. If the
external host serving the included files is compromised, all users of the CI/CD
environment website can be attacked through manipulated JavaScript from the
external host, which is also known as Cross-Site Scripting.
**Evidence**
Use the developer tools of the browser to check which scripts are loaded on the
mentioned URL for example: https://<argocd>/swagger-ui

image

**Impact: high**
Compromised external hosts make it possible to execute arbitrary scripting code in
the target user’s web browser. This scripting code will be executed within the security
context of CI/CD environment. Amongst other scenarios, this makes it possible to:
 Manipulate application interaction. Executed script can be used to perform any
interaction with the application on behalf of the user.
 Obtain cookies. Argo uses a session cookie which carries an ID for access control.
Access to this information provides control over the authenticated session
(account) of the target user. In case of an administrative user, the entire
application or server may be at risk.
 Mimic the web application presented to the target user (defacement). With this
attack, actual working functionality is injected into the vulnerable application,
designed to deceive end users and harvest confidential information such as log in
credentials.
 Perform arbitrary redirection. Redirection can be of use in phishing attacks in
order to induce a target user to visit a spoofed website and enter personal
information. Nowadays malware writers and scammers also use common redirect
vulnerabilities for luring unsuspecting users into installing malware on their
systems.

**Recommendation**
 Only deploy or install services, middleware and programs which are essential to
the correct working of the application. If partial installations are not possible,
non-essential services and functionality should be removed or disabled.
 Limit the privileges of the API interfaces by including a Content-Security-Policy
header in the response.
 Remove dependencies on external parties by reviewing the scripts and making
the scripts available from the application server directly.
 Make sure external parties are compliant with security guidelines.
 Use Subresource Integrity hashes on script tags to avoid loading manipulated
scripts.
 Reflect the above in a deployment or coding guideline in order to prevent the
same finding in future releases.

image

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #4520

**Note for reviewer:**
I sourced the script included with this PR from https://cdn.jsdelivr.net/npm/redoc/bundles/redoc.standalone.js, which seems to be the new official location (see https://github.com/go-openapi/runtime/blob/0f43ad21da658bad9ded004f0c42b3e2dc8fd376/middleware/redoc.go#L77)

Please check SHA256 checksums, for both, script downloaded from above location and script contained in this PR. It should be:

```
83a36385460319de925d221892fb9091985d6edab1f21a8d29533c24abeaa72e  redoc.standalone.js
```

Also, it updates the ReDoc script from version 1.22.3 to 2.0.0-rc.40, which contains licensing information (MIT license).

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by jessesuen — APPROVED** [review]

**Comment by jessesuen** [comment]
@jannfis great fix. Is there a way to get `Code scanning results / CodeQL Failing after 3s — 8 errors, 4 warnings` to PASS?

**Comment by jannfis** [comment]
> Is there a way to get `Code scanning results / CodeQL Failing after 3s — 8 errors, 4 warnings` to PASS?

Probably not without ignoring the findings (as in, closing in the CodeQL scanner as won't fix) or having the ReDoc guys take a look at it. 

However, I think the issues the CodeQL scanner complains about are negligible in our case -- they are purely client-side and we don't have the script handle arbitrary, user-supplied input but our swagger.json and the user interactions.

**Comment by jannfis** [comment]
I think the risk rating on those is low, so from my point of view, we can dismiss the CodeQL warnings.

@jessesuen/@alexmt, if you agree I'll close them and merge the PR. If someone else disagrees, please raise your hand :)

**Review by alexmt — CHANGES_REQUESTED** [review]
@jannfis I think I found easy way to keep CodeQL happy. We can dynamically copy  redoc.standalone.js during build. This will also simplify upgrading redoc version.

https://github.com/jannfis/argo-cd/pull/16

**Review by alexmt — APPROVED** [review]
LGTM

**Comment by jannfis** [comment]
OK, now snyk complains about the ReDoc script. Anyway gonna merge this change, I guess the old (foreign hosted) script had quite a couple of more problems, plus the fact it was foreign hosted too.

**Pull request merged**
