### PR TITLE
feat: add i18n (#12520)

### PR DESCRIPTION
**Pull request by juunini**
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

# Description
[ISSUE #12520]
Add dependency [i18next](https://www.i18next.com/) in ui
And add korean translation

image
image

### CODE REVIEW

**Comment by blakepettersson** [comment]
Hello! Could you split `add i18n` and `lint Go code` into 2 separate PRs? Thanks!

**Comment by juunini** [comment]
@blakepettersson OK, I separate `Lint Go code` in #12523

**Comment by blakepettersson** [comment]
Hi @juunini this looks good! Is there a chance of putting a language button somewhere, so that it's not _only_ the language browser settings that can determine the language? I'm not much of a UX guy, so I have no real idea where such a button should be? Maybe @rbreeze or @alexef has some ideas?

**Comment by juunini** [comment]
@blakepettersson Yes, I'll add language `select`.  
I think language select is locate is upper right(header nav).

**Comment by juunini** [comment]
Add language select

image
image

**Comment by blakepettersson** [comment]
@juunini there was a [discussion](https://cloud-native.slack.com/archives/C020XM04CUW/p1677251030358029) pertaining to this PR on the #argocd-contributors channel. Something which would be good to have (since I'm not sure if there are any Korean-native speakers that can review the translations) would be allowing for the possibility to optionally load community-translated languages via a module of some sort?

**Comment by dalinaum** [comment]
@blakepettersson @juunini I'm a Korean developer. I can participate in the review of the Korean translation if needed.

**Comment by Junsang-Mun** [comment]
@blakepettersson Another interested Korean developer here. Would be lovely if I can participate in.

**Comment by crenshaw-dev** [comment]
Thanks, y'all!

I think we need a way to store translation packs in a new argoproj-labs repo and load them into the UI as an optional component. @juunini are you up for proposing a design for that system?

**Comment by crenshaw-dev** [comment]
Closing for now, until we find a way to provide i18n as an externalized package.

**Pull request closed without merging**
