### PR TITLE
fix: keep array entries not found in live state

### LINKED ISSUE #9678: sync is not working with ignoreDifferences and RespectIgnoreDifferences=true
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have an application where I want to ignore the image of the deployment and ignore it from being synced, I can see that the image is ignored and there is new env variables to be added in app diff but once I sync it it succeeds without applying the env variables like it's ignored with the image itself and I still see them in app diff!. This is the application:

```
project: default
source:
  repoURL: 'git@bitbucket.org:x/x.git'
  path: kubernetes/production
  targetRevision: master
  plugin:
    name: argocd-vault-plugin
destination:
  server: 'https://x.x.x.x'
syncPolicy:
  syncOptions:
    - RespectIgnoreDifferences=true
ignoreDifferences:
  - group: apps
    kind: Deployment
    name: service
    jqPathExpressions:
      - >-
        .spec.template.spec.containers[] | select(.name == "service").image
```

**To Reproduce**

Apply an application with ignoreDifferences like the application above and add new changes inside the same container specs
The new specs will not be applied after sync.

**Expected behavior**

I expect the image to be ignored and the new env variables to be applied/synced

**Version**

```shell
❯ argocd version --grpc-web
argocd: v2.2.7+b8e154f
  BuildDate: 2022-03-09T01:07:22Z
  GitCommit: b8e154f767412172bb0c2b41131460c34d2a0c73
  GitTreeState: clean
  GoVersion: go1.16.11
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.3.4+ac8b7df
  BuildDate: 2022-05-18T11:41:37Z
  GitCommit: ac8b7df9467ffcc0920b826c62c4b603a7bfed24
  GitTreeState: clean
  GoVersion: go1.17.10
  Compiler: gc
  Platform: linux/amd64
  Ksonnet Version: v0.13.1
  Kustomize Version: v4.4.1 2021-11-11T23:36:27Z
  Helm Version: v3.8.0+gd141386
  Kubectl Version: v0.23.1
  Jsonnet Version: v0.18.0
```

### PR DESCRIPTION
**Pull request by blakepettersson**
There's an issue with `intersectMap` not appending items for array properties where the live array is smaller than the desired array.

Hopefully fixes #9678.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
This is probably a step in the right direction. It does fail to account for merge keys, though (e.g. in an `env` array, items should be merged on the `name` key).

**Comment by crenshaw-dev** [comment]
The new logic looks nicely done, and I appreciate all the unit tests. But I think we might have to address the underlying issue and see if we can implement strategic merge patching instead of plain json patching in ignoreDifferences.

**Comment by blakepettersson** [comment]
@zswanson time - it's something which sadly has been sorely lacking for me lately. When digging into this locally there are edge-cases upon edge-cases which I bump into, and this is sadly not as trivial as it seems in this PR (and it's already far from trivial).

The deeper I go into the rabbit hole, the more I think that this needs a rethink, and I agree with @crenshaw-dev that another approach is needed. 

@crenshaw-dev when you say strategic merge patching, is that the same thing as Server-Side Diff (hence potentially addressed with #13663)?

**Comment by crenshaw-dev** [comment]
@blakepettersson not exactly related to server-side diff. It's been a while since I've looked into this code in depth, but iirc we're generating patches using a generic JSON patch library. To handle k8s resources, we really need to use k8s libraries to generate "strategic merge patches," i.e. patches that respect resources' merge keys.

**Comment by crenshaw-dev** [comment]
That response is vague, and it's because I don't remember this code well enough to remember exactly how strategic merge patching would be used to solve the problem. :-P

**Comment by saumeya** [comment]
Hi @blakepettersson @crenshaw-dev any help needed to move this fix to completion? We also need a fix for this issue.

**Comment by blakepettersson** [comment]
Hi @saumeya @zswanson et al - due to life circumstances I haven't had the time to look at this for the past couple of months. I just changed jobs, and there's a reasonable chance that I can revisit this PR in a not too long time frame from now. Before iterating on this PR further though, I would like to see if the actual issue could be better addressed by instead making use of Server-Side Apply / Server-Side Diff.

**Comment by blakepettersson** [comment]
Closing this PR since I don't think this is a viable way to go, [see comment](https://github.com/argoproj/argo-cd/issues/9678#issuecomment-1988029193).

**Pull request closed without merging**
