### PR TITLE
fix: ui add tooltips on repository url links and names (#9868)

### PR DESCRIPTION
**Pull request by xieyanke**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Comment by ashutosh16** [comment]
@xieyanke Thanks for raising the PR. Can you add a screenshot of the change - expected/actual?

**Comment by xieyanke** [comment]
Hi @ashutosh16 , As follows:

image

image

**Review by saumeya — APPROVED** [review]

**Comment by keithchong** [comment]
Hi @xieyanke , I think we need the repo URL as a link so users can click on it to easily navigate to the repo.

Also, if you hover over the link, the full URL does show up at the bottom left corner of the browser anyway (at least from what I've tried using Chrome and Firefox).  So I don't think we should remove the usability of the link for the tooltip.

**Comment by xieyanke** [comment]
Hi, @keithchong, I have solved this problem, now users can hover over the link and the tooltip will show up at the top of it,  users also can click on the link to navigate to the repo (I've tested it using Chrome version: 104.0.5112.79 & Firefox version: 103.0)

I think getting the full URL with tooltips is necessary, because when users add a new long url repo, and ArgoCD have too many long url repos in repo-list, they cannot determine which one he is added



image


image

**Review by keithchong — APPROVED** [review]
LGTM

**Pull request merged**
