### PR TITLE
feat: Support context switch for argocd-util

### LINKED ISSUE #5912: Support context switch for argocd-util
# Summary
I have multiple contexts I need to switch between, it would be very helpful to switch the context on a global level via an argument or environment-variable.

# Motivation
Let's assume you have three contexts named dev, staging and production and are constantly changing via `argocd context dev....`, `argocd context staging....` or `argocd context production....`,  prior actual execution of the desired action. Also you have to check each time which context you are currently working in prior execution.

So the current workflow is:
```
# check which context I'm in
argocd context
# switch if required
argocd context staging...
# execute command, eg:
argocd app list
```
# Proposal
Pass the context in the actual command, eg:
```
argocd app list --context staging...
```
or as environment variable
```
ARGOCD_CONTEXT=staging... argocd app list
```

### PR DESCRIPTION
**Pull request by nekia**
Signed-off-by: Atsushi Neki <nekiaiken@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #5912

### CODE REVIEW

**Comment by nekia** [comment]
I changed the switch flag from `--context` to `--argocd-context` to avoid confusing with kubeconfig context flag , and merged files which were updated by running `make clidocsgen`.

image

**Comment by swerder-coop** [comment]
This simple and realy usefull change still not merged to the master branch, is there any reason for that?
The change https://github.com/argoproj/argo-cd/pull/8849 for "--kube-context" made it to production in April 2022
But for use the argocd command on jenkins and allow parallel builds I need the --argocd-context from this issue.

my only workaround without this change is use --config and make different config files for each argocd context

**Comment by lionelnicolas** [comment]
Any update on this PR ?

**Comment by todaywasawesome** [comment]
@nekia I think this stalled primarily because there is a decent workaround with `--config` but I also still think this is relevant. If you want to fix the conflicts, I think we could get this one merged.

**Review by todaywasawesome — CHANGES_REQUESTED** [review]
Lets just fix conflicts.

**Review by todaywasawesome — APPROVED** [review]
Ready to go

**Review by pasha-codefresh — APPROVED** [review]
LGTM, thank you!

**Comment by kencochrane** [comment]
It looks like we still have one of the checks failing before we can merge. Anyone know how to fix it?

**Comment by pasha-codefresh** [comment]
Opened new PR https://github.com/argoproj/argo-cd/pull/19549

**Pull request closed without merging**
