### PR TITLE
fix(notifications-catalog): Add nil check for notifications_catalog triggers

### PR DESCRIPTION
**Pull request by ichbinfrog**
Without this nil check, the argocd notification controller will periodically print out errors (see below) out when assessing trigger conditions. Although ultimately harmless, it makes debugging hard by introducing a lot of noises (and red herrings for the users).

```
time="2023-07-27T14:34:56+02:00" level=error msg="failed to execute when condition: cannot fetch phase from <nil> (1:27)\n | app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'\n | ..........................^"
```

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by jannfis — APPROVED** [review]
LGTM, thank you!

**Comment by jannfis** [comment]
Can you please run `make codegen` (or `make codegen-local`, depending on your setup) to update the installation manifests?

**Comment by jannfis** [comment]
Or actually, `make manifests` should probably be sufficient in this case.

**Comment by ichbinfrog** [comment]
Thanks for the fast review @jannfis , `make notification-catalog` worked for me

**Pull request merged**
