### PR TITLE
chore: Update to v3 of the sprig library for ApplicationSets (#11277)

### LINKED ISSUE #11277: Update ApplicationSets to use the sprig library v3
# Summary

Go templates in ApplicationSets are a nice addition, but I was surprised to find some missing sprig functions from the [linked documentation](https://masterminds.github.io/sprig/).

# Motivation

I was looking to specify defaults for config not passed through the values field.  Because `{{ .values }}` now comes through as an object like [metadata](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/#cluster-generators), this gets a little trickier.  

The [dig](https://masterminds.github.io/sprig/dicts.html#dig) function can help by traversing nested dicts or falling back to a default.  It was added in [v3.2.0](https://github.com/Masterminds/sprig/releases/tag/v3.2.0) of the sprig library and isn't available in [v2.22.0](https://github.com/argoproj/argo-cd/blob/41b1ebef83b3ea9f38108bb0ca02222b067152bc/go.mod#L131)

# Proposal

I have a [branch](https://github.com/argoproj/argo-cd/compare/master...genehand:argo-cd:sprig-v3) up after running `go get github.com/Masterminds/sprig/v3` and updating the reference in `applicationset/utils/utils.go` (v2 is still used by the notifications-engine.)  If this is accepted I'm happy to open a PR!

### PR DESCRIPTION
**Pull request by genehand**
Use the latest release of the sprig library for ApplicationSet templates. [v3.2.0](https://github.com/Masterminds/sprig/releases/tag/v3.2.0) added several new functions and [v3.0.0](https://github.com/Masterminds/sprig/releases/tag/v3.0.0) wasn't really a breaking change:

> Sprig v3 brings some changes while retaining the same Go API. This should enable projects to migrate to v3 with relative ease.
> You might be wondering, why increment the major version if the Go API didn't break? The reason for that is some edge case behavior changed. Most importantly the use of ^ while handling major version 0 use cases with semver. To be cautious, the major version of sprig was incremented to limit the number of surprises.

Closes #11277

Signed-off-by: Gene Hand <ghand@doximity.com>

---

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
Thanks @genehand for the PR. LGTM!

**Comment by ishitasequeira** [comment]
@crenshaw-dev PTAL

**Comment by crenshaw-dev** [comment]
The semver change is a bit difficult to understand, but I'd like to document it in the 2.5 -> 2.6 upgrade guide.

We could add this text:

> ### ApplicationSets: `^` behavior change in Sprig's semver functions
> 
> Argo CD 2.5 introduced [Go templating in ApplicationSets](https://argo-cd.readthedocs.io/en/stable/operator-manual/applicationset/GoTemplate/). Go templates have access to the Sprig function library.
> 
> Argo CD 2.6 upgrades Sprig to v3. That upgrade includes an upgrade of [Masterminds/semver](https://github.com/Masterminds/semver/releases) to v3.
> 
> Masterminds/semver v3 changed the behavior of the `^` prefix in semantic version constraints. If you are using Go-templated ApplicationSets which include references to [Sprig's semver functions](https://masterminds.github.io/sprig/semver.html) and use the `^` prefix, read the [Masterminds/semver changelog](https://github.com/Masterminds/semver/releases/tag/v3.0.0) to understand how your ApplicationSets' behavior may change.

This addresses the far-, far-edge case that someone is using a semver function in a way that changes the ApplicationSet's behavior. But better to be thorough, I think.  :-)

**Comment by genehand** [comment]
> This addresses the far-, far-edge case that someone is using a semver function in a way that changes the ApplicationSet's behavior. But better to be thorough, I think. :-)

Sgtm 😄  Added!

**Review by crenshaw-dev — APPROVED** [review]

**Pull request merged**
