### PR TITLE
fix(ui): Correct pod log viewer to support short log lines (#14402)

### LINKED ISSUE #14402: Pod logs are displayed as line numbers
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

I have a pod that just prints out 1-160 but they are displayed as line numbers in the log viewer.

**To Reproduce**

The following is the pod spec:
```
apiVersion: v1
kind: Pod
metadata:
  name: intentional-fail
spec:
  containers:
  - name: fail
    image: bash:4.4
    command: ["bash", "-c"]
    args:
    - |
      set -eu
      for i in {1..160}; do echo $i; done;
      exit 1

```

**Expected behavior**

The actual numbers printed out should also be in the log viewer.

**Screenshots**

Screen Shot 2023-07-03 at 2 55 10 PM

### PR DESCRIPTION
**Pull request by terrytangyuan**
Fixes #14402

### CODE REVIEW

**Comment by crenshaw-dev** [comment]
@terrytangyuan how far back do we need to cherry-pick this? 2.7 I think?

**Comment by terrytangyuan** [comment]
v2.7 seems reasonable (I am using v2.7.6). Could you also test the change if you already have the dev setup locally?

**Review by rbreeze — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@rbreeze have you had a chance to test locally? If so, I'll smash merge.

**Comment by terrytangyuan** [comment]
Let's perform more testing before merging this since this will be cherry-picked.

**Comment by crenshaw-dev** [comment]
I was about to test, but `kind` is misbehaving. :-P

**Comment by terrytangyuan** [comment]
@crenshaw-dev Verified that this looks good locally.

**Pull request merged**
