### PR TITLE
feat: support fetch refs (#1604)

### PR DESCRIPTION
**Pull request by yujunz**
Checklist:

* [x] I've created an enhancement proposal #1604 
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by alexmt** [comment]
looking

**Comment by yujunz** [comment]
> looking

Thanks.

Refactored the code a bit to make the logic more clear. I didn't expect so many side effects on changing the signature of Fetch.

Last tested version was https://github.com/argoproj/argo-cd/commit/a286507825d007a91b40bb61a818df897114bde7 

Let me know which one looks better.

**Comment by james-callahan** [comment]
oh damn, I thought this made it into 1.8.0 :(

**Comment by yujunz** [comment]
Will it be integrated to 1.8.x or needs to wait for v1.9.x? I have been using my fork for weeks and it looks good so far.

**Comment by yujunz** [comment]
Rebased to tip and all checks have passed. Could you take another look? @alexmt

**Review by alexmt — APPROVED** [review]
Sorry for the delay in review @yujunz . 

Learned what FETCH_HEAD is and verified your changes locally. Everyone looks good. LGTM.

Thank you!

**Pull request merged**
