### PR TITLE
Issue #2396 argocd list command should have filter options like by pr…

### PR DESCRIPTION
**Pull request by AalokAhluwalia**
Addresses issue #2396 and introduces a filter by project name

### CODE REVIEW

**Comment by AalokAhluwalia** [comment]
Builds passing. Can I get a review on this issue?

**Review by jannfis — COMMENTED** [review]
Hi and thanks for your contribution! It looks good so far, I have two comments:

1. Maybe it would make sense to accept a list of projects in `--project`, separated by commas, as `FilterByProjects` apparently already supports a list of projects as argument. What do you think?

2. I wonder where the changes to `Gopkg.lock` come from, I think they shouldn't be part of this PR.

**Comment by AalokAhluwalia** [comment]
1) I think it makes sense to allow specifying multiple projects. I add this functionality.
2) I am new to go and was trying out some changes. I reverted the Gopkg.lock file

**Review by jannfis — APPROVED** [review]
Awesome, thanks for the changes. From my side this PR can be incorporated.

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
Merged!

**Pull request merged**
