### PR TITLE
fix: Update account.proto annotaion for gen grpc gateway

### PR DESCRIPTION
**Pull request by wei840222**
For /api/v1/account/can-i/{resource}/{action}/{subresource}
the subresource in path parm may have slash, so it need be a wildcard
ex: /api/v1/account/can-i/{resource}/{action}/{subresource}
may be /api/v1/account/can-i/projects/create/abc/abc-123
for now it will return 404

### CODE REVIEW

**Comment by wei840222** [comment]
do I need to run ```make openapigen``` before commit?

**Comment by jannfis** [comment]
You should run `make codegen` and check for any changes on your local checkout, commit them and push back.

**Comment by jannfis** [comment]
For more information, refer to https://argo-cd.readthedocs.io/en/stable/developer-guide/contributing/#generate-api-glue-code-and-other-assets

**Comment by ishitasequeira** [comment]
Thanks @wei840222  for the PR. Can you try to retrigger the checks using this doc:https://argoproj.github.io/argo-cd/developer-guide/ci/#can-i-retrigger-the-checks-without-pushing-a-new-commit ?

**Comment by wei840222** [comment]
re triggered

**Comment by pasha-codefresh** [comment]
hey @wei840222 could you please retrigger the checks?

**Comment by wei840222** [comment]
@pasha-codefresh 
Done thx

**Review by pasha-codefresh — APPROVED** [review]

**Comment by pasha-codefresh** [comment]
Thank you!

**Pull request merged**
