### PR TITLE
chore: bump kubectl version from 1.17.8 to 1.19.2

### PR DESCRIPTION
**Pull request by simonfr**
Checklist:

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Comment by wtam2018** [comment]
LGTM

**Comment by simonfr** [comment]
@wtam2018 semantic fixed, can you review this pr?

**Comment by wtam2018** [comment]
Since we build against kubernetes v1.18.8, I wonder if we should upgrade kubectl tool to the consistent version (v1.18.8).   @alexmt

**Comment by simonfr** [comment]
According to kubernetes official repository https://github.com/kubernetes/kubernetes latest stable version is v1.19.2. Where did you use 1.18.8 one ?
According to https://kubernetes.io/docs/setup/release/version-skew-policy/#kubectl kubectl 1.19 is compatible with kube 1.18 to 1.20 (pre-release)

**Comment by wtam2018** [comment]
I am looking at go.mod, we are depending on kubernetes 1.18.8.   I think either 118 or 1.19 kubectl is fine but just wonder if we should stay at the same version as kubernetes as in gomod.

**Comment by jessesuen** [comment]
We are actually attempting to move kubectl binary completely from Argo CD (https://github.com/argoproj/argo-cd/issues/4385), so i think the correct thing to do is to eventually remove this line completely, rather than keep it up-to-date.

**Comment by alexmt** [comment]
Closing it since we agreed to remove unused kubectl binary from Argo CD https://github.com/argoproj/argo-cd/issues/4385

**Pull request closed without merging**
