### PR TITLE
chore: Migrate to Go modules

### LINKED ISSUE #3194: Switch to Go Modules from Go Dep
# Summary

Migrate argo-cd repo to Go Modules.

# Motivation

https://github.com/golang/go/wiki/Modules
> In Go 1.14, module support is considered ready for production use, and all users are encouraged to migrate to modules from other dependency management systems.

This migration will speed up builds thanks to caching, and provide more flexibility by moving away from `$GOPATH`.

# Proposal

https://github.com/golang/go/wiki/Modules#how-to-install-and-activate-module-support

`$ go mod init` should be sufficient to migrate the information found in `Gopkg.lock`.
However, it might be wise to `$ export GO111MODULE=on` in the scripts if users keep their git repo inside `$GOPATH`.

I can test that on my side, and open a PR.

### PR DESCRIPTION
**Pull request by jannfis**
Fixes #3194
Supersedes #2327

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by alexmt — APPROVED** [review]
It is green! ✅

**Comment by jannfis** [comment]
It's green yes, but for some reason, some operations are noticeable slower with modules than with dep (i.e. codegen takes ~6 minutes with modules, before it took ~2) - I'm still investigating.

**Comment by jannfis** [comment]
Need to adapt Snyk as well, because `Gopkg.lock` is gone now.

**Comment by jannfis** [comment]
Good enough for now, next step is to move to GH actions.

**Comment by matthyx** [comment]
Awesome, thanks a lot!

**Pull request merged**
