### PR TITLE
fix: Policy/policy.open-cluster-management.io health check is broken (#20108)

### LINKED ISSUE #20108: Policy/policy.open-cluster-management.io health check is broken
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

When using https://github.com/argoproj/argo-cd/blob/master/resource_customizations/policy.open-cluster-management.io/Policy/health.lua i get an error of the following type:

> error setting app health: failed to get resource health for "Policy" with name "XXXX" in namespace "local-cluster": <string>:35: invalid value (nil) at index 1 in table for concat stack traceback: [G]: in function 'concat' <string>:35: in main chunk [G]: ?

I beleive I have narrowed down why this wasn't being caught by tests because it only seems to be an issue when the NonCompliant hit is AFTER the Compliant hit due to the way indexing and the way `table.getn` worked.

**To Reproduce**

1. Add https://github.com/argoproj/argo-cd/blob/master/resource_customizations/policy.open-cluster-management.io/Policy/health.lua to your resource customizations
2. create a policy that has a Compliant status then a NonCompliant status, then a Compliant status
3. get the error

**Expected behavior**

Status should be correctly returned such as:

> NonCompliant templates: validate-openshift-gitops-applications2, inform-gatekeeper-audit-argocd-applications-healthy-and-sycned

**Screenshots**

N/A

**Version**

```shell
argocd: v2.12.3+6b9cd82
  BuildDate: 2024-08-27T15:33:41Z
  GitCommit: 6b9cd828c6e9807398869ad5ac44efd2c28422d6
  GitTreeState: clean
  GoVersion: go1.23.0
  Compiler: gc
  Platform: darwin/arm64
WARN[0000] Failed to invoke grpc call. Use flag --grpc-web in grpc calls. To avoid this warning message, use flag --grpc-web.
argocd-server: v2.11.6+089247d
  BuildDate: 2024-07-23T00:41:35Z
  GitCommit: 089247df0f15e64813d00a2d1271a2095feecad4
  GitTreeState: clean
  GoVersion: go1.21.11 (Red Hat 1.21.11-1.module+el8.10.0+21986+2112108a)
  Compiler: gc
  Platform: linux/amd64
  ExtraBuildInfo: {Vendor Information: Red Hat OpenShift GitOps version: v1.13.1}
  Kustomize Version: v5.2.1 unknown
  Helm Version: v3.14.4+g81c902a
  Kubectl Version: v0.26.11
  Jsonnet Version: v0.20.0
```

**Logs**

If something other then the error message is needed let me know.

### PR DESCRIPTION
**Pull request by itewk**
Fixes #20108 Policy/policy.open-cluster-management.io health check is broken

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [n/a] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [no] Does this PR require documentation updates?
* [n/a] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [n/a] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [n/a] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by crenshaw-dev — APPROVED** [review]

**Comment by crenshaw-dev** [comment]
@itewk thanks for the PR! If you want this cherry-picked back to 2.10-2.12, you'll need to open PRs directly against those branches.

It's also possible that the failed cherry-picks are because the health check simply didn't exist for those versions.

**Comment by itewk** [comment]
@crenshaw-dev thanks! i checked that this health check didn't exist until 2.13 hence the cherry pick not working. I assume we dont want to backport the entire health check? If we do, i'll do that. let me know.

**Comment by crenshaw-dev** [comment]
Yep, let's just stick with 2.13. Thanks!

**Pull request merged**
