### PR TITLE
fix: Bitbucket Cloud PR Author is processed correctly (#20769)

### LINKED ISSUE #20769: Pull Request generator not working for Bitbucket Cloud
Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Using the Pull Request generator with Bitbucket Cloud results in the error

```
error listing repos: error unmarshalling json to type '[]BitbucketCloudPullRequest': json: cannot unmarshal object into Go struct field BitbucketCloudPullRequest.author of type string
```

It looks like the error can be traced to adding the `author` field with the wrong type in [[1]](https://github.com/argoproj/argo-cd/pull/18974/files#diff-8523234aa497230c1a958d497fd318024e3659df83f15163537f2a4f98a43e77): it was added as a _string_ but in the Bitbucket Cloud API it's an _object_ [[2]](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-pullrequests/#api-repositories-workspace-repo-slug-pullrequests-get)

**To Reproduce**

Create an ApplicationSet with the Pull Request generator:

```yaml
spec:
  generators:
    - pullRequest:
        bitbucket:
          basicAuth:
            passwordRef:
              key: password
              secretName: argocd-controller-secret
            username: Srv-CICD-Robot
          owner: REDACTED
          repo: REDACTED
        filters:
          - branchMatch: .*/.*REDACTED.*/.*
        requeueAfterSeconds: 60
```

**Expected behavior**

The PR generator can parse the Bitbucket API response, where the `author` field is an object and not a string.

**Screenshots**

N/A

**Version**

```shell
argocd: v2.13.0+347f221
  BuildDate: 2024-11-04T12:09:06Z
  GitCommit: 347f221adba5599ef4d5f12ee572b2c17d01db4d
  GitTreeState: clean
  GoVersion: go1.23.1
  Compiler: gc
  Platform: linux/amd64
argocd-server: v2.13.0+347f221
```

**Logs**

```
error listing repos: error unmarshalling json to type '[]BitbucketCloudPullRequest': json: cannot unmarshal object into Go struct field BitbucketCloudPullRequest.author of type string
```

### PR DESCRIPTION
**Pull request by andrii-korotkov-verkada**
Fixes #20769

Author there is a struct, not a string. Use nickname from that struct as an author name.

Let's cherry pick to 2.11-2.13

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
LGTM!!

**Comment by ishitasequeira** [comment]
@andrii-korotkov-verkada seems like cherry-pick failed for 2.11 and 2.12. Would you be able to create cherry-pick PRs manually?

**Comment by andrii-korotkov-verkada** [comment]
@ishitasequeira, do you know how to fork specific tags? I've tried to find an option in my existing fork, but couldn't.

**Comment by andrii-korotkov-verkada** [comment]
Thanks! Looks like the author field for Bitbucket was added only in 2.13, that's why cherry pick failed. I think we can still do it, just would be more like adding a small feature.

**Comment by andrii-korotkov-verkada** [comment]
Ah, nvm, PullRequest doesn't have a field for Author either. Let's skip 2.11 and 2.12 then.

**Pull request merged**
