### PR TITLE
feat:  add disabled attribute to allow explicitly disabling automatic sync (#10070)

### LINKED ISSUE #10070: Allow explicit disable of autosync for applications
# What is the current behavior
Configuring an application to have no `automated` property within the `syncPolicy` property will turn autosync off once. This will not however enforce that autosync is off. You can manually turn autosync on through the ArgoCD website and it will not be automatically disabled again.

# Expected behavior
There should be a way to explicitly turn autosync off. If a user then turns it on through the website, it should (depending on the autosync policy of the parent application) be automatically turned off again.

Perhaps an `enabled` flag would make sense here, instead of just not configuring `automated` which is the current way. 

```yaml
  syncPolicy:
    automated:
      enabled: false
```

# Other info
Version: v2.4.7+81630e6
Helm: v3.8.1+g5cb9af4

### PR DESCRIPTION
**Pull request by richardjennings**
resolves #10070

Adds a disabled property to sync automated:
```
syncPolicy:
    automated:
      disabled: true
```

Disabled chosen over enabled due to boolean defaulting to false, disabled: false is the default and so backwards compatible.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

### CODE REVIEW

**Review by crenshaw-dev — CHANGES_REQUESTED** [review]
@richardjennings can you also update the docs on this page: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/

**Comment by richardjennings** [comment]
> @richardjennings can you also update the docs on this page: https://argo-cd.readthedocs.io/en/stable/user-guide/auto_sync/

done

**Comment by richardjennings** [comment]
@crenshaw-dev sorry I accidentally removed the @alexmt review request

**Comment by crenshaw-dev** [comment]
@richardjennings I think in order for this to solve the given use case, we need another PR to make the ApplicationSet controller support templating into boolean fields. That's non-trivial, but I'd be happy to point you in the right direction if you're up to it.

**Comment by crenshaw-dev** [comment]
Actually... I'm not sure that making the ApplicationSet controller handle _actual_ booleans is the way to go. 

Maybe we should just change this PR to make the `disabled` field a `StringOrBoolean` so that the ApplicationSet controller can handle it.

**Comment by crenshaw-dev** [comment]
I'm trying to find an example of StringOrBoolean in the Argo Workflows code base, but having trouble...

**Comment by richardjennings** [comment]
@crenshaw-dev I have been unable to think of a clean way to implement templating of ApplicationSpec booleans from the ApplicationSet directly. I am not sure StringOrBool is a thing.

The only potentially viable option I can see is an overrides property, for example.
```
template:
  override:
    syncPolicy:
      automated:
        enabled: {{ automated }}
  spec:
```

or 

```
template:
  override:
    syncPolicyAutomatedEnabled: {{ automated }}
  spec:
```

**Comment by richardjennings** [comment]
@crenshaw-dev I have reduced the scope of this PR to just adding a Disabled property to SyncPolicy.Automated. Making it possible to template booleans is a substantial change that I will work on separately.

**Comment by crenshaw-dev** [comment]
@richardjennings can we put this PR on hold until the boolean templating work is done?

I think AppSet is the only valid use case for this change. https://github.com/argoproj/argo-cd/issues/10070#issuecomment-1269097208

**Comment by pasha-codefresh** [comment]
@richardjennings i am closing it for now, please feel free to reopen it if you think it is still valid PR

**Pull request closed without merging**
