### PR TITLE
chore: Enable CI checks on PRs to release branches

### PR DESCRIPTION
**Pull request by jannfis**
Since we've moved to PRs for cherry-picking, I believe it makes sense to enable CI checks for those.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

### CODE REVIEW

**Review by 34fathombelow — COMMENTED** [review]
I absolutely agree this makes sense.  However I'm primarily concerned about the number of jobs and minutes used. We are [limited](https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits) by the total number of concurrent jobs running. 

Current number of jobs and time per event listed below:
| Event             | Jobs | Total time  |
|-------------------|--------|-----------------|
|Push               | ~12  |~120mins   |
| Pull_request | ~15  | ~120 mins |

We do have concurrency groups set on our workflows that help with this, but I'm not sure if our CI can handle it. We can try this, maybe extend the time in between cherry picks?  Also we need to be mindful that the total of allowed concurrent jobs is shared across the argoproj organization.

WDYT @jannfis @crenshaw-dev 

Should we also drop v1.23.3 from the e2e test, its was EOL 2023-07-28 ? That would also help with the number of jobs we use.
https://github.com/argoproj/argo-cd/blob/1f2810f11625a8c1173689a92c5a0676be85e75f/.github/workflows/ci-build.yaml#L364

**Comment by crenshaw-dev** [comment]
I'm not opposed to trying, but it's definitely something we should watch.

**Review by 34fathombelow — APPROVED** [review]

**Review by crenshaw-dev — APPROVED** [review]
Let's see how it goes. :-)

**Comment by crenshaw-dev** [comment]
Manually cherry-picked.

**Pull request merged**
