### PR TITLE
docs: Update Azure AD to Entra ID

### LINKED ISSUE #16868: Update documentation to reflect name change of Azure AD to Microsoft Entra ID
# Summary

Update documentation to reflect name change of Azure AD to Microsoft Entra ID:
https://learn.microsoft.com/en-us/entra/fundamentals/new-name

# Motivation

Motivation is to keep the documentation accurate and avoid any possible confusion to people setting up single sign for ArgoCD

# Proposal

How do you think this should be implemented?

Replace text occurrences 'Azure Active Directory' with 'Microsoft Entra ID' and occurrences of 'Azure AD' with 'Entra ID' in the file https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/user-management/microsoft.md

### PR DESCRIPTION
**Pull request by ryanpflynn**
Update user management documentation to reflect name change of Azure AD to Microsoft Entra ID:
https://learn.microsoft.com/en-us/entra/fundamentals/new-name

Closes #16868

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Review by PranitRout07 — COMMENTED** [review]
can you link the issue number here?

**Review by blakepettersson — CHANGES_REQUESTED** [review]
I think this generally makes sense - could we just have someplace where we have something like `(formally known as Azure AD)`, so it's clearer for users which do not know of the name change?

**Comment by ryanpflynn** [comment]
Issue Number is [16868](https://github.com/argoproj/argo-cd/issues/16868)

**Comment by ryanpflynn** [comment]
@blakepettersson I have added an admonition to the top of the document to call out the name change

**Review by blakepettersson — APPROVED** [review]

**Comment by blakepettersson** [comment]
@ryanpflynn LGTM, thanks!

**Pull request merged**
