### PR TITLE
docs: document built-in user limitations and workaround

### LINKED ISSUE #3105: Add security contacts to GitHub repo
# Summary

Add a security contacts file to this repo, as well as other repos within the argoproj org, and possibly to the website. For an example, see Kubernetes: https://github.com/kubernetes/kubernetes/blob/master/SECURITY_CONTACTS

# Motivation

Will let researchers know who to reach out to, and the preferred method of communicating sensitive issues that may require private (non-GitHub Issue) reporting.

### PR DESCRIPTION
**Pull request by alexmt**
PR documents security concerns related to the built-in users with recommendation to use SSO.

Closes https://github.com/argoproj/argo-cd/issues/3105

### CODE REVIEW

**Comment by jannfis** [comment]
Hm, I think the information related to security issues and known CVEs should be placed more prominently, like on the top level of the navigation - not "hidden" in the operator's manual.

**Comment by alexmt** [comment]
All CVEs are related to built-in users. We can add a warning in https://argoproj.github.io/argo-cd/operator-manual/user-management/ with the link to CVEs details. So anyone who attempts to configure local users should see information about security concerns.

@jannfis do you think it would be enough?

**Comment by jannfis** [comment]
> All CVEs are related to built-in users. We can add a warning in https://argoproj.github.io/argo-cd/operator-manual/user-management/ with the link to CVEs details. So anyone who attempts to configure local users should see information about security concerns.
> 
> @jannfis do you think it would be enough?

Well I think we should list all known and previous (mitigated) security issues on a single, rather prominent page, and then link from the documentation of the affected components to that central source. I'd like to see that page linked in the top level navigation, maybe between "FAQ" and "Support".

This would enable our users to get an easy overview about the currently known CVEs without having to browse through the docs, and also would motivate us to speed up their mitigation. I think this is the transparency we should give to our users, because they might be running ArgoCD in rather sensitive environments.

**Comment by jannfis** [comment]
Maybe we can move https://argoproj.github.io/argo-cd/operator-manual/security/ to the top level, and insert known and past issues in a separate section.

**Comment by alexmt** [comment]
Moved CVEs description into a separate document and added top-level link between FAQ and Support. Let me know what you think, please.

**Review by jannfis — APPROVED** [review]
Awesome, @alexmt! Thank you. This looks much better to me!

**Review by edlee2121 — APPROVED** [review]

**Pull request merged**
