### PR TITLE
fix: Disable Transparent Huge Pages (THP) for redis pods (#5195)

### LINKED ISSUE #5195: Disable Transparent Huge Pages (THP) for redis pods
If you are trying to resolve an environment-specific issue or have a one-off question about the edge case that does not require a feature then please consider asking a question in argocd slack [channel](https://argoproj.github.io/community/join-slack).

Checklist:

* [x] I've searched in the docs and FAQ for my answer: https://bit.ly/argocd-faq.
* [x] I've included steps to reproduce the bug.
* [x] I've pasted the output of `argocd version`.

**Describe the bug**

Redis screams on startup about THP

**To Reproduce**

1. Restart the redis deployment (e.g. by upgrading argocd)
2. Check the logs for the redis pod(s)

**Expected behavior**

No complaints about THP

**Screenshots**

**Version**

```shell
{
    "Version": "v1.9.0+5d6b321",
    "BuildDate": "2021-01-05T21:08:56Z",
    "GitCommit": "5d6b3216f559c76ee73d85b5121d6004b5554613",
    "GitTreeState": "clean",
    "GoVersion": "go1.14.12",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KsonnetVersion": "v0.13.1",
    "KustomizeVersion": "v3.8.1 2020-07-16T00:58:46Z",
    "HelmVersion": "v3.4.1+gc4e7485",
    "KubectlVersion": "v1.17.8",
    "JsonnetVersion": "v0.17.0"
}
```

**Logs**

```
1:C 06 Jan 2021 02:19:16.025 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 06 Jan 2021 02:19:16.105 # Redis version=5.0.8, bits=64, commit=00000000, modified=0, pid=1, just start
ed
1:C 06 Jan 2021 02:19:16.105 # Configuration loaded
1:M 06 Jan 2021 02:19:16.201 * Running mode=standalone, port=6379.
1:M 06 Jan 2021 02:19:16.201 # Server initialized
1:M 06 Jan 2021 02:19:16.201 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel
. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo neve
r > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to reta
in the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 06 Jan 2021 02:19:16.202 * Ready to accept connections
```

**Proposal**
https://stackoverflow.com/questions/45279477/disable-transparent-huge-pages-from-kubernetes

### PR DESCRIPTION
**Pull request by jsoref**
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>

closes #5195?

(This isn't tested)

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

### CODE REVIEW

**Review by jannfis — CHANGES_REQUESTED** [review]
I have a couple of objections to this change:

* Using `hostPath` mounts is usually not a good practice, and is disabled by pod security policies on many Kubernetes clusters
* Changing something on the host's (that's the node) `/sys` filesystem is possibly (very) dangerous, and will affect all workloads on that node 

Also, the Redis startup warning is just a warning. It probably doesn't have much impact on the Argo CD's cache workload, but that's just my gut feeling. Benchmarks, anyone? 

I feel that we could give users a hint in the documentation of how to suppress the warning, but not make this (potentially dangerous) change, that might not work on a large amount of K8s clusters out there, by default.

**Comment by jsoref** [comment]
Would an optional replicaset that disabled the feature and had a label and anti thing for items without a certain label + a thing on the deployment that favored that label work?

**Comment by jannfis** [comment]
I think that this is a perfect use-case for an optional Kustomize overlay, but we should not render it out and provide another install.yaml by default.

A good idea would be, that we ship some useful (but very environment specific) Kustomize overlays as ready-to-use examples, so that people can easily build their own installation manifests with the pieces they need.

**Comment by jsoref** [comment]
I don't speak kustomize (and we're a helm shop)... should we just add this to the issue and close this PR?

**Pull request closed without merging**
