### PR TITLE
feat: support super lightweight json unmarshalling as proposed in 17130

### PR DESCRIPTION
**Pull request by wilsonwang371**
Use ujson to partially parse json data. since ujson is small, we just include its source inside argocd repo.

Fixes [Issue: #17130]

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### CODE REVIEW

**Comment by wilsonwang371** [comment]
enhancement proposal: https://github.com/argoproj/argo-cd/issues/17130

**Comment by wilsonwang371** [comment]
Tested on my laptop. It is significant faster than json.Unmarshal and fastjson.ParseBytes()

img_v3_0282_4853af96-893f-4cc4-aeee-2b64398eaf5h

**Comment by wilsonwang371** [comment]
@crenshaw-dev

**Comment by wilsonwang371** [comment]
We did a cluster upgrade. We can see ManagedResources() is running faster now.

image

**Comment by wilsonwang371** [comment]
@ashutosh16

**Comment by blakepettersson** [comment]
IMO I think it'd be helpful to have a benchmark in this PR, comparing this approach with the status quo, and perhaps marshmallow and fastjson (#17172)

**Comment by wilsonwang371** [comment]
all following discussions are in #17802

**Pull request closed without merging**
